### ISSUE TITLE
EDDI 3.1.2 Not logging into Frontier API

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1005]
## Steps to reproduce.

After Horizons update on Dec 11, 2018 EDDI no longer logs into Frontier API.

1. Open EDDI, go to Frontier API, enter credentials, click on Next
2. Unable to login. This is usually a temporary issue with Frontier's services, try again later.

## Expected
Would be able to login

## Observed
Unable to login. This is usually a temporary issue with Frontier's services, try again later.

## Investigation
Came here for answers.

**Comment by incryptx** [comment]
So, when will this be fixed?

**Comment by philgschmidt** [comment]
Still fails. I went to the Frontier site, erased and retyped my login and it worked. Went to EDDI , used the same credentials and it failed. Any updates on this?

**Comment by Tkael** [comment]
Check #1069. We haven't forgotten about this issue.
