### ISSUE TITLE
(3.3.0-rc1) homesystem crashing

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#1014]
## EDDI version in which issue found
3.3.2-rc1 standalone

## Steps to reproduce

1. try tu write homesystem or squadron system
2. crash of EDDI with use of upper case, name not recognise with lower case

**Comment by Tkael** [comment]
I can confirm the casing issue, but I don't see a crash with uppercase. Please indicate the name you are trying to enter for your home system or squadron name?

**Comment by StivlWrith** [comment]
the problem to change now (due to the online return of EDSM?). If you type the name of the system in lowercase, it is not found, you must type the first letter in uppercase and the rest in lowercase it is found.
try with Sol, Shinrarta Dezhra and Eotienses
If you write just Shinrarta, EDDI find nothing
