### ISSUE TITLE
Exceptions during scanning, no data going out to EDDN

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#1015]
## EDDI version in which issue found
3.3.0-rc1 standalone

## Steps to reproduce

Activate EDDN responder, jump to a system, locate all planets via FSS, then proceed to probe them.  Look at the log file afterwards.

## Expected
Messages going out to EDDN, no errors in logfile

## Observed
Various error messages in the log file, no messages going out to EDDN (according to Bravada Cadelanme on #EDDI)

## Investigation
EDDI logs (restarted once just in case the EDDN responder only comes alive after a restart) and game journal attached
[eddi.log](https://github.com/EDCD/EDDI/files/2689666/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/2689667/eddi1.log)
[Journal.181218090829.01.log](https://github.com/EDCD/EDDI/files/2689669/Journal.181218090829.01.log)

**Comment by richardbuckle** [comment]
This was resolved in 3.3-rc2.
