### ISSUE TITLE
Cannot Log in into Frontier API

### ISSUE THREAD

**Issue by Darkae40** [EDCD/EDDI#1016]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1.  There was storm last week and my computer had a power surge, so in essence i had to do a computer restore.  I have re downloaded EDDI along with voice attack and other things, but for some reason i am not able to log into Frontier API now.  My Status states that the Frontier API connection not operational.  I have a buddy that plays as well and he is not having any issues.  

## Expected
I would like to access the Frontier API to continue playing Elite Dangerous i really enjoy the tool.

## Observed
Just not allowed to login, i get the message "Unable to log in. this is usually temporary issue with Frontier's service, please try again later"  i have been getting this message since Saturday.

## Investigation
I have moved files from my old backup and it still does not work, i have uninstalled and reinstalled.

**Comment by Darkcyde13** [comment]
This has been reported a dozen times already and talked about in the forums.  Frontier changed the authentication and didn't let any 3rd party tool authors know in time to do anything about it, hence it doesn't work for the time being.  This also applied to other tools like EDDB.

EDDI will work fine without it, but here's a quote from Verticalblank…

> Frontier API disabled
> 
> This has been disabled for the time being, due to changes that Frontier made to the authentication protocol without any transition period.
> Unfortunately this means that EDDI is temporarily blind to market, outfitting and shipyard data. We will rectify this in EDDI 3.3.1 by reading the local journal files, but that will require commanders to visit the screens in question in-game.

**Comment by richardbuckle** [comment]
Closing as duplicate.

**Comment by philgschmidt** [comment]
ummm

reopened.

EDDI was working until today. Update 3.3.5 fails to connect to the frontier authentication server again,.

**Comment by Tkael** [comment]
There was some sort of weirdness this week with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by Tkael** [comment]
Nevermind. Looks like we misconfigured something with todays release. Version 3.3.6 released to correct it.
