### ISSUE TITLE
EDDI not properly subtracting Donation missions from mission count

### ISSUE THREAD

**Issue by darth-crunchus** [EDCD/EDDI#1018]
EDDI 3.3.0-rc1 (running in conjunction with VoiceAttack and HCS Voice Packs)

## Steps to reproduce

1. Start EDDI and Elite: Dangerous
2. Dock at station you wish to increase your standing with a faction
3. Go to mission board and scroll to faction doling out "Donate # Credits to the Cause" missions
4. Accept one of the credit donation missions
5. Mission count increments
6. Complete credit donation mission

## Expected
Decrement of mission count

## Observed
Mission count stayed the same and incremented with each subsequent Donate Credits to the Cause mission accepted and turned in until I had 10 missions reported but only two missions in Transactions.

## Investigation
Have not done any investigation, at least not yet.

**Comment by Hoodathunk** [comment]
Please provide all matching 'Mission accepted' and 'Mission completed' events from the Journal log for all missions in question and I'll take a look.

**Comment by darth-crunchus** [comment]
Yes, they were; I had to let them 'expire' before they disappeared, but the odd thing is, EDDI didn't acknowledge them as having been completed.  But I'll see if I can't dig them up.  Here ya be.  Is there anything else you might need?  I don't have a log for EDDI.  Probably something I need to start doing for just this particular reason.

[Donation Mission Journal Events.txt](https://github.com/EDCD/EDDI/files/2696758/Donation.Mission.Journal.Events.txt)

**Comment by Tkael** [comment]
EDDI keeps some log files at `%appdata%/EDDI`.

**Comment by darth-crunchus** [comment]
Well, here's the log for the day in question (12/18/2018)

[eddi9.log](https://github.com/EDCD/EDDI/files/2699542/eddi9.log)

**Comment by Hoodathunk** [comment]
Finally got back into the bubble and was able to test myself in Debug... Nope, not resolved in rc2.

Looks like FDEV changed 'Donation' key to a string and added a 'donated' key with the the donation value.

I've created a hotfix with an accompanying unit test which verified the fix before/after.

We'll push the hotfix into the version. Thanks @darth-crunchus for your report.

**Comment by darth-crunchus** [comment]
Hey, not a problem, you're quite welcome!  EDDI is quite possibly one of my favorite apps to have among my crew.  Sorry for the sparse contact; been a bit of a busy week.
