### ISSUE TITLE
[IDEA] add english/original script button on edit script window

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#1028]
When you do large changes in existing scripts, users using other language, it's possible to we have a lot of mistakes if variables changes or something like that.

It's possible to add some other button like "compare to Default" (that compare with eddi.es.json in case of Spanish config) but that compare with script in eddi.json. Possible button name can be "Compare with original" or "Compare with English" i don't know.

Or maybe if original script has some change, you can add some alert icon to revise.

I appreciate any idea with this. Thank you for your effort.

**Comment by Tkael** [comment]
Added to our notes for issue #523. 
The change log we publish with our updates is probably the best resource for learning about changes being made to existing scripts.
Thanks,
