### ISSUE TITLE
Ship Transfer Initiated event not triggering

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#103]
In Ship Transfer in ED, select a ship to transfer to your current location.  This should trigger the 'Ship Transfer Initiated' event script, but it does not.

Event logged in Journal:
`{ "timestamp":"2017-09-24T12:31:38Z", "event":"ShipyardTransfer", "ShipType":"Asp", "ShipID":2, "System":"CD-34 9020", "Distance":145.314835, "TransferPrice":127713 }`

Retested with a test-sidey, and got the same result. No speech.

**Comment by Tkael** [comment]
This was throwing an exception because the transfer time was missing from the 2.3 data. Fixed for next release. Thanks.
