### ISSUE TITLE
Syntax highlighting in Cottle

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1032]
## EDDI version in which issue found
3.3.1

## Expected
Syntax highlighting

## Observed
No syntax highlighting

## Investigation
NotePad++ allows users to define custom `User Defined Languages` via Scintalla for use with Notepad++. These appear to allow syntax highlighting for more unique / unusual languages. If this can be adapted to work in EDDI's edit windows then it may serve as a basis for syntax highlighting.
[NotePad++(EDDI Script).zip](https://github.com/EDCD/EDDI/files/2704950/NotePad%2B%2B.EDDI.Script.zip)
http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files
https://archive.codeplex.com/?p=scintillanet

**Comment by richardbuckle** [comment]
Worth a look. New repo is https://github.com/jacobslusser/ScintillaNET

I always do some due diligence before taking on a big dependency like this, as it is tantamount to taking on a dev that you have no control over. Factors I consider:

* Code quality
* Health assessment for Issue reports on GitHub including response time
* Assessment of open and closed PRs
* Most importantly of all, exit strategy if it doesn't work out (possibly after some time and code churn).

**Comment by richardbuckle** [comment]
Should we go with this, please allow me to set it up as I am very well versed in Git submodules.

**Comment by Tkael** [comment]
By all means. Let us know if you think it'd be feasible.

**Comment by Tkael** [comment]
When an exception is thrown from a script, the exception includes the specific line number where the script failed. If line numbers were displayed in the UI, we could also improve our verbal script error responses to indicate the specific line that threw the exception.

**Comment by richardbuckle** [comment]
Noted, thank you. I was just about to take another look at Scintilla and assess the amount of work it would take, as this sort of thing is very much up my alley.

**Comment by Tkael** [comment]
Excellent. :-)

**Comment by richardbuckle** [comment]
I am looking at the following:

1. Use [ScintillaNET](https://github.com/jacobslusser/ScintillaNET) with [WindowsFormsHost](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.windowsformshost)
2. Use [this wrapper of the above](https://github.com/Stumpii/ScintillaNET.WPF) -- last update 2 years ago.
3. Use [AvalonEdit](http://avalonedit.net/)

See also [this](https://www.codeproject.com/Articles/1025495/Best-Text-Editor-Component-for-NET-WPF-Developers).

Right now AvalonEdit is looking attractive, but I want to test it by spinning up a toy WPF Cottle editor.

**Comment by richardbuckle** [comment]
At first glance Scintalla looks better: https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Syntax-Highlighting

**Comment by richardbuckle** [comment]
https://github.com/jacobslusser/ScintillaNET/wiki/User-Submitted-Recipes

**Comment by Tkael** [comment]
I was leaning towards AvalonEdit. That said, any of the above look like they would be viable.

**Comment by richardbuckle** [comment]
Thanks for that. This one is also useful: https://stackoverflow.com/questions/8577627/scintillanet-vs-avalonedit-for-providing-scripting-interface-for-a-wpf-applicati?rq=1

I'm still a bit on the fence myself and I think I'm going to try both in a simple toy project and see how I get on. I think it's worth taking the time to evaluate both hands-on.

**Comment by richardbuckle** [comment]
Noted: https://blackfalconsoftware.wordpress.com/2015/09/03/best-text-editor-component-for-net-wpf-developers/

**Comment by richardbuckle** [comment]
Useful info for implementing the diff view in AvalonEdit.

**Comment by Tkael** [comment]
For reference, an example .xshd file for c#: https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Highlighting/Resources/CSharp-Mode.xshd
