### ISSUE TITLE
you have a litmpet controller installed, but got now limpets

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#1034]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

V3.3.1

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

buy limpets and launch

## Expected
get no limpet warning

## Observed

I get the voice message "you have a litmpet controller installed, but got now limpets"

**Comment by Tkael** [comment]
More detail needed. Did you start EDDI before or after you purchased limpets? Does this always happen or is it something that you only noticed on the last play session? Please provide a copy of cargomonitor.json and the log frile from the play session (located at `%appdata%/EDDI`?

**Comment by Tkael** [comment]
Paging @Hoodathunk . Check the log, we're getting exceptions from the EDDI.cs `updateSquadronData` method.
@lwt-pressy This log doesn't include any information about the cargo monitor - it appears to be either incomplete or was closed before the cargo data was written?

**Comment by lwt-pressy** [comment]
btw - this test was done with the new version V3.3.2

**Comment by lwt-pressy** [comment]
1. cleared squadron details
2. closed eddi
3. closed elite
4. startet eddi
5. started elite

cargomonitor still empty. 

eddi.log from this start: 
[eddi.log](https://github.com/EDCD/EDDI/files/2706441/eddi.log)

Should the limpets also show up in the Cargo-Tab in EDDI or only in the file?

**Comment by lwt-pressy** [comment]
hmm, after the restart some deleted values for the commander tab is shown again. I deleted it again and now there are empty, so I do the lopp again. 

I also went to the nearby station sold all my limpets and bought them again.  
[eddi.log](https://github.com/EDCD/EDDI/files/2706448/eddi.log)

**Comment by Tkael** [comment]
How does cargomonitor.json look now?

**Comment by lwt-pressy** [comment]
The file cargomonitor.json and the tab is empty (file as above). 

I don't now if it helps:
* the system is a windows 10 pro all updates applied
* eddiscovery has always the correct cargo list (i'm running it parallel)
* even though the cargomonitor.json nevers seems to change, the file timestamp updates

btw - thanks for the greast tool. The additional infos per voice are quite helpfull while playing.

**Comment by Darkcyde13** [comment]
I notice you said you run VoiceAttack, but also EDDI as a standalone.  EDDI won't let you run two sessions at the same time, whichever runs second will pop up and error message.  I take it you have disabled the VA plug-in version?

**Comment by Tkael** [comment]
@hoodathunk it's sounding like an issue with the cargo.json parsing or cargo event? Thoughts?

**Comment by Hoodathunk** [comment]
Just bought a Limpet controller and 10 limpets.

Cargo.json:
```{ "timestamp":"2018-12-24T22:50:58Z", "event":"Cargo", "Vessel":"Ship", "Count":10, "Inventory":[ 
{ "Name":"drones", "Name_Localised":"Limpet", "Count":10, "Stolen":0 }
 ] }```

cargomonitor.json:
```{
  "cargo": [
    {
      "edname": "Drones",
      "stolen": 0,
      "haulage": 0,
      "owned": 10,
      "other": 10,
      "need": 0,
      "total": 10,
      "price": 101,
      "category": "Non-marketable",
      "haulageData": []
    }
  ],
  "cargocarried": 10
}```

And Cargo Monitor tab shows 10 limpets.

I sell the 10 limpets and all shows empty again.

**Comment by Tkael** [comment]
Ok. Is there anything further we can do to help troubleshoot @lwt-pressy's issue?

**Comment by StivlWrith** [comment]
I make a test, reactivate Cargo Monitor (because i don't use usualy) and I made 4 of them by synthesis and i see no change in cargomonitor.json. I return in station, buy drones and various commodities and my cargomonitor.json stay the same 
```
{
  "cargo": [],
  "cargocarried": 0
}
```
whe i lift off i had also the message about no limpet. I try with my EDDI in french and in english, and had the same result
this is my Cargo.json:
```
{ "timestamp":"2018-12-25T18:26:04Z", "event":"Cargo", "Vessel":"Ship", "Count":19, "Inventory":[ 
{ "Name":"bauxite", "Count":1, "Stolen":0 }, 
{ "Name":"coltan", "Count":1, "Stolen":0 }, 
{ "Name":"gold", "Name_Localised":"Or", "Count":1, "Stolen":0 }, 
{ "Name":"lepidolite", "Name_Localised":"Lépidolite", "Count":1, "Stolen":0 }, 
{ "Name":"drones", "Name_Localised":"Drone", "Count":15, "Stolen":0 }
 ] }
```

**Comment by lwt-pressy** [comment]
or can I do something to help to find the issue?

**Comment by Tkael** [comment]
Likely handled with #1053.
