### ISSUE TITLE
There is a problem with the Docking Denied Script. Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1042]
3.3.2

Unknown how to reproduce.

1. Created new "Personality"
2. Edited "Docking Denied"

## Expected
Tested script.

## Observed
There is a problem with the Docking Denied Script. Exception has been thrown by the target of an invocation.

## Investigation
Changed the script to "default". Still gives error. Changed the Active Personality to "Default" i.e. EDDI, still gives error.

I cannot find or fix this. The Docking Denied script still throws this error, no matter what I do now.

**Comment by incryptx** [comment]
Deleted New Personality, Now using default EDDI Personality. Error still being reported when "Testing" script. Using default script.

**Comment by Tkael** [comment]
Acknowledged. Will review once I'm back at my dev pc.

**Comment by Tkael** [comment]
The test event is using an old version of the event that is missing station type information. We'll update the test event.
