### ISSUE TITLE
Body Volcanism Report question

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1045]
## EDDI version in which issue found
V3.3.2 Standalone and under VoiceAttack

Another quick question really.  As parts of the Body Report have been split up into separate scripts, I've noticed something with the Body Volcanism Report.

I'm assuming these sections have been split up so that they can be executed at any time, independent of the main Body Report as they have the event and reportbody sections at the tops of each.  However, the Body Volcanism Report also has a check for reportVolcanism, which means that it will only ever work if executed from the full Body Report.

Is this an error, accidentally left over from the Body report rewrite? Or if they are all only to be called from the full Body report, then surely there is no need for the event/reportbody checks in each of them?

**Comment by Tkael** [comment]
Probably left over from the re-write. I wanted to make more complex portions of the report modular (mostly for easier legibility). I'll take a look once I'm back at my dev pc.

**Comment by Darkcyde13** [comment]
Ahh, ok.  So they are not intended to be used outside of the main Body Report script.  In which case they won't need the reportbody setup at the beginning of each, as that will already be set in the main script.

I've also found a few problems with other scripts, should I open them as separate issues per script?

**Comment by Tkael** [comment]
By making it modular, they could be called individually. I'd like each script to support being called individually.

Go ahead and open issues for any issues you see that warrant review.

**Comment by Tkael** [comment]
Darkcyde's script (for reference):
```

{_ Fetch from context }
{if event:
    {set reportbody to BodyDetails(event.name, system.name)}
}
{if !reportbody.name || reportbody.name = "": 
    {set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
}
{if !reportbody.name || reportbody.name = "": 
    {set reportbody to BodyDetails(state.eddi_context_body_name)}
}

{if !reportbody.name || reportbody.name = "":
    {_ If it's still not possible to get the body name...  _}
    I'm
    {OneOf("not sure","unsure")}
    {Occasionally(2,"of")}
    which body
    {OneOf("you are","you're")}
    {OneOf("asking about","referring to")}.

|else:
    {if (reportbody.volcanism && len(reportbody.volcanism) > 0):

        {if !body:
            {F("Body Name Tidy")}
            {body} has
        |else:
            {OneOf("Sensors detect", "This {body_type} has")}
        }

        {if reportbody.volcanism.type = "Geysers":
            {set amount to "numbers"}
            {set type to "geysers"}
        |else:
            {set amount to "levels"}
            {set type to OneOf("lava flows", "magma flows")}
        }

        {if reportbody.volcanism.invariantAmount = "Major":
            high {amount} of
        |elif reportbody.volcanism.invariantAmount = "Minor":
            low {amount} of
        }
        active {reportbody.volcanism.composition} {type}
        {Occasionally(2, "{OneOf('at', 'on')} the surface")}.
    }
}
```

**Comment by Darkcyde13** [comment]
That's true.  I always thought it didn't sound quite right, but I just couldn't put my finger on why. :)  I believe I copied that from the original default script, although it's been so long I can't rememeber.
