### ISSUE TITLE
M class Red Giant text 

### ISSUE THREAD

**Issue by Muczachan** [EDCD/EDDI#1047]
## EDDI version in which issue found
3.3.2

## Steps to reproduce
Scan a previously unexplored M class red giant star.

The text read is: "M_RedGiant-class red giant detected." Which reads "M underscore redgiant...". Maybe it should read something along the lines of "M class red giant star"?

**Comment by Tkael** [comment]
Noted. I'll take a look once I get back to my dev. PC.

**Comment by Darkcyde13** [comment]
This is because P() doesn't format(?) that text, it just reads it as-is.

`|elif reportbody.stellarclass = "M_RedGiant":
            {P(reportbody.stellarclass)}-class red giant {Occasionally(4, "that is expanding towards being a red super-giant")}`

 Results in "M_RedGiant-class red giant....".  As the class is already known, it easier to just use "an M class red giant ..." instead of using a variable.

**Comment by Muczachan** [comment]
OTOH, we know that red giant is M-class, cut it out?

**Comment by Darkcyde13** [comment]
Well, in my previous version of the script, it's like this, which I will probably keep:-

`|elif reportbody.stellarclass = "M_RedGiant":
        a {ringed} red giant
        {Occasionally(4, "that is expanding towards being a red super-giant")}`

{ringed} is a check earlier in the script to see if any star has rings.

**Comment by Muczachan** [comment]
Side question: not that it hurts here, but is it possible for a red giant to have a ring?

**Comment by Darkcyde13** [comment]
To be honest, I had no idea, but you never know what the StellarForge could come up with.  So I checked www.elitegalaxyonline.com, and it seems that there is at least one M class star with rings.  It's HIP 27773 C apparently.

A long time ago I saw other stars with rings, so I added it as an option to all star classes.  If there are no rings, it's just left blank, so it doesn't interfere with normal speech output.

**Comment by Muczachan** [comment]
Yeah, of course an empty string gets read properly ;-)
I just think giants eat any possible ring during the original expansion phase. But that's an astrophysics tangent.

**Comment by Tkael** [comment]
This appears to be a very rare type of stellar class that we don't have code to handle (usually we just see a stellarclass of "M"). 
I was able to find a journal entry in my logs where I've come across one:
```
{ "timestamp":"2017-06-10T21:12:13Z", "event":"FSDJump", "StarSystem":"NGC 1999 Sector AH-L b8-0", "StarPos":[479.281,-363.219,-859.250], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$SYSTEM_SECURITY_low;", "SystemSecurity_Localised":"Low Security", "JumpDist":44.979, "FuelUsed":4.732637, "FuelLevel":27.267363 }
{ "timestamp":"2017-06-10T21:13:00Z", "event":"Scan", "BodyName":"NGC 1999 Sector AH-L b8-0", "DistanceFromArrivalLS":0.000000, "StarType":"M_RedGiant", "StellarMass":0.257813, "Radius":317483168.000000, "AbsoluteMagnitude":10.467316, "Age_MY":12842, "SurfaceTemperature":2336.000000, "RotationPeriod":123571.242188 }
```

Other notables that I identified from my journals for review:
A_BlueWhiteSuperGiant: `{ "timestamp":"2016-11-20T06:24:30Z"	 "event":"Scan", "BodyName":"HD 164865", "DistanceFromArrivalLS":0.000000, "StarType":"A_BlueWhiteSuperGiant", "StellarMass":9.847656, "Radius":48338288640.000000, "AbsoluteMagnitude":-6.703156,  "Age_MY":500, "SurfaceTemperature":9864.000000, "RotationPeriod":2616417.250000 }`
M_RedGiant: `{ "timestamp":"2017-01-14T20:44:38Z"	 "event":"Scan", "BodyName":"Eafots LZ-H b10-0 C", "DistanceFromArrivalLS":84.801338, "StarType":"M_RedGiant", "StellarMass":0.281250, "Radius":334526816.000000, "AbsoluteMagnitude":10.402359, "Age_MY":12596, "SurfaceTemperature":2310.000000, "SemiMajorAxis":19912300544.000000, "Eccentricity":0.047341, "OrbitalInclination":-37.443687, "Periapsis":213.209183, "OrbitalPeriod":2504127.250000, "RotationPeriod":134570.281250, "Rings":[ { "Name":"Eafots LZ-H b10-0 C A Belt", "RingClass":"eRingClass_MetalRich", "MassMT":9.3125e+11, "InnerRad":6.3817e+08, "OuterRad":1.581e+09 } ] }`
F_WhiteSuperGiant: `{ "timestamp":"2017-06-10T16:53:33Z"	 "event":"Scan", "BodyName":"Mirphak A", "DistanceFromArrivalLS":0.000000, "StarType":"F_WhiteSuperGiant", "StellarMass":1.199219, "Radius":45292716032.000000, "AbsoluteMagnitude":-4.165558, "Age_MY":5112, "SurfaceTemperature":5681.000000, "SemiMajorAxis":23616777355264.000000, "Eccentricity":0.125006, "OrbitalInclination":-1.214016, "Periapsis":327.753387, "OrbitalPeriod":272055058432.000000, "RotationPeriod":20611270.000000 }`
K_OrangeGiant: `{ "timestamp":"2018-11-18T05:16:13Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"BD+48 738", "BodyID":0, "DistanceFromArrivalLS":0.000000, "StarType":"K_OrangeGiant", "StellarMass":0.738281, "Radius":7650499584.000000, "AbsoluteMagnitude":5.826706, "Age_MY":5138, "SurfaceTemperature":4394.000000,  "Luminosity":"III", "RotationPeriod":3592262.000000, "AxialTilt":-0.143237 }`

**Comment by Darkcyde13** [comment]
Wouldn't it just be easier to handle it in the script, like the older version of Star Report?
```
    |elif reportbody.stellarclass = "SuperMassiveBlackHole":
        a supermassive black hole
    |elif reportbody.stellarclass = "A_BlueWhiteSuperGiant":
        a {ringed} blue-white super-giant
        {Occasionally(4, "that is expanding towards being a red super-giant")}
    |elif reportbody.stellarclass = "F_WhiteSuperGiant":
        a {ringed} yellow-white supergiant
        {Occasionally(4, "that is expanding towards being a red super-giant")}
    |elif reportbody.stellarclass = "M_RedSuperGiant":
        a {ringed} red super-giant {Occasionally(4, "in its helium burning phase")}
    |elif reportbody.stellarclass = "M_RedGiant":
        a {ringed} red giant
        {Occasionally(4, "that is expanding towards being a red super-giant")}
    |elif reportbody.stellarclass = "K_OrangeGiant":
        {if ringed: a {ringed} |else: an} orange giant
        {Occasionally(4, "that is expanding as it heads towards the end of its life")}
    |elif reportbody.stellarclass = "RoguePlanet":
        a {ringed} rogue planet
```
Or are you thinking of handling it properly in the code so it's easier to use in custom scripts?

**Comment by richardbuckle** [comment]
Fixed unless I am mistaken.
