### ISSUE TITLE
EDDI Speech Responder: Make TTS voices assignable

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#105]
Assignable per personality, assignable via Cottle function, or assignable per ship role? As suggested in issue #75 .

**Comment by richardbuckle** [comment]
Once we increase our SSML support then it should be doable via SSML.

**Comment by Tkael** [comment]
that's an area where I haven't experimented yet. but a semi SayWithVoice() function ought to be possible. it would uses the same voice processing setting as the default voice.

**Comment by Tkael** [comment]
Some examples of how this might be implemented here: https://msdn.microsoft.com/en-us/library/jj127898.aspx?f=255&MSPPError=-2147217396

**Comment by richardbuckle** [comment]
PR merged
