### ISSUE TITLE
Cargo Monitor = only shows 3 or 4 different items

### ISSUE THREAD

**Issue by LaucianNailor** [EDCD/EDDI#1053]
## EDDI version in which issue found
3.3.2 (PC)

## Steps to reproduce

1.At Boltzmann Hub - buying 7 different item types up to 720 tonne capacity
2. first 3 (occasionally 4) item types are added to the cargo monitor tab, subsequent purchases do not appear 

## Expected
each separate cargo items shows

## Observed
first 3 items bought (occasionally 4) add to monitor, any additional items bought of a different type do not

## Investigation
repeated 6 times at the station and always duplicated

**Comment by Tkael** [comment]
Can you provide a copy of the player journal events and cargo.json? You'll find both in the Saved Games folder.

**Comment by LaucianNailor** [comment]
Cargo monitor currently only shows Coffee & Fish.


[Cargo.txt](https://github.com/EDCD/EDDI/files/2717106/Cargo.txt)

[Journal4065224.txt](https://github.com/EDCD/EDDI/files/2717107/Journal4065224.txt)

**Comment by Tkael** [comment]
Should be fixed by #1056.
