### ISSUE TITLE
Star Report  and reportbody.shortname

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1054]
## EDDI version in which issue found
v3.3.2 standalone and in VA

## Steps to reproduce
Set reportbody to event in the Star Report (as it already is)
Use reportbody.shortname

## Expected
reportbody.shortname to say "A" or "B" etc. in systems with multiple stars, or to return something if only one star.

## Observed
Always returns nothing. Empty string maybe?

## Investigation
I updated my Body Name Tidy Script to use reportbody.shortname but was getting the following error when scanning stars in multi-star systems.
```
There is a problem with the: Body Name Tidy script. Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
```
Due to the way the script works, it is fine with other bodies and single stars.

So I tried several things to see where the problem was.  I tracked it down to `{set reportbody to event}` in the Star Scanned event.  This event doesn't populate the 'system' variable, which I guess is needed to make the short name.

The Body Scanned event does populate this variable, so in the case of planets and moons, {set reportbody to event} followed by {reportbody.shortname} works fine.

I'm guessing that the short name is derived from simply removing the system name from the body name, much the same way I have been doing in my Body Name Tidy script.  However, with no system name, it results in an empty string.

Is there any way you can add the system name to the Star Scanned Event so that this will all work?  I know that for a lot of the time, the star name will be the same as the system name, but in multi-star systems, that's obviously not the case.  Where this would result in an empty variable, you could do what I have, and just call it 'The primary star'.

The only other alternative I can think of, is to use {set reportbody to BodyDetails(event.name, system.name)} instead, so that the reportbody.shortname (and reportbody.systemname) works when ued in the Star Report script.

**Comment by Tkael** [comment]
Correct, the system has to be set so that we can do a replacement from the system name.

**Comment by Darkcyde13** [comment]
OK, thank you.  I just thought it would be useful if .shortname returned the letter of a star's designation in multi-star systems, in the way it does with planets.

**Comment by Tkael** [comment]
Consolidating this into #1051.
