### ISSUE TITLE
Event and Details() property mismatches

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1055]
## EDDI version in which issue found
V3.3.2 standalone and under VA

## Steps to reproduce
Scan a body and use event.type

## Expected
Returns body type, like "Planet" or "Star".

## Observed
Returns scan type, "Body scanned" or "Star scanned".

## Investigation
I've gone out to do some exploring and while trying to refine and bug-check some of the Body reporting scripts, I've found that 'event.type' no longer matches the description in the help.

Setting reportbody to event, then using reportbody.type results in the scan type, not the body type.  Using BodyDetails(),type still returns the body type as expected.

**Comment by Tkael** [comment]
`event.type` is an undocumented variable that matches the name of the event.

**Comment by Darkcyde13** [comment]
Ah, OK, I think I understand.

So the 'event' object variables for the Body Scanned event (for example) are listed when you click the Variables button in the event's script window.  Where would I find the list of variables for the 'body' object?  Would I be correct in thinking that the 'body' object is derived from BodyDetails()?  If so, is there a list of all the possible variables for it (and others like it) somewhere?

**Comment by Darkcyde13** [comment]
Thanks Hoodathunk. :)  I'm just trying to get my head around why things are the way they are.  So I take it that the 'event' information is what the Journal gives when the event happens in game?  Where do the 'details' functions get their information from?  I first thought the API, but as that's not working at the moment, does that information come from EDDN or something like that, as well as the event?

**Comment by Tkael** [comment]
EDSM listens to EDDN broadcasts from commanders and makes that data available via its API. The `details` functions, in turn, are filled primarily from EDSM's API. 

The event object includes `atmospherecomposition` (singular), not `atmospherecompositions` (plural). In the interest of harmonizing the variables between both the `event` and `Body` object types, I'll submit a revision to change these to plural.

**Comment by Darkcyde13** [comment]
Cool, thanks Tkael!  I was aware of the singular version of atmosphere, but I've wanted to add back the full composition as an option, for which I've had to start using BodyDetails() only.  With your update, I'll be able to set things back to using 'event' again, like default.

I've also noticed that some of the variables between 'event' and 'body' have different names, yet are the same information (or appear to be).  For example 'axialtilt' in the event, but just 'tilt' in body.  I know it will be a low priority, but would it be possible to make the variables for events and their 'details' counterparts, be the same name?  If I knew anything about coding in C, I'd do it for the project myself so you guys didn't have to worry about it.

**Comment by Tkael** [comment]
give us the full list and we'll take a look at what we can do.

**Comment by Darkcyde13** [comment]
OK, I've had a look through the events, and the following are what I've found:-

```
Body Scanned / BodyDetails()
----------------------------
- distancefromarrival / - distance
- atmospherecomposition / - atmospherecompositions
- solidcomposition / - solidcompositions
- axialtilt / - tilt
- orbitalinclination / - inclination
- bodyclass / - planettype
```


```
Star Scanned / BodyDetails()
---------------------------
- distancefromarrival / - distance
```


```
Entered normal Space / Body Details()
-------------------------------------
- system / - systemname
- body / - name
- bodytype / - type
```


```
Glide / BodyDetails()
---------------------
- system / - systemname
- body / - name
- bodytype / - type
```


```
Location / BodyDetails()
------------------------
- system / - systemname
- body / - name
- bodytype / - type
```


```
Near Surface / BodyDetails()
----------------------------
- system / - systemname
- body / - name
```



As those last four events have the same 'discrepancies', may I suggest changing the events, and the BodyDetails() function, all to match the following for clarity?
```
- systemname
- bodyname
- bodytype
```

And then, to make all the above match, maybe also change the same three items in the 'Body Scanned' and 'Star Scanned' events?  This will give consistency across most of the events and functions that use those items.

Thank you for at least considering this for me. :)

**Comment by Tkael** [comment]
The tricky part is implementing this in a way that doesn't break preexisting scripts.

**Comment by Tkael** [comment]
We didn't document it because we didn't change the primary variable, but a number of these variables are actually published in both forms from the events. For example, you'll find that the ReportBody variables are compatible with the event for:
- distancefromarrival / - distance
- axialtilt / - tilt
- orbitalinclination / - inclination
- bodyclass / - planettype

This isn't true for all the items you listed, but it's a start. For these items, all we need to do is update the documentation so that the event and Details() properties are consistently named.

**Comment by Darkcyde13** [comment]
Ah ok.  Well, how about this for an idea then?

As it seems that you can have two variables that hold the same data, why not add the ones I suggested to the events and to BodyDetails() (or however you wish to name them) as additional to those that already exist?  Then, some time down the line, you end up removing the old ones, after people have had the chance to swap over to the new convention?

This way would mean that no script (default or custom) gets broken by the change, and it gives everyone time to update their own scripts.  You could then say that you intend to depreciate and remove the old versions in one or two versions (or months).  If it's too much of a pain to edit the code twice, how about just add the new names and just leave the old ones as is?

I feel that by unifying the names of variables that hold the same data, you would be able to shorten scripts, and potentially avoid possible confusion over what data those variables hold.

Meh, I'm just a neat-freak, and I prefer to keep things consistent over everything if possible. :D
