### ISSUE TITLE
Error in MissionCompleted script

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1079]
## EDDI version in which issue found
3.3.2 under VoiceAttack

1. Doing missions to get higher empire rank

## Expected
Eddi telling me that a have access to Cutter when I reach the rank of Duke

## Observed
Eddi told me that a have access to Cutter when I reached the rank of Marquis

## Investigation
The last couple of days I've been busy getting my rank up from Lord to Duke in order to gain access to the Cutter.

When I reached the rank of Marquis Eddi told me I got that access but that's one rank to soon.

I checked the speechresponder.out file and is said:
"your lordship, the Imperial Navy has promoted you to the rank of Marquis for your service to the Empire.
You have successfully completed the Assassination mission. Additionally, 5 units of Modified Embedded Firmware have been received.  Congratulations Commander J. Calvert (Joshua)! You have elevated your position within the Empire. You have been granted access to purchase the Imperial Cutter."

When I got to the rank of Count earlier this week it said I gained a permit for Facece and that's also one rank of.

Going back further when I got to Baron it didn't tell me I got access to the Imperial Clipper

The line in the ED journal when I got to Marquis said:
{ "timestamp":"2019-01-11T16:43:09Z", "event":"Promotion", "Empire":11 }

In the MissionCompleted script it says :
"|elif rank = 12:
        You have been granted access to purchase the Imperial Cutter"

but it also says:
{set rank to cmdr.empirerating.rank + 1}

So I guess that last line is the problem.
Marquis is rank 11 but Eddi adds 1 so it gives the line about the Cutter which it should give when the rank is Duke (12)

I'm going to delete that line so it should tell me I get access to the Cutter when I reach the rank of Duke but maybe you could check it in the default script for the lower ranks.

**Comment by richardbuckle** [comment]
Yes ranks in the if/else cascade are zero-based and should be kept as such. We shouldn't be adding 1 to them as you spotted. Also Achenar is mis-spelled.

@Tkael we also have "Empire promotion" and "Federation promotion" scripts, are they obsolete now? They named the new rank, according to the player's gender setting -- I'd like to retain that.

**Comment by Darkcyde13** [comment]
In my personality, I moved the rank reports to the respective 'promotion' events back in November '17, with all the correct (at the time) ranks and rewards.  I thought the promotion events were added because, on mission completion, the new rank had yet to be applied to the player when that event executed?  Is that no longer the case?

**Comment by Tkael** [comment]
I think I agree - the promotion details belong in the promotion scripts, not the mission completion scripts.
