### ISSUE TITLE
Incomplete sentence when swapping a module into an empty slot

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#108]
## Steps to reproduce

1. Have an empty optional slot in your ship
2. Swap an existing module into it

## Expected
Something like "You have swapped your 1-D, Intermediate Discovery Scanner into an empty size 2 slot."

## Observed
EDDI says "You have swapped the positions of a 1-D, Intermediate Discovery Scanner and a -,."

## Investigation
Here is the journal:
```
{
  "timestamp": "2017-09-25T00:30:02Z",
  "event": "ModuleSwap",
  "FromSlot": "Slot05_Size5",
  "ToSlot": "Slot09_Size2",
  "FromItem": "$int_stellarbodydiscoveryscanner_intermediate_name;",
  "FromItem_Localised": "D - Scanner",
  "ToItem": "Null",
  "Ship": "python",
  "ShipID": 8
}
```

**Comment by Tkael** [comment]
This is a new feature that we are adding for 2.4. Leaving the script bugged into release is not cool - I think this needs to be part of the 2.4.0 milestone.

**Comment by richardbuckle** [comment]
Good call, I agree.

**Comment by Tkael** [comment]
Bug zapped. Pull request sent.
