### ISSUE TITLE
Sothis says no stations despite other info being correct

### ISSUE THREAD

**Issue by Jagohu** [EDCD/EDDI#1080]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]
3.3.2

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
4 orbital stations, one planetary...
Don's Inheritance  L  1,694 ls
Newholm Station  L  1,539 ls
Sothis Mining  M  3,132 ls
Velinski Enterprise  M  614 ls
Vantage Point   L  113,405 ls

## Observed
[describe what happened instead]
No stations

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Please provide a copy of the relevant log? If there was an error somewhere in the chain, the log will help us identify it. Logs are located at `%APPDATA%/EDDI`.

**Comment by Jagohu** [comment]
No error in the log about this at all. There are a few errors, but nothing is created with this issue. If I say System Report when I'm in Sothis, the reply is: 

_Sothis is a Federation democracy supporting 420.000 people, Federation Unite! is the immediate power. There are no stations present in this system._

**Comment by Tkael** [comment]
I've been unable to replicate this issue (either via SystemDetails or by stepping through the code and reviewing outputs).
It's possible that you saw the result of a EDDB's server move earlier this week, but I don't think that would have had any effect on the dockable stations.
If you repeat the steps you took earlier, does Sothis still report that it has no stations?

**Comment by Tkael** [comment]
Unable to replicate, no additional reports. Closing - it was probably some sort of server blip.
