### ISSUE TITLE
Improve Galnet Catagory Regex matching

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1090]
## EDDI version in which issue found
3.3.2 Both VA and standalone
## Steps to reproduce

1. Galnet misclassifies Community Goal articles due to wording variance
2. Regex looks for "collect their rewards" ; Frontier has been using "collect your rewards" lately in text

## Expected

Article to be categorized a "Community Goal"

## Observed
Article categorized as generic "Article"

## Investigation
Proposed change;
Change Regex filter in EDDI\GalnetMonitor\GalnetMonitor.resx to `(collect \w+ rewards)` to catch all variations

**Comment by Tkael** [comment]
Thanks for the suggestion.
