### ISSUE TITLE
Mission numbering is confused

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1099]
## EDDI version in which issue found
3.3.4-b1

## Steps to reproduce
1. Start with no missions
2. Take a couple of missions

## Expected
EDDI says something like:

> You have accepted the community goal: Distant Worlds Mining Initiative. You have 1 mission.
> You have accepted the community goal: Distant Worlds Combat Initiative. This is your 2nd mission.

## Observed
EDDI says:

> You have accepted the community goal: Distant Worlds Mining Initiative. You have 0 mission.
> You have accepted the community goal: Distant Worlds Combat Initiative. This is your 0th mission.

## Investigation
Journals:
 ```json
{ "timestamp":"2019-01-19T00:57:35Z", "event":"CommunityGoalJoin", "CGID":568, "Name":"Distant Worlds Mining Initiative", "System":"Omega Sector VE-Q b5-15" }
{ "timestamp":"2019-01-19T00:57:37Z", "event":"CommunityGoalJoin", "CGID":569, "Name":"Distant Worlds Combat Initiative", "System":"Omega Sector VE-Q b5-15" }
{ "timestamp":"2019-01-19T00:57:59Z", "event":"CommunityGoal", "CurrentGoals":[ { "CGID":568, "Title":"Distant Worlds Mining Initiative", "SystemName":"Omega Sector VE-Q b5-15", "MarketName":"Omega Mining Operation", "Expiry":"2019-01-24T15:00:00Z", "IsComplete":false, "CurrentTotal":616089, "PlayerContribution":0, "NumContributors":2668, "TopTier":{ "Name":"Tier 11", "Bonus":"" }, "TopRankSize":10, "PlayerInTopRank":false, "TierReached":"Tier 9", "PlayerPercentileBand":100, "Bonus":1000000 }, { "CGID":569, "Title":"Distant Worlds Combat Initiative", "SystemName":"Omega Sector VE-Q b5-15", "MarketName":"Omega Mining Operation", "Expiry":"2019-01-24T15:00:00Z", "IsComplete":false, "CurrentTotal":1079185611, "PlayerContribution":0, "NumContributors":530, "TopTier":{ "Name":"Tier 8", "Bonus":"" }, "TopRankSize":10, "PlayerInTopRank":false, "TierReached":"Tier 1", "PlayerPercentileBand":100, "Bonus":100000 } ] }
```

**Comment by Tkael** [comment]
That's easy enough to provide without making a numbered list.

**Comment by Hoodathunk** [comment]
There is no numbered list, it just states the count.

jgm put us into this weird place of counting community goals as a mission... which they aren't.

Let me ponder this to come up with a better solution.

**Comment by Hoodathunk** [comment]
I looked at this a bit more. There is a limit of 20 missions, which Community Goals do not count toward.

It's a simple change in the personality script to not state the number of accepted missions when 'event.communal' is true.

**Comment by Tkael** [comment]
Merged @Hoodathunk's fix. Closing.
