### ISSUE TITLE
Ship exchange script doesn't get Name of old Ship

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#1106]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

v3.3.4-b1, standalolne

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

When swaping ships in the shipyard, the old ship is not announce by namem, like "storing federal [underscode] corvette"

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

Worked fine in last version and all ships are correctly shown in shipyard. It happens on every swap. The new ship is always addresed correctly.

**Comment by Tkael** [comment]
I'm having trouble replicating this issue.
Is it still occurring?
Do both ships appear in your shipyard?
Are you logged in to the Frontier API?

**Comment by lwt-pressy** [comment]
It happens everytime i swap ships. All ships are in the shipyard. I'n not logged in to the Frontier API. I never was logged in the API, because I dislike entering my credentials in 3rd party tools (sorry no offence mend).

**Comment by lwt-pressy** [comment]
hm, I didn't want to close ti.

**Comment by Tkael** [comment]
The whole point of the new Frontier API is that you don't have to give us your credentials anymore. 
Does it happen with all ships in your shipyard?
Your shipyard configuration is saved to `%appdata%/EDDI/shipmonitor.json`. If you move your current shipmonitor.json then restart EDDI, EDDI will rebuild your shipyard as you play. Please try this and let me know if the problem recurs?

**Comment by lwt-pressy** [comment]
It happens with all 11 ships I currently have access to (the other are far scattered in the galaxy). I will try it with deleting the shipmonitor.json this evening.

**Comment by lwt-pressy** [comment]
I delete shipmonitor.json, startet EDDI, signed in to the new Frontier API. Worked wit no problems. Then I started E:D. 

These are the things I observed:
* All Ships where loaded when I logged in into E:D, which is nice. Missing where only the ID (CallSigns) of the Ships.
* When I now switched Ships there is a 60/40 Chance, that the Name is used for the old ship. The other times still this technical name (e.g. federal "underscore" corvette) is used,
* It seems not ship related. I did a loop swaping between my federal corvette an krait mk2 and it still was 60/40 Chance for the name. So sometimes my federal corvette was addressed as "LWT Bandit" (Name) somtime as federal "underscore" corvette. Same happend with the krait.
* flying with the ships the fuel warning was quite unreliable. Quite often I got a warning, thar my fuel was almost depleted or below 20% even thoug my fuel was ingame still around 50%.

**Comment by Tkael** [comment]
Please provide a copy of your most recent journal file (located in your `[Saved Games]/Frontier Developments/Elite Dangerous/` folder)? It sounds like EDDI has an issue with some of the data being passed about the current ship configuration.

**Comment by Tkael** [comment]
I think I found enough information to make an improvement. https://rollbar.com/EDCD/EDDI/items/11363/occurrences/64537533570/
