### ISSUE TITLE
EDDI hangs when trying to input Home System

### ISSUE THREAD

**Issue by darth-crunchus** [EDCD/EDDI#1109]
## EDDI version in which issue found
3.3.4-b1 Primarily running under Voice Attack, but currently trying to setup under stand alone

## Steps to reproduce

1. Start EDDI, or from voice Attack, issue command, "Configure EDDI"
2. Click "Commander Info" Tab
3. Attempted to enter Home System "Asellus Primus"

## Expected
I expected EDDI to allow me to input my Home System

## Observed
EDDI locked up completely, requiring it to be closed through Task Manager

## Investigation
All I know is that this issue was not present in any previous versions of EDDI.

## Additional Information
I was unable to link the Frontier API in 3.3.3, but had no such issue in 3.3.4-b1  When using with Voice Attack, I'm also experiencing the "Sorry, Commander, I've lost track of things" spiel upon plugin initialization.  This is before launching Elite Dangerous.

**Comment by Tkael** [comment]
Looks like EDDI is being a little too aggressive in looking up star systems as soon as you type. I'm limiting the lookup to require at least 3 characters, but in the meantime you can input your home system by writing it somewhere else and then pasting the complete system name into EDDI.

**Comment by exgoaltender** [comment]
Doesn't seem to recognize a number of other systems - 'LHS 20' or 'HR 6421' for example... just shows a red box

**Comment by exgoaltender** [comment]
Doesn't seem to recognize a number of other systems - 'LHS 20' or 'HR 6421' for example... just shows a red box. Tried typing manually and copy/paste

**Comment by harakiwi** [comment]
Can confirm.
Has anyone managed to enter Shinrarta Dezhra? EDDI just deletes it every time i try to type or copy/paste it. Is it because of the space in the name?

**Comment by Tkael** [comment]
Pasting `Shinrarta Dezhra` works for me.

**Comment by Hoodathunk** [comment]
Ditto on pasting.

I've seen this happen when the sqlite database gets corrupted and returns zero on # bodies and null on stations which, in turn, results in exceptions. Same issue with squadron system HQ.

Recommend moving/deleting the EDDI.sqlite file and see if that improves.

Meanwhile, I'll look into protecting against those particular cases.

Incidentally, @Tkael , the >=3 char check is placed in code where validation check is now precluded, moving check to another method corrects problem. I will include fix and 'protections' in your branch/PR.
