### ISSUE TITLE
EDDI 3.3.4-b1 cannot log into Frontier API 

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1110]
## EDDI version in which issue found
3.3.4-b1 Standalone
## Steps to reproduce

1. Launch EDDI standalone
2. Select the "Frontier API" tab
3. Select the "Log In" button

## Expected
Web page to log into Frontier
## Observed
EDDI silently crashes
## Investigation
Nothing logged in eddi.log
Throws Windows Application Error Event 1026 followed by Event 1000, details below

Application Error Event 1026
`Application: EDDI.exe Framework Version: v4.0.30319 Description: The process was  terminated due to an unhandled exception. Exception Info:  EddiCompanionAppService.EliteDangerousCompanionAppAuthenticationException at  EddiCompanionAppService.CompanionAppService.Login() at  Eddi.MainWindow.companionAppClicked(System.Object,  System.Windows.RoutedEventArgs) at  System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object,  System.Windows.RoutedEventArgs) at  System.Windows.EventRoute.InvokeHandlersImpl(System.Object,  System.Windows.RoutedEventArgs, Boolean) at  System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject,  System.Windows.RoutedEventArgs) at  System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs) at  System.Windows.Controls.Primitives.ButtonBase.OnClick() at  System.Windows.Controls.Button.OnClick() at  ---`

Application Error Event 1000

`EDDI.exe 
   1.0.0.0 
   5c428c2b 
   KERNELBASE.dll 
   10.0.17763.134 
   c30ded87 
   e0434352 
   0011ab32 
   2ee0 
   01d4b10c4e5d3d8c 
   C:\Program Files (x86)\VoiceAttack\Apps\EDDI\EDDI.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   6d80eec3-28f4-4608-9efb-7740430215c2 
    `

EventData
--

**Comment by Tkael** [comment]
Were you able to log in previously in 3.3.4-b1? Or is this the first time you've tried with this version of the application?
Please try... 
1. reattempting login (in case the exception was due to an unexpected server response from the Frontier API server)
2. closing EDDI 
3. navigating to `%appdata%/EDDI`
4. deleting `CompanionAPI.json`
5. restarting EDDI
6. reattempting login
Let us know how it goes.

**Comment by Redrayg** [comment]
Have the same problem.  This has been re-curring since 3.3.1.  Uninstalled EDDI, donwloaded and installed latest version, still the same.  There is no 'CompanionAPI.json' file in my %AppData%/EDDI location.
Gary

**Comment by Tkael** [comment]
To confirm, you are using the installer rather than building from source?
@richardbuckle Possibly an issue with the `createAndRememberChallenge()` method?

**Comment by rodan123** [comment]
I hadn't tried logging into the API until this version, tried all the steps you listed before opening this issue, to no avail.
You may have isolated the problem. I was building from source. I downloaded the pre-made executable, installed, as was able to log into the Frontier API. Would prefer to compile though, as I merge a few minor code changes in my build.

**Comment by Redrayg** [comment]
> To confirm, you are using the installer rather than building from source?
> @richardbuckle Possibly an issue with the `createAndRememberChallenge()` method?

Thanks, but I always download the installer.  The program seems to run okay, just will not log in to the API.

**Comment by richardbuckle** [comment]
@rodan123  I am going to document how to register your own fork for cAPI access, stand by.

**Comment by richardbuckle** [comment]
@rodan123 That said, if your changes are compatible w/ our vision for EDDI then obviously we'd be happy to receive them via PR.

**Comment by richardbuckle** [comment]
OK, while we would much rather you PR'd your code changes to us, if you really want to go it alone then [here are instuctions](https://github.com/EDCD/EDDI/wiki/Running-from-source).

**Comment by Tkael** [comment]
@Redrayg It sounds like you and rodan123 are probably experiencing issues with different causes. Please confirm the version of EDDI that you are using?

**Comment by rodan123** [comment]
@richardbuckle Thanks for writing up the instruction. I was able to obtain an API key and compile. Everything now works as expected. I will leave this issue open for @Redrayg's benefit and for others that may wander by looking for the same information. Close at your convenience.

**Comment by Redrayg** [comment]
Re-downloaded the beta and this time the log in to the API was successful via the browser.
Only thing now is I'm being informed that it has 'lost its place' and I need to update via the 'Highway Core-E log'.  Is this the log I obtain from EDSM?  If so I have done that once (1691 logs) and it has lost its place again.  Any suggestions?

**Comment by Tkael** [comment]
@Redrayg EDDI is telling you to "high wake or re-log"... either jump out of the system and return or log out to main menu and return.

**Comment by Tkael** [comment]
Closing as the original issue has been resolved. EDDN responder issues e.g. "high wake or re-log" are under investigation in issue #1103.
