### ISSUE TITLE
cargo monitor does not display cargo appropriate

### ISSUE THREAD

**Issue by YamabushiGiri** [EDCD/EDDI#1116]
## EDDI version in which issue found
3.3.4-b1, stand alone
Corgo monitor does not update after frontier login, shown cargo is not appropriate

## Steps to reproduce

1. first starting EDDI, then starting Frontier, login in ED-account
2. restarting EDDI while loged in in ED
3. logout in ED starting launcher again
4. no result

## Expected
cargo monitor should be fixed

## Observed
Cargo monitor is showing wrong data

## Investigation
nothing done so far,

**Comment by Hoodathunk** [comment]
Cargo Monitor data comes from a "Cargo" journal event, which occurs at the start of a game (open, solo, private) session or when you purchase, sell, collect, eject, etc a commodity. Starting the ED launcher does not provide cargo data.

The cargo monitor will not update if EDDI is started after a game session has already, until you purchase, sell, collect, eject, etc a commodity.

Cargo data is not included in the cAPI. It come solely from journal events, in-game.

**Comment by Tkael** [comment]
Closing as invalid for the reasons @Hoodathunk gave. The cargo monitor requires data that is only updated when you are playing the game.

**Comment by YamabushiGiri** [comment]
Are you kidding me Mr. Hoodathunk??? I am playing the game for 2 years now I have this issue since weeks. If you want I can provide you with several screenshots. EDDI is not "Updating" the cargomonitor whenever I change something ingame . It always shows me 7 limpets and 8 structural regulators although I do not have any structural regulators for weeks and several other commodities.

I am running EDDI first and then log in into ED .... every time I doe this in this order. 
I thought EDDI is responsible for sending data to EDSM or is it vice cersa and probably my EDSM API is not working properly? I already have tried to rest my EDSM API and entered the new API into EDDI but without any result - problem is still the same. EDDI is showing the wrong cargo commodities and EDSM is not getting any updates as well.

I would like to know which tool/site is providing which one with informations and I really would like to know, where the error has to be searched.

The only thing I can do to update my EDSM account is to import my game-logfiles manually after my gamesession. I tried to obtain EDSM-Logs towards EDDI multiple times. 

ATM my cargo.json in my ED-datafolder is showing the correct data from ED but neither EDDI nor EDSM is showing the correct data. So What?

What can I do? Do I have any currupt files can I try to do something. 

Your comment and "support" is inappropriate :(

**Comment by Tkael** [comment]
Please provide a copy of the EDDI log file for the most recent game session (called `eddi.log`) and and the configuration file for your cargo monitor (called `cargomonitor.json`). Both are available at `%APPDATA%\roaming\EDDI\`.
Please also provide a copy of the most recent journal file and cargo.json from your saved games folder.

You can try closing EDDI completely and then deleting `cargomonitor.json`. Deleting this file will remove any file corruption and a new file will be created on your next play session.

**Comment by YamabushiGiri** [comment]
Thanks a lot for reopening and sorry for missleading opening post. Provided data is down below ... 
screenshot of most recent cargo.json is shown in the pictures above already ;)
![cargomonitorjson001](https://user-images.githubusercontent.com/46942476/52090908-07b22580-25b3-11e9-8f12-191e82df7638.JPG)
![cargomonitorjson002](https://user-images.githubusercontent.com/46942476/52090923-0da80680-25b3-11e9-89ed-da89e33af76d.JPG)
![missionmonitorjson](https://user-images.githubusercontent.com/46942476/52090928-126cba80-25b3-11e9-8986-77c456e12a16.JPG)




[eddi1.log](https://github.com/EDCD/EDDI/files/2819289/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/2819290/eddi2.log)
[Journal.190131015542.01.log](https://github.com/EDCD/EDDI/files/2819299/Journal.190131015542.01.log)

**Comment by YamabushiGiri** [comment]
I tried to end EDDI, delete cargomonitor.json and restarted EDDI ... there is e new cm.json, but its empty, even I made a jump to another system. But the good thing was, EDDI now transmit the system jumpdata to EDSM ... so just still a Problem with the cargomonitor.json .... below the actual cargomonitor.json from roaming - EDDI and the cargo.json from game saved files ...

![cargomonitorjson003](https://user-images.githubusercontent.com/46942476/52095258-a98d3e80-25c2-11e9-9db3-d11063712f1c.JPG)
![cargojson003](https://user-images.githubusercontent.com/46942476/52095270-b14ce300-25c2-11e9-80db-53378f816a2a.JPG)

**Comment by Hoodathunk** [comment]
Few things going on here.

Your Cargo manifest showing `Methanol Monohydrate` with none in the hold is intended. You had a pending Mining mission and the Cargo Monitor adds the commodity to the manifest to track the progress of the mission, via the `Need` value.

The `Structural Regulators` issue looks like the commodity data was corrupted in the json. Only deleting the cargomonitor.json file will correct that. I will look into whether additional 'protection' code is feasible.

The `Drones` issue has me a bit stumped as that should be updating. I will investigate this further.

**Comment by YamabushiGiri** [comment]
Thanks a lot hooda ... if any additional information is needed, please let me know ... what I have found out, my cargo.json from the game saved files folder shows 10 limpets and the journal logfile also shows that I have just 10 limpets left in hold, but even after manually importing the journal into edsm the edsm-site shows me 20 cargo-hold .... hmmmm .... the cargomonitor.json of eddi is still empty.

**Comment by Tkael** [comment]
@Hoodathunk If the `KeepAlive` exception killed the cargo monitor, that could explain what we are seeing. 
@YamabushiGiri Please downgrade to [version 3.3.3](https://github.com/EDCD/EDDI/releases/download/Release%2F3.3.3/EDDI-3.3.3.exe) and let us know if that fixes the problem?

**Comment by Hoodathunk** [comment]
It’s possible, but I found some minor errors in the update checking that allows scenarios in which cargo data updates are missed. I amended the code &  added unit testing for the scenarios, which are now passing. I expect to submit the PR tonight.

**Comment by YamabushiGiri** [comment]
after installing 3.3.3 unable to connect to frontier API ... with the tipp to try again later .... I will keep you informed as connection is working.

**Comment by YamabushiGiri** [comment]
Last days EDDI is not even starting. The process in the windows taskmanager is starting but window is not opening.

**Comment by YamabushiGiri** [comment]
> Last days EDDI is not even starting. The process in the windows taskmanager is starting but window is not opening.

Problem solved. Deinstallation, deleting app-data-folder, reinstallation -> EDDI running

**Comment by YamabushiGiri** [comment]
Updated to EDDI version 3.3.4. - cargomonitor still does not display propper amount of limpets, all other cargo is displayed correct now.

**Comment by YamabushiGiri** [comment]
EDDI is still not running without deleting the appdatafolder. background process is running but programwindow does not open.

**Comment by YamabushiGiri** [comment]
correction - I started EDDI, went for a smoke, came back and it was running :D

**Comment by Hoodathunk** [comment]
@YamabushiGiri you're describing a separate issue that is detailed #1159. We understand the failure mode and have a fix scheduled for deployment.
