### ISSUE TITLE
docked event not work

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#1122]
## EDDI version in which issue found
EDDI v3.3.4-b1

## Steps to reproduce

1. Dock into Coriolis or space port

## Expected

Docked script and VoiceAttack event ((EDDI docked)) should work.

## Observed
log shows `"event":"Docked"`, as always. Example:

`{ "timestamp":"2019-01-25T17:12:00Z", "event":"Docked", "StationName":"Schwann Port", "StationType":"Outpost", "StarSystem":"Bok", "SystemAddress":2450035558763, "MarketID":3223688960, "StationFaction":{ "Name":"Labour of Bok", "FactionState":"CivilWar" }, "StationGovernment":"$government_Democracy;", "StationGovernment_Localised":"Democracia", "StationAllegiance":"Federation", "StationServices":[ "Dock", "Autodock", "BlackMarket", "Commodities", "Contacts", "Exploration", "Missions", "Outfitting", "CrewLounge", "Rearm", "Refuel", "Repair", "Workshop", "MissionsGenerated", "FlightController", "StationOperations", "Powerplay", "SearchAndRescue", "StationMenu" ], "StationEconomy":"$economy_Industrial;", "StationEconomy_Localised":"Industrial", "StationEconomies":[ { "Name":"$economy_Industrial;", "Name_Localised":"Industrial", "Proportion":1.000000 } ], "DistFromStarLS":94.853157 }`

**Comment by Hoodathunk** [comment]
We are fully aware of this. FDEV changed the journal data for system and station controlling factions, breaking the 'Docked', Location', and 'FSDJump' events.

We already have a working fix and should be pushing it to the public soon.

**Comment by Tkael** [comment]
Fixed via #1118.

**Comment by hoksilato2** [comment]
We are a genius guys.
