### ISSUE TITLE
Eddi not starting

### ISSUE THREAD

**Issue by Beondred** [EDCD/EDDI#1128]
## EDDI version in which issue found
EDDI-3.3.4-b1

## Steps to reproduce

I open EDDI but it seems to do nothing

## Investigation
Removed appdata/roaming/eddi but it solved nothing. Uninstalled and installed again many times, different versions; no help.

Attached the log
[eddi.log](https://github.com/EDCD/EDDI/files/2798874/eddi.log)

**Comment by richardbuckle** [comment]
It looks like your installation may be damaged. Could you please re-download the installer from https://github.com/EDCD/EDDI/releases and re-install EDDI. Hope this helps.

**Comment by Juggernaut93** [comment]
Same is happening to me, I tried to install twice, but the process just starts and stops before showing anything on screen.

**Comment by Juggernaut93** [comment]
I think I have found the issue. `SpeechResponder.it.resx` has the wrong filename in `default_personality_script_filename`. It's `eddi.it.jsonb` instead of `eddi.it.json`.

**Comment by Beondred** [comment]
Yep! That's the problem.

**Comment by Tkael** [comment]
Fixed by PR #1134.

**Comment by richardbuckle** [comment]
Fix will be published v soon as 3.3.4-rc2.
