### ISSUE TITLE
Number of times a system is visited not right

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1143]
## EDDI version in which issue found
3.3.4-rc3

## Steps to reproduce

In ticket #1100 I reported a problem with obtaining the EDSM-logs and this was solved in 3.3.4-rc1 so I obtained the logs and the visit count was accurate again. I'm doing a CG at Kuma this week and last tuesday EDDI told me I had visited Gilya 3 times and Kuma 7 times and both numbers were correct..
After that I logged of while docked at Kuma.

This morning I updated to EDDI 3.3.4-rc3 and after the update I looked at EDDI.log and saw both Kuma and Gilya being mentioned (i hadn't started the game at that time). I then started VA to see if that was starting rc-3 alright and after I noticed it did I closed VA again.
Then I started VA and after that I started the game and made a test run to Gilya and back to Kuma.
EDDI told me it was my second visit to Gilya (instead of the fourth) and that it was my third visit to Kurma (instead of the eight) so it looks like the reading of the last journal at startup messes up the visit count for the systems that are in that journal.
I'll try deleting the SQlite file and obtain my EDSM-logs again after work later today.

**Comment by Tkael** [comment]
Ok. FYI we revised the code to only increment visits if the timestamp was fresher than the last visit timestamp in our database.

**Comment by Tkael** [comment]
It was included in rc3. 
I took another look in the code and found a bug that was causing us to wipe / discard visits data as we retrieved it from the database. Submitting a PR to correct this.

**Comment by JCalvertJoshua** [comment]
Thank you.

**Comment by JCalvertJoshua** [comment]
I updated to EDDI 3.3.4-rc4 and the problem still exists. After the update I obtained the EDSM-log again and headed back to my home system and the number of visits EDDI reported were correct. Then I closed everything (Elite and Voiceattack) and started it again. Made a short trip and when I returned to my home system the number of visits EDDI reported went down from 543 to 3.
I then deleted the SQlite file and obtained my EDSM-log again:
![eddi sqlite after obtain log](https://user-images.githubusercontent.com/19605885/52466787-be9a3c80-2b83-11e9-93d9-48aaee992317.JPG)

Then made a first trip and it looked good:

![eddi sqlite after first trip](https://user-images.githubusercontent.com/19605885/52466818-da054780-2b83-11e9-9da0-b0dd97cb3940.JPG)

After shutting down and starting up again and made a next trip it was wrong again (Sol this time)

![eddi sqlite after second trip](https://user-images.githubusercontent.com/19605885/52466879-0751f580-2b84-11e9-8b95-851278a062c7.JPG)

And here is the last part of my speechresponder.out file showing the speech from this morning:

[Speechout 8-2.txt](https://github.com/EDCD/EDDI/files/2844229/Speechout.8-2.txt)

Maybe you can look at it again and, hopefully, fix it otherwise I will just delete the mention of the number of visits from the scripts which would, for me at least, be a bad thing because it was one, among plenty, of the details I especially liked about EDDI but only if the number is correct.
