### ISSUE TITLE
Ship Monitor puts "NULL" as value for starsystem on ships

### ISSUE THREAD

**Issue by Razzledazzk** [EDCD/EDDI#1158]
## EDDI version in which issue found
3.3.3
Running it as standalone, got Voice Attack but I opened only EDDI during the play as my goal was to update my ship list.

## Steps to reproduce

1. Logged out of everything.
2. Deleted \AppData\Roaming\EDDI\Shipmonitor.json
3. Opened EDDI standalone.
4. Enabled shipmonitor plugin. 
5. Opened Elite, changed ship at station.
6. Ship location is blank.
7. Opened shipmonitor.json => "starsystem": null,
8. Jumped out of system and back in again.
9. Changed ship
10. Ship location is blank.
11. Opened shipmonitor.json => "starsystem": null,

## Expected
Expected to get EDDI to update the ship location with the solar system I was in

## Observed
Location is left blank, with the value of Null from the shipmonitor.json file

## Investigation
Tried with and without EDDN plugin engaged, as that has started to give notifications with responder not working.
Tried deleting shipmonitor.json file completely to rebuild, but it still gives Null as value

Uncertain where EDDI pulls location from, so haven't touched anything since those.

**Comment by Tkael** [comment]
We only record location for stowed ships, not the active ship. It's not clear from your description, but are you looking for the location of your active ship?

**Comment by Razzledazzk** [comment]
![ship monitor 2](https://user-images.githubusercontent.com/34264611/52238512-71d90c00-28cc-11e9-86f0-9a9b0b894aac.jpg)

As soon as I went into my Federal Corvette, the location disappears

**Comment by Tkael** [comment]
Would you please log in and switch to your Federal Corvette with EDDI running (if you've changed ships), and then send us a copy of your shipmonitor.json for review? The shipmonitor.json config file will be located at `%APPDATA%\EDDI`.

**Comment by Razzledazzk** [comment]
Did the following:
1. Bought a sidewinder, named it LEANN Just bought : ID:sidew.
2. Closed the game and logged out, closed EDDI
3. Opened EDDI, took a copy of the shipmonitor file (01)
4. logged in, then took a copy of the shipmonitor file (02)
5. changed ship from LEANN sidewinder -> LEANN Federal corvette, then took a copy of the ship monitor file (03)
6. logged out, then took a copy of the shipmonitor file (04)

I got all those 4 files ready, I am sending file nr. 3 alone, but also all of them in one zip folder, so you can compare them if that gives you any clue to where my issue is originated.

[shipmonitor 03 Switched to Federal Corvette.zip](https://github.com/EDCD/EDDI/files/2831942/shipmonitor.03.Switched.to.Federal.Corvette.zip)

[shipmonitor.json.zip](https://github.com/EDCD/EDDI/files/2831938/shipmonitor.json.zip)

Also sorry for the mess, I am a horder when it comes to ships.

As always, thank you very much for the time for looking into this.
If need be, let me know and I can uninstall and reinstall EDDI.

Also - when logging in / landing at the base. I got the EDDI audio info:
"The EDDN responder is in an invalid state and is unable to send messages. Please validate your position by either jumping out of the system and back in or by logging out and logging back in"
I have looked around a bit, but unable to find out if this is related - but since it started saying this, my issue started to happen.

**Comment by Hoodathunk** [comment]
@Razzledazzk we had some issues in 3.3.3 with the Current star system being properly set, causing the EDDN responder 'invalid state' and a likely culprit to what you're experiencing.

We are very close to releasing a final to 3.3.4, which addresses previous EDDN issues, including restoring cAPI functionality and handling the new `StoredShips` event.

I suggest that you try the latest 3.3.4 release candidate and verify whether your problem has been corrected.

**Comment by Tkael** [comment]
Make that version [3.3.4-rc4](https://github.com/EDCD/EDDI/releases/download/Release%2F3.3.4-rc4/EDDI-3.3.4-rc4.exe)?

**Comment by Razzledazzk** [comment]
Trying out 3.3.4-rc4 now and will update in a short while

**Comment by Razzledazzk** [comment]
Got some very strange data for you.
I dont know where the error is, but it is producing a lot of deletion of the ships I use.
I am ready for a clean install for next step if you think needed.
Esp at step 09 I got confused, as why the list suddenly rediscovered itself

For next trials, please inform as to the steps you would like me to take in regards the install & which folders to delete.

-------------------
Setup:
I installed EDDI 3.3.4-rc4 without doing any uninstall.
I logged in, everything seemed fine for a second, then data started disappearing.
I then deleted the old shipmonitor.json file and replaced it with the file I uploaded earlier in this thread - since after I began changing ships, data went missing, and I wanted to show the process.

I only used the following 2 ships:
Federal Corvette LEANN - ID Com847
Federal Gunship GOID HRP LAYERD XG8+9 - ID Gun05

I will refer to them as Com847 + Gun05

After each step, I took a screenshot of EDDI + a copy of the shipmonitor.json file
Below is my data
-------------------
01
Ran EDDI 3.3.4rc, without anything else.

![01 shipmonitor - old copy eddi 3 3 4-rc4 - before login - last ship fc com847](https://user-images.githubusercontent.com/34264611/52474518-02e40780-2b99-11e9-95ba-a6f9dbf7fe71.jpg)
[01 shipmonitor - Old copy EDDI 3.3.4-rc4 - before login - last ship FC Com847.zip](https://github.com/EDCD/EDDI/files/2844768/01.shipmonitor.-.Old.copy.EDDI.3.3.4-rc4.-.before.login.-.last.ship.FC.Com847.zip)

Price on Com847 is wrong due to changed items
-------------------
02
Logged in

![02 shipmonitor - running eddi 3 3 4-rc4 - logging in in fc com847](https://user-images.githubusercontent.com/34264611/52474541-14c5aa80-2b99-11e9-980c-d22b94feebfe.jpg)
[02 shipmonitor - Running EDDI 3.3.4-rc4 - logging in, in FC Com847.zip](https://github.com/EDCD/EDDI/files/2844772/02.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.logging.in.in.FC.Com847.zip)

Price on Com847 updated correct, not showing location
-------------------
03
Only entered Shipyard, nothing else.

![03 shipmonitor - running eddi 3 3 4-rc4 - entered shipyard from fc com847](https://user-images.githubusercontent.com/34264611/52474585-358e0000-2b99-11e9-8ae5-e3413762a8ca.jpg)
[03 shipmonitor - Running EDDI 3.3.4-rc4 - Entered Shipyard from FC Com847.zip](https://github.com/EDCD/EDDI/files/2844780/03.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.Entered.Shipyard.from.FC.Com847.zip)

Locaiton updates on all ships, Com847 that I was in, is gone from the list.
-------------------
04
Exited shipyard, without changing ship, logged out and back in again.

![04 shipmonitor - running eddi 3 3 4-rc4 - exit shipyard logged out back in no ship change](https://user-images.githubusercontent.com/34264611/52474641-55bdbf00-2b99-11e9-8987-ce70179e8607.jpg)
[04 shipmonitor - Running EDDI 3.3.4-rc4 - Exit shipyard, Logged out + back in, no ship change.zip](https://github.com/EDCD/EDDI/files/2844784/04.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.Exit.shipyard.Logged.out.%2B.back.in.no.ship.change.zip)

Com847 back on list, no location.
-------------------
05
Changed from Com847 -> Gun05
![05 shipmonitor - running eddi 3 3 4-rc4 - just changed from fc com847 to fg gun05](https://user-images.githubusercontent.com/34264611/52474666-68d08f00-2b99-11e9-89b6-806a886c7a0e.jpg)
[05 shipmonitor - Running EDDI 3.3.4-rc4 - Just changed from FC Com847 to FG Gun05.zip](https://github.com/EDCD/EDDI/files/2844787/05.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.Just.changed.from.FC.Com847.to.FG.Gun05.zip)

Com847 is gone, Gun05 location is gone.
-------------------
06
Entered shipyard from Gun05

![06 shipmonitor - running eddi 3 3 4-rc4 - entered shipyard from gun05 - fc appears without id](https://user-images.githubusercontent.com/34264611/52474726-8f8ec580-2b99-11e9-800d-fca6270a7f64.jpg)
[06 shipmonitor - Running EDDI 3.3.4-rc4 - Entered Shipyard from Gun05 - FC appears without ID.zip](https://github.com/EDCD/EDDI/files/2844791/06.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.Entered.Shipyard.from.Gun05.-.FC.appears.without.ID.zip)

Com847 back on list, wrong value. Gun05 gone from list
-------------------
07
Changed from Gun05 -> Com847

![07 shipmonitor - running eddi 3 3 4-rc4 - just changed from fg gun05 to fc com847](https://user-images.githubusercontent.com/34264611/52474827-cebd1680-2b99-11e9-9ef2-314ea659d646.jpg)
[07 shipmonitor - Running EDDI 3.3.4-rc4 - Just changed from FG Gun05 to FC Com847.zip](https://github.com/EDCD/EDDI/files/2844803/07.shipmonitor.-.Running.EDDI.3.3.4-rc4.-.Just.changed.from.FG.Gun05.to.FC.Com847.zip)

Com847 correct value, Gun05 gone from list
-------------------
08
Deleted shipmonitor.json
Rebooted system
Running EDDI 3.3.4-rc4
Logging in

![08 shipmonitor - running eddi 3 3 4-rc - clean data logged in fc com847](https://user-images.githubusercontent.com/34264611/52474882-00ce7880-2b9a-11e9-8761-f6dace5a57b2.jpg)
[08 shipmonitor - Running EDDI 3.3.4-rc - Clean data, logged in FC Com847.zip](https://github.com/EDCD/EDDI/files/2844808/08.shipmonitor.-.Running.EDDI.3.3.4-rc.-.Clean.data.logged.in.FC.Com847.zip)

Com847 correct value, empty list
-------------------
09
Changed from Com847 -> Gun05

![09 shipmonitor - running eddi 3 3 4-rc - clean data changed from fc com847 to fg gun05](https://user-images.githubusercontent.com/34264611/52474954-3a9f7f00-2b9a-11e9-8a33-50aec6b86cbf.jpg)
[09 shipmonitor - Running EDDI 3.3.4-rc - Clean data, changed from FC Com847 to FG Gun05.zip](https://github.com/EDCD/EDDI/files/2844819/09.shipmonitor.-.Running.EDDI.3.3.4-rc.-.Clean.data.changed.from.FC.Com847.to.FG.Gun05.zip)

List is now updated again??
No clue where the data was drawn from.
Com847 gone from list, Gun05 location gone
-------------------
10
Changed from Gun05 -> Com847

![10 shipmonitor - running eddi 3 3 4-rc - clean data changed from fg gun05 to fc com847](https://user-images.githubusercontent.com/34264611/52474985-599e1100-2b9a-11e9-8379-a91fb90c5fd6.jpg)
[10 shipmonitor - Running EDDI 3.3.4-rc - Clean data, changed from FG Gun05 to FC Com847.zip](https://github.com/EDCD/EDDI/files/2844823/10.shipmonitor.-.Running.EDDI.3.3.4-rc.-.Clean.data.changed.from.FG.Gun05.to.FC.Com847.zip)

Com847 back on list, correct value, Gun05 gone
-------------------

**Comment by Hoodathunk** [comment]
@Razzledazzk, thanks for the data. I understand most of what is going on, but one missing piece to the puzzle... are you logged into the Frontier cAPI?

To answer your confusion, the data comes from a `StoredShips` event and from the cAPI.

FYI, when you swap to another ship, the location disappearing is intended. Only the location of stored ships are displayed. Also, the data comes from multiple sources (cAPI and journal events) and they are not always in sync. It oftens takes some time to 'catch up'.

I understand the phenomena of the your currently occupied ship disappearing. Your currently occupied ship is no long in the list of 'stored ships' and the handler for the event is incorrectly pruning it from the shipyard. Simple fix which will be in the next (last?) update before going final on 3.3.4.

**Comment by Razzledazzk** [comment]
Just turned on Frontier API, and did a few tests.
I was one of those who couldnt get API to work, so that the new version makes it possible is wonderfull.

But stil only using Com847 & Gun05, everytime I switch out of a ship, it disappears from the list.

The ship I am in, is registrated but with a blank location, as you say it should be.
But the other ship is 100% gone from the list.

If im in Com847, then Gun05 is gone.
When I shifts, Com847 disappears 100%, and Gun05 is there with blank location

But then after restarting EDDI, the ships didnt return.
I am a tad pressed on time due to work this weekend, so will try to test more sunday, but can be it wont be until monday..

**Comment by Hoodathunk** [comment]
@Razzledazzk 

First, have you updated to 3.3.4.?

As I said above, the location for your current ship is intentionally blank.

As I'm writing this, I have swapped to multiple ships and it's all working fine for me.

**Comment by Razzledazzk** [comment]
Sorry for not answering before, I havent had time to test out yet due to real life.

I am upgrading now to 3.3.4, I was running 3.3.4-rc as it was instructed earlier, and I missed the part where switching to 3.3.4 purely.

After switching to 3.3.4, HUZZAAA
The ship monitor works perfectly.

It is slow sometimes, but as you said, it can take a bit until it updates - and I can use it for what I really wanted it to do - keeping track of my items when I need to reconfig ship.

Fast question though regarding Frontier API.
It worked fine for me in 3.3.4-rc, after a long time where I couldnt log in.
But as soon as I switched to 3.3.4, I can not log into Frontier API again.

I suspect an error on my side - and would just like to ask if a clean install and purge of files is recommended?

Regarding the ship monitor - soooo  nice it works now and thank you :)

**Comment by Tkael** [comment]
There was some sort of weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by Tkael** [comment]
The Frintier API issue is covered by another recent ticket, so I'm going to go ahead and close this ticket. o7 cmdr.
