### ISSUE TITLE
Cannot authenticate to Frontier API since 2.4 upgrade

### ISSUE THREAD

**Issue by shaunpond** [EDCD/EDDI#116]
## Steps to reproduce

1. start EDDI after upgrading E:D to 2.4

## Expected
Frontier API works

## Observed
Frontier API not operational, and fails if you try to re-authenticate, after entering the code from email

## Investigation
The ED Market connector is similarly "broken", so I imagine Frontier have changed the API. 
Submitting this as a marker, as I'm sure it's better to have a ticket to link to

**Comment by Syrrianyl** [comment]
Th ebug affect many different software : [Link to the forum about the bu"](https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED?p=5948667)

**Comment by richardbuckle** [comment]
Frontier bug, the API server is having a dirtnap. They are aware and working on it.
