### ISSUE TITLE
Number of visits still not correct in 3.3.4-rc4 to 3.4.1-b2

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1162]
I updated to EDDI 3.3.4-rc4 and the problem still exists. After the update I obtained the EDSM-log again and headed back to my home system and the number of visits EDDI reported were correct. Then I closed everything (Elite and Voiceattack) and started it again. Made a short trip and when I returned to my home system the number of visits EDDI reported went down from 543 to 3.
I then deleted the SQlite file and obtained my EDSM-log again:
![eddi sqlite after obtain log](https://user-images.githubusercontent.com/19605885/52466787-be9a3c80-2b83-11e9-93d9-48aaee992317.JPG)

Then made a trip from home to Sol and home was off again:

![eddi sqlite after first trip](https://user-images.githubusercontent.com/19605885/52466818-da054780-2b83-11e9-9da0-b0dd97cb3940.JPG)

After shutting down and starting up again and made the same trip a few times it was wrong again (also Sol this time)

![eddi sqlite after second trip](https://user-images.githubusercontent.com/19605885/52466879-0751f580-2b84-11e9-8b95-851278a062c7.JPG)

And here is the last part of my speechresponder.out file showing the speech from this morning:

[Speechout 8-2.txt](https://github.com/EDCD/EDDI/files/2844229/Speechout.8-2.txt)

Maybe you can look at it again and, hopefully, fix it otherwise I will just delete the mention of the number of visits from the scripts which would, for me at least, be a bad thing because it was one, among plenty, of the details I especially liked about EDDI but only if the number is correct.

_Originally posted by @JCalvertJoshua in https://github.com/EDCD/EDDI/issues/1143#issuecomment-461729189_

**Comment by Tkael** [comment]
Ok. I'll take another look.

**Comment by Tkael** [comment]
Any observations about when you notice a reset would be helpful. You can poll the data anytime by using {system.visits} and {lastsystem.visits} in a Cottle script.

**Comment by JCalvertJoshua** [comment]
I'm not sure what you mean by "a reset would be helpful". 

I've only changed the part from the default FSDengaged script about the number of visits with some small speech changes and also the part where the number of visits is > 3

  ```
{if reportsystem.visits = 0:
            {OneOf("This is our first visit to this system","We were never in this system before","This is the first time we are in this system","This is a new system for us")}
        |elif reportsystem.visits = 1:
            This is our second visit to this system
        |elif reportsystem.visits = 2:
            This is our third visit to this system
        |elif reportsystem.visits = 3:
            This is our fourth visit to this system
        |else:
        {set visitsincludingthis to reportsystem.visits+1}
            We have visited this system {visitsincludingthis} times.
        }.
```

Is there a difference between "reportsystem.visits" , like it's used in my (and default) script and the "system.visits" you mentioned ?

**Comment by Tkael** [comment]
Something is resetting the visit count. We need to figure out what that is. 
`reportsystem` reports information about a named star system (typically this is the current star system, though you could configure it to report on any star system)
`system` reports information about the current star system you are in.
`lastsystem` reports information about the last star system you visited

**Comment by Tkael** [comment]
`      {set visitsincludingthis to reportsystem.visits+1}`
Note: This won't be correct under the current implementation, since the visit count already takes into consideration the current visit.

**Comment by JCalvertJoshua** [comment]
I’ll do some more testing tomorrow (not at my PC now) but if IIRC it goes well if I play a session right after I obtained my EDSM-logs. But after I end that session (shutting down ED and VA) and start a new session the systems I visited in the first session get reset. 

Regarding your remark about my visitsincludingthis: does this only aply when the count is >3 ? Otherwise I think the default script needs to be changed too for if it always includes the current visit then for instance the first line will never trigger because at the first visit the number would be 1 instead of 0.

**Comment by JCalvertJoshua** [comment]
Did some testing and it looks like my memory was correct.
First I made a trip visiting 9 systems. After that SQlite looked like this:
![sqlite after first trip to lave](https://user-images.githubusercontent.com/19605885/52530951-44e28a00-2d0e-11e9-98f2-94e1f370f2cc.JPG)

I then checked the number of visits in EDSM and they were all correct apart from Luyten's Star (which I visited together with Sol in my previous test so they were in the last journal before today.

Then, after restarting the game and VA I made the return trip only this time I planned a stop to a system just before the next target before jumping to the target so this time I would also visit system that were not in my first trip. I also made a VA command using the Next System to tell me the number of visits I made to the system I was jumping to next.
At the first jump, from Lave to Leesti (the only jump without an extra stop) I knew it was wrong again because VA told me the number (for Next System) was 1 and after arriving at Leesti EDDI told me it was my second visit.

After this return trip SQlite looks like this:
![sqlite after return trip](https://user-images.githubusercontent.com/19605885/52531060-ca1a6e80-2d0f-11e9-8e9c-d7de99d144a7.JPG)

As you can see all the systems I visited in my first trip have been reset to 1 at the start and the number of visits is now 2. All the systems from the second trip that I didn't visit in the first trip are correct.
After typing this I started up the game and VA again and only planned a route to one of those "new" systems and VA (Next system) told me the number of Caelinus  is 1 instead of 81 so it looks like those systems are now also reset.

During my trips I never docked. The only thing happening is the automatic Honk I build in when arriving and then I jump to the next system.

**Comment by Tkael** [comment]
Would you say that it only happens when it's been more than hour since your last visit?

**Comment by JCalvertJoshua** [comment]
I don't think so. It also happens with just a couple of minutes between the sessions. The sessions from this morning were about 20 minutes apart because after the first trip I manually checked the number of visits of the systems I visited in the first screenshot with EDSM to see if they were OK.
I'll include the journals and logs from this mornings sessions. Maybe that will help you pinpoint the problem.

[eddi.log](https://github.com/EDCD/EDDI/files/2849233/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/2849234/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/2849235/eddi2.log)
[Journal.190210075126.01.log](https://github.com/EDCD/EDDI/files/2849237/Journal.190210075126.01.log)
[Journal.190210071708.01.log](https://github.com/EDCD/EDDI/files/2849238/Journal.190210071708.01.log)

**Comment by JCalvertJoshua** [comment]
There are issues with higher priority of course but did you get a chance to look at this ?

**Comment by Tkael** [comment]
Not yet, but I haven't forgotten about this one. I've been working on other issues and since I've been on DW2 I haven't been backtracking to prior systems very often.

**Comment by JCalvertJoshua** [comment]
No worries 😊

**Comment by richardbuckle** [comment]
Please re-test with 3.3.7-b1

**Comment by JCalvertJoshua** [comment]
I didn't expect it to be solved yet since Tkael's latest comment but I did a test this morning and the problem is still there.
I obtained my EDSM-logs and made some small trips, restarting VA+EDDI inbetween.
Here's the speechresponder.out from this morning and the same but with all the not relevant speech cut out and some comments about what the right numbers should be.
Hope this helps.
[speechresponder 10-3-2019.txt](https://github.com/EDCD/EDDI/files/2949227/speechresponder.10-3-2019.txt)
[speechresponder with comments.txt](https://github.com/EDCD/EDDI/files/2949228/speechresponder.with.comments.txt)

**Comment by Tkael** [comment]
Hi Josh, I've been taking another look at this. I've toyed around with various possible solutions but I'm not sure that they are really addressing the root cause.

The primary reason this issue has languished is that I don't really have a clear protocol for replicating the issue. If you can help me to establish a clear sequence of actions that reliably creates this condition (e.g. step 1, step 2, etc.) then that would be a great help.

**Comment by JCalvertJoshua** [comment]
Hi,
After upgrading Eddi to 3.4.1-b2 I did a new test and here's what I did:
1. deleted the EDDI.sqlite file
2. started EDDI-standalone and obtained my EDSM-logs
3. closed EDDI-standalone
4. Started VA (with EDDI-plugin active)
5. Started Elite (I was in space in the LTT 7876 system)
6. made a short trip to Lave
7. closed Elite and VA
7. made first screen shot of the SQlite file
![sqlite first](https://user-images.githubusercontent.com/19605885/58699528-fbda4280-839d-11e9-88d7-c94ee5048a4b.JPG)
8. checked the above numbers with my EDSM flightlogs. They were all correct with one exception. LTT 7876 (where I was before I started this) says in SQlite 3 times while I only visited it 2 times.
9. started up VA and Elite again.
9. made a round trip with an extra stop between systems.
10. closed Elite and VA.
11. made second screen shot of the SQlite file
![sqlite second](https://user-images.githubusercontent.com/19605885/58700176-abfc7b00-839f-11e9-8480-c3f261c36e75.JPG)
12. checked the numbers again with EDSM but as you can see the systems I visited in the first trip are wrong (apart from BAIJUNGU), they should be 1 higher then the first screenshot but they got less.  The systems where I made an extra stop in the roundtrip (and which therefor were not in the previous journal, like Diso) are correct.

Hope this all and my English makes sense :-)
If there's something else you want me to try just lest me know.

**Comment by Tkael** [comment]
is it always the starting star system that is falling out of sync with EDSM? If so, I know how to fix that.

**Comment by JCalvertJoshua** [comment]
Yes but not only the starting star system. I still have a feeling it's got to do with the reading of the previous journal when starting EDDI like I mentioned in my earlier issue (#1143)
Since the starting system normally is the last system in the previous journal it's always included in the problem but so are the other systems in that previous journal.
I just made the same trip I mentioned above twice again (without deleting the SQlite database and obtaining the EDSM logs this time). All the seven systems I visited now are out of sync with EDSM.
After these trips I closed VA and Elite and checked the numbers and started this post. While rereading issue #1143 I saw you mentioned the timestamp. 
I then made this screenshot of the SQlite database : 
![SQlite fourth trip](https://user-images.githubusercontent.com/19605885/58721002-fe578f00-83d3-11e9-9ac0-6510a2918017.JPG)

After that I started EDDI, let it run for a minute or so and then closed it again, without starting Elite.
The EDDI log from that session mentioned the seven systems : 
2019-05-31T16:31:15 [Info] EDDI:eventJumped Jumped to Diso 
2019-05-31T16:31:17 [Info] EDDI:eventJumped Jumped to Baijungu 
2019-05-31T16:31:17 [Info] DataProviderService:syncFromStarMapService EDSM sync completed 
2019-05-31T16:31:18 [Info] EDDI:eventJumped Jumped to Kame 
2019-05-31T16:31:18 [Info] EDDI:eventJumped Jumped to LFT 1223 
2019-05-31T16:31:19 [Info] EDDI:eventJumped Jumped to Othime 
2019-05-31T16:31:19 [Info] EDDI:eventJumped Jumped to LTT 7876 

and the SQlite  now looks like this:
![SQlite after fourth trip starting eddi without flying](https://user-images.githubusercontent.com/19605885/58721153-7e7df480-83d4-11e9-86ea-b1aa8fab7408.JPG)

As you can see the number of visits and the time of last visit changed for some of the systems. I don't know if that's expected behaviour or not but I thought I'ld let you know just to be sure.
