### ISSUE TITLE
EDDI starts up, but fails to show GUI

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#1165]
EDDI version 3.3.4.

Please, re-open this ticket: 
#1159

I put it my test and logs for it.

Test Resume:
If I delete %appdata%\EDDI\missionmonitor.json , GUI works again, but I need delete it at every EDDI start.

This occurs after reset Windows 10 and install the last 3.3.4 EDDI's version.

Thanks.

**Comment by hoksilato2** [comment]
last log:
[eddi.log](https://github.com/EDCD/EDDI/files/2848145/eddi.log)

**Comment by Tkael** [comment]
Re-opened #1159, making this issue redundant.
Unfortunately, your logs don't tell us very much about what's going on here. :-(
