### ISSUE TITLE
voice not

### ISSUE THREAD

**Issue by silverbane1970** [EDCD/EDDI#1168]
## EDDI version in which issue found
3.3.3

## Steps to reproduce

1. opened eddi
2. i use it as a standalone with no other voice program running, I do not own VoiceAttack

## Expected
voice to work

## Observed
GUI opened but no voice, not even when using the test voice button text to speech tab

## Investigation
uninstalled and reinstalled, still same issue, restarted computer, again same issue
 i also tried 3.3.4 and that one the GUI would not even come up on screen but was running in the task manager

**Comment by Tkael** [comment]
Merging with #1159. Please navigate to `%appdata%\EDDI` and try removing the file missionmonitor.json (move it to your desktop). Then try restarting EDDI version 3.3.4.
If removing missionmonitor.json resolves the issue, please attach the bad missionmonitor.json file to issue #1159.
Thanks!

**Comment by silverbane1970** [comment]
GUI is visible now for 3.3.4 Standalone but still no voice
