### ISSUE TITLE
EDDI 3.3.4 doesn't open

### ISSUE THREAD

**Issue by vee71** [EDCD/EDDI#1169]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by vee71** [comment]
after updating to 3.3.4 EDDI doesn't open at all. It says it's running in the background but doesn't open and doesn't work in game.

**Comment by Tkael** [comment]
Merging to #1159. Please see that issue for a temporary resolution until our next release.
