### ISSUE TITLE
The "Honorific" script is silent in Federation space

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#117]
## Steps to reproduce

1. Have a non-zero Federation rank
2. Jump from non-Federation space to any Federation system

## Expected
EDDI uses my Federation rank as the honorific upon arrival

## Observed
EDDI uses a blank string as my honorific

## Investigation
Looks like something is wrong with ` {cmdr.federationrating.name}`

**Comment by Tkael** [comment]
is the frontier api fixed yet? If the rating is updated from the api, it could explain this issue

**Comment by richardbuckle** [comment]
Possible. But Imperial rating is read from the journals, so why shouldn't Fed rating be? (insert role-play snark here re superior Imperial tech here.) 

This episode has taught us that given a choice between journals and cAPI, in general you are better off with the journals.

**Comment by Tkael** [comment]
I agree that you typically are better off with the journal data. I think, however, that EDDI writes neither Federation nor Empire ratings to the cmdr object - that all currently comes from the API. From EDDI.cs lines 97-98:
```
        // Information obtained from the companion app service
        public Commander Cmdr { get; private set; }
```
We can look into updating the cmdr object from the journal, either in addition to or in place of the API.

**Comment by richardbuckle** [comment]
Appears to be fixed now that the cAPI is back.
