### ISSUE TITLE
Trying to get body report to work correctly upon detailed surface scan

### ISSUE THREAD

**Issue by Zweistein000** [EDCD/EDDI#1174]
Hey, I've been playing around with the scripts trying to get the body report read only when I detailed scan objects. the reason behind this is to remove the bloat that happens when I quickly scan objects in FSS. The Problem I'm having is that body reports that are done after DSS only report the gravity and nothing else. Is there a way to fix this or am I stuck with it due to current limitations of the program?

**Comment by Tkael** [comment]
Do you mean when you map a body? 

Try dropping this into the `Body mapped` script:
```
{_ Context}
{SetState('eddi_context_last_action', 'scan')}
{SetState('eddi_context_last_subject', 'body')}
{SetState('eddi_context_body_system', system.name)}
{SetState('eddi_context_body_name', event.name)}

{OneOf("Mapping", "{Occasionally(2, \"Surface\")} Map")}
{Occasionally(2, "of body {P(event.name)}")}
{OneOf("is", "is now")}
{OneOf("complete", "finished")}.

{if event.probesused <= event.efficiencytarget:
    Efficiency bonus {OneOf("awarded", "granted")}.

{if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":
    {Pause(500)}
    {F("Body report")}
}
```
(You'll want to remove references to `    {F("Body report")}` from the `Body scanned` script.

**Comment by Zweistein000** [comment]
I've done this before posting here. It doesn't work. 

![capture](https://user-images.githubusercontent.com/7946816/52629731-ab0c1000-2eba-11e9-90f8-5bb601f24f83.JPG)

**Comment by Tkael** [comment]
Really? Because this is coming from my current personality and I know it's working there.

**Comment by Tkael** [comment]
Closed for lack of information about what isn't working - the script I posted works well for me.
Reply to this issue if you'd like us to reopen this.

**Comment by Zweistein000** [comment]
**The Problem I'm having is that body reports that are done after DSS only report the gravity and nothing else.**

What else information can I give you? I fore the probes, map the planet, the script detects that, tells me I got an efficiency bonus, then only reads out the gravity saying something like "Body is a high-gravity world". 

I have made no changes to the body report script.

**Comment by Tkael** [comment]
Try removing this statement from `Body report`:
```
{if event: 
    {set reportbody to event} 
}
```

**Comment by Zweistein000** [comment]
That worked! Thank you. Now to figure out why the script cant detect terraformable worlds....
