### ISSUE TITLE
Incorrect module swap savings reported when CAPI down

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1177]
## EDDI version in which issue found
3.3.4 (NB cAPI was down)

## Steps to reproduce

1. Dock at a starport with outfitting.

## Expected
Since CAPI is down, no module swapout savings report until I go to outfitting.

## Observed
Immediate module swapout savings report giving, incorrectly, a savings for each module equivalent or close to the purchase price.

## Investigation
Attached text output, shipmonitor.json and log files

**Comment by richardbuckle** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/2857740/eddi.log)

[shipmonitor.json.txt](https://github.com/EDCD/EDDI/files/2857741/shipmonitor.json.txt)
[speech.txt](https://github.com/EDCD/EDDI/files/2857745/speech.txt)

**Comment by Tkael** [comment]
Fixed by #1178
