### ISSUE TITLE
Frontier API Login not working / cargo related functions not working

### ISSUE THREAD

**Issue by simon-winter** [EDCD/EDDI#1179]
## EDDI version in which issue found
3.3.4

## Steps to reproduce

1. open eddi as administrator
2. navigate to "Frontier API"
3. click Login
(4. close EDDI)
5. login into frontier popup page
6. accepting the popup dialog to open that link with eddi

## Observed
The login fails with eddi running or not, in firefox and internet explorer. The Errormessage is something like "The data could not be passed to the programm". it comes from the browser/OS not eddi.
If eddi wasnt closed in step 4, i get the additional error, that there only can be one instance of eddi running.

## Investigation
I used Firefox and Internet Explorer and reinstalled eddi completly.

Note:
I'm not sure for what i have to loggin into the frontier stuff, but i assume thats what is keeping the "cargo Monitor" from working. it doesnt show anything on multiple relogs, restarts, and ingame events like buying stuff etc.
Also when using any cargo/inventory related commands/variables in the Speech responder, no cargo gets recognized. even the default limpet check doesnt work and never finds my limpets.

**Comment by Tkael** [comment]
There was some sort of weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by simon-winter** [comment]
Ok, thanks that worked and im now logged and conencted correctly.
The cargo monitor and the speech responders variables for cargo related stuffs till not work though

**Comment by Tkael** [comment]
Please try [the latest release](https://github.com/EDCD/EDDI/releases/download/Release%2F3.3.5-rc1/EDDI-3.3.5-rc1.exe)?
Please also be more specific - what specifically isn't working with the cargo monitor?

**Comment by simon-winter** [comment]
I installed new version and have same result.

The cargo monitor tab in eddi doesnt show any cargo and any cargo related commands don't yield any results.
`{set cargo to CargoDetails("Aluminium")}
You have {cargo.total} tonne of {cargo.name} in your cargo hold.`
reads out the text, while skipping the variables completly.

`{set stuff to 0}
{for cargo in inventory:
    {if cargo.name = "Aluminium":
        {set stuff to cargo.total}
    }
}
{stuff } stuff on-board`
reads out: "0 stuff on-board"

the default limpet check doesn't recognize any limpets and tells me i have 0 despite i have some in my cargo.

i tried all writing styles, the event is in "commoditiy purchased" so i'm activly buying said stuff and it doesnt update/work. Relogging, running as administrator etc. tried. I'm connected to the API.
In %Appdata% there is no cargo monitor .json.

and while the eddi.log contains
`2019-02-14T08:38:10 [Info] CargoMonitor:initializeCargoMonitor Initialised Cargo monitor 1.0.0 `

it is missing the cargo monitor variant of this log output:
`2019-02-14T08:38:11 [Info] EDDI:Start Starting keepalive for Mission monitor `

**Comment by Hoodathunk** [comment]
I will look at this on my next opportunity.

**Comment by richardbuckle** [comment]
@simon-winter 

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by richardbuckle** [comment]
Believed fixed in 3.3.5 final, please re-open if not.
