### ISSUE TITLE
EDDI can't Authenticate with Frontier API

### ISSUE THREAD

**Issue by darth-crunchus** [EDCD/EDDI#1180]
## EDDI version in which issue found
EDDI v3.3.4

## Steps to reproduce

1. Start EDDI
2. Click the 'Log in' button under Frontier API

## Expected
Expected Frontier "Authorize or Deny" screen after logging in

## Observed
I got a "Launch Application" dialog with EDDI as the only option, but nothing happens when I click "Open link"; EDDI still reports 'Frontier API connection not operational'

## Investigation
Went back through, version by version, back to version 3.3.3, 3.3.4 rc-2 crashes out when trying to log in, all other rc versions give an eddi link that does nothing when opened.

**Comment by Tkael** [comment]
There was some sort of weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by darth-crunchus** [comment]
Ah, alright, I'll give it a whirl.

**Comment by alphalvr** [comment]
oh my god this has been driving me insane. i only started using using EDDI a couple of days ago and after 1 day and some updates I had the same issue. (unable to authenticate, not logged in) This fixed it.

Thank you thank you.
