### ISSUE TITLE
Swapout-check wants me to replace every module

### ISSUE THREAD

**Issue by kchou94** [EDCD/EDDI#1181]
## EDDI version in which issue found
v3.3.4 w/ Voice Attack

## Steps to reproduce

1. Outfit Imperial Eagle with modules - [here's what I have](https://coriolis.io/outfit/imperial_eagle?code=A2p5t6F5l0d5s9f20r1i1i0l405328m0-.Iw18kA%3D%3D.MwRgDBYExukgsQ%3D%3D.&bn=Hime-sama) for reference
2. Land at station that sells modules - Chelomey Orbital in Cubeo in my case
3. Open station services

## Expected
EDDI notifies me of module savings if any of my modules can be bought cheaper

## Observed
EDDI tells me that practically all of my modules can be bought cheaper, even though the ones being sold are the same price

**Comment by Tkael** [comment]
Are you logged in to the Frontier API? That's where that data is coming from and there was some weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by Hoodathunk** [comment]
Also, update to 3.3.5-rc1, where this issue is specifically addressed.

**Comment by richardbuckle** [comment]
Thanks for the report, I am closing it as a duplicate because it is fixed in 3.3.5-rc1.
