### ISSUE TITLE
Cargo Monitor not working

### ISSUE THREAD

**Issue by simon-winter** [EDCD/EDDI#1183]
## EDDI version in which issue found
3.3.6

## Steps to reproduce
(frontier API is connected)

1. starting eddi
2. starting elite
3. buying stuff at station
(logging out of elite)

## Expected
Cargo Monitor should show cargo,
speech responder should tell infos about cargo items because of custom "commodie purchased" speech responder

## Observed
Neither the cargo monitor nor the speech responder picks up any of my cargo. in eddi the cargo monitor is blank despite being enabled and relogging to elite and buying/selling stuff etc.
i cannot get eddi to recognize any of my cargo. default limpet speech responder also not finds limpets on board.

## Investigation
earlier versions also affected, restarted eversything, relogged everything and reauthorized the Frontier API.

**Comment by Tkael** [comment]
In VoiceAttack or not?
You can try removing your `cargomonitor.json` config file from `%APPDATA%\EDDI`. If you do that and then restart EDDI, is cargo tracked correctly? If so, paste your `cargomonitor.json` file here for review.
Thanks!

**Comment by simon-winter** [comment]
Im not using voice attack, And i don't have a cargomonitor.json. I disabled/enabled the plugin and reinstaled with an appdata wipe. Still no cargomonitor.json. 
In the log, cargomonitor gets "initialized" like the other monitors, but the "keeping alive" logoutput is missing for cargo.

**Comment by Tkael** [comment]
keeping alive is not required for all monitors.

**Comment by Tkael** [comment]
Navigate to `%appdata%\EDDI` and remove `missionmonitor.json` (move it to your desktop). Then restart EDDI and check the cargo monitor. Is cargo tracked correctly when this config file is removed?

**Comment by simon-winter** [comment]
Sorry i'm in holiday and Don't have access to my Computer. I will check back in 4 weeks.
Thank you for your Help!

**Comment by Tkael** [comment]
Should be fixed by PR #1209 (already merged into the next release build). :-)
