### ISSUE TITLE
Frontier API not work on 3.3.6

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#1185]
## EDDI version in which issue found
3.3.6

## Steps to reproduce

1. Update EDDI 3.3.4 to 3.3.6
2. try to login frontier API

## Expected
API works

## Observed
When I use Frontier Login (https://auth.frontierstore.net/...) after put captcha and browser message for goback to EDDI, EDDI shows me the API disconnected.

## Investigation
If I delete CompanionAPI.json the problem persist.

**Comment by hoksilato2** [comment]
OK, I find the solution sorry:

There was some sort of weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:

1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

_Originally posted by @Tkael in https://github.com/EDCD/EDDI/issues/1180#issuecomment-463303194_

**Comment by hoksilato2** [comment]
I think it's important to put into realease comments.

**Comment by Hoodathunk** [comment]
The FDEV cAPI authentication glitch was not specifically an EDDI problem, all apps with cAPI connectivity were similarly affected.

No additional code was required to address the glitch. The bump from 3.3.5 to 3.3.6 addressed an unintentional removal of a specific (and necessary) data element for the cAPI connection, but was not in any way related to the FDEV authentication glitch.

The release comments properly document all relevant changes to EDDI.

The EDDI Team made the community aware of the glitch as soon as we were, and provided instructions for resolving the connection issue, using what we considered to be the proper channels (forum & discord).

**Comment by FireSammy** [comment]
Followed instructions and no. It is stil giving me this message:

![eddi login problem is back](https://user-images.githubusercontent.com/21980416/52879438-ca7b9500-3167-11e9-9777-93f6a4f9b703.JPG)

**Comment by YamabushiGiri** [comment]
> OK, I find the solution sorry:
> 
> There was some sort of weirdness yesterday with the Frontier API connection. If you find that EDDI is refusing to connect to the Frontier API, these steps may help:
> 
> 1. Go to https://auth.frontierstore.net/ and log in.
> 2. Go to the "Authorized Applications" screen and deauthorize EDDI.
> 3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.
> 
> _Originally posted by @Tkael in [#1180 (comment)](https://github.com/EDCD/EDDI/issues/1180#issuecomment-463303194)_

worked, thanks for that
