### ISSUE TITLE
Event stack up with VoiceAttack

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#1186]
## EDDI version in which issue found
EDDI 3.3.6 under VoiceAttack

## Steps to reproduce
When flying around in Elite Dangerous, the voice responder events don't trigger at the moments that the event happens (undock, hyperspace jump, supercruise, drop to normal space, scanned body). Instead, they all get reported a lot later (sometimes seconds, sometimes minutes) all at once.

## Expected
In version 3.3.4, undocking triggered the ((EDDI undocked)) event for VoiceAttack immediately

## Observed
Events don't seem to fire at all. However, sometimes 10 minutes later, they do, all at once.

## Investigation
I uninstalled and reinstalled 3.3.6 to see if that would fix the problem. This yielded no change. Uninstalling and changing back to 3.3.4 immediately fixed the problem.

**Comment by eavdmeer** [comment]
Additional info: VoiceAttack v1.7.3
Using this together with the Verity voice profile from HTC, version Singularity 2.03

**Comment by Tkael** [comment]
Known issue. Combining with #1155 .
Still not entirely sure why this is happening.

**Comment by eavdmeer** [comment]
This may be related, but it's infinitely more severe in 3.3.6. It breaks EDDI events completely. No events seem to bleed through at all. They seem to stack up and then get released all at once. I've gone back to 3.3.4 and all is working like expected (2 hour test). 3..3.6 already doesn't work from the very first undocked event
