### ISSUE TITLE
Frontier API Non-operational (3.3.5-rc2 and 3.3.6)

### ISSUE THREAD

**Issue by rottjr** [EDCD/EDDI#1188]
DUPLICATE of #1185 with more troubleshooting

## EDDI version in which issue found
Occurred in 3.3.5-rc2 and 3.3.6
Running standalone (for API connection process)

## Steps to reproduce

1. Validate Credentials json file is not present (doesn't look like it was ever written)
2. Remove EDDI from authorized programs on frontier website
3. Open EDDI as standalone and navigate to Frontier API tab
4. Click "Login" and receive auth website
5. Login and approved EDDI
Tracked and received eddi://auth/ call
XX At this stage we receive "Only one instance of EDDI can run at a time. Please close the other instance and try again"

## Expected
[describe what you expected to happen]
Expected that EDDI receives the eddi://auth/ call and performs auth operation instead of attempting to open another EDDI

## Observed
EDDI attempts to execute again and ignores the auth function

## Investigation
I have attempted another set of steps as well which include closing EDDI after opening the auth website and before authorizing EDDI in an attempt to allow EDDI to execute and run the auth function. This results in EDDI opening and having no API or auth information.

NOTE: I believe this is an issue with your deep links for eddi:// directly. There needs to be a catch function within the main code file that contains a redirect in the event that the application is on when it receives the eddi://[function]/

**Comment by rottjr** [comment]
I think I may have found the issue. I could be wrong but on line 98 of CompanionAppService.cs it looks like you put Constants.EDDI_URL_PROTOCOL instead of CALLBACK_URL.

**Comment by rottjr** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/2872576/eddi.log)

**Comment by rottjr** [comment]
I have confirmed that frontier is properly sending back a code and state. I was able to capture these in transit and have attempted a force auth via eddi://auth?code=XXX&state=XXX, eddi errors when this is executed while open and opens if closed but does not authenticate.

**Comment by MrStump** [comment]
same here

**Comment by richardbuckle** [comment]
> 
> 
> I think I may have found the issue. I could be wrong but on line 98 of CompanionAppService.cs it looks like you put Constants.EDDI_URL_PROTOCOL instead of CALLBACK_URL.

No, that line is correct. The CustomURLResponder constructor takes the protocol name only, as is documented in this source code.

Authentication is working for most people so it is likely to be something on your local setup. One possibility is that your browser has associated the "eddi" custom URL protocol with the wrong application. The quickest way to test this is to press Windows+R and put `eddi://foo` in the box, and press return. This should launch EDDI.

How to inspect the bindings depends you your browser. In Firefox:
1. Choose Tools/Options.
1. Scroll down to the list box titled "Applications".
1. Find the entry for content type "eddi". It should say "Use EDDI (default). If it doesn't then select "Use other" and navigate to EDDI's location and select it.

Hope this helps.

**Comment by MrStump** [comment]
found solution in neighborhood topic by [hoksilato2](/hoksilato2)
https://github.com/EDCD/EDDI/issues/1185#issuecomment-464124442

**Comment by FireSammy** [comment]
EDDI frontier API Authentication connected! Gool! :)

**Comment by rottjr** [comment]
No dice. I've gone through full OS reinstall on Windows 10 Pro updating to version 10.0.17763 Build 17763 and only installing steam, ED and EDDI. Receive same error about only allowing a single instance, eddi://foo opens EDDI correctly and everything works EXCEPT the frontier API will not authenticate. I even receive the security notification to allow eddi://auth?code=XXX&state=XXX when using Internet Explorer. However every time I authorize EDDI complains about another instance already being active.

**Comment by MrStump** [comment]
You don't need reinstall windows. Go to frontier API page and unauthorise EDDI. As told in link i post earlier.

1 - Go to https://auth.frontierstore.net/ and log in.
2 - Go to the "Authorized Applications" screen and deauthorize EDDI.
3 - Now you should be able to re-authorize EDDI from its "Frontier API" tab.

**Comment by Tkael** [comment]
I'm afraid @rottjr has already tried that. More than once, I think.
@richardbuckle Any thoughts on what to test next?
@rottjr Have you tried logging in from a different machine?

**Comment by richardbuckle** [comment]
In the past we’ve seen damaged files in`%APPDATA%\EDDI` cause EDDI to start up but get stuck as a background process, unable to display GUI. When this happens you can see it in Task Manager. 
So maybe quit any instances of EDDI or VA, kill any stray EDDI processes you see in Task Manager, then rename `%APPDATA%\EDDI` (but keep it on hand in case we need to examine it later).

**Comment by richardbuckle** [comment]
Please retest with 3.3.7-b1

**Comment by Tkael** [comment]
Closing for lack of input since release of 3.3.7-b1. Please reply if this issue persists in 3.3.7-b1 and we will reopen the issue.

**Comment by rottjr** [comment]
This issue is still in 3.3.7-b1 for me. @richardbuckle I fully deleted %appdata%/EDDI multiple times before installation as well as after installation but before running the program.

**Comment by Tkael** [comment]
Re-opened. Would you please post a log file from version 3.3.7-b1 where you attempt to connect to the Frontier API?

**Comment by rottjr** [comment]
It produced two logs, one for the initial instance and one for the instance that attempted to spawn on authorization. Attached
[eddi.log](https://github.com/EDCD/EDDI/files/2998826/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/2998827/eddi1.log)

**Comment by rottjr** [comment]
EDDI v.3.3.7-b2 has resolved the issue. I can now connect EDDI without a problem. Thank you for all the help
