### ISSUE TITLE
Landing event not retrieving info

### ISSUE THREAD

**Issue by JCBurnside** [EDCD/EDDI#119]
When landing (ATM I have only tested it on COL 285 SECTOR ZP-G A40-0 9 A, A land-able moon) and about 40-50% of the time it gives the right coords. the other times it says I am at 0,0. It never says the body name. I will dig into the issue.
CURRENT EDDI VERSION : 2.3.1
happens with touchdown and landing events.
default scripts.

**Comment by Tkael** [comment]
I'll check this out. Please continue to test this with our landable bodies?

**Comment by Tkael** [comment]
This issue seems to occur whenever a touchdown or takeoff event is not player controlled. Examining the journal, it looks like attitude & longitude are not written when the player is not controlling the ship.

**Comment by Tkael** [comment]
Since only the cottle script is changed, I am adding the change directly to develop and closing this issue.

**Comment by Tkael** [comment]
All tested and working well.
