### ISSUE TITLE
VoiceAttack home system variables not set

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1191]
## EDDI version in which issue found
3.3.6 running under Voice Attack

## Steps to reproduce

1. Query VA "Home" variables
- {TXT:Home system}: the name of the home system of the commander, set from EDDI configuration
- {TXT:Home system (spoken)}: the name of the home system of the commander, set from EDDI configuration as would be spoken
- {TXT:Home station}: the name of the home station of the commander in the home system, set from EDDI configuration

## Expected
VA variables set to EDDI home system configuration values

## Observed
VA variables return "not-set"
## Investigation
Cottle `{homesystem.name}` and other homesystem variables appear to set correctly.

**Comment by Tkael** [comment]
Confirmed, though in truth the wiki has become a little out of data on these variables. I've added a fix for this (with updated documentation) to a pending PR.
Home system variables will be accessed exactly like current system variables, except replacing the prefix "System" with "Home system".
