### ISSUE TITLE
Support assignable speech priority and make EDDI system messages high priority.

### ISSUE THREAD

**Issue by clinkingdog** [EDCD/EDDI#1192]
## EDDI version in which issue found
3.3.6 - running standalone when issue noticed but normally I run in VoiceAttack

## Steps to reproduce

1. Load an old version of EDDI (I think I was going from 3.3.1), standalone to allow upgrades
2. EDDI voice announces that a mandatory upgrade is necessary
3. Click to upgrade EDDI

## Expected
Upgrade completes and important EDDI voice messages about the upgrade are relayed immediately, overriding less important info like the Galnet readout.

## Observed
Galnet articles were read out, taking quite a long time as I haven't been playing for a while (hence being a few versions out-of-date). Only at the end of that process, once I'd already worked out how to get through the upgrade, did I get EDDI voice messages like:
"Upgrading"
"Please enter your authentication details on the Frontier website"
"Upgrade complete"
... and a few other non-upgrade-related things I'd asked for (e.g. voice tests) to see if I could make EDDI respond.

IMO ideally Galnet would pause when there are more urgent messages coming through, and resume after. As a workaround, having a "that's enough" button in the Galnet Monitor tab, so users can shut it up manually, would help. (I'm aware there's a VoiceAttack command that will do this, but AIUI that's not accessible when running upgrades as they have to be run in standalone EDDI.)

**Comment by Tkael** [comment]
There's already an issue for a standalone "shut up" button, see #197.
Otherwise, it sounds like you are talking about a speech priority system. I'm going to re-title this issue as such.

**Comment by Tkael** [comment]
EDDI already includes some basic foundations for speech priority, but jgm never developed these into a full fledged feature. This is an area that we've wanted to explore.
