### ISSUE TITLE
EDDI is really great

### ISSUE THREAD

**Issue by clinkingdog** [EDCD/EDDI#1193]
## EDDI version in which issue found
All

## Steps to reproduce

1. Use EDDI

## Expected
EDDI is decent.

## Observed
EDDI is amazing, with tons of useful functionality and very few bugs, and it's smooth to use and keeps evolving and improving.

## Investigation
(I just wanted to say thanks and didn't know where else to do so :P Thank you, team!)

**Comment by Tkael** [comment]
Thanks for the positive feedback. 💯 :-)
