### ISSUE TITLE
version 3.3.6 of EDDI causing VA to use 80%+ CPU

### ISSUE THREAD

**Issue by MalicT** [EDCD/EDDI#1194]
## EDDI version in which issue found
3.3.6

## Steps to reproduce

EDDI version 3.3.6

Running EDDI standalone is fine

Running VA without EDDI plugin activated it runs fine (less then 0.2% CPU)

Running VA with EDDI after 15-20 mins, causes VA to use 80%+ CPU when idle with nothing else running.

Same behavior as previous issue https://github.com/EDCD/EDDI/issues/747

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]
3.3.5 has same extreme use CPU behavior (10% CPU on startup and keeps climbing until computer stops responding to things)

3.3.4 voice attack runs like normal (less then 0.2% CPU)

**Comment by MalicT** [comment]
EDDI version 3.3.6

Running EDDI standalone is fine

Running VA without EDDI plugin activated it runs fine (less then 0.2% CPU)

Running VA with EDDI after 15-20 mins, causes VA to use 80%+ CPU when idle with nothing else running.


Same behavior as previous issue https://github.com/EDCD/EDDI/issues/747

**Comment by Tkael** [comment]
We're aware of this issue and already have a fix in place for the next release. Essentially, we had to tidy up some looping code. Thanks for the report.

**Comment by MalicT** [comment]
Any update on when this fix is going to be pushed out?  3.3.5 and 3.3.6 are unusable with VA because it pushes VA CPU use over anything else on the PC

**Comment by amadeus1171** [comment]
Yield() is your friend.
