### ISSUE TITLE
Not a Problem, more of a request

### ISSUE THREAD

**Issue by Trelos78** [EDCD/EDDI#1212]
Hey all
Firstly, have loved using EDDI for a while now.
Only have 1 request.  Instead of listing distance from home system, would it be possible to say how many jumps remaining from our destination ?

**Comment by Tkael** [comment]
Not possible at the moment. We don't receive complete route information from FDev. We can see the next system in the route, no more.

**Comment by Tkael** [comment]
Tagging as invalid, unfortunately. We can't provide this with the information FDev makes available.
