### ISSUE TITLE
Most EDDI voiceattack events don't trigger

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#1215]
## EDDI version in which issue found
EDDi 3.3.6 under VoiceAttack

I have reported this issue before: Event stack up with VoiceAttack (#1186) but it was closed without a resolution as a duplicate of an issue that does not look related at all.

## Steps to reproduce
1. Install the EDDI VoiceAttack 3.3.6 plugin and import the EDDI profile
2. Create your own profile with the following commands:
 ((EDDI docked))
 ((EDDI undocked))
 ((EDDI entered normal space))
 ((EDDI entered supercruise))
 ((EDDI landing gear))
 ((EDDI ship fsd))
 ((EDDI undocked))
3. Load Elite Dangerous, undock, jump so supercruise, turn around, drop to normal space and dock back at the station.

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
Expected events to fire are
1. ((EDDI undocked))
2. ((EDDI landing gear))
3, ((EDDI ship fsd))
4. ((EDDI entered supercruise))
5. ((EDDI entered normal space))
6. ((EDDI landing gear))
7. ((EDDI docked))

## Observed
2. ((EDDI landing gear))
3, ((EDDI ship fsd))
6. ((EDDI landing gear))

Then, about 5 minutes later, all queued up events burst in all at once.

## Investigation
No problems whatsoever with EDDI 3.3.4 installed

**Comment by Tkael** [comment]
Investigation into these issues hasn't ceased. We're still working on this.

**Comment by FireSammy** [comment]
Similar issues. Adding to that, my CPU is screaming at 90-100% after opening the Elite Client with VA on. Nothing i do will make it ease down, other than closing the VA.

**Comment by Tkael** [comment]
We're aware of that one too. A new release is close to being ready.

**Comment by richardbuckle** [comment]
Fixed in 3.3.7-b1

**Comment by dupsatou** [comment]
I am experiencing this issue pretty much exactly on EDDI 4.0.1 as a plugin in Voice Attack.  It's preventing some of my profiles from running because they hang in a loop waiting for the proper responses from EDDI and its not getting them.
