### ISSUE TITLE
VoiceAttack crashing after two minutes (EDDI/Galnet Bug)

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1218]
Version 3.3.6

Contacted VA Forum on VA crashing two minutes after start. 

They report it is EDDI Galnet causing the crash.

VA Forum Issue: https://forum.voiceattack.com/smf/index.php?topic=2544.msg11645#msg11645

They recommend that I disable Galnet in EDDI to solve this issue.

If you read the VA Bug (now a Sticky on their forum) they are well aware of this bug.

Advice?

**Comment by Tkael** [comment]
The same. Disable the Galnet monitor until the next release. See #1216. Closing as a duplicate.
