### ISSUE TITLE
Honour settings changes immediately without requiring app restart

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#122]
## Steps to reproduce

1. Change your home star system in EDDI's "Commander Details" tab.
2. Tweak the "FSD Engaged" script to always mention your home system's name.
3. Jump.

## Expected
The new home system to be honored immediately.

## Observed
The new home system is not honored until the app is restarted.

## Investigation
The problem lies with the event responders such as `EDDI.MainWindow.homeSystemChanged()` in `MainWindow.xaml.cs`. These are writing the config to disk but are not dynamically updating the in-memory structures.

**Comment by Tkael** [comment]
Submitted on PR #275, closed as complete pending approval.
