### ISSUE TITLE
Can't install EDDI 3.3.7-a1 (and older versions also not) ! Who blocks the installation ?

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1225]
## EDDI version 3.3.7-a1 and older (tested to v3.3)
* Win10 64bit v1803 build 17134.590

## Steps to reproduce
* last functional version 3.3.6 uninstalled
* deleted all directories of the old installation ( EDDI-directory in VoiceAttack, c:\Users\username\AppData\Roaming\EDDI, c:\Users\Flitzipaldi\AppData\Local\EDDI )

## Expected
* starting the installation

## Observed
* nothing, no Error, no window

## Investigation
* Installation of older versions tested to V3.3, each no reaction

The last updates (3.3.4> 3.3.5> 3.3.6) all worked (update via EDDI).

**Comment by nepomuk16321** [comment]
Just tested, installation of 3.1.2 starts!

**Comment by nepomuk16321** [comment]
Hello,
good news for me. About the PowerShell I could now install v3.3.6. The PowerShell made the mistake that is probably wrong with the path. I was able to start the installation with the command ".\EDDI-3.3.6.exe". Why does not Windows find the path and where could I set it? Can someone help me there?
Sorry, only in German
![image](https://user-images.githubusercontent.com/20616775/53758681-b8675980-3ebe-11e9-9495-39652e8567af.png)

**Comment by Tkael** [comment]
I'm sorry, but I don't understand the error message and I'm not very familiar with PowerShell. Can you please try again to explain what went wrong?

**Comment by nepomuk16321** [comment]
Hi Tkael,
my english is not good but i would like to try it.

* I wanted to test v3.3.7-a1 for translations
* I therefore uninstalled my version 3.3.6 and deleted all related directories (plug-in in VA and "... AppData\Roaming\EDDI")
* then I downloaded the version 3.3.7-a1 from GitHub and saved it on the desktop
* Double click on the icon EDDI-3.3.7-a1 and NOTHING happened
* I remembered the CMD command or the PowerShell
* I used the PowerShell and maneuvered to the installation file on the desktop (cd c:\...)
* Then the EXE was called and I got the error described above
* the ERROR says the file exists but the path does not exist, try using ".\File.exe" to start the file
* and that worked
* I'm pretty sure the error is due to my Windows installation, but I do not know how to fix it
* And the question remains, why can I install the version 3.1.2 normally with a double-click on the icon. The file is in the same directory as EDDI-3.3.7-a1.
* I tried the installation again with the command prompt (CMD command)
* With call of the EXE over k:\directory1\directory2\EDDI\EDDI-3.3.7-a1.exe (my archive) it worked then immediately

So, I hope you can do something with these lines. I hope so. :-)
The issue can now be closed.
Maybe you also have an idea how to fix my Windows problem. Thank you in advance !

Greetings nepomuk

**Comment by Tkael** [comment]
It could have something to do with registry values that we need to write to make the Frontier API work.

If you are having trouble with Windows, I'd suggest https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system
