### ISSUE TITLE
EDDI sending me to the wrong station on EDDB

### ISSUE THREAD

**Issue by highflyersnl** [EDCD/EDDI#1226]
## EDDI version in which issue found
3.3.6 with voice attack

## Steps to reproduce
when I am logged on and want to get my market data from the station I am on I tell EDDI to show the station on EDDB but every time I get the wrong station. now if I ask it to show the system gets it right but not the station. also in travel between systems, it does not update the system report.

**Comment by Tkael** [comment]
Please be as specific as possible. Which station did you expect? Which station did you receive? Did EDDI open another station in the same system or was it from a different system? Was it a station from another system with the same name?

**Comment by highflyersnl** [comment]
it doesn't matter which station I am at it does it with all station but in this case, I was at seares port in mu horologii and Eddi put eddb in as https://eddb.io/station/10212 Station Thuot Gateway in Aura i cant get more specific as this.

**Comment by Tkael** [comment]
Hmm. Seares Port has an EDDBID of 1897 while Thuot Gateway has an EDDBID of 10212 (according to the server). So the server data does have unique EDDBIDs that shouldn't cross over like that.

Had you previously visited Thuot Gateway?
Were you docked at the time you made the request?

**Comment by highflyersnl** [comment]
no never been to aura so never been to that station.
Yes, I was docked. 
Yes, I am logged on to the frontier API and with the same account.
I even went and checked my browser history and all because when the app did not load the right station I got my back up app market connector to send me to the correct station, so i can check my history and see two webpages back to back that go to two different stations.

**Comment by richardbuckle** [comment]
Please retest with EDDI 3.3.7-b1 as several timing issues have been resolved.

**Comment by highflyersnl** [comment]
well I tried it with 3.3.7-b1 just a moment ago and right after log in i asked eddi to show the station in EDDB and it voiced the right station but it sends me to https://eddb.io/station/15519 Culpeper port in Ute while i am at maunders vision in Phracani https://eddb.io/station/36247. so it seems like it has not been solved.

**Comment by Tkael** [comment]
Does this only happen shortly after loading EDDI? If so, it's probably still loading events from your last play session. Could you please test by waiting for the CPU to calm down after EDDI finishes loading, waiting a couple of extra minutes, and them repeating your request?
If this is the cause, we may need to disable the VA function until the log load is complete.

**Comment by highflyersnl** [comment]
It happens all the time it doent matter how long i wait or even if i go to another station. Just keeps giving another station then the one i am at. So right now i only use it to in a way go to windows desktop and firefox then use mc to get to the correct station in eddb.

**Comment by Tkael** [comment]
@Hoodathunk Would you mind taking a look at this? Since I'm on DWE2 and sans second account, it's rather difficult for me to replicate this one.

**Comment by Hoodathunk** [comment]
Yep, I'll take this one.

**Comment by Hoodathunk** [comment]
I found the issue and will have a submit a PR.

**Comment by highflyersnl** [comment]
Wow thanks i was beginning to think it was only happening to me. You guys realy rock.

**Comment by richardbuckle** [comment]
Fixed for 3.3.7.b2.
