### ISSUE TITLE
Unscanned system script?

### ISSUE THREAD

**Issue by luzclasil** [EDCD/EDDI#1227]
I need I script that warns me if I jump to a brand new system, but once I'm terrible with programming I definitely need some help. 
Or maybe this exists already, any heads up?

Thanks to all and I apologize in advance if I'm posting at the wrong place.

**Comment by Tkael** [comment]
I'm not sure what you mean? As in, entirely unscanned / undiscovered? There's no flag for that in the data we receive from FDev.

**Comment by luzclasil** [comment]
> I'm not sure what you mean? As in, entirely unscanned / undiscovered? There's no flag for that in the data we receive from FDev.

Yep, I'm sorry for my sloppy wording but you got it right. I'd like to be able to know if I've popped inside an undiscovered system without having to check system map every time. That would come in handy especially now that I'm trying to find new undiscovered systems nearby the bubble.

If there's no flag that means I'm hopeless, right? :(

Thanks for your quick reply!

**Comment by Tkael** [comment]
Unfortunately, we don't have a flag for that one. Sorry we couldn't help.

**Comment by luzclasil** [comment]
What if we cross-reference EDSM instead? Like if the system is not present in their database than consider as unexplored. No doubt it would't be ideal but might be better than nothing. Just a thought.

**Comment by Tkael** [comment]
That's more possible, but there's less utility there I think. 
The easiest way to determine whether a system is undiscovered in-game is pretty simple so I'm not sure this is needed. All you have to do is compare the number of bodies found by your honk to the number of bodies visible in your HUD map. If there are more bodies than the HUD map / system map shows then there are unexplored bodies in the system.

**Comment by luzclasil** [comment]
Yeah, I agree that it's quite simple but still not as convenient as a voice telling you right away, you know. Especially when you're jumping to literally hundreds of systems that may or may not have already been explored since you're nearby the bubble. In that case most have already been but there's always that last % which has not. Having to d-scan then hud every time is cumbersome and I fell like a voice responder script could improve our overall experience and make it a lot faster. Saving a few seconds here and there becomes hours in the long run...
That's my personal experience speaking - it's all good if you disagree, though.
