### ISSUE TITLE
VA command 'configure EDDI' and selecting the Ship Monitor -page will crash the EDDI API

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#1233]
## EDDI version in which issue found
EDDI v.3.3.6 with VA v1.7.3.5 (prerelease)

## Steps to reproduce
Opening EDDI API with given VA command 'configure EDDI' and selecting the Ship Monitor -page will crash the EDDI API. VA seems to keep working normally.

## Expected
To see the normal list of my ships etc. stats in the EDDI API Ship Monitor -page

## Observed
The window remains open but not responding at all. Once i left it open for many minutes and then it opened the Ship Monitor page and it looks utterly bugged and will then show the page 'Not Responding' on the top left bar (check pic's)

## Investigation
Worked fine with earlier versions. EDDI API standalone Ship Monitor -page seems to work normally

Plz: check this link too: https://github.com/EDCD/EDDI/issues/1182

Note: Galnet Monitor is off -plugin disabled, because of earlier bugs/problems
Changed the export  -ship's data from Coriolis to EDShipyard. This made the "hang" -waiting time clearly less but the end result is the same. The page will not respond and will crash. Needs to close the VA and if indeed not want to wait for the EDDI api to give the "red X' closing option, one needs to restart the whole PC

![EDDI Ship monitor page crash 1](https://user-images.githubusercontent.com/21980416/54068819-5cebf180-4259-11e9-98f7-c3bf3d8ecbc4.JPG)

![EDDI Ship monitor page crash](https://user-images.githubusercontent.com/21980416/54068824-61180f00-4259-11e9-9195-27d94a5ae94a.JPG)

**Comment by Tkael** [comment]
A new release fixing this issue is imminent.

**Comment by richardbuckle** [comment]
@FireSammy please re-test with 3.3.7-b1.

**Comment by FireSammy** [comment]
Updated and working. Great job guys!
Note: Some events still missing at login, such as file header and location but that's a different issue. Everything else checked in faster than ever before. Check pic plz.

![Update and EDDI start 10 3 1019](https://user-images.githubusercontent.com/21980416/54081943-2d4eef00-4316-11e9-8b58-a4e9c87d53bd.JPG)

**Comment by Tkael** [comment]
We intentionally don't trigger VoiceAttack events when we're loading an active journal file - we don't want to trigger a very high number of events in rapid succession, nor do we want to write and then immediately overwrite variables we don't need to.
Please open VoiceAttack before launching Elite Dangerous if you want to capture 100% of EDDI's events in VoiceAttack.

**Comment by FireSammy** [comment]
Well, i never EVER launch the game before VA. VA command string will launch my game and all the other applications i use with it/when gaming with a carefully tested sequence.

I would actually prefer less event commands to be triggered while the ED is still on the loading screen. It would help a lot on some things, but it's not a big problem. The bigger problem is that the ((EDDI Location)) not triggering at all at login.

**Comment by Tkael** [comment]
I found and am submitting a bug to fix missing file header events when Elite is restarted with EDDI running.

I suspect what you are describing with ((EDDI location)) is the same concern described by #966... we only write ((EDDI location)) once and suppress rewrites for the reasons described by that issue.
