### ISSUE TITLE
Script 'Test' buttons not working in 3.3.7-b1

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1234]
## EDDI version in which issue found
EDDI V3.3.7-b1, standalone and under VA.

## Steps to reproduce
Click the 'Test' buttons next to scripts in Speech Responder, or on the edit script windows.

## Expected
The script to run as if it had been executed by an event, or just execute for those script not tied to any events.

## Observed
Silence. Nothing is spoken, even when creating a test script with just "Hello" in it.

## Investigation
From my forum post... "Under VA and standalone, none of the script 'Test' buttons work, either next to the script name in Speech Responder, or on the edit script pages. I've reloaded a few times, and tried with and without VA, but no luck at all, everything remains silent. Running commands in VA that execute the scripts works fine still and the volume sliders are at normal 50%. Other speech works like hearing your ship names. Tried 3.3.6 again and the test buttons work fine. Back to 3.3.7-b1 and silence."

**Comment by richardbuckle** [comment]
Reproduced

**Comment by Darkcyde13** [comment]
I just looked at my speechresponder.out file, and it seems all the speech from the clicking of the test button was still be written to the file, just not coming out as actual speech.

**Comment by Tkael** [comment]
I've got this one.
