### ISSUE TITLE
Speech responder: cannot sort by priority and enabled

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1236]
## Expected
Click the enabled or priority header to sort as usual.

## Observed
Click does nothing.

**Comment by Tkael** [comment]
```
                <DataGridTemplateColumn x:Name="Priorities" Header="{x:Static resx:SpeechResponder.header_priority}" CanUserSort="True" SortMemberPath="Priority">
```
Adding `CanUserSort="True" SortMemberPath="Priority"` gets us part of the way there but not the whole way. `DataGridTemplateColumn` doesn't handle refreshing data on sorts well.
