### ISSUE TITLE
Speech responder help link broken

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1237]
## EDDI version in which issue found
3.3.7-b1

## Steps to reproduce
On Speech Responder, click "here" in the top explanatory text.

## Expected
Window with text content.

## Observed
Window with blank content.

**Comment by Tkael** [comment]
Odd? Working for me.

**Comment by Hoodathunk** [comment]
Working fine 3.4.0.

**Comment by bid** [comment]
No, it's not working with 3.4.0. I have the same problem: Clicking the link opens a window (which I assume should show the help), but that window is just white and doesn't show any content.

**Comment by Tkael** [comment]
Hmm. Clearly there's something weird going on then. Some of us can open it without any problems and others cannot.

**Comment by Tkael** [comment]
@richardbuckle Since you seem to have been having this same problem, would you mind stepping through the code to see what's going on?

**Comment by richardbuckle** [comment]
I'll have a look. Mine is working in debug under VS but broken in the installed release build. Could be an installer issue.

**Comment by richardbuckle** [comment]
Confirmed that bug is because `SpeechResponderHelp.md` is not copied to install dir.

**Comment by richardbuckle** [comment]
Fixed for next version.
