### ISSUE TITLE
Feature Request - System Scan Complete

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1239]
I wasn't sure if this is quite the right place to request this, and I have a feeling it's been asked before, but could we possibly have an event for when a system has been fully scanned?

I seem to remember someone saying that the journal doesn't get an event written for several (many?) seconds after all bodies have been scanned, and this is why EDDI doesn't have it.  However, I've just looked at my journal while checking something else and found that the entry for a completed system scan happens at the same time as the last body is scanned.  So not sure if this is something that FD have 'fixed' without telling anyone?

My journal entries:-
```
{ "timestamp":"2019-03-10T16:09:36Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"Dumbae DN-I d10-6057 1 l", "BodyID":27, "Parents":[ {"Planet":10}, {"Star":0} ], "DistanceFromArrivalLS":2010.524536, "TidalLock":false, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.022433, "Radius":2476317.500000, "SurfaceGravity":1.458109, "SurfaceTemperature":112.071358, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":27.104095 }, { "Name":"carbon", "Percent":22.791737 }, { "Name":"phosphorus", "Percent":14.591661 }, { "Name":"iron", "Percent":12.346003 }, { "Name":"nickel", "Percent":9.337999 }, { "Name":"manganese", "Percent":5.098773 }, { "Name":"zinc", "Percent":3.355182 }, { "Name":"germanium", "Percent":3.231764 }, { "Name":"tellurium", "Percent":0.837033 }, { "Name":"tin", "Percent":0.766623 }, { "Name":"mercury", "Percent":0.539130 } ], "Composition":{ "Ice":0.862593, "Rock":0.118006, "Metal":0.019401 }, "SemiMajorAxis":12105342976.000000, "Eccentricity":0.000000, "OrbitalInclination":82.935303, "Periapsis":198.217239, "OrbitalPeriod":21296678.000000, "RotationPeriod":183546.640625, "AxialTilt":-0.451612 }
{ "timestamp":"2019-03-10T16:09:36Z", "event":"FSSAllBodiesFound", "SystemName":"Dumbae DN-I d10-6057", "SystemAddress":208127228285531, "Count":19 }
```
Having such an event would help enormously with automating my mapping system I've been working on. :)

**Comment by lagoth** [comment]
I have some working code for the event. I'll work on a pull request here in a bit.

**Comment by Darkcyde13** [comment]
Thank you everyone for all your work on this. It's very much appreciated. :)

**Comment by Tkael** [comment]
I expect this to be in the next beta... 🙂
