### ISSUE TITLE
coriolis export not work

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#1240]
## EDDI version in which issue found
3.3.7-b1

## Steps to reproduce

1. VoiceAttack plugin context 'coriolis'
2. Using export button in ship monitor

## Expected
open Coriolis with ship exported

## Observed
only open a blank browser window
I don't use EDShipyard but, I think occurs the same thing.

Thanks :-)

**Comment by Darkcyde13** [comment]
What browser are you using?  This doesn't work with MS Edge, at least it's never worked for me with Edge.  I don't think it works with Internet Explorer either.  Something to do with not being able to pass such a long web address string to the browser for security reasons (that's a browser limitation, not EDDI).

I've not tried Firefox or Chrome, so I can't comment on those.

**Comment by Tkael** [comment]
Please post your shipmonitor.json (from `%appdata%/EDDI` and indicate the browser you are using. Most likely it's an issue with character limits in the browser causing data to be cut off and consequently causing Coriolis to receive partial data. If so, I'm afraid this may be a limitation of the current implementation of Coriolis.

**Comment by hoksilato2** [comment]
Sorry. With Chrome or Brave, works perfectly. The problem is Edge :-( Well, in future Edge will be chromium. I close the ticket. Thanks for all.
