### ISSUE TITLE
Cannot enter system "Ix" in CMDR details

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1241]
## EDDI version in which issue found
3.3.7-b1

## Steps to reproduce

1. Go to Commander Details tab
2. Try to entry system "Ix" for home system and squadron system

## Expected
System name accepted (blue border)

## Observed
System name rejected (red border) and cannot be entered

## Investigation
[Forum thread](https://forums.frontier.co.uk/showthread.php/387955-EDDI-3-3-Bring-your-cockpit-to-life?p=7466797&viewfull=1#post7466797)

**Comment by richardbuckle** [comment]
Manually entering "Ix" in `%APPDATA%\EDDI\eddi.json` causes the validation code to reject it too.

**Comment by Hoodathunk** [comment]
This is my code, I'll take it.

**Comment by richardbuckle** [comment]
Fixed by #1248
