### ISSUE TITLE
EDSM flight logs not being uploaded

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1247]
## EDDI version in which issue found
EDDI V3.3.7-b1 under VA

## Steps to reproduce
Travel the galaxy with the EDSM plugin enabled and active.

## Expected
Flight logs to be uploaded to EDSM and available to view on their website.

## Observed
No logs available to view.

## Investigation
I visited Sag A* on the 15th (I know, I'm a week behind in the DW2 expedition) and wanted to register my visit in the forums Sag A* visitor list thread.  As evidence they say you can use your EDSM log, so I went to the site and discovered that since upgrading to 3.3.7-b1 (from 3.3.6) none of my logs have been uploaded.

I've just reinstalled 3.3.6, loaded into game, and now my last couple of jumps have been uploaded.  So I'm still missing a gap of over 1000Ly worth of travel to the centre.  I've jumped back to Sag A* and it's been logged in EDSM as expected.

I've now tried 3.3.7-b1 again, done a couple of jumps around Sag A, and nothing has been logged.  Back to 3.3.6, a couple more jumps, and all logged as expected.

**Comment by Hoodathunk** [comment]
This is intended. Beta versions of EDDI do not send EDSM logs or EDDN messages. This was implemented at the beginning of the chapter 4 release due to concerns of betas sending faulty data to the database.

**Comment by Darkcyde13** [comment]
Ahh ok, my bad. I'll close this then.

**Comment by Hoodathunk** [comment]
No worries. Was fairly certain that message got out, but apparently not fully. Apologies for the confusion.
