### ISSUE TITLE
Request for feature/variable: Services seems to be listed in station info (system map)

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#1257]
Hi
Like the header suggests, the stations in system maps are listing 'Services' and i would recon this would equal as the 'General Services' in the Station Services menu behind the 'Advanced Maintenance' selection. If i got it wrong, please correct me.

If indeed i got it correct, i humbly request new variable for EDDI to check IF only possible -similar to this variable: **{BOOL:Last station has refuel}: true if this station has refuel capability**

Adding to that, i would also request us having all possible new station services listed available with similar variables IF only possible, Cheers!! :)

**Comment by lagoth** [comment]
Hi FireSammy,

I'm not one of the developers on the project, but I'm trying to contribute where I can. I'm not clear on what you're looking for, but I'd like to help you out.

The three 'General Services' are 'Repair', 'Restock', and 'Fuel Store'. They correspond to the 'Quick Maintenance' options to 'Refuel All', 'Repair All', and 'Restock All'. They have corresponding Voice Attack/EDDI variables like you note: 
`{BOOL:Last station has refuel}: true if this station has refuel capability`
`{BOOL:Last station has rearm}: true if this station has rearm capability`
`{BOOL:Last station has repair}: true if this station has repair capability`

Currently there are also VA/EDDI variables for 'Market', 'Black Market', 'Outfitting', and 'Shipyard'. Are you looking for more variables to be added, like for 'Crew Lounge', 'Tech Broker', 'Remote Workshop'?

**Comment by Hoodathunk** [comment]
@FireSammy All station services are available via Cottle, using the `StationDetails()` function. The `station` object has a `stationservices` property, which is a list of strings containing all available station services.

CPU utilization creep is becoming an issue and we have to be increasingly selective on the variables we make directly available to VA.

If you're looking for a specific station service to track via VA, you can write and call a Cottle script from VA (external plugin function) which will set a variable that is accessible to VA using the Cottle `SetState()` function.

**Comment by FireSammy** [comment]
> you can write and call a Cottle script from VA (external plugin function) which will set a variable that is accessible to VA using the Cottle `SetState()` function.

Thx for the suggestion, but i do not have the skill's to do/call Cottle scripts -etc... Some day i i'll try to learn that thing, but currently it's just out of question as i barely have time to handle/update the 'traditonal' VA upadates etc.
for my profile. cheers.

> Are you looking for more variables to be added, like for 'Crew Lounge', 'Tech Broker', 'Remote Workshop'?

Yes i am. All of them. Especially the 'Advanced Maintenance' -check if it is available or not. As it is not available in all stations due to size and/or status of the station etc... I hope you understand what i mean, cheers

**Comment by Tkael** [comment]
The station services we are able to see are those listed under the system map. As you can see, they are not 1:1 with the station menu you see when you are docked. Some are always applicable, some seem to serve no function at the moment. 
Do you know which service corresponds to "Advanced Maintenance"?

**Comment by FireSammy** [comment]
> The station services we are able to see are those listed under the system map. As you can see, they are not 1:1 with the station menu you see when you are docked. Some are always applicable, some seem to serve no function at the moment.

I imagined all available variables are/have been there. Still i dare to hope for more lol

> Do you know which service corresponds to "Advanced Maintenance"?
I'm sorry i really cannot say anything for sure. The 'Services' seems to suggest it might be the one i/we are looking for...? Just a wild guess, that's all.

**Comment by Tkael** [comment]
It looks like `Workshop` is probably be available wherever we have `Outfitting`, so there's no need to add another variable for that. 
I'm not sure whether there is a service that corresponds to "Advanced Maintenance". Please let us know if you are able to learn more about this.

You need to make a stronger case for the addition of these variables (particularly after rejecting @Hoodathunk 's recommended solution). Can you give an example of how they will be used?

**Comment by lagoth** [comment]
I've visited a dozen different stations trying to figure out if there's any indicator when an "Advanced Maintenance" equivalent appears in the station services list of the Docked journal event. I haven't yet found any correlation.

**Comment by Tkael** [comment]
Thanks for the update @lagoth . Do you want to keep this issue open while you search a little more? 
What are you trying to accomplish with "Advanced Maintenance"?

**Comment by FireSammy** [comment]
Sorry for not answering sooner. My goal is to automate basically all maintenance and restock services after docking. I have everything working already quite well, but will/can have some serious problems if/when indeed i cannot check if the advanced maintenance menu is available in a station. For example, the limpets cannot be restocked via quick maintenance restock. They can be restocked only via the advanced maintenance menu -as you are aware sir.

**Comment by Tkael** [comment]
What about the `Restock` service? I don't remember if there are stations out there that allow you to purchase ammo but not limpets.

**Comment by FireSammy** [comment]
Maybe this has changed. i have not visited any small stations in a long time, because what i'm currently doing now, but that is not the issue. As far as i recall, all the quick maintenance can be available, but the advanced maintenance not. This considers the smaller platforms usually. Bigger stations can be in a lockdown etc. which can be of course be checked via station status variables, but yeah.

It would simply be great to have this check variable feature available. Even greater if indeed this could be done already when targeting the station in supercruise, but i understand if/when this thing would be impossible.

**Comment by Tkael** [comment]
As long as we can identify an appropriate station service for this, it's possible. Without that, I'm afraid we're going to have to table this for now. 
Reply here if you find out any new information... I'll get the ping and re-open this issue.
