### ISSUE TITLE
Suggestion: "Close to system tray" option.

### ISSUE THREAD

**Issue by JetsonRING** [EDCD/EDDI#1258]
v3.3.6

Simply a suggestion to add a "close to system tray" option so that when a user clicks "X" to close the EDDI window, EDDI is not running minimized in the task bar but in the system tray the same way VA does.

A "Start when Windows starts" option would be nice too.

**Comment by richardbuckle** [comment]
EDDI is an application not a utility so I am not convinced it should be running invisibly all the time. Also, if VA users selected such an option it would conflict with VA running EDDI as a plugin.

Incidentally, [Microsoft no longer recommend that usage of the system tray](https://docs.microsoft.com/en-us/windows/desktop/uxguide/winenv-notification).
