### ISSUE TITLE
Feature Request - Body Radius

### ISSUE THREAD

**Issue by CmdrCienkiBolek** [EDCD/EDDI#1259]
Hello,
According to variables:
{DEC:Status latitude} a decimal value indicating the ship's current latitude (if near a surface)
{DEC:Status longitude} a decimal value indicating the ship's current longitude (if near a surface)
{DEC:Status altitude} a decimal value indicating the ship's current altitude (if in flight near a surface)
{DEC:Status heading} a decimal value indicating the ship's current heading (if near a surface)

please add variable:
{DEC:Status radius} a decimal value indicating the body's radius (if near a surface)

It will be helpfull for planet navigation (bearing) plugin for VA (under my development).

**Comment by Hoodathunk** [comment]
Status variables are specific to the `Status.json` file, periodically updated by FDEV. It would be inappropriate to add a static `Body` variable, easily available using alternate means, to the dynamic `Status` data set.

May I suggest you use the `Near surface' event within Cottle to set/clear a variable available to VA containing the body radius, using the Cottle `SetState()` function.

**Comment by lagoth** [comment]
Assuming you were to scan the planet before you arrive, you could get the radius from the [Body Scanned event](https://github.com/EDCD/EDDI/wiki/Body-scanned-event).

`{DEC:EDDI body scanned radius}` The radius of the body that has been scanned, in kilometres.

**Comment by richardbuckle** [comment]
Placing on hold because of forthcoming changes that I am not at liberty to disclose.

**Comment by Tkael** [comment]
@richardbuckle Please take another look at this? I don't think the changes we received with journal manual v25 for status.json address this case. The best solution, in my opinion, uses the methods @Hoodathunk and @lagoth recommended.

**Comment by Tkael** [comment]
Never mind, looks like a change dropped in today's patch notes that'll be applicable here:
```
Include BodyName and radius in Status.json file, when in SRV
```
