### ISSUE TITLE
Mission script doesn't apply the P() function to station type

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1264]
## EDDI version in which issue is found
3.3.7-b2

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Accept a mission to an Orbis starport
2. Jump to the system with that starport

## Expected
Mission report should use the `P()` function on the station type to ensure correct pronunciation.

## Observed
"Orbis" is mispronounced as "Orbise".

## Investigation
Text output (all instances of "Orbis" should be corrected to "Or-bis" via the `P()` function):
```
Information: L T T 6 7 7 4 is undergoing a boom; there might be some good trading profits to be made here.   There are 3 missions here.  1 depot mission at Orbis Starport, Dirac Gateway, 1 active mission at Orbis Starport, Kotov City and 1 active mission at Outpost, Ramelli Terminal.
 Flatulent Assassin has left supercruise near Or-bis Starport, Kotov City  You have 1 active mission at this station..
 Landing pad 3 is at six o'clock far, as you enter with the green lights on your right.
```

**Comment by richardbuckle** [comment]
@Hoodathunk Could you take a look please? I couldn't immediately spot the script that needs to be tweaked.

**Comment by Darkcyde13** [comment]
It's the Mission Check System script, near to the bottom.  This section of code:-
```
                mission{if total > 1:s}
                {if len(stations_here) = 1: {if total > 1: are |else: is}} at
                {station.model}, {stations_here[cur]}
                {set cur to cur + 1}
                {if cur = len(stations_here)-1: and |elif cur < len(stations_here): ,}
            }.
```
Sounds like the station model just needs to be put inside P(), like this:-
```
                mission{if total > 1:s}
                {if len(stations_here) = 1: {if total > 1: are |else: is}} at
                {P(station.model)}, {stations_here[cur]}
                {set cur to cur + 1}
                {if cur = len(stations_here)-1: and |elif cur < len(stations_here): ,}
            }.
```

**Comment by richardbuckle** [comment]
Much obliged, @Darkcyde13, I'm running lots of missions right now and will give it a test.

**Comment by richardbuckle** [comment]
Fixed. All `station.model` needs to be wrapped in `P()`. This is fragile and merits consideration.
