### ISSUE TITLE
Speech Responder Fuel check speech bug

### ISSUE THREAD

**Issue by randyDarsh** [EDCD/EDDI#1265]
## EDDI version in which issue is found
3.3.7-b2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Any time a fuel check happens, and title isn't chosen in the script, the percent is given then "comma" is spoken.

`{set title to Occasionally(3,"{F('Honorific')}")}`

`{shipsfuel} {OneOf("below 25%", "{currentpercent}" )}, {title}.`

## Expected
The script shouldn't say "comma" when the title is empty

## Observed
The script says "comma" when the title is empty

## Investigation
I have modified the script file as follows, and tested.  It appears to be working as expected.

`{set title to Occasionally(3,", {F('Honorific')}")}`

**Comment by richardbuckle** [comment]
Fixed by #1266
