### ISSUE TITLE
Just updated EDDI and VA. Unable to connect API

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#1268]
![Cannot connect 31 3 2019](https://user-images.githubusercontent.com/21980416/55286510-3119e280-53a5-11e9-8d2f-daddc032fa34.JPG)

**Comment by Tkael** [comment]
I imagine you already checked for running instances of either EDDI or VoiceAttack?
You might also try clearing the reinstalling or clearing cookies on your default browser.

**Comment by FireSammy** [comment]
Cleaning browser worked. I'll have to try to remember that next time when upgrading, thx. Issue solved

![EDDI connected](https://user-images.githubusercontent.com/21980416/55290648-7dcddf80-53de-11e9-8b1e-783503ea93c3.JPG)

**Comment by Tkael** [comment]
Closing as resolved. :-)
