### ISSUE TITLE
Discovery scan script

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1270]
After thinking about the System scan complete event, I thought I'd take a look at the Discovery scan event, just in case FD had fixed that too.  Guess what? They have!  The journal entry is added immediately after the scan completes and the event triggers perfectly.

So, I decided to write a small basic script for it, and would like to know if you wish to add it to future EDDI releases.

```
{Pause(1000)}
Discovery scan complete.

{event.bodies} {if event.bodies > 1: bodies |else: body}

{if event.nonbodies:
    and {event.nonbodies} non-body
    {if event.nonbody > 1: signals |else: signal}
}

detected.
```

I've added it to my new personality release, but if you want to use it in the default, you are most welcome to it.

EDIT: I added a 1 second pause at the start so speech doesn't start until the 'honk' is fully finished.

**Comment by Tkael** [comment]
Thanks for this. :-) It's actually very similar to the initial script I used to test the `Discovery scan` event.

My natural inclination is to abhor empty scripts, but in this case I found that I wasn't getting very much value out of my test script (@richardbuckle might say that the script created an unnecessary cognitive burden). 

What value do you see?

**Comment by Darkcyde13** [comment]
Well, I guess it can be considered as personal preference, but I do like to hear the report of the number of bodies.

Sometimes the report text on the HUD is just where the main star is and I can't read the text, so the report is very useful in that situation (to me at least).  Additionally, the report of the non-body signals tells me how many asteroid clusters, etc, there are, which is something not reported in game.

I'll continue to use the script, but if you don't want to have a default (leaving the script empty) that's fine too.  Although you may want to update the message text currently in there to reflect that there is no longer any delay. :)

**Comment by kaimi** [comment]
I’ve done something similar through voice attack and the EDDI event. Main value for me was getting the additional info about non-body objects that isn’t in E:D’s standard info display. Now I’ve grown used to being told the number of bodies, too, and I don’t want to miss it :)

**Comment by Tkael** [comment]
I've got an update in the works that'll probably touch on this. Right now, the plan is to tell you how many bodies you have left to scan when you honk if your ship's role is `exploration` or `multipurpose`.
Examples:
` 11 bodies remain to be scanned.`
 `1 out of 22 bodies have been scanned in this system.`

**Comment by Tkael** [comment]
@kaimi I'm curious how you're using the non-body object data?

**Comment by kaimi** [comment]
@Tkael basically just like @Darkcyde13. All it does is tell me the count. The general idea was to not ever miss NSP even if I’m just jumping and honking. But I kinda like getting all available information anyway.
