### ISSUE TITLE
Feature request - Event for certain classes of planetary bodies

### ISSUE THREAD

**Issue by Ole122** [EDCD/EDDI#1273]
Not sure if this has been asked before, but I'd love to see an event which alerts me if a body scanned by me in FSS belongs to a certain category (namely the ones that are worth more for a DSS scan - Heavy Metal content worlds, Earth-likes, Water, Metal-rich, Ammonia, certain kind of Gas Giants.

Unfortunately I have no real idea on how to set this up myself...

**Comment by Darkcyde13** [comment]
Hi Ole122,

You don't need an event for these, as you can add some code to do the job.  I have something in my EDDI personality that does just what you are asking for (and much more).  Here is the basic code you need:-
```
{if reportbody.terraformstate = "Candidate for terraforming" || reportbody.planettype = "Ammonia world"
 || reportbody.planettype = "Earth-like world" || reportbody.planettype = "Water world":

    This body is worth mapping

|elif reportbody.planettype = "High metal content world" || reportbody.planettype = "Metal-rich body":

    This body may be worth mapping.

}
```
This is only a small part of the code in my personality, and I have trimmed it down to suit your request.  Copy this onto the end of the Body Report script, and every planet you scan that is potentially valuable will suggest mapping it.  If you have any trouble with this, let me know and I'll try to help you out.

**Comment by Ole122** [comment]
Thats perfect, thank you! Just a small question: I've disabled most of the speech responses as I was a bit afraid that it would be too much. Set up a personality that only has very few responses still active. Body Report is one that seems to be enabled by default (checkmark is greyed out and I couldn't disable it), so just to be sure: The way it works is I scan a body in FSS, target it inside FSS mode and EDDI then delivers the report, right? (Sorry for the stupid question, just want to be sure that I don't miss something).

**Comment by Tkael** [comment]
The check box for `Body report` is grayed out because it not triggered directly by any event - instead it is invoked from within the `Body scanned` script. So if the `Body scanned` script is disabled, the `Body report` script won't be triggered.

**Comment by Tkael** [comment]
Closing with @Darkcyde13 's response on this one. No new event is needed.
