### ISSUE TITLE
Feature Request (if possible): VA ((Asteroid Depleted)) event

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#1278]
As the header suggests, this would be quite handy for (some) miners. I have automated many of my limpet launches etc, and mining laser(s) to shoot for a fixed time period. Problems come when the lasers shoot too long depleting my weapon capacitor and increase heat -of course, then an NPC(s) will attack and the ship defenses are already in a disadvantaged state.

I already know what the majority will say about how to do (with the traditional mining lasers) mining safely. I'm an eeerh... "quite unconventional" dude, and i don't give flying F about these bits of advice LOLOL. I do my mining in res sites, because of two reasons. It's less boring and to be able to get some bounty kills at the same time, will slightly increase the already crappy income. My only problem is that i cannot automatically stop my mining lasers when the Asteroid gets depleted. Because of many reasons -the asteroids take somewhat different time to get depleted.

This would also allow me not having to sit and watch the mining constantly, but do something else while the ship is mining the asteroid. If i go afk too long (get coffee, smoke etc.) i would not have to worry about the capacitor and the heat that much.

I could come up with a couple more things to suggest, but this is the main issue for me considering mining lasers.

Cheers!! :)
o7

**Comment by Tkael** [comment]
Unfortunately, there is no event available from the journal for this so we have no way to know when this occurs.
https://forums.frontier.co.uk/showthread.php/452937-Journal-Docs-for-v3-3
