### ISSUE TITLE
Cargomonitor doesn't work at all

### ISSUE THREAD

**Issue by bid** [EDCD/EDDI#1283]
## EDDI version in which issue is found
3.4.0

## VoiceAttack version in which issue is found (as applicable)
No VoiceAttack used

## Steps to reproduce
No real steps. Cargomonitor just doesn't reflect ANY changes in cargo and cargomonitor.json stays with an empty list. 

## Expected
Cargomonitor to reflect my actual cargo.

## Observed
cargomonitor.json just stays with an empty list and "cargocarried": 0, no matter what I do.

## Investigation
Things I tried: 
- Starting EDDI first, then Elite
- Starting Elite first, then EDDI
- Buying and Selling cargo in both cases
- Buying cargo, stopping Elite and EDDI, then starting both again - no change
- Deleting cargomonitor.json and restarting EDDI (file is just rewritten again in the same "no cargo" state)
- Completely removing EDDI, manually removing the data directory and doing a fresh reinstall - same problem

Other tools, like "E:D Market Connector" and "Trading Computer Extension MKII" reflect my current cargo without problems. 

**cargomonitor.json:**
{
  "cargo": [],
  "cargocarried": 0,
  "updatedat": "2019-04-26T20:12:38Z"
}
[eddi.log](https://github.com/EDCD/EDDI/files/3122875/eddi.log)

**Cargo.json:**
{ "timestamp":"2019-04-26T20:12:38Z", "event":"Cargo", "Vessel":"Ship", "Count":8, "Inventory":[ 
{ "Name":"survivalequipment", "Name_Localised":"Survival Equipment", "Count":1, "Stolen":0 }, 
{ "Name":"drones", "Name_Localised":"Limpet", "Count":7, "Stolen":0 }
 ] }

**Comment by Hoodathunk** [comment]
I see a Galnet Monitor exception in the log. This is likely the cause.

Try disabling the Galnet Monitor and test the Cargo Monitor again. Meanwhile, we'll investigate why a web request timeout is not playing nicely.

**Comment by bid** [comment]
Will do and report if that changes anything. I've just posted a second bug report about GalNet, which has its very own problems. ;)

**Comment by Tkael** [comment]
@bid Where you able to figure out what was going on with this issue?
We're not seeing anything that looks off on our side... the cargo monitor appears to register all cargo correctly from the event.

**Comment by bid** [comment]
@Tkael Sorry, I missed your message. No news on my side, but I didn't do any more investigation in the meantime. Took a few days of Elite-break. :) 
Cargomonitor is the only monitor not working for me. The others (ship-monitor, mission-monitor, material-monitor) all seem fine. And the speech output also tells me when I buy/sell cargo, so that event fires too. It's just the monitor itself that doesn't work.

One single thing I thought about in the meantime: I have Elite installed in a "non-standard" location on my second harddisk. Shouldn't really make any difference but who knows? I actually thought about checking the code myself and check for differences between the different monitors. But I've never looked at EDDIs sources and it would take me a while to get up to speed how everything is set up here.

**Comment by Tkael** [comment]
Are your EDDI config files or your `Saved games` folder in a non-standard location too?
Is the status monitor working? It reads `status.json` in pretty much the same way we read `cargo.json` (from the Saved Games folder where your journal entries are stored).

**Comment by Tkael** [comment]
Hi @bid , any updates on this issue?

**Comment by Tkael** [comment]
Closed due to lack of response and inability to replicate the issue (please let us know if you are still encountering this issue!)

**Comment by nepomuk16321** [comment]
Sorry guys, the cargo monitor is still not running or not running yet.

EDDI version 3.4.1-rc1 (stand alone)
