### ISSUE TITLE
Speech Responder keeps reading the same GalNet articles again and again

### ISSUE THREAD

**Issue by bid** [EDCD/EDDI#1285]
## EDDI version in which issue is found
3.4.0

## VoiceAttack version in which issue is found (as applicable)
No VoiceAttack used

## Steps to reproduce
1. Activate GalNet Monitor and Speech Responder
2. Wait

## Expected
Speech Responder reads new GalNet articles ONCE.

## Observed
Speech Responder reads new GalNet articles over an over, at random intervals (sometimes after 5 minutes, sometimes after an hour or so), without a discernable pattern. Sometimes it reads just the newest one, sometimes the newest two, sometimes several. 

## Investigation
No real investigation done since there's not much me as a user can do about it, except deactivating the speech responder for new GalNet articles, which is what I have done now. I had heard the latest few articles so often, that I knew them by heart and could seriously speak them together with the TTS voice word for word. 

[eddi.log](https://github.com/EDCD/EDDI/files/3123191/eddi.log)

**Comment by Tkael** [comment]
I've found an exception generated by an odd news item from Frontier (for "Bridging the Gap") that has a title but no actual article / content. Submitted in #1289. 
That change may resolve this issue, since in it's current state the Galnet monitor is resetting every time it encounters the error.

**Comment by bid** [comment]
That would be awesome. I really love that "read new articles" feature and would very much like to activate it again.

**Comment by Tkael** [comment]
Merged fix.
