### ISSUE TITLE
Revise `Friends` event

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#129]
## Steps to reproduce

1. Install any current beta
2. Keep the friends status script enabled
3. Have some friends
4. Log in and play

## Expected
Friends status updates appear only for real changes in status, and should not be re-stated while friends remain online.

## Observed
Friends status gives a burst of friend status updates, then may give another burst minutes later even though friend status remains unchanged (maybe friends are board hopping or similar?).

## Investigation
Proposal: Rework the 'Friends status' script into a 'Friends monitor' that can be queried but that does not constantly re-report the same data.

**Comment by richardbuckle** [comment]
Maybe post-2.4.0? Thoughts @Tkael @Hoodathunk ?

**Comment by Tkael** [comment]
it seems that everyone dislikes the current implementation (myself included, tbh). I'd like a version we are happy with before releasing 2.4.0

**Comment by richardbuckle** [comment]
Concur. TBH I'd rather it shipped as disabled as it stands. Way too spammy.

**Comment by Tkael** [comment]
mind giving me a day to work on this? I don't think it would be too complicated and I'd like to schedule some time to work on it after work tomorrow

**Comment by Tkael** [comment]
if not, we disable it by default and revisit post 2.4.0

**Comment by richardbuckle** [comment]
Let's disable it temporarily for beta 5 while you work on it.

**Comment by Tkael** [comment]
agreed. pushed a commit to disable in develop.

**Comment by Tkael** [comment]
Closed pending approval of PR #294.
