### ISSUE TITLE
Glide event not firing

### ISSUE THREAD

**Issue by dmon82** [EDCD/EDDI#1296]
## EDDI version in which issue is found
3.4.0

## VoiceAttack version in which issue is found (as applicable)
1.7.5

## Steps to reproduce
Drop from supercruise/OC into glide, ((EDDI glide)) command is not being executed/event never being fired, maybe because the FSD doesn't change to "masslock" status unless dropping to 2000 metres or lower altitude.

## Expected
Plugin command : '((EDDI glide))' being executed in VA.

## Observed
Nothing happens when dropping into glide. FSD doesn't get mass locked early enough (anymore)?

## Investigation
Making sure near_surface should be true by asking for coordinates (lat/long, heading, i. e. {DEC:Status latitude} et cetera). And checking all glide status variables (EDDI glide body/bodytype/gliding/system), all values are Not Set.

Maybe it could check for the drop altitude (25,000 m?) and the static ship velocity when in glide of 2,500 m/s?

**Comment by Tkael** [comment]
I'll check this out. FYI, we could check altitude but not velocity (velocity isn't provided via status).

**Comment by Tkael** [comment]
Update: You've correctly diagnosed the problem. FDev have changed something such that the FSD masslock we used to use to trigger a glide is no longer present. In fact, no FSD changes are registered at all at the start of the glide. All we see is a cooldown at the end of the glide.

It's possible to replace the FSD masslock with alititude, as you noted, but if we do so then we cannot distinguish between gliding towards the planet and crashing into it (the same condition of being close to the planet with an altitude less than 25 km is true in each case). 

We'll have to think on this further.

**Comment by Tkael** [comment]
I've tested the music event to see if we can use a change in soundtracks to to identify a glide. Unfortunately, the soundtrack doesn't change until the glide completes either. :-(

**Comment by dmon82** [comment]
I had a thought but I guess the fact you can crash out of supercruise voids it all, whether it's because you're too fast or at too steep of an angle in the approach. I had thought to perhaps combine the SupercruiseExit from the journal, and the altitude from the status.

I'm guessing the IsInDanger flag in the status only involves combat and incurs the 15 second logout timer, and is not set during an emergency exit from supercruise taking damage.

I can't see a way to get a glide event at this time myself. Maybe if it had a status flag, but there's only room for a few more, or if ship velocity was in the status entry, or the SupercruiseExit journal had a property for the kind of exit (e. g. interdiction, emergency, glide, regular). Not sure if FDev would touch any of that any time soon.

**Comment by Tkael** [comment]
I'm happy to run into a planet and test the `IsInDanger` flag but I don't think it's likely to work. :-D

**Comment by Tkael** [comment]
That's a negative for the `IsInDanger` flag. Good thought though.

**Comment by richardbuckle** [comment]
Are there any other circumstances where we exit supercruise and the FSD doesn't go into cooldown? If not then that could be our determinator.
