### ISSUE TITLE
Crashing Randomly, no apparant reason, tried 4 versions.

### ISSUE THREAD

**Issue by pjghangouts** [EDCD/EDDI#1297]
## EDDI version in which issue is found
3.4.0

## VoiceAttack version in which issue is found (as applicable)
1.7.5

## Steps to reproduce
Load up EDDI, wait a few mins, doing nothing is particular except playing the game, and EDDI will crash with no apparent error

## Expected
I expected it to stay working and usable

## Observed
Crashed, if EDDI was linked to Voiceattack via plugin, Voiceattack would crash too, neither giving me any error to work out what was causing it.

## Investigation
Tried 3.3.5/6/7 and 3.40, I've even deleted files in %APPDATA%/EDDI and let is recreate, 
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/3175197/eddi_issue.zip)

**Comment by Tkael** [comment]
Try removing all of the config files from %appdata%/EDDI at once. If it is stable, re-add the config files one by one until you begin to see crashes again. Likewise, you can try disabling all of the monitors and the re-enabling them one by one. 
Was it working prior to version 3.3.4?

**Comment by pjghangouts** [comment]
I've done that, and I'll turn them on, one by one and see what happens. To be honest, I don't know what version I was on, I took a step away from ED for a while and come back and updated all my 3rd party addon's, it was only when EDDI started breaking I started working back on versions from the GitHUB and I got back to 3.3.5 before deciding to post something here, as I didn't really see something in the logs that would have jumped out to me.

Once I've done a little more testing, I'll report back, I was kinda hoping there would be something clearing obvious in the log files. :) 

I'll keep you posted.

**Comment by Tkael** [comment]
The log you provided was actually quite short and included no logged exceptions. May I suggest turning off verbose logging, waiting until a crash has occurred, and then attaching `eddi.log` from `%appdata%/EDDI` to this issue? The non-verbose log will be much less verbose but should still capture any exception.

**Comment by Tkael** [comment]
Check #1299. Does switching to a different voice make a difference to stability?

**Comment by Tkael** [comment]
Hi @pjghangouts , any updates on this issue?

**Comment by pjghangouts** [comment]
Yeah, sorry, been a little busy and only just got around to replying to this. 

As I got the notification about the #1299 in the email, I was actually trying that, that night. I obtained a few more voices and installed them and switched to the new voices, away from the ones that were mentioned in #1299 and it appeared to stay running. [I just wish there were more available, none robot sound voices on Windows 10]

Thanks for the follow up though, I don't know if i have any other issues, I'll be sure to reach out as I know you'll try to help.

**Comment by Tkael** [comment]
Thanks for the follow up. For the record, which voice were you using and did you try reinstalling that voice?

**Comment by Tkael** [comment]
Closing this issue (don't worry, I'll still see your response).

**Comment by pjghangouts** [comment]
I was using ivona 2 salli, the others didn't seem to have an issue, just that one, and to be honest at the time of the issues I was getting tired of the voice (I like to change them up now and again) so I was switching to another and didn't bother to try and re-install it [or should I say, her] :)

**Comment by Tkael** [comment]
Thanks. FYI, I use Ivona Amy and haven't noticed the same issue with that voice.
