### ISSUE TITLE
EDDI crash hard VA on random jumps! Sometimes freeze PC

### ISSUE THREAD

**Issue by tulextreme** [EDCD/EDDI#1299]
## EDDI version in which issue is found
3.4.0

## VoiceAttack version in which issue is found (as applicable)
11:07:03 - Singularity v2.1.1 - VoiceAttack v1.7.5

## Steps to reproduce
Cant crashes randomly. Mostly on jumps from system to systems

## Expected
Don't Crash?

## Observed
Crash!

## Investigation
When stand alone via app it performs ok! But on VA dont matter the profile it crashes like hell!
[eddi.log](https://github.com/EDCD/EDDI/files/3178150/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/3178151/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/3178153/eddi2.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/3178155/eddi3.log)
[eddi5.log](https://github.com/EDCD/EDDI/files/3178157/eddi5.log)
[eddi6.log](https://github.com/EDCD/EDDI/files/3178158/eddi6.log)
[eddi7.log](https://github.com/EDCD/EDDI/files/3178159/eddi7.log)
[eddi4.log](https://github.com/EDCD/EDDI/files/3178160/eddi4.log)

**Comment by Tkael** [comment]
Thanks for the logs. Is EDDI installed in your VoiceAttack/apps folder?

**Comment by Hoodathunk** [comment]
Looks like the elite.josn file is corrupted. Attach the file here and then delete it. Re-start EDDI and it should come up fine.

**Comment by tulextreme** [comment]
Well same problem with version 3.3.7 on a random jump va crashes!
one thing i noticed on the log was:
019-05-14T22:50:16 [Warning] JournalMonitor:ParseJournalEntry EDDI has no handler for event type 'Powerplay'./r/nRaw event:/r/n{ "timestamp":"2019-05-14T22:50:18Z", "event":"Powerplay", "Power":"Archon Delaine", "Rank":0, "Merits":180, "Votes":0, "TimePledged":666451 } 
2019-05-14T23:00:02 [Info] EDDI:eventJumped Jumped to Ryujingit 

Maybe PP is the culprit? 
Tkael  - Yeah i've installed eddi on its default directory same as i aways had! 
Hoodathunk  - cant understand what u said but i had tried several times deleting the whole 
C:\Users\tulex\AppData\Roaming\EDDI directory with no aval! Same crash.

**Comment by Tkael** [comment]
I don't think so. A powerplay event not being handled is quite benign.

```
2019-05-14T23:07:50 [Warning] EDDI:Start Failed to start EDSM responder 
2019-05-14T23:07:50 [Warning] EDDI:Start Failed to start VoiceAttack responder 
```
I think something about the EDSM or VoiceAttack responder is off.

**Comment by tulextreme** [comment]
Guys i've found the problem. It was mt IVONA TTS installation! Something went awry! 
As eddi or VA use the voices it just adds some memory leak until it finally crashes! dnt ask me how
I've uninstalled  iVONA and atm using the windows 10 tts voices with no issues what so ever!
Sorry to invoke this error as a EDDI faulty but now after testing everything i could i know it was not a problem with this incredible software! Should i delete this thread ? close it? best regards!

**Comment by Tkael** [comment]
I'm glad you found a resolution. Perhaps a reinstall for your Ivona voice will help? I know I use an Ivona voice and haven't been seeing crashing.
