### ISSUE TITLE
EDDI Core: Speech prosody presets

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#130]
## Proposal
Full emotion with TTS is very difficult (and outside of the range of this project), but with SSML prosody tags we could create "preset" functions to provide some variation and suggest different emotional states for voices that support them:

For example:
```
{FeelsHappy("I'm happy.")}
{FeelsAngry("Now I'm angry.")}
{FeelsSad("Now I'm sad.")}
Now I'm not.
```
would translate into:
```
<prosody pitch="+5%" rate="+10%" volume="+20%">I'm happy.</prosody>
<prosody pitch="+3%" rate="+10%" volume="+100%">Now I'm angry.</prosody>
<prosody pitch="-3%" rate="-20%" volume="-20%">Now I'm sad.</prosody>
Now I'm not.
```

**Comment by Tkael** [comment]
Note: depends on #127

**Comment by Tkael** [comment]
Decided this probably isn't worth doing at this time.

**Comment by yasmeenh** [comment]
I have tried this  
<prosody pitch="+5%" rate="+10%" volume="+20%">I'm happy.</prosody>
<prosody pitch="+3%" rate="+10%" volume="+100%">Now I'm angry.</prosody>
<prosody pitch="-3%" rate="-20%" volume="-20%">Now I'm sad.</prosody>

But, it doesn't work!!. There are no changes in the voice emotion.
Can you help me to get happy, sad, fear, and angry emotions using SSMLprosody tag?
