### ISSUE TITLE
"Index was out of range, must be non-negative and less than the size of the collection"

### ISSUE THREAD

**Issue by Djuwanna** [EDCD/EDDI#1323]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Djuwanna** [comment]
EDDI version in which issue is found
v3.4.1-b1

VoiceAttack version in which issue is found (as applicable)
1.7.5

Steps to reproduce
Ask, "How many <x> do I have?" where <x> is any material currently on board

Expected
Count of existing material inventory

Observed
verbalized error "There is a problem with the Material Inventory Report script.  Index was out of range, must be non-negative and less than the size of the collection."

Investigation
Not sure what to investigate - it used to work, after upgrading to current version noticed that it was not working properly.  Not sure what went wrong, probably a corrupt index file or something but I don't know how to reset properly.

**Comment by Hoodathunk** [comment]
This is addressed by PR #1319 and will be fixed in the upcoming ‘b2’ release.

**Comment by Tkael** [comment]
I'll go ahead and close this ticket, but please re-test with the next release and let us know if the issue persists (we'll get an alert when you add to this ticket even if it's closed). 
The next release will be arriving very soon!
