### ISSUE TITLE
Feature request - Include the grade of materials.

### ISSUE THREAD

**Issue by Saifon2000** [EDCD/EDDI#1326]
## Feature request.

Great job on EDDI, just have a possible future feature request. To include which grade of material in the Materials section. 

Thanks,
S.

**Comment by Tkael** [comment]
Check out the `rarity` property for materials. Is that what you're after?

**Comment by Tkael** [comment]
I think the `rarity` property already covers this. If you disagree, please respond to this issue and we'll re-open it for another look.
