### ISSUE TITLE
Material inventory report error

### ISSUE THREAD

**Issue by jrohrer77** [EDCD/EDDI#1328]
## EDDI version in which issue is found
3.4.1-b1
## VoiceAttack version in which issue is found (as applicable)
VA version 1.7.3
## Steps to reproduce
1. Material collected script comes back with an error:
   Text of error: 
   **There is a problem with the: Material collected script. Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index**

Script: 

{_ Context }
{SetState('eddi_context_last_subject', 'material')}
{SetState('eddi_context_last_action', 'collect')}
{SetState('eddi_context_material_name', event.name)}

{set matis to MaterialDetails(event.name)}
{if matis.rarity.name = "very common":
  {set rarity to 1}
  {set limit to 300}
|elif matis.rarity.name = "common":
  {set rarity to 2}
  {set limit to 250}
|elif matis.rarity.name = "standard":
  {set rarity to 3}
  {set limit to 200}
|elif matis.rarity.name = "rare":
  {set rarity to 4}
  {set limit to 150}
|elif matis.rarity.name = "very rare":
  {set rarity to 5}
  {set limit to 100}
}

{OneOf("{P(matis.name)} {OneOf('Received','Collected','Ob-tained')}",
       "{OneOf('Received','Collected','Ob-tained')} {P(matis.name)}")}.

{if matis.category.name = "Data":
            {Occasionally(2,"This is")} a level {rarity} {OneOf("data set","set of data","data scan")}.
  

|elif matis.category.name = "Element":
  {Occasionally(2,"This is")} a level {rarity} {OneOf("element","raw element","raw material")}.

|elif matis.category.name = "Manufactured":
    {Occasionally(2,"This is")} a level {rarity} {OneOf("manufactured material","manufactured item")}.

}

{_ Function to obtain a material from inventory}
{set _inventory(required) to:
    {for material in materials:
        {if material.material = required:
            {return material}
        }
    }
}

{set material to matis.name}
{if material:
    {_ Fetch full material details }
    {set material to MaterialDetails(material)}
 
    
}

{set inventory to _inventory(material.name)}

{if inventory && inventory.amount > 0:
    {if inventory.amount = 1:
      {inventory.amount} unit of {inventory.material} now in inventory; the storage cap is {limit}.
    |else:
      {inventory.amount} units of {inventory.material} now in inventory; the storage cap is {limit}.  
    }
|else:
    You have no {inventory.material} on board.
}

This script worked prior to 3.4.1-b1
Working Output Example: 
**High Density Composites Ob-tained. a level 3 manufactured material. 170 units of High Density Composites now in inventory; the storage cap is 200.**

**Comment by Tkael** [comment]
Believe fixed by version (3.4.1-b2)[https://github.com/EDCD/EDDI/releases/download/Release%2F3.4.1-b2/EDDI-3.4.1-b2.exe]
