### ISSUE TITLE
Fighter not recognized in 3.4.1-b2

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1331]
## EDDI version in which issue is found
3.4.1-b2

## VoiceAttack version in which issue is found (as applicable)
1.7.5

## Steps to reproduce
Swap to a ship with a fighter

Until yesterday (3.4.1-b1) Eddi said this:

"Parking your Asp and transferring to css norfolk. You have a size 3 SRV hangar. It has a S R V Scarab with Starter load out. It has one rebuild remaining.  You have a size 5 Fighter hangar. It has a F 63 Condor with Aegis load out, and fixed weapons. It has 6 rebuilds remaining.  Reminder: you need to assign a crew member to active duty."

After upgrading to 3.4.1-b2 Eddi says this:

"Mothballing css louise and moving to css norfolk. You have a size 3 SRV hangar. It has a S R V Scarab with Starter load out. It has one rebuild remaining.  You have a size 5 Fighter hangar. It has a federation_fighter_name with federation_fighter_loadout_two_name load out. It has 6 rebuilds remaining.  Reminder: you need to assign a crew member to active duty."

**Comment by Tkael** [comment]
Hmm, I'm not sure that was a change caused be the new release. We didn't change anything that would affect that, and in fact all we've ever done with that vehicle information is tidy up the loadout name and and use the localized vehicle name from the Frontier API. FDev may have changed something. 
@Hoodathunk , mind taking a look?

**Comment by Hoodathunk** [comment]
Sure thing, as soon as I get back to dev computer.

**Comment by Djuwanna** [comment]
Same thing is happening with Guardian fighters

**Comment by Tkael** [comment]
@Djuwanna Please provide example text from speechresponder.out, it'll help us map to a more user friendly name.

**Comment by Djuwanna** [comment]
Speechresponder.out says (in part):

You have a size 7 Fighter hangar. It has a gdn_hybrid_fighter_v 1_name with gdn_hybrid_fighter_v1_loadout_one_name load out. It has 15 rebuilds remaining.  It has a gdn_hybrid_fighter_v 2_name with gdn_hybrid_fighter_v2_loadout_one_name load out. It has 15 rebuilds remaining.

Hope that helps!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Hoodathunk** [comment]
Corrected in PR #1399.
