### ISSUE TITLE
Typo "This is usually a temporary issue with Frontier's servvice"

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#134]
## Steps to reproduce

1. Launching EDDI while offline should do it.

## Expected
Correct spelling of "service"

## Observed
Incorrect spelling "servvice" as per [this forum post](https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5984812&viewfull=1#post5984812).

**Comment by Tkael** [comment]
Feature. "Servvice" is fancier than normal service. ;-)
Check MainWindow.xaml.cs lines 366 & 394. You've already claimed it so I won't mess.

**Comment by richardbuckle** [comment]
Fixed for 2.4b5
