### ISSUE TITLE
Obtaining EDSM logs working as intended ?

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1343]
## EDDI version in which issue is found
3.4.1-rc1

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. delete EDDI.sqlite
2. start EDDI
3. obtain EDSM logs

After updating to Rc1 I did above to start with a fresh database that matched my EDSM logs to see if my earlier problem #1162 was solved.
First thing I noticed was that the counter started with 0/30002 instead of 0/10000 (not sure about the exact number in the last but it was about 10000). Looks like the RC1 version counts all my flightlogs while the previous versions counted the unique systems I visited.
After seeing this I thought well maybe this is new so I let it running to see what happens.
Second this I noticed was the process was much slower. In the previous version it took about 10 minutes to obtain all records ending with a EDDI.SQlite of about 12Mb. Now after about 20 minutes the counter said 3000/300002 and the EDDI.SQlite file was already about 280Mb large..
Didn't have time to wait until it finished (with this speed it would take about 3 hours) so I closed down EDDI.
I briefly looked at the SQlite file and it looks like it obtains a lot more info for every system but a lot of system appears more the once. I saw 1 system mentioned 12 times for instance which was also the number of times I visited that system but the 12 records appeared to be identical except for the lastvisited entry.

Is this all expected behaviour or is something wrong with the obtain logs routine ?

**Comment by Tkael** [comment]
The sqlite file should have only one entry per system name. I'll check it out. Can you provide a screenshot of the sqlite file?

**Comment by JCalvertJoshua** [comment]
![sqlite blido piru](https://user-images.githubusercontent.com/19605885/59063935-7678f580-88a9-11e9-9238-dbb1397574f9.JPG)
![edsm blido piru](https://user-images.githubusercontent.com/19605885/59063978-8abcf280-88a9-11e9-830c-d09c0023e838.JPG)

**Comment by Tkael** [comment]
Having a larger value for the counter is expected, since we are no longer condensing the results to star system - as you surmised the new total is the total number of flight logs being synchronized from EDSM.
I think I understand what caused the duplication and slow-downs. PR incoming.
