### ISSUE TITLE
Accentued characters (in french)

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#1344]
## EDDI version in which issue is found
3.4.1-rc1

## VoiceAttack version in which issue is found (as applicable)
no voice attack

## Steps to reproduce
always

## Expected
continue to read the text as usualy

## Observed
accentuated characters (example to, é, è, è, ô etc....) are no longer read in the version with my usal (windows base) voice

## Investigation
same problem with 3.4.1-b1 & 3.4.1-b2. Work fine with 3.4

**Comment by Tkael** [comment]
With every script? And with which voice?

**Comment by richardbuckle** [comment]
Just to be clear, are you saying that it does not distinguish between "marche" and "marché"?

**Comment by StivlWrith** [comment]
with "marché" i listen "march"
I make some tests to compare 3.4.1-rc1 and 3.4.0

test of "Limpet purchased" script
[screenshot with 3.4.1-rc1](https://ibb.co/Prjvg0q)
in the speechresponder.out there is with the test button : 

> 19 drones ont �t� ajout� � votre soute

[screenshot with 3.4.0](https://ibb.co/qmv3v4f)
in the speechresponder.out there is with the test button :  

> 19 drones ont été ajouté à votre soute

For the voice, it is the "Windows TTS Default"
