### ISSUE TITLE
When VoiceAttack is running, I can't change settings in the EDDI panel. 

### ISSUE THREAD

**Issue by Acecool** [EDCD/EDDI#1350]
## EDDI version in which issue is found
latest

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. latest

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

I installed the VA plugin, launched EDDI then configured it. I made sure the plugin was checkmarked in VA then I restarted VA. The plugin complained about a maximum of 1 EDDI instance can run. I closed it and got updates. I found them annoying so I wanted to change it. I couldn't launch the EXE and I can't edit the plugin or open the GUI using VA. No profile is loaded in, so the shutup command doesn't work, etc...

## Expected
[Describe what you expected to happen]

I was hoping the GUI would go to the tray when running through VA.

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Running multiple instance of EDDI simultaneously could corrupt your configuration files, so we have to force a single instance.

The GUI can quite easily be opened through VoiceAttack. The easiest way to do this is to load the `EDDI.vap` profile then say `configure EDDI` or `open EDDI`. If you'd prefer to write your own command, here's a screenshot of the command included in `EDDI.vap` that you can use for reference:
![Untitled](https://user-images.githubusercontent.com/4382539/59150205-7b869380-89d4-11e9-9316-53407e010e4e.png)

**Comment by Tkael** [comment]
Closing as resolved, but I'll get a message if you respond to this message again and reopen if needed. o7

**Comment by ITCMD** [comment]
Issue is, no matter what I do, I cant get it to understand "EDDI"

This is with a studio reference mic. :/

**Comment by Tkael** [comment]
1. If you are not using a headset, consider using a headset to isolate voice commands from background or game noises. 
2. If you have not trained the operating system with your voice, you should do so.
3. I have no problem with EDDI being recognized (when pronounced like the name "Eddie"), but as a last resort, you can replace "eddi" and "EDDI" in the commands described above with a different word of your choosing.

**Comment by ITCMD** [comment]
Great ideas, thank you.

**Comment by dylan-k** [comment]
fwiw i also have the issue where, no matter what I try, I cannot get it to understand me when I say "EDDI."
