### ISSUE TITLE
Events recognition non working

### ISSUE THREAD

**Issue by Nyquisttt** [EDCD/EDDI#1351]
## EDDI version in which issue is found
3.4.1-rc1

## VoiceAttack version in which issue is found (as applicable)
1.6.1

## Steps to reproduce
1. Use the event ((EDDI jumped)) in the "When I Say" field of the VoiceAttack command editor
2. Jump to a system

## Expected
the event should trigger an action in VoiceAttack

## Observed
no action happens

## Investigation
the issue was not present in the previous beta version of EDDI. The "jumped" is not the only unrecognized event. All the events seem broken.

**Comment by Tkael** [comment]
If no events are triggering, please first confirm that the EDDI plugin is enabled in VoiceAttack's UI?

**Comment by Tkael** [comment]
You can also find copies of EDDI's log files at `%appdata%/EDDI`. If EDDI was enabled, you should find a log for that game session. If so, please attach a copy here?

**Comment by JCalvertJoshua** [comment]
VA 1.6.1  ? Maybe updating to latest version will fix it.

**Comment by Nyquisttt** [comment]
After cleaning the directory with the journal files the problem has just disappeared. Probably a problem with my filesystem.

**Comment by kaimi** [comment]
I’m randomly having this issue as well (read: starts happening several times per day). Sometimes restarting Elite and VoiceAttack fixes it, until it breaks again. No journal interaction at all seems to take place then. No state changes (e.g. landing gear deployed/retracted), no events firing, nothing.

While trying to troubleshoot this myself I have noticed that when this happens, the “modified at” date of the current journal file freezes even though Elite is still writing to it. Only closing Elite updates the modified date – until (as said above) it randomly breaks again.

**Comment by Tkael** [comment]
Are there any exceptions being written to eddi.log (found in `%appdata%/EDDI`) when this occurs?

**Comment by kaimi** [comment]
Nope, nothing. E.g. right now the log has just stopped getting new entries more than 2h ago (when it broke and I cba to try and fix it again).

Also my earlier theory about the log modified date doesn’t hold up, that’s set to ~7 min ago right now.

**Comment by Tkael** [comment]
Try jumping to a new star system. EDDI should record the jump.

**Comment by kaimi** [comment]
> Try jumping to a new star system. EDDI should record the jump.

Nope. _No_ events get through, including jumps.

> If that fails, try using VoiceAttack with just EDDI.vap and no other plugins enabled.

Gonna try this tonight and report back.

**Comment by kaimi** [comment]
I have disabled all plugins except EDDI and bindEd (because honestly, I’m relying way too much on the combination of those two for regular play …). It went fine for the majority of the evening, but it just broke again.

I noticed that after jumping into Fong Wang, the `((EDDI jumped))` VA command didn’t fire. Neither did the `{{EDDI discovery scan))` one after I manually honked. I immediately shut down VoiceAttack.

Since the log file was around 250 MB, I just cut it at an arbitrary timestamp.
[eddi.shortened.log](https://github.com/EDCD/EDDI/files/3331828/eddi.shortened.log)

**Comment by kaimi** [comment]
This keeps getting weirder. After restarting VA, I did a couple discovery scans to check if the event would fire. It didn’t. So I continued on my way, and while I in the process of requesting docking permissions at the nearest station, the `((EDDI discovery scan))` VA command fired three times – I had tried it three times before. So in that case, after restarting (and waiting for the plugin initialisation, of course) it just had a random delay.

The full log from last shutdown is over 80 MB again … I’ll include it in full anyway.

https://fuelrats.cloud/s/GHaAAd5Cf3EDjoQ

**Comment by Tkael** [comment]
I don't see any exceptions / errors, but I do see that the Speech responder is being disabled from a VoiceAttack command: `2019-06-26T20:46:55 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context disablespeechresponder`. This will disable all speech responses except those specifically invoked from VoiceAttack.
```
2019-06-26T20:35:52 [Info] VoiceAttackPlugin:VA_Exit1 EDDI VoiceAttack plugin exiting 
2019-06-26T20:46:45 [Info] VoiceAttackPlugin:VA_Init1 Initialising EDDI VoiceAttack plugin 
2019-06-26T20:46:54 [Info] VoiceAttackPlugin:VA_Init1 EDDI VoiceAttack plugin initialization complete 
2019-06-26T20:46:54 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI va initialized)) 
2019-06-26T20:46:55 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context disablespeechresponder 
2019-06-26T20:47:05 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context disablespeechresponder 
2019-06-26T20:49:16 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI ship fsd)) 
2019-06-26T20:49:16 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI ship fsd)) 
2019-06-26T20:49:16 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI ship fsd)) 
2019-06-26T20:49:21 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI ship fsd)) 
2019-06-26T20:49:21 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI ship fsd)) 
2019-06-26T20:49:21 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI ship fsd)) 
2019-06-26T20:49:22 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context say 
2019-06-26T20:49:26 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI ship fsd)) 
2019-06-26T20:49:26 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI ship fsd)) 
2019-06-26T20:49:26 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI ship fsd)) 
2019-06-26T20:49:39 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI station no fire zone entered)) 
2019-06-26T20:49:39 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI message received)) 
2019-06-26T20:49:39 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI entered normal space)) 
2019-06-26T20:49:39 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI music)) 
2019-06-26T20:49:39 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI music)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Debug] VoiceAttackPlugin:triggerVACommands Found command ((EDDI discovery scan)) 
2019-06-26T20:49:40 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI discovery scan)) 
2019-06-26T20:49:41 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context say 
2019-06-26T20:49:41 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context say 
2019-06-26T20:49:41 [Debug] VoiceAttackPlugin:VA_Invoke1 Invoked with context say 
2019-06-26T20:49:44 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI docking requested)) 
2019-06-26T20:49:45 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI message received)) 
2019-06-26T20:49:45 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI message received)) 
2019-06-26T20:49:45 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI docking granted)) 
2019-06-26T20:50:40 [Debug] VoiceAttackPlugin:triggerVACommands Searching for command ((EDDI message received)) 
2019-06-26T20:52:17 [Info] VoiceAttackPlugin:VA_Exit1 EDDI VoiceAttack plugin exiting 
```

**Comment by kaimi** [comment]
> I just noticed that the Speech responder has been disabled by a plugin command in your VoiceAttack profile and won't speak unless it is specifically invoked from VoiceAttack.

Yes, and that’s how it’s supposed to be. The problem is that specifically invoking it from VoiceAttack doesn’t work, because apparently events from the journal (they do get written to the journal) don’t end up triggering the appropriate events in EDDI.

At the moment I have no idea where in between they just disappear, but somewhere they do.

**Comment by Tkael** [comment]
So the commands that aren't being voiced do exist in the profile? As you can see above, it looks like EDDI is searching for VoiceAttack commands to trigger and isn't necessarily finding them, or if it is it isn't finding actions invoking the plugin within them. If so, you'll need to troubleshoot the profile with the profile's author.

**Comment by kaimi** [comment]
> So the commands that aren't being voiced do exist in the profile?

Yes, they do and they work fine. Until they randomly stop working. The profile’s author is me :)

**Comment by Tkael** [comment]
I see from the log entries above that EDDI is looking for VoiceAttack commands to trigger from when it starts to when it stops again. Unfortunately, I don't see any evidence that the VoiceAttack plugin thread is failing to process events, looping, or otherwise failing to respond.

If it helps to troubleshoot the issue, you can check `state.speechresponder_quiet` from within EDDI to determine whether the plugin command `disablespeechresponder` is active.

**Comment by kaimi** [comment]
> Unfortunately, I don't see any evidence that the VoiceAttack plugin thread is failing to process events, looping, or otherwise failing to respond.

Yeah. As it said, somewhere between E:D writing to the journal and VoiceAttack executing an EDDI event hook, the event gets gobbled up and disappears. I also don’t recall having done anything to VA/EDDI (no updates, no new plugins, no major profile changes) when it started happening initially.

I didn’t have the issue last night (~5h play session). Next time it happens, I’ll try and see if EDDiscovery (that’s what I’m running in the background to do all the third party site processing/uploading since it supports multiple CMDRs) stops receiving journal events as well.

> you can check state.speechresponder_quiet from within EDDI to determine whether the plugin command disablespeechresponder is active

It is inactive since I mainly use EDDI to trigger custom VoiceAttack stuff on events and having information on the game state. Like honking systems I haven’t been in after jumping, retracting landing gear after launching, telling me the number of objects in a system after a discovery scan, etc. pp. :)

**Comment by Tkael** [comment]
I didn't see the journal entries to accompany the logs you shared. Are the log entries that VoiceAttack saw incomplete then?

**Comment by kaimi** [comment]
> I didn't see the journal entries to accompany the logs you shared.

Huh. Yeah. Would have probably been a good idea to include the journal as well :D

> Are the log entries that VoiceAttack saw incomplete then?

Yes. That’s the thing that’s happening: at some point, new journal entries don’t turn into VA/EDDI events.

**Comment by Tkael** [comment]
Hmm... these are all of the events that were logged after EDDI finished loading the game session. Without the original file, this is as close as I can get to reviewing the original journal. 

The list looks very similar to the list of events that VoiceAttack handled (timestamps and event types appear to be the same)... I still can't see anything that looks like it is wrong in the data or that would explain EDDI suddenly ceasing to speak like you're describing.
```
	Line 3: 2019-06-26T20:46:54 [Debug] EDDI:eventHandler Handling event {"raw":null,"timestamp":"2019-06-26T20:46:54.4150166Z","type":"VA initialized","fromLoad":false} 
	Line 438: 2019-06-26T20:49:16 [Debug] EDDI:eventHandler Handling event {"fsd_status":"cooldown","raw":null,"timestamp":"2019-06-26T20:49:16Z","type":"Ship fsd","fromLoad":false} 
	Line 454: 2019-06-26T20:49:21 [Debug] EDDI:eventHandler Handling event {"fsd_status":"cooldown complete","raw":null,"timestamp":"2019-06-26T20:49:21Z","type":"Ship fsd","fromLoad":false} 
	Line 486: 2019-06-26T20:49:26 [Debug] EDDI:eventHandler Handling event {"fsd_status":"masslock","raw":null,"timestamp":"2019-06-26T20:49:26Z","type":"Ship fsd","fromLoad":false} 
	Line 590: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"name":"Ravenov","status":"Online","friend":"Ravenov","raw":"{ \"timestamp\":\"2019-06-26T20:47:39Z\", \"event\":\"Friends\", \"Status\":\"Online\", \"Name\":\"Ravenov\" }","timestamp":"2019-06-26T20:47:39Z","type":"Friends status","fromLoad":false} 
	Line 591: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"system":"Fong Wang","bodytype":"Station","body":"Schachner Dock","systemAddress":3274669295979,"bodyType":{"edname":"Station"},"bodyId":62,"raw":"{ \"timestamp\":\"2019-06-26T20:49:11Z\", \"event\":\"SupercruiseExit\", \"StarSystem\":\"Fong Wang\", \"SystemAddress\":3274669295979, \"Body\":\"Schachner Dock\", \"BodyID\":62, \"BodyType\":\"Station\" }","timestamp":"2019-06-26T20:49:11Z","type":"Entered normal space","fromLoad":false} 
	Line 592: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"musictrack":"DestinationFromSupercruise","raw":"{ \"timestamp\":\"2019-06-26T20:49:11Z\", \"event\":\"Music\", \"MusicTrack\":\"DestinationFromSupercruise\" }","timestamp":"2019-06-26T20:49:11Z","type":"Music","fromLoad":false} 
	Line 593: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"musictrack":"NoTrack","raw":"{ \"timestamp\":\"2019-06-26T20:49:16Z\", \"event\":\"Music\", \"MusicTrack\":\"NoTrack\" }","timestamp":"2019-06-26T20:49:16Z","type":"Music","fromLoad":false} 
	Line 594: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"from":"Schachner Dock","source":"Station","player":false,"channel":"npc","message":"No fire zone entered.","raw":"{ \"timestamp\":\"2019-06-26T20:49:19Z\", \"event\":\"ReceiveText\", \"From\":\"Schachner Dock\", \"Message\":\"$STATION_NoFireZone_entered;\", \"Message_Localised\":\"No fire zone entered.\", \"Channel\":\"npc\" }","timestamp":"2019-06-26T20:49:19Z","type":"Message received","fromLoad":false} 
	Line 595: 2019-06-26T20:49:39 [Debug] EDDI:eventHandler Handling event {"weaponsdeployed":false,"raw":"{ \"timestamp\":\"2019-06-26T20:49:19Z\", \"event\":\"ReceiveText\", \"From\":\"Schachner Dock\", \"Message\":\"$STATION_NoFireZone_entered;\", \"Message_Localised\":\"No fire zone entered.\", \"Channel\":\"npc\" }","timestamp":"2019-06-26T20:49:19Z","type":"Station no fire zone entered","fromLoad":false} 
	Line 596: 2019-06-26T20:49:40 [Debug] EDDI:eventHandler Handling event {"progress":100.0,"bodies":27,"nonbodies":46,"raw":"{ \"timestamp\":\"2019-06-26T20:47:12Z\", \"event\":\"FSSDiscoveryScan\", \"Progress\":1.000000, \"BodyCount\":27, \"NonBodyCount\":46, \"SystemName\":\"Fong Wang\", \"SystemAddress\":3274669295979 }","timestamp":"2019-06-26T20:47:12Z","type":"Discovery scan","fromLoad":false} 
	Line 597: 2019-06-26T20:49:40 [Debug] EDDI:eventHandler Handling event {"progress":100.0,"bodies":27,"nonbodies":46,"raw":"{ \"timestamp\":\"2019-06-26T20:46:56Z\", \"event\":\"FSSDiscoveryScan\", \"Progress\":1.000000, \"BodyCount\":27, \"NonBodyCount\":46, \"SystemName\":\"Fong Wang\", \"SystemAddress\":3274669295979 }","timestamp":"2019-06-26T20:46:56Z","type":"Discovery scan","fromLoad":false} 
	Line 598: 2019-06-26T20:49:40 [Debug] EDDI:eventHandler Handling event {"progress":100.0,"bodies":27,"nonbodies":46,"raw":"{ \"timestamp\":\"2019-06-26T20:47:37Z\", \"event\":\"FSSDiscoveryScan\", \"Progress\":1.000000, \"BodyCount\":27, \"NonBodyCount\":46, \"SystemName\":\"Fong Wang\", \"SystemAddress\":3274669295979 }","timestamp":"2019-06-26T20:47:37Z","type":"Discovery scan","fromLoad":false} 
	Line 599: 2019-06-26T20:49:44 [Debug] EDDI:eventHandler Handling event {"station":"Schachner Dock","stationType":{"edname":"Coriolis"},"stationtype":"Coriolis Starport","marketId":3228453632,"raw":"{ \"timestamp\":\"2019-06-26T20:49:45Z\", \"event\":\"DockingRequested\", \"MarketID\":3228453632, \"StationName\":\"Schachner Dock\", \"StationType\":\"Coriolis\" }","timestamp":"2019-06-26T20:49:45Z","type":"Docking requested","fromLoad":false} 
	Line 600: 2019-06-26T20:49:45 [Debug] EDDI:eventHandler Handling event {"from":"Schachner Dock","source":"Station","player":false,"channel":"npc","message":"An ally like you is always welcome here.","raw":"{ \"timestamp\":\"2019-06-26T20:49:46Z\", \"event\":\"ReceiveText\", \"From\":\"Schachner Dock\", \"Message\":\"$DockingChatter_Allied;\", \"Message_Localised\":\"An ally like you is always welcome here.\", \"Channel\":\"npc\" }","timestamp":"2019-06-26T20:49:46Z","type":"Message received","fromLoad":false} 
	Line 601: 2019-06-26T20:49:45 [Debug] EDDI:eventHandler Handling event {"from":"Schachner Dock","source":"Station","player":false,"channel":"npc","message":"Docking request granted.","raw":"{ \"timestamp\":\"2019-06-26T20:49:46Z\", \"event\":\"ReceiveText\", \"From\":\"Schachner Dock\", \"Message\":\"$STATION_docking_granted;\", \"Message_Localised\":\"Docking request granted.\", \"Channel\":\"npc\" }","timestamp":"2019-06-26T20:49:46Z","type":"Message received","fromLoad":false} 
	Line 602: 2019-06-26T20:49:45 [Debug] EDDI:eventHandler Handling event {"station":"Schachner Dock","stationType":{"edname":"Coriolis"},"stationtype":"Coriolis Starport","landingpad":38,"marketId":3228453632,"raw":"{ \"timestamp\":\"2019-06-26T20:49:46Z\", \"event\":\"DockingGranted\", \"LandingPad\":38, \"MarketID\":3228453632, \"StationName\":\"Schachner Dock\", \"StationType\":\"Coriolis\" }","timestamp":"2019-06-26T20:49:46Z","type":"Docking granted","fromLoad":false} 
	Line 603: 2019-06-26T20:50:40 [Debug] EDDI:eventHandler Handling event {"from":"Charlie Thomas","source":"Civilian pilot","player":false,"channel":"npc","message":"You'll get no trouble from me, officer.","raw":"{ \"timestamp\":\"2019-06-26T20:50:41Z\", \"event\":\"ReceiveText\", \"From\":\"$npc_name_decorate:#name=Charlie Thomas;\", \"From_Localised\":\"Charlie Thomas\", \"Message\":\"$Commuter_AuthorityScan10;\", \"Message_Localised\":\"You'll get no trouble from me, officer.\", \"Channel\":\"npc\" }","timestamp":"2019-06-26T20:50:41Z","type":"Message received","fromLoad":false} 
```
We just released a new version. Please give it a try.

**Comment by kaimi** [comment]
That’s the thing where they did get processed, but _delayed_. E.g. the triple discovery scan thing at `2019-06-26T20:49:40` was three scans I did way before dropping into Schachner.

This is different from the general problem I have as they _were_ processed, just not anywhere near instantly.

My earlier comment on that for reference:

> This keeps getting weirder. After restarting VA, I did a couple discovery scans to check if the event would fire. It didn’t. So I continued on my way, and while I in the process of requesting docking permissions at the nearest station, the ((EDDI discovery scan)) VA command fired three times – I had tried it three times before. So in that case, after restarting (and waiting for the plugin initialisation, of course) it just had a random delay.

**Comment by Tkael** [comment]
When EDDI loads, it plays through the last play session / journal silently before it starts processing fresh events. That load time could account for the delay you've reporting.

**Comment by kaimi** [comment]
Sounds plausbile.

> We just released a new version. Please give it a try.

Will report back when/if the issue presents itself again.

**Comment by kaimi** [comment]
So, fun fact. It stopped again.

This time I looked at EDDiscovery. It had stopped updating again. So I hit the “refresh history” button in EDDiscovery. Not only did that update EDDiscovery, but it also caused about 9000 missed events (yes, slightly exaggerated) to instantly pop up all at the same time in EDDI.

I guess I’m going to file a bug against EDDiscovery; even though I have no clue why or how it would stop other journal-reading applications from being able to read said journal.

**Comment by Tkael** [comment]
Aha. It sounds like EDDiscovery may be locking that file for exclusive access.

**Comment by kaimi** [comment]
> It sounds like EDDiscovery may be locking that file for exclusive access.

No idea how that works or doesn’t work on Windows, but it definitely didn’t lock it for writing :)

Anyway, seems it’s not an EDDI issue. Thanks for sticking it out with me!

**Comment by kaimi** [comment]
Just FYI, it just happened again; EDDiscovery was behaving fine, hitting refresh there (and closing it, and restarting VA) didn’t help. Only other running application handling anything remotely related to the journal was Elite itself.

Back to square one, and I’d really like to punch my PC right now.
