### ISSUE TITLE
Enhance speech options on Text-to-Speech tab

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1353]
From forum post https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-7838471:

Would it be possible to add a more in-depth EQ to the Text-to-Speech tab? I'm looking to change the pitch of my voice to match up a bit more with Verity but at the moment it seems like the only option for this would be to fork your project and edit SpeechFX.cs file.

**Comment by Tkael** [comment]
If you're not already aware, there is a function to adjust the pitch of speech (though it probably won't give you the degree of control that you would like). See https://github.com/EDCD/EDDI/blob/develop/SpeechResponder/Help.md#speechpitch.

**Comment by richardbuckle** [comment]
Closing as we already have enough support.
