### ISSUE TITLE
Reinstate export to EDShipyard

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1358]
Reinstate the export to EDShipyard feature that was disabled a while back.

**Comment by richardbuckle** [comment]
To quote taleden:

To do the same as before, just use `https://edsy.org/#/I=` instead of `http://edshipyard.com/#/I=`

When you're ready, you can switch to POSTing to `https://edsy.org/import`

Both of those also accept urlsafe_base64(zlib_deflate(json)), where json can be the capi /profile object, or just its ship property, or line delimited journal objects, preferably filtered to Loadout events.

**Comment by Tkael** [comment]
Disabled by https://github.com/EDCD/EDDI/commit/bb4f3791a2f8f8a79d68ef42dcfabd11d621993a.
