### ISSUE TITLE
API still not working

### ISSUE THREAD

**Issue by Stevax** [EDCD/EDDI#137]
Hi, have installed 2.4.0 b4 but still not ble to connect to Frontier API, get auth code come through but not accepted. Others have said it working? Have done a full delete of EDDI and a new install but still not able to get it working.

**Comment by richardbuckle** [comment]
This is down to Frontier and we are seeing some improvement. Please be patient and keep trying.

The forum thread with the bug report to Frontier is [here](https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED)

**Comment by Stevax** [comment]
Ah, ok, I had seen the Fdev patch notes saying API fix, but it looks like it wasn’t a full fix.
