### ISSUE TITLE
Body reported as mapped even if only the ring is mapped

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1370]
## EDDI version in which issue is found
3.4.1-rc1

## VoiceAttack version in which issue is found (as applicable)
1.75

## Observed
When mapping a system EDDI tells you when the mapping is finished. But it also says this when the ring of a system has been mapped but the mapping of the body hasn't completed yet. Then after the whole body is mapped it says it again.

## Investigation
I looked at the journal and found these entries which I think triggers the speech:
```
{ "timestamp":"2019-06-21T15:24:00Z", "event":"SAAScanComplete", "BodyName":"HIP 49789 5 B Ring", "BodyID":22, "ProbesUsed":1, "EfficiencyTarget":0 }

{ "timestamp":"2019-06-21T15:34:33Z", "event":"SAAScanComplete", "BodyName":"HIP 49789 5", "BodyID":20, "ProbesUsed":32, "EfficiencyTarget":21 }
```

It looked to me like the "B Ring" part is added to the bodyname so I tried something like this:
```
{OneOf("Mapping", "{Occasionally(2, \"Surface\")} Map")}
    {if slice(body.name,len(body.name)-4,4)="Ring": 
    of Ring}
    {OneOf("is", "is now")}
    {OneOf("complete", "finished")}.
```
I wanted Eddi to tell me it finished mapping the ring first but that didn't work. To test it I had EDDI tell me the body.name 
```
{OneOf("Mapping", "{Occasionally(2, \"Surface\")} Map")}
    of {body.name}
    {OneOf("is", "is now")}
    {OneOf("complete", "finished")}.
```
but it returned this (after ring mapped and total body mapped) : 
```
Mapping of HIP 49789 5 is finished.   Bodies 7 and 12 are also good mapping candidates.
Mapping of HIP 49789 5 is now finished.   Bodies 7 and 12 are also good candidates to map.
```

**Comment by Tkael** [comment]
I think I understand... EDDI isn't counting the body as mapped when you probe a ring but it is announcing it as if it were. Is that right?

**Comment by JCalvertJoshua** [comment]
Yes I think you're right. Here's the speech for the same system:
```
Bodies 1, 2, 3, 7 and 12 are recommended candidates for mapping.

Mapping is now finished. Efficiency bonus granted.   Bodies 2, 3, 7 and 12 are also good candidates for mapping.

Mapping is finished.   Bodies 2, 3, 7 and 12 are also good candidates to map.
Surface Map is complete.   Bodies 3, 7 and 12 are also recommended candidates to map.

Surface Map is finished.   Bodies 3, 7 and 12 are also recommended candidates for mapping.
Surface Map is finished. Efficiency bonus granted.   Bodies 7 and 12 are also good mapping candidates.
```
First line was after I scanned the system with FSS.
Then I mapped body 1 which has no rings.
Then I went to body 2 and first mapped the ring. As you can see EDDI says mapping is finished but still mentions body 2 as a good candidate to map.
After mapping the planet's surface EDDI again said mapping is complete but now doesn't recommend body 2 anymore.

Same happened when mapping body 3.

So, as you said, EDDI is announcing the mapping is finished after probing the ring but it knows the surface hasn't been mapped completely yet since it still recommends the body as a mapping candidate.

It would be nice if EDDI said something like "the rings have been probed but some of the surface still needs to be mapped".

As it is now it says the mapping is finished while it knows the mapping of the surface hasn't completed yet, and still mentions the body if it is a recommended body.

Here's the system I'm in if you want to have a look https://www.edsm.net/en/system/id/30076338/name/HIP+49789
