### ISSUE TITLE
EDDI 3.4.1-rc2 crashes when connecting to Frontier API

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#1377]
## EDDI version in which issue is found
EDDI 3.4.1-rc2

## VoiceAttack version in which issue is found (as applicable)
not using it this time

## Observed
After updating to 3.4.1-rc2 EDDI crashes when trying to connect to the API.
I've tried deleting CompanionAPI.json and also de-authorizing EDDI at  https://auth.frontierstore.net/ , like VerticalBlank suggested on Discord some time ago, but still no luck.
Here's my log:

[eddi.log](https://github.com/EDCD/EDDI/files/3324111/eddi.log)

**Comment by FireSammy** [comment]
Same problem here

**Comment by Tkael** [comment]
It's an issue with a file reverting on our side. We'll be publishing another release with that correction shorty.

**Comment by Hoodathunk** [comment]
Fixed by 3.4.1-rc3.
