### ISSUE TITLE
Bodies mapped script reports no bodies mapped

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1381]
## EDDI version in which issue is found
v3.4.1 release

## VoiceAttack version in which issue is found (as applicable)
v1.7.5

## Steps to reproduce
Map a body in a system.
Run Bodies mapped script.

## Expected
Mapped bodies reported.

## Observed
No bodies mapped yet is reported.

## Investigation
It would seem that the array set up is misconfigured.
I think {cat(mappedList, [body])}  should be  {set mappedList to cat(mappedList, [body])}.
After making this change the script works as expected.

**Comment by Tkael** [comment]
Well, you aren't wrong. ;-) Thanks for reporting.
