### ISSUE TITLE
Frontier 'bug' causing multiple triggers of 'System scan complete' event.

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1385]
## EDDI version in which issue is found
v3.4.1

## VoiceAttack version in which issue is found (as applicable)
Happens with or without VA.

## Steps to reproduce
Find a new system where there are only main stars. No other bodies of any kind.
'Honk' the system on arrival.

## Expected
'System scan complete' event triggers only once.

## Observed
The event executes for each additional star after the main one.  I.E. four stars, event triggers three times.

## Investigation
After making a small addition to the 'Bodies to map' script (making it report when no bodies found) I began to notice that it was triggering multiple times for a single 'honk'.  I managed to narrow it down to only systems with multiple main stars (so not ones that orbit as a planetary body, at least not that I've found so far), and that have no other bodies.

I then tried a fresh copy of the default personality, adding in only a single line of text to speak in the 'Bodies to map' script, and it would still trigger multiple times in the given situation.

I have traced it back to the 'System scan complete' event, where 'Bodies to map' is run (my addition in 'Btm' makes it run always).  So I had a look at the game journal, and for each instance of multiple triggers, there are multiple entries of 'FSSAllBodiesFound', one for each star after the first, and this is triggering the 'Ssc' event in EDDI multiple times for the one 'honk'.

The EDDI default script doesn't indicate anything because it is silent in these situations, but my test shows that the event is still triggering.

It would seem this is a Frontier bug, so I'm not sure if you want to write anything to 'fix' it from happening in EDDI or not, but I thought I'd share anyway.  I PM'd VB on the forums to explain, and he suggested opening a ticket for T'Keal to look at.

Here's an example of the journal entries for a honk in a system where there are four main stars and no other bodies:-

```
{ "timestamp":"2019-07-01T19:30:16Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua IX-L d7-3 A", "BodyID":2, "Parents":[ {"Null":1}, {"Null":0} ], "DistanceFromArrivalLS":0.000000, "StarType":"F", "Subclass":7, "StellarMass":1.207031, "Radius":833059008.000000, "AbsoluteMagnitude":4.026596, "Age_MY":1230, "SurfaceTemperature":6352.000000, "Luminosity":"Vab", "SemiMajorAxis":3676309815296.000000, "Eccentricity":0.248998, "OrbitalInclination":-33.538601, "Periapsis":247.226028, "OrbitalPeriod":27568822272.000000, "RotationPeriod":533701.562500, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"FSSDiscoveryScan", "Progress":1.000000, "BodyCount":4, "NonBodyCount":0, "SystemName":"Pyria Thua IX-L d7-3", "SystemAddress":113321713859 }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua IX-L d7-3 B", "BodyID":3, "Parents":[ {"Null":1}, {"Null":0} ], "DistanceFromArrivalLS":66145.921875, "StarType":"M", "Subclass":4, "StellarMass":0.363281, "Radius":373920384.000000, "AbsoluteMagnitude":9.136673, "Age_MY":1230, "SurfaceTemperature":2924.000000, "Luminosity":"Va", "SemiMajorAxis":12214836658176.000000, "Eccentricity":0.248998, "OrbitalInclination":-33.538601, "Periapsis":67.226036, "OrbitalPeriod":27568822272.000000, "RotationPeriod":153406.281250, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua IX-L d7-3 D", "BodyID":6, "Parents":[ {"Null":4}, {"Null":0} ], "DistanceFromArrivalLS":572856.125000, "StarType":"M", "Subclass":3, "StellarMass":0.437500, "Radius":383195680.000000, "AbsoluteMagnitude":8.724319, "Age_MY":1230, "SurfaceTemperature":3176.000000, "Luminosity":"Va", "SemiMajorAxis":519293468672.000000, "Eccentricity":0.102922, "OrbitalInclination":-22.559607, "Periapsis":90.855774, "OrbitalPeriod":394813760.000000, "RotationPeriod":157510.140625, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua IX-L d7-3 C", "BodyID":5, "Parents":[ {"Null":4}, {"Null":0} ], "DistanceFromArrivalLS":572646.187500, "StarType":"K", "Subclass":5, "StellarMass":0.703125, "Radius":600305920.000000, "AbsoluteMagnitude":6.367981, "Age_MY":1230, "SurfaceTemperature":4365.000000, "Luminosity":"Va", "SemiMajorAxis":323116007424.000000, "Eccentricity":0.102922, "OrbitalInclination":-22.559607, "Periapsis":270.855774, "OrbitalPeriod":394813760.000000, "RotationPeriod":261294.312500, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"FSSAllBodiesFound", "SystemName":"Pyria Thua IX-L d7-3", "SystemAddress":113321713859, "Count":4 }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"FSSAllBodiesFound", "SystemName":"Pyria Thua IX-L d7-3", "SystemAddress":113321713859, "Count":4 }
{ "timestamp":"2019-07-01T19:30:17Z", "event":"FSSAllBodiesFound", "SystemName":"Pyria Thua IX-L d7-3", "SystemAddress":113321713859, "Count":4 }
```

**Comment by Darkcyde13** [comment]
Just had it happen again.  Same situation, system with only 3 stars, nothing else. 'System scan complete' triggered twice.
```
{ "timestamp":"2019-07-03T22:18:40Z", "event":"FSSDiscoveryScan", "Progress":1.000000, "BodyCount":3, "NonBodyCount":0, "SystemName":"Pyria Thua FN-B c13-0", "SystemAddress":81839309170 }
{ "timestamp":"2019-07-03T22:18:41Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua FN-B c13-0 C", "BodyID":4, "Parents":[ {"Null":2}, {"Null":0} ], "DistanceFromArrivalLS":1351.956665, "StarType":"L", "Subclass":2, "StellarMass":0.152344, "Radius":199090272.000000, "AbsoluteMagnitude":12.625320, "Age_MY":10056, "SurfaceTemperature":1795.000000, "Luminosity":"V", "SemiMajorAxis":16525709312.000000, "Eccentricity":0.299157, "OrbitalInclination":-24.526524, "Periapsis":234.074692, "OrbitalPeriod":2242147.000000, "RotationPeriod":90287.656250, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-03T22:18:41Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pyria Thua FN-B c13-0 B", "BodyID":3, "Parents":[ {"Null":2}, {"Null":0} ], "DistanceFromArrivalLS":1348.238892, "StarType":"M", "Subclass":1, "StellarMass":0.468750, "Radius":444557088.000000, "AbsoluteMagnitude":8.029678, "Age_MY":10056, "SurfaceTemperature":3460.000000, "Luminosity":"Va", "SemiMajorAxis":5370854912.000000, "Eccentricity":0.299157, "OrbitalInclination":-24.526524, "Periapsis":54.074718, "OrbitalPeriod":2242147.000000, "RotationPeriod":198143.562500, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
{ "timestamp":"2019-07-03T22:18:41Z", "event":"FSSAllBodiesFound", "SystemName":"Pyria Thua FN-B c13-0", "SystemAddress":81839309170, "Count":3 }
{ "timestamp":"2019-07-03T22:18:41Z", "event":"FSSAllBodiesFound", "SystemName":"Pyria Thua FN-B c13-0", "SystemAddress":81839309170, "Count":3 }
{ "timestamp":"2019-07-03T22:19:01Z", "event":"ReservoirReplenished", "FuelMain":27.562090, "FuelReservoir":0.630000 }
```

**Comment by Tkael** [comment]
Hmm. I'm loathe to suppress these because I want to be able to have people "honk"and get feedback from this event more than once in a given system. We could consider a timed suppression, but realistically that'd be a bandaid until FDev corrects the problem at the source.

**Comment by Darkcyde13** [comment]
I understand.  I've had a basic fix in place, but it does block all executions of System scan complete when only stars are in the system, so not ideal.

However, this morning I came up with another idea that is just as simple.  It should fix the multiple executions, and at the same time allow 'Ssc' to run whenever the honk is done.  Of course this is only with the scripts, so you may be able to patch EDDI more efficiently than this...

1. In 'Discovery scan', at the start set a state variable to zero. Say, 'eddi_context_onlystars' for example.
2. Add a calculation for the number of stars in the FOR loop (i.e. scannedStars).
3. Add an ELIF after the main IF, to compare scannedStars to event.bodies to see if they are equal.
4. If equal, set state variable to 1.
5. In System Scan Complete, put the whole thing in {if state.eddi_context_onlystars < 2: ...}
6. At the very end make the state variable = +1.

By setting the state variable to zero in Discovery scan, it resets the whole thing when a honk is performed.  If only stars are found, it's set to 1.  When System scan complete triggers, it will always run the first time (state var is < 2), but any subsequent triggers will fail as the state var is now 2+, but this is reset when the honk is done, allowing as many honks as you want in a system.

I ran the scripts through my head, and I'm fairly confident that this should work fine. I'm going to add it all now and see how it goes.  I'll let you know if it works or not. :)

**Comment by Darkcyde13** [comment]
Do you ever get those forehead-slapping "doh!" moments?  I've just realised I've been approaching this from the wrong angle, and that it can be done much simpler...
1, In 'Jumped' event, set a state variable to false (eddi_context_system_complete maybe).
2. In 'System scan complete' event. put it all inside {if !state.eddi_context_system_complete: … }
3. At the end of 'System scan complete' set the state variable to true.

As 'System scan complete' is only supposed to trigger once, when the system has been all done, this should work perfectly.  I won't matter how many honks you do at all, you'll still get the same amount of info.

**Comment by Tkael** [comment]
Got it (handling it in code, not in the scripts).
