### ISSUE TITLE
EDDI does not report value of scanned bodies!

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1386]
EDDI 3.4.1

VoiceAttack 1.7.2

Steps to reproduce
1. Scan a body using FSS 
2. Expect EDDI to give value of body as it did before update.

EDDI now does not give me the estimated value of a scanned body for some reason, like it has always done. It also used to give me info on every scanned body, but now it only comments on anything notable and does not go into detail. I could not find any options to tweak this.

I think that some of the script variables in EDDI have been set to off on the new update, such as scannedbodyvalue 0. ?

**Comment by Tkael** [comment]
Scans now use the `Body report summary` script, which by default does not include the body's scan value (thought that value is available as described below). Rather, EDDI will advise you to map valuable planets (either after you've completed the full system scan or whenever you invoke the `Bodies to map` script) and will present a complete `Body report` (including scan + map value if you wish to activate that option) after mapping. 

Note: You can access the scan value at any time by accessing the body object's `estimatedvalue` property. e.g.
```
{set reportbody to BodyDetails(`somebody`, `somesystem`)}
The estimated exploration value is {Humanise(reportbody.estimatedvalue)} credits
```

**Comment by Tkael** [comment]
If you prefer the old behavior (full report on body scan), you can also open the `Body scanned` script and set `fullBodyReport` to 1.

**Comment by Tkael** [comment]
Closing as resolved (though I'll receive notifications if you respond to this ticket again). o7 commander!

**Comment by incryptx** [comment]
Well, setting the "fullbodyreport" to one fixed it, but this should be the default, not zero.

**Comment by Tkael** [comment]
I don't agree, but that's why we try to make preferences easy to set. 😉
