### ISSUE TITLE
Elite Ground Proximity Warning System or Terrain Avoidance Script

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1391]
Suggestion/Enhancement

A small EDDI Script for Ground Proximity Warning System when landing on HIgh Gravity Planets.

Elite has a Ground Proximity Warning System or Terrain Avoidance built in to the game now. The alerts (Terrain proximity/Collision) appear top right of the HUD, a high sink rate warning is also available through the vertical speed indicator once in orbital cruise. G readout is also bottom right of the HUD)

I suggest a small EDDI script, which could be added as an "Event" in the "Speech Responder" called "GPWS" which could include the following.

1) 1 audio alert when you go into glide mode, if the gravity is low or high.
2) 1 audio alert if you're flying fast with your nose pointed to the ground. (the pull up)
3) 1 audio alert if you height is low.

It would also be nice to have the audio alerts tell if you are breaking a given height. When it says you're hitting the minimum altitude when you hit 30k 20k 10k and 5k meters.

This script would act the same way for jet aircraft when they are approaching mountains or getting ready to stall, but in our game, instead of stalling, would give warnings as you decending too fast on a high gravity planet.

I think this would be a valuable addition to EDDI and would be of great benefit to all commanders as the ques currently in the game give no audible warning at all, just HUD information.

**Comment by Tkael** [comment]
I've played around with a terrain warning event, but I haven't come up with a solution that I've been very happy with yet. We don't receive any data from FDev corresponding to the in-ship signals.

Other comments:
1. Glide mode is currently broken - FDev doesn't provide an official event for this and the detection method we used to use suddenly stopped working after a recent update. The jury's still out on whether we'll be able to restore glide mode in the future. Were the `glide` event working, however, it would already alert users of high gravity worlds. 
2. Neither the ship's speed nor the ship's orientation is available in the data FDev provides.
3. Altitude is available as a property of the `status` object (so anyone with VoiceAttack can already react to it by polling it's value). That said, the `status` object is updated about once per second (which may not be enough if you are accelerating very quickly towards a surface!).

**Comment by incryptx** [comment]
I was going to add it to the Frontier forum as a suggestion, but I doubt they would do anything about it.

Since we need it to be audio or audible, I thought adding it to EDDI as a script would be simple, but reading your comments, it sounds impossible at the moment.

I thought about asking VA and HCS, as the singularity.vap file is locked by the author, and I doubt they would as they are more interested in providing voices for events than adding events for voices to respond to.

Thanks for your input. Let me know if things change.

**Comment by Tkael** [comment]
The biggest problem would be the lag... since we're only receiving about one sample per second we're be looking at being at least 3 seconds behind on any change in acceleration - more if we try to add more data points to smooth the data. 
Sorry, I'd like to have this too. :-)
