### ISSUE TITLE
Add support for TTS lexicons

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#140]
Scan `lexicon` subdirs in the EDDI install dir and the EDDI %appdata% dir for `*.pls` and add them to any SpeechSynthesizer object that EDDI creates.

Add all lexicons thus found *in that order*. This will ensure that lexicions in the %appdata% dir will override those in the EDDI install dir.

Write up the lexicon format for advanced users.

Refs:
~~https://msdn.microsoft.com/en-us/library/hh378339(v=office.14).aspx~~
https://docs.microsoft.com/en-us/dotnet/api/system.speech.synthesis.speechsynthesizer.addlexicon?view=netframework-4.8#System_Speech_Synthesis_SpeechSynthesizer_AddLexicon_System_Uri_System_String_
https://www.w3.org/TR/pronunciation-lexicon/

**Comment by richardbuckle** [comment]
Refer to #98.

**Comment by Corysia** [comment]
I contacted Cereproc to find out about their method of handling customized pronunciation.  I gave them the example of Heather and Caitlin, two of their voices, where Heather cannot pronounce Caiomhe or Siobhan correctly.  They provided me with instructions for how to fix that.

Create a file to hold the lexicons.  e.g., `c:\Program Files (x86)\CereProc\CereProc Heather 5.0.1\user_lexicon.txt`

The file should contain the word, and then the phonetic description:
`caoimhe k_w_ii1_v_@0`

[CereVoicePhoneSets.pdf](https://github.com/EDCD/EDDI/files/3100841/CereVoicePhoneSets.pdf)

**Comment by Tkael** [comment]
Some more information about Cereproc support for lexicons is available here: https://www.cereproc.com/files/CereVoiceCloudGuide.pdf

It looks like they are claiming support for standard SSML lexicons (using IPA) and also for their own custom phoneme set.

**Comment by Tkael** [comment]
Are the names `Caiomhe` and `Siobhan` ship names? If so, how well are they supported by using IPA pronunciations?

**Comment by Corysia** [comment]
Email shuffled this off in to another folder and I didn't see this until now.  Caoimhe and Siobhan are female Irish names, as Sean and Gavin are male.  I still think a simple word replacement would work.  Caoimhe=kweeva  Siobhan=chevon.

**Comment by Corysia** [comment]
Oh and Caoimhe O'Shea is my CMDR.  Siobhan is the name of my new VAP.  It sounds like VerticalBlank has trouble with CMDR pronunciation too.

**Comment by Tkael** [comment]
Cereproc voices do depart remarkably from the standard method used for supporting lexicons... it's a completely different file format and structure.

**Comment by Tkael** [comment]
And it looks like the System.Speech.SpeechSynthesizer method "AddLexicon" may be bugged. Great... 
https://stackoverflow.com/questions/11529164/how-do-i-use-a-lexicon-with-speechsynthesizer

**Comment by richardbuckle** [comment]
I found that if I open the Windows Speech Properties control panel (`C:\Windows\SysWOW64\Speech\SpeechUX\sapi.cpl` on my system) and click the Settings button for an IVONA voice, it opens up a custom app that lets me create a global override lexicon for that voice. The lexicons are stored in `%PROGRAMDATA%\NextUp-Ivona\Ivona-SAPI\lex` and are tab-separated text.

**Comment by Tkael** [comment]
Yes, but that is a rather Ivona specific feature. 
Once again, the deprecated speech synthesizer we are using may be having more of an impact than the specific voices.

**Comment by Tkael** [comment]
Resolved by #2222.
