### ISSUE TITLE
"Jumped" Script Not Updating Properly

### ISSUE THREAD

**Issue by c0dejunKie** [EDCD/EDDI#1407]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

Started happening in v3.4.1 and is continuing to happen in v3.4.2-b1

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

v1.7.6

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

I set a route and make my way to the final system in my route.  When I arrive at the final system in my route, the "jumped" script is triggered.

## Expected
[Describe what you expected to happen]

I expected eddi to list the proper system that I have targeted in my route and to be accurate when telling me how many jumps I have remaining. 

## Observed
[Describe what happened instead]

No matter what system I have targeted in my route and no matter if I have for example 10 jumps remaining or even if I'm arriving at my destination, when the "jumped" script is triggered, EDDI tells me "Distance to LT 34487 is 90.5 Ly with 4 jumps remaining".  This happens no matter what system I am in or the route I have set. 

The last system that I jumped into before logging out last is "G 41-14" which was my final destination of my route.   When I arrived I was told by eddi  "distance to LT 34487 is 90.5 Ly with 4 jumps remaining".  For some reason it seems that eddi is stuck on this system and no matter what my route is, it keeps telling me this info and is not updating to the route that I have targeted.

When I search eddb.io for system "LT 34487" I find nothing, so I am very confused by where eddi is getting this information. 

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

I have reviewed the "jumped" script and confirmed that it is the latest default script and that is has not been changed.  Here is the "jumped" script that I have:

{_ Jumped }
{_ Triggered when you complete a jump to another system }

{_ Context }
{SetState('eddi_context_last_subject', 'jump')}
{SetState('eddi_context_last_action', 'complete')}
{SetState('eddi_context_system_name', system.name)}
{SetState('eddi_context_system_system', system.name)}
{SetState('eddi_context_fuel_remaining', event.fuelremaining)}
{SetState('eddi_context_fuel_used', event.fuelused)}
{SetState('eddi_context_wanted_list', "")}

{if event.destination && event.destination != "":
    {if event.destdistance = 0:
        {ShipName()} has arrived at the {P(event.destination)} system.
        {Pause(1000)}
        {set next_system to RouteDetails("update")}
    |else:
        {set jump_mass to ship.unladenmass + ship.maxfuelperjump}
        {set jump_range to ship.maxjumprange * jump_mass / (jump_mass + cargoCarried)}
        {set jumps_left to ceil(event.destdistance / jump_range)}
        Distance to {P(event.destination)} is {round(event.destdistance, 1)} light years,
        with {jumps_left} {if jumps_left = 1: jump |else: jumps} remaining.
    }
}

{F('Fuel check')}

{set state_report to F("System state report")}
{set system_missions to F("Mission check system")}
{set system_crimes to F("Crime check system")}

{if state_report || system_missions || (system_crimes && find(system_crimes, "Warning") < 0):
    {Pause(500)}
    Information:
}

{if state_report:
    {Pause(500)}
    {state_report}
}
{if system_missions:
    {Pause(500)}
    {system_missions}
}
{if system_crimes:
    {Pause(500)}
    {system_crimes}
}

Please let me know if I can provide anymore information.  

I have attached my journal from last night in hopes of it helping.

[Journal.190718005301.01.log](https://github.com/EDCD/EDDI/files/3408302/Journal.190718005301.01.log)

**Comment by Tkael** [comment]
Huh. You seem to have set a destination that doesn't exist (perhaps using the `RouteDetails() function?). Here's what I want you to do:
1. Open EDDI's UI
2. Open the `Mission monitor` tab
3. Click the `Clear Route` button.
Does this resolve the issue?

**Comment by c0dejunKie** [comment]
> Huh. You seem to have set a destination that doesn't exist (perhaps using the `RouteDetails() function in EDDI's UI or using the `route` VoiceAttack plugin command?). Here's what I want you to do:
> 
> 1. Open EDDI's UI
> 2. Open the `Mission monitor` tab
> 3. Click the `Clear Route` button.
>    Does this resolve the issue?

Yep that seemed to have worked, not sure how this even happened but at least its fixed now :) .  I honestly didn't even know that those buttons for "Clear Route" and the others were even there, or I would have tried it before creating this post.  Sorry for wasting your time, but thanks alot for your help, it was getting really annoying.
