### ISSUE TITLE
Ship refuelled event - event.full always true

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1410]
## EDDI version in which issue is found
V3.4.1 and v3.4.2-b1, with the default EDDI personality.

## VoiceAttack version in which issue is found (as applicable)
V1.7.7

## Steps to reproduce
Scoop fuel at a star.

## Expected
Ship refuelled event only makes one report.

## Observed
About half the time, the event will report twice from scooping fuel.

## Investigation
After hearing some reports twice for a single scoop action, I looked into what was going on.  The Journal is reporting fuel twice, as we have noted in the past and subsequently accounted for in the script, but it looked like that wasn't working anymore.
```
{ "timestamp":"2019-07-20T22:45:28Z", "event":"FuelScoop", "Scooped":5.002489, "Total":31.581266 }
{ "timestamp":"2019-07-20T22:45:28Z", "event":"FuelScoop", "Scooped":0.418732, "Total":32.000000 }
```

Well, after messing about with variables to try to fix it, I ended up making the script just list the state of all variables, and this is when I found that 'event.full' is always set to true, even when the scoop was only the first report of 5.002489, which is what we accounted for in the script.  Thus the script is always executing the '{if event.full:' part of the code, even if the scoop wasn't a full completion.

> 13. Fuel remaining: 31.581266. Event total: 31.581266. Event full: true. A. Maximum fuel
> 14. Fuel remaining: 32. Event total: 32. Event full: true. A. Fuel at maximum

I named the {if event.full: as A. and the |else: as B.  The 13 & 14 are an incremental count of the number of executions of the event as I was testing.

As you can see from number 13, event.full should not be set as true.  This was immediately after an EDDI and game load, so the variable is set as true right from the start and not just getting stuck after a full refuel.

**Comment by Darkcyde13** [comment]
Hmm, after a couple of game reloads, it's now working as expected.  I think I need to run more tests, and more game reloads.  I know this has been happening (to me at least) since I installed v3.4.1,

**Comment by Tkael** [comment]
As you can see, the event doesn't provide a value that directly equates to whether you have a full tank. Rather, we compare the total to the ship's total. Consequently, if this is occurring then it probably means that EDDI "thinks" that you are in one ship when you are in fact in another.

**Comment by Tkael** [comment]
Another thought that occurs... this sort of event might trigger more than once if a "ReservoirReplenished" event is written between "FuelScoop" events. (The reservoir replenished event means that fuel is removed from the main tank to refill the reservoir)

**Comment by Darkcyde13** [comment]
Hmm, yeah I can understand that as being a possibility.

I have started up a new game today and it's happened again in the second system I jumped to.

> 3. Fuel remaining: 31.552881. Event total: 31.552881. Event full: true. A. Refueled
> 4. Fuel remaining: 32. Event total: 32. Event full: true. A. Into the Black 2 is now at 100% fuel capacity
```
{ "timestamp":"2019-07-21T16:28:35Z", "event":"FuelScoop", "Scooped":5.001066, "Total":31.552881 }
{ "timestamp":"2019-07-21T16:28:35Z", "event":"FuelScoop", "Scooped":0.447121, "Total":32.000000 }
```
This is with the reserve reservoir at about 70% full, so no replenished event anywhere near this scooping.

The first system I scooped at in this session worked fine:-
> 1. Fuel remaining: 30.807329. Event total: 30.807329. Event full:.
> 2. Fuel remaining: 32. Event total: 32. Event full: true. A. Refueled
```
{ "timestamp":"2019-07-21T16:16:13Z", "event":"FuelScoop", "Scooped":5.001352, "Total":30.807329 }
{ "timestamp":"2019-07-21T16:16:14Z", "event":"FuelScoop", "Scooped":1.192670, "Total":32.000000 }
```
Again, there was no replenished event anywhere near this scooping either.

I've just noticed that with the first set (1 & 2), the timestamp is 1 second later.  However, for the 'failed' set (3 & 4), the timestamp is exactly the same.  Could it be that the event.full is being set from number 4 at exactly the same time as 3 is being processed, and thus making it think it's a full scoop when it's not?  I mean could this be some kind of timing issue?  My first example above also has exactly the same timestamp.

After some experimentation, I've temporarily patched the script by adding this at the top:-
```
{if event.total = ship.fueltanktotalcapacity:
    {set event_full to true}
}
```
And then changing all instances of event.full to event_full.  This seems to be working ok.  I'm going to run some more tests to see if my theory has any weight to it.

**Comment by Tkael** [comment]
I think I see the issue - we're rounding to determine whether the "full" bool should be set, so any event recording more than 31.5 tons gets the bool set.

**Comment by Darkcyde13** [comment]
Ah, that does make sense.

I was just coming back to report that I've had another instance of the timestamp being different, but it still 'failed', so I was wrong about the timing thing.

However, as you've said about the rounding, I've looked back over the last set of tests, and every one that failed is indeed over 31.5, so it looks like you are most probably correct.  Hopefully that will be an easy fix. :)

**Comment by Tkael** [comment]
Should be. I'm already on it.
