### ISSUE TITLE
Clarify VoiceAttack documentation - 'say' plugin function only uses Script variable for input

### ISSUE THREAD

**Issue by Datura359** [EDCD/EDDI#1432]
## EDDI Versions:
3.4.2-b1
3.4.1

## Voice Attack Version:
1.7.7

## Expected Behaviour
While attempting to use the 'say' plugin function I was getting inconsistent feedback from EDDI's TTS system where it would repeat only one bit of text I had fed it, even though I was calling to it with different variables that had different text contained in them.  

## Steps to reproduce
1) Create a Voice Attack command triggered however you desire.
2) Add a text variable named "Script" that contains "This is the appropriate way of doing this".
3) Add the "Execute an external plugin function" command with the following settings:
* Plugin: EDDI
* Plugin Context: say
* Text Variables; Script
4) Trigger the Voice Attack command.
5) Create another Voice Attack command, triggered however you desire.
6) Add a text variable named "Words" that contains "This is a test".
7) Add the "Execute an external plugin function" command with the following settings:
* Plugin: EDDI
* Plugin Context: say
* Text Variables; Words
8) Trigger the second Voice Attack command.

## Observed
The first command should execute correctly, and you'll hear the words "This is the appropriate way of doing this".  When you trigger the second command created, you would expect the TTS system to speak the words "This is a test", however, in my testing, it would repeat the original words "This is the appropriate way of doing this" which is incorrect.

## Investigation
Through a bit of messing about, I found that if I used the variable [Script] every single time whenever I was calling the plugin function that the TTS system was finally behaving as expected and would speak the expected text.  This is not well defined in the documentation, and I'm not sure that this is the intended behaviour.  I would imagine that one should be able to call the say function while passing any text variable and EDDI would then read whatever it is sent, rather than having to only send the one variable of [Script].

**Comment by Tkael** [comment]
Are you waiting for the first `say` action to be completed before VA executes the second?

**Comment by Datura359** [comment]
> Are you waiting for the first `say` action to be completed before VA executes the second?

Yes.  VA commands are run sequentially by different triggers and the same behaviour persists even when using VA's built in option to wait for the Plugin function to finish before executing other commands, and when VA's option to allow other commands to execute is unchecked.

**Comment by Tkael** [comment]
Ah, I think I understand better now. Yes, the current design does require the word `Script` to be used to pass the value to the plugin. I'll have to double check the code to see why that is and whether it could be made more flexible.

**Comment by Hoodathunk** [comment]
jgm hard wired the text variable to `Script` before we took over. As an expert in VA profile coding, I see no compelling reason to go back... execution efficiency will not substantially improve, commensurate with the effort required.

**Comment by Tkael** [comment]
I'll double check with Gary, but after reviewing [the VoiceAttack documentation](https://www.voiceattack.com/VoiceAttackHelp.pdf) for the `vaProxy.GetText(string variableName)` method it looks like we do need to have a __known variable name__ to be able to retrieve the stored value from VoiceAttack.

**Comment by Tkael** [comment]
After giving this a little more thought, I think we need to keep the current design. Changing it would break current functionality... for example passing a voice selection and a script to EDDI simultaneously is currently possible but would no longer be possible if we didn't have a known variable name. 
![Untitled](https://user-images.githubusercontent.com/4382539/62506348-20df9d00-b7b5-11e9-9189-51a1b2a04d3e.png)

**Comment by Tkael** [comment]
I think our response to this issue should focus on clarifying the documentation with a few screenshots like the one above.

**Comment by alterNERDtive** [comment]
The “NOTE” on page 170 of the VoiceAttack documentation clearly says that all that passing of variables stuff is deprecated anyway and just for backwards compatibility.

It could be made more clear in the actual interface, but that’s not an EDDI issue.

**Comment by richardbuckle** [comment]
Fixed for 3.4.4-b1
