### ISSUE TITLE
EDDI goes into a loop reciting recent events when using EDDI with VoiceAttack

### ISSUE THREAD

**Issue by intelfx** [EDCD/EDDI#1434]
## EDDI version in which issue is found
3.4.1, 3.4.2-b1

## VoiceAttack version in which issue is found (as applicable)
1.7.7

## Steps to reproduce
1. Install VoiceAttack + EDDI in the default configuration
2. Use this profile: [Elite Dangerous (intelfx)-Profile.zip](https://github.com/EDCD/EDDI/files/3499407/Elite.Dangerous.intelfx.-Profile.zip)
3. Launch VoiceAttack when the game is not running

## Expected
EDDI starts up normally within VoiceAttack and remains silent.

## Observed
VoiceAttack process hogs 100% CPU for some time and EDDI starts reciting recent events, apparently going into a loop somewhere in that process.

## Investigation
- Logs: [EDDI.zip](https://github.com/EDCD/EDDI/files/3499413/EDDI.zip)

**Comment by Tkael** [comment]
ok. Let's try the following...
1. Close VoiceAttack and EDDI. 
2. Open Elite Dangerous and log into any game mode.
3. Close Elite Dangerous
4. Start VoiceAttack. Does the issue persist?

**Comment by Tkael** [comment]
Hi, is this issue still active?

**Comment by intelfx** [comment]
@Tkael Presumably yes — I haven’t had a chance to play Elite since this was reported.

**Comment by Hoodathunk** [comment]
@intelfx please try @Tkael 's suggestion and report back on the results.

Also, some context into what EDDI was 'reciting' would be very useful.

**Comment by intelfx** [comment]
@Hoodathunk I understand that you want me to try his scenario. I’m saying that I haven’t yet had the time to do this (or play Elite at all).

**Comment by Hoodathunk** [comment]
And some context on the events EDDI was 'reciting' would still be useful.

**Comment by intelfx** [comment]
@Hoodathunk Basically everything, from hyperspace jumps to targeted ships’ legal status reports.

**Comment by richardbuckle** [comment]
Not to worry. Next time you play Elite, if you could re-test with the latest EDDI build (3.4.2 final is imminent) that would be a great help.

**Comment by Tkael** [comment]
Closing due to lack of information and inability to replicate for the time being. If you are still experiencing this issue with the new installer and respond to this ticket, we'll get the notification and be able to re-open the ticket.
