### ISSUE TITLE
Virus Alert

### ISSUE THREAD

**Issue by CmdrThorik** [EDCD/EDDI#1446]
## EDDI version in which issue is found
3.4.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Just download and once the download completes the AV from Norton Security alerts to virus.
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]
No virus alert

## Observed
[Describe what happened instead]
AV alerts to presence of virus and then quarantines the 3.4.2 installer

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
None

**Comment by Tkael** [comment]
This sounds like a false positive. The project is open source and the source code is freely available for review. 
If you don't  mind me asking, what kind of virus does Norton think it detected?

**Comment by CmdrThorik** [comment]
I thought of it being a false-positive.  I just got home and downloaded it,
and this time it was a clean scan.  All is well.  Thanks!
