### ISSUE TITLE
Can't login to the Frontier API after update.

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1451]
V.3.4.2

In attempting to authorize EDDI, it hangs on "connecting" when I hit "login"

I have "authorized" and "de-authorized" EDDI in the Frontier User Portal many times. Each time, EDDI does authorize, but does not finish the "approval" process.

EDDI throws up a "EDDI one instance" dialog box each time I try to approve the application, but there is only one running, the one I'm trying to authorize.

I think v.3.4.2 is bugged and will not authorize.

Before this update, EDDI was authorized, logged in and working fine.

**Comment by Tkael** [comment]
I'm able to connect to the Frontier API, so I don't think that we can say that 3.4.2 is bugged so that it never connects. Furthermore, nothing that we've changed recently should affect this portion of the code. 

When you say that you have authorized and deauthorized EDDI in the Frontier User Portal, are you following these steps?
```
1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.
```
If so, then the next time that you deauthorize EDDI please (making sure that it is entirely closed first) and navigate to `%appdata%/EDDI` and delete `companionAPI.json` prior to re-authorizing EDDI.

**Comment by incryptx** [comment]
I deleted the companionapi.json, but this did not help.

Nothing changed on my system between the version before v3.4.1 and v3.4.2 so, I don't know why it does not authorize now. Do you have a link to v3.4.2 as I would like to "uninstall" EDDI, clean the registry and "reinstall", since EDDI does its own updates, I do not have a copy of the full installable version?
All I see available for download is v3.4.3 b1.

**Comment by incryptx** [comment]
Hello

I uninstalled v3.4.2 and reinstalled it. I deleted the %appdata%\EDDI directory and the EDDI main directory itself, cleaned the registry, and reinstalled. No difference in action. EDDI does connect to EDSM with it's API key and that works fine. I also approved all sites involved with Firefox and cleared the cookies for each. 

The only thing I can think of is that Firefox is not receiving the "final step" in the approval process which is "approved". That window never comes back. It just stays on the "approve/deny" window, and although EDDI is being approved, the "approved" window never shows up. If I hit "approve" a second time, the Frontier API site comes back with "Frontier Server Error".

As soon as I hit "approve" on the Frontier API approval site, EDDI throws up a dialog box which states "Only one instance of EDDI can run at one time". I only have one instance of the EDDI application open, the one I'm trying to authorize. I checked "processes" and there is only one instance running. 

Firefox updates with changes all the time. It must be something in Firefox not allowing the process to conclude with the "Approved" window.

**Comment by incryptx** [comment]
Apparently, EDDI does not like to be run as administrator. I don't know why it thinks there are more than one instance running when you try the approval process, but once I disabled it from running as administrator, it connected.

I don't know if this fact represents a bug, but maybe a warning somewhere, or a popup, stating that the user is running EDDI with administrator permissions would be wise.

Close the bug.

**Comment by Tkael** [comment]
I'm surprised that administrator privileges seemed to make the difference in the end but I'm glad you were able to get it working. We'll keep your findings under consideration if other people report a similar issue. o7

**Comment by richardbuckle** [comment]
That would probably be the window that Firefox pops up asking you to allow the "eddi" URL scheme to be associated with the EDDI app. This is an important security safeguard.

I myself have found that clicking the mouse too much while impatient will lose that important little modeless window in the background.

**Comment by Avrii** [comment]
> Apparently, EDDI does not like to be run as administrator. I don't know why it thinks there are more than one instance running when you try the approval process, but once I disabled it from running as administrator, it connected.

This fixed it for me, as well. I've been having this issue for months, checking here periodically. When EDDI is being run as Administrator, it seems to break the handshake between browser and application with the warning/focus popup. I vaguely recall needing to use Administrator privs on my machine way, way back with EDDI, so the setting was an unhelpful relic.

**Comment by richardbuckle** [comment]
It is not so much running EDDI as Admin, it is running EDDI as _anyone_ other than the desktop user. The OAuth dance requires a conversation to be held within the context of a single user session, whereby an app can open an HTTPS session and supply a custom callback URL protocol (such as `eddi`) by which said HTTPS session can return data to the originating app. 

That is why running EDDI under another account will break Frontier API login.
