### ISSUE TITLE
Shipyard: Ships fail to export to Coriolis

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#146]
## Steps to reproduce
1. Open the shipyard
2. Choose a ship
3. Select 'Export to Coriolis'

## Expected
My browser should open an export of the ship in Coriolis. Example here (this is the only ship in my shipyard that opens successfully):
`https://coriolis.edcd.io/import?data=H4sIAAAAAAAEAM2YQW%2FiOhCA%2F8pTzhxiO3Zsbgvd3a7UaqvSO3KJC1aDHTlO9%2FFW%2Fe9vkhRIGgwr1K7gGDwzn8cz4xn%2FjnQWjWkyioxcq2gcTSvvlYtG0YvMK%2FjwO1pVeR6NEaOMixjxUbS2WZWrMhqnTCQMM4pH0UK6pY3G8Sjy1ktYLwhFFLEUvlQmt9IosINAi%2BDsdRQ9OQXKn2ReqlFUeum1NbWxmgZhzlKcJHQH9fOx1JmW5p%2Bf7lHX6l8bIVduSq%2FWWzmWxEjsZG6llrCNdonMMqdKQOYYMYRImghQIXP9Aku9qwBipWTuV50Nx80PNKy0yrPBh6rYSmrj1dJpv4nGGPwRg4sKCR9%2FWff89ikFawu7eC60nzglF6vaG2%2B7t%2F9ulsrcA6Q22iyjcUJbOzs%2F%2F45uVaar9bV0WWFBM66%2FtX93nBYnIon3Trsu%2FPyuAhM3slRuUrnSz7%2Fr9aPM5626%2FSEnCGP67lC2%2Fthtuz6gdsOF0%2FZtv6%2BwsXdw6JLhkiAcIT24iZLrhi2MlfCUfBQX%2BTtcQkC6kiNYN5DH6g%2FijKEe1W2Vez2Vxliz5Wo0dbBSQXgcxkKc%2FzFWOMI%2BFuv0KV5XJ7EYR0KwU1i1oj0VxZwmhAW9RVJ6jOpBm80pKsYp6VPNmrI2sRYKppvP9H8qnk9zWZZ0D4YJ5qkIcaUsIeIwFxlwHY6tz%2BA6eoxDsMOpeAFgh2vXBYDRjwXjnJ6VkUMwdqkeS0MVjHY6mBrsWkk%2F0%2Bb5RlYGugY3f6icU35ea%2BugQWN2RrEYcvG%2FxnXaYVdqIfNQ9UpTui%2F1zcr5g5OZmn%2FNte9U0rMCCe3MHy5SKRVxfWn0zLf1%2FMMsH65Cn2z5i1vbyoVigHQst2PCvBWY30NL6%2Bteen%2BvxnDtEXJeIjcsd%2FaXcne5NP4wD3T7LN3x%2FDDQT9YSRS3RZDAfZDAiSZoQWs8rZ0LBUGG%2BmqU2bVt%2BiArFuEfVLv8Morgm%2BubAFJSvJ3%2FlmmkmQEX6VNebQrmslmjI0gFZgmlMOT2rwW3AbvSTmlVFYV3wABETPaiOSJcKdxojmN54yFlCgEJ8pKI0AXKlS%2B%2F0Y%2BVtINBZghEeBlZHLuAyEKWEJGcH173MZJgp6ftqpkxpXXmWnzhlAh0B%2BVap%2FEGa5xAL6dTemmW7voFhLQzp3AKcQDU42y2z3PoYtQkU7rD7Jza1ztlSW3PnrH2a1o8T93LRAqKBt2DATM662Pd8%2BML5SHs2F8uXXDgfPcaXQnXl%2Fexs%2BsnvyigntwXjLTFAk3fWLDv5ESNEUDBDhEhx%2FRYWrLQNIGtshDpxaHnjQcrOFtYWrdiglkF7JTgO1TIhaPPqdwgp2SGlx5Au4Ex5ozowVaUYi36Vm1TL5WYiN63UAChFLD6r9u8dJhrVofmTUNYHmnmV59JNbLaBy2lhX5TbzBbQDNaNWfYizUJlHYfRmMEoELwTYEo42vloaKyl28SBxxe4FTA%2BkANTYJxs74ZhnEG3xNPkyI2OUeBdiPSoAi9Vn0J1enSp21ZVc30pCmflYjWr6qkkEGgEvetjG%2Bm%2BaPd578yof339H9nBGBTtFwAA&bn=Multi-purpose%20Imperial%20Cutter`

## Observed
The browser opens a blank black page. Example here: 
`https://coriolis.edcd.io/import?data=H4sIAAAAAAAEAFWPzY7CIBSFX2Vy1ywo1EthPYn7eYMboZWEguFnTGP67qKT0bg9Od%2F5uYG3YKRiEGl1YOA7hcvZR2DwS6F15QbnFgKYgU%2BoD8hgTbYFV8AgcqVlV06UlwSGM6ipUvcq1OOkBYMWQ6LoesWBoxh2BnN2PXSmUByDUqn6FB8lzxlCSDlKHPA154e2ryNVd6UN9ieQy1aqW%2F8ZVHwc1Cj0NOn3CU9Lo2iz7z%2F%2B%2FGRtdqV8Avt%2BB73D%2B%2F4AAQAA&bn=Multi-purpose%20Dolphin`

## Investigation
Possibly a failure to parse data on some engineered modules? All of my current ships have had some engineering done.

**Comment by StivlWrith** [comment]
Look to work fine for me with the v2.4.0-b4 i get the link [for my actual ship](https://coriolis.edcd.io/outfit/imperial_clipper?code=A0pntkFflndpsnf4-----02-023h11f403-v62i2f.AwRj4yVaaA%3D%3D.EwRmAZK6ZFLkA%3D%3D%3D.&bn=Serial%20tourist)
and a short link [https://eddp.co/u/CtyUkZPg](https://eddp.co/u/CtyUkZPg)

If you want i make specials tests, just say what to do

**Comment by Tkael** [comment]
Appears to be related to this issue on Coriolis: https://github.com/EDCD/coriolis/issues/152

**Comment by richardbuckle** [comment]
I'd like to get this into 2.4.0 if it can be fixed at the Coriolis end

**Comment by strideynet** [comment]
Issue isn't Coriolis.  
  
The second link you provide contains the following JSON:  
`Object { id: 37, name: "Dolphin", value: Object, free: false, station: Object, starsystem: Object }`  
    
That is not the ship export data from Companion API.

**Comment by Tkael** [comment]
I concur. Shipmonitor.json is not storing full / sufficient information. Here's the complete info from the json:
```    {
      "LocalId": 37,
      "cargocapacity": 0,
      "value": 7694892,
      "name": null,
      "model": "Dolphin",
      "ident": null,
      "phoneticname": null,
      "role": "Multi-purpose",
      "raw": "{\"id\":37,\"name\":\"Dolphin\",\"value\":{\"hull\":1086956,\"modules\":6607936,\"cargo\":0,\"total\":7694892,\"unloaned\":50621},\"free\":false,\"station\":{\"id\":3223343616,\"name\":\"Ray Gateway\"},\"starsystem\":{\"id\":670417429889,\"name\":\"Diaguandri\",\"systemaddress\":670417429889}}",
      "starsystem": "Diaguandri",
      "station": "Ray Gateway",
      "health": 0.0,
      "cargohatch": null,
      "bulkheads": null,
      "canopy": null,
      "powerplant": null,
      "thrusters": null,
      "frameshiftdrive": null,
      "lifesupport": null,
      "powerdistributor": null,
      "sensors": null,
      "fueltank": null,
      "datalinkscanner": null,
      "fueltankcapacity": null,
      "fueltanktotalcapacity": null,
      "hardpoints": [],
      "compartments": [],
      "paintjob": null
    },
```
I'll try deleting and refreshing my shipyard data by cycling through my ships.

**Comment by Tkael** [comment]
My active ship appears to have full data and still fails to export though. There may be more than one issue here?
```
https://coriolis.edcd.io/import?data=H4sIAAAAAAAEAO1c627bSJZ%2BlYKARXYBm2Bdycq%2FJE466XG6s1a2G4vFwihLJYkTitTwYsfb6H8zT7cvtecURYmUSImWnJ1pTIwkcMhisepUne9851L8bRRNRy%2FVxSgxSzt6OXqVr0YXo3sTl%2FC%2F30aLMo7hNuWSKv9itEynZWzz0UtOA18xyS9GE5PN09FLuFmkhYHGPAgFFRRulUmcmsRC%2F1QEXPq%2FX4xmmYV%2BZybO7cUoX0Srn6rXfl5Ycm3NbFRd%2FXCF1%2F50SfUrvFKYIkoTHA8OljPGfMl8vR31x8jm5N4kZGozcpMu7IucvIlNtBz97h7P8se8sMtND9QPpK%2B5YJqxbScmSkwS4QtdazOdZjbPd5pDhyaO7uGBIithEgtr4mKxlRX13Y%2Bbh42nexfKVf1klBR2nkXF4%2BilFjwILkYrGEHxkGZfqisK3jVJJ19WUfE6s2ayQFGuZZd%2BfZzb5AZGGSVRMh%2B9FLJ6y2aJfhuNlyaO35tsukqhX4qXqru1HCgLfaGF1BsZvF8Vtx%2FLuIjemCRJk9sfouWdiW9dTyCYOJ2sF8w1uqxaVTeubD7JolW1UqMbs4qmZBZl9oLk%2BPTlBMR2l1myytI%2F20kRxZY8WLNKEwJ%2F5u49sZ2SZVomxQV5iIoFyaN5YooSHioyM%2FkC8yQmz6O88LZ7lAom%2FZ2NVa%2FJRvQ4pEroqyxKK5njdrTJPEqszVAg9e%2F1jkyn5AVuy9exgd2QvSAfJ%2F9eRgnOtm76AfeS7zNUjcxOopVdP%2Fyrm9jtdTRfFL9a%2FHdUt7jeiNDdJdVt8hGn3WzUFudHt25ks2VIlMNen8CuyEFmTljFAq6tJQrLHM2iiVObC3iK2K%2BThUnmlszSrPHgEsRJTDIleYyjiB8b96ZmaebW247J3lvY3xLE9its0Q%2FJpyydo4LcNt%2FmNt7PZTGLigLW6x1u%2Bc%2BPK3v70eTu3nrZfI9RTRX1OVfc57D5r6GrD%2FkPaTqt16qx2%2FDhi9E0ylexefyl6mIUhJ4f%2Fou7Dis4%2Bt%2B%2ForZ3vfvDVtMaAxDcF76kXGvGafv96320HcC2h71RXErladUYxt%2F6hvEpfbDZVWYeGsOgns%2F9kIeKUhCEPiwG1wGZYg%2F7w%2BBtYfSO4gr0J4vuyiLdHYvvBUIFvi8El0KE4vBgGv30DIlJj%2FMh6%2FMqA63PPtnEgp7XUL8VkArBpjAhQ%2B7LI%2BtU9URWkc0mCIt7Y1JeKIYMCTQ%2FA9i6Ts20NRiwewCYigoZKH5kMOs%2BSIyd7I2EBp6v20NBY7UCZTPxx7ZK%2Fdd%2Fw602nLM%2BOJdMtuHcGYhr0Ons9l301U670Ny1Ia5RF5r%2FBwIC4IpDwjSa5qRIyaQsyGRRJl9yks4IIAFIfgJ2eJalSxIV5F8z%2B5cSDEAO92aAl9njvzVwWyquToPtPVHw75btu2X7B7JsVIFtE5oFkoeSnmLZQu4F51g2YOAAT8ApaYgs%2BXTTRj05yKh0mTbfC7kMGQMLH4aBOmJODtk2qjzBhojjkG0LOdUh2DctABjYubYNhhT6z2DbfKqZDKkS1Gfn2jbYeWcYFPEdRVsoyr6j6N8XRVlImQbfQEjJ5UkoGuwpxJNQlEpfSao050Kc5SCEntBnoKjwAxCCrxElzgBR6elBbPwgiDLhi1ByocDEnA%2BigaeeA0RpIEKmJeyY3Y3ydBClXiDPcRB8wQKqVcDRTzgsoMP%2BwaXwWNDeNb1w%2Flt9%2FXaSZlmaR%2Ff2Nl9YjEclZRzjgx%2FtNCqXx6NB4Iq20P5TCRKsvIc12Fc9tdDeNep3H8YgudherlyrGFs9C7SDl%2Bp%2FC2h%2FnaUp%2BWwy8F460Bz89X8eNBfPheZcBsxXvlBAdthJ0R4F%2BnAGJ1YAWUoGYEvoWZSYS4%2FTM8A8gGFQoTSlwTEAPYjmrD2ME9AcIytCCsUBP3V4xLIcB%2FNLIOlyUADKbbVPNhvbSZrsoCewYeDnYRDoIDiySlU%2FZAUyyque9sakPTYIzKuuzhzJkNcfJuQ7GN0b4vlnwOgjQYzvGP0NMFoBr5M%2BhR99LPrbg9HcU4MUrhujZSiAxWmgu1rxY%2B7wIZAW1JP%2BOSANnJtJIP6gbOeBNFVnU%2B7Ap1JqMJ98L5hzAuVmnh5kRY%2FFLRgYspBKFdJjYfABcYthhr2XcvtKMxCPhr%2FnxeSBJjwpgvI5Sh6PU2rY0i24fm9NAXD75dqUyQTGc%2Fu5zDJb3GJvLcjGhgRbdgH2pzKb25xguvxFThbYFAaREkNwUmlu7gCecniY3MGzXwCzF9FkgTBVLCzgDwZZ7NQjN3WU3iyXZRJh7w38Ztqnp8A3PwzfN2YJ6L3YR25Kd5F7T1oDMPyhgvCN%2FEj9cD%2Be39hpidkLEA6pFhGkimh8QUCfCHSEd%2BzXlU3AQLqEBz4w3VqAb5kqBeefgeMdUqXCE1OlehBd7AsoA2vnfgB2VXBxXkCZnhEK0YH0OYgAFD48J1nK2ubhaXren3n7Q%2Bt5IL%2Fr%2Bd9bz4XWQH1UCE6yPK0kQnr%2BOXqufKmYFhxcdX2OmnNPi4Gxq30F683n%2FpEVjLuSuFMUbFc8vYmaP7J4vvOMfwT8oUwGLGCg%2F8ER69pLM4JB5TV9GRdGRYgvDwN1ZsYlOIdmSD8IdQCUR2lxRt5aeJo9hWZUnlJv1McXzTLdtYd2%2B0Nmppa29Lm5N1%2FFcfrYGfApTDIFTMGEa4EJV6zvmZsoyWEXxjEpQD6usscUhZl8aejqSfEcelhRxzYGV5P8aE1XAnVPWddzB8W7f7wq3R7YVVB3j%2BBNspZrr05%2BxkCNqdzUOxdqscnCJBO7tEmBwa0pSGIB4oSVdgEajNlESR2X2caAMhslcK968Nn09MrOLAym2jE2e%2B%2FE7RLsqziqpFmjqMeFUEy43Ck7pkHvS1jmuzTNi444ARfABoao8p9gpYpocmMx8odCa9fLccyfciAVvjgSvFh3hJVkdU%2F7mk1520Xv1ey3X1exS4T1DIwzJRhjUgV7gtod2Karw0PjzFNiyNB2cBfGosIQNDz0JTsNdy%2B58sJBYnHxj57VAuATgYAfpf0woEdGUkdSDslEekw9BQAdmH6KTVJ0g6ASrlQ42ViACsBX%2BMTtOPofy27fxCAhOdqH6KrbDiB8A%2B8vl1i4WNoYCxtXrj1iIJKetZXOmzUlEiu8vgEKvreZAb7iDiHshrT1LgZuhXX7GpXYTjtQ8Od7m00WBijclLTlcAgLm%2FAHWx9ks9wNd2OMumgE05zgsvQ%2BmtoGNFainAO0V0HEZ8NEN5c3ZmUmbRIByhQAhwH8o0HAjkUDK4lM6m729i8PPBmcEc9WyudUcwacZjfB9rR4NvfEoHg2MtG3M5BeBBZjRy5Sw48fMsWOldM4Pmu33XTije8%2FxcHDwzVv3Y7Oe1U7FC3Vrpo7tZaVWrNRG4CyEiuv8i6l%2FinFnXmZw8q6kjLMayHDqY72NHVZ%2BSr8Fhkq2M8zkDEwhU8m7kpSMbar0esZfy6TTl1%2BEwM7IlcZWiJoU8XSe9R4S0udpjrWsq7HRq1GugNem4EnYKVAUZHR3NkCxLnRaoCAaeySetDBymYzFCmgQiO51cCJZ9PsSgg%2Fr4pP21e2NjIToUJbSXmgjpX7QDcRzmW5ZUv7wUDhhYOYTreSBxJcV%2B0HKgTedU7QBMZBByl5JSFU0htTtA24kkoypiSXgT5Gaw6nQoD%2F8UGpvM16oaD3XErNAhoqHYJyc3kscrxZrW6SE7TzRE88Z8M4cBqgDxyQ5owyukvGvXBoXZaDvncZ9DpeRLPCqW4f%2FNHGUUSEv%2FcwlWyKTzQhsM1s3o2vusDvyt6DUoOKGufKpQ85yUvobZKVUe6y9aChTq0X%2BJIKJP9cLlc5YsCDtYCThcnWYNlkPhIkqOVJgawjcPnOxhEaYfLOZLl1erobsvF38RKmf3udJvMbTKR3AOaHDQ%2BBlmSvVVto2BGseuaS8pUwECOd%2FFoZ%2FXYqvxG0mQAJQ4e5kys13MdvFcChnuBA4AOug1AfSxX3OBLINIIhStYHhqGkkgcsDPZYxpPBcFA1UY%2ByCxpSIRnXXPJzlB2GMQhzYIN1QyD1pGBUoldF2SBzFdV1IB3%2BlPDYoIMQH83Xd%2BDNgAn9EXbyznlDoMZaC%2BHLo9ly6KbyirDICnWiw054dNCIQEAdFgtr0GCjaPB%2Fqa%2BO1eUdtlgKVv0pzuZ1NLPjcrVKs15vk8o2JW084kBZdPFSbETqjruOPth5GYMYcmBYd1FRxc%2FR0TTFMs1XMEdbUa7KmwKWtbTgvwERR1%2FbZvdplDm%2BtoritHiRkxu7xMj7PrcFvyM4MelwEKuvoRn5EX7P0y5eu1d81RTb8Kj6jhz%2F%2F%2BLpz1dQBUYr9IH4wL%2B7m3tgQZUeWK7TU%2FQKtFQrLUPO%2Fd2E4tOqXjXwp6eQngqWt%2BVIvRqmO%2BI5jeeaatYV1Wm%2BoosJ1be3vp9Tnbc%2F%2FXBBxv85dor269tPdQwgzZpsRwgOvvs3iPPguaGrBxvHnTwn7Iz0NIXyHhTkHbpza%2Fd8z1N0ER%2FytnLP6shPW1aH4j93MH2YTFKQaAlyAXcxvbcZRsRWrYhJ5Vvu0p2HBR7equDL%2BY9k5o5IbTqpAlJAtYrnOz9UFXjmN7bqfCf0AW4RqGEYKh4e0YJ1PwAT6472LZ4cGBRaxzu6h4QFPZIGPniPx9yidT%2BHhqQHWuFxxejPltK6n%2BeQ0lrgHbE83wvDQAs8Rxvslj31rlt%2FMO%2BSAi8cVLq%2FFvi5Q6rX7TmGtBb4uUOq1%2B1pQzoM9TdmanrxnXHdwvcxmGEA2f6o3rrBwYxlXkZFE2DuTB5NyNSu05gXBGhTUmwGWsWqcZuiTN3c76I4KqJWUF8F8ptg%2FVPJUiWAtaAO0yU829UH5K17z300E3P0mKLXoTztME9I9yptn8JruK99X7ivQO0N4Em8BvjVsJhbtRyf3SYaT0zyCk9LtF1fgHIQTEBVEBxD9Kofgh2RqqcO11N74kl6iA7fZ5N86VNFjuegG6pYt2%2FqIm%2BHl9D1c112amOa4fmbSZoUBj%2Fv4YiV8xZL9GDvHuuaoYozuCRdQ990EKB3dYq%2B4dl1cH186oauOies4AdzLjsTHk%2FSdFU91hlQw%2BG7Nl1Tfhc%2FkgnmwzDZhW5FXiZVYAjWEWgSBuadAHLswX0jJQWONync1aZjxvGTNuL0gjA3fVatXO96i3ZA8Q1%2Bqe3GTFoL3i4ccU0ItjmEvy5Aka%2BXH0%2F%2BuJWHRcdzLQbo5RKI3ZS4L8NhsDHJZzbryLz4YYBHq87ZAdzNpbtgEJZf6x0RVKdjUwTAdNYWCO2yRpsHSJ0xL8gRIVUKeo6MqsAtYkOVW6882NnMOiI%2BI5szvtXjLZGq4MS8dC1RcUiimFht2%2FPX5Xz%2B%2BNo8NrPvbRFivtmC9X0kv9hFNAHP4L1J5qbTXXtVOxNTi4fLrMsqL1IU2zxLy2R6WZXn3Fc9tXLywYkVhGIzdXlg6khl1A6Vcd%2Fz%2B6HKba89Vd5JaVxDsmnZCS1pBrTMODSNkhK8JIz21IlzYC11lRasOl6cO3TFbo0TjNsj92BzWjiDB4fYt%2BA0NiJvFrZ0Gchd93UvrbkrqE2Us8NzrV3WC3KdPqz91ur5vN9n7TqLF2MwvpH6rII%2BnalL3GT1Kbu1sdokTtcrAFBfZFWCoBL78wXxD9VP%2BZ7UQEspnv%2Fg%2FFhIf0gBlfAHHok9VCiEhzgk8C9GQ6aOVSwNqRO6pHrggb3DZV2%2BJ3SAH%2BqUQE7p7gfaTqvrkn7bH%2BqVWHctaSBDjaeIFdPsnBMrO8nhfg%2B%2FVrb%2BjCwPmFAy8DWXxyLudUYWv23an5ZVfMjS7Y1EgbVSUvJQSOGfFB7l2uOD4h494VE8xMg4Cxnmi84JjwZ74dEjqzMuMsDN6sOx21yIEDyQWiohj0Zr65XJ6446qo%2FFoFrsN8BRI%2BQ4fUWBWgKXklQyENWRDVN5nbvi8Z%2FoyThrrCpK0UPuYeu2yf24sHFsstfp9PEqAv59b7NH9K8Avm9fTe%2BdUWlZ5StySdYNOnlcdavyZaZlhjbYImBsC9nqdeOUn%2FiNqS3tCg7OFubbTkRdAaOKYjsdl9nMTGw90b2THev7hyZaCwd2kpMguQMRggczdPp4aOC0I%2F7HguSRSQwBYlSUie2InAR9kZO2TA4VCOC9qi6gIaEekvFhiQGndaapqhIALu68wLWswONdVz6itPDODplIDBD3h%2Fqme6yqr5rH%2B4Fwfmq1%2BHh866aEFeKt2nAKOxXsoh%2BI46lWF5qoJPPxQO0UpXQgAnfn6Xm1PyjVbPfA2dM%2Bfuvv1SMOrL2WSknmU%2B4rGZ70lTH8%2Fq%2BST8qN1R7RqxVsKTNZjDGe2edxwZq1M2Tu6faj3f5W3YY0Gu0me2xdFTgldT1lq8AlvyC5UyuyAicWnVncyOYebkUT9xlYVyADnotLYcP%2FZ%2BC5VM4qMKsYVWIdM4HBfAXeD%2FQcS4XdKFulRaeCCEjUueTvTTFZtKXY%2BfGn5jmWxiu8bXTM%2BRMmc72Cb3uVgs%2F2O74ndse74FL1ffUdf3lc3rlL%2BPu6p8LmxR26yG1UvvkF8SYzd07p78oI3ZuXFNuYaVqC2rqv1hdrxHbX6mfX12E8v%2F8fIG1hyL1fAAA%3D&bn=The%20Leaf
```

**Comment by Tkael** [comment]
After refreshing data for the dolphin with a ship swap:
```
https://coriolis.edcd.io/import?data=H4sIAAAAAAAEAFWPzY7CIBSFX2Vy1ywo1EthPYn7eYMboZWEguFnTGP67qKT0bg9Od%2F5uYG3YKRiEGl1YOA7hcvZR2DwS6F15QbnFgKYgU%2BoD8hgTbYFV8AgcqVlV06UlwSGM6ipUvcq1OOkBYMWQ6LoesWBoxh2BnN2PXSmUByDUqn6FB8lzxlCSDlKHPA154e2ryNVd6UN9ieQy1aqW%2F8ZVHwc1Cj0NOn3CU9Lo2iz7z%2F%2B%2FGRtdqV8Avt%2BB73D%2B%2F4AAQAA&bn=Multi-purpose%20Dolphin
```

**Comment by strideynet** [comment]
Yes. There is an outstanding issue with imports.

**Comment by Tkael** [comment]
Conclusion: this is mostly an EDDI bug. Incomplete jsons were being taken from the shipyard rather than only using the full json provided when the ship is active.

**Comment by Tkael** [comment]
Bugfix submitted

**Comment by richardbuckle** [comment]
All my ships are now exporting to Coriolis, however my engineer mods are not appearing

**Comment by richardbuckle** [comment]
Re-test when Coriolis is updated to recognise 2.4 eng mods.

**Comment by Tkael** [comment]
Given that Frontier has not yet fully reincorporated engineering mods, this may take a little time.

**Comment by SwissSkynet** [comment]
I Can Confirm that "Export to Coriolis" works now (tested with all my Ships) but ALL exports was **without** engineering mods. EDMC has the same Problem with Coriolis. E:D Shipyard works.

Here is an Export Example from EDMC to E:D Shipyard:

http://www.edshipyard.com/#/L=A0zC,ElxHp62k126pXIAuSVComQIwVJMyjjElxHp54hngAqaTEhcKIyC5Mzo1HgBHu70exP4kAFCy0CGyHdL400Wkkwcri6Hf5Hu62mi2CyJ-GyddL400Wkl2csmNHf5Hu70jFu4oYSCxRoGwgoL400Wkl2csmNFBSHF40oFNAplrSs4SWp6gFBSHF30mtJEmp2SrQ7,CzYGV22ycd6vEBDBwHp715004qYa8uj4Cv46IfS-MfS-QfS-DBwHq60Khc4Qqw8nIdIuGiKfJAOfWGCzYGV22yh76w8YDBwHr56rvc8watIqyRMqyRQqyRDBwGr56pAF8wfwIr0KMqaTQqaTDBwHp515mP4qfq8tXeCvffIRNtDBwHp715Ow4qJD8vIMCv6rIikIMikIQikI,9p3Hp44vTJAkghEkLWIkLWABkHq36umx8v5eCtFNARqGp60NhX6oxx8omzEnCFGvN9K_0IAfQGp50wQe6tC08qmDGxfGOjJ_AtyGD24_6Z8vlDBBoGo78kw2Ikk5KwOUQpWRSwOYYpWRawOYBRuGp32_Bi6ytRIuNZBcg1,16yHp50w9l4yVfAq_fEqg4Iqg425S1,7WCGr44w9qas9wgxyGkjHX7lUHA4ClR9InfHMflxOdBw0Bk152C11tO15WMHV22yer6uzp1LU22UI16DWHe38y1ZIvFfL0IL0nE2

You can see **ALL** engineering mods got exported to E:D Shipyard

Just to clarified that engineering mods export works. Hope its Helps.

**Comment by Tkael** [comment]
it's a known issue... Coriolis has been chasing bugs and hasn't yet been able to incorporate engineering mods to the same extent as EDShipyard. I'm looking into adding support for EDShipyard with EDDI.

**Comment by Tkael** [comment]
Pull request sent for new feature 'Export to EDShipyard'. :-)
