### ISSUE TITLE
Version 3.4.2 installer triggers Anti-Virus quarantine.

### ISSUE THREAD

**Issue by JEricEaton** [EDCD/EDDI#1460]
## EDDI version in which issue is found
3.4.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Start with version 3.4.1 installed
2. Launch EDDI without VoiceAttack
3. Open the "EDDI" tab
4. Click the link for "Upgrade EDDI" at the bottom of the screen. On my screen this says version 3.4.2 is available.

## Expected
Version 3.4.2 is installed

## Observed
Anti-virus software detected Heur.AdvML.BFull and quarantined the EDDI-update.exe file.

## Investigation
From Norton Anti-Virus (specifically Norton Internet Security version 22.18.0.213):
Filename: EDDI-update.exe
Threat name: Heur.AdvML.BFull Path: C:\Users\eeato\AppData\Local\Temp\EDDI-update.exe

____________________________

____________________________

On computers as of 
8/30/2019 at 5:00:54 PM

Last Used 
8/30/2019 at 5:02:55 PM

Startup Item 
No

Launched 
No

Threat type: Heuristic Virus. Detection of a threat based on malware heuristics.

____________________________

EDDI-update.exe Threat name: Heur.AdvML.B
Locate

Few Users
Fewer than 100 users in the Norton Community have used this file.

New
This file was released 9 days ago.

High
This file risk is high.

____________________________

Source: External Media

Source File:
EDDI-update.exe

____________________________

File Actions

File: C:\Users\eeato\AppData\Local\Temp\ EDDI-update.exe Removed
____________________________

File Thumbprint - SHA:
ce5aa61be8bd3d9224e4afe261f213754eb6e08766a8f265f52e6d0e09c4903c
File Thumbprint - MD5:
ea50a7c9d88ec058d6409bd07095e433

More information from Norton:
https://www.symantec.com/security_response/sape/

**Comment by Tkael** [comment]
Hmm. As you can see, this is a threat detected through Norton Heuristics and there's not too much we can do directly if your local antivirus detects it as malware. I don't know what it's detecting and flagging in the file as being a malware risk.

The project is completely open source and the code is freely available for review and inspection. I've looked at almost every bit of the code and I'm not aware of anything malicious.

Uploading the file to VirusTotal.com returns a clean bill of health: https://www.virustotal.com/gui/url/c473a1d02584c5eabb627069582f7ee14fd83e1617f3cea6c8282febb477d318/detection

You can report a suspected false positive via https://submit.symantec.com/false_positive/. If you were to report it there, we might gain some additional insight or Norton may be able to refine their algorithm.

I'm going to close this issue as unactionable, but I'll get a notification if you respond so feel free to do so. o7

**Comment by JEricEaton** [comment]
Tkael - thank you for looking into this and for a fast response.

I have submitted it to Norton as a false positive using the form you suggested.

I manually downloaded EDDI-3.4.2.exe and submitted it to VirusTotal via upload for a fresh scan, these were the results: https://www.virustotal.com/gui/file/ce5aa61be8bd3d9224e4afe261f213754eb6e08766a8f265f52e6d0e09c4903c/detection

It shows the SecureAge APEX engine and Symmantec both flagging the file I downloaded.

The direct link to GitHub via VirusTotal that you shared - I asked for VirusTotal to do a fresh scan, and it again came back passing all tests.

This remains mysterious to me, just adding these notes in case there are future troubles for others out there.

I told my Norton program to remove EDDI-upgrade from quarantine and to accept the file as safe and the upgrade to 3.4.2 worked just fine. When I manually scan the EDDI-upgrade.exe file with Norton, it gives it a clean bill of health and file insight manually also gives it a clean bill of health.

The only mystery that remains to me is the manually uploaded EDDI-3.4.2.exe file to VirusTotal that fails the scan.

No reason to open the ticket or take further action, I'm sharing this information as a courtesy to the community in case it is needed for later reference.

**Comment by Tkael** [comment]
Very odd. I just manually uploaded the installer myself and got the same result. I can't explain it - I don't know how Symantec's algorithm works. I do know that beta version 3.4.3-b2 released just a couple of days ago returns a clean bill of health.
https://www.virustotal.com/gui/url/c473a1d02584c5eabb627069582f7ee14fd83e1617f3cea6c8282febb477d318/detection

In any case, thanks for making us aware.

**Comment by Tkael** [comment]
For anyone interested in reviewing the complete change history between versions 3.4.1 and 3.4.3, the change history is available [here.](https://github.com/EDCD/EDDI/compare/Release/3.4.1...Release/3.4.3)
