### ISSUE TITLE
Enhancement Suggestion: Customisable table of 'last minute' string substitutions

### ISSUE THREAD

**Issue by Loophole62ndFF** [EDCD/EDDI#1463]
## EDDI version in which issue is found
3.4.3

The Windows text-to-speech function can struggle with some pronunciations.  For example, words like "pristine" and "gimbaled" are generally mangled in my experience.

This can be corrected by replacing the relevant word with a phonetic pronunciation in the script, but that gets very messy very quickly - particularly if the words are generated from environment variables.

It would be nice if there was a table of 'translations' - basically just string-replacements that are performed as a final step before the text is passed to the text-to-speech engine.  That would allow people to build up a table of common 'corrections', and have them apply universally.  You could even ship with a default list (with words like 'pristine' and 'gimbaled').

Over all it could enhance the EDDI experience and improve speech quality.

The table would be simply a list of string substitutions to perform; using the examples above, I might set my table with the following entries:

**FROM**:  `-------->` **TO**:
> pristine `-------->` `<phoneme alphabet="ipa" ph="ˈpɹɪstiːn">pristine</phoneme>`
> gimbaled `-------->` `<phoneme alphabet="ipa" ph="ɡɪmbəld">gimbaled</phoneme>`

The substitution algorithm would look for occurrences of the "from" word or phrase, preceded and followed by a word-boundary, and replace that with the corresponding "to" text prior to text-to-speech processing.

**Comment by Tkael** [comment]
We've actually been looking at doing something similar for a long time (ref. #98, #140).
