### ISSUE TITLE
Enhancement Suggestion: Highlight customised messages in the Speech Responder list

### ISSUE THREAD

**Issue by Loophole62ndFF** [EDCD/EDDI#1464]
## EDDI version in which issue is found
3.4.3

If you have a number of customisations to your EDDI scripts, then when a new version is released it can be a chore to go through and identify where improvements have been made to the standard scripts, and then either incorporate those into your customised scripts, or revert the script to the improved default.

While the editor has a handy 'compare' function, it would be nice if the list on the Speech Responder tab also flagged those scripts that differ from the default - perhaps by displaying the script name in bold, or with an icon or simple text column.

**Comment by Tkael** [comment]
PR submitted to make non-default scripts **bold**.

**Comment by Hoodathunk** [comment]
If the `Delete` button is active, then the script has been modified, yes?

**Comment by Tkael** [comment]
no... you can modify but cannot delete any script which is tied to an event.

**Comment by Darkcyde13** [comment]
+1 for this.  I'd love to be able to tell which scripts I've made changes to, for pretty much the exact same reasons @Loophole62ndFF has suggested.  Can't wait to see this one in action!  Thanks Tkael, and thanks Loophole for the suggestion! :)

**Comment by Hoodathunk** [comment]
@Tkael check again. it does it for me. even when you modify a default script tied to an event.

**Comment by Darkcyde13** [comment]
@Hoodathunk I see what you mean.  I just made a fresh copy of the EDDI default, and all 'Delete' buttons are greyed out, because none of them had been altered.  I made a change to the Body Scanned event script, and the button highlighted.  I was then able to completely delete the event from the personality.

I then quit and reloaded EDDI, and the default Body Scanned script was automatically added back into the default personality copy again.  So I can understand your point of view on this subject, with the Delete button only being available if the default script has been altered.

To be honest, I never realised this was the case. :/

**Comment by Hoodathunk** [comment]
Thanks for verifying, @Darkcyde13 ... keep me honest.

This may not be the 'metaphor' that was intended, but it does tell you which scripts have been modified.

IMO, when a default script is modified, the button should say `Restore`, not `Delete`.

**Comment by Tkael** [comment]
@Hoodathunk I see your point, but you're pointing out something that I'd actually classify as a bug.
- If I modify the `AFMU repairs` script, the delete button becomes available. 
- If I press it, the script is deleted from my custom personality.
- If I then restart EDDI, the script is regenerated / restored from the default template.

**Comment by Tkael** [comment]
I'm generally in favor of the suggestion regarding replacing `Delete` with `Reset` in the speech responder UI for scripts ties to events and would be happy to consider a PR to that effect. 
Note that we currently have a confirmation dialog prior to deleting scripts but we don't have a similar confirmation dialog prior to resetting. We should consider adding a similar confirmation dialog for resetting scripts - particularly if they may be reset from the main screen.

**Comment by Hoodathunk** [comment]
I'm still not a fan of 'Bolding'/Highlighting the script name to identify modified default scripts.
