### ISSUE TITLE
Cargo monitor not handling simultaneous events

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1465]
## EDDI version in which issue is found
3.4.3
## VoiceAttack version in which issue is found (as applicable)
1.7.8
## Steps to reproduce
1. Allow cargo bay fill up and the refinery to fill several slots 
2. Launch limpet

## Expected
1. Refinery replaces limpet with cargo and monitor increments cargo total by 1.
2. Monitor reduces limpet count by 1.

## Observed
Monitor Cargo total is increased properly.
Monitor Limpet total is not decreased.

## Investigation
I believe this is occurring because the two events (`MiningRefined` and `LaunchDrone`) occur very close together, almost simultaneously. The Cargo monitor handles the refining event, but ignores the limpet event. When no adjacent refining event is present the limpet inventory is decreased properly.

Sample log entries:
[limpet_count.txt](https://github.com/EDCD/EDDI/files/3575666/limpet_count.txt)

`{ "timestamp":"2019-09-04T16:26:53Z", "event":"MiningRefined", "Type":"$opal_name;", "Type_Localised":"Void Opals" }
{ "timestamp":"2019-09-04T16:26:55Z", "event":"Cargo", "Vessel":"Ship", "Count":40 }
{ "timestamp":"2019-09-04T16:29:45Z", "event":"LaunchDrone", "Type":"Collection" }
{ "timestamp":"2019-09-04T16:29:50Z", "event":"MiningRefined", "Type":"$opal_name;", "Type_Localised":"Void Opals" }
{ "timestamp":"2019-09-04T16:29:53Z", "event":"Cargo", "Vessel":"Ship", "Count":40 }
{ "timestamp":"2019-09-04T16:37:17Z", "event":"LaunchDrone", "Type":"Prospector" }
{ "timestamp":"2019-09-04T16:37:20Z", "event":"MiningRefined", "Type":"$opal_name;", "Type_Localised":"Void Opals" }
{ "timestamp":"2019-09-04T16:37:23Z", "event":"Cargo", "Vessel":"Ship", "Count":40 }`

**Comment by Tkael** [comment]
Leave it to FDev to add cargo above maximum and then subtract rather than doing things in a more sensible order. @Hoodathunk will get it straightened out.

**Comment by Tkael** [comment]
I think FDev immediately reallocates resources for a limpet launch but the actual event is delayed by a couple of seconds to correspond with the limpet actually leaving the ship.

**Comment by Hoodathunk** [comment]
Looks like FDEV stopped generating a `Cargo` event for launched limpets, but I will confirm this.

**Comment by rodan123** [comment]
@tkael @hoodathunk Thanks for looking at this.

The issue also occurs if I abandon limpets, while the cargo bay is filled by the refinery. Ejecting limpets 3 at a time, rather than firing them. 
Before the cargo bay is filled the limpet count seems to be tracked properly by the cargo monitor.

It is after the cargo bay is filled and limpets are immediately replaced by refined cargo that the problem starts occurring. 

Journal entries showing events that caused the miscount on this occasion;
[limpet_abandon.txt](https://github.com/EDCD/EDDI/files/3576559/limpet_abandon.txt)
 
This is the cargomonitor.json file from EDDI. After the above events, it shows 26 opals and 20 limpets in the hold, 46 tons. The ship only has a max cargo capacity of 40 tons.  

[cargomonitor.txt](https://github.com/EDCD/EDDI/files/3576562/cargomonitor.txt)

I should explain that I use the 3A refinery as 10 item storage area, so I can keep more limpets in cargo. Letting the refinery almost fill up before abandoning or using limpets.  Effectively turning my 40 tons of mining capacity into 50 tons.  So I am collecting material in the refinery before releasing it to cargo. Usually material sits in the refinery until I fire a prospector or collector limpet. Other times I have to dump limpets to free up refinery space for collected material.

**Comment by Hoodathunk** [comment]
Ok, thanks for the clarification. On first blush, this sounds like an FDEV bug. Need to wrap my head around the mechanism for this behavior. If it's not predictable, then we can't mitigate it.

**Comment by rodan123** [comment]
Oh. OK. I browsed through the journal entries and code. I think I see what you are saying. EDDI doesn't track limpet usage and relies on FDEV to provide a "Cargo" journal event that follows the launch or eject event like these;
`{ "timestamp":"2019-09-05T03:02:42Z", "event":"LaunchDrone", "Type":"Prospector" }`
`{ "timestamp":"2019-09-05T03:02:47Z", "event":"Cargo", "Vessel":"Ship", "Count":37 }`

`{ "timestamp":"2019-09-01T18:26:11Z", "event":"EjectCargo", "Type":"drones", "Type_Localised":"Limpet", "Count":3, "Abandoned":true }`
`{ "timestamp":"2019-09-01T18:26:15Z", "event":"Cargo", "Vessel":"Ship", "Count":29 }`

The problem is that I am seeing is caused by the `Cargo` event being missing after the drone event for some reason from FDEV;

`{ "timestamp":"2019-09-04T22:00:36Z", "event":"LaunchDrone", "Type":"Prospector" }`
**--->** There should be an `… "event":"Cargo", "Vessel":"Ship", "Count":39 }` entry here, but it's missing
`{ "timestamp":"2019-09-04T22:00:39Z", "event":"MiningRefined", "Type":"$opal_name;", "Type_Localised":"Void Opals" }`
`{ "timestamp":"2019-09-04T22:00:42Z", "event":"Cargo", "Vessel":"Ship", "Count":40 }`

**Comment by Hoodathunk** [comment]
Thanks for the additional info. So, we're only getting one `Cargo` event at the end of a string related events.

Question is, does the `Cargo.json` file properly reflect both the limpet & material count following the ejection and subsequent `MiningRefined` events?

**Comment by rodan123** [comment]
Went mining again today. Saved copies of EDDI's cargomonitor.json and FDEV's cargo.json during the session. It seems that FDEV's json always contains the correct cargo totals.

Here are relevant files from the same point in time;
Journal events:
[Journal.txt](https://github.com/EDCD/EDDI/files/3581245/Journal.txt)
FDEV cargo.json
[Cargo.json.txt](https://github.com/EDCD/EDDI/files/3581203/Cargo.json.txt)
EDDI cargomonitor.json
[cargomonitor.json.txt](https://github.com/EDCD/EDDI/files/3581205/cargomonitor.json.txt)

I have more json saves from other points in the session, if you need them.
In the end, the FDEV _cargo.json_ reported correctly 35 opals and 5 limpets in the 40T hold.
EDDI _cargomonitor.json_ reported 35 opals and 38 limpets in the hold.

I am beginning to think that the single "Cargo" event after multiple related events is by design. The same single event happens when I sell the opals and the refinery dumps the extras into the hold.
[market sell.txt](https://github.com/EDCD/EDDI/files/3581241/market.sell.txt)

**Comment by Hoodathunk** [comment]
Excellent. This is what I suspected, and now explains the purpose of the '3-sec delay' on `Cargo` events.

On an inventory 'update' using the `Cargo.json` file, I assumed (based on anecdotal observation) that there was a `Cargo` event triggered for each cargo related event and, after finding an 'changed' commodity, it would exit out of the update.

This full cargo bay with a refinery processing ore is an interesting edge case... you don't know what you don't know and FDEV ain't telling.

Good catch. Literally, removing one line of code will resolve the problem.

**Comment by rodan123** [comment]
Glad it was an simple fix.
Incorporated the change into my EDDI build and tested.
Everything is working as expected. 

Thanks.

**Comment by Tkael** [comment]
Merged. :-)
