### ISSUE TITLE
Wiki link for Responders doesn't work

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1466]
## Steps to reproduce
1. Go to the Wiki main page
2. Click on Responders

## Expected
Get to the page detailing the responders

## Observed
Instead of getting to the proper page, an error is thrown: `You do not have permission to update this wiki.`

**Comment by Tkael** [comment]
Ahh. That'd be because the page was never fully created. Should be fixed now, though we don't have detailed writeups for each of the responders to link to at this time.
