### ISSUE TITLE
Material Monitor only shows lines for items you have

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1467]
## EDDI version in which issue is found
3.4.3

## Steps to reproduce
1. Open the Material Monitor tab
2. Tab states "Below is a list of **all known materials**" but in fact only shows materials you posses.

## Expected
See all known materials in the game

## Observed
Only see materials I have

Maybe this is desired or expected behaviour? But it seems wrong to me, as if the materials I do *not* have aren't listed, then I can't set desired quantities.

**Comment by Tkael** [comment]
Are you sure about this? Can you give some examples of specific materials that are missing?

The Material Monitor is designed to list all materials in our list of known materials, not just the ones you currently possess. I currently have a half dozen materials that exist in the Material Monitor even though my inventory quantity is zero.

**Comment by jwvanderbeck** [comment]
I'm sure unless I amazingly happen to have at least one of everything since nothing in my list has a current quantity of 0.  I'm new to the engineering game so maybe I'm wrong.  I'll post a screenshot in a minute or two.

**Comment by jwvanderbeck** [comment]
sigh.  Ok appears to be a "first run" bug.  I just started it up again to get you that screenshot and NOW I see everything.

**Comment by Tkael** [comment]
Ok. Good to know that it fixed itself. If you provide the sequence of steps you followed for your first run then I can try to replicate it.

**Comment by jwvanderbeck** [comment]
I think it was something like:

1. Install
2. Link to Frontier account
3. Link to EDSM and start import process
4. Start clicking through the tabs figuring things out

**Comment by Tkael** [comment]
Finding: When the Material Monitor first starts, we fail to fill known materials on our first load because the list `Material.AllOfThem` hasn't yet been populated and is an empty list - the static constructor hasn't run yet. I've asked @richardbuckle to review since he's been quite involved in that area of the code.

**Comment by Tkael** [comment]
Alright, should be fixed with this PR.
