### ISSUE TITLE
Feature Request: Some way to set context for script testing

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1472]
## EDDI version in which issue is found
3.4.3

## Investigation
I have started digging into customizing my own EDDI scripts for the Speech Responder and while I see it having a LOT of potential, it is very hard to make changes and test things outside of game or even on demand as everything relies on context being set by actions in the game journal.

I'm not sure what the best way to achieve it would be but it would be great if there were some way to pass a *testing context* to various events so that we can see how the scripts respond.

One way to do this would be exposing a list of journal entries and allowing you to select one for context but that would be a bit limiting.  Another option, but would require more work, would be to present a contextual panel for each event that lists the variables it uses and lets you manually set them for testing.

**Comment by Hoodathunk** [comment]
There are journal events 'samples' built into the each event class for most of the 'user facing' events... that functionality is there.

For the non journal event related scripts, a brute force method of 'setting context' at the beginning of the script is required.

**Comment by jwvanderbeck** [comment]
> There are journal events 'samples' built into the each event class for most of the 'user facing' events... that functionality is there.

Really? I've been trying to tweak a lot of the exploration related events like scanning and what not and none of them work in "Test" as they have no body data.

**Comment by Hoodathunk** [comment]
Which event scripts are you working on?

**Comment by jwvanderbeck** [comment]
The various body report events mostly.

**Comment by Hoodathunk** [comment]
Okay. 'Body Reports' are not journal events. A good short cut to understanding is, if the script has an assignable priority, it's related to an FDEV journal event.

If you want to set a body 'context', you can use something like `{set reportbody to BodyDetails(bodyname, systemname)}` (you supply the body & system names) in an appropirate place.

**Comment by jwvanderbeck** [comment]
Ahh so that data is pulled from one of the third party databases then?

So calling that will fill in all the data for the requested body?

**Comment by Hoodathunk** [comment]
yup & yup.

**Comment by jwvanderbeck** [comment]
Ok thank you I understand now.  One last question, not directly related but I'm curious.  If I popped into a system that is undiscovered and there is no data in whatever data you pull the data from, is there a way to determine this and act upon it in script? And if so, which event would be the best one to do it in?

**Comment by Tkael** [comment]
I'd use a `Discovery scan` for that purpose.
Let's say that you've already invoked the system data for the system:
```
{set reportsystem to SystemDetails("some system")}
```

If {event.bodies} is greater than {reportsystem.bodies} then you may be in a system with undiscovered worlds. o7
