### ISSUE TITLE
Is there a system for making custom responders?

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1474]
I really like the core of what EDDI is and I've been playing around with it now for about a week getting to know it.

While there is a lot to like, I am also finding it a bit hard to really get it to do what I need it to do which is provide a solid setup for both giving and recording exploration information as an explorer in VR.

Is it possible to build my own responder that can essentially piggyback on the event system and monitor sources that EDDI has?  Was there ever any talk about making Monitors/Responders plugins that can be expanded?

Or is my only option at this point to fork EDDI and add in my own functionality directly?

**Comment by Hoodathunk** [comment]
This is not a valid issue. Please take this question up on either our FDEV forum thread or our EDCD discord channel.

Closing.

**Comment by Tkael** [comment]
To provide a quick answer to your question, monitors and responders really have too many dependencies to function well as standalone plugins (in our opinions). Consequently, we haven't documented the interface or encouraged people to make custom responders / monitors. 

We are interested in supporting VR and would be interested in your feedback about new responders or monitors that would help with that. :-)

The Discord channel would probably be best the best channel for continuing this conversation. You can find the #eddi channel on the EDCD Discord [here.](https://discord.gg/zQjjutY)
