### ISSUE TITLE
Feature Request: RouteDetails() for nearest known scoopable star

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1476]
## EDDI version in which issue is found
3.4.3

## Expected
It would be great to be able to query EDDI via the `RouteDetails()` function or another means to determine the nearest known system with a scoopable star.

### Intended Use Case
The desired use here is in a situation where fuel is low and the current and next system do not contain scoopable stars.  In this scenario I want to use EDDI to try and find another star off the plotted route that can be used for refueling.

Ideally this would return the nearest scoopable system name and jump distance, and then further logic could be done with this information to determine if it could be reached or could be reached with boosting and then that data can be used to give commander guidance.

**Comment by Hoodathunk** [comment]
`JumpDetails()` already exists to determine max jump range for current mass, so this is a no-brainer. This functionality could easily be incorporated into the FSD-ralated events.

I like it.

**Comment by jwvanderbeck** [comment]
Would it be reasonable to have an option to return the data based on a boosted jump range?

**Comment by Tkael** [comment]
Well, EDSM has a hard limit of a 200 ly wide cube / 100 ly radius centered on the location you specify so if your boosted range is above 100 ly then 100 ly will still have to be the ceiling for any star systems that you haven't cached yourself.
100 ly in any direction is still a lot of star systems. We'll probably implement this by searching in shells, searching close to your location first and then sequentially further as needed.

**Comment by jwvanderbeck** [comment]
Yeah I think that is a good idea.  Only need to go into boosted range if one isn't found closer, and that can be handled more efficiently internally to EDDI.

**Comment by Tkael** [comment]
Merged.
