### ISSUE TITLE
Humanise doesn't feel very human due to nonstandard use of qualifiers

### ISSUE THREAD

**Issue by jwvanderbeck** [EDCD/EDDI#1482]
## EDDI version in which issue is found
3.4.3

I've been holding off on bringing this up because its kind of hard to put my finger on it, but the "Humanised" numbers often don't feel very Human due to the qualifiers being used in a non-standard way.

I still am having trouble articulating it, but the qualifiers used in normal speech are often contextual to how large or small a number is.  Often the way the Humanised numbers are read to me from EDDI make me feel like EDDI thinks its a big number when it is in fact a tiny number.  

"The estimated value of scans in this system were well over 5 thousand credits".  "Well over" doesn't feel appropriate here because 5,000 is such a small value to begin with.  A person wouldn't say this.  Now if it was "well over a million credits" then it would feel correct.

I know this sounds silly.  This is obviously a super low priority not important thing, but at the same time I felt it was something to bring up in the interest of wanting to make things sound more Human.

If I could put my finger on this better I would offer up a PR so I'm part of the problem right now, not part of the solution.

**Comment by Tkael** [comment]
The algorithm was never intended to describe the number with respect to an arbitrarily large number or in only one context (like credits). 5 thousand credits is small but 5 thousand tons of cargo seems pretty substantial. Likewise, a million credits may seem substantial to you now but some players have accumulated hundreds of billions and won't sweat a couple of million here or there. 

Humanise() needs to be able to handle every kind of number that could be thrown at it and every possible context. We believe that the best way to do this is by using an algorithm which describes the position of the numbers relative to one another.
- 5500: Over 5000
- 5700: Well over 5000
- 5900: Nearly 6000
- 5,500,000: Over 5 million
- 5,700,000: Well over 5 million
- 5,900,000: Nearly 6 million

**Comment by Tkael** [comment]
Closing. If you can find a better way to do this then we'd be happy to look over your PR but in the meantime I don't see a feasible alternative to what we are doing right now.
