### ISSUE TITLE
Make discoverablebodies referenceable after a discovery scan?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1485]
## EDDI version in which issue is found
3.4.3

## Suggestion
Could I possibly request that when a discovery scan is done, the total number of bodies in the system is also stored in the DB? Maybe as a .totalbodies decimal? I would like something that I can reference when I load a game, and something that I can check against when scanning system bodies. I know that can easily be done with a state variable when the honk is done, but I won't be doing that at game load. Although, I could just add it into the honk event script I guess, I just think it would be tidier with a variable, plus in discovered systems, people won't really be doing a disc. scan to get that information.

**Comment by Darkcyde13** [comment]
Thank you Tkael.

**Comment by Tkael** [comment]
Note that as discussed in the other issue, we don't have access to this information either until the discovery scan is completed. Once a discovery scan is completed, however, we can store the value for later reference.
