### ISSUE TITLE
EDDI not updating EDSM with CMDR profile info, ship info and scan info

### ISSUE THREAD

**Issue by Hangfireflip** [EDCD/EDDI#149]
## Steps to reproduce

1. Issue first occured at first boot up of ED 2.4 plus EDDI 2.3.1. Still persisting even after the recent patch to ED 2.4 to correct API server issue.

## Expected

EDSM CMDR profile info, ships and space bodies scans fails to be synced from Frontier API server. 

## Observed and Investigation

Prior to ED 2.4 drop, I was able to have EDDI 2.3.1 transmit CMDR Profile data such as ranks, progression, ship type and name to EDSM profile. Also, I was able to have near real-time transmission of Flight Log info such as jumps and object scans info to EDSM.

Since ED 2.4, this function has failed, even after the update to ED 2.4 to correct the ED API server problem. 

I have noted that the ED Market Connector is working and also note that it was updated to correct pass thru errors on Oct 7 (AUST Eastern Summer Time GMT+11). 

I talked to AuthourNet at EDSM and he suggests that the connection from EDDI to EDDN to EDSM may be broken.

For your information and action.

**Comment by Tkael** [comment]
I just checked my EDSM profile and it looks like I have not been experiencing the same issue (currently running the latest beta build), all info is up to date. I've even been getting the badges. 

Likewise, reports seem to getting passed to EDDN and parsed successfully (https://ross.eddb.io/eddn/log?parsing_result=1&parsing_result_detail=&header_software_name=EDDI&schema=&schema_main_group=40&schema_sub_group=20&system_id=&station_id=&body_id=). 

Have you double checked that the EDSM responder plugin is enabled, that your EDSM API key is correct, and that your EDSM Commander name is correct?

**Comment by clinkingdog** [comment]
FWIW I'm having the same issue and yes, the EDSM responder is enabled (in the EDDI GUI, you mean?) and the API key is right. The commander name is blank by default but that seems to work for picking up EDSM logs so I _think_ the EDSM connection is alright, but I've tried putting in my commander name manually and still no joy.

Even verbose logs seem to show no EDSM activity other than initializing / enabling (and there are no obvious errors there).

**Comment by Tkael** [comment]
Mind sharing those?

**Comment by clinkingdog** [comment]
Not at all - attached. There's a bunch of stuff from today, but two recent journeys with verbose logging on - one starting at line 1200 and the second at 2533. In both cases you can see lines saying EDSM access is enabled and EDSM Responder started (apparently without errors) but no further EDSM activity. IIRC both journeys were just logging in to my ship (floating around a sun), jumping to a nearby system, logging out again.

The only actual error I can see is a null ref on "inventory" event that comes up sometimes - e.g. line 2527. I don't expect an inventory event is relevant to EDSM though - but anyway thought it was worth drawing your attention.

Let me know if there's anything else I can do!

[eddi.log](https://github.com/EDCD/EDDI/files/1367099/eddi.log)

**Comment by clinkingdog** [comment]
Oh - perhaps also worth mentioning: I _am_ getting EDDI verbalisations when I enter hyperspace, with correct system information. So it definitely knows about the jumps.

**Comment by Hangfireflip** [comment]
Hi all,

Also checked that EDSM responder was properly configured. It is. Also checked that the EDDN responder was on (as scans go to EDSM via EDDN). It was also on. 

Checked the ROSS message log (this shows the incoming messages to EDDN and the result of those messages) and filtering for EDDI messages shows that EDDI 2.3.1 incoming messages are failing. EDDI 2.4.0 seem to be ok, but there is clearly some disconnect between EDDI 2.3.1 and EDDN.

**Comment by Tkael** [comment]
@clinkingdog, the errors at the top of the log come from EDDI looking for the files stored in your directory %APPDATA%/EDDI and not finding them. Once those files were generated, the errors appear to have ceased and EDSM should have started working. I can't find any EDSM related errors that occur after the connection is established.

**Comment by Tkael** [comment]
@Hangfireflip Version 2.3.1 does not support the changes for Elite:Dangerous 2.4. Please consider updating to the latest beta, as that does include the alterations needed to support Elite:Dangerous 2.4.

**Comment by clinkingdog** [comment]
> Once those files were generated, the errors appear to have ceased and EDSM should have started working.

Should have, yes, but didn't :) It still doesn't track my activity, despite the lack of recorded errors.

I'll try updating to the beta as you suggest; it sounds like that will fix the problem.

**Comment by clinkingdog** [comment]
Just to confirm for the record that I'm now running the beta (2.4.0-b5) and EDSM sync seems to be working fine now. Thanks!

**Comment by Tkael** [comment]
cool. thanks for closing the loop. o7
