### ISSUE TITLE
Instant crashing of EDDI (Voice attack or EDDI standalone)

### ISSUE THREAD

**Issue by BeBumble** [EDCD/EDDI#1492]
## EDDI version in which issue is found
v3.4.3

## VoiceAttack version in which issue is found (as applicable)
v1.7.8

## Steps to reproduce
Starting either Voice attack or EDDI instant crash, no warnings or error messages

## Expected
Voice Attack or EDDI to run and function normally

## Observed
Window opens then closes (Voice Attack or EDDI)
[eddi.log](https://github.com/EDCD/EDDI/files/3612980/eddi.log)

Appears to be working right now so just uploading incase the logs give any insight into what happened at the time.

## Investigation
uploaded eddi.log files
[eddi4.log](https://github.com/EDCD/EDDI/files/3612983/eddi4.log)

**Comment by Tkael** [comment]
Is `eddi4.log` the one showing the non-working state?
From your comments in https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8001155, it sounds like it fixed itself without any particular on your part. Is that correct?

**Comment by BeBumble** [comment]
both logs are from when it was crashing yesterday, eddi.log is from the first time it  crashed and the eddi4.log is from it still crashing after i tried moving the settings folder and letting EDDI rebuild the settings folder as suggested in the help files

**Comment by Tkael** [comment]
Ok, then I'm afraid that the logs aren't showing whatever happened. I'm going to close this as we don't really have any leads to go on at this point. Glad you got it working again in any case.
