### ISSUE TITLE
[Suggestion] Export to E:D Shipyard

### ISSUE THREAD

**Issue by SwissSkynet** [EDCD/EDDI#152]
I would be nice to have a second Button beside "Export to Coriolis" with "Export to E:D Shipyard"

Why? First the FULL Export to E:D Shipyard works since 2.4 API is Online WITH Engineer Data. Coriolis has Blackscreens, dont import or just import non Engineerd Data. So we need an "Backup" Option to E:D Shipyard.

I tested the Export also with EDMC and E:D Shipyard imported all data Perfect while Coriolis just dont work (or sometime its works but without a single Engineer Data).

Would be nice to have that Second Export Option. Thank you and Fly Save o7

**Comment by Tkael** [comment]
The majority of the black screen issues should be resolved in the next release (with a few rare exceptions that Coriolis is investigating. But we can take this request under advisement. Thanks!

**Comment by Tkael** [comment]
Pull request sent for new feature 'Export to EDShipyard'. :-)
