### ISSUE TITLE
"cant connect to my update server"

### ISSUE THREAD

**Issue by kokrull** [EDCD/EDDI#1520]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
EDDI v 3.4.3

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
activating EDDI by double click on icon on the desktop

## Expected
[Describe what you expected to happen]
EDDI to start with no anomalies

## Observed
[Describe what happened instead]
EDDI starts and the voice says "cant connect to my update server"
## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

it happens every time i start EDDI. and started about the time of the elite update on the 18th sept

cheers

**Comment by Tkael** [comment]
You are the only one to have reported this problem. I'm afraid this sounds like a local issue with your internet connection.

**Comment by kokrull** [comment]
you mean the 1st :) lol, no worries but nothing changed my end

**Comment by Tkael** [comment]
Closing as resolved. o7
