### ISSUE TITLE
Small(?) 'Auto-scan' quality of life request.

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1525]
Having been out of the bubble exploring since the beginning of the year (for DW2, and I'm still out beyond Sag A*), I thought I'd finally ask something that's been on my mind all this time.

I was just wondering if it would be possible to defer all auto-scan reports of bodies and stars until after the FSSDiscoveryScan (honk) has been reported?

I know EDDI processes the events in chronological order as they appear in the game Journal, so I understand why this happens the way it does.  It just seems counter-intuitive to have the body/star reports come before the report on the system itself.

Ideally, I think it would be nice to have them like this:-  System -> Stars -> Bodies.  However, I'll understand if it's not really possible to do.

**Comment by Tkael** [comment]
While it is possible to do this, this would lead to situations where the player may have moved far away from those autoscanned bodies (separating those scans even more from the context in which they were acquired). I'm not sure we want to further separate autoscans from that context.

**Comment by Darkcyde13** [comment]
I must admit, I normally start my honk as soon as I drop into a system, even before comming to a stop at the main star, so maybe I am being a bit over eager with the scan.  When I do this, I usually get the honk report within a second of the default main star autoscan (according to the journal timestamps).

Thinking about it now, this is probably why I'm getting star/body reports before the FSS report, as the default autoscans are completing a fraction of a second before the honk is, and that has led me to believe things were in the 'wrong order' so to speak.

I've just tried a few systems, and let the autoscans complete before initiating the honk, and this does seem to confirm my hypothesis: I am starting my scan too soon.

So, may I change the request slightly?  Would it be possible to have an 'Autoscan complete' event (or even just a message) to fire just as the first autoscan in the journal appears?  As they all appear at the same timestamp, I don't think this would be too much of a problem with timings.

**Comment by Tkael** [comment]
Autoscans are triggered by proximity. They'll trigger for any bodies within the scanning range of the arrival point but they can also occur later if you fly close enough to another body that you haven't scanned.

In any case, it sounds like you've worked out a solution that you're happy with?

**Comment by Darkcyde13** [comment]
Yeah, I figured that was the case after more thought on the matter.  My solution is pretty basic, I just get EDDI to say "Auto scan complete" at the beginning of the first star/body report after jumping into a system, and then set a variable to turn it off.  So this won't work for any further stars or bodies that may get auto scanned by proximity later.

For explorers, I don't think this will matter much, as 99% of the time the honk will be done at the main star after jumping in.  Then all bodies will (usually) be scanned from there, without moving, thus no more auto scans.

At the moment, I have the message play no matter what you have your ship role set at, but I think I will move it into the script IF statement so that it will only be spoken for Exploration and Multipurpose, just like the reports.  That should mitigate most of the unnecessary executions of it.

I did think about asking for an event variable, something like 'event.autoscan = true/false', but then I'd have to deal with preventing multiple 'Auto scan complete' messages, one for each star/body report.  Although, I could work around that by setting a timer, and not have the message play if it's within a second or two of the previous one....  Hmm, would that be a possibility? Could you add such a variable for me?  It would be a lot less work for you to implement, no changes will be necessary to current scripts, and I will be able to do exactly what I'm looking to achieve.  Could you do that please? :)

**Comment by Hoodathunk** [comment]
@Darkcyde13 , in the `Body scanned` and `Star scanned` events, the `scantype` property tells you the type of scan... "AutoScan", "Basic", "Detailed", "NavBeacon", or "NavBeaconDetail".

If you don't want to hear the "AutoScan" types before the honk, just filter them out in the `Body scanned` and `Star scanned` scripts.

**Comment by Darkcyde13** [comment]
Ohhh… I must have missed that. My apologies.  Then that's all I need.

Well, thank you both for your help, and I'm sorry to have wasted your time.

**Comment by Hoodathunk** [comment]
Nope, time not wasted... just took a bit to figure out what you needed.

**Comment by Darkcyde13** [comment]
I did notice last night, that the Variables pages for both the Body scanned and Star scanned do not mention the 'event.scantype' property.  Is this supposed to be a 'hidden' variable, or are the pages just missing it?

**Comment by Hoodathunk** [comment]
Apparently, `scantype` is not supposed to be 'user-facing', but that can be easily corrected.

**Comment by Hoodathunk** [comment]
PR #1531 submitted to make `scantype` user-facing.

**Comment by Tkael** [comment]
Merged.
