### ISSUE TITLE
eddi frontier api connection not authenticating

### ISSUE THREAD

**Issue by highflyersnl** [EDCD/EDDI#1528]
## EDDI version in which issue is found
3.4.3

## VoiceAttack
not running yet

## Steps to reproduce
1. when i tell the EDDI app to login and authenticate with the frontier API when i press login on the site EDDI tells me that it can not run multiple instances of EDDI but the problem is EDDI needs the feed back from the site that the log in has happened and then it needs the feedback from the API site that its authenticated but it does not go past the login because of the fact that sending that signal to EDDI app it triggers a New instance of the app instead of EDDI using the trigger to authenticate. i have tried it multiple times and every time its the same i even told my browser to ask me how to treat the signal from the site, but off course you can only direct that to the EDDI app but then you get the multiple instances message. 

## Expected
is that it authenticates with the frontier API like it did all the other times before the last update.

## Observed
EDDI tried to start multiple instances of its self and it cant thus it creates a error

## Investigation
non because the upgrade is mandatory meaning its useless to try with older versions.

**Comment by Tkael** [comment]
Please review similar closed issues and see if the guidance there helps in this case:
https://github.com/EDCD/EDDI/issues/1180
https://github.com/EDCD/EDDI/issues/1451

**Comment by highflyersnl** [comment]
okey the problem is the administrative rights. but the thing is that it used to work before the update with admin rights so the code is still bugged from the original. BTW i searched for similar issues before i posted but could not find it my self maybe its the search i did as i searched on the text i also used as a issue title

**Comment by Tkael** [comment]
The code hasn't changed. That said, your pc must have entered an edge case state somehow. @richardbuckle Thoughts?

**Comment by highflyersnl** [comment]
i did not say its changed it just that its bugged from the original so that the edge case could show up after years of working without problems. after all i am not the only one person to experience the problem as you showed with the link to 1451.

**Comment by Hoodathunk** [comment]
Administrative rights, out of absolute necessity, is entirely within the purview of the OS. Giving apps access to set/bypass administrative rights would be scary, dangerous. laughable, all of the above.

Feel free to check our commits to see the last time anybody touched the API authentication code base.

Given the understanding of how administrative rights for apps work, it's extremely more likely that Windows pushed a security update between EDDI revisions that required the user to re-certify administrative rights for EDDI than it being an EDDI 'bug'.
