### ISSUE TITLE
VA profile typo for Cadmium

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1535]
## EDDI version in which issue is found
EDDI 3.4.3
## VoiceAttack version in which issue is found (as applicable)
VA 1.7.8

## Steps to reproduce
1. Execute `How many` or `What use is` VA commands using **cadmium** as the material

## Expected
Report of cadmium inventory and blueprints requiring cadmium

## Observed
Hear Error message about null value.

## Investigation
cadmium is misspelt as _cadmiun_ throughout EDDI VA profile.

**Comment by Tkael** [comment]
Merged.
