### ISSUE TITLE
Spoken name field in Ship Monitor has red border

### ISSUE THREAD

**Issue by CubieX** [EDCD/EDDI#1537]
## EDDI version in which issue is found
3.4.3

## Steps to reproduce
1. Try to add a spoken name for your ship

## Expected
The name should be "locked in" when pressing ENTER in the text field.
Or be active automatically.

## Observed
Text field stays with red border and when pressing "Hear it", it only says:
"Beluga I stands ready" instead of "Beluga One stands ready".
I cannot enter "Beluga One" as text.
I cannot enter "bɪˈlugə wʌn"
It will become red for no apparent reason.
I can enter "bɪˈlu" or "belu" but not more.
I guess it's checking for correct IPA phonetics. But it IS IPA... (used the online transcriber tools linked in EDDI)

## Investigation
Changed the tab. Still red outline.
Restarted EDDI. Text field empty again.

**Comment by rodan123** [comment]
I have some experience with getting the phonetic names working in the Ship monitor.
It sometimes takes some research and fooling with to get a working phonetic name. 
The translation websites do not always give an exact translation that will work with EDDI. 
I used [www.internationalphoneticalphabet.org/ipa-charts/ipa-symbols-chart-complete/
](url) to fine tune the translation.

In your case it seems the 'g' sound is the issue. replacing with the phonetic symbol ɣ or ɰ works best. Also, note the symbol that replaces a space between words. Below is a translation that should work for you;
bɵluɰəˈwʌn

Hope that helped.

**Comment by CubieX** [comment]
Oh wow. "bɵluɰəˈwʌn" indeed works.
But that's quite a hassle to figure out, if even online translators for IPA fail...
Thanks for the link. It will come in handy next time I name a ship.

**Comment by CubieX** [comment]
So it's not a bug. Just a very picky text field for an IPA translation.
