### ISSUE TITLE
eddi unable to connet frontier api, and does not say if or how many stations are in system when i arrive.

### ISSUE THREAD

**Issue by Bladesmith24** [EDCD/EDDI#1548]
## EDDI version in which issue is found  version 3.4.3
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable) not running
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
Attempted to go thru the speech responder list but all check boxes for station and systems are checked. I miss dropping in system and knowing if and how many stations/outpost there were. it used to tell how many orbital and how many surface. now nothing. please help.

2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]
when arriving in a system it should tell you how many station and or outpost there are. 
## Observed
[Describe what happened instead]
nothing just said star info and that's is it. when I used the discovery scanner only said how many objects need to be scanned. nothing about stations/outpost
## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
restarted eddi. also noticed frontier api no longer able to connect.i have tried the reset but keep getting the only one instance of eddi can run at a time please close other instance message. I hit rest wait for the window where you enter your api email and pass then close eddi. enter my info. click connect. then I get the window do you want windows to open EDDI. I click yes/open. but still show as not connected.im not sure if that is why. again please help.

**Comment by Tkael** [comment]
The discovery scanner script is not designed to tell you how many stations exist in a system. There is a count of non-body objects available in the event variables but this count may include more than just the quantity of dockable stations and by default is not used within the script.

For the Frontier API, is either EDDI or your browser running in administrator mode? If so, make sure the other is running in the same mode.

**Comment by Tkael** [comment]
Ref. #1541

**Comment by Bladesmith24** [comment]
eddi is in administrator mode but microsoft edge is not. and I can not find in properties were to turn run as administrator on. edge is the only browser on pc.

________________________________

**Comment by Hoodathunk** [comment]
To add to Tkael's comment, you will get a station count from the `System report` script (upon arrival) only if there's a human presence in the system. This comes from a remote server query, not local journal data.

**Comment by Tkael** [comment]
Try turning off administrator mode for EDDI.

**Comment by Bladesmith24** [comment]
i will try that but elite dangerous is set to run as administrator as well so should i revert all 3 programs. elite,eddi,and voice attack to normal.
________________________________

**Comment by Tkael** [comment]
As I understand it, EDDI and the browser both need to be in the same mode (administrator or not) but the mode for Elite should be irrelevant for the authentication. 
EDDI must be configured to connect to the Frontier API in standalone mode (without VoiceAttack). Once configured, you'll be free to close the standalone window and reopen in VoiceAttack.

**Comment by Tkael** [comment]
Hi @Bladesmith24, were you able to connect to the Frontier API?

**Comment by Bladesmith24** [comment]
No I go to the website enter the information but keep getting the only one instance of eddi can run at a time message I even close eddi after web page pops up where I enter info. And click connect it opens but nothing. It worked fine before.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Tkael** [comment]
Did you try following the suggestion regarding administrator mode?
