### ISSUE TITLE
VoiceAttack 'say' function doesn't parse International Phonetic Alphabet

### ISSUE THREAD

**Issue by Nerezza** [EDCD/EDDI#155]
## Steps to reproduce

1. Set up a ship in EDDI with a spoken, IPA-based name.
2. Use VoiceAttack's default profile for 'pre flight system checks'
3. The first line in the response, and the last line in the response, will either omit the ship's spoken name entirely or spell out any English characters used by the name (ie, 'ɑːrktɪkɑː' becomes 'r k t k')

## Expected
Phonetic reading of a ship name

## Observed
TTS picked out the English letters in the spoken name and spelled those out instead.

## Investigation
I swapped out the '$='s in the VA lines with {TXT:Ship name (spoken)} and received the same 'r k t k' response anyway. I also tried pasting the IPA-based ship name into the VA lines, and received the same response. My hunch is that either the say function can't parse those IPA characters, or VA can't pass them.

**Comment by Hoodathunk** [comment]
When you enter the IPA based name in the 'Ship Monitor' tab, is the IPA name spoken when you press the 'Hear it' button?

**Comment by Nerezza** [comment]
Yes, it works everywhere else perfectly fine.

**Comment by Tkael** [comment]
We could revise this to use the 'speech' plugin function and add the requisite text to a Cottle script?

**Comment by Tkael** [comment]
I've confirmed that VoiceAttack's say function cannot (at least at present) respond correctly to IPA and I've posted [a request on VoiceAttack's forums for this issue](http://voiceattack.com/SMF/index.php?topic=1555.0).

**Comment by Tkael** [comment]
After getting feedback from the VoiceAttack forums, I've found that it may be possible after all (though finicky). Details in the VoiceAttack forum link.
