### ISSUE TITLE
lost tabs on left hand side 

### ISSUE THREAD

**Issue by Urban-Nutta** [EDCD/EDDI#1552]
## EDDI version        v3.4.3

on updating to version 3.4.3 i have noticed that i have lost alot of the tabs on the left hand side i now only have 4 tabs 
EDDI
COMMANDER DETAILS
FRONTIER API
TEXT-TO-SPEECH
EDDI no longer communicates with me regarding the game it does not read out system stats etc, it does update INARA with the system details as before

## Expected
I expected the program to relay the system details as before 

## Observed
nothing 

## Investigation
i have tried to adjust settings in the available tab
![Capture](https://user-images.githubusercontent.com/56219912/66267491-209d6580-e829-11e9-82d0-44b6600ede57.PNG)
s but cant see any option to enable the missing tabs

**Comment by Tkael** [comment]
Pleas upload a copy of your latest eddi.log file (from `%appdata%/EDDI`).

**Comment by Urban-Nutta** [comment]
Hi , thanks for the responce and sorry for the delay in my reply i think this is the file you require 
[eddi.log](https://github.com/EDCD/EDDI/files/3697164/eddi.log)

**Comment by Tkael** [comment]
It seems like there might be a problem with your installation. Please try reinstalling [from here](https://github.com/EDCD/EDDI/releases/tag/Release%2F3.4.3) and let us know if that resolves the issue.

**Comment by Urban-Nutta** [comment]
Hi i tried an uninstall /remove program and re installed , this did not work, so i then deleted the EDDI folder in app data ( local and roaming )  ran the exe install file and this seems to have resolved the issue i am now seeing all tabs on the left hand side now , thank you for your replies o7
