### ISSUE TITLE
Ship name won't save or be read out if it has a space in it

### ISSUE THREAD

**Issue by jodrell2000** [EDCD/EDDI#1553]
## EDDI version in which issue is found
3.4.3

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. Click Ship Monitor tab. All Name (spoken) fields are empty
2. Click twice in Name (spoken) field
3. type "limited ". Once you press space the field highlights in Red and refuses to save or be spoken

## Expected
The ship is called LCU: No I'm Not LostI I'm trying to have the spoken version read out @Limited Contact Unit: No I'm Not Lost!

## Observed
The field highlights red as soon as a space is typed. It won't then save or be read out

## Investigation
I realised I had a much earlier version installed (2.4.x) when I first saw this problem. I updated today and am still seeing the same issue. I've tried with shorted names thinking the name might be too long, but even "a " produces the same issue.

**Comment by Tkael** [comment]
A space is not a valid IPA character. Please review the example that EDDI gives... we state there that spaces should not be included.

**Comment by jodrell2000** [comment]
Apologies...this page does a pretty good job of doing the translations for you, although you do have to remove the spaces ;-)

https://tophonetics.com/

**Comment by Tkael** [comment]
Yes, there can be small idiosyncrasies between what's rendered by the websites and what EDDI needs to see. I've been thinking about a change to perhaps automatically replace spaces since you're not the first person in recent weeks to miss that subtlety.
