### ISSUE TITLE
EDDI version 3.43 not working

### ISSUE THREAD

**Issue by zkfbzjm** [EDCD/EDDI#1554]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Darkcyde13** [comment]
Could you fill in and complete the above questions please?  Nothing can be done to help you if you don't give any information in the first place.  Completing the form will allow the developers to sort your problems out much faster. :)

**Comment by Tkael** [comment]
Closing due to lack of detail / inability to replicate.
Feel free to add more detail - I'll be notified and be able to re-open the issue.
