### ISSUE TITLE
Scripts can recommend bodies to map in settled systems

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1563]
## EDDI version in which issue is found
3.5.0-b1

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Use a ship with role set to `Multipurpose` or `Exploration`
2. Enter an explored system with population > 0 and a nav beacon.
3. Honk the discovery scanner and listen to the scripted response.

## Expected
No comments about mapping already explored bodies

## Observed
Script recommends bodies to map

## Investigation
- We could limit the script to only trigger when `system.population == 0`
- We could limit the script to only trigger when a system has no factions.
- We could set a system bool when a nav beacon is detected and limit the script to only trigger when no nav beacon is present (may not be foolproof for bodies very close to the jump point since it uses data from after the `Jumped` event).

**Comment by Darkcyde13** [comment]
I thought it was still possible to map already discovery bodies in the bubble?  I swear I was able to do it at the beginning of the year (when I was last there).  Is it no longer possible now?

**Comment by Tkael** [comment]
It is still possible but recommending bodies in settled systems for mapping wasn't ever really the goal and in my opinion verges on too much speech when flying around the bubble (particularly for less experienced commanders that use the `Multipurpose` role on many of their ships).

**Comment by richardbuckle** [comment]
On the other hand, I've been quite liking it on my alt account. Maybe limit it to the "Exploration" role.

**Comment by Tkael** [comment]
Ok. So perhaps changing the `Discovery scan` script from
```
    {if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":
```
to
```
    {if ship.Role.edname = "Exploration" || 
        (ship.Role.edname = "Multipurpose" && len(reportSystem.factions) = 0):
```

**Comment by richardbuckle** [comment]
I think you may be missing the point that my junior alt can profit a lot from mapping stuff in the Bubble that is already mapped, regardless of population. 

I'd be inclined to leave it, or perhaps go with just `if ship.Role.edname = "Exploration`.

**Comment by Tkael** [comment]
`if ship.Role.edname = "Exploration"` is less inclusive than `    {if ship.Role.edname = "Exploration" || (ship.Role.edname = "Multipurpose" && len(reportSystem.factions) = 0):` ;-)

**Comment by richardbuckle** [comment]
Works for both my newbie and old accounts but probably merits a comment.
