### ISSUE TITLE
Unlocalized text: weapon type

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1568]
## EDDI version in which issue is found
3.5.0 dev

## Steps to reproduce
See EDDI\JournalMonitor\JournalMonitor.cs around line 3157.

## Expected
[Describe what you expected to happen]
Words are all localised in REGX resources and any string is built using the current language's grammar.

## Observed
Words are hard-coded and the string is naively built in a way that assumes English grammar.

**Comment by richardbuckle** [comment]
Commit 493b03e74f23e4aa46918f4cd4692815fd2b54bb

**Comment by Tkael** [comment]
We can use `Module.cs/LocalizedMountName()` (https://github.com/EDCD/EDDI/blob/327ae6679315bf49a8038b2658609ccf54897b18/DataDefinitions/Module.cs#L101) to resolve instances of unlocalized text at https://github.com/EDCD/EDDI/blob/327ae6679315bf49a8038b2658609ccf54897b18/JournalMonitor/JournalMonitor.cs#L3103 and https://github.com/EDCD/EDDI/blob/327ae6679315bf49a8038b2658609ccf54897b18/JournalMonitor/JournalMonitor.cs#L3157.

To address the grammar, however, I think we need to revise Module.cs. 
- LocalizedMountName() is not readily accessible from Cottle / VA. 
- "mount" is documented as being used for accessing the module mount but that property is an unlocalized enum.
