### ISSUE TITLE
ED 2.4.03 spams CG events

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#157]
## Steps to reproduce

1. Sign up to any CG
2. Jump, drop in and out of supercruise

## Expected
I only get speech about CGs when I look at them or invoke the script via VA. 

## Observed
The game now spams CG events every 10 mins and every jump, drop in and out of supercruise, and I get speech each time. This is maddening, but it would be nice to silently update the data we hold.

## Investigation
Jorunal excerpt show no flags we can use to discriminate:

```
{ "timestamp":"2017-10-11T21:55:18Z", "event":"SupercruiseExit", "StarSystem":"Uhlang", "Body":"Uhlang A", "BodyType":"Star" }
{ "timestamp":"2017-10-11T21:55:18Z", "event":"Music", "MusicTrack":"Exploration" }
{ "timestamp":"2017-10-11T21:55:23Z", "event":"CommunityGoal", "CurrentGoals":[ { "CGID":425, "Title":"Third Aegis Initiative", "SystemName":"Wyrd", "MarketName":"Vonarburg Co-operative", "Expiry":"2017-10-12T15:00:00Z", "IsComplete":false, "CurrentTotal":16879049, "PlayerContribution":0, "NumContributors":7655, "TopRankSize":10, "PlayerInTopRank":false, "TierReached":"Tier 3", "PlayerPercentileBand":100, "Bonus":500000 } ] }
```

**Comment by richardbuckle** [comment]
Maybe only speak when docked?

**Comment by StivlWrith** [comment]
Is it time to monitoring missions and CG missions? So we can compare if CG exist in json file before to speech.

**Comment by Tkael** [comment]
I think that's going to need to part of the long term solution.

**Comment by richardbuckle** [comment]
Short term fix is done. Assigning the long term fix to the post-2.4.0 milestone.

**Comment by clinkingdog** [comment]
(Apologies for newb question...) What's the procedure for getting hold of this fix? Will it go into a new beta release at some point and therefore come via the auto-update?

**Comment by richardbuckle** [comment]
It will be in the forthcoming beta 6. In the meantime you can turn off the community goal event in the speech responder tab (duplicate the default personality if you haven't already).

**Comment by clinkingdog** [comment]
Great - Thank you!
