### ISSUE TITLE
Munged timestamps in EDDN commodity/shipyard/outfitting messages

### ISSUE THREAD

**Issue by klightspeed** [EDCD/EDDI#1571]
https://github.com/EDCD/EDDI/blob/493b03e74f23e4aa46918f4cd4692815fd2b54bb/EDDI/MarketInfoReader.cs#L12

Without `System.Globalization.DateTimeStyles.AdjustToUniversal`, this converts the timestamp to local time.  This is resulting in about 30% of EDDI's Commodity messages (and likely Shipyard and Outfitting messages as well) having munged timestamps.

**Comment by Tkael** [comment]
```
I think EDDI's issue is that MarketInfoReader is using DateTime.Parse(timestamp) without specifying System.Globalization.DateTimeStyles.AdjustToUniversal, so the time is being "helpfully" converted to local time.
```
