### ISSUE TITLE
Idea: Add a global search box to the speech responder

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1576]
## EDDI version in which issue is found
3.5.0-b2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Try to find all instances of known string within the personality (like the name of a script or a state variable)

## Expected
Scripts containing the desired string are easily found.

## Observed
It is not easy to identify all instances of a string within the personality.
Either scripts must be individually searched in EDDI's UI (slow and easy to miss what you're looking for) or the personality must be searched via an external tool (not user friendly). 

## Investigation
N/A

**Comment by richardbuckle** [comment]
As we are about to overhaul that UI via #1032, it might be best to wait until that is done.

**Comment by Tkael** [comment]
Agreed.

**Comment by richardbuckle** [comment]
We will get this for free with AvalonEdit.

**Comment by Tkael** [comment]
Within the script editor, yes. My original thought was to have a search box for our list of scripts so that we could search the personality for all instances of an invoked script or all uses for a particular variable.

**Comment by richardbuckle** [comment]
OK searching across all scripts would be rather more work.

**Comment by Tkael** [comment]
True, but it would also provide a capability that we currently lack.

**Comment by eavdmeer** [comment]
Excellent idea! If you do add this, please make it search **inside** the scripts as well. It can be a monumental task to find things you hear EDDI say in the standard scripts.

**Comment by clinkingdog** [comment]
Yeah I'm in favour of this too - would save a bunch of time debugging things if I could just search for where a particular script was called.
