### ISSUE TITLE
The variable for total  number of bodies is disappearing

### ISSUE THREAD

**Issue by Noodles4Pasta** [EDCD/EDDI#1578]
## Steps to reproduce
1. Be on a FAST computer.
~ I have an i9 9900k with 32GB ram and a Fast NVME m.2 SSD drive.
2. Set the folowing variables to post to the VA log When a discovery scan happens:
{INT:EDDI discovery scan totalbodies}
{INT:EDDI discovery scan bodies}
{INT:EDDI discovery scan nonbodies}
_*See pics for example_

## Expected
You would expect "totalbodies" and "bodies" To have the same result as according to the ones I talked to on the EDCD discord, "bodies" is set from the "totalbodies" variable.

## Observed
What is observed instead is that Total bodies is "Not Set" and "bodies" will have an accurate count... See pics for example.

## Investigation
We looked at the events in the journal, and tried several iterations of the variable in VA.

The only conclusion I can come up with is that since my computer is so blazingly fast, it's causing the variable to be unset before VA can have a chance to read it. ( I was told that the totalbodies variable is not kept but disappears after it's scanned)

A possible fix would be to make "totalbodies" a permanent variable that doesnt erase after a time.
Another would be to add a pause or timer to be able to set a variable within that time before it disappears.

![Untitled](https://user-images.githubusercontent.com/45958456/67614029-3c8a8c00-f783-11e9-938a-07db81c7c6e3.jpg)
Or https://imgur.com/A7KmuXS

![Untitled0](https://user-images.githubusercontent.com/45958456/67614031-4ad8a800-f783-11e9-8090-bc2320d8425f.jpg)
Or https://imgur.com/drtttWe

**Comment by Darkcyde13** [comment]
I believe you will find that 'bodies' and 'nonbodies' are set from the event object.  There is no event.totalbodies, hence it's not set in VA.

My PC is a 5 year old AMD, and I get the same results as you.  I don't think it's anything to do with speed.

**Comment by Darkcyde13** [comment]
I believe you will find that 'bodies' and 'nonbodies' are set from the event object. There is no event.totalbodies, hence it's not set in VA.

My PC is a 5 year old AMD, and I get the same results as you. I don't think it's anything to do with speed.

However, I did notice that, as the changelog says,  totalbodies is available under the 'system' object, not part of the discovery scan event, so it would never work trying to access it that way anyway.

I've tried {INT:System totalbodies} which I would expect to work, but that doesn't either.  While I may be wrong (and I probably am), I don't think it's available to VA at the moment.  Or I just tried to access it the wrong way, which is quite possible as my VA skills are not as good as my EDDI skills. :P

**Comment by Tkael** [comment]
The ticket helped... I've found the answer... you're using EDDI version 3.4.3. 
`totalbodies` does not exist in the version 3.4.3 version of the event... that change occurred for version 3.5.0-b1. 
If you upgrade tot he latest beta I think you'll find that ` {INT:EDDI discovery scan totalbodies}` works just fine. :-)

**Comment by Darkcyde13** [comment]
Weird, I installed 3.5.0-b2 when I tested this earlier, specifically just to try it, and {INT:EDDI discovery scan totalbodies} didn't work.  However, I've just reinstalled it again, and now it does....  Very strange.

**Comment by Tkael** [comment]
By the way, `{INT:System totalbodies}` was not implemented. I've submitted a PR that implements it.

**Comment by Noodles4Pasta** [comment]
My EDDI program says its up to date... weird. Normally it tells me there is an update for it.

**Comment by Tkael** [comment]
Do you have the checkbox for beta versions checked?

**Comment by Noodles4Pasta** [comment]
Yes. Not sure why it didn’t keep up tho. But reinstalling today and will see if it is still a problem.
