### ISSUE TITLE
CMDR comms are not read out

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#158]
## Steps to reproduce

1. Find another CMDR in game and have them message you

## Expected
The message text should be read out.

## Observed
was getting NPC chatter
player chatter would announce 'messge from' then no readout

**Comment by Nerezza** [comment]
This was working perfectly for me last night using 2.4.0-b5

**Comment by richardbuckle** [comment]
Turns out we fixed direct and wing comms but not local chat.
Adding more unit tests based on real journal entries obtained in game.

**Comment by Nerezza** [comment]
OH, I didn't know that it was supposed to read local chat too.

**Comment by richardbuckle** [comment]
Fixed and tested.
