### ISSUE TITLE
EDDI doesn’t like daylight savings time (or rather, changing the system time backwards)

### ISSUE THREAD

**Issue by alterNERDtive** [EDCD/EDDI#1580]
## EDDI version in which issue is found
3.5.0-b2

## VoiceAttack version in which issue is found (as applicable)
1.7.8

## Steps to reproduce
1. play Elite before time is set back an hour
2. keep playing Elite after time has been set back an hour

## Expected
EDDI works just as normal.

## Observed
EDDI doesn’t fire events in VoiceAttack anymore. (There might be other things that break, but this is what I noticed because I’m actually using it. I’m assuming anything journal-related will cease working.)

## Investigation
I’m _assuming_ new events are being discarded because they happened “before” events that have already been processed.

After manually setting the time 1h later it starts working again. Setting the clock back to the correct time breaks it again. I restarted Elite after changing the time, just to be sure.

I’m not really sure if there’s a feasible solution for this, and it only ever is relevant once per year (or if people play Elite, venture some thousand kilometers west and play Elite again on the same machine :D), but it’s a bug nonetheless.

**Comment by Tkael** [comment]
Might be related to this? https://forums.frontier.co.uk/threads/report-issues-using-the-issue-tracker.507724/post-8109899

**Comment by richardbuckle** [comment]
Eek, the journal is supposed to be writing timestamps in UTC, aka "Zulu", that is what the Z on the timestamp means. This is a Frontier bug.

**Comment by richardbuckle** [comment]
I am not sure we should attempt a fix for this as we are being given bad data. Frontier really need to fix it at their end and any fix we attempt would be a nasty workaround at best.

**Comment by Tkael** [comment]
Agreed. I don't think we can put resources on this one right now.

**Comment by alterNERDtive** [comment]
> Eek, the journal is supposed to be writing timestamps in UTC, aka "Zulu", that is what the Z on the timestamp means. This is a Frontier bug.

Too bad you guys are way faster at fixing bug than they are … guess I’m still going to file a ticket on the tracker (and link it here if you want to give it your vote).

**Comment by alterNERDtive** [comment]
This has [already been reported on Frontier’s tracker](https://issues.frontierstore.net/issue-detail/8716). Just like all the other bugs it’s still “confirming”. Great, isn’t it?
