### ISSUE TITLE
System information doesn't need to be read all the time

### ISSUE THREAD

**Issue by k5jat** [EDCD/EDDI#1581]
## EDDI version in which issue is found
v.3.4.3

## VoiceAttack version in which issue is found (as applicable)
1.7.8

## Steps to reproduce
1. Jump to a system I've been to 20+ times.
2. EDDI/VoiceAttack reads the "system news" every time.

## Expected
I would really like EDDI to not read the system news if it hasn't changed since the last time I visited a system.

## Observed
It doesn't matter if I've been to a system twice or 20 times in an hour, the system news gets read, which gets old quick.

## Investigation
I'm relatively sure this just the feature itself. This augmentation could be a toggle/check box "Read system news even if read before" or something similar.

**Comment by Tkael** [comment]
I'm assuming that you are referencing the `System state report` in the `Jumped` event (describing the faction states of the various factions in the star system).
