### ISSUE TITLE
EDDI doesn't tell body details anymore after changing ships

### ISSUE THREAD

**Issue by Thanatux** [EDCD/EDDI#1583]
## EDDI version in which issue is found
EDDI v.3.4.3

## VoiceAttack version in which issue is found (as applicable)
VoiceAttack v1.7.8
Singularity v2.2.4
HCS Plugins v3.3.2

## Steps to reproduce
Fly into a system that has already been discovered by another cmdr and use discovery scanner.

## Expected
If earthlikes, terraformables, ammonia or waterworlds are detected, EDDI should read them out as "mapping candidates". Likewise, ringed planets should also be described for their ring-type.

## Observed
EDDI remains silent throughout the entire scan and doesn't announce mapping-candidates after the system has been fully scanned.
Otherwise, EDDI seems to function normal, announcing system-details while in hyperspace etc.

## Investigation
Behaviour startet after switching ships from a Krait Phantom designated in EDDI as "exploration" to a KRAIT MK II designated as "combat"

**Comment by Tkael** [comment]
This is intended behavior. The script only triggers the additional dialog if you are in a ship with the assigned role of "exploration" or "multipurpose".

**Comment by Thanatux** [comment]
Wouldn't it be nice, if it was also triggered in the "mining" role. Information about ringtypes is relevant.
