### ISSUE TITLE
Translation of EDDI in Version 3.5.0

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1588]
## EDDI version in which issue is found
Version 3.5.0.

## Investigation

Question: The areas "Crime Monitor" and "INARA Responder" were not translated into version 3.5.0. . Is there a reason ? I thought this would be done for larger version jumps.

**Comment by Tkael** [comment]
I'm not sure what you mean? Please give specific details.

**Comment by nepomuk16321** [comment]
The German translation for "Crime Monitor" and "INARA Responder" is not included. 
It's not bad now, but I thought it would be done with every major version jump.
The text passages were added to 
https://crowdin.com/translate/eddi/134/en-de
https://crowdin.com/translate/eddi/120/en-de
translated.

**Comment by Tkael** [comment]
Hmm... I see them on CrowdIn but they should have synced to Github once they were approved. I'm not sure why they didn't. @richardbuckle , your thoughts?

**Comment by richardbuckle** [comment]
It's an error at our end: the translated resources were not added to the Crime Monitor and Inara Responder projects in Visual Studio. We can fix that for the next release.

**Comment by richardbuckle** [comment]
Fixed for 3.5.1-b1. Thanks for the report: it affected other languages too!
