### ISSUE TITLE
INARA responder crashes EDDI

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1589]
## EDDI version in which issue is found
3.5.0

## VoiceAttack version in which issue is found (as applicable)
1.7.8
## Steps to reproduce
1. Install EDDI 3.5.0 and launch VA
2. VA crashes to desktop

## Expected
No Crashes.

## Observed
Crashed to desktop

## Investigation
I don't use an INARA account and haven't a key. The EDDI INARA responder defaults to enabled.
Looked at the EDDI log file and got the following errors;

_2019-11-10T05:26:58 [Info] InaraService:.ctor Configuring Inara service for limited access: API key not set. 
2019-11-10T05:26:58 [Info] InaraResponder:.ctor Initialized Inara Responder 
2019-11-10T05:26:59 [Info] EDDI:Start Started Inara Responder_ 

**Then a bunch of these;**

_2019-11-10T05:27:13 [Error] InaraService:validateResponse Inara responded with: You cannot perform this event with read-only API key. "{\"InaraAPIEvent\":{\"eventName\":\"setCommanderCommunityGoalProgress\",\"eventTimestamp\":\"2019-11-10T05:26:35Z\",\"eventData\":{\"communitygoalGameID\":603,\"contribution\":1529,\"percentileBand\":50.0,\"percentileBandReward\":1520000,\"isTopRank\":false},\"eventCustomID\":13},\"InaraResponse\":{\"eventStatus\":400,\"eventStatusText\":\"You cannot perform this event with read-only API key.\",\"eventData\":null,\"eventCustomID\":13}}"_

**Finally;**
_2019-11-10T05:27:46 [Info] EDDI:Stop EDDI 3.5.0 stopped_    

Disabling the INARA plug-in seems to have stopped the crashing. Log file attached.
[eddi2.log](https://github.com/EDCD/EDDI/files/3828111/eddi2.log)

**Comment by Tkael** [comment]
Hmm... nothing I'm seeing in the logs looks like it would lead to a crash.
Does EDDI crash when running EDDI in standalone mode with the Inara Responder enabled or only with VoiceAttack and the Inara Responder enabled? Does it crash consistently or does it only crash sometimes?

**Comment by rodan123** [comment]
Perhaps you are correct. I cannot duplicate the crash either standalone or with VA.
I did notice that the system visit counts were incorrect and refreshed the database from EDSM.
Maybe I was crashing because of a corrupt database.

Closing this, will open anew if I have an issue again.

Thanks.
