### ISSUE TITLE
Typo in updated Engineer Progressed script

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1591]
## EDDI version in which issue is found
v3.5.0

## VoiceAttack version in which issue is found (as applicable)
v1.7.5

## Steps to reproduce
None.

## Expected
N/A

## Observed
N/A

## Investigation
The updated Engineer Progressed script has a capital E for engineer in the last |elif statement. I'm not sure if this is case sensitive or not, but if it is then I guess this will not work.

**Comment by nepomuk16321** [comment]
Yes, you're right! 
If you change that (E to e), the script works.

**Comment by Tkael** [comment]
Good catch. Looks like @richardbuckle is already on it. :-)

**Comment by richardbuckle** [comment]
Fixed for 3.5.1.
