### ISSUE TITLE
Mission monitor says that I need to complete missions that only need to be claimed

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1593]
## EDDI version in which issue is found
3.5.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Log out of Elite with assassination missions that are completed but not yet claimed
2. Log into Elite and listen to the `Commander Continued` / `Mission check galaxy` scripts.

## Expected
"You have unclaimed rewards from 6 missions."

## Observed
"You have 6 missions to complete. They have no designated target systems.."

## Investigation
N/A

**Comment by richardbuckle** [comment]
A wording issue I think. Let me amend the title.
