### ISSUE TITLE
EDDi Crashes when enter home system Shinrartra Dezhra

### ISSUE THREAD

**Issue by psefer** [EDCD/EDDI#1596]
## EDDI version in which issue is found
3.5.0.0

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. Install 3.5.0.0.
2. entering the correct edsm.net details
3.get this https://i.imgur.com/RfgByc9.jpg
4.And finally typing Shinrartra Dezhra in home system

## Expected
working as planned but because it can't communicate with edsm servers it causes a crash
[eddi.log](https://github.com/EDCD/EDDI/files/3838031/eddi.log)

here is the eddi.log

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
To be clear, do you try to sync your logs before you see the result in the screenshot?

**Comment by psefer** [comment]
I have tried to sync my logs and got the screenshot then I tried to type shinrarta dezhra and crashed to desktop.i am almost certain that this is a eddiscovery problem that creates syptoms both to eddi and g19s applet

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Tkael** [comment]
Additional information from https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8138082:
- i have an edsm key for a long time and was using ok but after eddi 3.5.0.0 and eddiscovery i have problems
- The problem i am having of not been able to correctly connect to edsm through eddiscovery after searching the internet was solved in the past with obtaining license for a expired security certificate

**Comment by Tkael** [comment]
1. Are you able to connect to EDSM by visiting www.edsm.net?
2. Would you please provide a **verbose** log? The basic log includes much less detail about EDSM related exceptions.

**Comment by psefer** [comment]
Yes I am able to connect cto edsm.net and everything works ok in the webpage
Can you explain me how  do I find the verbose log ? It’s location (folder)?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by psefer** [comment]
i have installed EDdiscovery latest version in another computer that i have in my home and the error is the same

**Comment by Tkael** [comment]
You need to `enable verbose logging` via the EDDI UI. The checkbox should be available from the main page in the UI (the top left tab).

You keep referencing EDdiscovery, which is confusing. EDdiscovery is a different 3rd party application not associated with us. EDDI stands for Elite Dangerous Data Interface.

**Comment by psefer** [comment]
i enable verbose logging now. how do you want me to proceed

**Comment by psefer** [comment]
i

> 
> 
> You need to `enable verbose logging` via the EDDI UI. The checkbox should be available from the main page in the UI (the top left tab).
> 
> You keep referencing EDdiscovery, which is confusing. EDdiscovery is a different 3rd party application not associated with us. EDDI stands for Elite Dangerous Data Interface.

i keep referring to Eddiscovery because i suspecct that the problem is Eddiscovery related and not eddi  since it connects ok to inara

**Comment by Tkael** [comment]
Please follow the same steps as before then share the log here. Depending on the file size, you may need to compress it into a .zip file before you can attach it.

**Comment by richardbuckle** [comment]
Looking at the first log, we have a lot of `StarMapService:sendEvent The request was aborted: Could not create SSL/TLS secure channel.` This implies that the EDSM server was either offline or experiencing difficulties at the time in question.

I've managed to reproduce the exception in the dev environment by renaming the SQL DB and changing the EDSM URL in StarMapService.cs to "https://example.com/". This has given me enough reproducibility to trial a fix, which I shall PR.

**Comment by psefer** [comment]
Here is the second log today

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by richardbuckle** [comment]
@psefer It turns out that we won't need the verbose log for this one. It looks like you were unlucky enough to catch EDSM when the server was down. The next release of EDDI will have morfe defensive coding so as to handle that gracefully. Thanks for the report!
