### ISSUE TITLE
Decimal token could not be converted

### ISSUE THREAD

**Issue by Slegnor** [EDCD/EDDI#1598]
## EDDI version in which issue is found
3.5.0

## VoiceAttack version in which issue is found (as applicable)
1.7.8 Steam

## Steps to reproduce
Use the FSS to scan bodies and this appears in the VoiceAttack log:

Stars:
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned semimajoraxis}
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned orbitalperiod}
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned rotationperiod}
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned periapsis}
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned orbitalinclination}
12:58:33 - Decimal token could not be converted : {DEC:EDDI star scanned eccentricity}
12:58:33 - Plugin command : '((EDDI star scanned))'

Planets:
11:07:19 - Decimal token could not be converted : {DEC:EDDI body scanned rotationperiod}
11:07:19 - Decimal token could not be converted : {DEC:EDDI body scanned orbitalinclination}
11:07:19 - Decimal token could not be converted : {DEC:EDDI body scanned distancefromarrival}
11:07:19 - Plugin command : '((EDDI body scanned))'

## Expected
This has never worked so I assume some sort of number calculation should occur

## Observed
The above errors

## Investigation
It was suggested it may be a regional settings issue, so I have made sure everything is set to English in Regional options in Windows and it is using a . for decimal symbol not comma
EDDi and VoiceAttack are set to English, not System Default/Auto

**Comment by Darkcyde13** [comment]
I may be wrong, but I was under the impression that the only variables available to VA were those listed here:- https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration
Body/Star data isn't listed, so I thought that those wouldn't be available?

**Comment by Tkael** [comment]
If you suspect regional settings, try replacing `{DEC:EDDI star semimajoraxis}`with `{DECINV:EDDI star semimajoraxis}`. Per VoiceAttack's help manual, this should render the value using the invariant culture settings rather than with your local / regional culture settings.

**Comment by Tkael** [comment]
@darkcyde those are event variables, documented on the applicable event page: https://github.com/EDCD/EDDI/wiki/Star-scanned-event

**Comment by Darkcyde13** [comment]
@Tkael Ahh, I see.  Sorry, I'd never realised those pages had that information. It's been a very long time since I last looked at the wiki.  Guess I should use that more often in future! ;)

**Comment by Tkael** [comment]
@Slegnor If the above suggestion doesn't work then please post a screenshot of your VoiceAttack command so that we can see how you're trying to use the variables. Thanks!

**Comment by Slegnor** [comment]
@Tkael 
I am using Malic_VR's profile for VA (.vap attached as .txt)

Someone on his discord channel pointed out that some variables have been changed (RotationPeriod to RotationalPeriod, orbitalinclination to inclination & distancefromarrival to distance) so i have updated those and they seem to be working now, at least for bodies, however I am still getting the following errors from stars, changing DECINV on them does not seem to make a difference:

13:23:15 - Decimal token could not be converted : {DECINV:EDDI star scanned semimajoraxis}
13:23:15 - Decimal token could not be converted : {DECINV:EDDI star scanned orbitalperiod}
13:23:15 - Decimal token could not be converted : {DECINV:EDDI star scanned periapsis}
13:23:15 - Decimal token could not be converted : {DECINV:EDDI star scanned inclination}
13:23:15 - Decimal token could not be converted : {DECINV:EDDI star scanned eccentricity}
13:23:15 - Plugin command : '((EDDI star scanned))'
[Malic Profile 5 Public-Test-Profile.vap.txt](https://github.com/EDCD/EDDI/files/3851661/Malic.Profile.5.Public-Test-Profile.vap.txt)

**Comment by Tkael** [comment]
What results do you get when when you create a command that writes the values of
`{DECINV:EDDI star scanned semimajoraxis}` and `{DEC:EDDI star scanned semimajoraxis}` to the event log?

**Comment by Slegnor** [comment]
I'm not sure I have added this correctly. created a blank profile and added the following:
![image](https://user-images.githubusercontent.com/11891577/69180821-df75c200-0b05-11ea-8f23-8adf35198639.png)


The log result was this:

19:48:20 - Not set
19:48:20 - Not set
19:48:20 - Plugin command : '((EDDI body scanned))'

**Comment by Tkael** [comment]
Looks ok but I'm not sure why your log result has `19:48:20 - Plugin command : '((EDDI body scanned))'` rather than `19:48:20 - Plugin command : '((EDDI star scanned))'`?

**Comment by Slegnor** [comment]
Sorry, copied the wring bit of the log, it says the same for star scanned (i created the same commands for body and stars)

**Comment by Tkael** [comment]
Oh, I think I see what's going on here. These variables describe orbital parameters relative to the primary star and consequently they are null for the primary star. **They are written for any secondary stars that you scan.** 

If Malic's profile doesn't take those null values into account then it will throw errors whenever it scans primary stars. That is something that Malic will need to address within his profile.

**Comment by Slegnor** [comment]
@Tkael I think you are correct, now I knew what to look for,  i just checked when droping into a system with 3 stars and i got this:
17:44:32 - Plugin command : '((EDDI star scanned))'
17:44:32 - Plugin command : '((EDDI star scanned))'
17:44:29 - Decimal token could not be converted : {DEC:EDDI star scanned semimajoraxis}
17:44:29 - Decimal token could not be converted : {DEC:EDDI star scanned orbitalperiod}
17:44:29 - Decimal token could not be converted : {DEC:EDDI star scanned periapsis}
17:44:29 - Decimal token could not be converted : {DEC:EDDI star scanned inclination}
17:44:29 - Decimal token could not be converted : {DEC:EDDI star scanned eccentricity}
17:44:29 - Plugin command : '((EDDI star scanned))'

Thanks for the figuring this out, I'm going to close this one off
