### ISSUE TITLE
Data Voucher Redeemed 'typo'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1602]
## EDDI version in which issue is found
v3.5.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Hand in a Data Voucher, or run the script test.

## Expected
Script runs through without problems.

## Observed
While the speech is normal for the test (which is all I've done), looking at the code I've spotted an error which would make it fail to produce correct results in many instances.

## Investigation
I've been going through all the scripts in the default, to rebase my personality on the latest iterations.  While doing so, I've come across a couple of problems in the Data Voucher Redeemed script.

The first code block where the number of vouchers and the credit amount are spoken, has a mistake in it.  The parenthesis are missing from the first IF statement.
`{if len event.rewards > 1: vouchers |else: voucher }`

Also, the code doesn't account for one voucher in the code that follows the above IF.
`{Occasionally(2, OneOf("have been", "have now been"))}` should have the option of 'has' for singular vouchers.

This can be fixed with the following:-
```
Data 
{if len(event.rewards) = 1: voucher |else: vouchers }
for {Humanise(event.amount)} credits
{Occasionally(2, "{if len(event.rewards) = 1: has |else: have} {Occasionally(2, 'now')} been"))}
{OneOf("redeemed", "claimed")}
```

Of course, I've written this to my personal preference.  You may choose to do it a different way.  :-)

**Comment by Tkael** [comment]
Confirmed. Thanks for bringing this to our attention.

**Comment by richardbuckle** [comment]
I'll take this. Also you are correct to prefer `= 1` to `> 1` for the singular as in English zero takes plural verbs, such as "zero vouchers are awarded".

**Comment by richardbuckle** [comment]
Will wait for #1601 to avoid merge conflicts.

**Comment by richardbuckle** [comment]
I went with:
```
{set singular to len(event.rewards) = 1}
Data 
{if singular: voucher |else: vouchers}
for {Humanise(event.amount)} credits
{Occasionally(2, "{if singular: has |else: have} {Occasionally(2, 'now')} been"))}
{OneOf("redeemed", "claimed")}
```

There is also the `when()` function as an alternative to `if|else` but I don't see any advantage to it.

**Comment by richardbuckle** [comment]
Just for the record, I'm only going to fix the English version. It's up to translators to apply their own language's grammar ;)
