### ISSUE TITLE
EDSM rejecting ship URI as too long

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#161]
## Steps to reproduce

1. Log into the game with EDDI running and a heavily engineered ship selected

## Expected
Ship data sent to EDDI

## Observed
Exception raised in >	EddiStarMapService.dll!EddiStarMapService.StarMapService.sendShip.AnonymousMethod__0() Line 270	 because clientResponse.Data is null.

## Investigation
clientResponse.statusCode = "RequestUriTooLong, Content-Type: text/html, Content-Length: 186)"
clientResponse.errorMessage = "The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3."
clientResponse.ResponseUri not posted because it contains my API key

**Comment by richardbuckle** [comment]
@Tkael @Hoodathunk when you get a moment can you try to repro this please? You may need to set a breakpoint in the code I touched with my commit just above.

**Comment by AnthorNet** [comment]
The RFC and the default mac lilit for nginx and apache are around 8192 bytes if I recall well.
What you can do, it passing the coriolis link as a POST request. The API work for both.

Cargo/Material/Data too.

For the flight log it is better to say on GET as we reparse the erroneous one every night.

**Comment by richardbuckle** [comment]
I'll switch it to POST this evening and test.
