### ISSUE TITLE
Error on Update

### ISSUE THREAD

**Issue by DarkHorseComm** [EDCD/EDDI#1612]
## EDDI version in which issue is found
EDDI v3.5.1

## VoiceAttack version in which issue is found (as applicable)
N/A
## Steps to reproduce
Preparing to Install.

## Expected
I expected EDDI to update

## Observed
Received and error box

## Investigation
None
![Error](https://user-images.githubusercontent.com/2033738/69904478-d9d57300-1374-11ea-90eb-36b3c4a5aa09.png)

**Comment by Tkael** [comment]
Possibly a file permission error? Installs ok for me and the installer code has not changed.

**Comment by DarkHorseComm** [comment]
I'll uninstall and reinstall

**Comment by Tkael** [comment]
Closing as resolved.
