### ISSUE TITLE
Voice Attack not using EDDI Plug-in

### ISSUE THREAD

**Issue by DarkHorseComm** [EDCD/EDDI#1613]
## EDDI version in which issue is found
3.5.1

## VoiceAttack version in which issue is found (as applicable)
1.8.2

## Steps to reproduce
1. Plug-ins enabled.  Checked plug-ins list and EDDI is not visible.
2. Checked install directory, everything is as instructed.

## Expected
Was hoping to see EDDI Plug-in Initialized... but this didn't happen.

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
There isn't enough information here for us to do anything or teach any conclusions about what is wrong. 
1. Please confirm that EDDI is installed within the `VoiceAttack/Apps` directory (e.g. `VoiceAttack/Apps/EDDI`. 
2. If the install directory is correct, please verify that the program runs in standalone mode (just double click on EDDI.exe to run).
3. Please forward the latest log file from `%appdata%/roaming/EDDI/EDDI.log` so that we can check for initialization errors.

**Comment by Tkael** [comment]
Per #1612, you were having some problems with installing. Please also verify whether you were able to install correctly or whether errors were encountered during installation?

**Comment by DarkHorseComm** [comment]
EDDI is installed in the correct folder.  I'm including the log file
you requested

Thanks for helping.

Mike

**Comment by Tkael** [comment]
There is no log file attached yet?

**Comment by DarkHorseComm** [comment]
Attaching ...

**Comment by Tkael** [comment]
Not attached.

**Comment by DarkHorseComm** [comment]
Last attempt.  Don't know why you're not getting it

Thanks

**Comment by Tkael** [comment]
Still no. Please zip the file them drag it into the message box for your response.

**Comment by DarkHorseComm** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/3908956/eddi.log)

**Comment by DarkHorseComm** [comment]
Sorry about the mess up.  Was sending via my email... not here.

Thanks

**Comment by Tkael** [comment]
Got it. This log appears to have originated from running EDDI in standalone mode. Please confirm whether this log was generated from VoiceAttack or from running EDDI in standalone mode?

**Comment by DarkHorseComm** [comment]
To be totally honest I didn't know there was a difference.  My startup procedure is: EDDI (wait until loads), VoiceAttack (wait again), then Elite Dangerous.  If I need to do something different please let me know.  When you say Standalone I would assume I'm running it that way, yes.  I don't know how to get VoiceAttack to initialize EDDI.

**Comment by Darkcyde13** [comment]
Just run VA, don't run EDDI first.  If EDDI is installed in the correct place, then it will load as a plugin for VA automatically.

**Comment by DarkHorseComm** [comment]
I'm attaching screenshots.  I opened VoiceAttack like I was told.  I didn't see that EDDI was initialized and I checked the Plugin Manager and it wasn't listed.  EDDI is installed to the correct directory.  I'm thinking it's something really simple and I'm skipping over something.
![Plugins](https://user-images.githubusercontent.com/2033738/69987528-b85bbf00-150d-11ea-9035-da1b484cdaa0.png)
![VoiceAttack](https://user-images.githubusercontent.com/2033738/69987530-b8f45580-150d-11ea-9de1-613afbfdf8ff.png)

**Comment by Tkael** [comment]
What directory is EDDI installed to? This would be the directory that contains EDDI.exe. (Feel free to replace your Windows user name if that is part of the path).
It should be something like `c:/Program Files/VoiceAttack/Apps/EDDI/EDDI.exe`

**Comment by DarkHorseComm** [comment]
C:\Program Files (x86)\VoiceAttack\Apps\EDDI
![File Explorer](https://user-images.githubusercontent.com/2033738/69991972-b1857a00-1516-11ea-99ff-6814e7c44ecd.png)

**Comment by Darkcyde13** [comment]
This is probably a dumb question, but you do have VoiceAttack actually installed in the \Program Files (x86)\VoiceAttack\ folder, don't you?  I mean, EDDI looks installed in the correct place, but if VA is somewhere other than the above....

**Comment by Hoodathunk** [comment]
Is the HCS plugin (and profile) a recent update?

**Comment by DarkHorseComm** [comment]
Not a dumb question at all.  I copied directories and put them in the appropriate directory.  Steam sure messes things up doesn't it?  Thanks for you help.  Is there anything I should do to complete the process, or am I done?
![Plugins](https://user-images.githubusercontent.com/2033738/69994383-c6b0d780-151b-11ea-994d-baaa0bc667b8.png)

**Comment by DarkHorseComm** [comment]
@Hoodathunk all is current.  I try to keep things updated as much as possible.

**Comment by Hoodathunk** [comment]
How recent?

**Comment by Darkcyde13** [comment]
Just so I'm clear on this:  Are you saying that you had VoiceAttack installed under Steam, and not in the \Program Files (x86)\Voice Attack\ folder?  Was it installed somewhere in your Steam folder then?

**Comment by DarkHorseComm** [comment]
Yes... under Steam.  I copied the EDDI folder structure to the Steam\steamapps\common\VoiceAttack\Apps\ folder.  EDDI 3.5.1 initializes when VA is executed and is now listed as a plugin in the Plugin Manager.

**Comment by DarkHorseComm** [comment]
Last question.  Is there a way to adjust the volume output while using EDDI through VA?  It seems VERY loud.

**Comment by Darkcyde13** [comment]
The default EDDI VoiceAttack profile has a command 'Configure EDDI'. Use this to open the EDDI config, just as if you had run EDDI as standalone.  Then, under the 'Text-to-Speech' tab, there is a volume slider to adjust.

**Comment by Tkael** [comment]
If you load the EDDI.vap profile, you'll be able to use the command "open EDDI" or the command "configure EDDI" to open EDDI's UI. Once you've done so, volume settings may be found in the Text-to-speech tab.

**Comment by DarkHorseComm** [comment]
Do I import EDDI.vap into Singularity?  I just don't want to get it wrong and have to ask to help fix my screw-up :)  Just preventative maintenance.

**Comment by DarkHorseComm** [comment]
Disregard my previous question.  I've linked the EDDI.vap into Singularity.  Everything is working as it should.  Thanks to Everyone for their help.  VERY much appreciated.

**Comment by Tkael** [comment]
Closing as resolved.
