### ISSUE TITLE
Add TXT variable that lists all modules on the ship

### ISSUE THREAD

**Issue by Noodles4Pasta** [EDCD/EDDI#1644]
## Expected     ## Observed
Add a variable to list in text all the modules on the ship that passes to VA.

## Investigation
I looked in ((EDDI module info)) and in ((EDDI ship loadout)) and could not find a List of all modules.
The ship loadout variable will give you a specific slot module name, but then you have to look through all weapon slots, utility slots, and/or optional internal slots... This could be done in VA but since EDDI already pulls the info, it would be nice to have it also make a master text list.

Something like {TXT:EDDI module info ModulesList} or {TXT:EDDI ship loadout ModulesList} or something similar... This could be in the latter as that is where the individual modules are already listed.

**Comment by richardbuckle** [comment]
An alternative would be a function that yields and iterable list of modules of a given type, or all modules if `null` is given for the type.

**Comment by Hoodathunk** [comment]
Voice Attack does not do objects or lists, and as such, the ship modules are broken down as individual, numbered compartment & hardpoint variables.

https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration

A good number of the module properties (name, class, grade, etc) are available in VA, you just need some experience with VA dynamic variable resolving. That's a topic that is better suited for the ED forum scripts and VA commands thread:

https://forums.frontier.co.uk/threads/eddi-scripts-and-eddi-enabled-va-commands-thread.311614/

**Comment by Hoodathunk** [comment]
Additionally, the ((EDDI module info)) event has the sole purpose of announcing that the data from the `ModulesInfo.json` file has been updated. It has no variables.

The wiki, https://github.com/EDCD/EDDI/wiki/Module-info-event , also states that it has no data.

**Comment by Tkael** [comment]
Using a `For` loop to identify the appropriate index for the module you're searching for had the added benefit of making all of the other properties of that module accessible via the same index number. 
A custom function that simply resolves to `true` or `false` simply cannot compete in terms of the richness of the data.

**Comment by richardbuckle** [comment]
Fair.

**Comment by richardbuckle** [comment]
@Noodles4Pasta let's re-focus in on your exact use case, so that we as devs can provide more focused suggestions?

**Comment by Noodles4Pasta** [comment]
My issue, is I just need to check if a module is present. I don’t need to know which slot it’s in.

As I stated, this could be done in VA by writing a custom code for it, but I am not good enough to do that.
Additionally, this code would be run each time it’s needed.

For example, on the ((EDDI ship undocked)) event, I want it to retract the landing gear. This becomes a problem if my ship has an advanced docking computer, as that also will retract the gear... resulting in it being left deployed.

If I had a text list of the modules on my ship, then all I would need is a simple `IF contains` comparison in VA.

This would be useful in many other areas as well, and would simplify things for people that don’t know how to code... I’m somewhere in the middle... know some but not enough. (I haven’t been able to figure out VA’s loop function...)

**Comment by richardbuckle** [comment]
Sounds like what you *really* want is a boolean `ShipHasModuleOfType(ModuleType t)` function to be exposed from C#-land to both Cottle and VA. And from our side, that'd be the better thing to do. Thoughts welcomed as always.

**Comment by richardbuckle** [comment]
PS I completely understand about it retracting the landing gear for you: totally threw me for a loop just recently -- I have alternatate HOTAS settings when gear is down.

**Comment by Tkael** [comment]
Here's an example using a `For` loop in VoiceAttack:
```
Start Loop : Repeat From 1 to 12
    Set Text [moduleName] to '{TXT:Ship compartment {INT:n} module}'
    Begin Condition : ([moduleName] Starts With 'Fighter' AND [{TXT:Status gui focus}] Equals 'role panel')
        Write [Blue] '{TXT:moduleName} found.' to log
        (Add additional actions here...)
        Loop Break
    End Condition
End Loop
```

**Comment by Noodles4Pasta** [comment]
All im getting for `{TXT:Ship compartment {INT:n} module}` is a bunch of "Not Set" parameters... Its not reading out the module in _ANY_ slot.

**Comment by Tkael** [comment]
Please 
1. run the EDDI.vap command `((EDDI: ship compartment variables))` to prove that the appropriate variables are being set.
2. revise your `Set Text` action to set the value as **Text** rather than as a variable.
3. give it another try.

**Comment by Noodles4Pasta** [comment]
Ok so ((EDDI: ship compartment variables)) generates all the stuff it is supposed to, but when i run it in that loop above it doesn't generate anything.

Also for what its worth, boolean values from EDDI are a pain as they cant be used on their own, because VA does not like ":" in the boolean T/F IF statement.

**Comment by Tkael** [comment]
Did you change your command per step 2?

**Comment by Noodles4Pasta** [comment]
That is setting a value as text. That’s what VA shows after the menu item has been chosen and completed.

**Comment by Corysia** [comment]
@Tkael helped me solve something like this earlier this year.  I was trying to determine whether or not I had a docking computer installed.  I learned that looping in Voice Attack is hidiously slow, so I wrote a C# script to search at **((EDDI ship loadout))**.  That will fire at different points in the game.

The following snippet sets a VA variable **bDockingComputerPresent** to true or false if any type of docking computer is present.  You can use it later for events like **((EDDI docking granted))**.

```
public class VAInline
{
	public void main()
	{
		VA.SetBoolean("bDockingComputerPresent", false);
		for (int x = 1; x < 20; x++)
		{
			if (VA.GetBoolean("Ship compartment " + x + " occupied").GetValueOrDefault())
			{
				if (VA.GetText("Ship compartment " + x + " module").Contains("Docking Computer")
				{
					VA.SetBoolean("bDockingComputerPresent", true);
					break;
				}
			}
		}
	}
}
 ```

This is my EDDI Docking Granted VA script:
```
Begin Boolean Compare : [bDockingComputerPresent] Equals True
    Press variable key(s) [edSetSpeedZero] and hold for 0.2 seconds and release
    Set Text [Script] to '[Initiating;starting;beginning;executing] automated docking [sequence;proceedure]'
    Execute command, '(( EDDI Plugin Say ))' (and wait until it completes)
End Condition
```

**Comment by Tkael** [comment]
I'm going to presume that this issue is resolved? Please indicate if otherwise.
