### ISSUE TITLE
I can not log into the frontier API EDDI v 3.5.2-b2

### ISSUE THREAD

**Issue by Msirike** [EDCD/EDDI#1650]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Please review similar closed issues and see if the guidance there helps in this case:
https://github.com/EDCD/EDDI/issues/1180
https://github.com/EDCD/EDDI/issues/1451
