### ISSUE TITLE
when attempting to use the mission route tool on this it will say.. Missions route calc .......then crashes

### ISSUE THREAD

**Issue by Msirike** [EDCD/EDDI#1651]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
I'm afraid we won't be able to do much without more information. We don't even know which version of EDDI you are using. Please fill in the details requested above and provide a log file from the crash (log files are located at `%appdata%/roaming/EDDI`).

**Comment by Darkcyde13** [comment]
I've just come across an exception error when trying to run RouteDetails().  It may or may not be related to what Msirike is experiencing.  I'll open a proper issue for it.

**Comment by richardbuckle** [comment]
Believed fixed with #1652, closing as duplicate.
