### ISSUE TITLE
Misspelled Numbers 

### ISSUE THREAD

**Issue by Droninator** [EDCD/EDDI#1653]
Hello, just a little something I noticed while scanning planets. 
When EDDI runs the "Bodies to map" function, 'three' gets pronounced as 'tree'.
I thought it was my voice pack at first, but after checking the output file I saw that EDDI was, in fact, saying 'tree'. After some testing, I found some other misspelled numbers, although they are pronounced understandably, so I do not know if this was done so intentionally.
Just something odd that doesn't break anything. Thanks for all the hard work!

## EDDI version in which issue is found
EDDI Version 3.5.1

## Steps to reproduce
1. Jump to a system you haven't done surface scans in.
2. Trigger the "Bodies to map" function.

## Expected
Expected to hear the following;
> Bodies alpha **three**, alpha eight, bravo two, bravo **three**, bravo **four**, bravo **four** alpha, bravo **five**, bravo six, bravo seven, bravo eight and bravo eight alpha are recommended mapping candidates.

## Observed
Heard the following;
> Bodies alpha **tree**, alpha eight, bravo two, bravo **tree**, bravo **fawer**, bravo **fawer** alpha, bravo **fife**, bravo six, bravo seven, bravo eight and bravo eight alpha are recommended mapping candidates.

## Investigation
Got the same result every time the "Bodies to map" function fires.
Checked against the speech responder output file.

**Comment by richardbuckle** [comment]
Thanks for the report!

These are the [official ICAO pronounciations](https://www.skybrary.aero/index.php/ICAO_Phonetic_Alphabet). If you don't want them, you can uncheck `Enable ICAO` in the `Text-to-Speech` tab:
![image](https://user-images.githubusercontent.com/227024/71549244-38146680-29b2-11ea-8d37-4797689d828a.png)

Hope this helps!

**Comment by Droninator** [comment]
Ah, I was unaware, thank you.
