### ISSUE TITLE
Latest beta seem to break speech tags for Cereproc voices

### ISSUE THREAD

**Issue by WonkoTheDane** [EDCD/EDDI#1655]
## EDDI version in which issue is found
v3.5.2-b2

## VoiceAttack version in which issue is found (as applicable)
v1.8.2

## Steps to reproduce
1. Select Cereproc TTS voice that supports speech tags - e.g. "Jess" or "Sarah"
2. Add speech tags to speech responder script - e.g.  `<spurt audio='g0001_004'>cough</spurt>`
3. Test script

## Expected
Cereproc voice produces a coughing sound and does not speak the tags themselves nor the enclosed word "cough". 

## Observed
Cereproc voice produces no coughing sound but speaks all tag characters ("less-than", "greater-than", "equals", etc.) including tag attributes and the word "cough". 

## Investigation
1. These tags worked as expected in previous versions of EDDI - e.g. v3.5.0 
2. It happens both in speech responder scripts and when sending speech scripts to EDDI from VA. 
3. speechresponder.out does not log the speaking of the tags but logs the word ("cough") enclosed in the tags.

**Comment by Tkael** [comment]
EDDI has never officially supported Cereproc speech tags. We recently revised Cereproc voice handling so that it would better support ssml but doing so may have broken those tags. I will investigate this.

**Comment by Tkael** [comment]
Other than `<spurt>`, are there any other special Cereproc tags that we'll need to consider?

**Comment by WonkoTheDane** [comment]
Sorry for the delay. Yes, apart from the `<spurt>` they have other specific non-ssml tags. Those include: 
1. a _variant_ tag: `<usel>` - example: `This is a <usel variant="1">test</usel> sentence.` (I use this a lot with a rand() value) 
2. an _emotion_ attribute with the voice tag: `<voice>` - example: `Today, <voice emotion='happy'>the sun is shining.</voice>` 

However, the emotion attribute seems to have no real effect on their Windows installed voices (in EDDI at least). More info and details can be found on page 23 in their user guide for their cloud-based voices. Link: https://www.cereproc.com/files/CereVoiceCloudGuide.pdf

**Comment by Tkael** [comment]
Thanks. I'm away from my dev pc for the next couple of days but I appreciate the response.

**Comment by WonkoTheDane** [comment]
Of course, Happy New Year! :-)

**Comment by richardbuckle** [comment]
Ping @Tkael @WonkoTheDane.

**Comment by Tkael** [comment]
I'm still planning to delve into this.

**Comment by WonkoTheDane** [comment]
If you need anything from me (testing, info, etc), please don't hesitate to ask. I will be happy to contribute in any way I can.

**Comment by Tkael** [comment]
I think I've got it.

FYI, you can use the `emotion` attribute in a `<voice>' tag in EDDI right now but it needs to be escaped and double quoted, e.g. `Today, <voice emotion=\"happy\">the sun is shining.</voice>`.

Once my PR is merged, you'll be able to use it exactly like it is shown in the Cereproc manual, e.g. `Today, <voice emotion='happy'>the sun is shining.</voice>`.

**Comment by WonkoTheDane** [comment]
Sorry for the delay again (was away). 
That sounds absolutely awesomely wonderful!! 

And may I also just take this opportunity to thank all of you guys for your outstanding contributions to the E:D community. Your work makes it an absolute joy to play E:D with EDDI and I couldn't imagine playing without it. So a very heartfelt thank you from Copenhagen, Denmark. :-)
