### ISSUE TITLE
Spacialise() doing something weird with a string for BodyDetails().

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1657]
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A
## Steps to reproduce
Use Spacialise() on a string and then use that string for BodyDetails().

## Expected
BodyDetails().bodyname to speak the correct body name.

## Observed
Nothing is spoken.

## Investigation
While working on my profile, I just tested out my VA command for more info on a body.  This supplies a body name to EDDI, and EDDI processes that to get a Body Report on the requested body.  I was having trouble with EDDI saying it didn't know what body I was talking about, however, this was working in the past, and I've made no changes to it recently.

I tracked the problem down to a line in my 'Body Info Request' script where the string passed from VA is put through Spacialise().  If I remove this one command, it all works again.  However, I do need the string to be spaced out sometimes, so Spacialise() is important.

So, I've done some further testing.....

Using the following code to test:

```
{set body to "4"}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
Name: {BodyDetails(body_id, system).bodyname}.
```

Any system and body will do, these are just the ones I'm near at the moment.
This results in "Name: Eol Prou KW-L c8-75 4."

Now, if I add the following line:
`{set body to Spacialise(body)}`

Like this:

```
{set body to "4"}
{set body to Spacialise(body)}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
Name: {BodyDetails(body_id, system).bodyname}.
```

This results in "Name: ." and nothing else being spoken.  Spacialise seems to do 'something' to the "4" that makes BodyDetails() not recognise it.

Taking this a step further, I've changed the body to be "4 b".  Without Spacialise(), BodyDetails() works as expected again, saying "Eol Prou KW-L c8-75 4 b".

However, and this is where it gets weird, adding back the Spacialise() results in nothing from BodyDetails(), but if I add a `{body_id}` line, this results in "Eol Prou KW-L c8-75 4spaceb".  The space is litterally spoken as "space", even though the log output shows "...4 b"

This is the code in full:

```
{set body to "4 b"}
{set body to Spacialise(body)}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
{body_id}.
Name: {BodyDetails(body_id, system).bodyname}.
```

Whatever Spacialise() is doing to the string, it's stopping BodyDetails() from working.  Whatever it's doing, it's also affecting a single character string.  And why is the space being voiced as "space"?   Is there anything that can be done to correct this?

Hope you can help.

**Comment by Tkael** [comment]
The {Spacialise()} function was recently updated to wrap the string in an ssml tag (which is more effective then simply spacing and upper casing the string for providing correct pronunciation). You should be able to observe this in speechresponder.out if you write the speech responder output to a file.

**Comment by Tkael** [comment]
I would recommend minimizing use of `{P()}`, `{Spacialise()}`, or other functions that can transform the string until after you've completed your `{BodyDetails()}` lookup.

**Comment by Tkael** [comment]
As for the spoken "space", results may vary from voice to voice. Which voice are you using?

**Comment by Darkcyde13** [comment]
Ah, OK, that makes sense then.  I must admit I rarely use Spacialise() much, so I hadn't noticed anything strange before.  I'm using the Ivona Amy voice.

I do have everything written to the speechresponder.out file, just so when unexpected things happen, I can take a look.  However, I can't see any difference between the version put through Spacialise(), and the raw version.  Every instance in the output file looks like this "Eol Prou KW-L c8-75 4 b" (whether the "4 b" is put through Spacialise(), or not).  I had even tried using dump() to see if there was anything else going on, but that also didn't show any differences.  That's mostly why I opened the issue, because I can't see anything different between the two.  Even when the word 'space' was spoken between the 4 and b, the file only shows "...4 b".

I did make my own version of Spacialise() a while ago, when the function wasn't working right (it was adding an additional space to the end of the string), so I can just put that back in place in my script to do what I need.

Thank you for the info though. :)

**Comment by Tkael** [comment]
So as discussed, here's how I would rearrange your test code to move `Spacialise()` to the point of vocalization:
```
{set body to "4 b"}
{set system to "Eol Prou KW-L c8-75"}
{set body_id to cat(system, " ", body)}
{body_id}.
Name: {Spacialise(BodyDetails(body_id, system).bodyname)}.
```

I've investigated the "space" that you observed and have identified a fix for that. PR incoming. :-)

**Comment by Darkcyde13** [comment]
Ah, cool, thanks for looking into it. :)

I totally agree with your solution to the test script, however I don't think that will work with what I'm doing in my 'Body Info Request' script.

The script takes a variable passed by VA, and VA gets that by the user specifying which body to get more info on.  As VA can interpret a voice command in various ways, I'm having to make sure it's formatted correctly for BodyDetails() to accept.  Thus I need to make sure that anything after a number is spaced out before it is used by BodyDetails().

So as an example, the user can say "Tell me about body 4 b".  VA strips out the first part, leaving the "4 b", but in doing so, it may send "4b" or "four B" or "four b", and so on.  My EDDI script then makes sure it's "4 b", ready to be added to the system name for BodyDetails().  The whole body/system variable is then setup to be ready for the "Body report" script.  This is why I needed the Spacialise() part before it goes to BodyDetails().

Just thinking about this now has given me a little idea.  I know Spacialise() takes one argument of the string to space out, but how much of a pain would it be to add a second argument, one that could (if set) drop the use of SSML tags and just space out the string by adding spaces between letters?  I know it would almost certainly be slower, hence defaulting to the SSML version, but in cases like mine, where the tags interfere with what I need to do, the small speed loss would be acceptable.  What are your thoughts on that?

As things stand at the moment, I have a working solution for my needs, and so far it's only been for this one situation.  So I'll fully understand that you probably won't want to make something that could see minimal use.  It was just an idea and suggestion. :)

**Comment by Tkael** [comment]
It's certainly possible to force the old behavior. I'll consider it.

**Comment by Tkael** [comment]
Another option you might consider would be to adjust the VoiceAttack command phrase. If the command phrase is looking for something like `[4][b]` rather than `*` then that will improve recognition while giving you a more consistent input.

**Comment by Darkcyde13** [comment]
I have to say a big thank you Tkael, while I already do check for [1..9], your comment prompted me to take a deeper look at my VA command.

It turns out I had made a tiny typo.  While removing the initial speech to leave just the body name, I had forgotten to make it also remove the space between that speech and the body name.  So VA was sending " 4 b" to EDDI instead of just "4 b".

Also, it's been a while since I first wrote the command, and I've played about with in the mean time.  At some point I must have changed it over to use [1..9], thus eliminating the need to convert numbers from words.

It's all now allowed me to re-write my EDDI script, making it more efficient, and also removed the need for spacialising anything.  It's about 2/3 the size of what it was.

So thank you again, and you can close this if you want to, unless you still want to add that optional to Spacialise().  :)

**Comment by Tkael** [comment]
Excellent. I think I'll go ahead and close this one. :-)
