### ISSUE TITLE
EDDI Crashes when docking at station or entering game - only some stations (50%)

### ISSUE THREAD

**Issue by TROG111** [EDCD/EDDI#1658]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
EDDI seems to crash midway through speaking when I dock at certain stations (or when i enter the game at those stations).  It does not happen at every station, about 50%.  And the stations it happens to seem to change each day, but are reproducable on that specific day (happens every time then).  Currently it is happening to me at Arnold Hub in Convoumia and is reproducable.

When EDDI crashes it take VA with it, though I can get it to also crash when VA is not running (hence I have marked VA as N/A)

## Expected
Shouldnt crash ;-)

## Observed
Crashes and process dies

## Investigation
It has been happening in the last two beta but I didnt report it as I though it was VA crashing and not EDDI.  But now I have tested without VA and see it is EDDI that has the problem.

**Comment by Hoodathunk** [comment]
Please attached 'verbose' logs, showing the 'crash'.

**Comment by TROG111** [comment]
I can't find the log. I put verbose on, but there is no zip file create on 
my desktop.

I have used eddi for 3 years and not had this problem until the last two betas.

**Comment by TROG111** [comment]
since Ive had verbose on it hasnt crashed ;-(

**Comment by Tkael** [comment]
Ok. Please navigate to `%appdata%\roaming\EDDI`. Zip up all of the files ending with the extension `.log` and attach them to this issue.

**Comment by Tkael** [comment]
It's likely that the crash was something specific to your game session. Looking at your logs will still provide the best chance for us to identify the issue.

**Comment by TROG111** [comment]
Log files uploaded as requested
[EDDI.zip](https://github.com/EDCD/EDDI/files/4011974/EDDI.zip)

**Comment by Tkael** [comment]
You seem to have a corrupt database. 
Please navigate to `%appdata%/Roaming/EDDI` and (while EDDI and VoiceAttack are not running) delete `EDDI.sqlite`.
Once deleted, restart EDDI and VoiceAttack then check for crashes again.

**Comment by Tkael** [comment]
I'm unable to determine what may have happened to corrupt your database so I'm going to mark this issue as resolved. Please reply to this issue if you experience additional crashes after deleting `EDDI.sqlite`.
