### ISSUE TITLE
Variables not set on game start

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1659]
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Start a game while in an SRV.

## Expected
Variables `{event.startlanded}` and `{status.vehicle}` to be populated.

## Observed
Both variables are empty (null?).

## Investigation
I loaded up a game while in my SRV, and I have code that stops the reporting of 'Touchdown' for my ship if I'm in the SRV.  However, this now doesn't work.

So, I copied the default EDDI profile and added the following lines into the Commander Continued script:

```
Start Landed: {event.startlanded}.
Vehicle: {status.vehicle}.
```

These are the variables I was checking in my personality.  When I start my game, these lines say:
"Start Landed: ."
"Vehicle: ."

I can understand if the vehicle isn't set right at the start of a game, but 'startlanded' is part of the Commander Continued script, so I would expect that to be set to True.

If I quit to main menu and load again, then the vehicle is set correctly to SRV, so I guess this is being done after the Commander Continued script is executed, and remains set when exiting and restarting the game.  Although quitting to desktop and reloading (leaving EDDI loaded) vehicle is reset to nothing.

**Comment by Hoodathunk** [comment]
Dude, you know the drill.

eddi log, the journal 'LoadGame' event, etc.

**Comment by Hoodathunk** [comment]
FWIW, those values are not set by the `CommanderContinued` event in EDDI, so the journal event data may not be useful.

**Comment by Darkcyde13** [comment]
Yeah, sorry. I was in a hurry as I needed to go out. :/  While I was out, it occurred to me that startlanded may only apply when you are in your ship, rather than in your SRV, even when the ship is landed nearby.  Apologies if that's the case, although one of the two variables must have been set in the past, or my script would never have worked back then (it's been a good couple of months since I last tried this part out).

Here's my log and Journal:
[eddi.log](https://github.com/EDCD/EDDI/files/4011063/eddi.log)
[Journal.191230211431.01.zip](https://github.com/EDCD/EDDI/files/4011083/Journal.191230211431.01.zip)

**Comment by Hoodathunk** [comment]
Thanks, bro.

**Comment by Darkcyde13** [comment]
I just thought I'd let you know, I've just tried loading while landed in my ship, and 'startlanded' is still blank.

**Comment by Hoodathunk** [comment]
Check the accompanied `LoadGame` journal event. Is `startlanded` present? If not, then It's a FDEV problem. We can only read what's there.

**Comment by Darkcyde13** [comment]
Oh yeah, you're right,  That copy of the log doesn't have startlanded in it.  Strange, because I've looked through other ones I have, and they do have that in.

So, I've just tried again.  Same procedure: start EDDI with the test personality, turn on verbose logging, start Elite, log into game.  This time I'm in my ship.  Those extra lines I added to Commander Continued still say nothing for those variables (although you've already explained the vehicle one).  

I've checked the Journal, and this time it does have the startlanded entry, which is set to true, so it should have populated the event.startlanded variable.

[eddi.log](https://github.com/EDCD/EDDI/files/4011356/eddi.log)
[Journal.191230225245.01.zip](https://github.com/EDCD/EDDI/files/4011357/Journal.191230225245.01.zip)

**Comment by Darkcyde13** [comment]
Well, I tried it out a few times, but 'startlanded' never showed up in the Journals.

Looking back over the last twenty or so Journals, it seems that 'startlanded' appears between 'fuelcapacity' and 'gamemode' in the LoadGame event, but only if you're in your ship, other wise it's not written to the Journal at all, not even if it's 'false'.

I guess, since I last tried this out, FDev must have removed it, or made a mistake meaning it now only appears if you're in your ship.  I'd err on the side of a mistake, because when loading in your SRV, there are still entries for fuel that are zero.  If they wanted to write less to the Journal by removing startlanded, then I would have thought that they would also remove the redundant fuel entries?  Maybe?  I dunno…

Well, anyway, you've helped me see what's going on, and why my script no longer works, so thank you for you help. :)
