### ISSUE TITLE
Add an event to indicate deployment or retraction of the hardpoints

### ISSUE THREAD

**Issue by danielRicardo** [EDCD/EDDI#1661]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
N/A

## Expected
There should be an event triggered whenever the status monitor detects a change in the hardpoints status, just like we have for the landing gear for example

## Observed
This event is missing

## Investigation
I will be happy to add this event myself. In fact, I have already written most of the code for it, so if you feel like this event should indeed exist, I will create a PR.

**Comment by Hoodathunk** [comment]
Can you give a compelling use case that is not covered by existing code?

**Comment by danielRicardo** [comment]
Well, first of all - if someone wants to have a speech response when the hardpoints are deployed - just like they can do for the landing gear or cargo scoop.
However, this actually came up as a part of a bigger project I had in mind - creating a `Serial Port responder` for EDDI, which will allow people to build custom physical cockpit panels

**Comment by Tkael** [comment]
We don't want to be too verbose around combat scenarios but we do have speech priorities to help with that now and I can see some VoiceAttack users potentially wanting to adjust pips or select a target when hardpoints are deployed / retracted. 

If you choose to submit a PR, the variable used in the event should (ideally) carry the same name and value as the `status` object property to keep things as clear and as consistent as possible.

**Comment by danielRicardo** [comment]
That sounds reasonable enough - I will submit a PR later today or tomorrow.
Thanks!

**Comment by danielRicardo** [comment]
PR submitted #1670
