### ISSUE TITLE
Inserting {event.station} in the "Docking requested" script causes a crash

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1664]
## EDDI version in which issue is found
EDDI v.3.5.2

## VoiceAttack version in which issue is found (as applicable)
Vois Attack V1.8.2

## Steps to reproduce
Edit/open the "Docking requested" script.
Entering the characters "{event.station}". Execute the test.
Crash

## Expected
I wanted EDDI to say which station the request goes to.

## Observed
EDDI crashes, no matter if as plugin from VA or stand alone.

## Investigation
This text (german) works without problems:
{OneOf("Andockerlaubnis erbeeten",
       "Kontaktiere Station",
       "Kontaktiere Stationspersonal",
       "öffne Kanal",
       "öffne Kanal zur Station", 
       "Anfrage ist raus",
       "Aye {F('Honorific')}")}

**Comment by Hoodathunk** [comment]
Confirmed. Only occurs when testing script in speech responder window. Committed a hotfix for next update.

**Comment by nepomuk16321** [comment]
Thanks guys, you're great!

**Comment by Tkael** [comment]
We should keep this open until @Hoodathunk submits his PR and it is merged. 😉

**Comment by nepomuk16321** [comment]
Sorry, my bad, wrong button pressed .

**Comment by Tkael** [comment]
Nothing to apologize for.

**Comment by richardbuckle** [comment]
Hey, @Hoodathunk, is that hotfix/1664-docking-request-exception ? I think you forgot to create the PR.

**Comment by richardbuckle** [comment]
Fixed by #1673.
