### ISSUE TITLE
7.1 speakers. EDDI centre output, VA left and right output.

### ISSUE THREAD

**Issue by Alan-fx8150** [EDCD/EDDI#1667]
## EDDI version in which issue is found
v.3.5.2

## VoiceAttack version in which issue is found (as applicable)
v1.8.2

## Steps to reproduce
1. Enable 7.1 analogue sound (I'm using an Asus Xonar D2X)
2. Set sound card as the windows 10 default sound device. 
3. Have it set with EDDI, VA, ED etc. 
4. Disable all unused devices.

## Expected
Both VA and EDDI to output voice through the same speakers.

## Observed
VA output is through left and right, whereas EDDI is output through centre. 
I can't see a way to align them either way. 
I'd be happy for both to be left and right or both as centre. 
It sounds strange / immersion breaking when they're coming through different speakers/channels (same device as mentioned above).

## Investigation

- I've been through the EDDI options and VA options, searched online for a few days. 
- Looked through my soundcard, forums, google and then used discord to contact HCS. 
- They recommended using something like upmix but the trouble is, I guess a universal solution would downgrade my speaker output for other applications such as ED. 
- Here's my soundcard to show there isn't a way to split speaker channel per application (as that seemed to be what I thought HCS were suggesting in discord)
- ![Xonar D2X](https://user-images.githubusercontent.com/56416336/71754558-98a61680-2e7e-11ea-833f-c45743af0851.gif)
- I assume for a solution along those lines but instead, _I might need something to separate ED, EDDI and VA so ED still comes through 7.1, then EDDI and VA both come through left and right or centre._ 
- Alternatively, perhaps there's a file I can edit to specify the speaker channels used for the device? 
- Or do you have any other suggestions please?

Many thanks.

**Comment by Tkael** [comment]
I've taken a stab at updating EDDI to utilize all available channels (or at least stereo channels) with surround sound systems, though my ability to test this is limited since I currently do not use a surround sound system.

**Comment by Alan-fx8150** [comment]
Oh cool, thanks a lot Tkael.
Is there a way I could mirror the fix from my side and report back on the findings? 
I have an app which shows me a visual representation of which speakers are being used so it'll be easy to quickly see. Thanks, Alan

**Comment by Tkael** [comment]
Please try the attached alpha build and report back.
[EDDI-3.5.3.a1.exe.zip](https://github.com/EDCD/EDDI/files/4022442/EDDI-3.5.3.a1.exe.zip)

**Comment by Alan-fx8150** [comment]
Thanks Tkael.

I can confirm the sound is output through all channels but it is very quiet. It was on 90% before but even at 100%, the system volume has to be twice what it was before. It sounds deeper but that could be as it's coming through subs now as well as the directional speakers.

Thanks again for your time and support. I'm sorry to say that when I turn up the volume, I think it sounds worse coming from everywhere rather than centre (EDDI) or left and right (VA) but it's probably made worse as I can hear it through the subs. 

Sorry this is a difficult one. I take it there's no way to force it through just left and right please?

**Comment by Tkael** [comment]
Since I can't test directly, I'm not that surprised that the first test wasn't completely successful (though it does seem that I'm pulling some of the right levers, which is promising).

The Wikipedia entry on [surround sound](https://en.wikipedia.org/wiki/Surround_sound) states:
>The function of the center channel is to anchor the signal so that any central panned images do not shift when a listener is moving or is sitting away from the sweet spot.[27] The center channel also prevents any timbral modifications from occurring, which is typical for 2-channel stereo, due to phase differences at the two ears of a listener.[24] The centre channel is especially used in films and television, with dialogue primarily feeding the center channel.[25] The function of the center channel can either be of a monophonic nature (as with dialogue) or it can be used in combination with the left and right channels for true three-channel stereo. Motion Pictures tend to use the center channel for monophonic purposes with stereo being reserved purely for the left and right channels. Surround microphones techniques have however been developed that fully use the potential of three-channel stereo. 

It's much more typical for dialogue to originate from the center speaker rather than from left and right in a surround sound system. We'd be breaking with that convention a bit, but I can see a case for doing so since we're trying to simulate the ship. Thoughts?

I'm using a prepackaged channel matrix to convert from mono (which appears to play from your center speaker to 7.1 surround). My understanding is that the sound is attenuated when you have multiple speakers so as to not overwhelm the user, so I expected that you might need to play with the volume and channel mix a bit. 

I can give it another try where we simply convert mono to stereo. Please test and report back.
[EDDI-3.5.3.a2.zip](https://github.com/EDCD/EDDI/files/4023982/EDDI-3.5.3.a2.zip)

**Comment by Alan-fx8150** [comment]
Thanks a lot Tkael, that's very interesting.

I wonder why HCS decided to use left and right for their voice output. I have a feeling I might be better to continue trying to get their output through the mono centre channel so it lines up with EDDI (like I had tried before raising this support request but didn't get anywhere with them). Knowing computers (I'm a Snr QA Engineer but not a dev like yourself mate), normally if it's possible, there must be a way!

Thank you for the revised alpha build. It's definitely louder than 3.5.3.a1 but is quieter than mono channel 3.5.1 (more info at the end).

There isn't much play with the upmix for speaker levels unfortunately  and you might not need to know any of this, but just to explain the reason with the speaker set up I'm using: 
![image](https://user-images.githubusercontent.com/56416336/71815049-1b44f680-3076-11ea-9138-5b0918b1b83e.png)
**Front L&R** 
- (5.1) L&R channel of Logitech z506
- (2.1) a cheap system called Bass Pulse for it's blue LEDs lol.
- Haptic feedback Kor-FX Vest.

**Centre/Sub** 
- (5.1) centre/sub channel of Logitech z506
- 15" active sub 
- Bass transducer feedback from Subpac M2.

**L&R**
- Panasonic quad hifi with 2 speakers left and two for right

**Rear L&R**
- (5.1) Rear L&R channel of Logitech z506
- Bass transducer feedback from Subpac S2.

It's a nightmare to explain but it's not as complicated as it might sound. Basically, each system has it's own independent volume which I keep set between around 50%-75% to make sure they're all in line and never 'red-lining' it. The PC volume is usually on about 16% but even when it's on 100% playing music (barely, barely ever that high in the last couple of years), then the max volume for anything is 75% so nothing get's blown/broken.

After explaining that and to give approximate levels to what I said near the top:
- With 3.5.1 on 16%
- Then 3.5.3.a2 needs to be on about 24% to sound similar
- Prev  3.5.3.a1 needed to be on about 43%

I think I just need to find a way to sort the issue from the VA side and to leave EDDI as centre from what you shared, thank you Tkael. That seems the most logical thing and was what I was trying at first too. I guess there must be an application somewhere which does it. If you hear anything, would you mind keeping me in mind please mate. 

Many thanks, Alan

**Comment by Tkael** [comment]
There's a good chance that you'll need to go through VoiceAttack's dev rather than through HCS. As far as I know, HCS simply uses the VoiceAttack `Play sound` command. VA's dev is a good guy, we've troubleshot some issues together in the past.

**Comment by Tkael** [comment]
Closing as resolved for our part.
