### ISSUE TITLE
Missing tags in interface

### ISSUE THREAD

**Issue by jmanwich** [EDCD/EDDI#1676]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
VoiceAttack Not running

## Steps to reproduce
1. Tabs/Functions of EDDI missing
2. Notifications from EDDI stopped a couple of weeks ago but I've only been able to start trying to look into the issue today. When I opened EDDI, I noticed that several tabs are missing from the interface (see attached image linked below)

## Expected
Buttons on left to all be present and accessible

## Observed
Only tabs showing on the left side of the interface are "EDDI", "Commander Details", "Frontier API" and "Text-to-Speech"

See image

## Investigation
Closed and re-started EDDI
Closed EDDI and started VoiceAttack then opened EDDI through the "configure EDDI" command
Shut down and restarted the computer
Searched documentation and past tickets for similar issues
Uninstalled and re-installed EDDI 3.5.1
Successfully updated to EDDI 3.5.2 through the application
Closed and restarted EDDI
Closed EDDI and started VoiceAttack then opened EDDI through the "configure EDDI" command
Shut down and restarted the computer
Uninstalled EDDI, downloaded 3.5.2 directly from GitHub and installed from the new download
Shut down and restarted the computer
Uninstalled EDDI & VoiceAttack, deleted VoiceAttack folder from program files folder, shut down and re-started, re-installed VoiceAttack (without Singularity or voice packs), re-installed EDDI, re-installed voice packs and singularity
created ticket.

I'm really hoping there is some option that I can simply enable or disable to get this working again but I haven't been able to locate any such option in the program or in the documentation.

![2020-01-10 - EDDI Interface](https://user-images.githubusercontent.com/59752000/72198748-496c6280-33f7-11ea-9aac-f4178649cf99.jpg)

**Comment by Darkcyde13** [comment]
Try deleting the EDDI folders from your Appdata Local and Roaming folders, as per this post from Urban-Nutta, from ticket #1552.  Obviously this will wipe any settings you have configured, but I'm guessing it's something like a corrupt setting entry that's possibly causing it anyway.

"Hi i tried an uninstall /remove program and re installed , this did not work, so i then deleted the EDDI folder in app data ( local and roaming ) ran the exe install file and this seems to have resolved the issue i am now seeing all tabs on the left hand side now , thank you for your replies o7"

**Comment by jmanwich** [comment]
That must have been it. Thank you!
