### ISSUE TITLE
Material scripts crash when activated by the test button

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1677]
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Without Elite loaded, click the Test button for:
Material discard report
Material inventory report
Material location report
Material required report

## Expected
The scripts report what can be discarded or are required, etc., or a test string variation of them.

## Observed
EDDI will crash to desktop.

## Investigation
I was going through the personality with Notepad, looking for scripts with plural IF statements, when I noticed that there appeared to be duplicated (or almost identical) script names.  I went to see if they reported the same thing, so I clicked the test buttons, and that made EDDI CTD.  After the first crash, I tried the other materials reports to see if any others did the same.

As for the duplication, I thought 'Material discard report' and 'Materials discard report' were the same thing (likewise for the '...required...' reports), but then realised one is for a single material, and the other is for all materials.  It was just the very similar names that confused me.

Here's my log for one instance of trying 'Material discard report'.  I loaded EDDI with the default personality, enabled verbose logging, and then clicked the test button.
[eddi.log](https://github.com/EDCD/EDDI/files/4050962/eddi.log)

Let me know if you need anything else.

**Comment by Tkael** [comment]
Replicated. It's crashing because of a null value exception.

**Comment by Tkael** [comment]
FYI, these are scripts that are typically only triggered from VoiceAttack commands for a specific material.
