### ISSUE TITLE
[Question] Fighters states.

### ISSUE THREAD

**Issue by bronney** [EDCD/EDDI#168]
Dear devs,

I am doing a VA commands for fighters and noticed there's no states that tracks when a launched fighter dies in combat.  The Fighter launched and docked command is handy only if the fighter survives and dock.  But if it dies in space, there's no way to tell who's controlling what.  So the controlling ship or fighter event is borked if the fighter dies.

Any solutions?

EDIT: To make it more precise, if you launch a fighter to fly yourself, your {TXT:Vehicle} will be Fighter.  Now if you die, you will be in your ship, but the {TXT:Vehicle} is still Fighter.  That's the problem.

**Comment by Tkael** [comment]
There is no direct "Fighter destroyed" event. Is there a "hull damage" event that triggers at zero hull, and could that be used as a proxy?

**Comment by bronney** [comment]
Ok I tried but I don't know how to set {TXT:Vehicle} to Ship after the SRV explodes.  Btw SRV has the same problem.  Can you help with below?  How can I set EDDI var to a certain value?  In this case, back to "Ship".  The below exist in the ((srv launched)) event.

Set small int (condition) [launched-vehicle-death] value to 0
Start Loop While : [launched-vehicle-death] Equals 0
    Set small int (condition) [launched-vehicle-hull] value to the value of [{DEC:EDDI hull damaged health}]
    Begin Condition : ([{TXT:EDDI hull damaged vehicle}] Equals 'SRV' AND [launched-vehicle-hull] Equals 0)
        Set small int (condition) [launched-vehicle-death] value to 1
        Set Text [{TXT:Vehicle}] to 'Ship'
        Set small int (condition) [srv] value to 0 (save value to profile)
    End Condition - Exit when condition met
End Loop

**Comment by Hoodathunk** [comment]
Unfortunately, EDDI variables only go one way... From EDDI to Voice Attack.

The one exception to that rule are 'state variables', but they are restricted to communication between 'speech responder' scripts and Voice Attack. There is presently no way for Voice Attack to manipulate journal and API related variables.

Best we can do for the present is investigate a work-around inside EDDI until FDEV generates a 'Fighter Destroyed' journal event, which IMO would be the best outcome.

**Comment by bronney** [comment]
Oh boy, time to redo the if's.. thanks anyway guys.

**Comment by bronney** [comment]
Guys, I had to reopen this as I found something weird.  I use the below to track destruction of launched vehicles (SRV, Fighters) so that it'll set my [ship] var back to 1 when they died when I was in one.

`Set small int (condition) [launched-vehicle-death] value to 0
Start Loop While : [launched-vehicle-death] Equals 0
    Set small int (condition) [launched-vehicle-hull] value to the value of [{DEC:EDDI hull damaged health}]
    Begin Condition : ([{TXT:EDDI hull damaged vehicle}] Equals 'SRV' AND [launched-vehicle-hull] Equals 0)
        Set small int (condition) [launched-vehicle-death] value to 1
        Set small int (condition) [srv] value to 0 (save value to profile)
        Set small int (condition) [ship] value to 1 (save value to profile)
        Set small int (condition) [fighter] value to 0 (save value to profile)
    End Condition - Exit when condition met
End Loop
`
And I use the command "say {DEC:EDDI hull damaged health}" to track the hull health.  My SRV just died but the {DEC:EDDI hull damaged health} is at 19.  It should be 0.  And hence my while loop didn't end and it thinks I am in an SRV still.  Can you investigateplease?  Is it lag?

**Comment by Hoodathunk** [comment]
It's been my experience in studying this issue (trying to do what you're doing), that you seldom get that final 'hull damage = 0' event, so you can't use hull damage as a work around for the lack of a 'FIghter/SRV destroyed' event.

Until FDEV corrects this, we will continue to have this hole in the Fighter/SRV 'life-cycle'.

**Comment by bronney** [comment]
Thanks dude.  It's nice hearing from the pros so I can sleep easy.  closing it.

**Comment by Tkael** [comment]
We don't get a continuous number on Hull health from the player journal. Rather, a new journal event is created after each 20% Hull loss. Thus dropping from 19% to 0% could happen without a new journal event firing and without that journal event EDDI had no other way to know about the Hull loss

**Comment by bronney** [comment]
Yes I noticed that while testing also.  Must be a measure to reduce lag on their side.  I put in a new command in VA to set the vars back when kicked back in ship.  But as we know it's not optimal as the {TXT:Vehicle} will report SRV until a entered supercruise or jump event.  It's all good here it only bugs "us" hehe.

**Comment by Tkael** [comment]
Once again, this comes back to the same missing journal event. You may wish to create a bug report to Frontier to request they fill this hole.

EDDI currently updates the variable {TXT:Vehicle} whenever your vehicle (fighter or SRV) is docked or launched (since we have journal events for each of those occurrences), but it cannot currently detect when your vehicle is destroyed.

**Comment by bronney** [comment]
See somehow I think we will be very good friends in real life as we are thinking of the same thing so often.  I was just about to file this to Frontier.  It's great the community has the team from EDDI you guys really care and respond to the make the game better.
