### ISSUE TITLE
EDDI will not run after finding undiscovered system

### ISSUE THREAD

**Issue by cdspace** [EDCD/EDDI#1680]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A, not installed

## Steps to reproduce
Try to run it? This must be specific to me (see logs below) it crashed when I visited an undiscovered system.

## Expected
Expect EDDI to run

## Observed
EDDI shows up in Task Manager when trying to run, goes up to about 30 Mb memory, then just exits

## Investigation
Looked into the logs. Something related to a previously undiscovered system, it reads my ED logs, and then crashes on a system description. Since no one has ever been to this system, it must be related.

EDDI:eventHandler EDDI core failed to handle event Body scanned [ -big JSON system desc- }
EDDI:eventHandler EDDI core failed to handle event Body scanned System.Collections.Generic.Dictionary`2[System.String,System.Object

[eddi.log](https://github.com/EDCD/EDDI/files/4051749/eddi.log)

**Comment by Tkael** [comment]
Have you tried running EDDI since the crash? Is it still crashing or is it ok now?

**Comment by richardbuckle** [comment]
From the logs, I suspect that your home system as recorded in `eddi.json` might be corrupted. Could you please, while EDDI and VA aren't running, try renaming `eddi.json` to `eddi.json.bak` and re-launching?

**Comment by cdspace** [comment]
I ran it several times after the first crash, got the same thing in the logs each time...
I renamed 'eddi.json', and now it's running again...

**Comment by cdspace** [comment]
I tried putting `edsm.json` back to the original filename, renamed `eddi.json` and it ran okay. I out everything back to the original filenames, and it's running fine now. I have all EDSM and Inara updating turned off. I use EDMC to update EDSM. Looking at the stack trace, I'm wondering if EDDI was trying to pull system data from EDSM before EDMC could send it's updates? Just a thought... anyway, it's working now. I can upload more log files if you want, or just close out this issue.

**Comment by richardbuckle** [comment]
Thanks again for the report. I think we can close this now as being a glitch, but we will keep it in mind.
