### ISSUE TITLE
New personality can crash if malformed file exists

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1685]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Create an empty file called "bad.json" in `%APPDATA%\EDDI\personalities`.
2. Launch EDDI and attempt to duplicate the default personality with a name of "bad"

## Expected
EDDI behaves gracefully, e.g. warns you that the name is taken.

## Observed
Crash to desktop from uncaught exception.

## Investigation
Upon investigation, supplying an existing name for a well-formed JSON is not handled as I would expect: it is overwritten without warning.

**Comment by Tkael** [comment]
Wow. Well, that's certainly a problem. :-D
