### ISSUE TITLE
Cottle version is out of date

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1687]
## EDDI version in which issue is found
3.5.3

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Visit https://github.com/r3c/cottle and note the release number
2. Visit the recently revised Cottle documentation page at https://cottle.readthedocs.io/. Note that the documents there (with the exception of the update guide) only describe the latest version and not version 1.4.0.4 (the version EDDI currently uses).

## Expected
Cottle documentation available on the internet matches EDDI's implementation

## Observed
Differences may develop since EDDI is using Cottle version 1.4.0.4 while the latest stable release is 1.6.0.

## Investigation
Cottle version 1.4.0.4 was the last version prior to Cottle rolling to a requirement for .Net version 4.7.2. Updating would require 
1. Retargeting from [.Net version 4.7.1 to 4.7.2](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.1-4.7.2).
2. Updating the Cottle package and following [the documented versioning update guide](https://cottle.readthedocs.io/en/stable/page/07-version.html#update-from-previous).

**Comment by Tkael** [comment]
I intend to work on this once #1682 is merged.

**Comment by richardbuckle** [comment]
We are currently on the latest version of Cottle that allows us to write functions that re-parse string arguments using the live context. If we need to update then we would have to persuade the Cottle maintainers to add explicit support for this. We are their second largest open-source consumer on GitHub so that might be possible.

**Comment by Tkael** [comment]
Resolved in 4.1.0-b1.
