### ISSUE TITLE
EDDI throws an error when Voice Attack Starts stating: Unable to fully initialize EDDI, some functions may not work.

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1690]
V3.5.2

EDDI throws an error when Voice Attack Starts stating: Unable to fully initialize EDDI, some functions may not work.

When I close VA and open EDDI, only four items show up.
1) EDDI
2) Commander Details
3) Frontier API (which is connected)
4) Text-To-Speech

I have uninstalled and reinstalled EDDI. It makes no difference.

It was working a few days ago, and then I ran Elite CQC and when I went back to regular Elite Horizons, this started. I also did a System Restore of Windows back to 01/07.2020, which was the last restore point before I noticed this. No difference.

Any suggestions

**Comment by Tkael** [comment]
It looks like EDDI encountered an exception while it was loading. Please share a copy of your log files, saved to `%appdata%/roaming/EDDI`?

Once you've done that, I would recommend restarting Elite and logging into a new session. If there was a problem with the data from your prior journal file, this may be enough to clear it. If not, follow the steps at https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup.

**Comment by Tkael** [comment]
Please also specify the method you used to launch Elite CQC. Did you launch `Elite Dangerous Arena` directly from the launcher or did you select CQC from the normal in-game menu?

**Comment by incryptx** [comment]
Ok, I found the troubleshooting section of your website, and although the instructions were in error, I managed to resolve the problem by removing files from %Appdata%\UserProfileName\Local and Roaming.

In your troubleshooting instructions where you state to copy the files out of %AppData% you missed the correct path for this, which should be either
1) %Appdata%\UserProfileName\Local\EDDI (or)
2) %Appdata%\UserProfileName\Roaming\EDDI

But I figured that was what you were referring to and deleting those files fixed it.

As to what caused it in the first place, It may have been launching "Elite Dangerous Arena" from the main menu. Why this happened, I have no clue, but if I use CQC (Elite Dangerous Arena) again, and EDDI does the same thing, I will report it. 

As to the EDDI logs, they were in the %Appdata% directory I deleted before I can here and read the messages. Sorry.

**Comment by Tkael** [comment]
`%AppData%\EDDI` opens `%Appdata%\UserProfileName\Roaming\EDDI` when you paste it into the Windows file explorer. ;-)

Without logs, I'm afraid there's little we can do to investigate at this point. I'll close this issue for now but it recurs then please let us know and send us those logs. :-D

**Comment by incryptx** [comment]
Will do. I suspect that playing CQC may corrupt the journal files with then prevents EDDI from functioning.

**Comment by Tkael** [comment]
Possibly, though I jumped onto a match this evening (launching into Elite Dangerous Areana from the launcher) and when I later tried to open EDDI it opened without issue.
