### ISSUE TITLE
close

### ISSUE THREAD

**Issue by Jessebob42** [EDCD/EDDI#1694]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Why was this opened? The ticket is empty.
