### ISSUE TITLE
StarScannedEvent missing alreadydiscovered etc

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1696]
This stems from [this forum post](https://forums.frontier.co.uk/threads/eddi-scripts-and-eddi-enabled-va-commands-thread.311614/post-8275863). 

1. Review the `Scan` journal event (journal doc para 6.3) [around line 837](https://github.com/EDCD/EDDI/blob/develop/JournalMonitor/JournalMonitor.cs#L837).
1. Add debug-level logging of fields that are not added to the `StarScannedEvent`. 
1. Add, with unit tests, properties to `StarScannedEvent` that represent the fields *for stars* in the  `Scan` journal event that are not currently in the `StarScannedEvent`.
1. These should include at a minimum `WasDiscovered` => `alreadydiscovered`.

**Comment by Tkael** [comment]
Example journal event:
```json
{ "timestamp":"2019-09-24T01:55:39Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Gudran", "BodyID":0, "StarSystem":"Gudran", "SystemAddress":5069806118273, "DistanceFromArrivalLS":0.000000, "StarType":"M", "Subclass":2, "StellarMass":0.406250, "Radius":413122880.000000, "AbsoluteMagnitude":8.340973, "Age_MY":5242, "SurfaceTemperature":3341.000000, "Luminosity":"Va", "RotationPeriod":213105.875000, "AxialTilt":0.000000, "Rings":[ { "Name":"Gudran A Belt", "RingClass":"eRingClass_Metalic", "MassMT":2.6104e+10, "InnerRad":6.8165e+08, "OuterRad":1.8877e+09 } ], "WasDiscovered":true, "WasMapped":false }
```
Note that "WasMapped" will always be false for the star.

**Comment by Tkael** [comment]
Actually, while not published in the variable descriptions for the `Star scanned` event, the `alreadydiscovered` property **is** already being passed to the event and is already made available from the event.
