### ISSUE TITLE
damaged garbled voice being used after I swap ships. 

### ISSUE THREAD

**Issue by jbroad20** [EDCD/EDDI#1698]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.3

## Steps to reproduce
1. log in to game and load into a station
2. swap stop asp explorer at the shipyard
3. the voice will then sound garbled and tell you you have no limpets when you do have limpets

## Expected
the voice not to sound garbled

## Observed
the voice assistant seemed to work fine but did sound garbled afterward

## Investigation
N/A

**Comment by Tkael** [comment]
After the swap is complete, does the vice continue to sound garbled? In particular, is it still garbled after the `Ship loadout` event?

It sounds like the ship may be recorded as damaged in shipmonitor.json when it is first made active...
