### ISSUE TITLE
'RepairDrone' event

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#17]
Needs to be added.
Is a repair event generated when using the amfu or healing limpets to heal the ship? If not, these events will need to include modifications to the ship object. Needs testing?

**Comment by Tkael** [comment]
Added module definitions for Repair Limpet Controllers. I believe the module definitions are complete with the exception of the EDDB ID used for Coriolis export (that value doesn't seem to be available yet / is still being worked on?)

**Comment by naperken** [comment]
This doesn't appear to be committed/pushed yet.

**Comment by Tkael** [comment]
Sorry. Added EDDB IDs and pushed now.

**Comment by Tkael** [comment]
Response: a repair event is not generated.
Example journal entries:
{ "timestamp":"2017-09-02T00:06:07Z", "event":"RepairDrone", "HullRepaired":103.333740 }
{ "timestamp":"2017-09-02T00:08:38Z", "event":"RepairDrone", "HullRepaired":103.332764 }
{ "timestamp":"2017-09-02T00:16:10Z", "event":"RepairDrone", "HullRepaired":103.332642 }
{ "timestamp":"2017-09-02T00:19:20Z", "event":"RepairDrone", "HullRepaired":103.332397 }

**Comment by Tkael** [comment]
Created a branch and have a local solution ready for testing. Note that no modifications to the ship object are included - the ship object does not contain sufficient detail to make the new data useful for modifying the ship object.

**Comment by Tkael** [comment]
Fully tested & committed.
