### ISSUE TITLE
Send symbolic not localised names to EDDN

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#170]
As per Discord:

Summary of the material changes as far as senders & consumers of EDDN messages are concerned:
1. In 2.3 and earlier this info was available from the /profile endpoint. In 2.4 you will have to hit the /market endpoint for this info, and the /shipyard endpoint for outfitting and shipyard info.
2. Commodity "name" was English(ish) name in 2.3. In 2.4 it will be symbolic name (same naming scheme as used in the "Cargo" and other events in the Journal). There's also a new "locName" field for the localised name - this isn't sent over EDDN.
3. New "legality" flag indicating that the commodity is not normally traded at this station market. Commodities with this flag set to a non-empty string MUST NOT be sent over EDDN.
4. New "economies" and "prohibited" lists. These SHOULD be sent in commodity/3 messages over EDDN.

**Comment by MacNetron** [comment]
for completeness, a piece of eddi-postedon-eddn commodity-json containing some names with an added space:
`            {
                "demandBracket": 3,
                "name": "Bio Reducing Lichen",
                "buyPrice": 0,
                "meanPrice": 997,
                "stockBracket": 0,
                "demand": 35597,
                "sellPrice": 1242,
                "stock": 0
            },
            {
                "demandBracket": 3,
                "name": "Hazardous Environment Suits",
                "buyPrice": 0,
                "meanPrice": 338,
                "stockBracket": 0,
                "demand": 88668,
                "sellPrice": 474,
                "stock": 0
            },
             {
                "demandBracket": 3,
                "name": "Non Lethal Weapons",
                "buyPrice": 0,
                "meanPrice": 1834,
                "stockBracket": 0,
                "demand": 1822,
                "sellPrice": 2303,
                "stock": 0
            },`

**Comment by richardbuckle** [comment]
It's not added spaces, it's symbolic name vs localised name. Sometimes the difference is added spaces, other times it is more.

**Comment by MacNetron** [comment]
Haha, I'll stop adding useless wannabe-helpfull text that is only showing that I lack knowledge and is just confusing :D

**Comment by richardbuckle** [comment]
Hoodathunk I think I will need your help on this.

**Comment by richardbuckle** [comment]
https://github.com/EDSM-NET/Alias/blob/master/Station/Commodity/Type.php may be useful

**Comment by Hoodathunk** [comment]
Already on it.

**Comment by Hoodathunk** [comment]
Update:

Problem wasn't in sending 'localized' names vs 'symbolic' (EDName) names.

Problem was that CommodityDefinitions.cs had become a bit dated. By my guess, some ED names at one time did have spaces in them and when the 'Market' data from the API is built to send to EDDN, the CompanionsAppServices used the CommodityDefinitions.CommodityFromEliteID() method which pulled the out-dated data.

1. Out-dated data in CommodityDefinitions.cs fixed
2. API has everything needed to build the EDDN commodity object, CommodityFromEliteID() method not needed.
3. Added code to announce when an 'unknown' or 'out of sync' commodity is encountered, asking user to forward log to developers.

**Comment by richardbuckle** [comment]
Nice one, that's makes sense. Do you still need help getting the ED names for the rare goods?

OtisB said 'If it's easy, please send "economies" and "prohibited" too.' I initially said that would be a bigger job for a separate ticket, do you agree?

**Comment by Hoodathunk** [comment]
ED names and 'localized' names are one in the same., as there are not reported to EDDN.

Yeah, separate ticket/issue for that... it will require a bit of 'up front' work.

**Comment by Hoodathunk** [comment]
Issue corrected under PR #179
