### ISSUE TITLE
"Has granted you access to grade blueprints" on every startup

### ISSUE THREAD

**Issue by shaunpond** [EDCD/EDDI#1710]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
Load VA, sign in to PG on E:D.

## Expected
no voice response

## Observed
"Has granted you access to grade blueprints" (sic) 

## Investigation
this is persisted through at least the last 3 or 4 versions of EDDI

**Comment by shaunpond** [comment]
Forgot - VA is 1.8.3

**Comment by shaunpond** [comment]
oops, clicked wrong button

**Comment by Tkael** [comment]
It sounds like you are using an old version of the `Engineer progressed `  event script? Please update the script.

**Comment by shaunpond** [comment]
I had a lot of scripts with the “reset” option available; I’ve only changed one script, so my guess is that during an upgrade, only the current personality is updated? I have several personalities in EDDI and the one I am using now was copied from another that I copied from the default personality some time ago (turning off several responses when doing exploring for example). Does that make sense?

**Comment by Darkcyde13** [comment]
As I understand it (though I may be wrong), if you make and use a copy of the default personality, it will not be updated with any changes made to the default when you upgrade EDDI to a newer version.  Only the default is updated.  This is most likely why you have so many 'reset' options available.

This means that the fix that was applied to the `Engineer Progressed` script will not be in the copy you use now.  You will need to manually update your version, or click the reset option if you are happy to use the default version of that script.

**Comment by shaunpond** [comment]
That does appear to be the case – it’s a pity, as I’ll need to load up each of my personalities and do reset on more than a dozen scripts

**Comment by shaunpond** [comment]
I should add that it does appear to be working, so pretty happy, if not ecstatic 😊

**Comment by Darkcyde13** [comment]
Glad it's working for you now. :)

I can see why it works the way it does.  EDDI probably can't tell the difference between an old outdated default script, and one you have edited yourself, so it has no choice but to leave them all alone in your copy of the personality.  The default personality is the only one it can safely update.

It would be awesome if EDDI could check that a script hasn't been altered from a previous default when upgrading to a newer version, but it would be impossible to cover all previous versions just to check a script hadn't been changed from an old default.

Or would it?....  I don't know how EDDI knows to active the 'Reset' buttons, but if a hidden flag could be implemented that shows if a script has never been changed by the user, then it should be pretty simple to have the first run of a new EDDI version go over a personality and replace any 'unedited' scripts with the current version.  This way, it wouldn't matter if a user skipped a couple of versions of EDDI.  Obviously, any fixes won't go into any script that has been edited, but that's how it is now anyway.

Granted, this method could add a lot of time to a first run, but having a window message pop up saying something like "Personality upgrade in progress, please wait.  Processing <personality_name>." could at least tell the user what's going on.

@Tkael @Hoodathunk @richardbuckle  what do you think of this idea?  I think it may help mitigate some issues like this one from being raised.

**Comment by richardbuckle** [comment]
Let's park this for now -- in the long term I still want to change the storage approach and that would be a better time to tackle it.
