### ISSUE TITLE
Improve handling of invalid Inara API keys

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1712]
This is a request from Artie. If the Inara server rejects an API key as invalid, returning an error, we should inform the user and stop transmitting until a new API key is provided.

Suggestions:

- Log at error level
- Alert user via both GUI and speech interface
- Either clear the invalid key or invent a way to flag it as invalid in the UI (not sure which is better)

**Comment by richardbuckle** [comment]
Any logging should not include the invalid API key itself for privacy reasons. It is likely to be either accidental other pasteboard content or a typo on the actual API key. In either case, we don't want to log it.

**Comment by Tkael** [comment]
Of course.
