### ISSUE TITLE
Random VA crashes when playing Elite Dangerous with EDDI plugin

### ISSUE THREAD

**Issue by Sparklepaws** [EDCD/EDDI#1715]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8,3

## Steps to reproduce
The following steps provide a reproduction of the crash for me, but this has not always been the case. Please let me know the results.

**Environment:**
- Voice Attack with custom profile loaded and EDDI commands imported.
- EDDI plugin enabled.
- HCS plugin enabled with custom EDDI personality loaded.
- Ivona Salli installed and set as EDDI TTS voice.
- ((EDDI entered supercruise)) event in VA with following commands:
      `Set Text (Script) to "Say anything here".`
      `Execute external plugin, "EDDI"` (Plugin Context: say).
- Elite Dangerous ship in normal space or landed on planet.

**Steps:**

1. Start Voice Attack with custom profile loaded.
2. Start Elite Dangerous and go to Open Play.
3. While Ivona Salli is enabled, jump in and out of Supercruise. Alternatively try entering glide on a planet or moon and/or jumping back to orbit. The goal here is to trigger the ((EDDI entered supercruise)) event so that Salli echos your "Script" variable and also attempts to announce the default supercruise message.

## Expected
Expect VA client to work without crashes when using EDDI plugin.

## Observed
VA appears to randomly crash when playing Elite Dangerous. 

## Investigation
Turned EDDI beta on and off.
Reinstalled EDDI and VA, 
Renamed and deleted APPDATA EDDI.sql file.
Turned Phonetic pronunciation on and off (using Ivona Salli TTS, further tests pending).
Systematically turned EDDI modules off and on.
Changed TTS voice to another Ivona voice. This did not fix the issue.
Changed TTS voice to Microsoft TTS voice. This appeared to solve the issue.
Lowered EDDI voice processing to 0.
Changed EDDI personality to default.
**Checking "Disable Phonetic Speech" in EDDI panel or using something other than Ivona voices appears to stop crashes.** Current conclusion is that something in Ivona's speech programming conflicts with EDDI or VA.

[eddi.log](https://github.com/EDCD/EDDI/files/4275370/eddi.log)
[eddi.log](https://github.com/EDCD/EDDI/files/4276327/eddi.log)

**Comment by Darkcyde13** [comment]
I've had something similar for a couple of years now.  In my case, while VA operates fine for it's functions, and the EDDI plugin works, after a variable amount of time, VA stops responding to voice commands, and the 'Listen/Stop Listening' button stops working.  It only happens with the EDDI plugin enabled, and can happen anywhere between a few minutes, to over half an hour.

I've also tried everything you have, but without any luck.  The only thing I've been able to narrow it down to is the size of my EDDI pesonality.  Making a copy of the default, and then adding more of my own modifications, I start to see the problem after a few changes.  However, because it all still 'works' (just no more voice commands) there is nothing in the EDDI log to show anything is wrong.

While your problem is a full on crash, it makes me wonder if there isn't an underlying problem with the EDDI plugin that is casuing both our difficulties.

**Comment by Tkael** [comment]
That sounds like a separate / unrelated issue (probably more to do with the speech synthesizer?)

**Comment by Tkael** [comment]
Reported on Discord chat:
```
Alright so at this point I can confirm, within 99% reasonable suspicion, that the Ivona 2 Salli voice is causing this crash somehow. I can reproduce the crash 100% of the time when that voice pack is enabled in the EDDI plugin and when I assign another voice the crashes stop.
```
Interesting if true. Are you invoking any functions that affect the voice processing? Does the crashing disappear if voice effects in EDDI are reduced to zero?

I'm also seeing a not of StarMapService timeouts logged and a logged error from Inara stating "too many requests". Are you using the default EDDI personality or a custom personality. If custom, is the default more stable?

**Comment by Sparklepaws** [comment]
> Reported on Discord chat:
> 
> ```
> Alright so at this point I can confirm, within 99% reasonable suspicion, that the Ivona 2 Salli voice is causing this crash somehow. I can reproduce the crash 100% of the time when that voice pack is enabled in the EDDI plugin and when I assign another voice the crashes stop.
> ```
> 
> Interesting if true. Are you invoking any functions that affect the voice processing? Does the crashing disappear if voice effects in EDDI are reduced to zero?
> 
> I'm also seeing a not of StarMapService timeouts logged and a logged error from Inara stating "too many requests". Are you using the default EDDI personality or a custom personality. If custom, is the default more stable?

I'm currently running some more tests while I have a reproducible condition (I'll update the original post's "Investigations" as I proceed). 

If I'm correct about this I should be able to lessen the crashes by disabling the speech Phonetics, but I didn't even consider turning the synth down. I'm at work right now but I'm going to try this when I get back.

On the topic of a custom personality, yes I'm using one of my own creation. I'll try toggling it on and off to see if it effects anything.

**Comment by Sarcocto** [comment]
Hi, I am also using EDDI for a few days now with Ivona Salli and have experienced a similar issue, when running EDDI individually or straight as plugin in VA is spontaneously closes itself or VA when using IVONA Salli as voice. It does not happen when using a Windows standard TTS voice.

**Comment by TalonHawke** [comment]
I've tested a few Ivona voices, and if you don't disable phonetic speech the American English voices all cause crashes.  British and Australian English seem to work fine.

I'm *guessing* there's something wrong in EDDI's handling of American English ssml?

The voices seem to work fine with EDDiscovery with ssml enabled, although I haven't used it extensively, and haven't explicitly tested a known phonetic pronunciation.  I have not had it crash on me during a few hours worth of playing though.

**Comment by Tkael** [comment]
[This](http://developer.ivona.com/en/ttsresources/ssml/ssml.html) is all of the documentation that I've been able to find on Ivona voices with SSML. 
All Ivona voices *should* in theory behave the same in EDDI since the documentation does not distinguish. As far as I'm aware, none of us own any of the American English voices to use for testing. We may need to test using a trial version.

**Comment by Tkael** [comment]
@Sparklepaws @Sarcocto @TalonHawke I'm curious whether VoiceAttackFault.txt recorded anything for these crashes? the file should be located in VoiceAttack's install directory. Thanks!

**Comment by Sarcocto** [comment]
@Tkael no the VoiceAttackFault.txt does not pick up anything. I had clean file, then ran VA through multiple "crashes" with EDDI Salli Ivona Voice and SSML enabled, nothing.

**Comment by Tkael** [comment]
I'm not sure this was asked / answered previously. Does EDDI crash when running in standalone mode?

Installing Ivona Salli, EDDI, and VoiceAttack in a clean sandbox environment then triggering the VoiceAttack `say` context does not trigger a crash for me.

One of the logs includes an exception that isn't present in the other. Did both logs result in a crash? If not, this exception may provide a clue. The exception is:
```
2020-03-01T20:22:49 [Error] VoiceAttackPlugin:triggerVACommands Failed to trigger local VoiceAttack command ((EDDI ship fsd)) {"ClassName":"System.InvalidOperationException","Message":"Collection was modified; enumeration operation may not execute.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()\r\n
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)\r\n
   at VoiceAttack.VoiceAttackInitProxyClass.CommandExists(String commandName)\r\n
   at CallSite.Target(Closure , CallSite , Object , String )\r\n
   at EddiVoiceAttackResponder.VoiceAttackPlugin.triggerVACommands(Event event, Object& vaProxy)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nThrowInvalidOperationException\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.ThrowHelper\nVoid ThrowInvalidOperationException(System.ExceptionResource)","HResult":-2146233079,"Source":"mscorlib","WatsonBuckets":null}
```

**Comment by Tkael** [comment]
I've discussed the exception above with Gary from VoiceAttack. He's going to add a little more protection around this in VoiceAttack's methods.

**Comment by Tkael** [comment]
The latest VoiceAttack beta incorporates improved protection around the proxy command `vaProxy.CommandExists()`. We believe that this change should resolve this issue.
