### ISSUE TITLE
EDDI version 3.5.2 Voice Attack 1.7.9.63 Eddi has stopped working even though i am told that Eddi is connected to my frontier account

### ISSUE THREAD

**Issue by Freakmeister51** [EDCD/EDDI#1718]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Freakmeister51** [comment]
She doesn't say anything anymore

**Comment by Tkael** [comment]
I'm afraid that we have very little to go by with the information provided so far. What have you done to investigate / diagnose the issue? Have you checked the log to determine whether EDDI is still running? Can you provide a copy of those logs? Have you made any changes to your settings recently? Does restarting VoiceAttack or running EDDI in standalone mode resolve the issue?

**Comment by Freakmeister51** [comment]
Dear Brian,
Thank you for your email. I'm sorry I didn't provide enough information
with my previous message. I have sent you a copy of the fault log that the
system provided me with, I hope it helps you as it doesn't make any sense
to me.
Running in standalone, Eddi normally provides a lot of information tabs to
choose from on screen, currently, it only displays EDDI main page,
Commander details Frontier API tab and Text to speech tab. Frontier API tab
shows that it is connected. I am going to try a re-install to see whether
this helps. I have also tried resetting the frontier API to see whether
this was an issue She was working earlier in the day but a later log in
found Eddi not responding to system jumps or system scans.
If there is anything else I can try, please let me know

Thanks again
Paul Francis

**Comment by Freakmeister51** [comment]
I have tried a reinstall of EDDI but the results are the same. EDDI shows as running and connected to my Frontier API. But there are many tabs missing from the EDDI stand alone application so my diagnosis of the fault is limited. There is no update facility so I can only assume that version 3.5.2 is the most up to date edition.

**Comment by Tkael** [comment]
That's a much more helpful description, thanks. We've seen similar issues (with missing tabs) when a configuration file has become corrupted. 

Please follow the steps at https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup to identify the corrupted configuration file. Once identified, please let us know which file is causing the issue. Depending on the file, we may ask you to send us the file to review for further investigation (we will not ask you to send the file if it contains private information like your EDSM or Inara API key).

**Comment by Tkael** [comment]
Closing as (presumably) resolved. Please reply if otherwise.
