### ISSUE TITLE
Revise "Entered signal source" script for Thargoid threat levels

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#172]
Currently the script is:

```
{Pause(2000)}

{if event.threat < 2:
  Entered signal source.
|elif event.threat = 2:
    Caution: medium-threat signal source.
|elif event.threat = 3:
    Warning: high-threat signal source.
|else:
    Danger: very high-threat signal source.
}
```

Extend this to make threat level 4 "Danger: very high-threat signal source." and insert new text for levels 5 to 7 (I don't think we've seen any level 6 yet in practice?)

**Comment by Tkael** [comment]
What would you like said for those levels? `Danger: very high-threat signal source` still seems to be more or less appropriate. ;-)

**Comment by richardbuckle** [comment]
I'm sure @Darkcyde13 can be creative.

**Comment by richardbuckle** [comment]
And a 5 is way more serious than a 4. My PvE Python can faceroll any human NPC, but any Thargoid will make very short work of me unless I am prepped.

**Comment by Darkcyde13** [comment]
How about this for a first draft?

```
|elif event.threat = 4:
    Danger: very high-threat signal source.
|elif event.threat = 5:
    Extreme Danger: very high-threat Xeno signal source.
|elif event.threat = 6:
|elif event.threat = 7:
    Extreme Danger: Multiple Xeno ultra-high-threat signal source.
}
```

**Comment by Darkcyde13** [comment]
Second draft:-

```
|elif event.threat = 4:
    Danger: very high-threat {source} signal source.
|elif event.threat = 5:
    Extreme Danger: very high-threat Xeno signal source.
|elif event.threat = 6:
    Extreme Danger: major high-threat Xeno signal source.
|elif event.threat = 7:
    Extreme Danger: Multiple Xeno ultra-high-threat signal source.
}
```

**Comment by Tkael** [comment]
Could I get copies of journal events for threat 5 & threat 7 (if we have any of those)? We should be reacting to the USSType variable, not just the USSThreat variable.

**Comment by richardbuckle** [comment]
My threat 5 are the same. I don't have any threat 7 but I'm currently near the Pleiades in a cheapish DBX so I'll go and find one [gulp].

**Comment by richardbuckle** [comment]
On the Cottle side, I would probably add a catch-all else clause at the end to cater for FDev adding surprise new content.

**Comment by Darkcyde13** [comment]
OK, how about this one?  This is my full script with a couple of amendments as mentioned above.
```
{Pause(2000)}


{set source to token(event.source, "_", 2)}

{if source = "Convoy;":
    {set source to "convoy"}
|elif source = "DisruptedWakeEchoes;":
    {set source to ""}
|elif source = "Salvage;":
    {set source to "salvage"}
|elif source = "ValuableSalvage;":
    {set source to "valuable salvage"}
|elif source = "VeryValuableSalvage;":
    {set source to "high value salvage"}
|elif source = "NonHuman;":
    {set source to "Non-human"}
}

{if event.threat < 2:
  Entered {source} signal source.
|elif event.threat = 2:
    Caution: medium-threat {source} signal source.
|elif event.threat = 3:
    Warning: high-threat {source} signal source.
|elif event.threat = 4:
    Danger: very high-threat {source} signal source.
|elif event.threat = 5:
    Extreme Danger: very high-threat {source} signal source.
|elif event.threat = 6:
    Extreme Danger: major high-threat {source} signal source.
|elif event.threat = 7:
    Extreme Danger: ultra-high-threat {source} signal source.
|else:
    Caution: Unknown threat level {source} signal source.
}
```

I've been using the {source} variable for some time.  This should cover most eventualities I think.

**Comment by richardbuckle** [comment]
I like Darkcyde's proposal.

Been tooling around Maia but didn't manage to find a lvl 7 so far.

**Comment by Tkael** [comment]
Taking from your suggestions, my journals, and some experimentation today this is what I'm now using:
```
{set warninglevel to:
   {set entered to OneOf("Entered", "Dropped on", "Entering")}
   {if event.threat < 2:
      {entered}
   |elif event.threat = 2:
      Caution: {entered} medium threat
   |elif event.threat = 3:
      Warning: {entered} high-threat
   |elif event.threat = 4:
      Danger: {entered} very high-threat
   |elif event.threat >= 5:
      Extreme Danger: {Occasionally(2, entered)} very high-threat
   |elif event.threat >= 6:
      Extreme Danger: {Occasionally(2, entered)} extremely high-threat
   |elif event.threat >= 7:
      Extreme Danger: {Occasionally(2, entered)} ultra high-threat
   |elif event.threat >= 8:
      Extreme Danger: {Occasionally(2, entered)} Unprecedented level {event.threat} threat
   }
}

{set source to token(event.source, "$USS_Type_", "")}
{if find(event.source, "Ceremonial") >= 0:
   {set source to "ceremonial comms"}
|elif find(event.source, "VeryValuableSalvage") >= 0:
   {set source to "high grade emissions"}
|elif find(source, "ValuableSalvage") >= 0:
   {set source to "encoded emissions"}
|elif find(event.source, "Salvage") >= 0:
   {set source to OneOf("degraded emissions", "salvageable wreckage", "salvage")}
|elif find(event.source, "Aftermath") >= 0:
   {set source to OneOf("combat aftermath", "dissippating combat")}
|elif find(event.source, "WeaponsFire") >= 0:
   {set source to OneOf("combat", "weapons fire")}
|elif find(event.source, "Convoy") >= 0:
   {set source to "convoy")}
|elif find(event.source, "MissionTarget") >= 0:
   {set source to OneOf("mission", "mission encoded")}
|elif find(event.source, "DistressSignal") >= 0:
   {set source to "distress"}
|elif find(event.source, "Anamoly") >= 0:
   {set source to OneOf("anamolous", "unknown", "mysterious")}
|elif find(event.source, "NonHuman") >= 0:
   {set source to OneOf("alien", "xeno", "non-human")}
|elif ((find(event.source, "Anomaly") >= 0 || find(event.source, "Salvage") >= 0) && event.threat = 2):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid probe")}
|elif (find(event.source, "Anomaly") >= 0 && event.threat = 4):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid sensor")}
}

{Pause(2000)}
{warninglevel} {source} {OneOf("signal source", "signal's point of origin")}.
```

**Comment by richardbuckle** [comment]
Looks good but I think the tests for level 5,6, and 7 should be `=` not `>=`. And the final one might as well just be `else`.

**Comment by Darkcyde13** [comment]
The most efficient way to use 'find' is to do a > -1 as what you are looking for can be at position zero.  This is a 'good practice' method to apply to all instances of 'find' to maintain a uniform codebase.

However, using 'find' in this instance is inefficient, and while we are probably talking only milliseconds, that function does use increased processing time over a simple 'if' statement once the required data is extracted.

Likewise, using >= in the first half for each value when they are only ever going to be whole numbers, is redundant.  That section will only ever reach number five as anything above that will also trigger it, meaning 6+ will never be used.

On a positive note, I do like how you have constructed the sentence to be spoken, and I think it provides a much better result, and variation.

**Comment by Darkcyde13** [comment]
I believe this version is most efficient, and fixes the points mentioned above.  It's also less code and easier for beginners to understand what's going on.

```
{set warninglevel to:
   {set entered to OneOf("Entered", "Dropped into", "Entering")}
   {if event.threat < 2:
      {entered}
   |elif event.threat = 2:
      Caution: {entered} medium threat
   |elif event.threat = 3:
      Warning: {entered} high-threat
   |elif event.threat = 4:
      Danger: {entered} very high-threat
   |elif event.threat = 5:
      Extreme Danger: {Occasionally(2, entered)} very high-threat
   |elif event.threat = 6:
      Extreme Danger: {Occasionally(2, entered)} extremely high-threat
   |elif event.threat = 7:
      Extreme Danger: {Occasionally(2, entered)} ultra high-threat
   |else:
      Extreme Danger: {Occasionally(2, entered)} Unprecedented level {event.threat} threat
   }
}

{set source to token(event.source, "_", 2)}

{if source = "Aftermath;":
   {set source to OneOf("combat aftermath", "dissippating combat")}
|elif ((source = "Anomaly;" || source = "Salvage;") && event.threat = 2):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid probe")}
|elif (source = "Anomaly;" && event.threat = 4):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid sensor")}
|elif source = "Anamoly;":
   {set source to OneOf("anamolous", "unknown", "mysterious")}
|elif source = "Ceremonial;":
    {set source to "ceremonial comms"}
|elif source = "Convoy;":
    {set source to "convoy"}
|elif source = "DisruptedWakeEchoes;":
    {set source to ""}
|elif source = "DistressSignal;":
   {set source to "distress"}
|elif source = "MissionTarget;":
   {set source to OneOf("mission", "mission encoded")}
|elif source = "NonHuman;":
   {set source to OneOf("alien", "xeno", "non-human")}
|elif source = "Salvage;":
    {set source to "degraded emissions"}
|elif source = "ValuableSalvage;":
    {set source to "encoded emissions"}
|elif source = "VeryValuableSalvage;":
    {set source to "high grade emissions"}
|elif source = "WeaponsFire;":
   {set source to OneOf("combat", "weapons fire")}
}

{Pause(2000)}
{warninglevel} {source} {OneOf("signal source", "signal's point of origin")}.

```

**Comment by richardbuckle** [comment]
This latest version looks the best.

As a side note, for integers `i > -1` and `i >= 0` are precisely equivalent.

**Comment by Darkcyde13** [comment]
Yeah, that's true.  From a logic point of view, in the first example you are performing only a single operation, 'is greater than', while in the second example you are performing two operations, 'is greater than' and 'is equal to', hence the first is slightly more efficient.

**Comment by Tkael** [comment]
You alphabetized it too. ;-) Looks good.
Any final thoughts on speech variations we may want to add before we publish it?

**Comment by Darkcyde13** [comment]
Sorry, I've not been around my PC too much this past week, so haven't really had much time to do anything.

I'm happy with it like this.  At least, this is how I'll have it in my profile.  Of course, if anyone has any speech variations to enhance it, I'm open to further suggestion.

**Comment by Tkael** [comment]
Add occasional warnings regarding possible pirate ambushes:
```
{set warninglevel to:
   {set entered to OneOf("Entered", "Dropped into", "Entering")}
   {if event.threat < 2:
      {entered}
   |elif event.threat = 2:
      Caution: {entered} medium threat
   |elif event.threat = 3:
      Warning: {entered} high-threat
   |elif event.threat = 4:
      Danger: {entered} very high-threat
   |elif event.threat = 5:
      Extreme Danger: {Occasionally(2, entered)} very high-threat
   |elif event.threat = 6:
      Extreme Danger: {Occasionally(2, entered)} extremely high-threat
   |elif event.threat = 7:
      Extreme Danger: {Occasionally(2, entered)} ultra high-threat
   |else:
      Extreme Danger: {Occasionally(2, entered)} Unprecedented level {event.threat} threat
   }
}

{set source to token(event.source, "$USS_Type_", 1)}

{if source = "Aftermath;":
   {set source to OneOf("combat aftermath", "dissippating combat")}
|elif ((source = "Anomaly;" || source = "Salvage;") && event.threat = 2):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid probe")}
|elif (source = "Anomaly;" && event.threat = 4):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid sensor")}
|elif source = "Anomaly;":
   {set source to OneOf("anomalous", "unknown", "mysterious")}
|elif source = "Ceremonial;":
    {set source to "ceremonial comms"}
|elif source = "Convoy;":
    {set source to "convoy"}
|elif source = "DisruptedWakeEchoes;":
    {set source to ""}
|elif source = "DistressSignal;":
   {set source to "distress"}
|elif source = "MissionTarget;":
   {set source to OneOf("mission", "mission encoded")}
|elif source = "NonHuman;":
   {set source to OneOf("alien", "xeno", "non-human")}
|elif source = "Salvage;":
    {set source to "degraded emissions"}
|elif source = "ValuableSalvage;":
    {set source to "encoded emissions"}
|elif source = "VeryValuableSalvage;":
    {set source to "high grade emissions"}
|elif source = "WeaponsFire;":
   {set source to OneOf("combat", "weapons fire")}
}

{Pause(2000)}
{warninglevel} {source} {OneOf("signal source", "signal's point of origin")}

{if system.state = "Anarchy" && source = "degraded emissions" && system.population > 0: 
   {set some to Occasionally(2, "some")}
   {set faintsignals to OneOf("low level readings", "faint signals", "signal echos")}
   {Occasionally(3, cat(Pause(1000), OneOf("There are {some} {faintsignals} on the scanner", "Long range sensors detect {some} {faintsignals}"), Occasionally(2, "here"), OneOf(". Stay vigilant", ". Stay alert") ))}
}

{Occasionally(3,", {F('Honorific')}")}.
```

**Comment by Darkcyde13** [comment]
I like that.  It gets my seal of approval! ;-)

**Comment by richardbuckle** [comment]
Typo: dissippating -> dissipating.

I'm in Maia so I'll try to scare up some Thargoids and test this.

**Comment by richardbuckle** [comment]
Doesn't quite work: I entered a level 5 and it said:

" Extreme Danger: very high-threat non-human signal's point of origin."

**Comment by richardbuckle** [comment]
I think `{OneOf("signal source", "signal's point of origin")}` is a reach too far and will try again with just `signal source`.

**Comment by richardbuckle** [comment]
yes that's better.

**Comment by Darkcyde13** [comment]
Hmm, yes, I see what you mean.  Maybe the reduced information would be better.

I'd also been toying with the idea of removing "signal's point of origin".  It didn't feel quite right, but I wasn't sure of what to change it to, or if to remove it totally.

**Comment by Tkael** [comment]
"Faint signals" is meant to not be immersion breaking but to still give a reason to stay alert. If it is too on the nose / specific then it'll spoil the effect I'm going for. I want to suggest a trap, but to do so indirectly.

**Comment by Darkcyde13** [comment]
I've been thinking about this today, and have come up with a rough alternative.  It could probably do with a bit of polish, but...
```
{set group to OneOf("clan", "gang", "syndicate")}
{set are to OneOf("known to be", "reported")}
{set type to OneOf("active", "present", "operational")}
{set type2 to OneOf("activity reported", "presence reported", "known to be operating")}

{Occasionally(1, "
  Caution:
  {OneOf('criminal', 'pirate')}
  {OneOf('{group}s {are} {type}', '{group} {type2}')}
  in {OneOf('the area', 'the vicinty', 'this sector', 'this system')}.
  Remain vigilant Commander.
")}
```
I've run this many times, and each spoken sentence sounds right (no odd phrases constructed).  I'm still not sure if it's appropriate though, but I thought I'd see what you guys think about it.

**Comment by Tkael** [comment]
This is a good direction. Maybe we could use something like "local transmissions" (like for faction state changes with the EDDP monitor) to give reasonable suspicion here.

**Comment by Tkael** [comment]
For example: `Chatter in local transmissions suggests that there is an elevated criminal presence in this area. Stay vigilant, commander.`

**Comment by Darkcyde13** [comment]
OK, I've combined the two to make the following.  However, I'm not sure it feels... natural?  Something seems off to me, but I can't quite put my finger on it, so to speak.
```
   {Occasionally(2, "
      Caution:
      {set type1 to OneOf('com', 'transmission')}

      {OneOf('local {type1}{Occasionally(2, \\'s\\')} {Occasionally(2, \\'net\\')} chatter',
             'chatter in local {type1}{Occasionally(2, \\'s\\')} {Occasionally(2, \\'net\\')}' )}
      {OneOf('indicates', 'suggest{Occasionally(2, \\'s\\')}')}
      {OneOf('increased', 'elevated', 'high')}
      levels of
      {OneOf('criminal', 'pirate')}
      {OneOf('clan', 'gang', 'syndicate')}
      {OneOf('activity', 'presence')}
      in {OneOf('the area', 'the vicinity', 'this sector', 'this system')}.
      {OneOf('Remain vigilant', 'Stay alert')}
   ")}
```

**Comment by richardbuckle** [comment]
Interesting discussion that highlights how one might develop in different directions according to one's concept for the script's "personality". I'm going to reflect on this a bit before deciding.

In some future version I would very much like EDDI to ship with a selection of personalities out of the box.

**Comment by richardbuckle** [comment]
PS are those double backslashes correct? It might be cleaner to delimit the string in double quotes so you can use unescaped single quotes within it.

**Comment by richardbuckle** [comment]
@Darkcyde13 I've listened to it a few times. It's going in the right direction but I agree something is a bit off. Maybe it's just too verbose? Here is some output:

- Entered signal source. Caution: local transmissions net chatter indicates high levels of pirate gang activity in the area. Remain vigilant, commander.
- Entered signal source. Caution: local transmissions chatter suggests increased levels of criminal syndicate activity in this system. Stay alert, commander.
- Entering signal source. Caution: chatter in local transmission indicates high levels of criminal clan presence in the vicinity. Remain vigilant, commander.

Also, we have a random change of singular and plural subjects and verbs disagreeing. (I'm a bit OCD about that.)

**Comment by Darkcyde13** [comment]
The double backslashes are correct as far as I am aware, because the whole thing is inside an Occasionally which uses double quotes.  As far as I've discovered from using Cottle, you can use either single or double quotes to start, and then use the other inside, but if you need to nest further you have to escape them with the double backslash.  If this is incorrect, please do let me know.

As for the personality aspect, I am constantly aware of it, and try hard to make my own personality fit with the default.  I guess that stems from me preferring the 'neutral' profile that the default exhibits.  Plus I like the ships computer to be just that, a computer, just like the ships computer in Star Trek, all 'matter-of-fact' like.

**Comment by richardbuckle** [comment]
Yes you are right about the double backslashes now that I am testing it.

**Comment by Darkcyde13** [comment]
@richardbuckle Yeah, I agree.  I'm feeling that I like my earlier suggestion better.  It's shorter and more consise I think.

**Comment by richardbuckle** [comment]
I think it is unfortunate combos like "local transmissions net chatter" that are making it feel unnatural. Thoughts?

**Comment by richardbuckle** [comment]
I'm leaning towards the more concise version too. How about tweaking the last phrase:

```
{OneOf('Remain', 'Stay', 'Keep')} {OneOf('vigilant', 'alert', 'frosty', 'sharp')}
```

**Comment by Darkcyde13** [comment]
Maybe if it was just transmissions OR comms net (or just comms)?

Sorry, I keep forgetting to log into Discord for this stuff. Now re-installing it after Win10 Upgrade the other day.

**Comment by Darkcyde13** [comment]
Tweaking that last phrase is fine by me.  I was trying to think of other ways to put it.

**Comment by richardbuckle** [comment]
It's possible that we are worrying too much about a secondary feature and should just ship the rest of the script, creating a new issue for this warning paragraph. Thoughts?

**Comment by Darkcyde13** [comment]
While I would very much like my scripts, and script ideas, to be included with the default personality so that I can make a worth-while contribution to the project, you are most certainly correct.  What a script says isn't as important as what it's potential capabilities are.

"I like it this way" or "I like it that way" will always be said about practically all scripts as everyone has their own personal preference.   We will use whatever we each deem appropriate anyway, so as long as the basic default script can show a user what's possible to achieve, then it's more than adequate for release.

**Comment by Tkael** [comment]
And as long as the default script isn't broken / doesn't unnecessarily break immersion. I'm fine with breaking out this bit as its own issue or simply leaving it out... it's always been an optional extra.

**Comment by Tkael** [comment]
Ok. Last attempt before we break this off and make it a separate thing. Just give a thumbs up or thumbs down reaction to the following:
```
{set warninglevel to:
   {set entered to OneOf("Entered", "Dropped into", "Entering")}
   {if event.threat < 2:
      {entered}
   |elif event.threat = 2:
      Caution: {entered} medium threat
   |elif event.threat = 3:
      Warning: {entered} high-threat
   |elif event.threat = 4:
      Danger: {entered} very high-threat
   |elif event.threat = 5:
      Extreme Danger: {Occasionally(2, entered)} very high-threat
   |elif event.threat = 6:
      Extreme Danger: {Occasionally(2, entered)} extremely high-threat
   |elif event.threat = 7:
      Extreme Danger: {Occasionally(2, entered)} ultra high-threat
   |else:
      Extreme Danger: {Occasionally(2, entered)} Unprecedented level {event.threat} threat
   }
}

{set source to token(event.source, "$USS_Type_", 1)}

{if source = "Aftermath;":
   {set source to OneOf("combat aftermath", "dissippating combat")}
|elif ((source = "Anomaly;" || source = "Salvage;") && event.threat = 2):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid probe")}
|elif (source = "Anomaly;" && event.threat = 4):
   {set warninglevel to entered}
   {set source to OneOf("alien", "xeno", "non-human", "Thargoid sensor")}
|elif source = "Anomaly;":
   {set source to OneOf("anomalous", "unknown", "mysterious")}
|elif source = "Ceremonial;":
    {set source to "ceremonial comms"}
|elif source = "Convoy;":
    {set source to "convoy"}
|elif source = "DisruptedWakeEchoes;":
    {set source to ""}
|elif source = "DistressSignal;":
   {set source to "distress"}
|elif source = "MissionTarget;":
   {set source to OneOf("mission", "mission encoded")}
|elif source = "NonHuman;":
   {set source to OneOf("alien", "xeno", "non-human")}
|elif source = "Salvage;":
    {set source to "degraded emissions"}
|elif source = "ValuableSalvage;":
    {set source to "encoded emissions"}
|elif source = "VeryValuableSalvage;":
    {set source to "high grade emissions"}
|elif source = "WeaponsFire;":
   {set source to OneOf("combat", "weapons fire")}
}

{Pause(2000)}
{warninglevel} {source} signal source.

{if system.state = "Anarchy" && source = "degraded emissions" && system.population > 0: 
   {Occasionally(2, "
      Caution:
      {set local to OneOf('local', 'nearby')}
      {set chatter to OneOf('chatter', 
                        'gossip', 
                        'rumors')}
      {set indicate to OneOf('claim', 
                        'suggest', 
                        'imply',
                        'report')}
      {OneOf('{local} transmissions {indicate}', 
         '{chatter} in {local} transmissions {indicate}')}
      {Occasionally(3, 'that there is')}
      {OneOf('increased', 'elevated', 'heightened')}
      {OneOf('criminal {Occasionally(2, \\'syndicate\\')}', 
             'pirate {Occasionally(2, OneOf(\\'gang\\', \\'clan\\'))}' )}
      {OneOf('activity', 'presence')}
      in {OneOf('the area', 'the vicinity', 'this sector', 'this system')}.
      {OneOf('Remain {OneOf(\\'vigilant\\', \\'alert\\')}', 
             'Stay {OneOf(\\'vigilant\\', \\'alert\\', \\'frosty\\', \\'sharp\\')}' )} 
      {Occasionally(3,' {F(\\'Honorific\\')}' )}.
   ")}
}
```

**Comment by Darkcyde13** [comment]
While I understand the desire to have a source for the warning (transmissions, rumors, etc), I still feel it takes too long overall.  On average, it takes about 8 seconds to say, whereas the earlier version takes only 5 seconds.

In the grand scheme of things, three seconds isn't much, and as I said, it's all down to personal preference anyway.  I have no objections to this version being used as the default, as I will still use the shorter version for myself.

**Comment by Tkael** [comment]
The 3 seconds will only apply for a single, somewhat specific case.

**Comment by richardbuckle** [comment]
Discussed with Tkael. For a simpler grammar:

```
      {set chatter to OneOf('chatter', 
                        'gossip', 
                        'rumor')}
      {set indicate to OneOf('claim', 
                        'suggets', 
                        'implies',
                        'reports')}
```
