### ISSUE TITLE
keep hearing as i enter system "this is the 1st time you have been to this system"

### ISSUE THREAD

**Issue by Timnus** [EDCD/EDDI#1720]
## EDDI version in which issue is found
3.5.1

## VoiceAttack version in which issue is found (as applicable)
not running.

## Steps to reproduce
1. start after game file is open.
2. Travel between several systems you normally do not travel in. Repeat same systems.

## Expected
verbalize how many times i have traveled to system if under 25. 

## Observed
keep hearing "This is the first time you have been to this system"

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
More data is needed to diagnose and replicate this problem. Is this something that you have noticed as a recent change or an ongoing issue? Do you synchronize your flight logs to EDSM?

**Comment by Tkael** [comment]
Closing due to lack of information and lack of corroborating reports.

**Comment by Timnus** [comment]
i have eddiscovery in full synch mode. 

Have a Wonderful Day!!!
Timothy Deane 

    On Saturday, March 14, 2020, 11:03:03 PM CDT, Brian Wilson <notifications@github.com> wrote:  
 
 


More data is needed to diagnose and replicate this problem. Is this something that you have noticed as a recent change or an ongoing issue? Do you synchronize your flight logs to EDSM?

**Comment by Tkael** [comment]
Hi Timnus, we still don't have very much information to use to diagnose this issue but it seems like maybe data isn't being written correctly to your local database.
Would you please share a copy of a log file where this problem occurred so that we can review it?
Logs are located at `%appdata%/roaming/EDDI` and end with the suffix `.log`.

**Comment by Timnus** [comment]
[EDDI.zip](https://github.com/EDCD/EDDI/files/4362317/EDDI.zip)

**Comment by Timnus** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/4393450/eddi.log)
it keep stating it even though i have turned in cartography on the system

**Comment by Timnus** [comment]
ok i red the logs. added my name in the slot and it went away. i think.

**Comment by Tkael** [comment]
Alright. Looks like we were trying to obtain data from EDSM, returning no results from EDSM, and then resetting the visit count on the basis of having no visit data returned from the server. Adding your name resolves that.

I'm also seeing a lot of attempts to send data to EDSM after we've already established that your credentials aren't set. I'll submit a PR to try to tidy that up.
