### ISSUE TITLE
It's worse than my wife... EDDI talks too much. 

### ISSUE THREAD

**Issue by SweetyVolty** [EDCD/EDDI#1726]
## Problem
I expected EDDI would add some color to the game but oh my it's literally giving headaches.

## Expected
[Describe what you expected to happen]
Simply switching off some check boxes to stop him from responding but it's waaay to complicated than I thought 

## Observed
[Describe what happened instead]
Headaches when jumping a lot of warps from this system you have entered have blah blah blah etc 

## Needs
A less talking EDDI, which means trimmed unnecessary talking features. More simplified way to edit Speech responder for dummies like me.

**Comment by Tkael** [comment]
"Unnecessary talking features" is a rather vague criteria and the fact of the matter is that many people will have differing opinions on what is useful and what is not. That is one of the primary reasons why the speech responder gives users so much latitude to create custom personalities and write their own scripts. Additionally, it's easier (especially for people who aren't technically inclined) to "prune" from that default personality and remove information than to add information.

If you find that EDDI is far too verbose, I would suggest that you disable all of the scripts in the speech responder and then selectively enable scripts for areas where you'd like to add more color or information to the game.
