### ISSUE TITLE
EDDI need a toggle for NPC "Message Received"

### ISSUE THREAD

**Issue by sammyf** [EDCD/EDDI#173]
## Steps to reproduce
Everytime an NPC sends a message EDDI reads it aloud. There is no option to turn this behaviour off and it interferes with specialized 3rd party tools (TTS4Elite  in my case)

## Expected
There should be a toggle to turn off the *NPC* messages. It should be separate from PC messages (so that the "old" behaviour can be restored (PC messages being read, but NPCs not)

**Comment by Tkael** [comment]
The script can be customized. This will remove all messages from the "npc" channel.
```
{_ Context }
{SetState('eddi_context_last_subject', 'message')}
{SetState('eddi_context_last_action', 'receive')}
{SetState('eddi_context_message_name', event.from)}
{SetState('eddi_context_message_content', event.message)}

{if event.player = true:
    {if event.message = "o7":
        {event.from} salutes
        {if event.channel = "player":
            you
        }.
    |else:
        Message received from {event.source} {event.from}.  Message reads: {event.message}.
    }
|elif event.source != "Station" #&& event.channel != "npc":
    Message received from {event.source} {event.from}.  Message reads: {event.message}.
}
```

**Comment by Tkael** [comment]
Note that you can always reset a script back to its default, or compare your version to the default.
