### ISSUE TITLE
First installation on Win10; EDDI icon shows up in taskbar but no GUI

### ISSUE THREAD

**Issue by codje** [EDCD/EDDI#1730]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
(First time I download EDDI and try to install)
1. Fresh download of the .exe file
2. Run of the .exe file as Admin
3. Standard installation
4. EDDI.exe run as Admin

## Expected
Expect to have EDDI opens and showing up

## Observed
Only taskbar icon shows up, nothing appears.

## Investigation
I tried the troubleshooting proposed with removing file from AppData/Roaming/EDDi but no improvement. I checked other topics with same GUI issue but proposed solutions dont work. I didn't change anything in the files as it's a first installation. It happens always with a fresh install. I tried version 3.5.1 and 3.5.2.
I run on Windows10 and I tried putting the correct settings in WinDefender and checked the dll options, run as Admin etc. Everything looks fine... but EDDI windows doesnt show up. Please have you any suggestions ? Thanks

Could you let me know how to prvide a log file please?

**Comment by clinkingdog** [comment]
It sounds like possibly the window is opening off-screen? If you shift+right click the taskbar icon, select "Move", and then move the arrow keys, that would shift the window around and you might be able to bring it on-screen that way.

(It would still be odd behaviour from EDDI but that solution might get you moving in the meantime!)

**Comment by codje** [comment]
Thanks clinkingdof, as simple as it sounds, it was this issue.
The windows was way down, I was able to move it back.

Thanks for your help!
