### ISSUE TITLE
allow variable priority disablespeechresponder

### ISSUE THREAD

**Issue by maboesanman** [EDCD/EDDI#1731]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.5 - Steam

## Feature suggestion:
all event commands have a priority already, so it would be great if the
`disablespeechresponder` and `enablespeechresponder` commands could take an optional parameter priority.

proposed syntax and behavior:

* `disablespeechresponder(3)` would disable all speech responders with a priority 3 or **greater**, and would default to 1, which would preserve the current behavior.

* `enablespeechresponder(3)` would enable all speech responders with a priority 3 or **less**, and would default to 5, which would preserve current behavior.

I know this could be solved by multiple personalities, but this seems valuable as an additional feature.

**Comment by maboesanman** [comment]
If there’s interest in this I can try to throw together a PR, but I wanted to get some official comment on whether or not this aligns with the viewpoint of the maintainers before dumping too much time into it.

**Comment by Tkael** [comment]
Users can currently toggle personalities or use `setstate` to modify scripts for various levels of verbosity. I recognize that these solutions may not be perfect, but I'm not sure that enabling and disabling scripts across the board by priority is the correct solution.

Priority is about ordering scripts and (when appropriate) interrupting low priority scripts. It's never been about enabling and disabling scripts. 

Additionally, enabling and disabling scripts across the board by priority is a very blunt instrument - users could easily enable or disable scripts that they don't intend.
