### ISSUE TITLE
EDDI don't connect to Frontier-API

### ISSUE THREAD

**Issue by Waylinkin** [EDCD/EDDI#1735]
## EDDI version in which issue is found
3.5.2

## Steps to reproduce
Have made a Video... But its german. But you can see, what i have tried.
https://youtu.be/sMNnOavMMfo

## Expected
I want to connect EDDI with Frontier-API.

## Observed
EDDI don't connect to Frontier-API.

## Investigation
Have tried to delete the permission from EDDI in Frontier Auth. Then tried to connect EDDI, but no success. 

The solution in #1185 don't work.

**Comment by Tkael** [comment]
Can you please provide EDDIE'S log files (found in %appdata%\EDDI on your PC)?

**Comment by Tkael** [comment]
Pose also verify that neither EDDI not your internet browser is in administrator mode?

**Comment by Waylinkin** [comment]
Okay, here the log:
[eddi.log](https://github.com/EDCD/EDDI/files/4452406/eddi.log)

I have tried both: As Admin and normal. Both don't succes. But usually i use EDDI in normal mode.

**Comment by Tkael** [comment]
The log file shows that EDDI tried to connect on startup but doesn't indicate any problems. A verbose debug log might show more but if you would like to send one of those then please turn off verbose logging as soon as you're done collecting the log.

The dialog that you see when you try to connect appears similar to what we've sometimes seen when a user is trying to use EDDI or the browser in administrator mode.

I'm not familiar with the effect on your desktop. Is your system opening more than one application at a time to create that visual effect and echo?

Has the Frontier API been working for you previously or are you trying to configure it for the first time?

You might try deleting your Frontier API credential from EDDI and restarting. To do this:
1.    Close completely out of EDDI
2.    Navigate to `%APPDATA%/EDDI`
3.    Cut the file `CompanionAPI.json` and paste it to another location. This removes all of EDDI's information about the Frontier API connection.
4.    Attempt to start EDDI. EDDI should open with the default Frontier API configuration.
5.    Try again to connect to the Frontier API in EDDI. You should not see a dialog box after you log in.

@richardbuckle How's your German? :-)

**Comment by Waylinkin** [comment]
I have a desk-microphone and the voice was very loud, so it comes to a feedback. ;)
Okay, i have tested cutting the Companion.json. But with no succes. And i have tried using the edge browser, but the same thing happened. The first log is the trie with my Standardbrowser Vivaldi, the second Log with edge:
[eddi.log](https://github.com/EDCD/EDDI/files/4454384/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/4454385/eddi1.log)

I have played ED at last in the year 2018. In 2018 EDDI worked perfect. My Windows is fresh installed, therefore there are no old programs, which can disturb.

**Comment by Tkael** [comment]
@richardbuckle Any ideas?

**Comment by Tkael** [comment]
The logs do not record any data from CompanionAppService.cs. They do include the line 
`2020-04-09T06:21:16 [Info] EDDI:.ctor EDDI access to the Frontier API is not enabled.`
which appears to originate from:
https://github.com/EDCD/EDDI/blob/0bcad4c338a3d637477c8f3889f13cc2d7cad5cc/EDDI/EDDI.cs#L220
and
`2020-04-09T06:21:42 [Debug] SpeechService:speak Feeding normal text to synthesizer: Bitte authentifizieren Sie EDDI's Verbindung zur Frontier API.` ("Please authenticate EDDI's connection to the Frontier API.")
which appears to originate from:
https://github.com/EDCD/EDDI/blob/0bcad4c338a3d637477c8f3889f13cc2d7cad5cc/EDDI/MainWindow.xaml.cs#L911

It looks like the CompanionAppService fails to achieve an authorized state initially and then does not recognize subsequent attempts to authorize the connection.

**Comment by Waylinkin** [comment]
I have tested the connection with Opera and Firefox too, but the connection not work. It seems not to be a problem from Browsers itself.

**Comment by Tkael** [comment]
@richardbuckle Have you had a chance to look into this?

**Comment by richardbuckle** [comment]
Sorry, not had any time yet on this one. Had a quick look at the video, and I do speak a bit of German. I think the binding between the EDDI app and the `eddi` URL protocol might be broken. This resides in ResEdit under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\eddi`.

I would try:
1. Backup `%appdata%\EDDI` in a zip file or similar.
2. Uninstall EDDI via the Windows Apps and Programs control panel or whatever it is called these days.
3. Use regedit to delete `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\eddi`.
4. Reinstall EDDI.
5. Reinstate `%appdata%\EDDI`.

**Comment by Tkael** [comment]
If this resolves the immediate issue, is there a way that we could test for and fix similarly broken bindings in the future?

**Comment by Waylinkin** [comment]
Okay... I have tried the tipp von richardbuckle. I was unable to do Point 3, becaus this key dosn't exist. 
But i searched the Registry with the keyword EDDI and found this one:
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\DDECache\EDDI`
I deleted it and have restart the computer. Then i reinstalled EDDI, and now i was able to connect EDDI to Frontier. Strange thing...

**Comment by richardbuckle** [comment]
Aha, if that key was missing then that would explain everything. That key is what registers the custom URL protocol "eddi:" with the OS and web browsers. Usually when it is missing it is because some over-zealous anti-virus software interfered with EDDI's installer. Another possibility is that EDDI was installed as Asministrator but is being run as a regular user.

@Tkael That key is supposed to be self-repairing: see `EddiCompanionAppService.CustomURLResponder.RegisterAppPath()`. An error should be logged if that fails.

**Comment by Tkael** [comment]
Perhaps the code you're referencing isn't triggering in this case? It's conditional on `absoluteAppPath` not being null. Ref. https://github.com/EDCD/EDDI/blob/ed57c070a15dca1062b758bf7e195aa11fec71da/CompanionAppService/CustomURLResponder.cs#L40-L43.

**Comment by Tkael** [comment]
Ok, @richardbuckle I've got this issue on my own setup now and am trying to trace it down. It looks like `RegisterAppPath()` is triggering after all. 

I've checked my registry and this is the current state:
```
[HKEY_CURRENT_USER\Software\Classes\eddi]
@="URL Protocol eddi"
"URL Protocol"=""

[HKEY_CURRENT_USER\Software\Classes\eddi\Default Icon]
@="C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\bin\\Debug\\EDDI.exe,0"

[HKEY_CURRENT_USER\Software\Classes\eddi\shell]

[HKEY_CURRENT_USER\Software\Classes\eddi\shell\open]

[HKEY_CURRENT_USER\Software\Classes\eddi\shell\open\command]
@="\"C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\bin\\Debug\\EDDI.exe\" \"%1\""

[HKEY_CURRENT_USER\Software\Classes\eddi\shell\open\ddeexec]
@="%1"
```
[eddi.reg.zip](https://github.com/EDCD/EDDI/files/4641326/eddi.reg.zip)

Any ideas?

**Comment by Tkael** [comment]
@richardbuckle New observations: 
- If I reinstall EDDI, that reinstalled version of EDDI is able to authenticate successfully.
- There is a difference in the registry before and after running the RegisterAppPath() method. For all registery keys, we see "**EDDI** URL Protocol" when first installed. After running, **most** keys are changed to "URL Protocol **eddi**" via the RegisterAppPath() method but there is an exception:
  - `[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\eddi]` has "**EDDI** URL Protocol" (the key used from the installer) while
  - `[HKEY_CURRENT_USER\Software\Classes\eddi]` has "URL Protocol **eddi**",
  - `[HKEY_CLASSES_ROOT\eddi]` has "URL Protocol **eddi**",
  - `[HKEY_USERS\...\Software\Classes\eddi]` has "URL Protocol **eddi**", and
  - `[HKEY_USERS\..._Classes\eddi]` has "URL Protocol **eddi**"
- Changing `RegisterAppPath()` to match the installed key appears correct the error by making the key consistent between runs.
  - If I run the installer then the version with the changed RegisterAppPath() method I am able to connect.
  - If I run the installer then the version without the changed RegisterAppPath() method then I am unable to connect / EDDI is reported as already running.

Possible solutions? 
- Change the installer key to match the method key.
- Change the method key to match the installer key.
- Expand the `RegisterAppPath()` method to include setting keys to `HKEY_LOCAL_MACHINE`

**Comment by richardbuckle** [comment]
This entire technique is a legacy wart from when MS were rather less competent. 

The name "EDDI URL Protocol" vs "URL Protocol eddi" is neither here nor there.

I favour changing the method key to match the installer key.

**Comment by Tkael** [comment]
Hmm. And now I'm finding myself unable to replicate my earlier finding. :-(
For the time being, I'd better leave this to you.

**Comment by Tkael** [comment]
Superseded by #1786.
