### ISSUE TITLE
Data not sent to EDDN

### ISSUE THREAD

**Issue by TalShaf** [EDCD/EDDI#174]
Market data isn't being sent to EDDN when I dock. I've turned on verbose logging and found these two error messages:

`2017-10-21T22:18:19 EDDNResponder:handleRawEvent [D] Missing current starsystem information, cannot send message to EDDN `

and then:
`
2017-10-21T22:18:26 EDDNResponder:sendMessage [D] Response content is FAIL: [<ValidationError: "None is not of type u'string'">] `

I've tried turning the EDDN plugin off and on again, I've tried restaring EDDI and reauthenticated my cAPI credentials. I've also jumped to other systems and tried at other stations with no success.

**Comment by Hoodathunk** [comment]
What version of EDDI are you running?

**Comment by Tkael** [comment]
I checked my own logs and reviewed the EDDN message output here: https://ross.eddb.io/eddn/log?parsing_result=&parsing_result_detail=&header_software_name=EDDI&schema=&schema_main_group=&schema_sub_group=10&system_id=&station_id=&body_id=

Messages are going through, so this seems to be isolated to your PC... something to do with your specific config perhaps? Is this a continuing problem? If so, could you attach a more complete log showing the issue?

**Comment by TalShaf** [comment]
I am running EDDI 2.4.1.

**Comment by Tkael** [comment]
odd. I'm afraid there isn't much more we can do without the log though

**Comment by TalShaf** [comment]
Herte is the log file. After more testing, it seems some of that data IS being sent, but not all. Only the journal schema was sent. Wne I tried using EDMC, all schemas were sent. 

[eddi.log](https://github.com/EDCD/EDDI/files/1404735/eddi.log)

**Comment by TalShaf** [comment]
After more testing, here what's I've found:

1. When docking at a large orbital station, only the journal/docked schema is sent. If I then undock and redock, EDDI sends all schemas.

2. When docking at a small station (outposts, etc.), all schemas are immediately sent.

**Comment by Hoodathunk** [comment]
Issue found and corrected.
