### ISSUE TITLE
Feature: EDDI should recover scripts when crashing 

### ISSUE THREAD

**Issue by JPVenson** [EDCD/EDDI#1742]
## EDDI version in which issue is found
0bcad4c 3.5.2

## Steps to reproduce
1. Sometimes EDDI seems to crash for no reason while in the Script editor.

## Expected
After restarting EDDI a script backup should be recovered

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Darkcyde13** [comment]
The only time I've had EDDI crash while in the script editor, is when I've messed up the script and got it stuck in a never ending loop.

If I've made a lot of changes before saving or running a test, I always just highlight the whole script and do a simple CTRL-C to copy it.  Makes life so much easier. :)

**Comment by Tkael** [comment]
Yes. The PR that's being considered for this would essentially automate that and save a backup copy of the script that will be no more than 3 seconds out of date from your last edit. :-)

**Comment by Tkael** [comment]
Merged.
