### ISSUE TITLE
Route details script handling scoop parameter

### ISSUE THREAD

**Issue by philcart** [EDCD/EDDI#1750]
## EDDI version in which issue is found
3.5.2

## Steps to reproduce
1. Jump into system with very low fuel and scoopable stars (I jumped into [Bleae Thua EC-D d12-12](https://www.edsm.net/en/system/id/6829338/name/Bleae+Thua+EC-D+d12-12))

## Expected
EDDI should tell me to scoop from the stars within the system (see screenshot)
![2020-04-26 16-07-17 Bleae Thua EC-D d12-12-Bleae Thua EC-D d12-12 A](https://user-images.githubusercontent.com/4084083/80313418-2642b300-882e-11ea-9061-793dbd796353.png)

## Observed
EDDI tells me the following (taken from the speechresponder.out file)
"Jump in progress. GYPSY ROVER is travelling to the Bleae Thua E C dash D d 12 dash 12 system. Caution: neutron star detected. This is your first visit to this system. You are over 2 and a half thousand lightyears from Shinrarta Dezhra.
It is currently 02:04 AM. Warning: Fuel tanks now almost depleted.  Your nearest scoopable star is in the Bleae Thua BG-H b51-7 system, 3.8 lightyears away.  Fuel scooping is strongly recommended."

## Investigation
The RouteDetails script is called in the "Fuel Check" script at line 34.
`{set scoop_system to RouteDetails('scoop', detail.distance)}`

Not 100% on the syntax, but I'm guessing 'scoop' is the parameter used for the type variable in the Route details script at line 12
`{set type to event.routetype}`

There is nothing in the Route details script if the type is 'scoop'.

**Comment by Darkcyde13** [comment]
Just my two cents, but it would seem that system.scoopable (in the fuel check script) must have been false, meaning that the system you were in (?) didn't have a scoopable star.

A quick look at that system (Bleae Thua EC-D d12-12), and it contains a Neutron star and an L class Brown dwarf, neither of which are scoopable, at least as far as I can tell form various ED sites.

**Comment by Tkael** [comment]
You can get a boost from a neutron star but I'm pretty sure that it doesn't add any fuel to the tank.

**Comment by Tkael** [comment]
That said, `Bleae Thua EC-D d12-12 C` is a scoopable star first discovered in 2017 for EDSM. We'll have to look at why the script didn't recommend that star.

**Comment by Darkcyde13** [comment]
OK, that's weird.  I went to EDSM earlier to check, and that entire section for the third star wasn't there. WTH??

Hmm, I just tried again, and it took a long time to load the page, so maybe it just didn't fully load last time. :(

**Comment by Darkcyde13** [comment]
As a side note (and correct me if I'm wrong) RouteDetails() is mainly an internal function of EDDI, and the script is there to deal with it's output.  So there doesn't have to be a section in the script for 'scoop' for the function to do what it needs.

**Comment by Tkael** [comment]
I've done a bit of investigating and submitted a PR to better handle scenarios where non-primary stars in the current system are known to be scoopable.
