### ISSUE TITLE
Mission complete event not reporting the mission type

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1754]
## EDDI version in which issue is found
v3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Hand in (complete) a mission.

## Expected
EDDI to say "Data Courier mission completed. You have been awarded over 47 and a half thousand credits."

## Observed
EDDI says "mission completed. You have been awarded over 47 and a half thousand credits."

## Investigation
I've been running missions in Colonia, and realised that when handing them in, EDDI wasn't actually reporting what the mission type was.

So, I flipped back to the EDDI default personality and ran a couple of test missions.  The first was a depot mission, and the second a data courier mission (both run separately).

For the first depot mission I got these when accepting and handing in:

> You have accepted a Delivery mission for People of Colonia in this time of civil conflict.. You have 1 mission.
> mission completed. You have received well over 939 thousand credits. Additionally, 4 units of Biotech Conductors have been received.

For the second mission, I got these:

> Data Courier mission for Jaques accepted in this time of outbreak relief. This is your 1st mission.
> mission completed. You have been awarded over 47 and a half thousand credits.

Here's the Journal events for completing the missions:

`{ "timestamp":"2020-04-29T20:14:11Z", "event":"MissionCompleted", "Faction":"People of Colonia", "Name":"Mission_Delivery_CivilUnrest_name", "MissionID":572566339, "Commodity":"$PerformanceEnhancers_Name;", "Commodity_Localised":"Performance Enhancers", "Count":72, "TargetFaction":"Jaques", "DestinationSystem":"Deriso", "DestinationStation":"Talalay Retreat", "Reward":939631, "MaterialsReward":[ { "Name":"BiotechConductors", "Name_Localised":"Biotech Conductors", "Category":"$MICRORESOURCE_CATEGORY_Manufactured;", "Category_Localised":"Manufactured", "Count":4 } ], "FactionEffects":[ { "Faction":"Jaques", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_Outbreak_down;", "Effect_Localised":"With fewer reported cases of illness, $#MinorFaction; hope they have prevented a full outbreak in the $#System; system.", "Trend":"DownGood" } ], "Influence":[ { "SystemAddress":71536135676490, "Trend":"UpGood", "Influence":"++++" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"People of Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" } ] }
`

`{ "timestamp":"2020-04-29T20:33:27Z", "event":"MissionCompleted", "Faction":"Jaques", "Name":"Mission_Courier_Outbreak_name", "MissionID":572593627, "TargetFaction":"Jaques", "DestinationSystem":"Colonia", "DestinationStation":"Jaques Station", "Reward":47760, "FactionEffects":[ { "Faction":"Jaques", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" }, { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":71536135676490, "Trend":"UpGood", "Influence":"+" }, { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"+" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }`

I then made a copy of the default, and added these lines:
```
EDName type: {mission.typeEDName}.
Localised type: {mission.type}.
```

When handing in another data courier mission, both of these variables were empty:

> EDName type:. Localised type:. mission completed. You have been awarded nearly 11 thousand credits.

I also noticed that `.type` and `.typeEDName` are not colored the same as other variables such as `.passengertype` or `.faction`.

**Comment by Tkael** [comment]
EDDI does not create a new mission object in response to a `Mission completed` event - the mission has already exist in the mission monitor before the `Mission completed` event is logged. 

The `Mission completed` script attempts to look up the mission object created when the mission was generated using
```
{set mission to MissionDetails(event.missionid)}
```
If no mission is found, the `mission` object will be empty with no properties. 

Were these both missions which were showing in the mission monitor prior to handing them in?

**Comment by Darkcyde13** [comment]
To be honest, I didn't look at the Missions tab to see, but all missions were done in the same session, without reloading EDDI or Elite, so I would assume they were there.

However, I have just run another depot mission to check.  This I did with the EDDI default personality from start to finish to be sure, and checked the Missions tab just before completing it.  The result was the same, no missions type reported upon completion, and the Missions tab immediately prior to the hand in looked like this:
![image](https://user-images.githubusercontent.com/24360725/81303048-19fef700-9073-11ea-9dea-73152af945de.png)
After handing it in, the mission disappeared from the Missions tab, so it must have got the correct missionid from there.  This is the text from the speechresponder.out file:
> You have delivered 2 tonnes of Consumer Technology to the mission depot.  Solo mission requirements are now completed.
> mission completed. You have received around 1 and a half million credits. Also, 4 units of Modified Embedded Firmware have been awarded.

**Comment by Hoodathunk** [comment]
I have a branch which (among other things) added/revised faction states, along with updating scripts.

I'm splitting off the faction states into a separate branch now... I think my update resolves this but will verify before I PR.

**Comment by Tkael** [comment]
Fixed by #1783.

**Comment by Darkcyde13** [comment]
I've just been doing a few missions in Colonia again, using EDDI v3.7.0, and I'm getting the same problem again.  Missions are in the Missions Monitor, listed as "Data Courier", but the mission type is not being reported on hand-in.

I get this in speechresponder.out "You have been awarded 100 thousand credits for successful mission completion."

The event from the journal is:
```
{ "timestamp":"2020-07-08T14:28:48Z", "event":"MissionCompleted", "Faction":"People of Colonia", "Name":"Mission_Courier_CivilUnrest_name", "MissionID":605237136, "TargetFaction":"GalCop Colonial Defence Commission", "DestinationSystem":"Ogmar", "DestinationStation":"Dervish Platform", "Reward":100000, "FactionEffects":[ { "Faction":"GalCop Colonial Defence Commission", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":84180519395914, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"People of Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" } ] }
```

This was just the last one I had, but all the missions were in the Missions Monitor (I took four Data Courier missions from the same station) and each one was removed from the monitor when I handed them in.

**Comment by Tkael** [comment]
Was the output the same for all four missions? If so, please provide all of the applicable journal events.

**Comment by Darkcyde13** [comment]
Yes, all four failed to say what the missions type was.  This is the output in speechresponder.out:

> You have received 55 thousand credits for successfully completing the mission.

> mission completed. You have been awarded just over 268 thousand credits.

> mission completed. You have received over 158 thousand credits.

And these are the journal entries:
```
{ "timestamp":"2020-07-08T13:47:36Z", "event":"MissionCompleted", "Faction":"People of Colonia", "Name":"Mission_Courier_CivilUnrest_name", "MissionID":605237017, "TargetFaction":"Colonia Council", "DestinationSystem":"Hephaestus", "DestinationStation":"Malik Station", "Reward":55000, "FactionEffects":[ { "Faction":"People of Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"+" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"Colonia Council", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":7764461265482, "Trend":"UpGood", "Influence":"+" } ], "ReputationTrend":"UpGood", "Reputation":"++" } ] }


{ "timestamp":"2020-07-08T13:56:34Z", "event":"MissionCompleted", "Faction":"People of Colonia", "Name":"Mission_Courier_CivilUnrest_name", "MissionID":605237093, "TargetFaction":"Tenjin Pioneers Colonia", "DestinationSystem":"Kojeara", "DestinationStation":"Oswald Park", "Reward":268189, "FactionEffects":[ { "Faction":"Tenjin Pioneers Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":59166629864010, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" }, { "Faction":"People of Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }


{ "timestamp":"2020-07-08T14:14:15Z", "event":"MissionCompleted", "Faction":"People of Colonia", "Name":"Mission_Courier_CivilUnrest_name", "MissionID":605236943, "TargetFaction":"GalCop Colonial Defence Commission", "DestinationSystem":"Alberta", "DestinationStation":"Berman Market", "Reward":158458, "FactionEffects":[ { "Faction":"GalCop Colonial Defence Commission", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":2741931033745, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" }, { "Faction":"People of Colonia", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }
```

**Comment by Hoodathunk** [comment]
@Tkael, with all the async processing we've added, it's possible that the mission is removed from the list before the script is called and `{set mission to MissionDetails(event.missionid)}` is returning null.

Could try pushing the `Mission completed` event handler into `PostHandle` processing. I'll take a look.

**Comment by Hoodathunk** [comment]
DC, dig a little deeper and investigate the state of the `mission` variable in the script.

**Comment by Tkael** [comment]
@hoodathunk Good thinking. The pre-handler should set the mission status to completed (if it does anything) while the post handler should clear it.

**Comment by Darkcyde13** [comment]
Sorry this took so long, today has been a hectic day. :/  Hopefully this is what you were looking for...

Testing:
 I took three missions, 1x Data Courier and 2x Transport Cargo.
 I setup a new script with this code:
```
{for mission in missions:
    ID: {mission.missionid},
    Name: {mission.name},
    Local Name: {mission.localisedname},
    Type: {mission.type},
    Status: {mission.status},
    Faction: {mission.faction},
    Origin System: {mission.originsystem},
    Origin Station: {mission.originstation},
    Origin Return: {mission.originreturn},
    Destination System: {mission.destinationsystem},
    Destination Station: {mission.destinationstation},
    Destination Systems: {mission.destinationsystems},
    Influence: {mission.influence},
    Reputation: {mission.reputation},
    Reward: {mission.reward},
    Legal: {mission.legal},
    Wing: {mission.wing},
    Shared: {mission.shared},
    Communal: {mission.communal},
    Commodity: {mission.commodity},
    Passenger Type: {mission.passengertype},
    Passenger VIP's: {mission.passengervips},
    Passenger Wanted: {mission.passengerwanted},
    Target: {mission.target},
    Target Type: {mission.targettype},
    Target Faction: {mission.targetfaction},
    Amount: {mission.amount},
    Expiry: {mission.expiry},
    Expiry Seconds: {mission.expiryseconds}.
}
```
I then run this script with the following result (separated for clarity):

> ID: 605836004, Name: Mission_Courier_CivilUnrest, Local Name: Sensitive Data Delivery, Type: Data Courier, Status: Active, Faction: Holloway Bioscience Institute, Origin System: Colonia, Origin Station: Colonia Orbital, Origin Return:, Destination System: Ratraii, Destination Station: Bonestell Point, Destination Systems:, Influence: ++, Reputation: +, Reward: 42269, Legal: true, Wing:, Shared:, Communal:, Commodity:, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction: Brian's Thugs, Amount: 0, Expiry:, Expiry Seconds: 1594397860.
> 
> ID: 605836861, Name: Mission_Delivery_CivilUnrest, Local Name: Help quell civil unrest by transporting 28 units of Biowaste, Type: Delivery, Status: Active, Faction: Holloway Bioscience Institute, Origin System: Colonia, Origin Station: Colonia Orbital, Origin Return:, Destination System: Deriso, Destination Station: Giles Station, Destination Systems:, Influence: ++, Reputation: ++, Reward: 388164, Legal: true, Wing:, Shared:, Communal:, Commodity: Bio-waste, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction: Colonia Co-operative, Amount: 28, Expiry:, Expiry Seconds: 1594397859.
> 
> ID: 605837154, Name: Mission_Delivery_CivilUnrest, Local Name: Help quell civil unrest by transporting 28 units of Biowaste, Type: Delivery, Status: Active, Faction: Holloway Bioscience Institute, Origin System: Colonia, Origin Station: Colonia Orbital, Origin Return:, Destination System: Deriso, Destination Station: Giles Station, Destination Systems:, Influence: ++, Reputation: ++, Reward: 388164, Legal: true, Wing:, Shared:, Communal:, Commodity: Bio-waste, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction: Societas Eruditorum de Civitas Dei, Amount: 28, Expiry:, Expiry Seconds: 1594397860.

I then added the same code (without being in a For loop) just after the line that sets 'mission' in the 'Mission complete' script.  (I think that should still work, right?).  I then went to hand them all in...


For the first mission:

speechresponder.out:
"mission completed. You have received over 42 thousand credits."

Journal event:

> { "timestamp":"2020-07-09T16:39:33Z", "event":"MissionCompleted", "Faction":"Holloway Bioscience Institute", "Name":"Mission_Courier_CivilUnrest_name", "MissionID":605836004, "TargetFaction":"Brian's Thugs", "DestinationSystem":"Ratraii", "DestinationStation":"Bonestell Point", "Reward":42269, "FactionEffects":[ { "Faction":"Brian's Thugs", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":20958600798794, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" }, { "Faction":"Holloway Bioscience Institute", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }

Script variables check:

> ID:, Name:, Local Name:, Type:, Status:, Faction:, Origin System:, Origin Station:, Origin Return:, Destination System:, Destination Station:, Destination Systems:, Influence:, Reputation:, Reward:, Legal:, Wing:, Shared:, Communal:, Commodity:, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction:, Amount:, Expiry:, Expiry Seconds:.


Second mission:

speechresponder.out:
"You have received just over 388 thousand credits for successful mission completion."

Journal event:

> { "timestamp":"2020-07-09T16:59:09Z", "event":"MissionCompleted", "Faction":"Holloway Bioscience Institute", "Name":"Mission_Delivery_CivilUnrest_name", "MissionID":605836861, "Commodity":"$Biowaste_Name;", "Commodity_Localised":"Biowaste", "Count":28, "TargetFaction":"Colonia Co-operative", "DestinationSystem":"Deriso", "DestinationStation":"Giles Station", "Reward":388164, "FactionEffects":[ { "Faction":"Holloway Bioscience Institute", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_Outbreak_down;", "Effect_Localised":"With fewer reported cases of illness, $#MinorFaction; hope they have prevented a full outbreak in the $#System; system.", "Trend":"DownGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"Colonia Co-operative", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_Outbreak_up;", "Effect_Localised":"Without medical support, $#MinorFaction; may soon be forced to declare a state of outbreak in the $#System; system.", "Trend":"UpBad" } ], "Influence":[ { "SystemAddress":71536135676490, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" } ] }

Script variable check:

> ID:, Name:, Local Name:, Type:, Status:, Faction:, Origin System:, Origin Station:, Origin Return:, Destination System:, Destination Station:, Destination Systems:, Influence:, Reputation:, Reward:, Legal:, Wing:, Shared:, Communal:, Commodity:, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction:, Amount:, Expiry:, Expiry Seconds:.


Third mission:

speechresponder.out:
"mission completed. You have been awarded just over 388 thousand credits."

Journal event:

> { "timestamp":"2020-07-09T17:01:42Z", "event":"MissionCompleted", "Faction":"Holloway Bioscience Institute", "Name":"Mission_Delivery_CivilUnrest_name", "MissionID":605837154, "Commodity":"$Biowaste_Name;", "Commodity_Localised":"Biowaste", "Count":28, "TargetFaction":"Societas Eruditorum de Civitas Dei", "DestinationSystem":"Deriso", "DestinationStation":"Giles Station", "Reward":388164, "FactionEffects":[ { "Faction":"Holloway Bioscience Institute", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_Outbreak_down;", "Effect_Localised":"With fewer reported cases of illness, $#MinorFaction; hope they have prevented a full outbreak in the $#System; system.", "Trend":"DownGood" } ], "Influence":[ { "SystemAddress":3238296097059, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"Societas Eruditorum de Civitas Dei", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_Outbreak_up;", "Effect_Localised":"Without medical support, $#MinorFaction; may soon be forced to declare a state of outbreak in the $#System; system.", "Trend":"UpBad" } ], "Influence":[ { "SystemAddress":71536135676490, "Trend":"UpGood", "Influence":"++" } ], "ReputationTrend":"UpGood", "Reputation":"++" } ] }

Script variable check:

> ID:, Name:, Local Name:, Type:, Status:, Faction:, Origin System:, Origin Station:, Origin Return:, Destination System:, Destination Station:, Destination Systems:, Influence:, Reputation:, Reward:, Legal:, Wing:, Shared:, Communal:, Commodity:, Passenger Type:, Passenger VIP's:, Passenger Wanted:, Target:, Target Type:, Target Faction:, Amount:, Expiry:, Expiry Seconds:.


So, assuming I've done that right, it looks like the mission data is being cleared before the script is triggered, as you you've suggested.  If I have screwed up with collection the 'mission' data, let me know and I'll try again.

**Comment by Hoodathunk** [comment]
Yup, `{set mission to MissionDetails(event.missionid)}` is returning null. Okay, on it.

**Comment by Hoodathunk** [comment]
Yup, `{set mission to MissionDetails(event.missionid)}` is returning null. Okay, on it.
