### ISSUE TITLE
EDDI can be abused to report false time-stamps to EDDN

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1761]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A	

## Steps to reproduce
1. Manipulate your system clock to read a future date and time.
2. Observe that DateTime.UTCNow() no longer reports an actual accurate time.
3. Observe that DateTime.UTCNow() timestamps are now offset from game timestamps (which are set from an independent server)
4. Note that CAPI data is reported to EDDN using DateTime.UTCNow. 

## Expected
Timestamps reported to EDDN from CAPI and from the player journal should be consistent.

## Observed
Timestamps reported to EDDN from the player journal are consistent but timestamps reported to EDDN from CAPI (using system time) are not consistent.

## Investigation
Per discussion in EDSM Discord, EDDI has reported 1619 events (out of 2,338,671) with a timestamp more than 10 minutes in the future since 2020-01-01.

> Sum(message_timestamp > gateway_timestamp, (message_ts-gateway_ts) > 600, gateway_timestamp >= '2020-01-01'):
 ```
Software                       count(*)
 E:D Market Connector [Windows]        2
 EDDI                              1,619
 EDDiscovery                          12
 EDSM - Console                      475
 Elite G19s Companion App             30
 EVA [iPad]                            6
 NIX                                  74
```

Breaking the future data down by schema, EDDI journal schema is accurate but schemas reported using CAPI data were less so.

 ```
Software                         Schema        diff_600        count_all
 EDDI                             Commodity          453          229,471
 EDDI                             Journal              0        1,767,934
 EDDI                             Outfitting         669          187,252
 EDDI                             Shipyard           497          154,014
```

**Comment by Tkael** [comment]
Possible solutions:
- Periodically check the local system time against a network server time. Disable sending CAPI data through the EDDN responder and alert the user if the difference exceeds a threshold value. 
- Look at the difference between journal time and system time as journal events are handled. Apply this as an offset to timestamps reported from CAPI. 
- Look at the difference between journal time and EDDN response headers as journal events are handled. Apply this as an offset to timestamps reported from CAPI.

**Comment by bgol** [comment]
Additional possible solutions:
* Use the [`Date` header field](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) the CAPI response as timestamp (EDMC does is this way).
```python
data['timestamp'] = time.strftime('%Y-%m-%dT%H:%M:%SZ', parsedate(r.headers['Date']))
```

**Comment by richardbuckle** [comment]
I favour using the CAPI response as an additional trigger _when the CAPI is configured_, but remember that the CAPI credentials are not part of the open source repo, so EDDI is expected to build and run out of the box without the CAPI configured. 

Therefore I think we treat differences between journal timestamps and local time of receipt as triggers too.

Where I differ is on steps to take. It is 2020 and we have NNTP everywhere. If someone's machine's system clock is off by more than a second or so, I suspect shenanigans and I think EDDI should go into safe mode (which includes immediately halting all uploads) and only go back when it sees a `Fileheader` event with a plausible timestamp.

Thoughts welcomed.

**Comment by richardbuckle** [comment]
Possibly the system clock should be entirely disregarded and that way both Journal and CAPI code paths are using both timestamps from server sources.

**Comment by Tkael** [comment]
When we have a journal timestamp, we're already using it. It's only when working with CAPI data that we're referencing system time. Thus a solution that uses the CAPI response to provide a timestamp for CAPI should be very viable.

**Comment by Tkael** [comment]
All of the potentially affected data is all passed to the EDDN Responder using a `MarketInformationUpdatedEvent`.

- ✔️ [Updates from Market.json use the Market.json timestamp.](https://github.com/EDCD/EDDI/blob/ed57c070a15dca1062b758bf7e195aa11fec71da/EDDI/EDDI.cs#L1481-L1523)
- ✔️ [Updates from Outfitting.json use the Outfitting.json timestamp.](https://github.com/EDCD/EDDI/blob/ed57c070a15dca1062b758bf7e195aa11fec71da/EDDI/EDDI.cs#L1525-L1568)
- ✔️ [Updates from Shipyard.json use the Shipyard.json timestamp.](https://github.com/EDCD/EDDI/blob/ed57c070a15dca1062b758bf7e195aa11fec71da/EDDI/EDDI.cs#L1570-L1613)
- ❌ [Updates from CAPI use system time.](https://github.com/EDCD/EDDI/blob/ed57c070a15dca1062b758bf7e195aa11fec71da/EDDI/EDDI.cs#L2591-L2677)

**Comment by richardbuckle** [comment]
OK cool, we can stop using the system clock completely then.

**Comment by GioVAX** [comment]
Another possible approach is to go for our internal time provider component.
At application startup, we can get the current time from a NNTP server and register the offset from the local system time. Any future time requests will return the local system time plus the offset.

Finally, intercepting [TImeChanged](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.timechanged?view=dotnet-plat-ext-3.1) we can re-evaluate the offset if/when necessary.

PRO: we would have a time component that is fully independent from anything
CONS: adds complexity and we would need to change all the places where time is used.

**Comment by richardbuckle** [comment]
For a very minority abuse case that has no honest explanation, I'd lean towards a minimal solution: don't trust the system clock and if a discrepancy occurs, put EDDI into safe mode.

I have ZERO time to waste on trying to remediate this. If somebody has a bad system clock in 2020 then assume that they are a bad actor.

**Comment by GioVAX** [comment]
@richardbuckle, I totally agree about not investing too much effort to handle a few cases.

Not knowing the codebase, I could not judge how much work was required to "put EDDI into safe mode", hence my approach was kind of all-out 😃
