### ISSUE TITLE
Vehicle variable not always correct at start up.

### ISSUE THREAD

**Issue by Labanden** [EDCD/EDDI#1776]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
CMDR in SLF at load up of game. near ship. 

Sometimes reports Ship and sometimes not set
Question: Does the API to Frontier have to be active?
Question: Can an event for LoadGame be created as that includes data I could use, and not just the ship.

**Comment by Tkael** [comment]
I believe that this was a bug in the object comparison used to determine when we write values to VoiceAttack and that it's already been fixed for the next release.

**Comment by Labanden** [comment]
Brian,
Thanks for your reply.



Regards
Alan Bend
T: 01202 572215 | M: 07522244731 | E: Alan.Bend@Kinsonhold.co.uk<mailto:Alan.Bend@Kinsonhold.co.uk>
P Please don't print this e:mail unless it's really necessary.
________________________________

**Comment by Tkael** [comment]
Sure thing. I'm going to close this issue for now. Feel free to respond here or open a new issue if it recurs after the next beta version of EDDI is released.
