### ISSUE TITLE
EDDI Core: Switch endpoint for static server reference files

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#178]
## Observed
(Broken out from issue #97)
EDDI relies on data from http://api.eddp.co, which we do not control. Data from this server should be transitioned to an endpoint that we can influence.

## Investigation
EDDP is used in DataDefinitions/BlueprintMaterials.cs with http://api.eddp.co/_blueprintrequirements, in MaterialMonitor/MaterialMonitor.cs with http://api.eddp.co/_materiallocations and http://api.eddp.co/_materialuses.

**Comment by Tkael** [comment]
Alternatively, material / blueprint data could be referenced from https://github.com/msarilar/EDEngineer/tree/master/EDEngineer/Resources/Data or some other actively managed source. Maybe a common repository for this data in EDCD?

**Comment by richardbuckle** [comment]
I too would favour a common EDCD repository.

**Comment by Tkael** [comment]
Completed on PR #282.
