### ISSUE TITLE
Doesn't count system visits properly.

### ISSUE THREAD

**Issue by legarth** [EDCD/EDDI#1784]
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Visit any system that has been previously visited.

## Expected
Reporting increasing mounts of visits.

## Observed
Always reports "This is your first visit to this system".

## Investigation
I have tried deleting the local database and downloaded the log from EDSM as suggested here: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/126 but and it worked for one visit but then reverted to first visit again.

**Comment by Tkael** [comment]
Please re-test with recently released version [3.5.3-b1](https://github.com/EDCD/EDDI/releases/download/Release%2F3.5.3-b1/EDDI-3.5.3.b1.exe)? Thanks!

**Comment by Tkael** [comment]
I've been paying attention to this for the last several days and have not been able to replicate your findings. Is the visit count still incorrect on every jump?

**Comment by legarth** [comment]
Hey,

I haven't tied tie new version as you suggested yet. But it seems to work pretty inconsistently.  Sometimes it counts above 1 but then reverts back. First I thought it reset on new play sessions but I guess that doesn't make much sense as EDDI runs separately to the client.

Let me try and install the suggested version tonight (UK time) and see if that fixes it.

Ps. I've never heard it count higher that 2, but I didn't know if that's just because it is only set to read out specific visit counts. 

M

**Comment by Tkael** [comment]
I've submitted a speculative fix that I think should help prevent EDDI from dropping visits if there's an issue with the connection to EDSM or if the user doesn't sync visits to EDSM. Ref. #1803.

**Comment by Kedriv** [comment]
Hi,
I am experiencing the same issue. I am using version 3-5-3b1. It is somewhat inconsistent for me. Sometimes the count is correct and sometimes it is not correct.

**Comment by Tkael** [comment]
Please re-test with version 3.5.3-b3.

**Comment by legarth** [comment]
Ok just resinstalled 3.5.3-b3. Do I need to redownload the EDSM log?

**Comment by Tkael** [comment]
It's probably not required but wouldn't hurt to do so.
