### ISSUE TITLE
Reporting incorrect distance to home system

### ISSUE THREAD

**Issue by philgschmidt** [EDCD/EDDI#1799]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.5.3-b1
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
1.8.5
## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
1. Identify home system (i.e. Colonia) in EDDI app
2. Fly 22000ly away to bubble
3. When jumping into systems EDDI voice says we are 130ly from home system
## Expected
[Describe what you expected to happen]
As of last version it would correctly say 22000ly
## Observed
[Describe what happened instead]
It says 130ly
## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
Tried in various systems and always the same

**Comment by Tkael** [comment]
Please provide for review the following files from `%appdata%/EDDI`:
1. eddi.json
2. the eddiX.log file where this occurred (one log file is generated per time that EDDI is opened, so it may be eddi1.log, eddi2.log, etc.)

**Comment by Tkael** [comment]
3. Please also indicate if the `Reset` button is enabled on the `FSD engaged` script (if so, you may have a modified version of that script).

**Comment by philgschmidt** [comment]
Only this user.config was in the appdata dir.

I'm not sure what the 'reset' button is.

**Comment by Tkael** [comment]
For 1 and 2, the typical path to the directory is `C:\Users\[Your Windows Account Name]\AppData\Roaming\EDDI`
For 3, I'm referencing this button:
![Untitled](https://user-images.githubusercontent.com/4382539/83468179-db214e80-a430-11ea-9b4e-beab97bc86ef.png)
In the pictured example, the button for `FSD enaged` is enabled while the button for the surrounding scripts is not.

**Comment by philgschmidt** [comment]
Ok, I didn't know to look in /roaming/,

and Yes, my EDDI app does show a Reset button for the FSD script.

**Comment by philgschmidt** [comment]
I'd created a copy personality to reduce some HCS voicepack overlap. I
guess some of the personality scripts have changed but I never updated my
copy.
I'm betting that's the issue here.

**Comment by Tkael** [comment]
It may be. Let's try resetting that first just in case something is coded into your current script that's causing the issue. 

If that doesn't work, the next step would be to review the files I requested above.

**Comment by philgschmidt** [comment]
Thanks!

I've finally started to view and understand the scripts. As a developer I
am impressed with the thoroughness of your project (docs, extensible
design, etc)
The EDDI function System distance report has both reportsystem and system
object set to the current system. I see that jumps to arrival works.

The context variable state.eddi_context_system_system is set to the same as
the system global.

Have you removed the 'distance to home system' call from EDDI, or is that
called somewhere else?

**Comment by philgschmidt** [comment]
Sorry for the slightly confused email before, Its the FSD

{DEC:System distance from home} is also not set.

Let me know if you need more info. Or have any guidance for me.

Thx!

**Comment by philgschmidt** [comment]
It worked when I edited the FSD engaged script to this:

 {if reportsystem.distancefromhome:
>             {set ReportDistanceFromHome() to:
>                 {return cat(
>                     OneOf("You are", "Current location is", "You are now"
> ), " ",
>                     Humanise(Distance(homesystem.x,homesystem.y,homesystem
> .z,reportsystem.x,reportsystem.y,reportsystem.z)), " lightyears from ",
>                     OneOf("home", "{P(homesystem.name)}"), "."
>                 )}
>             }
>             {ReportDistanceFromHome()}

  }


>

**Comment by Tkael** [comment]
Yes, that's a viable solution. It seems that `reportsystem.distancefromhome` was probably not set correctly (that also would explain `{DEC:System distance from home}` not being set).
The variable should be updated every time the system state changes, but without logs or similar data it's very difficult for to identify the specific scenario that you are (or were?) experiencing with this variable.
Is the variable still being set incorrectly? If so, please share those log files that we requested so that we can investigate further.

**Comment by Tkael** [comment]
Closing. We've done all we can without reviewing the logs.

**Comment by philgschmidt** [comment]
I sent a stack of logs and the .json file, were they not the right ones?

Phil Schmidt
917 449 8672
pschmidt@tenbones.com

**Comment by Tkael** [comment]
I didn't receive those. I'm guessing that you must have attached them to an email response and as far as I'm aware Github isn't able to handle email attachments. You would need to open this Github issue and attach the files directly.

**Comment by philgschmidt** [comment]
No, They are all attached to an email in this thread from June 3rd, 2:13 AM

Let me know if I need to resend them, or if I sent the wrong stuff.

Thanks!

**Comment by Tkael** [comment]
When you respond with an email attachment, that isn't available for me to view in the ticket so no files were attached to this ticket on June 3rd. Please zip up the files, open this Github ticket, and then drag/drop the zip file into the text box where you are replying to this ticket.
