### ISSUE TITLE
Inara not updating with faction influence data

### ISSUE THREAD

**Issue by zcampau** [EDCD/EDDI#1804]
## EDDI version in which issue is found
v.3.5.3-b2

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Launch EDDI first
2. Launch E:D game client second
3. Already docked at a station, take any action such as change ships. Check influence of minor faction and take note of it.

## Expected
4. Expected: Inara.cz reflects the latest faction influence data

## Observed
4. Observed: Inara.cz reflects minor faction data from previous day

## Investigation
Verified eddn, inara, frontier api are enabled and report as operational. Restarted both eddi app and game client.
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/4725346/eddi_issue.zip)

**Comment by Tkael** [comment]
No new location event was generated during the logged session. The EDDN responder will not send data under these conditions - a new event needs to be generated while EDDI is running.

**Comment by Tkael** [comment]
Swapping ships is not sufficient to trigger an EDDN update containing faction data. 
Please either jump out of the system and then jump back in or at least leave the station and re-dock.

**Comment by Tkael** [comment]
You're also using the beta version of EDDI. Beta versions of EDDI send data to a special `/test` EDDN endpoint that is not visible from ROSS or used by Inara.cz

**Comment by zcampau** [comment]
Ok sounds like this ticket is no longer needed, working as designed
