### ISSUE TITLE
EDDI commodities issue

### ISSUE THREAD

**Issue by Tigir** [EDCD/EDDI#181]
## Steps to reproduce

1. dock at station in Maia system

## Expected
expected info on station commodities
## Observed
EDDI reported error, said to send logs
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1412102/eddi_issue.zip)

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Hoodathunk** [comment]
.zip file is empty

**Comment by ebarron** [comment]
same issue.  what do you need?

**Comment by Tkael** [comment]
Looks like Hoodathunk responded on the forum thread here with what we need: https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=6066410&viewfull=1#post6066410

Thanks for reporting, commanders. o7

**Comment by Tigir** [comment]
The empty zip file is the log the program created, I guess that's another issue in itself.
[eddi.zip](https://github.com/EDCD/EDDI/files/1414475/eddi.zip)

**Comment by Tigir** [comment]
Here is the last error line:

2017-10-25T12:36:11 CompanionAppService:CommoditiesFromProfile [W] Commodity definition errors: [{"name":"Thargoid Resin","category":"Salvage","avgprice":415100,"rare":null,"buyprice":0,"stock":0,"stockbracket":0,"sellprice":20350,"demand":9,"demandbracket":3,"StatusFlags":[],"EDDBID":0,"EDName":"UnknownResin"}]

**Comment by Tkael** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/1429393/eddi.log)
Another example here.

**Comment by richardbuckle** [comment]
As a reminder, the numbered tags are meant to be a priority scale, so it doesn't make sense to assign more than one of them.

**Comment by richardbuckle** [comment]
Fixed for the next release.
