### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by the-mec** [EDCD/EDDI#1810]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.5.2
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Suggestion
needs a way to turn down the volume, its way to loud

**Comment by Tkael** [comment]
You can adjust the volume from the `Text-to-Speech` tab in the UI. o7!
