### ISSUE TITLE
Error happened once I landed 

### ISSUE THREAD

**Issue by rj16066** [EDCD/EDDI#182]
## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Hoodathunk** [comment]
Which error would that be? Details?

**Comment by Tkael** [comment]
Closed for lack of information.
