### ISSUE TITLE
Eddi fails to obtain information from edsm past visits. 

### ISSUE THREAD

**Issue by PikkuMika** [EDCD/EDDI#1821]
[eddi1.log](https://github.com/EDCD/EDDI/files/4775475/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/4775476/eddi2.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/4775477/eddi3.log)
[eddi4.log](https://github.com/EDCD/EDDI/files/4775478/eddi4.log)
[eddi5.log](https://github.com/EDCD/EDDI/files/4775479/eddi5.log)
[eddi6.log](https://github.com/EDCD/EDDI/files/4775480/eddi6.log)
[eddi7.log](https://github.com/EDCD/EDDI/files/4775481/eddi7.log)
[eddi8.log](https://github.com/EDCD/EDDI/files/4775482/eddi8.log)
[eddi9.log](https://github.com/EDCD/EDDI/files/4775483/eddi9.log)
[eddi.log](https://github.com/EDCD/EDDI/files/4775484/eddi.log)

## EDDI version in which issue is found
eddi version 3.5.2

## VoiceAttack version in which issue is found (as applicable)
version 1.8.5
## Steps to reproduce
1. Jumping from systems back and forth end up being the first time to enter according to EDDI
2. [The more reproducible, the better our chances of fixing it]

## Expected
eddi to count visits everytime one more as I visit.
## Observed
eddi announces everytime that this is the first visit in system,even if i jump back and forth.
To make it more mysterious,sometimes it adds up,but next restart its back at zero and everytime its again first visit.
## Investigation
I replaced the eddi.sqlite file
Uploaded elite logs to edsm via upload journal
I have reinstalled windows,so I didnt have more than from february atm in my logs.
Once I re-installed eddi, but I didnt delete the user info, just reinstalled it.

**Comment by PikkuMika** [comment]
aww I forgot to put that I have replaced the eddi-sqlite file 
also uploaded my logs to EDSM
The obtain edsm logs button just turns grey,but no numbers appear under it like before that its getting the info from edsm. 
Otherwise eddi works quite well,but every visit is usually the first one, sometomes it does add up the visits,but eventually it forgets it and starts over.

**Comment by Tkael** [comment]
I see a lot of `[Warning] StarMapService:SetEdsmCredentials EDSM Responder not configured: Commander name not set.` I would recommend setting your commander name.

Otherwise, there is a known issue with 3.5.2 where visit data may not be preserved when refreshing stale data (older than one hour). It should be resolved in 3.5.3-b3 and later versions.

**Comment by PikkuMika** [comment]
Ok,where do I set the commander name?

ma 15. kesäk. 2020 klo 13.01 Brian Wilson <notifications@github.com>
kirjoitti:

**Comment by Tkael** [comment]
In the EDSM responder tab.

**Comment by PikkuMika** [comment]
Didnt help. I tried and it does run that it obtains the logs,but I can see
from eddiscovery that eddi announces it wrong.

ma 15. kesäk. 2020 klo 21.47 Brian Wilson <notifications@github.com>
kirjoitti:

**Comment by Tkael** [comment]
As I said, the other problem is the version of EDDI that you are using. You will need to [upgrade versions](https://github.com/EDCD/EDDI/releases/download/Release%2F3.5.3-b3/EDDI-3.5.3.b3.exe) if you want the systems visits problem resolved now.

**Comment by PikkuMika** [comment]
oh sry. I thought i had that version, thanks for your help. I will try this
as soon as I get norton to not delete it right away. 😄

ma 15. kesäk. 2020 klo 22.07 Brian Wilson <notifications@github.com>
kirjoitti:

**Comment by PikkuMika** [comment]
that solved the problem. thank you once again.

ma 15. kesäk. 2020 klo 23.19 Mika <mikalansman@gmail.com> kirjoitti:
