### ISSUE TITLE
Crash on fleet carrier jump setting

### ISSUE THREAD

**Issue by Jwh1o1** [EDCD/EDDI#1822]
## EDDI version in which issue is found
[3.5.3 b3]

## VoiceAttack version in which issue is found (as applicable)
[1.8.5]

## Steps to reproduce
Starting voice attack.

## Expected
voice attack to start up

## Observed
voice attack errors out and closes

## Investigation
setting the fleet carrier jump crashes the thing

**Comment by Jwh1o1** [comment]
[eddi1.log](https://github.com/EDCD/EDDI/files/4775586/eddi1.log)

**Comment by Jwh1o1** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/4775587/eddi.log)

**Comment by Tkael** [comment]
Duplicate of #1819. Please follow the instructions there for a temporary resolution.

**Comment by Tkael** [comment]
See also https://github.com/EDCD/EDDI/issues/1819#issuecomment-646868827
