### ISSUE TITLE
[Feature Request/Correction] Add other callsign formats and improve current format

### ISSUE THREAD

**Issue by AnonymousDapper** [EDCD/EDDI#1833]
While experimenting with some speech responder functions the other day, I noticed that EDDI doesn't provide a way to get other callsign formats. `ShipCallsign()` also does not match the ingame default.

I checked all 3 ingame options and they are as follows:

- Commander Name: last word of manufacturer name + first 3 alphanumeric characters of commander name
- Ship Name: last word of manufacturer name + first 3 alphanumeric characters of ship name
- Ship ID: last word of manufacturer name + first 3 alphanumeric characters of ship identifier

If the ship name, commander name, or ship identifier are shorter than 3 alphanumeric characters, they are zero-padded.

Examples:

Examples are with the ingame option set to Ship ID.

| Manufacturer       | Ship Model      | Ship Name   |Ship ID | Callsign                    | 
|--------------------|-----------------|-------------|--------|-----------------------------|
| Gutamaya           | Imperial Eagle  | Crying Kite | C      | Gutamaya Charlie Zero Zero  |
| Gutamaya           | Imperial Eagle  | Crying Kite | CRKIE  | Gutamaya Charlie Romeo Kilo |
| Faulcon DeLacy     | Sidewinder      | Sidewinder  | AN-19S | DeLacy Alpha November One   |
| Faulcon DeLacy     | Sidewinder      | Sidewinder  | A      | DeLacy Alpha Zero Zero      |

To make the current callsign function match the ingame, it would need to check for multiple words in the manufacturer name and only take the last one. I'm not sure how your IPA setup works, so this may require a little extra work.

Adding the ship name and ship id callsigns is easy enough, just replace the `EDDI.Instance.Cmdr.name` with the appropriate value, as it works the same way.

Lastly the code needs to check the length of the trimmed name/id and zero-pad if it is shorter than 3 characters.

Obviously there needs to be a way to pick between callsign formats. There could be a config option in EDDI, or have the function itself take an argument denoting which format to produce.
Again, I'm not too certain how the codebase works, so this may not be as easy as I think it is, but it appears to me that an integer 0-2 or an Enum type could be used as a second argument. ex. `ShipCallsign(ship.ident, callsign.shipname)` or `ShipCallsign(null, 1)`

My code insight is from reading [ScriptResolver.cs in tag 3.5.3-b3](https://github.com/EDCD/EDDI/blob/Release/3.5.3-b3/SpeechResponder/ScriptResolver.cs#L606)

**Comment by richardbuckle** [comment]
Thank you.

Not always last word of manufacturer name: e.g. "Core Dynamics" is spoken in full.

**Comment by Tkael** [comment]
Sounds like we'd need to compile a list of manufacturer names spoken in full vs. abbreviated to the last word.

**Comment by AnonymousDapper** [comment]
As @richardbuckle said, apparently not every manufacturer is treated that way. When I get on again I'll check all my different manufacturers, but I don't own every ship so some other people may need to chime in.

**Comment by richardbuckle** [comment]
I'm fairly sure my fleet covers all the manufacturers. I'll check this evening.

**Comment by richardbuckle** [comment]
OK, full names before the dash, what ATC says after it:

- Core Dynamics - Core Dynamics
- Faulcon deLacy - deLacy
- Gutamaya - Gutamaya
- Lakon Spaceways - Lakon
- Saud Kruger - Saud Kruger
- Zorgon Peterson - Zorgon Peterson

NB "Saud" rhymes with "loud"; our phonetics are already set up for that.

**Comment by richardbuckle** [comment]
Please wait for the next release before commencing any work as we are re-working the underlying code a bit.

**Comment by AnonymousDapper** [comment]
Is the next release you mentioned the 3.5.3-b4? Also, it turns out I *only* own DeLacy and Gutamaya ships, so I appreciate your input on names.

**Comment by richardbuckle** [comment]
Post 3.5.3-b4, TK has PR'd some first-digit updates to the Cottle engine that may change the playing field in coding terms. Let us integrate that first, and then see where we stand.
