### ISSUE TITLE
Vehicle loadouts are not localized for the events `Fighter launched` and `SRV launched`

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1835]
## EDDI version in which issue is found
3.5.3-b3

## VoiceAttack version in which issue is found (as applicable)
N/A

## Expected
A comprehensible description of the vehicle's loadout.

## Observed
All that's provided is the unlocalized loadout, e.g. "one".

## Investigation
At present, we have separate translations for loadouts like "EmpireOne", "FederationOne" and "IndependentOne" in LoadoutDescription.resx. It looks like we can probably drop the allegiance separator and redefine these loadouts in a way that can apply to `Fighter launched`events, e.g.
- EmpireOne: fixed beam lasers and heat sink launcher
- FederationOne: fixed pulse lasers and heat sink launcher
- IndependentOne: fixed beam lasers and heat sink launcher

can become
- One: fixed beam lasers and heat sink launcher

This localization strategy better matches `Fighter launched` events (which do not include the allegiance):
`{ "timestamp":"2020-06-01T05:40:10Z", "event":"LaunchFighter", "Loadout":"one", "ID":95, "PlayerControlled":false }`

Still to investigate: How are guardian fighter loadouts described for the `Fighter launched` event?

SRVs always use the "starter" loadout.

**Comment by Hoodathunk** [comment]
You best double check ALL of them. I would not have added the allegiance with the load out numbers if they were all the same.

Are you not seeing that the FederationOne fighter has a pulse laser?!?

**Comment by Tkael** [comment]
You're right, unfortunately.
