### ISSUE TITLE
3.5.3-b4 TTS Configuration - Volume set to zero, config doesn't match UI

### ISSUE THREAD

**Issue by alterNERDtive** [EDCD/EDDI#1837]
## EDDI version in which issue is found
3.5.3-b4

## Steps to reproduce
1. Install 3.5.3-b4, manually or through the upgrade process

## Expected
No configuration change.

## Observed
TTS volume is set to 0. In my case the UI did not reflect that change, but fiddling with the slider brought speech back.

## Investigation
I’ve been switching around between 3.5.2 and 3.5.3-b4 trying to find out what killed TTS.

Manually reverting to 3.5.2 brought speech back the first time I tried it, but not the second time. After reverting, then manually installing 3.5.3-b4 speech worked the first time I launched EDDI, but not on subsequent launches.

It appears to be a bug that doesn’t happen consistently.

There has been a second user reporting the problem on Discord, too.

**Comment by Tkael** [comment]
Please provide logs? Located at `%appdata%\EDDI`.

**Comment by alterNERDtive** [comment]
… you should add that to the issue template, because I literally forget to attach them every. Single. Time.

Will do when I get my Windows box back from the kids.

**Comment by alterNERDtive** [comment]
That’s all the logs from my fiddling today.

[eddi logs.zip](https://github.com/EDCD/EDDI/files/4809969/eddi.logs.zip)

**Comment by alterNERDtive** [comment]
Uh … I just restarted VA and that set speech _speed_ back to 0 (standard), but settings still showed 3 …

[eddi.log](https://github.com/EDCD/EDDI/files/4810410/eddi.log)

**Comment by Tkael** [comment]
Also reported on Discord by AnonymousDapper:
"I'm on the new release of EDDI (3.5.3-b4) and I'm noticing that the actual TTS voice used is the one previously selected in the dropdown"
"Well, when I first launched VA (with the EDDI plugin), the Speech Responder scripts I wrote weren't responding. I opened the eddi window from inside VA and tried the "Test Voice" button; no response so I picked another voice (MS David in this case) and tried again. It responded using the first voice I had when it launched, not MS David. So I picked the first voice again and tested again. This time it spoke with MS David's voice. Selected Zira, tested, it spoke with the first one. Selected the first one, it spoke with Zira."

**Comment by Tkael** [comment]
Found the issue: We're saving to the config file then immediately reading from the config file, but since the write operation is now asynchronous the read operation may actually complete before the write operation. This creates a de-coupling between the displayed UI configuration and the speech service configuration and can result in the speech service not actually picking up the change in the config file until another change occurs.

**Comment by alterNERDtive** [comment]
I’ve just had speed randomly reset again (without the slider in the preferences showing the change, again). Not sure if this is the same issue or separate, honestly.

That was in the middle of the same VoiceAttack session. No restarts. Nothing logged.
