### ISSUE TITLE
EDDI Core: Verbose error logging returns an empty log

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#184]
## Steps to reproduce

1. Turn on verbose logging
2. Click the button to report an issue

## Expected
A truncated zip file containing the last hour of logs should appear on the desktop.

## Observed
The truncated zip file contains an empty log file.
I don't see any commits that should have mucked this up. Will need to test to figure out what's going on.

**Comment by Hoodathunk** [comment]
The zip file is empty, regardless of whether the log is verbose (box checked) or not (box un-checked).

**Comment by Tkael** [comment]
Are you saying that a new export is created while verbose logging is unchecked? If so, that shouldn't be happening.

**Comment by Hoodathunk** [comment]
I suppose so. In issue #181, tigir posted an empty eddi-issue.zip file. When he re-sent the log (un-zipped), it was clearly a non-verbose log.

**Comment by Tkael** [comment]
@richardbuckle I think this was broken for me by the changes on commit #c0f89725. Is the current version working for you?

**Comment by Tkael** [comment]
I think I have a fix in place. PR generated.
