### ISSUE TITLE
Support for Roman Numerals

### ISSUE THREAD

**Issue by mearmortal** [EDCD/EDDI#1843]
## 3.5.3-b4

Nice job on the addition of roman numeral translation works great up to 'XIX' for '19', after which anything up to 40 still says letters, i.e.  'XXXIII' for thirty-three. The only reason I mention this is because I have 36 ships and I use the numerals for naming them. Everyone's different.

Might be a good idea to cope with at least the number of ships in the game, just in case some strange person like me want's it to actually say 'Nebuchadnezzar Thirty-Three' and not 'Nebuchadnezzar XXXIII'

Smashing job so far on this program, great addition to the game, using it all the time.

Thank you.

**Comment by Tkael** [comment]
Are you using IPA to set the phonetic pronunciations for your ship names in the Ship Monitor? If not, is that a possibility?

**Comment by mearmortal** [comment]
My ship names are configured in ED somehow eddi has imported them and plays back the names when I press hear it




Sent from Samsung Mobile on O2







On Tue, Jun 23, 2020 at 6:59 AM +0100, "Brian Wilson" <notifications@github.com> wrote:















Are you using IPA to set the phonetic pronunciations for your ship names in the Ship Monitor? If not, is that a possibility?

**Comment by Tkael** [comment]
As far as I'm aware, EDDI does not do any general roman numeral translation on ship names (only translation for applicable ship models). If up to XIX is working for you, your TTS voice is probably doing the heavy lifting there. For numbers beyond XIX, the ship monitor already provides the ability to create a customized name with IPA.

**Comment by mearmortal** [comment]
Fair enough thank you




Sent from Samsung Mobile on O2


Get Outlook for Android







On Thu, Jul 2, 2020 at 6:27 PM +0100, "Brian Wilson" <notifications@github.com> wrote:















As far as I'm aware, EDDI does not do any general roman numeral translation on ship names (only translation for applicable ship models). If up to XIX is working for you, your TTS voice use probably doing the heavy lifting there. For numbers beyond XIX, the ship monitor already provides the ability to create a customized name with IPA.
