### ISSUE TITLE
Mission Check Galaxy script broken

### ISSUE THREAD

**Issue by ocram9** [EDCD/EDDI#1848]
## EDDI version in which issue is found
3.5.3-b5

## Steps to reproduce
1. Test the mission check galaxy script
2. EDDI tells you the script is wrong

## Expected
Running the mission check galaxy script

## Observed
Script errors out and doesn't play

## Investigation
This was not happening in 3.5.3-b4. According to the TTS there is a problem at "line 0" which is weird because there is no line 0 (I don't know much about coding so it could mean the start of the script but I'm not sure). I haven't modified this script and also reset it to default (just in case I forgot a change) but the issue persists.

**Comment by Tkael** [comment]
1. It looks like the old method we were using to obtain the line number of the error isn't supported anymore. It'll be easy to fix that.
2. There is a missing `:` at line 109 of the default script. We can patch that up too.
