### ISSUE TITLE
Excessive internal exception throwing in `PrepRollbarData()` during regular app launch

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1850]
## EDDI version in which issue is found
3.5.3-b6

## Steps to reproduce
1. Run up the current dev branch in Visual Studio with default exception settings.

## Expected
No breakpoints on exceptions during a regular vanilla launch (this is the case in the stable branch).

## Observed
A storm of breakpoints -- I gave up counting at 55. It makes running the debugger with default exception settings untenable. 

One lot is `Newtonsoft.Json.JsonReaderException` from `Utilities.Logging.FilterProperties()` being given non-JSON strings such as "EDDI 3.5.3-b6 starting " (yes there is a trailing space) or "on live".

Another is `Json.JsonSerializationException` from `Utilities.Logging.PrepRollbarData()` being given non-JSON strings as above.

## Investigation
As noted, does not happen with stable.

Exceptions are low cost to set up but very costly to use, and should only be used for truly exceptional circumstances: the IDE breaks on them by default because they are assumed to need developer attention. Regular control flow on "the happy path" shouldn't be using them.

**Comment by richardbuckle** [comment]
Fixed in 3.5.3-b7.

**Comment by Tkael** [comment]
Note: I've been investigating this and my conclusion is that my Rollbar changes simply increased the flow of messages through the methods - the current released methods seem to have exactly the same issues.
