### ISSUE TITLE
landing pad report fails to say where the pad is in the station

### ISSUE THREAD

**Issue by dauthiatull** [EDCD/EDDI#1852]
## EDDI version in which issue is found
v.3.5.3-b6
## VoiceAttack version in which issue is found (as applicable)
v1.8.5 steam

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
landing at a station eddi says landing pad is at   as you enter with the green lights on your right.
but does not say the location. 

2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
I dont remember all the stations I visited but can confirm this happens at Virchow Dock in the LFT 1300 system

this happens with the default script in eddi

**Comment by nepomuk16321** [comment]
This is probably related to the same problem in Issue #1851.
For discussions you can also visit the forum https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/page-110

**Comment by richardbuckle** [comment]
Yes, I've confirmed that this is the same as #1851.
