### ISSUE TITLE
error in voice app 

### ISSUE THREAD

**Issue by conrad1878** [EDCD/EDDI#1853]
## EDDI version in which issue is found 3.5.3-b6
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]taking and completing missions as voice  text error 
2. [The more reproducible, the better our chances of fixing it] with every mission taken and completed 

## Expected
[Describe what you expected to happen]
voice to work correctly 
## Observed
[Describe what happened instead]
saying unexpected error with faction 
## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
none first time ever happened

**Comment by richardbuckle** [comment]
Possibly related to #1851. Will investigate.

**Comment by Tkael** [comment]
We believe this issue to be resolved with the release of [EDDI version 3.5.3-b7](https://github.com/EDCD/EDDI/releases/download/Release%2F3.5.3-b7/EDDI-3.5.3.b7.exe).

If not, please provide additional details to help us to identify and replicate the issue.
