### ISSUE TITLE
Truncated Info Delivery - constant

### ISSUE THREAD

**Issue by afalk** [EDCD/EDDI#1854]
## Steps to reproduce
1. Travel to any station/port in ED -- request landing -- pad assignment is cut off
2. When travelling to a new systesm, EDDI's reporting gets truncated as well

## Expected
the reg data

## Observed
everything gets truncated

## Investigation
this is a new issue since you dropped 3.5.3-b6

**Comment by Darkcyde13** [comment]
Probably related to this issue with version b6. #1851 Try going back to beta 4, or v3.5.2

**Comment by Tkael** [comment]
We believe this issue to be resolved with the release of [EDDI version 3.5.3-b7](https://github.com/EDCD/EDDI/releases/download/Release%2F3.5.3-b7/EDDI-3.5.3.b7.exe).
