### ISSUE TITLE
Fuel Report

### ISSUE THREAD

**Issue by afalk** [EDCD/EDDI#1855]
## EDDI version in which issue is found
3.5.3-b6

## Steps to reproduce
Try fueling from any start. Stop before you reach 100% fuel.... 99% works fine.
EDDI gets nervous declaring that it is a fuel emergency and that you are essentailly running on fumes, with all the dire portents

## Expected
an accurate % reported for fuel use

## Observed
Panic mode if you do not fuel scoop back up to 100%

**Comment by Darkcyde13** [comment]
Probably related to this issue with version b6 #1851 Try going back to beta 4, or v3.5.2

**Comment by Tkael** [comment]
We believe this issue to be resolved with the release of [EDDI version 3.5.3-b7](https://github.com/EDCD/EDDI/releases/download/Release%2F3.5.3-b7/EDDI-3.5.3.b7.exe).
