### ISSUE TITLE
EDDI needs a splash screen to show that launch is underway

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1856]
## EDDI version in which issue is found
3.5.3-b7

## Steps to reproduce
1. Launch EDDI and watch for a visible responce.

## Expected
Something visible happens as soon as EDDI is launched, so that the user knows that it worked.

## Observed
Nothing visible for a variable number of seconds until EDDI's main loop gets underway.

## Sundry
I'm not normally a fan of splash screens, but in this case it would help a lot. Show it immediately and take it down when the main loop gets underway.

**Comment by Tkael** [comment]
A splash screen is intrusive and is of no help when EDDI is started in a windowless mode (e.g. from VoiceAttack). Maybe some sort of audio cue would be preferable to a splash screen?

**Comment by nepomuk16321** [comment]
With VA this is no problem (script "VA initialized").
Maybe you can do it similar to the announcement that a new version is available ?

**Comment by richardbuckle** [comment]
I'm going to stick to my guns here because UX is very much my specialty.

First off, I'm only talking about the standalone app here: no change at all when running as a VA plugin.

Gratuitous/intrusive splash screens are indeed very bad UX, especially when abused for marketing purposes and most especially when not auto-closing. A well-known iOS developer once described them as like "inviting your user on a date and then sticking a mirror on their forehead" which I fully agree with.

There is however one case where a simple, auto-closing splash screen is good UX and that is *to give immediate visual feedback that the app has launched, when it needs more time to set up its UI*. When the user double-clicks the app icon and nothing happens right away, that's a very dissonant user experience.

There is a genuine UX problem to be solved here: giving the user feedback that their double-click or whatever registered. Examples we all have include GitKraken, Discord, Visual Studio and EDDiscovery. (OK we don't all have the latter). They all immediately show a screen to say "yes, your double-click registered, just a sec".

Numerous studies into delay times have shown that users perceive less than 0.4s to be instant, up to 1.0s to be "meh", up to 2.0s to be sluggish, and over 2.0s they start to wonder whether their click registered and will probably click again. 

I myself have quite often clicked EDDI's icon in the taskbar and clicked it again after nothing happened, *even though intellectually I know what is going on*. It's just reflexive. And then of course I get the "only one instance" dialog box and facepalm. 

It's such a well-recognized issue that MS provide framework support: 

- [How to add a splash screen](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/how-to-add-a-splash-screen-to-a-wpf-application)
- [SplashScreen class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.splashscreen?view=netcore-3.1)

**Comment by richardbuckle** [comment]
Also the fix is super easy 😁
