### ISSUE TITLE
EDDI not reading out anything beyond my ship

### ISSUE THREAD

**Issue by CupcakeComrade** [EDCD/EDDI#1857]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
v3.5.2
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
1.8.3
## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
Fly into a new system, and scan the planets
## Expected
[Describe what you expected to happen]
EDDI to read out what each planets surface materials was, and if it was terrformable or a good mapping canidate.
## Observed
[Describe what happened instead]
Nothing happended beyond her stating im low on fuel when i entered a system (my anaconda consumes half my fuel for a 71ly jump)
## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
i poked around to see if an option was disabled, but it doesnt appear that any were off, or that it shouldnt be working.

**Comment by Tkael** [comment]
1. Is the issue specific to a certain system, or does it apply for all of the star systems you've visited?
2. Some exploration scripts are only invoked for certain ship roles. Is your ship role set to either "Multipurpose" or "Exploration"?
3. Are you using the default scripts?
  - The default `Body report summary` script does not report non-terraformable bodies. If the bodies were not terraformable they are much less likely to have been considered good mapping candidates.
  - The default `Body materials report` only tells you about materials when the materials in your inventory are less than their desired levels. If your inventory levels are high or the desired quantities are low, you are less likely to hear reports about the materials on a body.

**Comment by CupcakeComrade** [comment]
side note: updated to 3.5.3-b7, same issues occur
the Body report didnt trigger on 4 terraformable worlds, not did the body materials report ever pipe up, and i have like 0 elements. Usually Stella (what i named her) would never shut up like "This body contains high levels of zinc, annoyance, and non-stop talking" (obviously it tells me the actual elements) but it never has now, and i had gone into multiple systems with good canidiates, 2 hmc terraformables in one, and 2 in another, but neither was stated as such, i never even got a system scan complete report from her.
hang on i was streaming when all this was happening, i have a video of it ill cut out the parts that arent as important, but i jumped into a system with 2 planets with rings, several landable moons, and 2 terraformable HMCs, Stella didnt say a peep about the rings, when usually shed be like "this planet is unusual, with a pristine rockey and icey ring." and didnt say like "this planet is a hmc with potential for terraforming, the triangle atmosphere is produced by doritos." (cause i dont remember the atmospehere)

Ill edit the video and drop it here for proof, its just taking a bit cause i dont got good editing software >:c

**Comment by nepomuk16321** [comment]
There is the "Body scanned" script (event), the "Body report" script (function call), "Body report summery" (function call) and the "Body materials report" script (function call). In all scripts you have settings for pronunciation/announcement, in some you have settings for calling the following scripts (function call).
E.g. you can set in the "Body materials report" if you want to compare with your inventory or/and from which concentration on you want to announce and/or if the announcement should come from xx% or always the announcement in percent.

Please excuse me if you know this and you have noticed this and it still doesn't work. Then maybe there is a mistake.

Yes, and my English, is DeepL. :-)

Translated with www.DeepL.com/Translator (free version)

look here, the "Body materials report"-Script (beginning)
```
{_ Preferences _}
{set reportMats to 1} {_ Set to 0 if you want to hear about materials below your minimum inventory level _}
                      {_ Set to 1 if you want to hear about materials below your desired inventory level _}
                      {_ Set to 2 if you want to hear about all materials irrespective of inventory levels _}

{set reportMatConc to 1} {_ Set to 0 if you only want to hear about great material concentrations _}
                         {_ Set to 1 if you want to hear about good and great material concentrations _}
                         {_ Set to 2 if you want to hear about all material concentrations _}

{set reportMatPercent to 1} {_ Set to 0 if you do not want to hear about material percentages _}
                            {_ Set to 1 if you only want to hear about great material percentages _}
                            {_ Set to 2 if you want to hear about good and great material percentages _}
                            {_ Set to 3 if you want to hear about all material percentages _}

{_ Fetch from context _}
{set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
{if !reportbody: 
    {set reportbody to BodyDetails(state.eddi_context_body_name)}
}

{if !reportbody.name || reportbody.name = "":
    {_ If it's still not possible to get the body name...  _}
    Which body are you
    {OneOf("asking about","referring to")}?
```

**Comment by Tkael** [comment]
Yes. This is why we're asking whether you are using the default scripts. If you've customized the scripts then that may explain your observations.

**Comment by CupcakeComrade** [comment]
i have no idea how to customize the scripts, im under the assumption its just defaultly buggered.

**Comment by CupcakeComrade** [comment]
BTW sorry the video is taking longer to edit, i just had to cut out 13 minutes of me jumping around red dwarves with icy bodies. fuckin icy bodies

**Comment by CupcakeComrade** [comment]
Okay the videos rendering now, itll take about 30 minutes, but i cut out most of the not helpful information and focused on a system which is the golden example of how its buggering, it does work for where my ship is, what my fuel is, and SRVs, but doesnt state anything beyond that. Im using default scripts (note i was on 3.5.2 at the time, but updating it still has the same results)

**Comment by Tkael** [comment]
I've been exploring for the last couple of days and haven't encountered the same issue that you're describing. EDDI doesn't remark on every body but it does remark on many of them.

Would you please provide 
1. a copy of your logs (located at %appdata%/EDDI and ending with the `.log` extension) 
2. a screenshot of your speech responder tab (focused on the `Body... ` scripts please)
3. a screenshot of your ship monitor tab highlighting your current ship?

**Comment by CupcakeComrade** [comment]
[eddi6.log](https://github.com/EDCD/EDDI/files/4839442/eddi6.log)
[eddi7.log](https://github.com/EDCD/EDDI/files/4839443/eddi7.log)
[eddi8.log](https://github.com/EDCD/EDDI/files/4839444/eddi8.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/4839445/eddi3.log)
[eddi4.log](https://github.com/EDCD/EDDI/files/4839446/eddi4.log)
[eddi5.log](https://github.com/EDCD/EDDI/files/4839447/eddi5.log)
(all these files are from yesterday, i havent played today)
![f4b9c61f988348455f3dab7f1dea1a12](https://user-images.githubusercontent.com/67446609/85906400-351cf600-b7dc-11ea-9a31-5a74b28a2365.png)
![2936d80ed003c79e14455ee8fe138847](https://user-images.githubusercontent.com/67446609/85906401-351cf600-b7dc-11ea-9a17-45d25f0656b7.png)
Do you want the video? or no?

**Comment by Tkael** [comment]
As I mentioned earlier, some exploration scripts are only invoked for certain ship roles. If your ship role is set to "Mining" (as it would appear) then exploration scripts by default will not trigger. 

```
{if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":
    {Pause(500)}
    {if fullBodyReport:
        {F("Body report")}
    |else:
        {F("Body report summary")}
    }
}
```
(excerpt is from the `Body scanned` script)

If you were to do nothing except swap to any of your other ships (with roles of `Exploration` or `Multipurpose`) then you'd find that the exploration scripts were triggering again.

If you'd like these scripts to trigger for your mining ships then you would want make a copy of the default personality and then customize the appropriate section of the `Body scanned` script as follows:

```
{if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose" || ship.Role.edname = "Mining":
    {Pause(500)}
    {if fullBodyReport:
        {F("Body report")}
    |else:
        {F("Body report summary")}
    }
}
```

EDIT: If this answers your question then the video isn't needed. o7

**Comment by CupcakeComrade** [comment]
Okay, i kinda regualrly swapped out what this ship did for a long time, lemme try using it marked as only exploration then ill see if it works :)

**Comment by CupcakeComrade** [comment]
or well, no imma mark it as exploration, and see if it works, not then see if it works

**Comment by Tkael** [comment]
If you're swapping capabilities regularly, I would suggest using the "Multipurpose" role. :-)

**Comment by CupcakeComrade** [comment]
Yes, i flew into a new system that had 2 terraformable worlds, Stella gladly read them off and told me about there thick and thin carbon dioxide atmospheres. Side question, i had an idea to put a command in called "Any notable planets?; What were the notable planets again?" how do i do this? (sometimes she rants on and on about 1 planet than states the rest but i just want to know what the other planets needing scanned were, either way, changing the role fixed the issue :)

**Comment by Tkael** [comment]
If you honk the discovery scanner after scanning all of the planets, EDDI will respond by reminding you of any un-mapped notable planets. :-)

Closing this issue as resolved. o7
