### ISSUE TITLE
EDDI fails to launch in Windows 10 Home (2004 build)

### ISSUE THREAD

**Issue by jpalsgaardanglin** [EDCD/EDDI#1858]
## EDDI version in which issue is found - 3.5.3 b7
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable) - 1.8.5 / HCS Astra Edition
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. Using Windows 10 Home 2004 attempt to launch from start / taskbar / file location
2. Application fails to launch
3. Go to Windows Event Viewer / Administrative Events and sort by most recent

NOTE: I reproduced with both the stable release of EDDI and the beta channel

Expected behavior:  Application window launches
[Describe what you expected to happen]

Observed: Application fails to launch.  Error entries generated by Windows Event viewer/administrative events related to unhandled exception related to XML parsing
[EDDI_ApplicationError.txt](https://github.com/EDCD/EDDI/files/4839920/EDDI_ApplicationError.txt)
[EDDI_UnhandledException.txt](https://github.com/EDCD/EDDI/files/4839921/EDDI_UnhandledException.txt)

[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

-Uninstall/reinstall beta channel (orginally had beta channel of EDDI which had worked flawlessly until update to Win10 2004)
-Uninstall beta and replace with stable EDDI 

NOTE: Each of these were followed by running CCleaner just in case

**Comment by Tkael** [comment]
A [variety of issues](https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-2004) have been reported for the May 2020 Windows 10 update. Microsoft has even been blocking some PCs from receiving the update through the normal Windows Update channel.

This may be an issue with the installation of the .Net Framework version 4.8 on your local system (something that's built into Windows 10). Please try the steps at https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system to find any fix any problems with your Windows installation.

**Comment by jpalsgaardanglin** [comment]
Thanks.  Will update you as to the results.

**Comment by Darkcyde13** [comment]
I must be one of the luckiest people around, as I've had no problems at all with Win10 2004.  I did do a clean install though, so maybe that helped?

EDDI is working fine as both standalone and as the VA plugin for me, so I doubt it's likely to be something inherent in 2004 as such.  I'd go with what Tkael said, and err on the side of something got corrupted or just didn't install correctly maybe.

Oh, I'm also using Win10 Pro, but I doubt that would make any difference.

**Comment by jpalsgaardanglin** [comment]
Still getting the same thing -- I guess I'll refresh Windows and see if that is the culprit.

**Comment by jpalsgaardanglin** [comment]
Please close this ticket.  Windows refresh did wonders.

**Comment by jpalsgaardanglin** [comment]
I actually had this happen again but fixed it this time.  Windows 10 has a setting under speech properties which triggers EDDI to stop working.  If the following isn't checked it causes the issue I observed.  Checking it immediately allows the application to work as normal.  I just wanted to post this so y'all have a documented root cause.

![image](https://user-images.githubusercontent.com/61337614/86525148-f248c700-be48-11ea-9a11-ae81ee8e7f9e.png)

**Comment by Tkael** [comment]
Thanks for the report. Unfortunately, I'm not able to replicate your result on my machine.
On my machine, all three user settings check boxes were already unchecked (with EDDI working fine). Checking or unchecking the boxes on my machine, then restarting EDDI, seems to have no affect on EDDI.
