### ISSUE TITLE
EDDI ship loadout not responding

### ISSUE THREAD

**Issue by Labanden** [EDCD/EDDI#1870]
## EDDI version in which issue is found
3.5.3-b7, but may show in earlier versions

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
1. See below
2. See below

## Observed
When logged in to Elite Dangerous with second account, using same logon to computer. EDDI and Voice attack do not recognise the ((EDDI ship location)) event. When logged on to EDDI with First account it does. No API is enabled in EDDI. Install of ED is the same and Voice attack and EDDI are also same install. Voice attack profile is the same.

## Investigation
Have regressed EDDI to 3.5.2, uninstalled both VA and EDDI.

To be honest not sure if this is ED, EDDI or VA. Just need help to resolve the issue.

**Comment by Tkael** [comment]
I'm not sure I follow exactly what you are describing but EDDI's configuration settings are stored per Windows account and using multiple commanders with the same Windows account is not currently supported (see #505). If you are attempting to use EDDI with multiple ED accounts from a single Windows login then your config files have likely become a corrupt mixture of data from both ED accounts. This could cause various events to fail or to not behave as expected.

**Comment by Labanden** [comment]
Hi Brian,
                I had the two ED accounts on separate PCs and had the same issue. As part of the investigation I  did use them on the setup I described.

Not sure if it was working before I installed 3.5.3-b7 but believe it was. Having said that the first account also has B7 installed and is ok.



Regards

Alan

**Comment by Tkael** [comment]
If the issue occurs with two separate ED accounts each on a different PC then please clarify further what exactly is wrong / not working as expected. Please provide a complete description, including screenshots if possible, to show what you have set up in your profile and what you expect to happen.

**Comment by Labanden** [comment]
Brian,
Simply put, I have a command in Voice attack the is configured to trigger when the Location event happens in Elite Dangerous. ((EDDI Ship Location)).
Actions include writing to VAs event log when the command is called, and variables assigned from the EDDI event its self.

On primary account - this happens
On secondary account - it does not happen.
Conditions
Both are Windows 10 1909
Both FDEV versions of ED
Both have same Version of VA and EDDI (as detailed in the report)
Both use the same VA Profile.

Please any advice on why this is happening is appreciated.

[X]
[X]

Regards
Alan Bend
T: 01202 572215 | M: 07522244731 | E: Alan.Bend@Kinsonhold.co.uk<mailto:Alan.Bend@Kinsonhold.co.uk>
P Please don't print this e:mail unless it's really necessary.
________________________________

**Comment by Tkael** [comment]
The title of the ticket says `((EDDI ship loadout))` but twice now you've described the event that you're trying to capture as `((EDDI ship location))`. `((EDDI ship location))` does not exist / is not a valid command name. Please clarify which event you are trying to trigger and double check that your VoiceAttack commands are referencing the desired event correctly. It should be either:
- [((EDDI ship loadout))](https://github.com/EDCD/EDDI/wiki/Location-event) or
- [((EDDI location))](https://github.com/EDCD/EDDI/wiki/Ship-loadout-event)

If the command name in your VoiceAttack profiles are correct, please provide log files so that we can check for logged exceptions / errors. The log files will be located at %appdata%/EDDI and end with the .log suffix. Please add them to a .zip file and attach the .zip file to this ticket.

**Comment by Labanden** [comment]
Brian,
Sorry for the confusion. I sometimes get confuse myself. Sorry for any confusion was working on some logic to do with location at the time i replied to your email.

((EDDI ship loadout)) is the event I am having issues with.





Regards
Alan Bend
T: 01202 572215 | M: 07522244731 | E: Alan.Bend@Kinsonhold.co.uk<mailto:Alan.Bend@Kinsonhold.co.uk>
P Please don't print this e:mail unless it's really necessary.
________________________________

**Comment by Tkael** [comment]
Thanks for clarifying. I need the logs requested above (ideally with a screenshot of the VoiceAttack command for context) to look for any issues in the back-end code.

**Comment by Labanden** [comment]
> Thanks for clarifying. I need the logs requested above (ideally with a screenshot of the VoiceAttack command for context) to look for any issues in the back-end code.

[EDDI Logs.zip](https://github.com/EDCD/EDDI/files/4872783/EDDI.Logs.zip)
[VA extracts.zip](https://github.com/EDCD/EDDI/files/4872784/VA.extracts.zip)

Note have modified EDDI.vap to use the Ship Loadout event to call the ship variables command, on the secondary it does not happen. On Primary it does. again on different Windows installs (But same versions of every thing)

**Comment by Tkael** [comment]
Ok. Looks like the `((Ship loadout))` event is throwing an exception while being parsed.

```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at EddiJournalMonitor.JournalMonitor.parseShipCompartment(String ship, String slot)
   at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line, Boolean fromLogLoad)
```

That exception causes the event to fail / not execute in VoiceAttack.

Essentially, there was a problem with EDDI's internal definitions where we weren't expecting to see a military slot on Eagle Mk. II.

I've submitted PR #1874 to correct the exception. In the meantime, the issue may be resolved if you either use a different ship or remove the module from the military slot in your current ship.

**Comment by Labanden** [comment]
Confirmed if I remove the Military slot entry it does allow the event to respond. Thanks for your help. Please pass on to all involved with EDDI I really appreciate the App. It is an excellent addition to Voice Attack
