### ISSUE TITLE
TTS not working correctly in 3.7.0-RC1 with 3rd party voices

### ISSUE THREAD

**Issue by Ketris** [EDCD/EDDI#1872]
## EDDI version in which issue is found
EDDI v.3.7.0-rc1

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Select any voice that is not the system default (Tested with 10+ Ivona voices and 2 Microsoft ones that were not the system default)
2. Click "Test Voice"

## Expected
3rd party voices should work as they did in every previous version

## Observed
"msvcr110.dll is either not designed to run on Windows or it contains an error" message boxes appear multiple times.

## Investigation
Reinstalling MS VC++ 2010 Redist did not correct the error.
Selecting any voice after the error occurs will either ignore your selection (and use system default) or give more of the same errors.

**Comment by Ketris** [comment]
Appears to be a system-wide issue, as I'm seeing the same broken behavior in Windows Control Panel's TTS settings.

**Comment by Ketris** [comment]
After rolling back to v.3.5.3-b7, all voices from all 3rd parties are working correctly. (eSpeak, LH, Ivona, old Microsoft ones, etc.)

Likely related to the switch to 64-bit https://github.com/EDCD/EDDI/commit/d830987f8917b5a179f1240fc1334e39dbedccf5 (aside from Win10 builtins, only Ivona offers 64-bit support, but it is broken in my installed version)

**Comment by Tkael** [comment]
Please identify the specific voices that you are having trouble with?

The speech service (SpeechService.cs) was [unchanged from version 3.5.3-b7 to version 3.7.0-rc1](https://github.com/edcd/eddi/compare/Release/3.5.3-b7...develop). We don't expect **any** differences between the two versions with respect to speech synthesis.

On my system, EDDI version 3.7.0-rc1 is able to select the following voices: Cerevoice Heather, Ivona Amy, Microsoft David Desktop, and Microsoft Zira Desktop). These are all of the voices that are detected by the Windows (System.Speech) speech synthesizer (as confirmed both within the code and by right clicking on the Start button, selecting Run, entering `control /name Microsoft.TextToSpeech`, and reviewing the drop-down selection.

I have several other Microsoft server (Microsoft.Speech) voices installed on my system but the Windows speech synthesizer does not recognize them and EDDI does not support them.

Rolling my local build back to 3.5.3-b7 does not change the voices made available from the Windows speech synthesizer.

On neither the current build nor the prior build do I see the same exceptions that you're describing related to msvcr110.dll. If this is faulting, perhaps it is preventing the speech synthesizer from discovering voices as it should? Is there a specific voice on your system that requires that .dll file?

**Comment by Tkael** [comment]
Do you use any other text-to-speech programs on your local machine? Do those programs present the same errors?

We wouldn't expect EDDI to be generating that message box... do you know which program generates the message box containing the error message?

**Comment by Ketris** [comment]
I have taken screenshots showing the issue I see:  https://imgur.com/a/zgDkobP

From playing with other SAPI TTS applications over the past few days, I have found that the voices that "vanish"/break in EDDI 3.7.0 are only usable by 32-bit applications. When I run any other 64-bit TTS application, I see the same behavior, so yes it is more of an issue with the voices installed on my system than with EDDI, but the switch to 64-bit has removed my ability to use my installed voices.

Is it an option to have 2 binaries or even a setting within EDDI to be able to use 32-bit again? Or is this switch to 64-bit to prepare for new functionality that requires it?


As to the MSVC-related errors, those come from trying to load 32-bit Ivona DLLs into a 64-bit TTS app. (Any 64-bit app does this if I select Ivona)

**Comment by richardbuckle** [comment]
I'm inclined to just revert the change and go back to preferring 32-bit for standalone mode.

**Comment by Tkael** [comment]
Agreed, that may be the best solution. 
For reference on the voices missing from the 64 bit version, we have:
- Crystal16, an AT&T Natural Voice
- VW Kate, a NeoSpeech Voice (I think)

**Comment by Ketris** [comment]
Those are both correct. Thank you both for your quick responses!

**Comment by Ketris** [comment]
For reference, eSpeak is free and also exhibited the same behavior

**Comment by richardbuckle** [comment]
I made the change to prefer 64-bit as a general modernisation but I am going to revert it given that 32-bit-only voices still exist.
