### ISSUE TITLE
Missing responder tab

### ISSUE THREAD

**Issue by rookie10501** [EDCD/EDDI#1873]
## EDDI version in which issue is found
3.7.0-rc1

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Open EDDI
2. Observe no respronder tab

## Expected
Responder tab on the left side

## Observed
Responder tab is missing

## Investigation
Restarted EDDI
Tried installing 3.5.2 (still no responder tab)

**Comment by rookie10501** [comment]
Full uninstall. Delete all EDDI files and restart computer. Installed 3.7.0-rc1 and is now working

**Comment by Tkael** [comment]
This is rare but we've seen this before. There is usually a problem with one of the config files that causes EDDI's tabs to fail to load. Clearing the config files likely resolved the issue.
