### ISSUE TITLE
EDDI tab has hotlinks referencing dead URLs

### ISSUE THREAD

**Issue by ncolton** [EDCD/EDDI#1876]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Start EDDI
2. On EDDI tab, click "EDDI" in "EDDI has a number of features that can be configured separately. There are three different types of items" at top, or click "Troubleshoot common issues"
3. Get 404

## Expected
Something not a 404

## Observed
Sent to https://github.com/EDCD/EDDI/blob/master/README.md or https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md respectively.

## Investigation
The branch named "master" no longer exists in the project, rendering the URLs those hotlinks point to being dead links.

**Comment by Tkael** [comment]
Thanks. Looks like renaming the release branch from "master" to "stable" had a few very minor knock-on effects. 

For reference, the links should point to:
https://github.com/EDCD/EDDI/blob/stable/README.md
https://github.com/EDCD/EDDI/blob/stable/TROUBLESHOOTING.md
