### ISSUE TITLE
New script bugs in v3.7.0: 'Crime check station' and 'Location' scripts

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1877]
## EDDI version in which issue is found
v.3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Run 'Crime check station' and 'Location' scripts.

## Expected
Scripts to function as expected.

## Observed
Scripts produce unexpected results.

## Investigation
Sorry the above is a little vague, I wasn't really sure how to describe this.  First, I want to say thanks for the update, I really like what's been done with the new and updated scripts.

While looking over them to see what's changed, I noticed a couple of things in the 'Crime check station' and 'Location' scripts.

In **'Crime check station'**, when reporting at the end, if there are bounties and/or fines, but no claims, the script is saying 'and', and then just stopping.  This results in "There are facilities at this station to clear your pending bounties and."  This can be fixed by changing the code to:
```
    {if bounties || fines || claims:
        There are facilities at this station to
        {if bounties || fines: clear your pending
            {if bounties: {if bounty_count = 1: bounty |else: bounties} {if fines: and}}
            {if fines: {if fine_count = 1: fine |else: fines}}
            {if claims:, and}
        }

        {if claims: claim your pending
            {if claim_count = 1: reward |else: rewards}
            for hunting services rendered
        }.
    }
```
This now results in "There are facilities at this station to clear your pending bounties."  If all three items are true, then it says "There are facilities at this station to clear your pending bounties and fines, and claim your pending rewards for hunting services rendered."  I added the comma to help the flow of the speech as it didn't sound right without it. (Edited: for clarity).

By changing the check to just 'claims', and moving it up into the previous check (rather than keeping it as is, and moving it down to the next check), it shortens the code and only has to perform the one check (for claims) instead of two checks (for bounties OR fines).

In **'Location'**, it looks like the reporting at the end for station and system, missions and crimes, has been copy/pasted and then updated.  However, the last two (for system missions and crimes) have not been fully updated as they both still say 'station'.  This leads the script to repeat the station versions instead of the system versions.  I believe the script should say:
```
    {if system_missions:
        {Pause(500)}
        {system_missions}
    }
    {if system_crimes:
        {Pause(500)}
        {system_crimes}
    }
```

I'm sorry that I didn't notice these earlier (as they've been new since v3.5.3-b3) but I tend not to look at betas much.  I guess I should do though. :(

While writing this, something occurred to me:  would you like me to go over scripts when they are new, or get updated?  Like a 'second set of eyes', or a 'fresh perspective' kinda thing.  Proof-reading for you, is what I'm thinking of.  Things like the above just seem to jump out at me when I look over them (I found the above without even running them or the game).  Well, the offer is there if you want. :)

**Comment by Tkael** [comment]
@Hoodathunk, mind looking into this please? Thanks!

**Comment by Tkael** [comment]
@Darkcyde13 Thank you for the feedback. If in the future you can manage to keep up with the betas and provide your feedback on script changes, we'd be happy to have your perspective on them. ;-)

**Comment by Tkael** [comment]
`Crime check station` was resolved by https://github.com/EDCD/EDDI/commit/1fa25fac206d4b01ae31dd1feeb780f3281b10bd.

Regarding the `Location` script, I think this is ok. 
- `station missions` and `station crimes` are only set if we're at a station
- `system missions` and `system crimes` are only set if we're not at a station

I'll go ahead and close this but please respond if you have any lingering concerns. o7

**Comment by Darkcyde13** [comment]
It's that the default script will report the wrong information.  With how it is at the moment, if 'system_missions' or 'system_crimes' are set, then it is the 'station' versions that will be reported, not the 'system' ones.

The script sets 'system_crimes' (for example) but the final IF statement only checks if this is set, it doesn't use the contents of it.  So, if you have crimes in the system, the script will try to tell you of crimes at the station, and if this is not set, it will not report anything at all, even if you do have crimes in the system.

**Comment by Darkcyde13** [comment]
This is the default:
```
{if station_missions || station_crimes ||system_missions || system_crimes:
    {Pause(500)}
    Information:
    {if station_missions:
        {Pause(500)}
        {station_missions}
    }
    {if station_crimes:
        {Pause(500)}
        {station_crimes}
    }
    {if system_missions:
        {Pause(500)}
        {station_missions}
    }
    {if system_crimes:
        {Pause(500)}
        {station_crimes}
    }
}

```
For it to work correctly, it should be:
```
{if station_missions || station_crimes || system_missions || system_crimes:
    {Pause(500)}
    Information:
    {if station_missions:
        {Pause(500)}
        {station_missions}
    }
    {if station_crimes:
        {Pause(500)}
        {station_crimes}
    }
    {if system_missions:
        {Pause(500)}
        {system_missions}
    }
    {if system_crimes:
        {Pause(500)}
        {system_crimes}
    }
}
```

**Comment by Tkael** [comment]
Ok, when I looked at it last night I think I saw the latter. I'll double check again though. Thanks!

**Comment by Tkael** [comment]
Sorry, I forgot to circle back to this before 3.7.1-b1 was released. 
You're right about the `Location` script. The next release will include the fix.
