### ISSUE TITLE
Issues with main window position restoration

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1878]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
Still under research in Discord, but in certain circumstances (currently unclear) a window that was closed on a secondary monitor is being forced back to the primary monitor when EDDI is next launched.

**Comment by richardbuckle** [comment]
The simplest explanation would be that [isWindowValid](https://github.com/EDCD/EDDI/blob/f3570f2a9663662efbc040b091a1a2243ee8756d/EDDI/MainWindow.xaml.cs#L121) is failing when it should pass. We could deploy some temporary debug logging to test this hypothesis.

**Note that we are using the Windows Forms [Screen](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.screen?view=netcore-3.1) object in a WPF app.** [This SO answer](https://stackoverflow.com/a/2707176) warns that WinForms display units are not pixels, and if you really want to use the WinForms `Screen` then you need to do the conversions.

Other options to consider:
- https://github.com/micdenny/WpfScreenHelper -- code looks clean repo is up to date
~~- https://www.codeproject.com/Articles/50761/Save-and-Restore-WPF-Window-Size-Position-and-or-S - I'd need to review this one~~
~~- https://stackoverflow.com/questions/37927011/in-wpf-how-to-shift-a-window-onto-the-screen-if-it-is-off-the-screen - this one seems like overkill~~

Considered and rejected:
- https://stackoverflow.com/questions/10434338/determine-if-an-open-wpf-window-is-visible-on-any-monitor - doesn't take into account that the Virtual Screen is a polygon and not necessarily a simple rectangle.
- https://www.codeproject.com/Articles/50761/Save-and-Restore-WPF-Window-Size-Position-and-or-S - Same as above.
- https://stackoverflow.com/questions/37927011/in-wpf-how-to-shift-a-window-onto-the-screen-if-it-is-off-the-screen - overkill, and the same problem as above.

**Comment by richardbuckle** [comment]
The perfect is the enemy of the good. I think I will revise the condition for `isWindowValid` to "is every corner of the proposed rect on one of the screens?" 

In other words, if any corner of the proposed rect is off-screen, fail and relocate to the main screen. This may be a bit too severe but it shouldn't affect a stable set-up.

**Comment by richardbuckle** [comment]
We could alternatively test the corners of the implied title bar rather than the entire window.

**Comment by richardbuckle** [comment]
I'm happy to take point on this one; it's the sort of thing I enjoy.

**Comment by GioVAX** [comment]
Based on the code, the only way it seems plausible to fail is if `Properties.Settings.Default.WindowPosition` got somehow corrupted.
Any other paths through the code should produce the correct answer, whether success or fail.

Is this happening frequently?
Can we add some logging to what is returned from `Properties.Settings.Default.WindowPosition`?

**Comment by richardbuckle** [comment]
I think you are overlooking what I wrote above, that [this SO answer](https://stackoverflow.com/a/2707176) warns that WinForms display units are not pixels, and if you really want to use the WinForms Screen then you need to do the conversions.

One user has already confirmed that they had one auxiliary screen at 200%.

**Comment by Tkael** [comment]
Agreed that `isWindowValid()` is the most likely culprit. Also agreed that the fact that we're treating WPF units like pixels is quite possibly the culprit. Until we've identified the specific conditions that cause EDDI to forget its window position, however, we still have to regard any fix as speculative. A second user (T1-Jafo) with this issues reports this failure or a similar one with no monitor scaling (using one 3440x1440 monitor and a second 2560 x 1440 monitor, arranged horizontally, with EDDI in standalone mode).

If it's failing when it should pass when testing with two corners, getting stricter by testing additional corners won't help. I think we should focus on the units issue @richardbuckle identified for WPF vs. Windows forms first.

**Comment by GioVAX** [comment]
Sorry, what I meant was that the logic of the code looks correct, so, beyond the problem of the units, the only other problem could be the values coming from `Properties`.

If we have a user that can reproduce the issue "consistently", we might give them an ad-hoc build with additional logs to pinpoint the root cause.

**Comment by richardbuckle** [comment]
Initial single-screen testing with display scaling indicated correct results from existing code:

```cs
// 100% scaling
rect = {1368,78,1050,1057} // System.Windows.Rect
rect.BottomRight = {2418, ‬‭1135‬}

Screen = {
Bounds = {X = 0 Y = 0 Width = 2560 Height = 1440} // System.Drawing.Rectangle
WorkingArea = {X = 0 Y = 0 Width = 2560 Height = 1400} // System.Drawing.Rectangle
Primary = true DeviceName = "\\\\.\\DISPLAY6"
}

// 125% scaling
rect = {1368,78,1050,1057} // same
screen = {
Bounds = {X = 0 Y = 0 Width = 2048 Height = 1152} // correctly scaled
WorkingArea = {X = 0 Y = 0 Width = 2048 Height = 1112} // correctly scaled
Primary = true DeviceName = "\\\\.\\DISPLAY6"
}
```

Also, I see that `System.Windows.Rect`, `System.Windows.Point` and friends implement the full suite of geometry primitives, so lets for example use its `Contains()` methods rather than rolling our own.

**Comment by richardbuckle** [comment]
It should be noted that this is a QoL issue, and that the current situation is far better than when the current team took over and there was no window state preservation at all.

**Comment by Tkael** [comment]
@richardbuckle Are you still looking at this?

**Comment by richardbuckle** [comment]
I'm afraid I haven't, no.
