### ISSUE TITLE
state.eddi_context_last_subject being automatically deleted between script executions.

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1879]
## EDDI version in which issue is found
V3.7.0

## VoiceAttack version in which issue is found (as applicable)
I tried both with and without VA v1.8.5.12.

## Steps to reproduce
1. Load game while landed on a planet.
2. Listen to Touchdown event.

## Expected
Touchdown event to say:
"Into The Black 2 has touched down on Colonia 3 d.  Coordinates are -35.17 degrees latitude, 56.41 degrees longitude."

## Observed
Touchdown event actually says:
"Touchdown on Colonia 3 d.  Coordinates are -35.17 degrees latitude, 56.41 degrees longitude."

## Investigation
It seems that the state.eddi_context_last_subject variable is being deleted, or set to nothing, between the 'Location' event and the 'Touchdown' event. As this state variable is used in the first IF check, the wrong speech is always spoken.

I first found this today when trying to stop the Docked event from saying "Docking complete" when loading a game.  I tried to use the same method that the Touchdown event uses to prevent just that part from being spoken.  When I loaded into my game docked at a station, it was still saying "Docking complete".  I added the line {state.eddi_context_last_subject} to the start of the Docked script, and nothing was spoken for it when I loaded into game.

I then went to a nearby planet surface to test out the Touchdown event.  When loading my game while landed, I got the same thing: the wrong speech option was being spoken (as described above).

So I reverted back to the default EDDI profile and tried again.  I loaded while landed and the wrong speech was spoken. I then made a copy of the default personality, and added {state.eddi_context_last_subject} to both the Touchdown and Docked events.  Again I loaded my game while on the planet surface and that varaible was not spoken (so was blank or null).

I've also run those tests without the game loaded at all.  I made a new command where I set {SetState('eddi_context_last_subject', "location")} and ran it.  Then I ran Touchdown as a test, and it worked perfectly.  I also did the same with my modified Docked script too, and that also worked fine.  However, running the tests again immediately, resulted in '...last_subject' once again becoming blank.  I even temporarily removed the SetState for last_subject from the end of the Touchdown script, and it was still being erased after the first run.

To test, I did the following without the game loaded:
1. Create new copy of the default personality.
2. Create new script with {SetState('eddi_context_last_subject', "location")} in it, and run it.
3. Edit out the SetState for last_subject from the end of Touchdown so that it's not overwritten.
4. Added a test line of {state.eddi_context_last_subject} to the start of Touchdown script.
5. Run the test of Touchdown script.  It worked as expected, and the test line said "location".
6. Immediately run the test of Touchdown again. It failed to work correctly, and the test line was not spoken.

So it seems that somehow, somewhere, state.eddi_context_last_subject is being overwritten or set to null, outside of the running of any scripts.

To check if this happend to any other state variables, I added a couple more test lines to point 2. above called 'eddi_context_test_1' and '...test_2' and set them to "Test 1" and "Test 2" respectively, and added corresponding check lines to Touchdown.  I repeated the tests, and both of those line remained set correctly through 3-4 test runs, while 'last_subject' only worked for the first run, but not subsequent ones.

As one final test, I did point 2. above to set the variable, then created a new script with only {state.eddi_context_last_subject} in it.  When I run this, "location" was spoken for the first run, but not for any others.  So it seems that it's not even dependant on any particular script, as it's always deleted (or nulled) once it has been used once.

EDIT: I just tried one more test. As above, setting the last_subject variable. Created a new script with just "test me" in, and run that.  Create a new script with {state.eddi_context_last_subject} in and run that.  Nothing was spoken, so it doesn't even have to be referenced in a preceding script, for it to be deleted.

**Comment by Tkael** [comment]
This is per JGM's original design. I think that his intent was to ensure that scripts which did not give an explicit context would not trigger anything in the context interactions that he was planning.

Ref. https://github.com/EDCD/EDDI/blob/f3570f2a9663662efbc040b091a1a2243ee8756d/SpeechResponder/ScriptResolver.cs#L102-L108 and https://github.com/EDCD/EDDI/blob/f3570f2a9663662efbc040b091a1a2243ee8756d/SpeechResponder/ScriptResolver.cs#L129-L137

I think that this is essentially an artifact from a feature that JGM never finished. @Hoodathunk and @richardbuckle, what are your thoughts on removing this?

**Comment by Tkael** [comment]
Marking as confusing because the current practice of deleting these user-exposed states between scripts isn't obvious to the end user.

**Comment by Darkcyde13** [comment]
Ahh, I see.  That makes sense as to why it was also happening when I tried previous versions this morning (v3.5.0 & v.3.4.3).

In that case then, it's stopping the default Touchdown script from working as intended, because last_subject is being cleared before Touchdown is run.  I can get around this by just creating another state variable in Commander Continued to do the same job.

Thanks for the info Tkael! :)

**Comment by richardbuckle** [comment]
In commit 18e5fa36f4e6489012f4a43d9fe234cebee3276b jgm went from *always* clearing that state to *only* clearing it for top-level scripts. I am not entirely sure of the reason that they are being cleared at all.

**Comment by Tkael** [comment]
I believe it was so that context states wouldn't survive past the initial triggering event where that context state might no longer be valid. The context wouldn't be recycled and would need to be set again. 

For a sense of jgm's intentions at the time, please see the release notes for versions [2.1.1-b2](https://forums-new.frontier.co.uk/threads/eddi-windows-app-for-immersion-and-more.294579/post-5098951) and [2.2.0](https://forums-new.frontier.co.uk/threads/eddi-windows-app-for-immersion-and-more.294579/post-5124296) (both from Feb. 2017, just a few weeks after the commit you noted above was made).
