### ISSUE TITLE
Script Error Warnings

### ISSUE THREAD

**Issue by daBernd** [EDCD/EDDI#1883]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.6.5

## Steps to reproduce
1. Surface scanning rings or boddies
2. when scan is done the error appears

## Expected
a detailed info about the body or the ring

## Observed
Eddi says: "Error with body/ring mapped script. Exception has been thrown by the target of an invication"

## Investigation
I tried to restart VoiceAttack - but the error still exists.
I then quit elite to desktop and voiceAttack and restarted both. Then all Info aout the detected Hotspots an geological signals were "told" by Eddi

**Comment by Tkael** [comment]
Please provide a zipped up copy of EDDI's log files (saved at %appdata%/EDDI and ending in .log)?

**Comment by Tkael** [comment]
Does this occur every time or did it occur just the once?

**Comment by Tkael** [comment]
I spent some time scanning bodies and rings this evening but I wasn't able to replicate the issue that you're describing. Are you using a custom personality? If so, does the issue to occur if you swap to the default personality?

**Comment by daBernd** [comment]
Hi Brian,

sorry for being late. I just now saw the mails from you. Here are log-files from EDDI. It only appeared once for now… and I recently jumped a lot. Sorry I cannot reproduce the error. I will send you a new error message when the error occurs next time.

 

Best regards and thank you for the great work. 

 

Bernd

 

Von: Brian Wilson <notifications@github.com> 
Gesendet: Mittwoch, 8. Juli 2020 19:32
An: EDCD/EDDI <EDDI@noreply.github.com>
Cc: daBernd <Bernd.Hoeh@d-w-d.de>; Author <author@noreply.github.com>
Betreff: Re: [EDCD/EDDI] Script Error Warnings (#1883)

 

Please provide a zipped up copy of EDDI's log files (saved at %appdata%/EDDI and ending in .log)?

**Comment by Tkael** [comment]
Hi daBernd, if you attached your log files to your email, they didn't come through on Github. You'll need to open this ticket on Github and manually attach the files to a reply comment. Thanks!

**Comment by Tkael** [comment]
Closing for lack of feedback and for similarity to #1894.
