### ISSUE TITLE
Distance() function giving wrong results

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1884]
## EDDI version in which issue is found
v3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Use the Distance() function to find the distance between two star systems.  For example {Distance("Colonia", "Hephaestus")}

## Expected
The correct distance to be given. For Example "11.55"

## Observed
The distance reported is very wrong. For example "19829.03"

## Investigation
I was having trouble with my route plotting, as I wanted to see if I could just discard the whole thing in favour of the EDDI default.  I tracked down my problem to the Distance() function which was producing wildly wrong distances.

As above, for Colonia to Hephaestus (which is only 11.55 LY) it is reporting 19829.03 LY. I've also tried with Sol to Alpha Centauri (which is 4.38 LY) and that reported only 3.03 LY.

I reverted back to EDDI v3.5.2 and Distance() works perfectly fine, giving the correct distances.  I reinstalled v3.7.0 and they are once again very wrong.

I had been initially using the X Y Z co-ords for Distance() when I found it to be wrong, so I tried just the system names directly, but it's still doing the same.

**Comment by Tkael** [comment]
Good catch. Looks like we forgot to add a couple of very necessary parenthesis after we touched up that function in mid-January and never caught it until now. Pull request #1887 submitted.
