### ISSUE TITLE
Mission check galaxy script bug

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#1886]
## EDDI version in which issue is found
v3.7.0

## VoiceAttack version in which issue is found (as applicable)
v1.8.5.12

## Steps to reproduce
1. Accept a 'locate cargo' mission from an in-game comms message.
2. Log off from game and exit VA.
3. Open VA and reload game.

## Expected
'Mission check galaxy' (in Commander continued) to report "You have 1 pending mission with no designated target system."  Although, to be honest, I didn't really expect anything.

## Observed
'Mission check galaxy' actually reports "You have 1 pending mission**s** with no designated target system."

## Investigation
I accepted a "locate missing cargo" mission from a comms message.  I checked the mission monitor and it did not appear.  I expected this though, as there was no corresponding journal event.  This is why I didn't expect anything to be reported when I loaded again.

I logged out of game and VA to go get something to eat, and when I reloaded to play again, I noticed that the report from 'Mission check galaxy' said 'missions' (plural) and saw that the mission was now in the Mission Monitor.  There is no destination system or station, but I guess this is due to the type of mission, as I have to go and find it's location.  I assume this is all taken from the game loading data. (I've now checked and found the journal entry).

I looked over the script for 'Mission check galaxy' to see why it used the plural for missions, but couldn't see anything wrong to begin with.  After looking at the EDDI variable list, I noticed that the part that is reporting, uses 'missionCount', when it should be 'missionsCount' (with an 's').  After correcting this, the script now works as expected, using the singular 'mission'.

EDIT: I just found the same problem at line 72 for failed missions.  The one above, is at line 107.

**Comment by Tkael** [comment]
I think that @Hoodathunk is going to want to take point on this one too.

**Comment by Tkael** [comment]
Thanks for reporting this, I've fixed the typo. 
FYI, when you start the game a list of active missions is written to the player journal and it is this that allowed EDDI to become aware of the mission after you reloaded the game.
