### ISSUE TITLE
Verbose logging request

### ISSUE THREAD

**Issue by Sekotser** [EDCD/EDDI#189]
## Steps to reproduce
Verbose logging as requested
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1423110/eddi_issue.zip)
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1423113/eddi_issue.zip)

**Comment by Tkael** [comment]
What is the issue that needs to be investigated here? It's not clear from the description.

**Comment by Sekotser** [comment]
I was asked to record a log by EDDI developers, and paste it to the Github
issue report

**Comment by Tkael** [comment]
I see that, but which conversation on the forums? What is your forum name?

**Comment by Tkael** [comment]
This may be related to issues #181 and #183. Referencing issue numbers to link to those issues, then closing this issue as unclear and potentially redundant.
