### ISSUE TITLE
Some scripts of the default personality of Speech responder are broken in some languages

### ISSUE THREAD

**Issue by Test-of-gource** [EDCD/EDDI#1890]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. switch application's language to any language other than English or Japanese
2. try to test some script like "Asteroid Prospected"

## Expected
It would say "Asteroid contains 26% low temperature diamonds. It is 10% depleted"

## Observed
It says nothing 😔

## Investigation
Probably separate default EDDI personalities by language requires to solve this issue...

**Comment by richardbuckle** [comment]
Invalid. We already have language-specific default personalities in the form `eddi.xx.json` where `xx` is the language code.

**Comment by richardbuckle** [comment]
They are not currently on CrowdIn because the format isn’t very amenable; in the longer term we hope to solve that.
