### ISSUE TITLE
Add a `lastevent` object to the Speech Responder and VoiceAttack?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1892]
As suggested by @Hoodathunk in private chat. Properties would be accessible from Cottle and VA.

**Comment by richardbuckle** [comment]
Presumably that would require script changes in both Cottle and VA?

**Comment by Tkael** [comment]
We'd be looking at saving/updating the value as it is processed through EDDI.cs and referencing it in both VoiceAttackVariables.cs and ScriptResolver.cs.
Script changes wouldn't immediately become necessary but the change would open new options for future script changes.

**Comment by Tkael** [comment]
Closing as I'm not seeing much immediate use for this at the moment.
