### ISSUE TITLE
Exception has been thrown by the target of an invocation (when starting in an SRV)

### ISSUE THREAD

**Issue by TechRoss** [EDCD/EDDI#1894]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
1. It seems after using a SRV and then boarding the ship , EDDI is getting confused. 
2. If you make a Supercruise jump, EDDI will report "your SRV is in transit to..." which is what has lead me to believe it is when this problem starts.
3. This also affects other scripts like the script run after fuel scooping, the discovery script, the star discovery script, etc after this and the only way to resolve this that I have found is to reboot my PC. 
3.1 Scripts start reporting "Exception has been thrown by the target of an invocation"
3.2 (Full Log Line) 2020-07-13T17:02:14 [Info] EDDI:eventJumped Jumped to Har Itari 
2020-07-13T17:02:14 [Warning] ScriptResolver:resolveFromValue Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
3.3 

## Expected
Scripts to run as they normally would and report on event.

## Observed
This started happening when I upgraded to version 3.7.0. 
[EDDI.zip](https://github.com/EDCD/EDDI/files/4914092/EDDI.zip)

This seems to happen after using a SRV on a planet surface and then boarding the ship again. 

## Investigation
I was using a modified personality so I changed back to the default personality with no successes. 

I attached a ZIP of the logs.

**Comment by richardbuckle** [comment]
eddi2.log in the zip shows this at line 137.

**Comment by richardbuckle** [comment]
This is puzzling because I have been doing exactly the same (use SRV, board ship, jump to supercruise) without seeing this. However I am not using VoiceAttack.

@TechRoss Are you using the default speech scripts?

**Comment by Tkael** [comment]
VoiceAttack should be immaterial here unless the Script Resolver is being invoked by a VoiceAttack plugin command (`say` or `speech`).
@TechRoss Do you have a VoiceAttack command that triggers off of this event? If so, can you share that command to help us to replicate this issue?

**Comment by Tkael** [comment]
Also... 
1. does this occur for every ship in your shipyard or only for a specific ship?
2. do you have multiple accounts for Elite Dangerous?

**Comment by Tkael** [comment]
If you could, please make sure that the commands from EDDI.vap are available from your VoiceAttack profile.
1. On a fresh game where this hasn't yet triggered, please hit LEFT CTRL + LEFT ALT + LEFT SHIFT + 3 to trigger the ((EDDI: ship variables)) command and dump those values to the VoiceAttack log. 
2. Repeat the process after the error occurs.
3. Copy and paste the values from both before and after the error occurs here. 

This will allow us to inspect the state of the ship both before and after the triggering event. Thanks!

**Comment by TechRoss** [comment]
> @TechRoss Do you have a VoiceAttack command that triggers off of this event? If so, can you share that command to help us to replicate this issue?

No I let EDDI report on events. 

I have only been flying one ship for a while now. I can try in another ship later today and see what happens.

I will also check the variables when I try the new ship and output to log.

I only have  a single ED account.

**Comment by TechRoss** [comment]
> @TechRoss Are you using the default speech scripts?

I have a custom personality if that is what you mean but I did switch this back to the default and I still had the issue.

**Comment by TechRoss** [comment]
Just an update: Last night I did uninstall EDDI and then reinstall with a fresh downloaded copy. I had to relink my Frontier account but I did not get a chance to test in game as it was already very late, so will see how that goes today.

**Comment by TechRoss** [comment]
Hi guys, sorry only managed to get back to a station with my other ships last night. Managed to use the SRV without a issue. Will try the original ship again today to see what happens.

**Comment by ITZAP** [comment]
At Jameson's Crash Site (HIP 12099) driving around in my SRV I was getting the speech "**_Exception has been thrown by the target of an invocation_**".
Also speech saying "**_Error with this script. (something) not set to an instance of an object._**"

**Comment by Tkael** [comment]
@ITZAP I'm not sure that's entirely related to the OP's issue though it sounds like you've heard a similar error message. Can you open a seperate ticket and include your logs from the incident (located at %appdata%\EDDI)?

**Comment by Tkael** [comment]
@TechRoss Any update?

**Comment by ITZAP** [comment]
@Tkael ... Not sure about log files, but if you just visit Jameson's Crash Site and launch your SRV, then you will hear all the error speech mentioned.

**Comment by Artanisx** [comment]
Is there any way to mute these errors? I keep getting several of them (often in a row). It's fine if there is some issue with some script, but it's made so much worse with the text-to-speech feature which says it out aloud over and over again :(

**Comment by TechRoss** [comment]
Hi guys, did some more testing over the weekend. I am able to replicate this reliably now. It seems to happen when you spawn in and you are in your SRV on a planet surface. I was doing this at Dav's Hope. relogging and this is where it happens.

You will get the first error when it fires the landing script and then it continues.

I then tried the same thing on other planets, and did not get the error. This was in the open and then tried close to stations, bio and geo areas. I should have tried Jamerson, but I battle to find it. I see somebody else mentioned Jamerson so I wonder if it has something to do with the close to whatever station etc. When it gives that feedback, it says $S is close to.....

I am such a dork, I was so busy trying this, I never thought to dump the variables as asked.

**Comment by TechRoss** [comment]
@Artanisx there is a command in EDDI to shut her / him up. You will have to use that for now until the guys can figure this out.

It is literally Execute external plugin and send shutup

**Comment by Artanisx** [comment]
> @Artanisx there is a command in EDDI to shut her / him up. You will have to use that for now until the guys can figure this out.
> 
> It is literally Execute external plugin and send shutup

@TechRoss That's great :-) Could you please tell me how to send this command? Sorry, but I'm very new, I've installed EDDI literally yesterday :D Thanks again!

**Comment by TechRoss** [comment]
@Artanisx are you using VoiceAttack? I only know how to do it from VA and not if you only running EDDI.

**Comment by Artanisx** [comment]
I'm not using Voice Attack unfortunately :(

**Comment by Tkael** [comment]
The `shutup` command would apply to the entire personality. I'm more interested in determining the precise script that is triggering the incorrect state for all of the following scripts. It sounds like that may be the `Touchdown` event? A verbose log would capture that for sure.

**Comment by TechRoss** [comment]
Hi

I went back to Dav's Hope to get the variables. I battled to get it to throw the error. So I retraced my steps from Saturday night and I think I have a little more help. I have a command in my VA to open the EDDI config (pass configuration). If I open the EDDI config thru VA and thin go into my mission, with my SRV on the planet surface, it throws the error.

Error with touchdown script.

I have attached the verbose log and a zip containing the VA vars output before the error and then after the error.
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/4948243/eddi_issue.zip)
[va_vars.zip](https://github.com/EDCD/EDDI/files/4948245/va_vars.zip)

**Comment by Tkael** [comment]
Ok. This one took some sleuthing but I have some findings now...
1. The ship model is being passed from the `Commander continued` event as "SRV" rather than as "TestBuggy" (the FDev internal name for the SRV).
2. Starting the game in an SRV isn't supposed to create a new entry in the ship monitor and change your currently active ship, but because the ship model is set to "SRV" (rather than "TestBuggy", which is what the Ship monitor currently expects), our internal filter on creating a new ship and setting it as the active ship fails in this circumstance.
3. That leaves us with an SRV "ship" with various null / undefined values.

**Comment by Tkael** [comment]
4. This creates a null reference exception when trying to access the "Size" property of the SRV "ship" (since the size is determined by the ship model and there is no ship model matching "SRV")

**Comment by Tkael** [comment]
Best mitigation until a new version is released is to swap ships and to not start the game in an SRV.
