### ISSUE TITLE
EDDI - tabs not loaded, exception thrown from failure to load elite.json

### ISSUE THREAD

**Issue by ze-carlos** [EDCD/EDDI#1897]
## Steps to reproduce
1. Start EDDI (Frontier API connected)

## Expected
To "see" the three groups:
- the first group;
- the second group (which obtains event information);
- the third group (that responds to events)

## Observed
Only the first group shows.

## Investigation
Issue started with version 3.3.
I've uninstalled EDDI, deleted any folder "left over", run CCleaner and Glary Utilities to clear any junk left behind, to no avail...

**Comment by Tkael** [comment]
I'm sorry but i don't follow your meaning. What "groups" are missing? If it helps, you can attach screenshots to this ticket.

**Comment by ze-carlos** [comment]
Here they are. Sorry, no time for clipping them.

![image](https://user-images.githubusercontent.com/68303343/87519595-c06e0680-c679-11ea-9d00-16356bafdc96.png)

![image](https://user-images.githubusercontent.com/68303343/87519610-c663e780-c679-11ea-801f-efceb09b5b99.png)

![image](https://user-images.githubusercontent.com/68303343/87519639-cd8af580-c679-11ea-8c75-62a20d265801.png)

![image](https://user-images.githubusercontent.com/68303343/87519658-d380d680-c679-11ea-96f5-06522aedb2b5.png)

**Comment by Tkael** [comment]
I see that you closed the ticket. Did you figure out the issue?

We've seen similar issues in the past when an exception occurs while loading data from EDDI's config files.

1. EDDI's log files are located at %appdata%/EDDI. If you can zip up a spot of your log files and attach it, that may help us to identify the specific issue.
2. Following the steps at https://github.com/EDCD/EDDI/blob/develop/TROUBLESHOOTING.md#eddi-doesnt-start-or-crashes-on-startup would probably help you (and us) to identify the problem config file.

**Comment by ze-carlos** [comment]
Sorry, n00b here...
[EDDI.zip](https://github.com/EDCD/EDDI/files/4924083/EDDI.zip)

**Comment by Tkael** [comment]
Looks like elite.json is corrupt. Please follow the troubleshooting steps described above except just remove elite.json. That should be all that's needed to restore EDDI.

**Comment by Tkael** [comment]
For debugging reference, this is the corrupt file (it contains no commander specific information).
[elite.zip](https://github.com/EDCD/EDDI/files/4928890/elite.zip)

**Comment by ze-carlos** [comment]
It solved the issue as soon as I deleted the elite.json file.
Thank you very much!

![image](https://user-images.githubusercontent.com/68303343/87645820-f1b40880-c745-11ea-9a35-a107c601ece4.png)
