### ISSUE TITLE
Script "Signal detected" causes an error in the Maia system

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#1898]
## EDDI version in which issue is found
v3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.6

## Steps to reproduce
Fly into the Maia system (at time of writing)

## Expected
Nothing out of the ordinary

## Observed
About 20 repeats of: "There was an error in this script" for "Signal detected". Stating: "Parameter cannot be null: source".

## Investigation
Dug into the code for the script and found this:
````
{if status.guifocus = "fss mode" || status.gui_focus = "saa mode" || 
(spokenSources[event.source] = true && find(system.signalsources, event.source) = -1):
    {if event.source && !event.stationsignal:
        {if event.threatlevel > 0:
            Class {event.threatlevel} 
        }
        {event.source} 
        {if event.faction != "None":
            for {event.faction}
        }
        detected.
    }
}
````
The first if will fail if event.source is null, as find does not allow that. This would work fine with the {if event.source && !event.stationsignal: was moved up:
````
{if event.source && !event.stationsignal:
    {if status.guifocus = "fss mode" || status.gui_focus = "saa mode" || 
    (spokenSources[event.source] = true && find(system.signalsources, event.source) = -1):
        {if event.threatlevel > 0:
            Class {event.threatlevel} 
        }
        {event.source} 
        {if event.faction != "None":
            for {event.faction}
        }
        detected.
    }
}
````

**Comment by nepomuk16321** [comment]
Please look at the second line. The variable is misspelled. Correctly it is called **"status.gui_focus"** as after the || (OR) symbol.

**Comment by eavdmeer** [comment]
That may be the case, but it's not what's causing the error. The suggested code fixes it. Also, the voice responder clearly reads out they the error is that the parameter source cannot be null

**Comment by Darkcyde13** [comment]
When the error is read out, it should have specified which line number it was at.  Does that match the line you mention?  I've tried manually running the code with a null in place of 'event.source', and don't get that error, so I'm just curios.  Even with the find() test looking for a null value, it should resolve to -1 as null is not found.

I tried this code, which should simulate the line you mention:
```
{set test to ["1","2","3","4"]}
{if find(test, test2) = -1: no}
```
In this, test2 is null as it has not been set, yet this still resolves as -1, and "no" is voiced, because it is not in 'test'.

The reason your fix works is because the first check is now to see if event.source has valid data, which it does not when it is null, and thus the code skips the rest.  I have a feeling the problem may lie elsewhere...

**Comment by Tkael** [comment]
1. Typo confirmed. We'll want to fix that. 
2. Could I ask you to share the relevant entries from your player journal to help us replicate your observation?
The player journal is located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/ and the files end with the .log suffix. We'll looking for lines containing the key word "FSSSignalDiscovered" from your most recent .log files.

**Comment by nepomuk16321** [comment]
I corrected the wrong variable. After that many (I could not check all of them) signal sources were announced in different systems. But I was not in Maia.

**Comment by eavdmeer** [comment]
Your tests do seem to indicate that perhaps EDDI got into a confused state. That does tend to happen every now and then. The original message certainly did not include a line number. I would have remembered that. It just told me the script name and 'parameter cannot be null'. I'll try to dig through the journal entries to find the relevant ones. That could take a day or two though

**Comment by eavdmeer** [comment]
[Maia.log.txt](https://github.com/EDCD/EDDI/files/4942336/Maia.log.txt)

Here are the log events. Seems like a whole bunch of fleet carriers. Confusing that they use IsStation=true for those. Definitely not a station. They should get their own flag. Does look like the names are all uppercase though.

**Comment by Tkael** [comment]
In most ways, FDev treats carriers like stations so it's consistent(ish) at least.

Unfortunately, I'm not getting the same exceptions from these journal events (simulating seeing these events while the current system is set to Maia).

1. Does this issue recur on every visit or was it a one-time issue?
2. Are you certain about the syntax of the error message that you heard? If no script line was included in the message then I'd expect the message to be more like: "Error with Signal detected script:  Parameter cannot be null: source". If you heard "this script" rather than "Signal detected script" then that might indicate that the script was triggered by something other than a direct journal event?
3. A corresponding entry should have been written to EDDI's log files (saved to %appdata%\EDDI and ending with .log). If you can find that entry then that may help shed further light on this too.

**Comment by eavdmeer** [comment]
1. I'll have to get back to you on that. I'm close to Maya again, so I'll have a look.
2. It absolutely mentioned the Signal detected script. That's why I checked that. I was paraphrasing on the message.
3. I'll have a look

There is every chance that this was a once off

**Comment by eavdmeer** [comment]
[Maia.EDDI.log.txt](https://github.com/EDCD/EDDI/files/4949187/Maia.EDDI.log.txt)

Here is the EDDI log for the jump to Maia. It shows a ton of exceptions. All like this:
````
2020-07-16T17:59:39 [Warning] ScriptResolver:resolveFromValue Value cannot be null.
Parameter name: source System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Cottle.Values.ReflectionValue..ctor(Object source, BindingFlags binding)
   at Cottle.Values.ReflectionValue.Resolve()
   at Cottle.Values.ResolveValue.Acquire()
   at Cottle.Values.ResolveValue.get_Type()
   at Cottle.Builtins.BuiltinFunctions.<>c.<.cctor>b__47_13(IList`1 values)
   at Cottle.Functions.NativeFunction.<>c__DisplayClass13_0.<.ctor>b__0(IList`1 v, IStore s, TextWriter o)
   at Cottle.Functions.NativeFunction.Execute(IList`1 arguments, IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Evaluators.InvokeEvaluator.Evaluate(IStore store, TextWriter output)
   at Cottle.Documents.Simple.Nodes.IfNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.Simple.Nodes.CompositeNode.Render(IStore store, TextWriter output, Value& result)
   at Cottle.Documents.SimpleDocument.Render(IStore store, TextWriter writer)
   at Cottle.Documents.AbstractDocument.Render(IStore store)
   at EddiSpeechResponder.ScriptResolver.resolveFromValue(String script, BuiltinStore store, Boolean isTopLevelScript, Script scriptObject)
````
Looks like it was not the source parameter in the script.

**Comment by Tkael** [comment]
Hmm. That looks very similar to the message we're addressing in #1894. Did you perchance start that play session in an SRV?

**Comment by eavdmeer** [comment]
That's a definite no. I came from Sterope II , with a Thargoid heart in my cargo bay after killing a Cyclops. I had an SRV bay and SRV in the ship, but I was not in it.

**Comment by nepomuk16321** [comment]
Is it possible that an entry in the list "spokenSources" is incorrect, maybe empty or with wrong syntax ?

**Comment by Tkael** [comment]
Possibly. Is it only `Signal detected` messages where you are seeing this exception?

**Comment by eavdmeer** [comment]
Confirmed it's not happening in Maia now (or yesterday, actually). This may have been a one-off. It still indicates some kind of error, of course. EDDI definitely gets its knickers in a twist every now and then

**Comment by Tkael** [comment]
Thanks for the update. We'll need to stay vigilante but I don't think there's anything further that I can do right now based on the rather generic error message that we're seeing.
