### ISSUE TITLE
Wrong ship details when starting in SRV

### ISSUE THREAD

**Issue by Labanden** [EDCD/EDDI#1899]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.6

## Steps to reproduce
1. Start Elite Dangerous Horizon in a SRV. Voice attack profile includes ((EDDI: ship variables)) from EDDI.vap(supplied with EDDI). created a ((EDDI commander loading)) voice attack entry that calls the ((EDDI: ship variables)).

## Observed
The above reports the ship is a Diamondback Explorer, which I do not have currently in my fleet on the account (never have had one). se below attached output from Voiceattack
[Landed out put at Commander Loaded for SRV.txt](https://github.com/EDCD/EDDI/files/4941971/Landed.out.put.at.Commander.Loaded.for.SRV.txt)

## Investigation
No further Investigation done. When in ship all reported correctly, currently do not have a SLF to test with that.

**Comment by Labanden** [comment]
I Made one mistake in this report, It should be Diamondback Scout not Explorer.

**Comment by Labanden** [comment]
[Landed out put at Commander Loaded.txt](https://github.com/EDCD/EDDI/files/4942024/Landed.out.put.at.Commander.Loaded.txt)
Just landed in the ship minutes earlier.

**Comment by Tkael** [comment]
1. The `((EDDI ship loadout))` event would be a more appropriate place to check the state of your variables. The `((EDDI commander loading))` fires at the very beginning of when we're starting to receive data from the game - before we've received any details about your ship loadout (though we might have already received some details about your ship and shipyard from the Frontier API if that is connected). 
2. Do you have more than one account? If so, which account is currently logged in via the Frontier API? (this is especially relevant if your other account has a DiamondBack Scout...)
3. Does this happen every time or is this a one-off error?

**Comment by Tkael** [comment]
4. If VoiceAttack was already running, had you already logged into Elite previously under a different account?

**Comment by Labanden** [comment]
1. Understood - will check.
2. Yes but not on that PC and I do not use the Frontier API on EDDI.
3. the twice i checked it
4. Fresh start on VoiceAttack each time. See above for account.

**Comment by Labanden** [comment]
Quick note for you.
((EDDI ship loadout)) does not trigger when starting game in SRV.

I need to review something, I may have done the original testing on my programming PC (this has been used for when ED Betas have been running) and is possible a DBS may have been involved with one of the accounts used.

**Comment by Tkael** [comment]
If so, your ~~shipyard.json~~ `shipmonitor.json` config file (located on your programming pc at %appdata%\EDDI) is likely associating your current ship local id / index with a Diamondback Scout. There'd be no other reason to connect them.

**Comment by Labanden** [comment]
Have checked the Programming PC, EDDI on there does have data of ships including a DBS. However the Frontier API is not currently logged in.
Why would it have picked the DBS, it is not first in the viewed list, that is an Adder, it also would not have been the last ship used as that would have been a Viper Mk III. The DBS and the Adder (along with a number of other ships) are on a different account, but not used recently. Last ship used prior to the Viper would have been a Keelback.

**Comment by Tkael** [comment]
Fair, the game may not write a loadout event when starting the game in an SRV. I believe you'd get one once you swapped back to your ship though.

**Comment by Labanden** [comment]
File content =
{ "timestamp":"2020-05-25T20:03:33Z", "event":"Shipyard", "MarketID":3701396736, "StationName":"G62-J5X", "StarSystem":"HR 7047", "Horizons":true, "AllowCobraMkIV":true, "PriceList":[ 

 ] }

**Comment by Labanden** [comment]
> Fair, the game may not write a loadout event when starting the game in an SRV. I believe you'd get one once you swapped back to your ship though.

Yes but needed to know which vehicle game started in, and I know it is not the correct data for that. It was a test only. Then observed the output I reported thought you needed to know.
 
the Vehicle variable did report correctly at all times (after being added and post reporting the error).

**Comment by Tkael** [comment]
Note: Looks like I accidentally wrote `shipyard.json` where `shipmonitor.json` was intended. Corrected above.

EDDI would think you were in the DBS if the "currentshipid" recorded in `%appdata%\EDDI\shipmonitor.json` matched the "localId" recorded in the same file for your DBS. Because we're checking the state of the variables before having received any content from the player journal and because you're not logged into the API, that config file would be the only possible source for the information that EDDI is reporting.

Please note that this file differs from the shipyard.json file whose contents you linked. The file whose contents you linked is a different file written by FDev and written to your [Saved Games] folder when you view the shipyard in a station. It describes the station's shipyard and has nothing to do with your personal shipyard configuration in EDDI.

**Comment by Labanden** [comment]
You may be right, cannot tell now as that file has been updated today.
But question.
On the day I reported the issue.
I purchased a SRV bay and SRV for my current ship ( a Viper). launched and landed on a planet. then deployed the SRV. Logged out of both ED and VA.
Started VA and ED, Logged on to ED and got the output described.
Surely the currentshipid should have been the one for the Viper not a DBS that has not been used on that computer account for months.
So my question is still why did it report as a DBS and not a SRV or possibly a Viper?

**Comment by Tkael** [comment]
I've identified a bug where the `Commander continued` event reports a ship id when you log in using an SRV (ref. #1894) and the the ship monitor changes the currentshipid to match the id reported there (so it no longer thought that you were in your viper but in your case it seems that the ship monitor matched the id for the DBS and so it didn't overwrite it with a definition for a new SRV "ship").

**Comment by Labanden** [comment]
Why would EDDI trigger a commander continued, just because i logged out of the game and then back in. How would it know? I thought that was for when the Journal file reached its limit.

**Comment by Tkael** [comment]
The `Commander continued` event is triggered by the `LoadGame` event from the player journal and not from the `Continued` event in the player journal. Consequently, you'll see `Commander continued` every time you load the game.
(I suspect the `Commander continued` event was named before the `Continued` event was added to the player journal but that was before my time and my records for past player journal revisions don't stretch back that far)
