### ISSUE TITLE
Local commodity definitions can change the edName reported by the EDDN responder on the `commodity` schema

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#1906]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Observe the output of an EDDN message for commodity ID 128667076

## Expected
The commodity name should be "SanumaMEAT"

## Observed
The commodity name is "SanumaDecorativeMeat"

## Investigation
- We pass CommodityMarketQuote objects inside of the MarketInformationUpdated event to the EDDN responder. The EDDN responder passes the edName property from the commodity definition property of the object as the commodity name.
- CommodityMarketQuote  objects are generated by looking up the local commodity definition by commodity ID. The edName in the commodity definition originates from EDDI's internal definition rather than from the original name given in the cAPI response or from market.json.
- This is a severe problem because the commodity id is not passed via the EDDN schema. The commodity edName is the primary key for all EDDN feed consumers and it is being transformed / not being conserved when we look up and apply a local definition by its commodity ID.

Proposed solution: We handle station updates in the same methods where we generate the MarketInformationUpdated events, and consequently we can pass the original values to the EDDN responder in the MarketInformationUpdated event rather than values which may have been transformed by EDDI's internal definitions. 
- For the commodities endpoint, pass List\<EDCommodityMarketQuote\>, where each EDCommodityMarketQuote contains only the original data received from cAPI or from market.json and is similar to the current `EDDNCommodity` class currently in the EDDNResponder namespace)
- For the outfitting endpoint, pass List\<string\>, where each string is an edName for a module.
- For the shipyard endpoint, pass List\<string\>, where each string is an edName for a ship model.

**Comment by bgol** [comment]
And another one: `CD-75KittenBrandCoffee` should be `CD75CatCoffee` (id: 128667042)

**Comment by Tkael** [comment]
Yes, that's another one that I'd already identified on my private branch. Here's part of the commit summary:
- SanumaMEAT was SanumaDecorativeMeat
- Wolf1301Fesh was WolfFesh
- CD75CatCoffee was CD-75KittenBrandCoffee
- AerialEdenApple was EdenApplesOfAerial
- UzumokuLowGWings was UzumokuLow-GWings
