### ISSUE TITLE
Couple of minor issues

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#1910]
## EDDI version in which issue is found
v3.7.0
## VoiceAttack version in which issue is found (as applicable)
1.8.5

## Steps to reproduce
1. Buy new ship
2. Execute cargo report cottle script

## Expected
Report of cargo space

## Observed
Report of exception thrown
## Investigation

- #1

Log Entry;
_2020-07-24T20:32:54 [Warning] ScriptResolver:resolveFromValue Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiDataDefinitions.Ship.get_size()
   --- End of inner exception stack trace ---_

Problem clears on reload of the game. 

- #2

Also, found a missing EDName:
_2020-07-23T16:32:43 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name SensorMiscFastScan in resource EddiDataDefinitions.Properties.Modifications_

**Comment by Tkael** [comment]
I believe the first will be resolved for the next release by [`7f740d1` (#1905)](https://github.com/EDCD/EDDI/pull/1905/commits/7f740d19d949a99496f8252c3e76036ed4e886af).

**Comment by Tkael** [comment]
Pushed a very minor edit to correct item 2 as well.
