### ISSUE TITLE
Introduce event for planetary material record

### ISSUE THREAD

**Issue by Javelias** [EDCD/EDDI#1916]
## EDDI version in which issue is found
3.7.0

## Expected
When a new record is found, EDDI notifies you broke the current record.

For example, let's say you find a planet with a Polonium percentage higher then the current record of 2.093%. Currently EDDI will treat this as a great percentage event, so any finding at 1.3% or higher will result in the same audio feedback. Instead, we'd like EDDI to treat this record as a separate event, giving it a specific message.

## Investigation
EDSM does not keep records for material distributions, so static values will have to be kept and maintained. Possible configurable from scripts?

**Comment by Tkael** [comment]
Going to close this as not currently practical without an API endpoint for this information.
