### ISSUE TITLE
Add flag to undocked event to indicate if player is controlling ship

### ISSUE THREAD

**Issue by ghost** [EDCD/EDDI#1920]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.6 Steam

## Steps to reproduce
1. undock from a station to trigger ((EDDI undocked))
2. {BOOL:EDDI undocked playercontrolled} is not available to test if the player is controlling the ship or the docking computer is

**Comment by Tkael** [comment]
The player journal does not provide any direct information about whether the docking computer is being used. That said, is a music event generated when the docking computer activates and deactivates? Music could potentially be used to infer that a docking computer is in use.

**Comment by ghost** [comment]
Well the music event was the answer, ended up with this
```
Begin Text Compare : [{TXT:EDDI music musictrack}] Does Not Equal 'DockingComputer'
    Execute command, '[deploy;retract;]landing gear'
    Pause 2 seconds
    Say, 'Oi, this ship requires input, so when you're ready commander?'
End Condition
```
in case anyone else finds it useful.
