### ISSUE TITLE
Humanize() is too verbose and not used everywhere throughout the default personality

### ISSUE THREAD

**Issue by intelfx** [EDCD/EDDI#1927]
## EDDI version in which issue is found
I have observed this since 3.3.0 or even earlier.

## VoiceAttack version in which issue is found (as applicable)
N/A 

## Steps to reproduce
- Perform any transaction with a value in range of hundreds thousands credits.
- Buy or sell a 8A prismatic shield.

## Expected
Expected the verbalization of the transaction value to have a reasonable length.

## Observed
- Sometimes, the verbalization of the value is not shortened enough, resulting in verbally cluttered utterances like "well over seven hundreds sixty four thousands".
- Sometimes (specifically, the module buy/sell events) the total value is not preprocessed at all, resulting in utterances like ""you have just sold a 8A prismatic shield for a total of eight hundreds seventy four millions six hundreds twenty two thousands one hundred and sixty seven credits".

## Investigation
Expect a PR fixing both issues.

**Comment by Tkael** [comment]
Companion PR was resolved.

**Comment by Tkael** [comment]
Re-opened at OP author's request.
