### ISSUE TITLE
Faction names in all caps wrongly processed via P()

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1938]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
Jump to system `Kamuy` with the default personality.

## Expected
Faction "ORIGAMI AEROSPACE INDUSTRIES" to be pronounced as such.

## Observed
Faction name was pronounced via `Spacialize()`. Extract from speechresponder.out:

> Telemetry obtained. Momentary Discrepancy is heading to the Kamuy system. You are no longer in Federation space. This is your first visit to this system. Kamuy is an independent Corporate with a population of nearly 21 million souls, and is aligned to Yuri Grom. O R I G A M I A E R O S P A C E I N D U S T R I E S is the local faction. There is one orbital station and a single planetary station in this system.
1 jump to go. Fuel levels now at 92 percent capacity.  Information:  The New LP 862-184 Progressive Party faction is recovering after winning an Election with the Kamuy Independents faction for control of Pavlou Arsenal. The Corycia Crimson Allied Corp. faction will soon be tied in an Election with the Kamuy Crimson Dynamic Systems faction for control of Low Bastion.  The O R I G A M I A E R O S P A C E I N D U S T R I E S is undergoing a boom

## Investigation
This one might be tricky to implement.

**Comment by Darkcyde13** [comment]
I could swear I had reported this last year, but I can't find any mention in past issues.  Maybe I'd mentioned it on the forums?  I don't remember. :/

I made an effort to fix it myself with the following code:
```
{_ Setup capitalisation function _}
{set capitalise(string) to:
    {set string to split(string, " ")}
    {set cur to 0}
    {for word in string:
        {if ord(slice(word, 1, 1)) < 91:
            {set word to lcase(word)}
            {set string to union(string, [cur:token(word, slice(word, 1, 2), 0, char(ord(word) - 32))])}
        }
        {set cur to cur + 1}
    }
    {set string to join(string, " ")}
    {return(string)}
}
```
It converts any fully capitals string supplied into a capitalised version.  So "CAPITALISED WORDS" becomes "Capitalised Words". 
 I know it's not perfect, but it works, and I've been using this for ages for a few scripts in my personality.  I know you'll want to get EDDI to do it natively, rather than like this though. ;)  If you want to see where I use it, you can just check my latest personality download (dated 01-01-20), as it's listed in my change log. :)

**Comment by richardbuckle** [comment]
Thanks @Darkcyde13, that's a lead. Maybe the presence of a space in the faction name should stop the name from being spelled out (I've long been of the view that the function should be called `SpellOut()` rather than `Spacialise()`).

**Comment by Tkael** [comment]
It's not the `{Spacialise()}` function, at least not directly. It's the `{P()}` function (ref. System report script line 36). "ORIGAMI AEROSPACE INDUSTRIES" must be tripping the regex we use for a different type of object.

**Comment by Tkael** [comment]
As you noted, that may make it a bit tricky to resolve without impacting other strings where `{P()}` is used.

**Comment by Tkael** [comment]
It's tripping the `STARSYSTEM` phonetics, and the regex it's tripping on is simply one to replace all uppercase strings with spacialized strings in a star system name: 
https://github.com/EDCD/EDDI/blob/a3aecf81574b72581651020aacacda526d7d53d5/SpeechService/Translations.cs#L528-L529

If we cause it not to trigger when a name contains a space, it will cease to trigger for any star system names which are all caps and contain spaces.

What we need is a better method for identifying whether the string is a star system name (whether custom named or auto generated) or not so that we can process accordingly.

**Comment by Tkael** [comment]
Possible solution: Revise the `{P()}` method to accept a hint string as an optional second argument. The hint string would be one of: 
- power
- stellarclass
- planettype
- shipmodel
- shipmanufacturer
- body
- starsystem
- station
- faction

If a valid hint string is provided, that would be used to restrict the algorithm to fixing that expected type of string only.

For the `System report` script, the usage would be:
```
    {P(reportsystem.faction, "faction")} is the {OneOf("controlling", "local", "immediate")} {OneOf("power", "faction")}.
```

**Comment by GioVAX** [comment]
Disclaimer: I am assuming that Spacialize() will spell words that are all
capitals. If this assumption is incorrect, you can stop reading now  :D

If we know that the string are passing to P() should never be spelled,
could we just convert it to lower case before the call?
Eg. the above usage would become:
    { P(lowercase(reportsystem.faction)) is the... }

That also assumes that faction names should NEVER be spelled...

**Comment by Tkael** [comment]
Yes, that's also a viable solution (though it might not be a solution that will appear clear to the next person to edit the script).

**Comment by richardbuckle** [comment]
I'm a bit nervous about makimg too many assumptions about how faction names should be read out, especially in the context of non-English TTS voices.

A useful resource for sampling faction names is [Elite BGDS](https://elitebgs.app/faction).
I see:

- ACME Interstellar
- LTT 4487 Industry
- LTT 9810 Citizens' Forum
- Nanomam Ltd
- YZ Ceti Blue Galactic & Co

**Comment by Tkael** [comment]
It's probably worth remembering that neither the current nor the proposed solutions is going to be perfect. The current implementation applies rules for both star systems and faction names but if the string is transformed by the star system rules then processing with the faction rules is skipped. If we force the translation to use the faction rules, on the other hand, then we don't currently have anything that would identify, extract, and process any embedded star system names in the string. 

We could add some dependencies to link to the DataProviderService and use that to check if a known star system name is embedded in the string, but that approach would certainly hurt performance and I'm not sure the trade off would be worthwhile.

**Comment by Tkael** [comment]
My proposal would allow users to apply a much more restricted rule set from the {P()} function (and the rule set for faction names is very short simply because we cannot make many assumptions).

**Comment by GioVAX** [comment]
All things considered, I like Tkael's proposal: it is an improvement on the current situation and minimizes risks.

Are we going to also leave the existing P() without the specialization qualifier for general cases and backwards compatibility?

**Comment by Tkael** [comment]
My intent was to do so, yes.

**Comment by Tkael** [comment]
Pending #2025.
