### ISSUE TITLE
Requested Features: AutoStart, Minimize to System Tray

### ISSUE THREAD

**Issue by topper4125** [EDCD/EDDI#1940]
## EDDI version in which issue is found
3.7.7

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
Checked to see if these were options, didn't see them.

## Expected
to see them, and activate them

## Observed
Couldn't find these options, or they don't exist

## Investigation
Couldn't find anywhere to place a suggestion to add these options to the app, so I hope this is an appropriate place to make a suggestion that this app adds options for minimize to system tray and autostart on computer boot.

**Comment by Tkael** [comment]
Thanks for the feedback. Starting minimized and closing to the system tray are both items we've considered previously (ref. #231 and #1258). 

Minimizing to system tray isn't in line with Microsoft's guidance on the use of the system tray and we have chosen to respect that guidance. Furthermore, while EDDI does not have an option to start minimized by default it will remember the prior condition when it starts back up (so if it was closed minimized, it'll open minimized too).

If you'd like to launch EDDI when your system starts you can create a shortcut and drop it into your Windows `Startup` folder. Tips on how to find that folder are [here](https://helpdeskgeek.com/windows-10/how-to-access-the-windows-10-startup-folder/).

**Comment by topper4125** [comment]
Wow, didn't know about the Microsoft guidance for the system tray, that's... different, but I can respect the decision to follow it.

Thanks for the reply, I'll add it manually to my system startup
