### ISSUE TITLE
Mission monitor remaining time column needs leading zeros to sort nicely

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1942]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Take on some missions with duration < 10 hours and some with > 10 hours.
2. Sort the mission monitor by the "Remaining" column.

## Expected
Missions to be sorted in ascending/descending value of time remaining.

## Observed
The times with < 10 hours sort at the end. (screenshot to follow).

## Investigation
Formatting the timespan with leading zeros would solve this completely.
It many also be beneficial to make use of `TimeSpan`'s built-in formatting capabilities rather than rolling our own.

**Comment by richardbuckle** [comment]
![image](https://user-images.githubusercontent.com/227024/90964170-170b0380-e4b6-11ea-884d-d23ef4403f23.png)

**Comment by richardbuckle** [comment]
For reference, I tested how travel distances are displayed in-game in all six languages supported in-game.

- Over a year is shown as variations on `> 1 year` in each (`> 1 [local abbr for years]`). (In Russian, "> 1 года" ("goda"), which genitive singular of "год", "year".)
- Less than a year but over a day is shown as `12.3 d` in English, `12,3 j` in Spanish, `12,3 дн` in Russian, in general `[locally formatted decimal] [local abbrev for days]`.
- Less than one day is universally shown as `[hh:]mm:ss` in all languages including Russian.

I also tested [C#/.NET's formatting of `TimeSpan` structs with different locales](https://docs.microsoft.com/en-us/dotnet/api/system.timespan.tostring?view=netframework-4.8#System_TimeSpan_ToString_System_String_System_IFormatProvider_). These all boiled down to variations on `[-]d.hh:mm:ss.ff` for all cultures including Russian. Note that no culture-specific abbreviations for days, hours, minutes etc are used.

Recommendations:

1. Look into sorting the column by `TimeSpan.TotalMinutes` or the misson completion `DateTime` instead of the text representation. This solves the main issue right away.
1. There are multi-day missions, such as long-range passenger, and it is not reasonable to expect users to divide by 24 in their heads, so we do need to keep the "days hours:minutes" format.
1. The default hard-coded "D" for days etc isn't localized.
1. That said, I'd be happy to go with the default `TimeSpan.ToString()` format with the seconds elided. The [format code](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings) for this would be `(@"dd\.hh\:mm)`.

**Comment by Tkael** [comment]
The approach looks reasonable. I believe the time separator (usually `:`) can vary with the culture too though. 

I recently saw this with PR #1925. 😉

**Comment by richardbuckle** [comment]
Duly noted. We can read that from the locale. I'd prefer that to putting a format spec string in the localisable resources as (a) it is unreasonable to expect tranlators to learn the notation and (b) it is generally a major security risk to accept format strings from untrusted sources.

**Comment by Tkael** [comment]
It is possible to access the culture-specific separator via the DateTimeFormatInfo in the CultureInfo class if needed. 

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.timeseparator?view=netframework-4.8

**Comment by richardbuckle** [comment]
I think the most important thing is to sort the column correctly, as that is a real-world use case ("which mission do I need to do next?").

We can then refine the display further.

**Comment by Tkael** [comment]
Certainly. The only reason I called attention to the separator is recent  experience. Deviating from `:` is very rare.

**Comment by richardbuckle** [comment]
To be honest the view should be binding to the `TimeSpan` property itself, not any formatted version thereof, and the formatter should be specified in the XAML.

**Comment by Tkael** [comment]
Yes, that seems eminently appropriate to me. How the data is presented should be the domain of the view.
