### ISSUE TITLE
Error with limpet check script.

### ISSUE THREAD

**Issue by RuneDemomn** [EDCD/EDDI#1948]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Click "test" on limpet check script.

## Expected
Just started using EDDI for the first time so I'm not sure what's supposed to happen.

## Observed
"Error with limpet check script. Exception has been thrown by the target of an invocation."

## Investigation
Fresh install.

**Comment by Tkael** [comment]
Same as #1949.

**Comment by Tkael** [comment]
Closing as a duplicate.
