### ISSUE TITLE
Error with damage check script. I've got a lot of these same errors with multiple scripts so this will be my last report.

### ISSUE THREAD

**Issue by RuneDemomn** [EDCD/EDDI#1949]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Click "test" on damage check script.

## Expected
Just started using EDDI for the first time so I'm not sure what's supposed to happen.

## Observed
"Error with damage check script. Exception has been thrown by the target of an invocation."

## Investigation
Fresh install.

**Comment by Tkael** [comment]
Noted. We've got some speculative fixes in place to try to improve this for the next release but we've also been unable to replicate the issue locally. 

If you restart the game and log back in, does the issue persist?

**Comment by Tkael** [comment]
@GioVAX was able to help me to replicate the issue with a new installation of EDDI v3.7.0 with no config files, running the `Body scanned` event. I was able to confirm that the fixes we've already put in place will prevent this issue in the future. Furthermore, restarting EDDI should resolve the issue on your local install. o7

**Comment by Tkael** [comment]
Closing as already resolved for the next release.
