### ISSUE TITLE
Annoying extraneous "the" in `System state report`

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1951]
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Jump to a system with nothing special going on.
2. Listen to the report.

## Observed
Spoken:
> Information:   **The** Djendelis Federal Network is undergoing a boom and **The** Sagittarius Eye is gearing up to expand to another system
(my emphasis)

## Expected
No "The" before any faction name. A "the" before "Sagittarius Eye" is especially annoying.

## Investigation
Appears to be due to `System state report` line 95 but needs a fuller diagnosis.

**Comment by Tkael** [comment]
Yes, line 95 appears to be correct. 
I think this was from my last major rewrite of the script, where we added conflict summaries. 
If I remember right, adding "The" was a deliberate choice to identify what followed as a proper noun. I feel like some factions need it while others don't. Most are not hindered by it. 

Examples of factions which (imo) likely benefit from "The":
- 48 Turtles
- 10th Fleet
- 13th Legion
- Andromeda Corporation
- Angels of Death
- Browncoats
- Children of Raxxla
- DaVinci Corp.
- Edge Fraternity
- etc.

Strongly hindered factions:
- Any faction with a name which already begins with "The"
- Sagittarius Eye
- others?

If we elect to remove "The", let's also consider changing "is" to "are", e.g. 
> Information:  ~~The~~ Djendelis Federal Network ~~is~~ are undergoing a boom and ~~The~~ Sagittarius Eye ~~is~~ are gearing up to expand to another system
> Information:  ~~The~~ 48 Turtles ~~is~~ are undergoing a boom and ~~The~~ 10th Fleet ~~is~~ are gearing up to expand to another system
> Information:  ~~The~~ 13th Legion ~~is~~ are undergoing a boom and ~~The~~ Andromeda Coporation ~~is~~ are gearing up to expand to another system
> Information:  ~~The~~ Angels of Death ~~is~~ are undergoing a boom and ~~The~~ Browncoats ~~is~~ are gearing up to expand to another system

**Comment by richardbuckle** [comment]
Bit of a minefield, isn't it? Also, there are some sentence fragments in the script that will need to keep "the".

Concerning singular vs plural for corporations, with my proof-reader's hat on, it's considered a matter of style. You follow the house style guide if there is one, otherwise do what seems most natural and try to be consistent. In the context of text-to-speech I'd say go with plural throughout as many faction names are explicitly plural and it also fits those that aren't. That means changing pronouns to they/them/their as well (e.g. line 126).

**Comment by richardbuckle** [comment]
Fun fact: in Russian there are no definite or indefinite articles and the present tense of "to be" is almost always dropped in favour of an em-dash. I'm a little envious.

**Comment by Tkael** [comment]
Indeed. "Sagittarius Eye" is a bit of an odd case too. If I use a plural there there I just here "Sagittarius I R gearing up...".
What if, rather than removing "The" (except perhaps in cases where a faction name includes "The"), we added the word "faction"? e.g. 
>Information: The Djendelis Federal Network **faction** is undergoing a boom and The Sagittarius Eye **faction** is gearing up to expand to another system

**Comment by richardbuckle** [comment]
I'd submit that they are many cases like "Sagittarius Eye". "Aisling's Angels" comes to mind and <https://eddb.io/faction> lists them all.

To me, what you heard is "Sagittarius Eye are gearing up" -- is that so bad?

**Comment by Tkael** [comment]
The grammar feels more jarring when you hear "Sagittarius I R". ;-)
I still think that the best way to handle this is to be very clear that we're describing a proper name. Either `The Sagittarius Eye faction` or `The faction Sagittarius Eye` (with perhaps some added emphasis on the proper name).

**Comment by richardbuckle** [comment]
I dunno, maybe it's because I'm on their team and that makes a plural sit better with me, but "Sagittarius Eye are doing XYZ" sounds OK to me.

I can see your concerns, and I'm keeping in mind that we have different preferences about concision. Let me reflect on this.

**Comment by richardbuckle** [comment]
Let's also keep in mind that we can't get a one-size-fits-all here and we're going to have to compromise. And if a player is particularly irked, they can edit or disable the particular script

**Comment by eavdmeer** [comment]
One case that might deserve special attention is where the faction already has 'the' in the name. Like 'the Fatherhood'. Hearing: 'The the fatherhood....' is definitely a bummer.
