### ISSUE TITLE
EDDI Opens With Four Tabs Only

### ISSUE THREAD

**Issue by incryptx** [EDCD/EDDI#1956]
3.7.0

I built a new system with a AMD Ryzen 9 3900x and a MPG-570X Gaming board. Reinstalled everything from scratch. EDDI opens now with four tabs and after an uninstall/reinstall, this will not solve the issue.

Any ideas?

**Comment by incryptx** [comment]
Closing. Deleted Appdata. Restored

**Comment by Tkael** [comment]
Usually, this would be caused by a bad config file which causes the monitors and responders to not load. Glad you were able to sort it out.
