### ISSUE TITLE
Mission Complete details not passed to INARA upon Exiting Elite Dangerous

### ISSUE THREAD

**Issue by ITZAP** [EDCD/EDDI#1965]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.0-rc1
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
1.8.6
## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

(1) Launch Voice Attack with EDDI profile activated.
(2) Launch Elite Dangerous.
(3) Accept a Mission, complete the mission and select a reward.
(4) Exit to the Elite Dangerous Main Menu, then Quit to Desktop. Or just Quit to Desktop; it does not matter.
(5) Close Elite Dangerous Launcher and Exit Voice Attack.

## Expected
[Describe what you expected to happen]

Visit the Inara Mission Log webpage [https://inara.cz/cmdr-missionlog/](url) and check to confirm that your most recent mission state is listed as "**COMPLETED**"

## Observed
[Describe what happened instead]

The Inara Mission Log lists your most recent mission state as "**EXPIRES in ..**."
The EDDI Inara Plugin failed to update the Mission State upon exiting Elite Dangerous.

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

Upon opening EDDI alone and checking the "Mission Monitor" tab, there are **no missions** listed as outstanding, perfectly correct.

If I instead use the "Elite: Dangerous Market Connector" (EDMC) [https://github.com/EDCD/EDMarketConnector](url), I find that this always updates the Inara Mission State upon exiting Elite Dangerous.

EDDI log file attached:
[eddi.log](https://github.com/EDCD/EDDI/files/5265641/eddi.log)

**Comment by Tkael** [comment]
Hmm... we send to Inara periodically while EDDI is active (Inara's dev has asked that we send data in batches and don't spam the server). It does look like we might be able to do more to ensure that the queue is flushed and everything gets sent before we close.

**Comment by ITZAP** [comment]
This issue still exists in EDDI v3.7.1
Reproduce by doing ROBIGO to SOTHIS Passenger Missions.
Upon returning to ROBIGO, EDDI announces "You have 1 completed mission" when in fact you have "4 completed missions".
Hand in all 4 Passenger Missions and exit Elite Dangerous.
Check Inara to discover 1 Mission marked "Completed", but 3 Missions marked "ACCEPTED" and "EXPIRES IN ..."

The workaround is to switch OFF the Inara Plugin in EDDI.
Then run "ED Market Connector" instead, which works flawlessly no matter what.

**Comment by Tkael** [comment]
Confirmed. The thread is (usually) being killed before it completes. Working on it.
