### ISSUE TITLE
no 'name' in Rating object {cmdr.empirerating} 

### ISSUE THREAD

**Issue by Fingolfin74** [EDCD/EDDI#1966]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
no VA

## Steps to reproduce
{cmdr.empirerating.rank} delivers the correct rank number (e. g. '6')
Both {cmdr.empirerating.name} and {cmdr.empirerating.femininename} deliver nothing 
Even {EmpireRatingDetails('Lord').name} delivers nothing

{cmdr.federationrating.name} works complete fine, delivering the federation title

## Expected
{cmdr.empirerating.name} should deliver the correct title name (e. g. "Lord" for rank 6)

**Comment by Tkael** [comment]
Agreed, there's a mismatch between the actual object and the documentation for that object. We'll work on that. In the meantime, It looks like you can currently access the names with:
```
{cmdr.empirerating.maleRank.name} or
{cmdr.empirerating.femaleRank.name}
```
