### ISSUE TITLE
Getting lots of script errors read out by EDDI during multiple game events

### ISSUE THREAD

**Issue by sosborn4** [EDCD/EDDI#1967]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.0
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]
v1.8.6  (not running as plugin)
## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
I'm getting lots of script errors.  Here is just one example:
In Elite, enter FSS and scan a new body

## Expected
[Describe what you expected to happen]
Not get script errors

## Observed
[Describe what happened instead]
Get script errors read out by EDDI such as:
"Error with body scan script. Exception has been thrown by the target of an invocation"

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
See logs.

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]
I'm guessing I have a config issue.  Have tried re-installing EDDI.  Downgrading to previous release fixed it but now that version won't run so have gone back to 3.7.0.
[eddi.log](https://github.com/EDCD/EDDI/files/5306627/eddi.log)

**Comment by Tkael** [comment]
Should already be fixed in the next release. In the meantime, if you restart EDDI without touching your config then I think it should stop.

**Comment by sosborn4** [comment]
Hi Brian,

Restarting worked.  Thank you very much.  And thanks for EDDI - its a 
great tool.

I don't really understand why restarting EDDI fixed my problems this 
time, when I must have restarted it lots of times between gaming 
sessions and that didn't seem to make a difference.

Kind Regards,
Steve.


------ Original Message ------

**Comment by Tkael** [comment]
There's a problem with an object where when it is initially created and placed in memory a property is left undefined. When the same object is reconstructed from the config file the property is fully defined.
