### ISSUE TITLE
Powerplay trigger

### ISSUE THREAD

**Issue by CmdrFelaKuti** [EDCD/EDDI#1968]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
Not running VoiceAttack

## Steps to reproduce
1. I start de game, and need to wait until the ``powerplay`` script starts to run

## Expected

Sorry for my baaaaaaaad English :(((

I wish there was any way to trigger it mor frequently, like every time I start the game? Or when I send a `doking request` ?
I want to use it to monitore my rank and merits so it would be really useful, but then is not because some times I am playing for 2h and have no information about it.

## Observed
Sometimes it plays, some times doesn't, never as often as I want

## Investigation
No investigations

**Comment by Darkcyde13** [comment]
If you wish to trigger that script when you start your game, you can add the following line to the 'Commander Continued' event script:
`{F("Powerplay")}`

If you want to hear it when you dock, just add the line to the 'Docked' event script.

To add that line to either of the scripts, you will first need to make a copy of the default EDDI personality (if you have not done so already) as you can't edit the default.  On the Speech Responder tab in EDDI, click Copy Personality at the bottom and give it a new name, then click OK.  You will then be able to edit those scripts in your new copy.

Hope that helps! :)

**Comment by Tkael** [comment]
`{F("Powerplay")}` is not recommended as it won't be backed by an event and consequently event variables won't be filled. 

The best way to ensure the data reported in the event is accurate is to trigger the event as soon as powerplay data is written to the player journal (which is what we do). 

Based on my personal observations, the current event should be getting written just after logging into the game (just after the `Location` script). It also should be written periodically as you play (typically I've seen this after a change in FSD state, such as after a jump or when transitioning from supercruise to normal space).

**Comment by CmdrFelaKuti** [comment]
So Tkael, I am not getting this after FSD state changes, actually I was playing yesterday for 4 ours and just got juts once, after 1h30 gameplay.

Do you think there is any way to trigger it every time I request dock permit (or any other trigger)?

**Comment by Tkael** [comment]
The journal event comes from FDev and they control when it gets written. I don't know exactly what triggers a write. The journal manual indicates that it is intended to be written once at startup and then not repeat but I've seen that it can actually repeat multiple times in a play session.

EDDI does not currently try to track powerplay state between `Powerplay` events. This could be possible but may or may not be accurate (depending on how often it can sync and whether a `Powerplay` event is actually being written each time a play session starts like it should). Until now, we've prefered to work from the known good state when we get an `Powerplay` event.

**Comment by Tkael** [comment]
Closing as not currently feasible. The data isn't available from the Frontier API or from any source other than the current intermittent event (where we are already responding to it).

At minimum, the event **should** be triggering each time you load into the game while pledged to a power (per the journal documentation):
```
3.10	Powerplay
When written: at startup, if player has pledged to a power
Parameters:
•	Power: name
•	Rank
•	Merits
•	Votes
•	TimePledged (time in seconds)

Example:
{ "timestamp":"2018-01-31T10:53:04Z", "event":"Powerplay", "Power":"Edmund Mahon", "Rank":0, "Merits":10, "Votes":0, "TimePledged":433024 }
```
