### ISSUE TITLE
Bodies to Map function stopped working

### ISSUE THREAD

**Issue by Akquar** [EDCD/EDDI#1970]
Hi, thx for great addon, makes a huge difference in my enjoyment of the game.

I have ver 3.7.0. installed.  All functions work as normal, but the Bodies to map function never triggers anymore.  
I have made sure to go to systems I have not mapped yet, I get star an some planet trivia, but never the scan candidate message.
I can't find any information about other player with similar issue, any advice would be appreciated, it was one of the most useful features for me.

**Comment by Tkael** [comment]
Please check the role assigned to your current ship in the ship monitor. The script should trigger as long as the ship's role is set to either "Multipurpose" or "Exploration". 

If you are triggering the Bodies to map script with the `Discovery scan` rather than via the `System scan complete` event, please also note that the default script suppresses mapping recommendations in populated systems.

**Comment by Akquar** [comment]
Thank you very much for the fast response. I always do Discovery Scan on entering system. I tested and I believe it is due to the suppression in populated systems. Is this something I can change in the setup?
Sorry if I am doing something stupid, still new to the game.

**Comment by Tkael** [comment]
Sure. The suppression only occurs in the ship role is "Multipurpose". Nothing should be suppressed if the ship role is "Exploration" so your first option is to change the ship's role to "Exploration". Your second option if you'd like to always have the recommendations while in your multipurpose ship, would be to edit the `Discovery scan` script, lines 10-11, from:
```
    {if ship.Role.edname = "Exploration" || 
        (ship.Role.edname = "Multipurpose" && len(reportSystem.factions) = 0):
```
to:
```
    {if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":
```

**Comment by Akquar** [comment]
Brilliant, thanks so much for taking the time to respond.
I will change the role to Exploration, I am sure that will solve it.
