### ISSUE TITLE
NullPointerError exceptions when calling EddiDataDefinitions.Ship.get_size()

### ISSUE THREAD

**Issue by SkoZombie** [EDCD/EDDI#1971]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
Not installed

## Steps to reproduce
1. Clean install lasted build
2. Fly around triggering different events (eg, fuel check, discovery scan, star scan)
3. Hear the error message repeated every time (Error running script X, Exception has been thrown by the target of an invocation)

## Expected
Scripts to work , or not constantly say the same error over and over.

## Observed
Errors with many scripts, given they the same error I figure they might be related

## Investigation
Looked at the logs and saw lots of NullPointer exceptions when calling EddiDataDefinitions.Ship.get_size()

[eddi_issue.zip](https://github.com/EDCD/EDDI/files/5345003/eddi_issue.zip)

**Comment by Tkael** [comment]
Thanks, it's a known issue that will be resolved in the next release. In the meantime, users have had good success with restarting EDDI after this occurs.

**Comment by SkoZombie** [comment]
@Tkael Ah ok cool. I'll try restarting and wait for the next version! Thanks! I'm loving the tool!
