### ISSUE TITLE
Is there a js version of the game? And are there any source files ?

### ISSUE THREAD

**Issue by zababurinsv** [EDCD/EDDI#1974]
Is there a js version of the game? And are there any source files ?

**Comment by Tkael** [comment]
I don't understand the question. This repository contains files written in C# and the application we develop is not a game (though it is designed to integrate with a game). The source files are in this repository.

**Comment by zababurinsv** [comment]
Where can I find the source files for the game?

**Comment by Tkael** [comment]
Elite Dangerous is a commercial product (https://www.elitedangerous.com/). Source files are not available.

**Comment by zababurinsv** [comment]
Thanks. This is what I wanted to hear.
