### ISSUE TITLE
Mission accepted speech responder always reports zero missions

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#1975]
## EDDI version in which issue is found
v3.7.0 (and before)
## VoiceAttack version in which issue is found (as applicable)
1.8.7 (not limited to that version)
## Steps to reproduce
Accept a mission from the mission board.

## Expected
I expect the voice responder to read out: "You have 1 mission, that is your 1st mission."

## Observed
The readout is: "You have 0 mission, that is your 0th mission."

## Investigation
If I add an `&& missionsCount != 0` to the if condition, the wrong readout does not take place. So looks like the missionsCount is always zero and stays zero.

**Comment by Tkael** [comment]
`missionsCount` is set by the Mission Monitor. If you navigate to the Mission Monitor tab, is the plugin disabled?

Are missions are being written to your configuration files? Please accept a couple of missions then review the file located at %APPDATA%/EDDI/missionmonitor.json to determine whether missions are being recorded appropriately.

There are .log files located in the same folder that you can send us if missions aren't being logged appropriately.

**Comment by eavdmeer** [comment]
I can confirm that the mission monitor plugin was not enabled. It would still make sense to add the zero check to the speech responder for the people who have it disabled

**Comment by Tkael** [comment]
Excellent. Glad we were able to figure it out and yes I agree that we can tweak the script for this.

**Comment by eavdmeer** [comment]
Thanks

**Comment by Tkael** [comment]
Re-opening so that we don't forget to update the script.
