### ISSUE TITLE
Possible mistake in timeout increment in JournalMonitor.cs

### ISSUE THREAD

**Issue by Darker** [EDCD/EDDI#1977]
## EDDI version in which issue is found
src rev 90c33930

I was looking through the source code and found this:

```
int timeout;
do
{
    await Task.Delay(1500);
    timeout = +1;
}
while (EDDI.Instance.CurrentStarSystem.bodies.Count == 0 && timeout < 3);
```

I am almost sure that the `timeout < 3` condition will never be satisfied. Is this a typo or deliberate?

**Comment by Tkael** [comment]
Good catch. Looks like `timeout = +1` ought to be `timeout++`.
