### ISSUE TITLE
throwing random errors in the middle of game session

### ISSUE THREAD

**Issue by DbrStudio** [EDCD/EDDI#1984]
## EDDI version in which issue is found
3.7.0

## VoiceAttack version in which issue is found (as applicable)
1.8.7 (Steam)

## Steps to reproduce
Happens randomly while just flying around, jumping, basically playing the game.

## Expected
EDDI should tell me my exact fuel reserves, if I have limpets, what system I'm jumping to and many other things.

## Observed
EDDI throwing errors left and right saying stuff like eg "Error in limpet check script, an error was thrown by something something" or "Warning, fuel reserves are at 0%, commander" even though fueltanks are completely full.

## Investigation
Restarting VoiceAttack and EDDI _sometimes_ fixes it, it can sometimes work perfectly fine for hours and then suddenly stop working all of a sudden.

**Comment by Tkael** [comment]
This sounds like a known issue (an exception had been thrown by the target of an invocation) but we can take a look at your logs to confirm. Logs are located at %appdata%/EDDI and use the .log extension. 

If it is what I think it is, a fix is already incorporated in the development version and will be included on the next release. In the meantime, the best mitigation is to restart EDDI if this occurs.

**Comment by Tkael** [comment]
Another user reported today that they had more success with exiting to Elite's main menu then loading back into the game.

**Comment by Tkael** [comment]
Believed fixed in version 3.7.1-b1, released earlier today and available from https://github.com/EDCD/EDDI/releases.

**Comment by aelfwyne** [comment]
I don't want to open a duplicate report, but I just had this exact same error message appear randomly in the same script on version v.3.7.1 as well. Search led me here. 

As above, a restart seemed to fix the issue.
