### ISSUE TITLE
Humanise() seems to have a bug

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2000]
## EDDI version in which issue is found
v3.7.1

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Try to Humanise() numbers that are between 1 and 999.  For example 456.

## Expected
EDDI says "four hundred and fifty six" or "just over four hundred and fifty" or "over four hundred and fifty".

## Observed
EDDI says "just over four hundred and fifty six".

## Investigation
I was just going over the latest script updates, amending my personality to match where necessary, and when I tried the Humanise() addition in 'Bond redeemed' I discovered this problem.

In my version, for the broker part, I use ceil() instead of round() (because in game the broker amount is always rounded up, even if it's only .1, so 200.1 becomes 201), and I wanted to check what it sounded like with Humanise().  So, I copied that line and pasted into a new script and changed the variables to fixed numbers.  After getting some strange results, I thought ceil() was causing a problem by rounding everything up, but after some tests with Humanise() by itself, I found that any number below 1000 and not ending in a zero, always says "just over" and the full number.  So, 199 becomes "just over one hundred and ninety nine", 211 becomes "just over two hundred and eleven".

With numbers as small as 999 or less (small in comparison to the many thousands you can get in game anyway), I would expect them to either be read out in full, or humanised properly, like numbers larger than 999 are.  When spoken, most of the time either full or humanised takes roughly the same amount of time to say.  Maybe just get Humanise() to say sub-1000 numbers in full?  Or if it's not too much trouble to program, make it random to say full or humanised?

**Comment by Tkael** [comment]
Confirmed.
{Humanise(456)} yields "Just over four hundred and fifty six"
{Humanise(1800000)} yields "One million"

**Comment by Darkcyde13** [comment]
Hmm, I didn't think of going that high.  Surely 1.8 million should really say "Nearly two million", rather than just "One million"?  Sorry if that's what you meant.

Edit:  I just tried {Humanise(1800001)} and it said "Well over one and a half million".  It seems odd that a single digit can make such a big difference in what is spoken.

**Comment by Tkael** [comment]
Agreed, it's an undesirable quirk in the algorithm.
