### ISSUE TITLE
Speech: there is a problem with the script signal detected at line 110 expected parentheses end found

### ISSUE THREAD

**Issue by FisuMAD** [EDCD/EDDI#2001]
## EDDI version in which issue is found
3.7.1

## VoiceAttack version in which issue is found (as applicable)
1.8.7

## Steps to reproduce
Its aleatory when reach a system. The start the with the speech "there is a problem with the script signal detected at line 110 expected parentheses end found", no messages in VA console. This is repeat like 100 times, need to kill VA and restart, the continue and in the next jump start again. 

## Expected
no sound

## Investigation
try lo put log in EDDI, but no find any log file to debugg o see.

**Comment by Tkael** [comment]
The default `Signal detected` script does not go to line 110. You must be using a customized script?

**Comment by FisuMAD** [comment]
Sure is something within VA custom profile. Just rollback and no problem, so, some thing is breaking with the update, need to investigate what happend with this profile, but i dont know how can debug.

**Comment by brushi** [comment]
Im having the same problem , any chance i can disable the error ? it repeats over and over.

**Comment by Tkael** [comment]
I can't diagnose a custom script or VoiceAttack profile that hasn't been shared with me. 

If your custom script is generating an error, you might consider resetting the script to match the default. 

You can also disable the Signal detected script entirely if you prefer.
