### ISSUE TITLE
Voice Attack actions for mission monitor

### ISSUE THREAD

**Issue by ghost** [EDCD/EDDI#2003]
## EDDI version in which issue is found
v3.7.1

## VoiceAttack version in which issue is found (as applicable)
v1.8.7-Steam

Are there any voice commands to trigger the mission monitor functionalities from Voice Attack? If you're using a VR headset it is cumbersome to remove VR headset to click two buttons, etc.

Specifically the buttons at the bottom:
- Get Route
- Next In Route
- Update Route
- Clear Route

They may already be included, but I cannot find those in the EDDI Voice Attack profile nor here in the wiki.

## Expected
Have Voice Attack be able to trigger the functionalities from the missions monitor.

**Comment by Tkael** [comment]
The default EDDI.vap does not currently include voice commands for this, but the plugin commands are documented [here](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#route).

**Comment by ghost** [comment]
Ok, very helpful. I've simply overlooked that part of the docs. Sorry.

**Comment by ghost** [comment]
Ok I read the complete Wiki page, but maybe I am too stupid ;-) Could you maybe so kind and give one example how to create the corresponding action in VoiceAttack?

1.) Example scenario to improve the documentation: "route route"
I looked up e.g. "open EDDI" and figured out, that the line "Execute external plugin" contains (doubleclick) the crucial "Plugin context" variable, which cannot be seen from the outside.
And on other occasions one has to `Set text [Script] to 'Body report'`.

As far as my understanding now goes this would lead to a new entry to calculate a RNNA route with this:
```
Set text [Type] to 'route'
Execute external plugin, 'EDDI 3.7.1' and wait for return
  - doubleclick on/Edit that line and set: Plugin context 'route'
```
and finally assign a voice command or similar that invokes that action. Is this correct?

2.) Simply documentation changes: `'Type variable'` - could we change that to `'Type' variable` (and similar), as the name is simply 'Type' not 'Type variable', right?

If I get that all correct and working I will try to send you a pull request with some additional information about the VoiceAttack plugin functionailty. 

Btw: Using the variables **from** EDDI within VoiceAttack is super easy and straightforward ;-) (I use that a lot for convenience functions like raising landing gear when lifting off from planet surfaces ;-))

**Comment by ghost** [comment]
Ok, it's 'Type variable', not 'Type'.
