### ISSUE TITLE
Voice Attack action for "Find legal facilities" (crime monitor)

### ISSUE THREAD

**Issue by ghost** [EDCD/EDDI#2004]
## EDDI version in which issue is found
v3.7.1

## VoiceAttack version in which issue is found (as applicable)
v1.8.7-Steam

Are there any voice commands to trigger the crime monitor functionalities from Voice Attack? If you're using a VR headset it is cumbersome to remove VR headset to click two buttons, etc.

Specifically the button at the bottom:
- Find Legal Facilities

They may already be included, but I cannot find those in the EDDI Voice Attack profile nor here in the wiki.

## Expected
Have Voice Attack be able to trigger the functionalities from the crime monitor.

**Comment by Tkael** [comment]
The default EDDI.vap does not include voice commands for this, but the plugin command is documented [here](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#route).

**Comment by ghost** [comment]
Same here, thanks for pointing that out :-)
