### ISSUE TITLE
Viper Mk III and similar mispronounced on ship transfer

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#2008]
## EDDI version in which issue is found
3.7.1

## VoiceAttack version in which issue is found (as applicable)
n/a

## Steps to reproduce
1. Ship a Viper Mk III somewhere close and wait for arrival
2. Listen to the output

## Expected
Ship model is referred to as "Viper mark three".

## Observed
Ship model is referred to as "Viper em kay three". 
speechresponder.out shows `Your Viper Mk. III has arrived.`

## Investigation
The phonetics are correctly set up in ShipDefinitions.cs.
Is it possible to use the ship name rather than model in this script?

**Comment by Tkael** [comment]
Pending / fix with #1608.
