### ISSUE TITLE
Not all installed Windows voices are available

### ISSUE THREAD

**Issue by Sonnenwerk** [EDCD/EDDI#2009]
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]
3.7.1
## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

There are David, Hazel, Hedda, Zira voices in the TTS, but missing non english ones, i installed..e.g. Michael, Mark

Installation of added voices has been after installation of Eddi. So maybe something to look into.

## Expected
[Describe what you expected to happen]

Seeing all installed voices 

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
EDDI uses the Windows Speech synthesizer. It is not compatible with voices that do not use the Windows Speech synthesizer (such as Microsoft Server or Microsoft Mobile voices).

**Comment by Tkael** [comment]
Doing further reading, it looks like many of the voices available via language packs are not SAPI voices but are instead WinRT voices. These are not compatible with the current speech synthesizer API we are using. It may be possible to add support for that speech synthesizer... worth thinking about though I'm not sure the namespace is natively available for .NET framework applications. <https://stackoverflow.com/questions/40406719/windows-10-tts-voices-not-showing-up>

**Comment by Tkael** [comment]
To open up additional Microsoft voices in EDDI, it looks like we would need to do the following (ref. https://blogs.windows.com/windowsdeveloper/2019/09/30/windows-10-winrt-api-packs-released/):
1. Configure the SpeechService project to use PackageReference.
2. Add the Microsoft.Windows.SDK.Contracts NuGet package to our project
3. Add [Windows.Media.SpeechSynthesis](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer) as an alternate speech synthesizer
4. Pipe the speech we want through the correct synth.

**Comment by Thormor** [comment]
If I may, this would be lovely as we could have Eva (Cortana). Even if you get it to show in the Voice list (like Microsoft David) only Zira seems to work (for wtv reason)
