### ISSUE TITLE
Remember and restore window size and pos

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#201]
## Steps to reproduce

1. Launch EDDI
2. Size and position the window how you like it.
3. Quit and relaunch EDDI.

## Expected
My preferred window size and pos is restored.

## Observed
Window size and pos reverts to default.

## Investigation
When implementing this be sure to test that the restored window will be onscreen (perhaps the user has disconnected a secondary monitor) and if not, revert to default size and pos.

**Comment by richardbuckle** [comment]
Preferably also remember which tab is selected.

**Comment by Tkael** [comment]
Closed pending approval of #299.
