### ISSUE TITLE
Review MVVM changes

### ISSUE THREAD

**Issue by JPVenson** [EDCD/EDDI#2010]
As previously discussed i'v created an example rewrite of an module with better MVVM structure in mind.

https://github.com/JPVenson/EDDI/tree/MvvmRewrite

@Tkael i'v also used the service pattern, as described in the material you got.

@1772

The Branch should only be seen as an Example and warning for the impact an rewrite would have.

**Comment by Tkael** [comment]
Thanks JP. It looks like we should focus on the changes which were made to the Speech Responder project? I see changes to other projects but for the most part those appear to be fairly inconsequential. 

Changes like converting from spaces to tabs clutter the diff and make comparison much more difficult, unfortunately.

**Comment by JPVenson** [comment]
Indeed. I choose the SpeechResponder module as I had made changes to it previously and its "closed" in itself so it was a good target for an quick rewrite. It also shows the kind of infrastructure i have in mind with the `IDialogService` used to control dialogs and the IoC Container.

I am sory the other changes where made by VS automatically and are not intended.

Beside the changes in the SpeechResponder module,
- I had to change app.xaml & app.xaml.cs
- I Added a new Module: Eddit.Common.WPF
- Added the IoC components to Utilities

**Comment by richardbuckle** [comment]
Simplest way to review is probably <https://github.com/JPVenson/EDDI/commit/ed551514511d090013d3c412b7d9868ff63b32db?w=1>

**Comment by Tkael** [comment]
Thank you for this, JP. We've evaluated it and discussed it internally and concluded that the significant increase in code complexity does not provide a sufficient benefit to either developers or users in our particular case. But thank you for taking an interest in our project. o7
