### ISSUE TITLE
[Warning] ScriptResolver:resolveFromValue Failed at line 110. 

### ISSUE THREAD

**Issue by Blastoro** [EDCD/EDDI#2011]
## EDDI version in which issue is found
[3.7.1]

## VoiceAttack version in which issue is found (as applicable)
[1.8.7-Steam]

## Steps to reproduce
1. [This happen when i am in the any stations] 
2. [when i arrive a system ]
2. [Also happen when i scanning a system]

## Expected
[ In the past, EDDI give information of the system (ej: Minerals in te rings) ]

## Observed
Log EDDI:
2020-11-25T02:01:35 [Info] EDDI:eventLocation Location StarSystem: Vega
2020-11-25T02:01:35[Warning] ScriptResolver:resolveFromValue Failed to resolve the script "Signal detected" at line 110. Cottle.Exceptions.ParseException: expected 'parenthesis end (')')', found ':'
   en Cottle.Parsers.DefaultParser.ParseValue()
   en Cottle.Parsers.DefaultParser.ParseExpression()
   en Cottle.Parsers.DefaultParser.ParseKeywordIf()
   en Cottle.Parsers.DefaultParser.<>c.<.cctor>b__21_6(DefaultParser p)
   en Cottle.Parsers.DefaultParser.ParseCommand()
   en Cottle.Parsers.DefaultParser.Parse(TextReader reader)
   en Cottle.Parsers.PostParser.Parse(TextReader reader)
   en Cottle.Documents.SimpleDocument..ctor(TextReader reader, ISetting setting)
   en EddiSpeechResponder.ScriptResolver.resolveFromValue(String script, BuiltinStore store, Boolean isTopLevelScript, Script scriptObject)

* **Extra information**
EDDI is configured in spanish

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Spanish? Yeah, that's the information that I was missing. I think I found it. Please update line 110 to:
`(spokenSources[event.source] = true && event.unique):`

This will be fixed in the next release.

**Comment by Blastoro** [comment]
Tanks @Tkael 
I will like test this change but I dont found the script to update the line 110. 
Which is te script?

**Comment by Tkael** [comment]
Signal detected
