### ISSUE TITLE
Add an `Ordinal()` function to render numbers like "lst", "2nd", etc.

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2019]
## EDDI version in which issue is found
3.7.1

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Review the `Mission accepted` script. 

## Expected
Mission count description is suitable for translation. 

## Observed
Mission count description is not suitable for translation and heavily expects English grammar. 

## Investigation
We could implement an `Ordinal()` function to have this rendered via the voice and speech synthesizer, see https://www.w3.org/TR/2005/NOTE-ssml-sayas-20050526/, ref. para. 3.6

**Comment by richardbuckle** [comment]
I just tested while the Microsoft voices support this, the Ivona ones do not.

**Comment by richardbuckle** [comment]
I can also forsee some issues with case and gender agreement.

**Comment by Tkael** [comment]
Odd, my MiniSpeech app with Ivona supports this. 

```
<say-as interpret-as="ordinal">1</say-as>
```
renders as "first".

If EDDI doesn't support it, it'll probably come down to the Ivona SSML version vs. the speech synthesizer (much like I suspect to be the case for Ivona IPA).

**Comment by richardbuckle** [comment]
It's increasingly looking like I have an out of date Ivona package.

**Comment by Tkael** [comment]
Maybe. But again, some things that render fine in MiniSpeech do not render correctly in EDDI which points me back to the synthesizer as a potential problem.

**Comment by Tkael** [comment]
Temporarily on hold pending approval of #2025.

**Comment by Tkael** [comment]
Closed as not currently viable. Ivona and Cereproc voices do not currently adequately support this implementation and return "one" when "first" is expected, "two" when "second" is expected, etc.
