### ISSUE TITLE
Document implicit VA variables

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#2026]
[`VoiceAttackPlugin.SpeechFromScript`](https://github.com/EDCD/EDDI/blob/develop/VoiceAttackResponder/VoiceAttackPlugin.cs#L830) does some transformations that are not documented in the Wiki, notably replacing `$=` with the phoentic ship name and `$-` with the commander name. Let's document these.

**Comment by Tkael** [comment]
I was aware of `$=` and  (to a lesser extent) `$-`, though I thought that they were documented. Honestly though, neither is particularly intuitive and clear. Furthermore, `$-` is used nowhere within the example profile and renders as "EDDI.Instance.Cmdr T'kael" - not exactly useful. I'm not sure why JGM set it up that way.

**Comment by richardbuckle** [comment]
I suspect jgm was inspired by similar variables in older languages like Bash script. I'd be all for documenting them as deprecated and getting rid of them.
