### ISSUE TITLE
Script 'Pause' function doesn't seem to work

### ISSUE THREAD

**Issue by aeterna426** [EDCD/EDDI#2029]
EDDI ver. 3.7.1

**Speech Responder** -> **FSD Engaged** _script_:

...
`{_ Wait for the FSD countdown and initial jump}`
`{Pause(5000)}`
...

**Pause** function doesn't seem to work. Looks like the specified waiting time is treated always like 0 (zero) (I tried different values, no luck).

**Comment by Tkael** [comment]
`{Pause()}` works for me. Mind taking a screenshot of your `Text-to-Speech` tab so that we can see your settings?
For example, `{Pause()}` is a function based on SSML speech tags and will not work if you've disabled phonetic speech.

**Comment by aeterna426** [comment]
Thanks for the answer. Yes, I had to disable phonetic speech. Otherwise EDDI keeps crashing in my environment. Don't know why. But without phonetic speech it seems to be stable. If `Pause` uses SSML and will not work without phonetic speech then I have to figure out how to pause the script in some other way. I need that. Any thoughts are welcome.

**Comment by Tkael** [comment]
There are some non-SSML options we might consider, but TBH problems that require disabling phonetic speech are quite rare and I'd like to look more deeply into that too. 

Would you mind enabling phonetic speech and verbose logging just long enough to trigger a crash? Once you've done so, you'll be able to retrieve the resulting log file from %appdata%\EDDI\eddi.log, zip it up, and attach it to this ticket.

**Comment by aeterna426** [comment]
Got it! It has something to do with the IVONA voice I use. When I change it to e.g. Microsoft Zira Desktop everything is just fine. it looks like using IVONA is making problems. My version of IVONA is 1.6. The crash is very easy to reproduce:
1. `Text-to-Speech` tab
2. Ship for testing the voice: `Cobra Mk. III` or any other ship containing period character ( `.` ) inside its name. Those without periods work fine.
3. Test voice
4. In this moment crash should occur with no visible information. EDDI is just closing.

I did as you asked. Created log file with verbose logging option enabled. It is in zip file attached to this ticket.
[eddi.log.zip](https://github.com/EDCD/EDDI/files/5625730/eddi.log.zip)

**Comment by Darkcyde13** [comment]
I too use Ivona, the British 'Amy' voice, version 1.6.70.  I went to the TTS tab, chose Cobra Mk. III and clicked both the 'Test voice' and 'Test voice (severe damage)' buttons, and both worked correctly.  While this may not help you directly, it does provide an additional data point for reference, should Tkael require one.

**Comment by Tkael** [comment]
Thanks. Hmm... it looks like you're running EDDI as a VoiceAttack plugin with Ivona Sally. I don't see any exceptions logged here, the log just ends. The actual crash may have occurred in VoiceAttack or the speech synthesizer but isn't recorded here. You might check VoiceAttackFault.txt in the VoiceAttack install directory and see what is recorded there.

I am seeing some odd formatting on the message being passed to the synthesizer.
Characters that ought not to be escaped are being escaped.
```
&lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;speak version=&quot;1.0&quot; xmlns="https://www.w3.org/2001/10/synthesis" xml:lang="en-US"&gt;This is how I will sound in your <phoneme alphabet="ipa" ph="ˈkəʊbrə">cobra</phoneme> <phoneme alphabet="ipa" ph="mɑːk">Mark</phoneme> <phoneme alphabet="ipa" ph="θriː">3</phoneme> .&lt;/speak&gt;
```
ought to look like
```
<?xml version="1.0" encoding="UTF-8"?><speak version="1.0" xmlns="https://www.w3.org/2001/10/synthesis" xml:lang="en-US">This is how I will sound in your <phoneme alphabet="ipa" ph="ˈkəʊbrə">cobra</phoneme> <phoneme alphabet="ipa" ph="mɑːk">Mark</phoneme> <phoneme alphabet="ipa" ph="θriː">3</phoneme> .</speak>
```

**Comment by Tkael** [comment]
Ok. I've ruled out the odd formatting, it's just an artifact from the way we pass the information to the logger (the output from Ivona Amy is exactly the same but no crash occurs).

Looks like VoiceAttackFault.txt from the main VoiceAttack directory is the next file we need to check out.

**Comment by aeterna426** [comment]
Thanks for your insight but... well... I don't use Voice Attack at all.

**Comment by aeterna426** [comment]
If Darkcyde13 says he doesn't have such problems with IVONA as me (his IVONA version looks the same as mine) then maybe it is just one-off case... I mean my case. Maybe I have something messed up in my system. Reinstalling IVONA Sally doesn't help for example. Of course I'm not willing to reinstall the whole Windows to find out, for obvious reasons :D. If you don't find a solution it would be more than enough for me if you could give me an idea how to pause script with another method, other than the Pause function.

**Comment by Tkael** [comment]
Huh. Yeah, it looks like the VoiceAttack Responder is disabled. Even though EDDI is installed in a VoiceAttack plugin directory?

That leaves me puzzled then. EDDI is designed to log issues that cause it to crash. When I see a log end like yours that just ends with no logged errors and no shutdown, the usual explanation is that some external process (like a VoiceAttack host process) choked. 

I'm trying to explore the options that are immediately available so that you don't have to wait for another release of EDDI to resolve your issue.

**Comment by aeterna426** [comment]
>> **_Even though EDDI is installed in a VoiceAttack plugin directory?_**

Looks that way. This is my installation path: `C:\Program Files (x86)\VoiceAttack\Apps\EDDI`

Also, If it helps, I tried to turn off other than Speech Responder EDDI functions (i.e. EDDN Responder, EDDB Monitor, Galnet, Inara, etc.), but unfortunately it makes no difference.

**Comment by aeterna426** [comment]
I don't know. I don't have Voice Attack but the path I gave above is the default installation path, isn't it? I don't remember I had possibility of changing it during EDDI installation.

**Comment by Tkael** [comment]
Hmm. Ok, so I just installed both EDDI and Ivona Salli (a trial version) in a Windows sandbox. No crash when tested as prescribed above. The installer did offer to install in the VoiceAttack directory though (I didn't remember that being the default directory but apparently it is). 

If my sandboxed version isn't crashing that may suggest suggest a problem with either your voice installation or your Windows speech synthesizer. You've already tried reinstalling the voice, so as a last ditch effort to try to resolve this without waiting for a new release or swapping to another voice you might try checking your Windows installation for errors (https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system).

**Comment by aeterna426** [comment]
I appreciate your efforts and I thank you for your patience. For now I think I can live with that. And if you just gave me any temporary solution on how to pause the script without `Pause` function I would be very grateful. :D

**Comment by aeterna426** [comment]
Ok. Maybe I'm stubborn but I satisfied your curiosity as best I could for the sake of your project. Could you just do the same for me? You said there are some non-SSML options you might consider when it comes to pause the script with nonstandard methods. What did you have in mind? Please?

**Comment by Tkael** [comment]
Unfortunately, aside from using a different voice I don't have any options that I can offer you that would give you any immediate relief. All of the options that I'd be looking at would require changing EDDI's source code and releasing a new version of the program.

**Comment by aeterna426** [comment]
Now I fully understand. I didn't want to be annoying. But it looks like I am ;D. All the best. Keep up the good work! Thank you.

**Comment by Tkael** [comment]
Sorry to disappoint. I'll definitely be looking into a source code change.

**Comment by Tkael** [comment]
Temporarily on hold pending approval of #2025.
