### ISSUE TITLE
Cannot deactivate limpet check script

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#203]
## Steps to reproduce
1. Get annoyed with the limpet check message on an explorer that will synthesize limpets at need
2. Create a new personality
3. Click the checkmark in front of limpet check

## Expected
Limpet check script is deactivated

## Observed
No changes happening, the only way I can deactivate the message is by changing the script or manually checking the cottle code for all other scripts until I find the call to this script

## Investigation
The problem happens with a number of what seem to be sub-scripts.

**Comment by Tkael** [comment]
This is a fairly common UI complaint. At the very least, it should be obvious to the user which scripts can be unchecked (those linked directly to events) those and which cannot (those which exist independent of events but may be called by event scripts).

**Comment by Tkael** [comment]
The WPF for this is a bit tricky. Essentially, I think we need to take this [line](https://github.com/EDCD/EDDI/blob/fef18dfc462cb509faa1a7a73ae0bf08664a12e7/SpeechResponder/ConfigurationWindow.xaml#L34-L35) and add a second condition for the "IsEnabled" property, based on whether "Value.Responder" is true or false. If current conditions are true, and "Value.Responder" is true, then "IsEnabled" should be true. If both are not true, "IsEnabled" should be false.

**Comment by richardbuckle** [comment]
It strikes me that the proper fix here is to create an "Explorer" personality script that skips the limpet check via editing it. 

Meanwhile I'm afraid I'm going to be tough and close this as a "will not fix". Sorry, but we have provided the tools to fix this given our limited resources we need to spend our time carefully.
