### ISSUE TITLE
Recommend adding troubleshooting step for VoiceAttack integration (Steam users)

### ISSUE THREAD

**Issue by ajklotz** [EDCD/EDDI#2032]
I would recommend that if users are unable to get EDDI to initialize during VoiceAttack startup, make sure that they have the EDDI installation in the same directory as VoiceAttack. Steam will install games in the default directory C:\Program Files (x86)\Steam\steamapps\common\

**Comment by Tkael** [comment]
Thanks for the feedback. We've made some touch-ups to our documentation.
