### ISSUE TITLE
Enhancement: expose current system info through the 'Commander continued' Voice Attack command

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#2039]
## EDDI version in which issue is found
N.A.

## VoiceAttack version in which issue is found (as applicable)
N.A.

## Steps to reproduce
N.A.

## Expected
I expect the `EDDI commander continued system` variable to be set when `((EDDI commander continued))` is called

## Observed
Don't see it

## Investigation
N.A.

The `Commander continued` event should expose the current system information. The speech responder actually makes use of the information, but it is not exposed to the Voice Attack command (not that I can see at least).

**Comment by Tkael** [comment]
The variables prefixed by the event name are those documented within the [Commander continued](https://github.com/EDCD/EDDI/wiki/Commander-continued-event) event documentation. 

Current system variables are not prefixed with the event name and may be accessed independent of the event as documented [here.](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#current-system-variables)

**Comment by eavdmeer** [comment]
Wow, this is the first time I see those system variables. I was not aware that any other information was available than the information exposed by the event itself. Is that something that could make its way into the documentation of the events?

**Comment by Tkael** [comment]
Fair. We'll do that.
