### ISSUE TITLE
Cant open after 2.4.2 update...

### ISSUE THREAD

**Issue by stephenatronach** [EDCD/EDDI#204]
## Steps to reproduce
It happens every time I open it, so step one, open.

## Expected
The program to open and run correctly.

## Observed
It instantly stops working and crashes.

## Investigation
I have uninstalled and reinstalled, and tried an older version. 2.4.1 works, but requires me to update. I have tried various compatibility settings and running as admin. I am on fall creators update of windows.

**Comment by Tkael** [comment]
Sounds like a potential file corruption issue. 
Try moving the folder at %appdata%/EDDI (containing all of your configuration data) to your desktop with a cut and paste, then attempt to open EDDI. It'll recreate new, clean versions of the files it needs in %appdata% when you do this.
Does EDDI open successfully this way?

**Comment by stephenatronach** [comment]
I was actually about to update my post, it turned out I had a missing file
in my elite dangerous folder that it was referencing and it cause the
program to crash, on validating my ed install it now works. Thanks for your
quick response.

**Comment by Tkael** [comment]
Ahh. Glad to hear it. o7 commander.
