### ISSUE TITLE
Make use of WasDiscovered from the journal logs

### ISSUE THREAD

**Issue by Coffee4cr** [EDCD/EDDI#2041]
there's a WasDiscovered when you scan/autoscan a star/body. It would be cool to have it voiced out. So that way when you jump in a system, you know if it was scanned or not.

**Comment by Tkael** [comment]
How would you incorporate it into the current scripts?

**Comment by Tkael** [comment]
Closing for lack of specificity. We can reopen this if any new comments are made.

**Comment by Coffee4cr** [comment]
Oops never got the notification of your message.

I was thinking more of a way to know if you're getting a First Discovered / First Scanned on a planet.

so like, when you FSS a planet, it would tell you, hey you're the first to discover this.  or if it was discovered already, but not scanned (DSS) it could tell you, you can be the first to scan this planet

**Comment by Tkael** [comment]
My concern is that this could quickly get annoying if repeated too often (for example, if you're in an undiscovered system and every body is new). 

Have you tried incorporating this into any of your current scripts to test it out?

**Comment by Coffee4cr** [comment]
No I haven't, I can't find where to access the WasDiscovered in the EDDI scripts

**Comment by Tkael** [comment]
The data is already available, it's just not included in the default script. 

EDDI uses the property names "alreadydiscovered" and "alreadymapped", where "alreadydiscovered" is based on the "WasDiscovered" journal property. 

https://github.com/EDCD/EDDI/wiki/Body-scanned-event

**Comment by Coffee4cr** [comment]
thanks, I'll test it out

**Comment by Coffee4cr** [comment]
Alright that worked, exactly like I wanted

Thanks @Tkael
