### ISSUE TITLE
Error with Crime Check Station Script

### ISSUE THREAD

**Issue by ITZAP** [EDCD/EDDI#2042]
## What's Wrong (please be as specific as possible)
After loading Voice Attack + EDDI v3.7.1, then launching Elite Dangerous, EDDI announces the normal intro:
You are pledged to .... etc
BUT then I regularly get this:
"**Error with Crime Check Station Script. Exception has been thrown by the target of an invocation.**"

### Expected
[Describe what you expected to happen]
No script error.

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
Happens to me regular upon launching Elite Dangerous.
Cannot say if any other Users encounter the same error, except I do not see this Issue Reported here.
eddi.log file provided.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.1
  * VoiceAttack Version: [if applicable] 1.8.7
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] English
  * Voice: [Name and language] Microsoft Zira Desktop

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]
[eddi.log](https://github.com/EDCD/EDDI/files/5706879/eddi.log)

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
Thanks for the report. Please
1. Provide a copy of all of your log files (a new log file is generated each time EDDI or VA is launched and the log file you provided unfortunately does not include any record of the exception).
2. Confirm that you are using the default scripts? If the "Reset" button is active on the "Crime check station" script then you're script has been customized. You can compare your script to the default or reset it as appropriate.
3. If this happens every time that EDDI starts, there might be an issue with your configuration. With EDDI / VA closed, try navigating to %APPDATA%/EDDI and temporarily removing crimemonitor.json before re-launching EDDI / VA?
4. If you close EDDI / VA, then close out of Elite and restart, then re-launch EDDI, does the issue still recur? (if not then it may be a state issue triggered by the events recorded in your local player journal)

**Comment by ITZAP** [comment]
Thanks for your reply @Tkael 
Please delete this issue report.
I will investigate more thoroughly along the lines you have explained.
Thanks.

**Comment by Tkael** [comment]
Feel free to reply after your investigation if you'd like, we can re-open the same ticket. o7 and thanks!
