### ISSUE TITLE
Older Community Goal Missions Not Clearing from EDDI

### ISSUE THREAD

**Issue by ProfStevenFalken** [EDCD/EDDI#2045]
v. 3.7.1  I have two older community goals that won't clear from the mission list.  One is in Eurybia which is a failed mission, the other is in Ackwada and is a claim mission.  Neither of these missions are in the in game mission list.  Neither of these missions list a destination station in EDDI.  Multiple game exits and restarts have not cleared the missions.  Are there any other suggestions as to how to get rid of these two missions?

**Comment by Tkael** [comment]
I see the issue here and I'll make a very small tweak to ensure those get cleared for the next release. In the meantime, you can reset the mission monitor by (with EDDI closed) deleting `missionmonitor.json` from `%APPDATA%/EDDI`.
