### ISSUE TITLE
Limpet purchased -> "{ShipName()}'s"

### ISSUE THREAD

**Issue by VMSrefugee** [EDCD/EDDI#2048]
This doesn't pronounce the way one would hope.  I tried looking for a low, short "zz" in the phonetic translator, but this code didn't seem to accept a phonetic suffix on the shipname.  (Maybe it thinks it's a separate word?  It sounded that way, anyway.)

Possibly the cleanest way to do this is to get a possessive pronunciation from the user?

Anyway, drove me mildly nuts, so I'm taking out possessives from (copies of) the scripts as I run across them.

Loving EDDI, thanks for all your work!

**Comment by Tkael** [comment]
Fair enough. So the proposal is to add a separate possessive pronunciation?
Could you elaborate a little more on how the current behavior isn't working for you?

**Comment by VMSrefugee** [comment]
There are 10 limpets in Shipname's cargo hold.

is pronounced as

There are 10 limpets in Shipname Ess cargo hold.

The "'s" is pronounced as though it's a whole 'nother word.  (Possibly the parser is assuming anything in a variable is a whole word?  I didn't dig into it.)

My thinking is, giving the user a choice of a few (3-10?) different phonemes to tack on the end should be good enough for most cases.  (I'm guessing "totally adequate" for 80%, and "not actively grating" for another 15-19%.)

For that other 1-5%, getting another whole word for the possessive version of the ship name is probably the only practical solution.  And as long as you're doing that, which is easier to code anyway, why bother with the possessive-phoneme-suffix chooser widget, ya?

Anyway, love love love what you guys are doing, big fan!  Thanks for listening to my tiny suggestion!

**Comment by Tkael** [comment]
Thanks for the feedback. 

I've done a little testing and it seems that the output here depends on the specific voice that you're using. I find that my Ivona and Microsoft voices pronounce this perfectly while my Cereproc voices do not. So it's a difference in how each voice interprets the text being fed into it.

The scripts which are affected are:
- `Limpet purchased`
- `Ship repaired`
- `System scan complete`

Unfortunately, adding a possessive form for ship names isn't a particularly simple solution. The simplest solution, and the quickest, is going to be to edit your local personality to rephrase the affected scripts while @richardbuckle and I consider this further.

Suggestions:

_Limpet purchased_
```
{event.amount} limpet{if event.amount > 1:s}
{Occasionally(2, "{if event.amount = 1: has |else: have} been")}
added to 
{OneOf("our", "the")}
{OneOf("cargo hold", "inventory", "hold")}
```

_Ship repaired_
```
{set repairedSystems to []}
{if len(event.items) > 0:
    {for item in event.items:
        {if item = "Paint":
            {set systemDescription to cat("Paint ", OneOf("restored.", "renewed.")))}
            {set repairedSystems to cat(repairedSystems, [systemDescription])}        
        |elif item = "Ship Integrity" || item = "Wear":
            {set systemDescription to cat(Occasionally(2, '{OneOf(\"regular\", \"standard\")}')," maintenance completed."))}
            {set repairedSystems to cat(repairedSystems, [systemDescription])}                 
        }
    }
}

{set repairedModules to []}
{if len(event.modules) > 0:
    {for module in event.modules:
        {if len(module.localizedmount) > 0:
            {_ This is a weapon. We'll identify the class, grade, and mount}
            {set weaponDescription to cat(module.class, " ", module.grade, " ", module.mount, " ", module.name)}
            {set repairedModules to cat(repairedModules, [weaponDescription])}
        |elif find(module.invariantName, "Cockpit") > -1:
            {_ This isn't a weapon. We've matched it to the name of our cockpit module}
            {set repairedModules to cat(repairedModules, [OneOf("Canopy", "Cockpit")])}                 
        |else:
            {_ This isn't a weapon. We haven't matched it to the name of any particular module}
            {set repairedModules to cat(repairedModules, [module.name])}
        }
    }
}

{if len(repairedSystems) > 0:
    {List(repairedSystems)}.
}
{if len(repairedModules) > 0:
    {List(repairedModules)} repaired.
}
{if len(repairedSystems) = 0 && len(repairedModules) = 0:
    {ShipName()} repaired.
}
```

_System scan complete_
```
{_ Preferences _}
{set reportGreenSystems to true}  {_ if true, reports systems containing all fsd synthesis elements. _}
{set reportGoldSystems to true}   {_ if true, reports systems containing all surface prospectable elements. _}
{set reportBodiesToMap to true}   {_ If true, recommends bodies to map using the `Bodies to map` script. _}

{if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":
    {for compartment in ship.compartments:
        {if compartment.module.invariantName = "Planetary Vehicle Hangar":
            {set hasSRV to true}
        }
    }
    {if hasSRV:
        {if system.isgold:
            {if reportGoldSystems:
                This {Occasionally(2, "star")} system 
                {OneOf("contains", "holds", "has")}
                every element 
                {OneOf("that can be found", "available")}
                {OneOf("on planetary surfaces.", "from surface prospecting.")}
                Exploration class: Gold.
            }
        |elif system.isgreen:
            {if reportGreenSystems:
                This {Occasionally(2, "star")} system 
                {OneOf("contains", "holds", "has")}
                every element 
                {Occasionally(2, "that may be")} 
                required to 
                {OneOf("augment", "boost")} 
                {OneOf("the {Occasionally(2, \"jump\")} range of this ship.", 
                       "an explorer's {Occasionally(2, \"jump\")} range."
                )}
                Exploration class: Green.
            }
        }
    }

    {if reportBodiesToMap:
        {set bodiesToMap to F("Bodies to map")}
        {if bodiesToMap:
            {Pause(2000)}
            {bodiesToMap}
        }
    }
}
```

**Comment by Tkael** [comment]
@richardbuckle Your thoughts on this?

**Comment by Tkael** [comment]
Closing due to the complexity of trying to solve this in a way that localizes well with different languages and the relative ease of resolving the issue in individual user scripts.
