### ISSUE TITLE
EDDI process suspended on start up

### ISSUE THREAD

**Issue by giddian** [EDCD/EDDI#2049]
## What's Wrong (please be as specific as possible)
When attempting to run EDDI, the process appears in Task Manager for a second before being suspended and ended.

### Expected
I expect EDDI to run.

### Configuration
* EDDI Version: 3.7.1

## My Investigation
Steps taken in an attempt to rectify the situation
- Ran the EDDI uninstaller.
- Deleted the EDDI folder in AppData/Roaming.
- Downloaded fresh installer.
- Ensured installer executable is unblocked.
- Ran installer as admin.
- Clicked through installer steps using default options. No issues.
- Started Elite Dangerous.
- Once in game, attempted to run EDDI.
- "EDDI (32 bit)" appeared briefly in Task Manager as previously stated before being suspended and disappearing from the process list.
- No data generated in AppData/Roaming/EDDI (the folder is completely empty)

### Investigation Notes
EDDI has worked fine for me in the past. One day I received a pop-up telling me I had been logged out of my OneDrive. After that point EDDI started to experience the errors listed above. I have no idea if this correlation implies causation, since I have no idea how OneDrive could shag up EDDI to begin with. When the issue first occurred, I attempted to find a log file in AppData but none existed (only json files). I still have backups of those json files if any would be useful.

### EDDI Logs
As stated above, no log file, nor any other file, currently exists in AppData.

**Comment by Tkael** [comment]
Let's check the system event viewer to see if it has any details about what is going on. Please see https://www.ideateinc.com/blog/2014/05/use-windows-event-viewer-to-help and report to us any details recorded there about EDDI crashing or being killed by the operating system.

**Comment by Tkael** [comment]
Hi @giddian were you able to identify any additional information to add to this ticket?

**Comment by giddian** [comment]
Hi @Tkael,

Apologies for the delayed reply. Holidays and all. Anyway, I have attached the error logs in question. The source is listed as ".NET Runtime". Thanks for helping me look into this!

Giddian

[EDDI_errorlog_01.txt](https://github.com/EDCD/EDDI/files/5758551/EDDI_errorlog_01.txt)
[EDDI_errorlog_02.txt](https://github.com/EDCD/EDDI/files/5758552/EDDI_errorlog_02.txt)

Oh! And Happy New Year! I have a good feeling about this one ;)

**Comment by Tkael** [comment]
Don't jinx it. ;-)

What version of Windows are you running?
What version of .NET Framework do you have installed? (EDDI requires version 4.8 - this is included by default in Windows 10)
Have you tried reinstalling EDDI?
Have you tried scanning your PC for errors with [sfc /scannow](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system)?

**Comment by Tkael** [comment]
Sorry for the accidental close

**Comment by giddian** [comment]
Hi again,

Windows version: 10.0.19042 N/A Build 19042
.NET Framework version: 4.8.04084
.NET Framework targetversion: 4.0.0
.NET Framework Release: 0x00080ff4 (528372)

I have indeed reinstalled EDDI (tried some of the older versions too, uninstalling with the included executable between each unsuccessful attempt).

I actually ran sfc /scannow the other day for a completely unrelated reason (computer occasionally bluescreens due to bug code 313. Probably not relevant. Haven't delved deeper yet). In any case, /scannow did not find any integrity violations.

I've also run chkdsk for good measure, but it gets stuck in a loop with the following error:

"Insufficient disk space to correct errors in index $SII of file 9"

This is repeated over and over, even after being left to run overnight. Plenty of space on my HDD and SSD, so I'm not sure what it's on about. Again, haven't delved deeper yet. I don't know enough about the ghosts in the machine to determine if these problems are at all related but I figure this extra info can't hurt.

Giddian

**Comment by richardbuckle** [comment]
If `chkdsk` is reporting insufficient disk space when Windows Explorer etc are reporting ample space, then something is badly wrong at the file system level or lower, and I urge you to take a full backup, and a double backup of any important files, then reformat the disks in question.

**Comment by richardbuckle** [comment]
The absence of log files is also a concern and would support the hypothesis of the file system being damaged at a low level. I would urge a backup and reinstall.

**Comment by Tkael** [comment]
Concern seconded.

You might try dowloading and running the [.NET repair tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135), or reinstalling .NET.

Since the initial exception is being thrown from the Rollbar telemetry service, we also can try to bypass that.
1. With EDDI closed, navigate to $APPDATA%/EDDI
2. Open eddi.json
3. Change the `DisableTelemetry` key from `false` to `true`
4. Save and close eddi.json
5. Attempt to restart EDDI
6. Look for .log files and system events if it crashes again

**Comment by giddian** [comment]
I was afraid of as much. If I still have problems after I reformat the computer I'll let you know. Otherwise, thank you to everyone who chimed in to help. It was much appreciated :)

Giddian
