### ISSUE TITLE
Message received Event.source are not localized

### ISSUE THREAD

**Issue by parduz** [EDCD/EDDI#2057]
I'm italian, so i'm using an Italian voice and translating the scripts.

In the "Message Received" script, from {event.source} i keep getting "Squadron mate" and "commander" (in english) ... i don't know if there's other titles in that variable.

### Configuration
  * EDDI Version: 3.7.2-b2
  * VoiceAttack Version: none
  * EDDI's language: Italian
  * Voice: IVONA Carla (italian) but the problem is not voice related.

## My Investigation
I looked in CrowdIn but did'nt find that words (for the context).

**Comment by Tkael** [comment]
Should the `channel` property be localized also? 
Channels are currently only used in the filter but we can expose a localized version of channel names for other uses.

**Comment by Tkael** [comment]
I've reviewed the `channel` property from my own messages. The results were very finite... one of:
- local
- npc
- player
- squadron
- system
- wing

**Comment by Tkael** [comment]
I've reviewed the `channel` property from my own messages. The results were very finite... one of:
- local
- npc
- player
- squadron
- starsystem
- wing

We also know that messages without the `channel` property are possible when in `multicrew` and assign that channel when the property is missing.

**Comment by parduz** [comment]
> Should the `channel` property be localized also?
> Channels are currently only used in the filter but we can expose a localized version of channel names for other uses.

Not a primary need, but if it could be done without too much hassle, why not?
