### ISSUE TITLE
submit error report

### ISSUE THREAD

**Issue by dalvon** [EDCD/EDDI#206]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1442923/eddi_issue.zip)
## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Duplicate of #181. Fix is in testing. Thanks!
