### ISSUE TITLE
Name (Spoken) feature locked up

### ISSUE THREAD

**Issue by DeNomaly** [EDCD/EDDI#2069]
## What's Wrong (please be as specific as possible)
So I accidentally typed "D" (capital letter) and deleted it, but basically it's now telling me, no matter what I input, that the letter "D" is invalid even tho it's not even there

### Expected
Of course that it didn't lock up and instead picked up on the fact that the capital D is no longer in the text field

### Steps to reproduce
I inputted a capital letter "D" and deleted it again, I haven't been able to fix the issue myself and reproduce it as it's a state I can't get it out of

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.2-b2
  * VoiceAttack Version: None installed, isn't using it at all
* Localization [if applicable]
  * EDDI's language: English (English)
  * Voice: Microsoft David Desktop

## My Investigation
I tried typing in "D" again and deleting to see if it was just an issue with not picking it up or whatever, didn't work

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/5792042/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/5792043/eddi1.log)

### Player journals
Since this issue has nothing to do with Elite and only the program I doubt these are needed but I can add them if requested

**Comment by Tkael** [comment]
I'm having trouble replicating this (clearing the invalid character clears the validation so I'm not sure exactly what you're describing). Can you provide more detail on what you are seeing?

If you close EDDI then navigate to %APPDATA%/EDDI/eddi.json, you can manually clear the "PhoneticName" property by replacing the value with `""`.

**Comment by DeNomaly** [comment]
> I'm having trouble replicating this (clearing the invalid character clears the validation so I'm not sure exactly what you're describing). Can you provide more detail on what you are seeing?
> 
> If you close EDDI then navigate to %APPDATA%/EDDI/eddi.json, you can manually clear the "PhoneticName" property by replacing the value with `""`.

I'll try this and attach a screenshot as well, thanks for the info

**Comment by DeNomaly** [comment]
Okay then, Update. Turns out restarting my PC and opening EDDI up somehow fixed it. Welp I guess I could've looked into a restart of my device but I figured it wouldn't make sense if it was connected, the more you know..
