### ISSUE TITLE
Fleet carriers are not initially detected in system report

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#2070]
When jumping into a new system with fleet carriers, the initial after-jump system report does not report any fleet carriers, ever! However, if you then run the 'System report' command through VoiceAttack immediately after, (most) present fleet carriers are reported. Sometimes 1 or more are missing though.

### Expected
To hear fleet carriers get reported with orbital stations and planetary bases at the moment you jump into a new system.

### Observed
Orbital stations and planetary bases are reported, but no fleet carriers.

### Steps to reproduce
1. Set up VoiceAttack with the EDDI profile;
2. Jump into a system that's known to have multiple fleet carriers in it;
2. Listen to the announcements. They will not include any fleet carriers;
3. Issue the 'System report' VoiceAttack command. Fleet carriers will (most likely) be reported. Some may be missing.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.3.7.1
  * VoiceAttack Version: v1.8.7
* Localization [if applicable]
  * EDDI's language: US/English
  * Voice: Microsoft David

**Comment by Tkael** [comment]
The `System report` is triggered from the `FSD engaged` event, written before you enter the star system. At that juncture, signal sources from fleet carriers in-system are not available. These become available only after you have arrived in-system yourself.

**Comment by eavdmeer** [comment]
That makes sense. Also, the Jumped script won't yet report Fleet Carriers and that runs after the jump. I tried to add it there. I ended up making my own 'Fleet carrier report' script and triggering it from VoiceAttack.

**Comment by Tkael** [comment]
Yes, that's expected too and is also due to the timing of when events are recorded in the player journal. `Jumped` is triggered at arrival and we start seeing `Signal detected` events immediately after arrival.

**Comment by Tkael** [comment]
Closing this as not possible since signal sources are not available prior to arriving at your destination system.
