### ISSUE TITLE
Signal detected script bug: event.unique error?

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2072]
## What's Wrong (please be as specific as possible)
When signals are detected the first is ignored and subsequent ones are read out.

### Expected
The first one to be read out and subsequent ones ignored.

### Observed
Detected signals are repeated many times.

### Steps to reproduce
Jump to a system and use the D-Scanner in supercruise (so gui_focus is not relevant).

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v3.7.2-rc1
  * VoiceAttack Version: n/a
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Ivona Amy

## My Investigation
I think that the first instance of a detected signal is being ignored because event.unique is not set (or is 'false'), after which it is then set to 'true'.  This means that all subsequent instances are then read out.  I think the code should be checking for !event.unique instead (line 34).

### Investigation Notes
I added the following to the bottom of the default script:
```
{if event.unique: unique {event.source}. {status.gui_focus}.}
test.
```
I then changed the options to read out combat zones, extractions sites, and emissions.  I jumped into a new system (Ratraii) and used the D-Scanner (honk) in supercruise.  I noted that many of these things were repeated and 'event.unique' was always set.

I got these results read out:
```
test.
[snip]
test.
High Intensity Resource Extraction Site detected. unique High Intensity Resource Extraction Site. none. test.
test.
[snip]
test.
Hazardous Resource Extraction Site detected. unique Hazardous Resource Extraction Site. none. test.
Hazardous Resource Extraction Site detected. unique Hazardous Resource Extraction Site. none. test.
test.
test.
High Intensity Resource Extraction Site detected. unique High Intensity Resource Extraction Site. none. test.
High Intensity Resource Extraction Site detected. unique High Intensity Resource Extraction Site. none. test.
High Intensity Resource Extraction Site detected. unique High Intensity Resource Extraction Site. none. test.
test.
Low Intensity Resource Extraction Site detected. unique Low Intensity Resource Extraction Site. none. test.
```

I jumped to another system, then changed line 34 to use '!event.unique' and jumped back to Ratraii.  This is what I got then:
```
test.
[snip]
test.
Hazardous Resource Extraction Site detected. test.
test.
test.
test.
High Intensity Resource Extraction Site detected. test.
unique High Intensity Resource Extraction Site. none. test.
test.
unique Hazardous Resource Extraction Site. none. test.
Low Intensity Resource Extraction Site detected. test.
test.
unique Hazardous Resource Extraction Site. none. test.
unique Low Intensity Resource Extraction Site. none. test.
unique High Intensity Resource Extraction Site. none. test.
unique High Intensity Resource Extraction Site. none. test.
unique High Intensity Resource Extraction Site. none. test.
test.
```

As you can see, now the first instance is correctly read out, and all 'unique' ones are not (apart from my additional code).

The simplest fix is to use !event.unique to make it the opposite, however this wouldn't then accurately describe the value of the variable.  Alternatively, you could set the variable to be 'true' when entering a system, and then change it to 'false' after the first detected instance.

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
Ah. I see the error. We did inadvertently invert the bool. Thanks for the report.
