### ISSUE TITLE
Is there an EDDI variable for VA to know the state of the normal or alternative flight control input?

### ISSUE THREAD

**Issue by uchiki** [EDCD/EDDI#2076]
## What happens now
I looked at the Wiki but couldn't find this variable.

## What I'd like to happen 
I want to switch the flight input between FA-OFF and FA-ON from the EDDI event so that I want to know the reliable flight input status.

## How it can happen
[Describe how we could implement the feature, if known. Feel free to include any alternative implementation methods you've considered]

## EDDI Version
3.7.2-rc2

**Comment by Tkael** [comment]
You're referencing alternative flight controls for docking? I don't believe such a variable is made available from the game.

**Comment by uchiki** [comment]
It is a display of the setting image and notification when switching.
![001](https://user-images.githubusercontent.com/32535209/104404633-78835a00-559e-11eb-9884-3f2ddfd620a6.png)
![002](https://user-images.githubusercontent.com/32535209/104404638-7b7e4a80-559e-11eb-937a-647222574fbd.png)

**Comment by Tkael** [comment]
That's what I thought. I'm not aware of any feedback made available to us to signal when that transition has occurred.

**Comment by uchiki** [comment]
Understood, thank you for investigating.
Can I close this post?

**Comment by Tkael** [comment]
Done. o7
