### ISSUE TITLE
Norton AV "Not Safe" Message

### ISSUE THREAD

**Issue by ShadowLegion** [EDCD/EDDI#2077]
## What's Wrong (please be as specific as possible)
Norton Security Anti-Virus does not allow installation of EDDI-3.7.2-rc2.exe since it states it is "not safe".

### Expected
[Describe what you expected to happen]
Expecting to be able to install software.

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
Press on the installer file after download to install and get a message that the file is not safe to run from Norton AV.

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
3. Pressed on the installer file after download to install and get a message that the file is not safe to run from Norton AV.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:   EDDI-3.7.2-rc2.exe 
  * VoiceAttack Version: [if applicable] N/A
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] English
  * Voice: [Name and language] N/A

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]
N/A; not installed

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]
N/A

**Comment by Tkael** [comment]
We cannot control or prevent antivirus software from flagging our software but the source code is freely available for inspection and I can assure you that the code is not malicious. 

If you trust EDDI, please report this as a false positive to Norton.
