### ISSUE TITLE
EDDI Speech: EDDI sometimes reverts to a different voice when a Cereproc voice is selected

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#208]
## Steps to reproduce

1. Install a Cereproc Voice ( `CereVoice Heather - English (Scotland)` )
2. Select the Cereproc voice in EDDI while having a different voice set as the Windows speech default
3. Open the Speech responder in EDDI.
4. Create a 'Test' script in your custom personality
5. Write `{ICAO('ABC')}`
6. Hit the 'Test script' button

## Expected
I should hear the Cereproc voice speaking 'Alpha Bravo Charlie'

## Observed
My speech engine falls back to my default speech engine when speaking 'Alpha Bravo Charlie'

## Investigation
Cereproc voices do not support some standard ssml attributes, including the xml:lang tag.
https://www.cereproc.com/files/CereVoiceCloudGuide.pdf

**Comment by Tkael** [comment]
When the xml:lang tag is removed from EDDI's speech synthesis code, the Cereproc voice works.

**Comment by richardbuckle** [comment]
That's annoying as i have just read that Ivona voices _require_ the `xml:lang` tag in order for PLS dictionaries to work.

I don't suppose we can auto-detect if a Cereproc voice is loaded by examining [the VoiceInfo object](https://docs.microsoft.com/en-us/dotnet/api/system.speech.synthesis.voiceinfo?view=netframework-4.7)?

**Comment by Tkael** [comment]
No, but the voice name includes the keyword "CereVoice". JGM was already using the name to try to inject language codes for Cereproc voices.

**Comment by richardbuckle** [comment]
Fix merged.
