### ISSUE TITLE
Broken link in the Wiki

### ISSUE THREAD

**Issue by alterNERDtive** [EDCD/EDDI#2083]
## What's Wrong (please be as specific as possible)

https://github.com/EDCD/EDDI/wiki/Functions links to https://github.com/EDCD/EDDI/blob/beta/SpeechResponder/Help.md (“detailed documentation”) which doesn’t exist.

Educated guess: should be https://github.com/EDCD/EDDI/blob/master/SpeechResponder/SpeechResponderHelp.md.

### Expected

The link does lead somewhere :D

### Steps to reproduce
1. Go to https://github.com/EDCD/EDDI/wiki/Functions.
2. Click the link leading to “detailed documentation”.

**Comment by Tkael** [comment]
Ah yes. Since `Help.md` is now being generated dynamically during the build process the link to the old static file in the repo is no longer valid.
