### ISSUE TITLE
`Swapout` check verbiage is misleading. 

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2084]
## What happens now
Ref. https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8897443
Ref. https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8897494
I just experienced a bug when I docked back at Li Yong Rui power, EDDI tells me I can save money by swapping out the fuel scoop here but it didn't. It's the exact same price.
I wasn't trying to profit, that alert made me think oh that means my scoop isn't bought from LYR so if I sell it here, I will sell it at the 100% price, then buy at 85% price of the same scoop thereby lowering my rebuys. But when I went to sell it, it sells it at the 85% price. So why did the voice prompt said "profit"? Just weird.
The word "profit" is misleading because you won't see any immediate gain from selling your old module and purchasing a new module. The transaction reduces your insurance that the speech should reflect this.

## What I'd like to happen 
Ref. https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8897527
Perhaps, "You can lower your ship insurance by swapping out your {item} at this station". I still think it might be a bug, I am pretty sure I bought and fit that ship at LYR. It's an AspX I bought and fit after coming back in October for engineering mats gathering, by that time I was focused on the discount. Anyway, if it's not a profit we shouldn't say profit :) As you know in Elite, profit is a strong word haha. 

## How it can happen
Speech responder script change

## EDDI Version
3.7.2-rc3

**Comment by Tkael** [comment]
I'm considering changing the `Swapout check` script from
```
                {_ Only bother if it's a relatively good saving}
                {if saving / cmdr.credits > 0.001:
                    You could save {Humanise(saving)} credits by swapping out your {shipmodule.name} here.
                }
```
to
```
                {_ Only bother if it's a relatively good saving... more than 2% of the ship value and more than 0.1% of the commander's credit balance}
                {if saving / ship.value > 0.02 && saving / cmdr.credits > 0.001:
                    You could reduce your rebuy by {Humanise(round(saving * cmdr.insurance))} credits by swapping out your {shipmodule.name} here.
                }
```
This would re-phrase the output in terms of your rebuy and would change the savings criteria to require saving both at least 2% on your ship's value and 0.1% on the your total credit balance).

**Comment by clinkingdog** [comment]
This has confused me for years, and now I finally know what it means! 😄 Thank you for this PR, looking forward to the new wording.
