### ISSUE TITLE
EDDI not launching

### ISSUE THREAD

**Issue by Hazen357** [EDCD/EDDI#2088]
I have the latest version of EDDI and Voice Attack, but when I try and launch EDDI, nothing happens.  In event viewer it gives me errors 1000 and 1026 for EDDI.  I've scanned for corrupt files on my pc with sfc /scannow.  I have updated video drivers. I have reinstalled EDDI and VA.  I'm not sure what I should try next  Any help is appreciated.

**Comment by Tkael** [comment]
I'm afraid that this isn't very much information to go on. Can you provide a screenshot of the full error messages that you're seeing in the Windows Event Viewer? 
Please also provide the specific software versions that you are using. We don't want to make assumptions based on "latest version".
Is an eddi.log file created at %appdata%/EDDI/eddi.log? If so, please provide a copy of that log file too.

**Comment by Hazen357** [comment]
I added a txt file with the event errors.  I am using EDDI version 3.7.2.  I didn't see a log file that was created in the folder.  I hope this helps.

[EDDI Error.txt](https://github.com/EDCD/EDDI/files/5870966/EDDI.Error.txt)

**Comment by Tkael** [comment]
Thanks. 

You might try disabling the Rollbar telemetry service since that seems to be triggering an issue with system .dll files. You can do that by opening %APPDATA%/EDDI/eddi.json and changing the "DisableTelemetry" property from "false" to "true".

Whether or not that works, you might also want to run the .Net Framework Repair tool [here](https://www.microsoft.com/en-us/download/details.aspx?id=30135). 

If all else fails, it might be time to reinstall or refresh Windows.

**Comment by rodan123** [comment]
Isn't the folder for EDDI logs (.log) and config files (.json); %APPDATA%/**ROAMING**/EDDI/...

At least it is on my system.

**Comment by ABELSS** [comment]
![image](https://user-images.githubusercontent.com/9919880/106020786-66d4a300-60c4-11eb-92f4-72e97b2bbe6e.png)
![image](https://user-images.githubusercontent.com/9919880/106020836-7522bf00-60c4-11eb-9109-02b2117167b4.png)

**Comment by ABELSS** [comment]
![image](https://user-images.githubusercontent.com/9919880/106020935-91266080-60c4-11eb-9425-ad97fa21e359.png)

**Comment by Hazen357** [comment]
Thanks for helping Tkael

I don't see a DisableTelemetry entry in my EDDI.json.  Should there be?  I did run the .net repair tool, and it did not resolve my issue.  If you don't know of something else to try, then maybe a fresh install is needed.

**Comment by Tkael** [comment]
Yes, eddi.json should have a line that looks like `  "DisableTelemetry": false,`. For me, it's on line 15.

Other than that, I'm at a loss. You seem to be the only one with this issue and while we cannot rule out a flaw in the program its looking like a possible issue with your .Net Framework installation. Are you having any issues with other programs or is it just this one?

There are technically some ways that you might be able to reinstall the .Net Framework but if you're at that point then it may be simpler to just do a fresh install.

**Comment by ABELSS** [comment]
Just that one.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Brian Wilson <notifications@github.com> Datum: 29/01/2021  08:43  (GMT+01:00) Aan: EDCD/EDDI <EDDI@noreply.github.com> Cc: ABELSS <sven.abels@telenet.be>, Comment <comment@noreply.github.com> Onderwerp: Re: [EDCD/EDDI] EDDI not launching (#2088) 
Yes, eddi.json should have a line that looks like   "DisableTelemetry": false,. For me, it's on line 15.
Other than that, I'm at a loss. You seem to be the only one with this issue and while we cannot rule out a flaw in the program its looking like a possible issue with your .Net Framework installation. Are you having any issues with other programs or is it just this one?
There are technically some ways that you might be able to reinstall the .Net Framework but if you're at that point then it may be simpler to just do a fresh install.

**Comment by ABELSS** [comment]
And sadly reinstalling EDDI 3.7.2 did not solve the issue either

**Comment by ABELSS** [comment]
> Yes, eddi.json should have a line that looks like ` "DisableTelemetry": false,`. For me, it's on line 15.
> 
> Other than that, I'm at a loss. You seem to be the only one with this issue and while we cannot rule out a flaw in the program its looking like a possible issue with your .Net Framework installation. Are you having any issues with other programs or is it just this one?
> 
> There are technically some ways that you might be able to reinstall the .Net Framework but if you're at that point then it may be simpler to just do a fresh install.

It looks my eddi.json does not include the line you mentioned: "DisableTelemetry": false,

**Comment by Tkael** [comment]
That suggests that the last version of EDDI that you ran successfully was several versions ago. 

Please confirm the Windows version that you are using? Do you have .Net Framework version 4.8 installed (if you're running Windows 10 then it should be installed as part of Windows)?

**Comment by ABELSS** [comment]
Hi, Thanks for the support.i´m running win 10 home ed. Need to check on .net versionVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Brian Wilson <notifications@github.com> Datum: 30/01/2021  05:40  (GMT+01:00) Aan: EDCD/EDDI <EDDI@noreply.github.com> Cc: ABELSS <sven.abels@telenet.be>, Comment <comment@noreply.github.com> Onderwerp: Re: [EDCD/EDDI] EDDI not launching (#2088) 
Please confirm the Windows version that you are using? Do you have .Net Framework version 4.8 installed (if you're running Windows 10 then it should be installed as part of Windows)?

**Comment by ABELSS** [comment]
Error is still in place. 
Have tried the following:
Uninstalled .NET4.8 and 3.5 (in Win10), then rebooted and reinstalled the apps => No luck error is coming from .NET 4.0.30319
uninstalled EDDI, then rebooted and installed latest download 3.7.2 => Not resolved
Reinstalled Ms Visual C++ 2015-2019 package to force an update of .net

Below error messages remained:

![image](https://user-images.githubusercontent.com/9919880/106464800-6d369680-6499-11eb-900d-c3a39a790404.png)
![image](https://user-images.githubusercontent.com/9919880/106464821-76276800-6499-11eb-823d-3f584a25a7be.png)
![image](https://user-images.githubusercontent.com/9919880/106464862-84758400-6499-11eb-9bc4-390752c9ee6a.png)

**Comment by Tkael** [comment]
I'm still grasping at straws but I might have an idea.

When you reinstalled EDDI, did you delete the install directory entirely? If not, please try deleting EDDI.exe.config. Please also re-run `sfc /scannow` and the .Net Framework Repair Tool.

**Comment by Tkael** [comment]
In fact, go ahead and delete the install folder entirely before reinstalling EDDI (just to be sure).

**Comment by ABELSS** [comment]
> In fact, go ahead and delete the install folder entirely before reinstalling EDDI (just to be sure).

Sadly, still same error. So most probably the .net, And I lack the knowledge on how to reinstall that specific version of .net...

**Comment by Sotakone** [comment]
I'm hopping in with this same problem. Occured yesterday, few days after i have upgraded into newest version of EDDI. I have pretty much re-installed everything else than windows10 itself and it just wont load.

```
Application: EDDI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(System.String)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
   at System.Diagnostics.TraceInternal.InitializeSettings()
   at System.Diagnostics.TraceInternal.TraceEvent(System.Diagnostics.TraceEventType, Int32, System.String, System.Object[])
   at Rollbar.NetFramework.RollbarTelemetryConfigSection.GetConfiguration()
   at Rollbar.Telemetry.TelemetryConfig.SetDefaults()
   at Rollbar.Telemetry.TelemetryCollector..ctor()
   at Rollbar.Telemetry.TelemetryCollector+NestedSingleInstance..cctor()

Exception Info: System.TypeInitializationException
   at Rollbar.Telemetry.TelemetryCollector.get_Instance()
   at Rollbar.RollbarLogger..ctor(Boolean, Rollbar.IRollbarConfig)
   at Rollbar.RollbarFactory.CreateNew(Boolean)
   at Rollbar.RollbarLocator+NestedSingleInstance..cctor()

Exception Info: System.TypeInitializationException
   at Rollbar.RollbarLocator.get_RollbarInstance()
   at Utilities._Rollbar.set_TelemetryEnabled(Boolean)
   at Eddi.App.StartRollbar(Boolean)
   at Eddi.App.Main()

```

**Comment by Tkael** [comment]
Hi @Sotakone, other than upgrading to the latest version of EDDI have you changed anything about your system in the last couple of days? If you do a System Restore to a timestamp immediately after upgrading EDDI then does that correct the issue?

**Comment by Sotakone** [comment]
Havent done anything... no new software and no new hardware. Everything else is running as always, EDDI just stopped working.

```
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
```

Device name	MATOLAATIKKO
Processor	Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz   2.49 GHz  (2 processors)
Installed RAM	64,0 GB
Device ID	7F088536-7F34-479B-AF5E-92F359B0AC2E
Product ID	00329-00000-00003-AA778
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎19/‎08/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by Tkael** [comment]
Did EDDI run correctly at least once after upgrading? Or did it stop running as soon as you upgraded? If so, did you try downgrading to an older release?

Did you try a System Restore?

**Comment by Sotakone** [comment]
EDDi did run perfectly for few days and then just stopped working... last time it worked, i was just playing normally, shut everything down and closed my comp.. next day i started comp and everything else fired up besides EDDI. API's are working normally with every other tool, nothing unusual going on...
Dont have system restore running. I kinda sweep everything clean with new windows-installation rather than make snapshots.

**Comment by Sotakone** [comment]
Ok, got it working again. Uninstalled EDDI, used BCUninstaller for it, cleaned registry with it and manually remover both directories from `%appdata%` \Local and \Roaming.
Will add EDSM and Inara API's next and connect into Frontier to see what happens...

**Comment by Tkael** [comment]
@Sotakone Awesome! I'd forgotten about the \Local folder. Perhaps there was some file corruption there. If you still have your folder (perhaps in the Recycle Bin?), would you consider zipping it up and attaching it to this ticket?

@Hazen357 @ABELSS Please check whether similar actions resolve this issue for you too?

**Comment by Sotakone** [comment]
[Eddi.zip](https://github.com/EDCD/EDDI/files/5925198/Eddi.zip)

There you go, happy to help :)

**Comment by Tkael** [comment]
Yep. I can confirm that the user.config file in a sub-folder of %LOCALAPPDATA%/Eddi was corrupt (at least for @Sotakone).
That would be the file that normally stores your window state and position.

**Comment by Tkael** [comment]
The fix then would be to either 
1. Validate the settings in %LOCALAPPDATA% are readable when EDDI launches and gracefully reset if they are not OR
2. Migrate settings to the EddiConfiguration class (where we've already built in a graceful reset if the file isn't readable) and deprecate our %LOCALAPPDATA% file.

**Comment by Tkael** [comment]
@richardbuckle Your thoughts?

**Comment by Tkael** [comment]
For option 1, we'd be looking at adding something like [this](https://www.codeproject.com/Articles/30216/Handling-Corrupt-user-config-Settings).
