### ISSUE TITLE
Support the Inara API when it becomes available

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#209]
See https://inara.cz/inara-api/

**Comment by richardbuckle** [comment]
From Artie:
https://inara.cz/inara-api-devguide/
https://inara.cz/inara-api-docs/
there aren't all events available and documented yet, I am adding it as the beta is progressing
discussion is there, eventually: https://inara.cz/board/7049/

**Comment by Tkael** [comment]
This is also redundant with EDSM in many respects.

**Comment by richardbuckle** [comment]
Maybe so, but it's an established service that many users would like to see supported.

**Comment by BeBumble** [comment]
I personally have both, I like INARA cause it just looks cool and I can look to see what engineering I can do. EDSM to see where I've been etc.

**Comment by clinkingdog** [comment]
Is anyone actively working on this at the moment? I don't mean to nag - just curious about whether it's likely to be released any time soon. If not I'll set up EDMC, but I'd rather get EDDI to do it so if it's on its way then I'll wait :)

**Comment by richardbuckle** [comment]
It hasn’t been scheduled yet, but it’s something that I personally would like to see soon. You might want to use EDMC in the meantime.

**Comment by clinkingdog** [comment]
Ok, will do. Thanks!

**Comment by Tkael** [comment]
One way we could use this would be to have a 'Friends monitor' tab with an option to sync detailed data about your friends from Inara using the `[getCommanderProfile](https://inara.cz/inara-api-docs/#event-2)` method described by Inara's profile docs. You'd also have to be able to assign friends to categories of course (so that you could mute or otherwise differently handle different friends).

**Comment by Taomyn** [comment]
+1 I like Inara's "nearest" search automatically picking up my location so I don't have to type anything into the browser - handy as I use VR, I just wish I could find a way to populate the result into the clipboard so I can paste it into the game, but that's another issue.

**Comment by kkdawkins** [comment]
+1 I love Inara, and automatic sync would be awesome! :)

**Comment by Simon-Dainty** [comment]
Any news on Inara support?

**Comment by richardbuckle** [comment]
Fixed for 3.4.4-b1
