### ISSUE TITLE
Galnet stuck on repeat 

### ISSUE THREAD

**Issue by feczo** [EDCD/EDDI#2096]
I hear:

A new Galnet article has been published, entitled Halsey Suggests Motivation for Assassination Attempt.  The audio recording is ready.
15 new Galnet articles have been published, including 7 of note. The first is entitled Anonymous Source Refers to Distress Call Location. The second is entitled Trial of Fleet Admiral Vincent Begins. The next is entitled Jasmina Halsey Returns to the Federation. The next is entitled Galactic Summit Proposal from Sirius Corporation. The next is entitled New Marlinist Systems Request Emergency Food Supplies. The next is entitled Xenological Samples Delivered to Colonia. The last is entitled Core Dynamics Insider Discusses Lakon Takeover.  The audio recordings are ready.
An unusual new Galnet article has been published, entitled Halsey Suggests Motivation for Assassination Attempt.  The audio recording is ready.
15 new Galnet articles have been published, including 7 of interest. The first is entitled Anonymous Source Refers to Distress Call Location. The second is entitled Trial of Fleet Admiral Vincent Begins. The next is entitled Jasmina Halsey Returns to the Federation. The next is entitled Galactic Summit Proposal from Sirius Corporation. The next is entitled New Marlinist Systems Request Emergency Food Supplies. The next is entitled Xenological Samples Delivered to Colonia. The last is entitled Core Dynamics Insider Discusses Lakon Takeover.  The audio recordings are ready.
A new Galnet article has been published, entitled Halsey Suggests Motivation for Assassination Attempt.  The news report is ready for playback.

**Comment by feczo** [comment]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/5894178/eddi_issue.zip)

**Comment by Tkael** [comment]
Hmm...
2021-01-29T13:46:04 [Debug] GalnetMonitor:monitor Updated latest UID to 6014054b77651863fb13c65d
2021-01-29T13:46:35 [Debug] GalnetMonitor:monitor Updated latest UID to 6012e18984e09d125e030977
2021-01-29T13:47:36 [Debug] GalnetMonitor:monitor Updated latest UID to 6014054b77651863fb13c65d
2021-01-29T13:49:07 [Debug] GalnetMonitor:monitor Updated latest UID to 6012e18984e09d125e030977
2021-01-29T13:49:37 [Debug] GalnetMonitor:monitor Updated latest UID to 6014054b77651863fb13c65d
2021-01-29T13:50:38 [Debug] GalnetMonitor:monitor Updated latest UID to 6012e18984e09d125e030977
2021-01-29T13:51:08 [Debug] GalnetMonitor:monitor Updated latest UID to 6014054b77651863fb13c65d
2021-01-29T13:51:39 [Debug] GalnetMonitor:monitor Updated latest UID to 6012e18984e09d125e030977

We track the latest UID to know the last article we received. It's almost as though articles were being received in a different order each time we checked the feed, though I've never known that to happen before and I haven't been able to reproduce it locally.

**Comment by Tkael** [comment]
Is this issue still occurring?

**Comment by feczo** [comment]
did not experience it since

**Comment by Tkael** [comment]
Thanks. I'm going to go ahead and close this as a weird one-off (maybe the RSS feed was being updated at the time?). Please let us know if it happens again and we can reopen this ticket if that happens.
