### ISSUE TITLE
Using the phrase "in this system"

### ISSUE THREAD

**Issue by zkfbzjm** [EDCD/EDDI#2106]
When this phrase is said it comes out as "indiana this system" Not really a problem ,just thought you should know.

**Comment by Tkael** [comment]
That may be a voice-specific quirk? What voice are you using and what was the complete speech?

**Comment by zkfbzjm** [comment]
Using Microsoft Zira voice.The complete speech has to do with missions at a particular system.EX "you have 5 missions indiana this system"
    On Tuesday, February 9, 2021, 12:34:39 AM EST, Brian Wilson <notifications@github.com> wrote:  
 
 


That may be a voice-specific quirk? What voice are you using and what was the complete speech?

**Comment by Darkcyde13** [comment]
That's strange.  I've just tried this out with MS Zira, and I am unable replicate the problem.  I've tried a few variations like:
"You have 5 missions in this system."
"You have 5 missions In this system." (capitalised 'in')
I've also tried them with a period '.' or comma ',' both before and after the 'in'.  The only time I get anything different, is when I use 'In.' where EDDI spoke it as "eye-en", spelling the letters out.

Could this be something country specific?  What region is your PC set to?  Mine is English UK.

Also, are you using a custom EDDI personality, or the default?  I'm wondering if something may have been edited that could possibly cause your problem?

**Comment by zkfbzjm** [comment]
Mine is English USA.

    On Tuesday, February 9, 2021, 01:05:11 PM EST, Darkcyde <notifications@github.com> wrote:  
 
 


That's strange. I've just tried this out with MS Zira, and I am unable replicate the problem. I've tried a few variations like:
"You have 5 missions in this system."
"You have 5 missions In this system." (capitalised 'in')
I've also tried them with a period '.' or comma ',' both before and after the 'in'. The only time I get anything different, is when I use 'In.' where EDDI spoke it as "eye-en", spelling the letters out.

Could this be something country specific? What region is your PC set to? Mine is English UK.

Also, are you using a custom EDDI personality, or the default? I'm wondering if something may have been edited that could possibly cause your problem?

**Comment by zkfbzjm** [comment]
Just opened ED and EDDI just said you have 5 missions in 4 systems so I think it is linked to the combination of in and this .Also Indiana is in the US .(sorry you already knew that)
    On Tuesday, February 9, 2021, 01:17:58 PM EST, dennis phillips <zkbzjm@yahoo.com> wrote:  
 
  Mine is English USA.

    On Tuesday, February 9, 2021, 01:05:11 PM EST, Darkcyde <notifications@github.com> wrote:  
 
 


That's strange. I've just tried this out with MS Zira, and I am unable replicate the problem. I've tried a few variations like:
"You have 5 missions in this system."
"You have 5 missions In this system." (capitalised 'in')
I've also tried them with a period '.' or comma ',' both before and after the 'in'. The only time I get anything different, is when I use 'In.' where EDDI spoke it as "eye-en", spelling the letters out.

Could this be something country specific? What region is your PC set to? Mine is English UK.

Also, are you using a custom EDDI personality, or the default? I'm wondering if something may have been edited that could possibly cause your problem?

**Comment by Darkcyde13** [comment]
> Also Indiana is in the US .(sorry you already knew that)

Yeah, that's kinda why I was wondering if it was country specific, just in case your PC being set to the US region meant that sometimes 'in' could be mistaken for the abbreviation of Indiana, hence why I tried the particular variations I did.  But I think that's a bit of a long shot and is unlikely to be the case.  I've tried setting my PC to be US region, and it still works as I'd expect, saying 'in' and not 'Indiana'.

Are you using the EDDI default personality, or a custom one?  I.E. have you made changes to any scripts?

The script that reports your missions in the system, is called 'Mission check system'.  Is this still default?

**Comment by Tkael** [comment]
Usually, such things are voice specific rather than region specific. That said, I might expect "IN" to yield Indiana but not "in".

**Comment by zkfbzjm** [comment]
I do have ICAO active.    On Tuesday, February 9, 2021, 04:06:14 PM EST, Brian Wilson <notifications@github.com> wrote:  
 
 


Usually, such things are vice specific rather than region specific. That said, I might expect "IN" to yield Indiana but not "in".

**Comment by Tkael** [comment]
ICAO will have no affect here.
I'm not replicating this with Microsoft Zira on my system.

If you can replicate this, please temporarily activate verbose logging, replicate the issue, grab the eddi.log file at %appdata%/EDDI, zip it up, and attach it here so that we can see the exact text being sent to the speech synthesizer. Please turn off verbose logging once this is done.

**Comment by zkfbzjm** [comment]
For some reason this happens randomly.Happened when the phrase "in this system" came after saying the station name associated  with the mission EX: You have 4 missions at station Key Enterprise indiana this system.That was the only instance of this issue that I encountered during about 2 hours of play.
    On Wednesday, February 10, 2021, 02:05:50 AM EST, Brian Wilson <notifications@github.com> wrote:  
 
 


ICAO will have no affect here.
I'm not replicating this with Microsoft Zira on my system.

If you can replicate this, please temporarily activate verbose logging, replicate the issue, grab the eddi.log file at %appdata%/EDDI, zip it up, and attach it here so that we can see the exact text being sent to the speech synthesizer. Please turn off verbose logging once this is done.

**Comment by Tkael** [comment]
Ok. If it happens again, please jump out of the system, enable verbose logging, and then jump back in.

I'll close this ticket for now since we can't replicate the issue but if you update this ticket I'll get a notification. We'll then be able to re-open the ticket once again. o7
