### ISSUE TITLE
Auto generate a RouteDetails() from the NavRoute.json file

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2108]
## What happens now
To generate a route, and have the variables set to the route details, we need to manually invoke a RouteDetails() with the relevant route type.  This can currently only be done with certain route types.  It does not allow for EDDI to have the details (systems in a route, number of jumps to destination, etc) for a route manually plotted by the GalMap.

## What I'd like to happen 
I'd like the details of a manually plotted route to be available to EDDI and the user.  I think it would be a nice idea to have an event for when the NavRoute.json file is updated/changed, and in that event, a simple RouteDetails("set", destinations_system) be run so that all route info is available to EDDI.

This has come about from a request by Don_Chooluvit on the forums, and subsequent replies:  https://forums.frontier.co.uk/threads/eddi-scripts-and-eddi-enabled-va-commands-thread.311614/post-8943507

## How it can happen
When a route is plotted on the GalMap, by selecting a system and clicking the Plot Route icon, Elite writes this info to the NavRoute.json file.  EDDI could then check the file for any changes, just like it does with the Player Journal (which I think it already does?).  When this file is updated, trigger an event that runs RouteDetails() to set the relevant route variables with the information provided, or just run the code for RouteDetails() in the background.  I think an event would be better though, as then speech responses can be configured and customised for this.

The only downside I can see to this, is that if a route is cancelled by clicking the 'Clear route' icon, the NavRoute.json file is not updated and cleared, so the route information is considered still valid.

## EDDI Version
V3.7.2

**Comment by Tkael** [comment]
I've been thinking about this recently. 

RouteDetails() seems to be doing several different kinds of tasks.
1. Querying for services / scoopable stars near me (encoded, facilitator, guardian, human, manufactured, raw, scoop)
2. Querying for various mission specific criteria (expiring, most, nearest, farthest, source)
3. Managing internal routing, entirely separate from the game, primarily (but not exclusively) for mission routes (cancel, set, next, update, route)

The other way that we could consider going with this might be to drop support for group 3, rely on NavRoute.json for the actual routing, and convert select mission routing functions (perhaps next/update & route) to queries like group 2. That way there wouldn't be two separate routings (one in game and another external to the game) that commanders would need to keep straight. 

Feedback welcome.

**Comment by Darkcyde13** [comment]
I like the idea, but isn't the NavRoute.json only a list (in basic terms) of the systems you need to pass through to reach your destination?  I mean, it doesn't handle a multi-stop mission route, for example.  Or am I missing what you mean entirely?

**Comment by Tkael** [comment]
Correct. NavRoute.json provides your actual plotted route from in game.

Essentially, the thought is to continue to recommend mission system destinations but not to "set" a destination in EDDI which differs from your in-game selection.

**Comment by Darkcyde13** [comment]
It's been a long time since I opened this ticket, but I think I was thinking along the lines of if you don't already have a route calculated and set (mission or otherwise), then set one using the NavRoute file when it changes.

I think I see what you mean though.  Calculate and store a mission route as a separate entity to anything created with RouteDetails(), or at least not to overwrite one with the other.  A mission route is something that you need to go back to and update as you complete each mission, whereas all other types are a single destination; go there and you're done.  You may also want or need to make a detour in the middle of a mission route, but still want to retain that route to continue later.  Then use the NavRoute.json to actually set the destination/route in EDDI.

**Comment by alterNERDtive** [comment]
> The only downside I can see to this, is that if a route is cancelled by clicking the 'Clear route' icon, the NavRoute.json file is not updated and cleared, so the route information is considered still valid.

Is it updated as you do jumps along your route?

In general I don’t think not having it updated unless you plot a different route isn’t that big of an issue, especially if you go with the event route. An event is just a snapshot of the state at a certain time anyway.

**Comment by Tkael** [comment]
Resolved by changes to the RouteDetails() function and navigation service for next release.
