### ISSUE TITLE
Keyboard shortcuts to access the configuration tabs

### ISSUE THREAD

**Issue by TastyVacuum** [EDCD/EDDI#2109]
## What happens now
There are no short cuts to accessing the different tabs, you need to click or press the tab key to move between them. I am trying to automate changing between Commanders using VoiceAttack and can't consistently access the tabs to change items such as name, EDSM API key etc.

## What I'd like to happen 
A keyboard shortcut available for each such as ALT-G opens the Galnet Monitor tab.

## How it can happen
I don't know the details from a coding point of view but it is normally a mark up in the tab component entries. There is a lot of duplication across the names of the tabs so maybe hidden A. B. C. ... prefixes would simplify it.

## EDDI Version
v3.7.2

**Comment by Tkael** [comment]
The underlying issue here is #505.

**Comment by Tkael** [comment]
Please note that there is a risk of mixing data between accounts with the method that you are proposing for managing multiple commander accounts. Particularly with respect to the shipyard when the Frontier API is connected, but also with most other monitors.
At present, the best way to isolate multiple commander accounts is to use multiple Windows accounts. We know its unwieldy but it is the best method to prevent mixed data between your accounts.

**Comment by TastyVacuum** [comment]
Thanks Tkael,
Isn't the change as described a useful one regardless of my intended use? I am aware of the mixed data issues and full multi-commander support would be fantastic. I can live with the inconsistencies and was just looking to help my script work more consistently than it does with slightly unpredictable nature of the current field/tab focus when opening and re-opening the config app.

Many thanks.

**Comment by Tkael** [comment]
I'm sorry, but I just don't see enough benefit to warrant the effort required for this.
