### ISSUE TITLE
Update rings from the `SAASignalsFound` event?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2118]
- Add a variable to record when / whether the ring has been mapped?
- Add a variable to record detected hotspots for that ring?
- Preserve these properties when syncing data from 3rd parties
- Add optional `Rings to map` script, similar to the `Bodies to map` script? (see description below)

I am trying to add a recommended rings to scan to the "Bodies to map" script,
I want it to inform me of icy rings like it does with planets.
`{ if body.rings != 0:
        {for ring in body.rings:
        	{if ring.composition = "Icy":
        		{if !toMapList[body.shortname]: 
	                      {set toMapList to cat(toMapList, [body.shortname])}
	                  } 
        	}
        }
}`
I have this code after line 45 (test if not star)
I haven't been able to find a variable that would tell the script if the ring has been mapped yet, only the planet.

thanks in advance

_Originally posted by @TentacleMasterKonami in https://github.com/EDCD/EDDI/discussions/2117_

**Comment by TentacleMasterKonami** [comment]
If possible, a position of hotspots and their size would be great, since you can use that data to find overlaps automatically

**Comment by Tkael** [comment]
Sorry, but as you can see below hotspot size and position are not available from the messages we receive. 
```json
{ "timestamp":"2020-11-27T01:56:06Z", "event":"SAASignalsFound", "BodyName":"Robigo 2 A Ring", "SystemAddress":9463020987689, "BodyID":17, "Signals":[ { "Type":"Alexandrite", "Count":2 }, { "Type":"Monazite", "Count":1 } ] }
```

**Comment by fraxinus-e** [comment]
I have raised #2169 Ring hotspots detected not triggering with Ship role set to 'Mining', Tkael asked me to link it here.

**Comment by Tkael** [comment]
I've added `mapped` and `hotspots` properties to `ring` objects for the next release. That should allow you to create a `Rings to map` script.
