### ISSUE TITLE
Phonetic short names of bodies 10+ are oddly pronounced

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#2119]
### Expected
"Body 11 A"

### Observed
"Body 1 1 A"

### Steps to reproduce
1. Pass the short name of any body 10+ through the P() function with the hint set to "body"
2. Listen to the resulting output

### Configuration
* Version 
  * EDDI Version: 3.7.2
  * VoiceAttack Version: N/A 
* Localization: N/A

### Investigation Notes
The P() function passes the body short name through the `Translations.cs/sayAsLettersOrNumbers` method. This method breaks the input down into individual characters then applies SSML to speak each character or digit separately. "11" is broken down into two digits to be pronounced separately rather than being preserved as a single number.

**Comment by rodan123** [comment]
While you're in there, could you look at systems where the '-' is read as "minus" rather than "dash"?
I believe that the "-" should always be read as "dash" never "minus" in regard to system names.

cpd-28 332 is an example system where I have experienced this anomaly.

Thanks.
