### ISSUE TITLE
Missions reporting bug

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2121]
## What's Wrong (please be as specific as possible)
When loading into game, EDDI reports that I have "one pending mission at this station" (I'm currently docked at the CG megaship).  It then proceeds to tell me that I "have no missions at this time", contradicting what it just told me, and being incorrect as I do have one mission, the current CG.

### Expected
EDDI to correctly report I have one mission on both occasions.

### Observed
On start up, EDDI reports:
"Welcome back commander.
You are docked at Mega-ship, Spirit of Laelaps, in the Sirius system.  Information:  You have 1 pending mission located at this station
You currently have no missions.
Docking complete."

### Steps to reproduce
1. Load EDDI, either stand-alone or by Voice Attack, as it happens with both.
2. Run the Elite Launcher.
3. Click Play and load up the game.
4. Click 'Continue' and load your game.
5. Listen to what EDDI reports for your current missions.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v3.7.2
  * VoiceAttack Version: v1.8.7.12 (prerelease) 64bit
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I noticed this last week when I was doing the previous CG, but when I tried all the scripts, they all worked ok.  Having had the same thing occur this week, I've investigated further.

I was getting this problem with my personality, so I changed over to the EDDI default and I'm getting the same thing happen.  It seems that on loading my game, EDDI runs the 'Commander Continued' script, then the 'Location' script, then the 'Missions' script.  The 'Location' script runs the 'Mission check station' script, as I am docked at a station, and this correctly reports I have one mission here.  When the 'Missions' script runs, it runs the 'Mission check galaxy' script, and this then reports I have no missions.

However, once I'm loaded up, if I manually run any of the above scripts, they all work as expected, correctly reporting I have one mission.  As both the 'Location' and 'Mission check galaxy' scripts check the missionsCount variable in exactly the same way in order to do their respective reporting, I can only assume that it's a timing thing.  I first thought that one script was running before the variable was populated with the number of missions, but that doesn't make sense as the failure happens after missionsCount is used successfully.  At least in my testing that's how it appears, as the info from 'Location' always gets spoken before the info from 'Missions'.  'Location' works as expected, but 'Missions' does not.

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/6063885/eddi.log)

### Player journals
(Not included)

EDIT: Sorry, I forgot to specify, I only have the one mission, and it is the CG.  I'm not sure if this will also happen with normal missions or not, but it's reproducible with the CG as the only mission.

**Comment by Tkael** [comment]
Found the issues.
1. The `Missions` event was stripping community goal missions from the mission list.
2. The `Community Goal` event was re-adding the missions, less the `communal` flag that we use to track that the mission represents a community goal.
