### ISSUE TITLE
Mission accepted script doesn't account for CG missions

### ISSUE THREAD

**Issue by arancaytar** [EDCD/EDDI#2122]
## What's Wrong (please be as specific as possible)

Community Goals do not count toward the maximum of 20 missions in-game, but are counted by EDDI; the script will therefore incorrectly tell you the maximum has been reached before it has been.

(Related to this, the script currently only has special cases for the suffix of 1st, 2nd, and 3rd, but due to the above it is sometimes possible to have more than 20 missions, which is incorrectly pronounced as "21th", "22th" etc)

**Comment by Tkael** [comment]
This occurs because of a bug that causes community goal missions to sometimes not be counted as community goal missions. Should already be fixed for the next release by https://github.com/EDCD/EDDI/commit/e648ebc3c44ea8797d680d23ec668c56738a7e46.
