### ISSUE TITLE
A Resource for Scripts and Personalities for EDDI?

### ISSUE THREAD

**Issue by dylan-k** [EDCD/EDDI#2126]
## What happens now
If you'd like to find/share scripts and personalities for EDDI at present, they're out there, but the forum thread is cumbersome and other options are spread out. None of the current options have versioning, etc. like other code can have.

## What I'd like to happen 
Could there be a wiki or a repo where customized community scripts and EDDI personalities could be organized and shared?

## How it can happen
Probably a few ways to do this but maybe a repo using pull requests or issues as a way to contribute?

**Comment by Tkael** [comment]
Anyone who likes is free to open a repo and post a script or personality with versioning controls. 

I haven't announced it yet but the community is also free to take advantage of Github's `Discussions` feature (https://github.com/EDCD/EDDI/discussions).
