### ISSUE TITLE
TTS static/crackle

### ISSUE THREAD

**Issue by Californ1a** [EDCD/EDDI#2128]
## What's Wrong (please be as specific as possible)
There's some distinct static sounds during TTS voices even with voice processing turned all the way down/off.

### Expected
It shouldn't have static or crackle just like the default voices in Window's sound settings don't.

### Observed
https://www.youtube.com/watch?v=jpuNKGw_lyw
Listen specifically to the start of the word "how", there's a large crackle in the audio when starting to pronounce it, which doesn't happen when I go to Window's speech settings and preview the voice there:
https://www.youtube.com/watch?v=pQ207JZ_3U4
I also don't have this issue with EDDiscovery's TTS, using the same voice (though their own effects implementation):
https://www.youtube.com/watch?v=QpQHnI8W9Wk

### Configuration
* Version
  * EDDI Version: 3.7.2
  * VoiceAttack Version: N/A, though it happens in VA too with 1.8.7
* Localization
  * EDDI's language: English
  * Voice: Zira & David

**Comment by Tkael** [comment]
Replicated with MS Zira (only while wearing headphones, the PC speakers don't crackle for me). Not very much but definitely there. Hmm...

**Comment by Tkael** [comment]
It still occurs when bypassing all effects. 
Outputting to a memory stream seems to be the issue. 
Outputting directly to speakers does not have the same crackle but prevents adding effects.
It might have to do with encoding from the memory stream to a .wav for playback?

**Comment by cpypcy** [comment]
TTS does not work for me at all. I can hear some feint ineligible noise.

**Comment by Tkael** [comment]
Closing as a very minor issue which would take significant work to correct and has no clear path to resolution.
