### ISSUE TITLE
"Charlie" and "three" mispronounced

### ISSUE THREAD

**Issue by Californ1a** [EDCD/EDDI#2129]
## What's Wrong (please be as specific as possible)
When "disable phonetic speech" is enabled, "three" is mispronounced as "tree", and when "disable phonetic speech" is disabled, both "charlie" and "three" are mispronounced as "chalie" and "tree".

### Expected
The correct pronunciations

### Observed
0:33 - with "disabled phonetic speech" enabled, "charlie" is fine, but "three" gets pronounced as "tree":
https://youtu.be/EsM-lA_bCCA?t=33
3:25 - with "disable phonetic speech" disabled, "charlie" gets pronounced as "chalie" and "three" as "tree":
https://youtu.be/EsM-lA_bCCA?t=205

### Steps to reproduce
1. Enable/disable phonetic speech with Zira or David.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.2
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Zira & David

**Comment by Tkael** [comment]
"charlie" - agreed, the "R" is a little too soft when we apply our phonetics. I'll tweak the IPA driving that.

"3" - "Tree" is actually 100% correct for ICAO pronunciation. See https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

**Comment by Californ1a** [comment]
> "3" - "Tree" is actually 100% correct for ICAO pronunciation.

TIL, thanks. Still bugs me. I like having it on for the letters, and none of the other numbers sounded too different, but 3 got kind of annoying; I had to just turn off ICAO. Would be nice to have separate toggles for letters and numbers, or some way to manually tweak the pronunciations for each.
