### ISSUE TITLE
Star age is reported incorrectly on direct scans. 

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#213]
## Steps to reproduce

1. Reset your `Star report` script to the default
2. Scan star `Dryo Aob EG-Y g26 AB 1` (link [here](https://www.edsm.net/en/system/bodies/id/18087772/name/Dryo+Aob+EG-Y+g26/details/idB/9644322/nameB/Dryo+Aob+EG-Y+g26+AB+1))

## Expected
The star should be reported as being 16 million years old.

## Observed
Actual output: `Scan of TTS-class star completed. Dryo Aob E G dash Y g 26 A B 1 is a T tauri star in the process of gravitational contraction of 16 trillion years making it one of the oldest stars in the galaxy.`

## Investigation
16 trillion = 16 (age from the journal in millions of years) * 1 million * 1 million
We updated the script to handle the way age is reported from the server by multiplying by 1,000,000 there, but the age reported from the journal is already multiplied by 1,000,000 so it's compounding.

**Comment by Tkael** [comment]
Pull request submitted with a fix.

**Comment by richardbuckle** [comment]
Fixed for 2.4.4.
