### ISSUE TITLE
EDSM plugin config

### ISSUE THREAD

**Issue by Californ1a** [EDCD/EDDI#2130]
## What happens now
The EDSM plugin is either completely enabled or disabled with no config.

## What I'd like to happen 
* Be able to individually enable/disable sending to or reading from EDSM, so if you use multiple third-party tools at the same time, you can still allow EDDI to read from EDSM for missed info if you have something else sending to EDSM.
* Be able to config how often it sends to EDSM, if send is enabled.

It's probably a very specific use-case, but here's the full info:

Personally, I run EDDiscovery at the same time (mostly for the neat overlays) and you can [individually disable sending to or reading from EDSM in EDDiscovery](https://i.imgur.com/nAApMay.png). So I *could* enable the EDSM plugin in EDDI and have EDDiscovery set to only read from EDSM (not send to), but EDDI seems to not send logs to EDSM very quickly compared to EDDiscovery.

This is a problem because I like to have [EDSM's dashboard](https://www.edsm.net/en/dashboard) open while exploring since it [shows bodies worth mapping as you scan](https://i.imgur.com/uT06cb9.png) (42% of bodies discovered in this system, 1 so far worth mapping), which goes very well alongside EDDI's "bodies to map" speech, but oftentimes EDDI won't send new scan entries to EDSM until after multiple of the dashboard's auto-refresh times. With EDDI's EDSM plugin enabled, I have to wait for the dashboard to auto-refresh twice or sometimes 3 times after finishing every system scan, compared to when EDDiscovery is sending to EDSM, EDSM's dashboard shows new entries much more frequently; less waiting.

This means I have to disable EDDI's EDSM plugin entirely since EDDiscovery is sending data to EDSM (so EDSM doesn't get duplicate info), instead of being able to leave EDDI's EDSM plugin enabled but set to only read missed jumps (if, for example, I forgot to open it until after a few jumps) instead of sending new ones.

With the EDSM plugin disabled, if I did forget to open it for a few jumps and then went back to revisit those systems again, EDDI TTS would say it's my first visit to that system even though I already have them logged in EDSM, but EDDI isn't reading from EDSM with the plugin disabled to be able to get those few missed jumps (or an entire play session if it was on a different PC without my full setup or something like that).

## EDDI Version
3.7.2

**Comment by Tkael** [comment]
🤔 We currently batch messages to EDSM and send about once per minute (with the intent of keeping the EDSM dashboard reasonably up to date without hammering the server). As you've found, this may lag behind a bit if you're expecting real-time updates.

EDSM's dashboard currently updates every 10s. To keep up with the dashboard we would probably ideally need to reduce our send interval to no more than ~5s. That would increase the load on EDSM's servers, and EDSM's servers are already sometimes under very heavy strain.

**Comment by Tkael** [comment]
Anthor has given the all-clear to increase our send frequency.
