### ISSUE TITLE
Guardian Material discovered: no material type in MaterialDetails()

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2133]
### Expected
Using MaterialDetails(), Guardian materials should have the '.category' variable correctly populated with 'Manufactured'.

### Observed
The '.category' variable contains a long line of various 'Material' variables.

### Steps to reproduce
1. Create a script that will work in the 'Material discovered' and/or 'Material collected' events.
2. Collect a Guardian material.
3. Listen to the output of the 'Material discovered/collected' scripts.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v3.7.2
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Ivona Amy

### Investigation Notes
Yesterday I decided to try for some Guardian modules and headed to a Guardian site.  This is the first time I've tried for these and so all materials are new to me.  When collecting new mats, I have created scripts for the 'Material discovered' and 'Material collected' events, as the defaults are empty.

On collecting the Guardian mats, I am getting an 'error' (if it can be called that) where some speech should be happening, but isn't.  Both scripts should be saying the material type; its '.category' of 'Manufactured'.  When discovering (or collecting) mats in the past, this has worked fine.

This is my 'discovered' script:

```
{_ Context _}
{SetState('eddi_context_last_subject', 'material')}
{SetState('eddi_context_last_action', 'discover')}
{SetState('eddi_context_material_name', event.name)}

{set matis to MaterialDetails(event.name)}

{Occasionally(2, "You have")} Discovered {P(matis.name)},
{Occasionally(2, "this is")}
{if matis.rarity.name = "unknown":an |else: a}
{matis.rarity.name}

{if matis.category = "Data":
    {OneOf("data set", "set of data", "data scan")}
|elif matis.category = "Element":
    element
|elif matis.category = "Manufactured":
    manufactured {OneOf("item", "component")}
|elif matis.category = "Unknown":
    {set type to slice(matis.name, 0, 7)}
    {if type = "ancient":
        ancient alien data
    |else:
        {matis.name}
    }
}.
```

The problem I am having is that the Guardian mats have no material type.  Looking at the Journal entries, it should be 'Manufactured'.  After the first couple, I added a test line to dump the contents of the variable: `{dump(matis.category)}` (added to the end of the 'Material collected' script).  This is the result I got (copied directly from the speechresponder.out file):
`["edname": "Manufactured", "basename": "Manufactured", "invariantName": "Manufactured", "fallbackLocalizedName": , "localizedName": "Manufactured", "name": "Manufactured"]`

I have a feeling that isn't what is supposed to be in the '.category' variable, and is why my scripts are failing to vocalise the material type.  Is this some failure of the MaterialDetails() function for Guardian items?

For reference, my 'Material collected' script:

```
{_ Context _}
{SetState('eddi_context_last_subject', 'material')}
{SetState('eddi_context_last_action', 'collect')}
{SetState('eddi_context_material_name', event.name)}

{_ Function to obtain a material from inventory _}
{set _inventory(required) to:
    {for material in materials:
        {if material.material = required:
            {return material}
        }
    }
}

{set matis to MaterialDetails(event.name)}

{OneOf("{matis.name} {OneOf('Received', 'Collected', 'Ob-tained')}",
       "{OneOf('Received', 'Collected', 'Ob-tained')} {matis.name}")}.

{if matis.category = "Data":
    {if matis.rarity.level > 3:
        {Occasionally(2, "This is")}
        a {matis.rarity.name} {OneOf("data set", "set of data", "data scan")}.
    }
|elif matis.category = "Element":

|elif matis.category = "Manufactured":
    {if matis.name = "unknownenergysource":
        {_ Unknown Artifact Fragment _}
    |else:
        {Occasionally(2, "This is")}
        a manufactured {OneOf("item", "component")}
    }
|elif matis.category = "Unknown":
    {Occasionally(2, "This is")}
    {set type to slice(matis.name, 0, 7)}
    {if type = "ancient":
        ancient alien data
    |else:
        {matis.name}
    }
}

{set inventory to _inventory(event.name)}
{if inventory.maximum = inventory.amount:
    You have reached your maximum capacity.
|elif inventory && inventory.amount > 0:
    {Occasionally(2, "You have {inventory.amount} {if inventory.amount = 1: unit |else: units}
                      {OneOf('on board', 'in your inventory', 'in your storage')}.")}
}
```

As a side note, I have "Unknown" in the script because way back when all the Thargoid and Guardian stuff was just starting, I used that for the unknown alien artifacts we could collect.

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
My Journal entries for the first few instances:

```
{ "timestamp":"2021-03-13T14:25:11Z", "event":"MaterialDiscovered", "Category":"Manufactured", "Name":"guardian_sentinel_weaponparts", "Name_Localised":"Guardian Sentinel Weapon Parts", "DiscoveryNumber":51 }
{ "timestamp":"2021-03-13T14:25:11Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_sentinel_weaponparts", "Name_Localised":"Guardian Sentinel Weapon Parts", "Count":3 }
{ "timestamp":"2021-03-13T14:25:31Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_sentinel_weaponparts", "Name_Localised":"Guardian Sentinel Weapon Parts", "Count":3 }
{ "timestamp":"2021-03-13T14:25:45Z", "event":"MaterialDiscovered", "Category":"Manufactured", "Name":"guardian_powerconduit", "Name_Localised":"Guardian Power Conduit", "DiscoveryNumber":52 }
{ "timestamp":"2021-03-13T14:25:45Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_powerconduit", "Name_Localised":"Guardian Power Conduit", "Count":3 }
{ "timestamp":"2021-03-13T14:31:05Z", "event":"MaterialDiscovered", "Category":"Manufactured", "Name":"guardian_techcomponent", "Name_Localised":"Guardian Technology Component", "DiscoveryNumber":53 }
{ "timestamp":"2021-03-13T14:31:05Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_techcomponent", "Name_Localised":"Guardian Technology Component", "Count":3 }
{ "timestamp":"2021-03-13T14:35:29Z", "event":"MaterialDiscovered", "Category":"Manufactured", "Name":"guardian_powercell", "Name_Localised":"Guardian Power Cell", "DiscoveryNumber":54 }
{ "timestamp":"2021-03-13T14:35:29Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_powercell", "Name_Localised":"Guardian Power Cell", "Count":3 }
{ "timestamp":"2021-03-13T14:38:56Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"guardian_techcomponent", "Name_Localised":"Guardian Technology Component", "Count":3 }

```

The resulting speechresponder.out entries from using my scripts:

```
You have Discovered Guardian Sentinel Weapon Parts, a standard.
Guardian Sentinel Weapon Parts Received. You have 3 units in your inventory.
Guardian Sentinel Weapon Parts Ob-tained. You have 6 units in your inventory.
You have Discovered Guardian Power Conduit, a common.
Ob-tained Guardian Power Conduit.
Discovered Guardian Technology Component, this is a standard.
Collected Guardian Technology Component.
You have Discovered Guardian Power Cell, a very common.
Guardian Power Cell Ob-tained.
Guardian Technology Component Collected. You have 6 units on board.  ["edname": "Manufactured", "basename": "Manufactured", "invariantName": "Manufactured", "fallbackLocalizedName": , "localizedName": "Manufactured", "name": "Manufactured"]
```

**Comment by Darkcyde13** [comment]
Hmm, I just tried the same with the Guardian pattern obelisk data.  A dump() of those produces this:
`["edname": "Data", "basename": "Data", "invariantName": "Data", "fallbackLocalizedName": , "localizedName": "Data", "name": "Data"]`
Shouldn't this just be 'Data'?  It makes me wonder if I've just been missing that '.category' hasn't been working for a while on anything and I've just not noticed until now.  When I get back to Human space, I'll give mats and data another go to check.

**Comment by Tkael** [comment]
Looks like back in 2018 someone replaced the `category` string with a `category` object. We can fix that for the next release. o7
