### ISSUE TITLE
Phonetic Issue

### ISSUE THREAD

**Issue by feiercrack** [EDCD/EDDI#2141]
## What's Wrong (please be as specific as possible)
My CMDR Name is wrong pronounced
### Expected
[Describe what you expected to happen]
I expect an correct pronouncement
### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
My CMDR Name is wrong pronounced
### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
Open EDDI v3.7.2
Click on Commander Details, then click on "Hear it" 
Remove Feiercrack, insert faɪɚ     <--- absolutely no changes, it still says: Favorcrack
My Name sounds like IPA fAY-vuhr  and not IPA faɪɚ 
2. [The more reproducible, the better our chances of fixing it]
see above
### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  3.7.2.
  * VoiceAttack Version: [if applicable] 1.87
* Localization [if applicable] 
  Germany, german and english language completely installed, Zira selected
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] 
  English
  * Voice: [Name and language] 
  MS-Zira English

## My Investigation
dont understand.. see above
### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]
dont understand.. see above
[user.zip](https://github.com/EDCD/EDDI/files/6167077/user.zip)

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]
[Journal.210318205657.01.log.zip](https://github.com/EDCD/EDDI/files/6167082/Journal.210318205657.01.log.zip)

**Comment by Tkael** [comment]
I'm trying to replicate your report but I don't seem to be getting the same result?
https://user-images.githubusercontent.com/4382539/111868579-fade2080-8937-11eb-81a8-8aeca93c3ac4.mp4

**Comment by Darkcyde13** [comment]
I'm getting the exact same as @Tkael.  It sounds as I would expect it to.

I do note, however, that the MS Zira voice is American English, not British English.  The word "fire" as spoken in these tests has a very American accent to it, so it doesn't sound 'right' to us Brits. ;)  While it doesn't quite sound like "fAY-vuhr" to me, I can see why it doesn't sound like "fire" (from my British point of view) either.

Now, using MS Hazel and Ivona Amy (both British English) "faɪɚ" is quite clearly "fire" in a British accent.  Is it possible that it's the American accent that is making it sound 'wrong' for you?

For me, using Ivona Amy, there are times when that has trouble pronouncing some words for me.  When it comes to voices and accents, I've noticed that two people can say the same word in slightly different ways and we don't notice (we kinda filter that out), but we are very aware when a computer voice says something slightly differently.  My name, dɑrkˈsaɪd, sounds slightly different between MS Hazel and Ivona Amy, so I think a lot comes down to which voice you use, as well as what you want it to say.

**Comment by Tkael** [comment]
@feiercrack I'm not sure how to help further - I've been unable to replicate the ticket.

**Comment by Tkael** [comment]
Closing due to inability to replicate.
