### ISSUE TITLE
Ability to use multiple voices for message received event

### ISSUE THREAD

**Issue by Californ1a** [EDCD/EDDI#2146]
## What happens now
Right now everything is read out by the same voice with the same effects added.

## What I'd like to happen 
It would be really cool if it was possible to have different voices and/or different effects applied (pitch shift or whatever else) so NPC (or player) text is read out as if they're coming from someone else. Then instead of TTS saying "From NPC whoever: message" it could just read out the message as if someone else was actually on comms with you.

## How it can happen
Select which of the installed voices you want to be included in the message received event, and config a min/max pitch shift or other effects.

## EDDI Version
3.7.2

**Comment by Tkael** [comment]
Have you examined the options already available?
- [SpeechPitch](https://github.com/EDCD/EDDI/wiki/Help#speechpitch)
- [SpeechRate](https://github.com/EDCD/EDDI/wiki/Help#speechrate)
- [SpeechVolume](https://github.com/EDCD/EDDI/wiki/Help#speechvolume)
- [Transmit](https://github.com/EDCD/EDDI/wiki/Help#transmit)
- [Voice](https://github.com/EDCD/EDDI/wiki/Help#voice)

**Comment by Californ1a** [comment]
Ah, I must have missed that page, looks like it isn't linked on the main [Home](/EDCD/EDDI/wiki) wiki page, and is a little hidden under the [Functions](/EDCD/EDDI/wiki/Functions) subpage (detailed documentation link). Thanks.
