### ISSUE TITLE
Clicking "OK" on the Edit window de-selects the edited script in the list.

### ISSUE THREAD

**Issue by parduz** [EDCD/EDDI#2154]
## What's Wrong (please be as specific as possible)
When you click on a script, or on a script button, in the scripts list, the whole line becomes "Selected". It remains selected if you click on "show" and then "ok" on the "show" window, and if you click on "edit" and then on "cancel".
BUT if you click on "edit" and then on "OK" the item in the list will become unselected.

### Expected
The list should keep the selected items.

### Steps to reproduce
1. Click on a script, note it becomes selected. 
2. click on the "Edit" button
3. in the Edit window, click on the "OK" button.
4. the edited script is no more selected.

### Configuration
* Version 
  * EDDI Version: 3.7.3
* Localization 
  * EDDI's language: Windows 10, italian
  * Voice: IVONA 2 Carla, italian.

**Comment by Tkael** [comment]
I agree that the refreshed list no longer highlights (or perhaps never did highlight?) the prior selection, but I'm not sure I understand the problem that you are trying to resolve. Why is the current behavior bad?

**Comment by parduz** [comment]
> I agree that the refreshed list no longer highlights the prior selection, but I'm not sure I understand the problem that you are trying to resolve.

In my case. while "mass-editing" (translating) i loose the "reference" of what script i've just edited.

> Why is the current behavior bad?

It's a really minor issue, i agree. But it's the only exception to the "normal" behaviour, which is to keep the item highlighted :)
