### ISSUE TITLE
It's impossible to comment out a whole line of code in the Script editor

### ISSUE THREAD

**Issue by parduz** [EDCD/EDDI#2155]
## What's Wrong (please be as specific as possible)

Suppose that this is a line in a script: `{Humanise(1)} {Pause(500)} 1.`  i can't comment it out like `{_ {Humanise(1)} {Pause(500)} 1.}`. The parser (and the syntax highlighter) "closes" the comment at the first `}` and then throws (and shows) errors on the text after it.

### Expected
The "comment section" should finish at the corresponding closing bracket, not at the first one.

### Configuration
* Version 
  * EDDI Version: 3.7.3

**Comment by Tkael** [comment]
It's possible to do this, but not without applying the escape character `\` to the interior curly brackets:
```
{_ \{Humanise(1)\} \{Pause(500)\} 1.}
```

**Comment by Tkael** [comment]
Ref. https://cottle.readthedocs.io/en/stable/page/02-language.html?highlight=delimiters#command-delimiters

**Comment by richardbuckle** [comment]
Closing as invalid.
