### ISSUE TITLE
Disabled "Message received" but messages are still read aloud

### ISSUE THREAD

**Issue by dylan-k** [EDCD/EDDI#2176]
I wanted to prevent EDDI from reading messages because I use a different app for that, but when I disabled the "Message received" rule, and even when I edited it and deleted its contents, the messages were still voiced.

### Expected
If "Message received" rule is disabled, should it prevent messages from being read aloud?

### Observed
EDDI didn't seem to respond to these changes in the settings.

### Steps to reproduce
1. uncheck "Message received"
2. Recieve a message, in my case it was a Squadron chat message that I could still hear
3. EDDI will read it aloud even though the setting is disabled

### Configuration
  * EDDI Version:  3.7.3
  * installed via Voiceattack

**Comment by Tkael** [comment]
That sounds like it should work. Are you sure that EDDI is the only app running that might be reading the message?

**Comment by dylan-k** [comment]
I am sure it's the only app running, but here's an update. It worked for me when both (a) the option is enabled but (b) i've edited its text to be blank. If I disable the option though, the messages are voiced incorrectly. 

So in other words I got it to work for me, at least. I suppose if nobody else can replicate this we can close the issue, but I thought to share the experience fwiw.

**Comment by Tkael** [comment]
Closing due to inability to replicate. In my testing, I found that disabling a script does suffice to prevent that script from being executed (even when the script contents are not blank).
