### ISSUE TITLE
EDDI 3.7.3 cant connect to update server

### ISSUE THREAD

**Issue by Handlyhanden** [EDCD/EDDI#2177]
Hi all I am getting an an error when starting EDDI. It is telling me that it cant connect to update server. The program still runs ok but I am not to sure what it meens. Is there any one that does know?

**Comment by Tkael** [comment]
This means that an error occurred while checking for a newer version of EDDI.
The most likely reason that this might occur would be if there is a network settings issue preventing EDDI from connecting to the version page at https://edcd.github.io/EDDP/. There may be additional details in your .log files in `%APPDATA%/EDDI/`.

**Comment by Handlyhanden** [comment]
Hi and thanks for your swift reply to my question. I have had a poke around in the appdata and it looks as though the problem is with ssl/tsl authentication. not to sure how this has happend but I will have a look and report later. many thanks.

**Comment by Handlyhanden** [comment]
Hi all I have not been able to find a solution for my EDDI problem just yet so I thought that maybe if I add my appdata file it may be a little clearer to some one smarter tham me.
[eddi.log](https://github.com/EDCD/EDDI/files/6546115/eddi.log)
Hopefully this will give some one a clue.
   Many thanks

**Comment by Tkael** [comment]
If you're running a very old version of Windows then it may not support modern networking protocols?
