### ISSUE TITLE
Jumped script missing check

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2179]
I've finally had some time to go through all the new updates to EDDI and have come across a couple of minor errors in some scripts. As discussed in the past, I'll open a new ticket for each one. These are all from the latest v4.0.0-b3.

In the Jumped script, line 55 says:
`{if state_report || system_missions || (system_crimes && find(system_crimes, "Warning") < 0):`

This is missing the check for the new 'system_engineer' report.  Line 55 should say:
`{if state_report || system_engineer || system_missions || (system_crimes && find(system_crimes, "Warning") < 0):`

This will then correctly voice the engineer report, even if none of the others reports are to be spoken.

**Comment by Tkael** [comment]
It wouldn't prevent the engineer report from being voiced but it would prevent "Information:" from being voiced. 
In any case, it's not the intended behavior and I appreciate the feedback. o7
