### ISSUE TITLE
Number of signal sources

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2181]
## What's Wrong 
When I call SystemDetails I get only one source when in fact there are more than one, but they are all the same type.

{set currentSystem to SystemDetails(state.eddi_context_system_name)}
{set sources to currentSystem.signalsources}

Is this expected behaviour? If so, how can I determine the total number of signal sources?

### Expected
Expected to get the total number of signal sources.

### Configuration
* Version 
  * EDDI 3.7.3

**Comment by Tkael** [comment]
This is intentional. Each signal source is recorded in the player journal as a discrete event so when we start processing signal sources we don't know how many we'll be receiving. The default script handles this by only responding to unique signal types unless you're in fss or saa mode.
