### ISSUE TITLE
Documentation for Role object missing

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2182]
The description for the Role object is missing from the documentation. From the example scripts I can see that there is an 'edname' field. Anything else? Also some scripts access the edname field and others just access the object directly.

**Comment by Tkael** [comment]
`{ship.role}` is a string containing the localized name of the role assigned to the ship. 

`{ship.Role}` is a backing object for internationalizing the variables contents. It can be used to access the localized name (`ship.Role.name`), the invariant name (`ship.Role.invariantName`), or in rare cases the symbolic name (`ship.Role.edname`) used in the player journal. There is no other data available from the object. By accessing the invariant or edname forms of a name, we're able to ensure that a script works consistently even after EDDI's UI and standard variables (like `{ship.role}`) are localized for a non-English language.

Typically, a user customizing their own personality would simply use the documented `{ship.role}` (equivalent to `ship.Role.name`) to return the localized role assigned to the ship.
