### ISSUE TITLE
((EDDI under attack)) on foot bug

### ISSUE THREAD

**Issue by Orgamorsh** [EDCD/EDDI#2183]
## What's Wrong 
When on foot. This event plays every single time you get shot. This causes the event to be spammed.

### Expected
The event plays on first shot. Similarly to when the event plays in a ship.

### Observed
When on foot. This event plays every single time you get shot. This causes the event to be spammed when shot with automatic weapons or when fighting multiple targets.

### Steps to reproduce
1. Make a ((EDDI under attack)) event in Voice Attack.
2. Start an on foot engagement.

### Configuration
* Versions
  * EDDI Version: EDDI 4.0.0-b3
  * VoiceAttack Version: v1.8.7 - Steam

**Comment by Tkael** [comment]
This isn't exactly a bug - nothing about how this event functions has changed. We're responding to the event whenever it's written to the player journal and it happens to be written much more often often while we're in combat on foot. We've commented on this to FDev but there is no guarantee that FDev will take action to modify this. 

I have a couple of ideas for potentially mitigating this but don't want to over-promise before I've been able to prove my ideas out.
