### ISSUE TITLE
Crime report not correctly reporting systems_bounties

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2184]
In EDDI v4.0.0-b3, for the 'Crime report' script, I've noticed that 'systems_bounties' is calculated, but then never used.  I mentioned something about this in #1656 where I noted that line 42 incorrectly uses the length of 'factions_bounties', instead of 'systems_bounties' to set 'systems_count', but it seems this has been overlooked and not yet fixed.

Looking into this a little deeper, I've noticed that line 18 is incorrect.  The two variables have been swapped around.
`{if find(presence.systemName, systems_bounties) = -1:`
This should be:
`{if find(systems_bounties, presence.systemName) = -1:`
The array of 'systems_bounties' should be checked for the presence of 'presence.systemName', not 'presence.systemName' being checked for 'systems_bounties'.

Making this change, and the change I noted in #1656 (making line 42 `{set systems_count to len(systems_bounties)}` ), makes the report function correctly.

I only noticed this because I was being told I was wanted in zero systems (with my original fix):

> You are wanted by 1 faction in 0 systems for a total of 1,000 credits. You have 1 pending fine from 1 faction, for a total of 250 credits.

(With the default script, I'm told it's 1 faction in 1 system, but that's incorrect, as per below)

With the above changes, I am correctly told:

> You are wanted by 1 faction in 2 systems for a total of 1,000 credits. You have 1 pending fine from 1 faction, for a total of 250 credits.

I this case, I am wanted by League of Hrunapori  Liberty Party in both the Shambogi and Hrunapori systems.  I don't really break the law at all, so I never noticed until today, when I got caught walking around a base I shouldn't have been. ;)

**Comment by Tkael** [comment]
Good catches. Sorry I missed that on #1656. o7
