### ISSUE TITLE
On-foot missions not cleared from the mission log

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2187]
### Expected
On-foot missions to be removed from the mission log when completed.

### Observed
The on-foot mission remains in the log, and can't be removed.

### Steps to reproduce
1. Take an on-foot mission.
2. Complete the mission.
3. Return to the mission giver, and hand it in.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.0.-b3
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Ivona Amy

### Investigation Notes
I noticed nothing was said when I handed in my on-foot mission.  So, I looked at the mission log and the mission is still there.  When checking the Player Journal, there is no entry for completing the mission, and so there is no way for EDDI to know it's been completed to be removed from the log.  I don't know if this is intended by FDev, or a bug that an entry is missing.

Unless I'm missing something somewhere, I can't see any way to manually remove the mission from the log.  So my completed mission will stay in the log, saying 'Active', at least until it expires in a few days.

Could an option to remove missions be added to the mission log tab please?

### EDDI Logs
None.

### Player journals
The only entry in the Journal for the time I handed the mission in, is the one for NPC crew wage being paid.

**Comment by Tkael** [comment]
There seems to be a server transaction error that can occur in Odyssey that can make completed missions fail to fully resolve. This is resolved both in game and in EDDI as soon as you re-log.

I don't expect the server transaction error to remain unresolved for long and the missions will be resolved in EDDI as soon as you re-log or FDev corrects the transaction error. Consequently, I would suggest that you re-log when you encounter mission transaction errors like you're describing for the time being.

**Comment by Tkael** [comment]
I believe [this issue](https://issues.frontierstore.net/issue-detail/35768) in the tracker may describe what you're seeing? If so, please add your vote.

**Comment by Darkcyde13** [comment]
> I believe [this issue](https://issues.frontierstore.net/issue-detail/35768) in the tracker may describe what you're seeing? If so, please add your vote.

Hmm, no, that's not quite it.  My mission did complete properly and was removed from my transactions tab as expected.  Those in that tracker issue are all about missions that didn't complete properly.

Still, as you say, EDDI has removed it from my missions log after restarting it.  So now that I know, it's not really a problem for me when it happens again.  Thanks for looking into it though. :)
