### ISSUE TITLE
Minor issue: New events have delete button

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2190]
## What's Wrong (please be as specific as possible)
When the voice responders are listed, the new events added by 4.0.0-rc1 (Backpack, backpack changed) have a delete button as if the system thinks that the are user added scripts.

### Expected
They should have a disabled (Greyed) reset button as they are blank scripts that match the default script. I have not customised them yet.

### Observed
Delete buttons shown

### Steps to reproduce
1. Open EDDI
2. Display speech responders

### Configuration
* Version 4.0.0-rc1

**Comment by Tkael** [comment]
Nice catch. I'll check it out this evening.
