### ISSUE TITLE
'Community Goal' Event: Add

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#22]

**Comment by Tkael** [comment]
see branch. currently bugged

**Comment by Tkael** [comment]
Bugs appear to be resolved (using test script). Will mark as closed once I've had a chance to test in-game.

**Comment by Tkael** [comment]
Tested & resolved bugs (see pull request #113). Good to go!

**Comment by richardbuckle** [comment]
Working for me. Nice job.
