### ISSUE TITLE
Please shut down VoiceAttack and run EDDI standalone to upgrade - no upgrade available.

### ISSUE THREAD

**Issue by Al-Katraz** [EDCD/EDDI#2200]
Is this a nuisance or misconfiguration?
I have downloaded and reinstalled EDDI.

1:47:10.972 Plugin 'EDDI 3.7.3' initialized.
1:47:10.948 The EDDI plugin is fully operational.
1:47:10.836 Please shut down VoiceAttack and run EDDI standalone to upgrade
1:47:10.831 Loading customiser settings...
1:47:10.831 Initialising, please wait...
1:47:10.831 Listening suspended
1:47:10.217 VoiceAttack profile - (c) 2017-2021 HCS VoicePacks Ltd
1:47:10.217 Singularity v2.5.1 - VoiceAttack v1.8.8
1:47:09.202 Plugin 'HCS Plugin v3.6.7 - (c) 2016-2021 HCS VoicePacks Ltd' initialized.
1:47:08.209 Plugin support enabled.

**Comment by Tkael** [comment]
You seem to still be running an old version of EDDI with the plugin. Please check the install location for EDDI? You might have the older version in VoiceAttack's app directory and a newer version installed elsewhere on your PC?

**Comment by Al-Katraz** [comment]
Brian,
As always, when I try to document anything it magically starts working
fine.  I had removed the keypad after it stopped working, - pluging it back
in for the 20th (our phone conversation was #19) time and now it works
fine(?).
If the problem returns, I assume I am covered since it was reported within
the 5 days ?

Thanks

V/R

Roger I. Braden

**Comment by Al-Katraz** [comment]
You are correct - weird that - fixed - thanks!
