### ISSUE TITLE
Reading the news get (rudely) interrupted by any other messages

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#2201]
## What's Wrong (please be as specific as possible)
When using VoiceAttack and using the 'read the news' command, the news properly starts to be read. Then, on any kind of state change, like a hyperspace jump, the readback stops. What is worse: the article being read back is marked as read and you can't make reading resume in a straightforward manner. I always used to love having the news articles read while traveling.

### Expected
News keeps being read until the entire article is finished, even with jumps, real space drop and such.

### Observed
Many events seem to cut the readback short, such a hyperspace jump, supercruise drop.

### Steps to reproduce
1. Use the 'Read the news' command in VoiceAttack
2. Jump to another start system. The news readback will be cut off

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.0 
  * VoiceAttack Version: 1,8,8 64-bit
* Localization [if applicable]
  * EDDI's language: US-EN
  * Voice: Verity EN

**Comment by Tkael** [comment]
Issue found, thanks for reporting. 

Until the fix for this is released, I would suggest that you add a line to [manually set the priority parameter](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#speech).
