### ISSUE TITLE
Could SetState be extended to handle map variables

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2205]
## What happens now
Currently the SetState function handles numbers, booleans and strings, but not maps. Presumably because it is a little more complex than the others. The function seems to teat maps as if it were a string. So if I Call SetState(fred, ["a", "b", "c"]) and then dump type(state.fred), it tells me it is a string.

## What I'd like to happen 
It would be useful so that, for example, I can store the bodies that I have visited so that later on I can check whether I have landed on a body yet or not. I suppose I could create a concatenated string and then use regex to separate them out again. Not used regex before. It sounds complex.  Any examples?

## How it can happen
I'm not sure how the persistence is implemented, so I could not comment.

## EDDI Version
4.0.0

**Comment by Darkcyde13** [comment]
When I first needed to store arrays using SetState(), I made it into a string and separated the array elements using "+=" (I chose this as it's unlikely to occur naturally).  Now I use this all the time.

Set your array to a string using a separator:
`{set array_name to join(your_map, "+=")}`
So, ["a", "b", "c"] becomes "a+=b+=c".

Then store it as normal:
`{SetState('store_array', array_name)}`

When I need to use it again, just split it back up:
`{set array_name to spilt(state.store_array, "+=")}`
This comes back out as ["a", "b", "c"] again.

The only downside to this is that it doesn't keep map keys, only the data element. Although, you could probably do some juggling by flipping the key:data pairs and storing the keys as a second State variable if you really need them.  Most of the time though, I doubt you'd need the keys, as most people only use arrays to store the data parts.

Edit:  The other thing to note is that numbers will no longer be digits, they will come back out again as text characters (type = string).  You would then need to convert them back to digits using the cast() function.  However, if you're only going to store system and planet names, this shouldn't be a problem.

**Comment by Tkael** [comment]
- `{SetState("fred", ["a", "b", "c"])}` as a string value is `""`. ;-)
- The `Galnet news published` and `Message received` scripts demo Cottle's Regex `match` function.

In addition to storing values between events, `SetState()` acts a bridge between VoiceAttack and the Speech Responder. For that role, storing map values would be less than ideal. VoiceAttack does not permit values to be stored as maps so if we were to make this change then we'd have to walk the object and individually store the values at each node in the map using a dynamic auto-generated key (which the user would then have to correctly guess to access those variables in VoiceAttack). Not ideal. If we were to implement this then it would essentially need to be a Cottle-only feature.

**Comment by TribbleTrouble** [comment]
> When I first needed to store arrays using SetState(), I made it into a string and separated the array elements using "+=" (I chose this as it's unlikely to occur naturally). Now I use this all the time.
> 
> Set your array to a string using a separator:
> `{set array_name to join(your_map, "+=")}`
> So, ["a", "b", "c"] becomes "a+=b+=c".
> 
> Then store it as normal:
> `{SetState('store_array', array_name)}`
> 
> When I need to use it again, just split it back up:
> `{set array_name to spilt(state.store_array, "+=")}`
> This comes back out as ["a", "b", "c"] again.
> 
> The only downside to this is that it doesn't keep map keys, only the data element. Although, you could probably do some juggling by flipping the key:data pairs and storing the keys as a second State variable if you really need them. Most of the time though, I doubt you'd need the keys, as most people only use arrays to store the data parts.
> 
> Edit: The other thing to note is that numbers will no longer be digits, they will come back out again as text characters (type = string). You would then need to convert them back to digits using the cast() function. However, if you're only going to store system and planet names, this shouldn't be a problem.

Thanks @Darkcyde13 . That works great.

**Comment by Tkael** [comment]
Closing as resolved for the time being with Darkcyde's suggestion.
