### ISSUE TITLE
Strange Test-2-Speech messages

### ISSUE THREAD

**Issue by Ragnar65** [EDCD/EDDI#2207]
Hi, since two weeks or so i get strange messages when entering a new system. They say something like "<shipname> has reached NTT xxxx system" or "Distance to NTT xxx system is yyy-Lightyears" Under Commander Details I have fixed Maridal as my home system. So i don´t know why "David" is talking of this NTT xxx-System...
Any suggestions how to fix this?

Rgds
Stefan
Cdr. Tech65 [GPL]

**Comment by Tkael** [comment]
You probably have a destination system set. Please open the Mission Monitor and click the `Clear Route` button to clear it.

**Comment by Tkael** [comment]
Closing as presumed resolved. Please respond if otherwise. o7 cmdr.
