### ISSUE TITLE
Ship monitor: Odyssey makes ships get reset 

### ISSUE THREAD

**Issue by mlmurphy70** [EDCD/EDDI#2208]
When switching ships while running the Elite Dangerous: Odyssey DLC, ships in the list below the ship you switch to seem to be reset or "forgotten".  Although their value seems to be retained, their IPA pronunciation is reset, as well as their Role, and their module configuration (they can no longer be exported to EDSY/Coriolis).

This behavior does not seem to happen when running Horizons.

### Steps to reproduce
1. Start Elite Dangerous: Odyssey
2. Switch ships.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.0
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Microsoft Zira Desktop

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/6706030/eddi.log)

### Player journals
[Journal.210622213532.01.log](https://github.com/EDCD/EDDI/files/6706041/Journal.210622213532.01.log)

**Comment by Tkael** [comment]
Hmm... I know that there are situations that can reset the ship monitor but I'm not sure that they are Horizons related. More likely, there may have been some file corruption making the ship monitor configuration unreadable and triggering a reset. 

The log files you provided give no indication that there was an issue, but I did identify a gap in the logging where if EDDI fails to read the configuration file it will EDDI silently discard the old configuration and create a new one without logging any issues. 

I'll improve the logging so that we can capture the circumstances around this better but unless you can restore the old version of your shipmonitor.json configuration (saved to %appdata%/EDDI) so that we can inspect it, that may be as far as we can go for the time being.

I know that's not what you want to hear and I apologize for the inconvenience. o7 commander.

**Comment by mlmurphy70** [comment]
Hey, not a problem - I just wanted to let you and anyone else who might be experiencing it know about the issue.  I can delete my shipmonitor.json and repopulate the data by just swapping to each of my ships, while I'm in Horizons.   I've done that once, though, and I'm pretty sure that even if I do this again, once I start playing in Odyssey again, the file will get corrupted again.

If there's anything I can do to help diagnose the issue further, just let me know!

**Comment by mlmurphy70** [comment]
Just in case it helps diagnose the issue: I deleted my shipmonitor.json file, started Horizons, and swapped to each of my 14 ships at Okinura.  I also set the Role for all of my ships.  Here's the new shipmonitor.json file (renamed to a .txt so GitHub will allow it to be attached).  As you can see, 14 of the 17 ships now have modules listed.

[shipmonitor.json.txt](https://github.com/EDCD/EDDI/files/6713441/shipmonitor.json.txt)

**Comment by mlmurphy70** [comment]
And here, I started in Odyssey with my shipmonitor.json file in the same state as the previous message, and did exactly one ship swap, from my Federal Corvette to my Imperial Courier.  As you can see, as soon as I swapped ships in Odyssey, everything below the Imperial Courier in the json file has now had its Role and module listing "reset".

[shipmonitor-ody.json.txt](https://github.com/EDCD/EDDI/files/6713461/shipmonitor-ody.json.txt)

**Comment by Tkael** [comment]
Looks like the Odyssey file is taking its latest data from the Frontier API and is not collecting very complete information. The Frontier API doesn't reset the IPA configuration, ship role, etc. however which suggests that something else is acting to remove that information. If you have multiple accounts for Elite Dangerous and your Frontier API isn't configured to match the active commander, that might create such a scenario. Likewise if something is corrupting your shipmonitor.json file.

If you could repeat your experiment and collect a verbose log for this then that would be quite helpful - I'm afraid the standard logging just isn't sufficient for this problem.

**Comment by Tkael** [comment]
Related to the above - if you sign out of the Frontier API then does the problem cease or persist?

**Comment by Tkael** [comment]
Possibly related: The "StoredShips" journal event can apparently now come up empty for ships stored in that station. That could certainly create a missing ships scenario...

Is it only ships docked at same station that are being reset?

**Comment by srguglielmo** [comment]
Hello! I am experiencing the same issue. The ship role and IPA pronunciation is being reset for all my ships (not just the ones stored at the same station). I noticed that even exiting EDDI and reopening EDDI, the values are lost/reset. This happens even if Elite isn't running.

- EDDI version 4.0.1-b1 (English, Microsoft Zira Desktop).
- ED Odyssey version: 4.0.0.600.
- ED Horizons version: Odyssey Compatibility Update 3.8.04.
- ED files validated via Steam.
- I have reset the Frontier API connection in EDDI (twice now).

Some more notes I took while debugging:

- When swapping ships, I occasionally hear EDDI say "You are carrying limpets but no limpet controller", which makes me think EDDI lost the ship module data (both ships in question _do_ have a limpet controller).
- When swapping ships, occasionally the entire ship disappears from EDDI (i.e. the row for the ship no longer exists). When I swap back, the ship reappears with the role reset to multipurpose and the custom IPA lost.

I have EDDI verbose debugging enabled with logs attached below. I don't see much relevant info, unfortunately.

The logs include: start EDDI, set ship role, quit EDDI, then restart EDDI and observe Ship Monitor role/ipa are reset.

FYI I am willing to run a special branch/build of EDDI to assist in debugging if needed.

Thank you!

[eddi1.log](https://github.com/EDCD/EDDI/files/6803342/eddi1.log)
[eddi.log](https://github.com/EDCD/EDDI/files/6803343/eddi.log)

**Comment by Tkael** [comment]
@srguglielmo EDDI version 4.0.1-b1 seems to have a bug with remembering ship roles specifically. I've added a fix for the next release. 

I have reason to believe that the `StoredShips` journal event bug should be fixed with update 6, though I don't know when that will actually drop.

**Comment by mlmurphy70** [comment]
Looks like you got that verbose log from someone else!  Sorry I didn't also submit one.

As you predicted, as of ED: Odyssey Update 6, I'm no longer able to reproduce this issue likely due to the `StoredShips` journal event bugfix you mentioned (how did you know that fix was coming!?).  Swapping ships correctly (re)populates the current ship's modules and no longer erases information on other ships.  As far as I'm concerned this bug could be closed.

**Comment by Tkael** [comment]
Thanks for the follow up. :-)
