### ISSUE TITLE
On Foot missions all called 'onfoot'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2209]
## What's Wrong (please be as specific as possible)
When dealing with on foot missions, EDDI lists them all as 'onfoot' rather than the actual mission type.
### Expected
EDDI to describe the type of mission it is. i.e. 'reactivation'.

### Observed
All on foot missions are simply described as 'onfoot'.

### Steps to reproduce
1. Accept/fail/hand in any on foot mission.
2. Observe that {MissionDetails(event.missionid).type} is always 'onfoot'.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1-b1
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: English UK
  * Voice: Ivona Amy
### Investigation Notes
As well as the Missions scripts, the Missions Monitor in EDDI lists the mission type as 'onfoot' too.  However, the Player Journal does specify what each on foot mission type is:
`{ "timestamp":"2021-06-27T15:10:43Z", "event":"MissionAccepted", "Faction":"Fatal Shadows", "Name":"Mission_OnFoot_RebootRestore_MB", "LocalisedName":"Restore: Prepare Bonfils Excavation Station for operation", "Commodity":"$LargeCapacityPowerRegulator_Name;", "Commodity_Localised":"Power Regulator", "Count":1, "Expiry":"2021-06-27T21:41:50Z", "Wing":false, "Influence":"+", "Reputation":"+", "Reward":126563, "MissionID":787559900 }`
In this case it's a reboot/restore, or just 'restore' as the localised name.

`{ "timestamp":"2021-06-27T13:56:21Z", "event":"MissionAccepted", "Faction":"Dingos of Duwali", "Name":"Mission_OnFoot_Reboot_MB", "LocalisedName":"Reactivation: Turn on power at Naudiyal's Find", "Commodity":"$LargeCapacityPowerRegulator_Name;", "Commodity_Localised":"Power Regulator", "Count":1, "Expiry":"2021-06-27T20:04:23Z", "Wing":false, "Influence":"++", "Reputation":"++", "Reward":177929, "MissionID":787538403 }`
This one is just reboot, or 'reactivation' localised.

### EDDI Logs
None

### Player journals
As above.

**Comment by Tkael** [comment]
I'm already aware of this - it's the current default state for the mission monitor for on-foot missions. 

I'd like to  refine the code on mission types, perhaps to indicate that it is both an On-Foot and a Reboot mission, but I've considered this to be a pretty low priority. In the meantime, I added the localized name of the mission as a tooltip to help distinguish missions from one another.

**Comment by Darkcyde13** [comment]
Hmm, how about making the type just like normal missions (so like 'Reboot') and then have a boolean for if it's on foot or not?  So, 'MissionDetails().onfoot' = True/False?  Then just have the scripts check for this.  Wouldn't that make translating scripts to include this easier too?

**Comment by Tkael** [comment]
There is a lot of information in the mission's symbolic name (e.g. "Mission_OnFoot_RebootRestore_MB") that isn't fully captured by the current mission type... information like the legal status of the mission, whether the passenger VIP that you're transporting is a criminal (e.g. "Mission_Sightseeing_Criminal_BOOM"), if the mission scenario is tied to a current faction state (e.g.  "Mission_PassengerVIP_Doctor_WAR"), if the massacre mission is tied to skimmer targets (e.g. "Mission_Massacre_Skimmer_Corporation"), etc. 

The thought it to try to bring more of this to the surface.
