### ISSUE TITLE
Status on_foot_in_station not set in Voice Attack

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2210]
## What's Wrong (please be as specific as possible)
The status variable on_foot_in_station is not set in Voice Attack
### Expected
The variable to be populated with True or False.

### Observed
The variable is 'Not set' in Voice Attack.

### Steps to reproduce
1. Disembark from your ship onto a station.
2. Test {status.on_foot_in_station} in EDDI to see that it reports as True.
3. Test {BOOL:Status on_foot_in_station} in VA and see that it is 'Not set'.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1-b1
  * VoiceAttack Version: v1.8.8
* Localization [if applicable]
  * EDDI's language: English UK
  * Voice: Ivona Amy

### Investigation Notes
I wanted to check if I was walking about a station in VA, so I tried to use the 'Status on_foot_in_station' variable, but this keeps returning as 'Not set'.

To check, I created a command with the following in;
```
Write [Blue]: '{BOOL:Status docked}' to log
Write [Blue]: '{BOOL:Status on_foot_in_station}' to log
```
Docked was 'False', and on_foot... was 'Not set'.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
The [docs](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#status-variables) list it as `{BOOL:Status on foot in station} true if you've disembarked at a station.`
