### ISSUE TITLE
Community Goal update incorrectly says "you have fallen"

### ISSUE THREAD

**Issue by arancaytar** [EDCD/EDDI#2211]
While participating in a CG, I did the following:

- Signed up
- Sold enough commodities to enter the 25% rank: A while later, EDDI commented that I had "fallen" to the 25th percentile band
- Sold enough commodities to enter the 10% rank: EDDI again said I had "fallen" to the 10th percentile band.

The script contains the following check:

```
            {if update.direction = "Increase":
                You have reached 
            |else:
                You have fallen to
            }
```

My guess is that the `update.direction` value is either absent or doesn't match the expected format, causing it to always be interpreted as a decrease.

**Comment by arancaytar** [comment]
Update: I have now fallen to the 25% percentile, which has revealed that the messages are exactly flipped - this time EDDI said "You have reached".

**Comment by Tkael** [comment]
Ah, thanks for the report. The 10th percentile should be an increase from the 25th rather than a decrease. Fixed for the next release. o7
