### ISSUE TITLE
Uncheck all option for the Speech Responder

### ISSUE THREAD

**Issue by UseLessUK** [EDCD/EDDI#2217]
## What happens now
When a personality is copied and you do not wish to hear everything that the personality says it takes a while to uncheck, from the ones you're allowed to uncheck, the items you don't want to hear.

## What I'd like to happen 
It would be a lot simpler if there was an `untick all button` and you can then `tick` the few items you do want to hear.

## How it can happen
Addition of a Button with appropriate code to uncheck all the checkboxes that can be unchecked by the user.

## EDDI Version
Current

Probably forgotten about as this request was made a while ago on the Frontier forum.

**Comment by Tkael** [comment]
We actually already implemented this (see https://github.com/EDCD/EDDI/releases/tag/Release%2F4.0.0-b1 notes). When you copy a personality, you are presented with this option. Likewise, if you right click on the column header for `Enabled` then you also have a small context menu pop up with the option there.

**Comment by UseLessUK** [comment]
Nice, just a shame its not very obvious for an already copied personality.

**Comment by Tkael** [comment]
We wanted to avoid crowding the UI too much.
