### ISSUE TITLE
EDDI mandatory upgrade 2.4.4 Crashes on running

### ISSUE THREAD

**Issue by daiaxis** [EDCD/EDDI#222]
## Steps to reproduce

Dowloaded EDDI 2.4.0-rc1
On running EDDI it prompts for mandatory upgrade
Click on the upgrade button
EDDI reports downloading
EDDI reports upgrading
EDDI window opens with 2.4.4 but then immediately stops with following error

EDDI has stopped Working
A problem caused the program to stop working correctly. Window will close the program and notify you is a solution is available

## Expected
Expected upgrade to work

## Observed
EDDI has stopped Working
A problem caused the program to stop working correctly. Window will close the program and notify you is a solution is available

## Investigation
I have tried going back to earlier versions but they all now report mandatory upgrades to the next version when the fional upgrade to 2.4.4 happens EDDIT crashes

**Comment by richardbuckle** [comment]
The problem is likely some sort of damage to a file in EDDI's data folder `%APPDATA%\EDDI`.

1. Quit EDDI (or VoiceAttack if that's how you use it).
1. Hit Windows+R and supply `%APPDATA%\EDDI`.
1. Remove all contents to another location.
1. Re-launch EDDI

If that works then you can try restoring the elements you removed, one at a time.

I hope this helps. Please let us know how you get on.

**Comment by daiaxis** [comment]
Thanks Richard
It appears to be related to eddi.json - If I remove this file from the C:\Program Files (x86)\VoiceAttack\Apps\EDDI folder then it appears to work OK. But I have no idea what eddi.json is, or what it's for, so I've not been able to test anything specific to see if the removal of this file is important??
Thanks for your help. Greatly appreciated

Dai

**Comment by richardbuckle** [comment]
`eddi.json` is a settings file. To be honest, everything in it is expendable. Here for example is mine:
```json
{
  "homeSystem": "Shinrarta Dezhra",
  "homeStation": "Jameson Memorial",
  "debug": false,
  "beta": true,
  "insurance": 5.0,
  "plugins": {
    "Galnet monitor": false,
    "Material monitor": true,
    "VoiceAttack responder": false
  },
  "exporttarget": "Coriolis"
}
```

Nuking it will not be a problem ;)

**Comment by richardbuckle** [comment]
Wait, I just noticed you said you were removing files from `C:\Program Files (x86)\VoiceAttack\Apps\EDDI`.

Please **DON'T** interfere in there! If you have messed around in there, then the best thing to do is uninstall and re-install.

If you go messing around in that directory then all bets are off.

**Comment by daiaxis** [comment]
OK I removed everything from the correct directory now. Re ran EDDI which recreated some of them. I then copied back those that I had originally replacing where necessary and now everything works.
Thank you so much
Dai
