### ISSUE TITLE
Make Personalities path configurable

### ISSUE THREAD

**Issue by parduz** [EDCD/EDDI#2223]
The Personalities directory is now fixed in the %USERPROFILE%\AppData\EDDI\ folder.
It could be useful to have it configurable (thru the "usual" textbox+"Browse" button) so the users may pick a  different drive or path.

One of the advantages is that one could put the Personalities in a "cloud-synced" folder and have them always updated between different PCs, or have them stored in a (not) daily backupped drive, etc.

**Comment by Tkael** [comment]
That could create complications that I'd rather avoid, but you can still configure Windows to do what you are describing. https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by parduz** [comment]
Oh, i know SymLinks, thanks. I thought it could be a nice feature for less expert users :)
