### ISSUE TITLE
Feature Request: Speech Responder Event Names Appended to Speechrespoder.out File?

### ISSUE THREAD

**Issue by Vel-RahnKoon** [EDCD/EDDI#2230]
## What I'd like to happen 
Would it be possible to add the Event Name listed in EDDI to the output for the speechresponder.out file? 

For instance, when selling to the market, I get a TTS message telling what was bought, how much, expected credit gain, etc. BUT, I don't necessarily know what to uncheck in the Speech Responder section of EDDI to stop hearing that specific report. 

As a specific example, here's a copy/paste from my log:

Welcome back Petty Officer.
You are docked at Coriolis Starport, Wohler Landing, in the Losin system.
You have no missions at the moment.

For the 3rd line ("You have no missions at the moment."), it would be nice to know what event generated that line. Checking the list of events, there are 13 events with "Mission" in the name. I'm assuming it's one of these, and I can probably eliminate some of them off the bat (Mission Abandoned is most likely not it, for instance), but I would have to uncheck each one in turn and restart the game to check them all.

If the output looked something like this:

Mission check system: You have no missions at the moment.

where the event name was added up front or at the end or something it would make tweaking a bit easier.

## EDDI Version
v.4.0.1-b1

**Comment by Tkael** [comment]
Interesting idea, though I believe some commanders pass the contents of `speechresponder.out` to an overlay so I don't think they'd appreciate the change that you're proposing. 

In the example you cited there is both a parent script and a child script. Both play a part. While we could readily log the name of the top level speech, it would be very difficult to reach into the guts of the parser, extract the name of the child script, and tag the associated speech segment associated with a child script. 

That said, the Speech Responder does include a filter in the bottom left corner to help you to identify and manage scripts. I used the filter to search for the phrase "at the moment". That identified `Mission check galaxy` as the originating script. `Mission check galaxy` is an invoked script with no associated event so I searched for `Mission check galaxy` and found the `Missions` event. 

If you'd prefer to omit this speech, you might either disable the event-based `Missions` script or edit the invoked `Mission check galaxy` script.

**Comment by Vel-RahnKoon** [comment]
Hi Tkael, thanks for the response!

It sounds like it will be a pain, and you've given me an alternate course of action with the Filter section. It's not as easy as just opening a log, but it sounds like a lot less work for you.

In your example using the filter, you noted that Mission Check Galaxy is an invoked script and that led you to go searching further. What gave you the info that it's an invoked script (other than being the developer  :D )? Is it the fact that it has no Priority value listed, whereas Missions does? Just trying to nail it all down and we can close this request.


VRK

**Comment by Tkael** [comment]
Bingo. Invoked scripts have no priority (since they inherit the priority of the parent script) and cannot be disabled (since they are not triggered by journal events in the first place). o7
