### ISSUE TITLE
MaterialDetails() rarity not working?

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2231]
### Expected
MaterialDetails().rarity.name (or .level) to be populated.

### Observed
MaterialDetails().rarity.name (or .level) are blank.  However, MaterialDetails().rarity is populated with the name.

### Steps to reproduce
1. Test MaterialDetails() with a material, i.e. MaterialDetails("Inconsistent Shield Soak Analysis").rarity.name
2. Observe that nothing is reported.  Same for .level

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1-b1
  * VoiceAttack Version: [if applicable] 
* Localization 
  * EDDI's language: English
  * Voice: Ivona Amy

### Investigation Notes
I have my Material collected script read out the grade of data collected from scans (using .level), and have just noticed that it's not being spoken anymore.

I've run the test button on the script, using MaterialDetails().rarity.level, .rarity.name, and just .rarity.  Only .rarity has anything in it now, both .name and .level are empty.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
Try `MaterialDetails().Rarity.name`.

**Comment by Darkcyde13** [comment]
Ahh, yes, that works.  The help and variables pages in EDDI have it listed with a lowercase 'R', and that is what I had been using.  In the past that worked.  Has it been changed recently then?

**Comment by Tkael** [comment]
Ah yes, most of our backing objects are Propercased (or camelCased) with the localized name lowercased. Looks like we identified this an exception to our convention and updated it in April, thinking that the change was consistent with the documentation in the variables page. Looks like we forgot to consider examples in the help page. I'll catch it up. :-D
