### ISSUE TITLE
Wrong Ship Type

### ISSUE THREAD

**Issue by adwbkk** [EDCD/EDDI#2233]
Hi
Love the program!
Works great .... but .... I am in a Python and EDDI thinks I am in a Type 7.   All the spoken messages reference a Type 7.

I am not a technical person, but it you want logs or something and you tell me how to do it I should be able to.

Regards
Tony
(Cmdr Stayns)

**Comment by Tkael** [comment]
Hmm. This might occur if you've connected the Frontier API from one account and player journals from another. Do you have multiple game accounts?

Verbose logs would probably be helpful. Please check the verbose logging button, swap ships once, uncheck the verbose logging button, and then upload the following from the %appdata%/EDDI folder:
- eddy.log
- shipmonitor.json

**Comment by adwbkk** [comment]
Hi Brian
I only have the one account and only the one ship.
I will check the box for verbose logs and do some exploring then send it to
you.

Just for your info, the number of hours I have played is a lie.   I often
quit to desktop but forget to close the ED select game window which always
seems to be hiding behind other windows. I tell you this as a pre-excuse
for not being able to do clever stuff that a gamer with those hours should
be able to do.  LOL

Thanks and regards
Tony
Cmdr Stayns

**Comment by adwbkk** [comment]
Hi
I have tried to copy and paste the shipmonitor.json file but it gets rejected, seemingly by this window and I can not find an eddy.log file in the EDDI folder, only eddi.log files.
I have zipped the .json file
Please advise.

**Comment by adwbkk** [comment]
Sorry about closing and opening - got confused
I can not find an eddy.log file in the EDDI folder.
When trying to send the .json file it gets rejected, seemingly by this window. I have zipped it
[shipmonitor.zip](https://github.com/EDCD/EDDI/files/6945033/shipmonitor.zip)

**Comment by Tkael** [comment]
Ah, sorry. It should have been eddi.log but the spellcheck on my phone apparently interfered.
If you could just zip up and attach all of the files ending in .log then I'll be able to review them.

**Comment by Tkael** [comment]
I can confirm that your shipmonitor.json appears to contain bad data - the ship model is recorded as "Type-7 Transporter" but the data is clearly that of a Python.

I'd recommend deleting shipmonitor.json when EDDI is closed and allowing EDDI to rebuild it.

When did you first notice this issue? Have you perhaps reset your commander? Trying to determine what could have caused the bad data.

**Comment by adwbkk** [comment]
I downloaded EDDI some time ago but did not use it but then started using it after a while.   I have not done any resets but have lost many ships.
I noticed this when I started using it again about a month ago.   It started with a Type 7 and never changed.
[EDDILogs.zip](https://github.com/EDCD/EDDI/files/6947357/EDDILogs.zip)

**Comment by Tkael** [comment]
Thanks. Let me know if deleting shipmonitor.json resolves the issue or if it comes back still wrong.

**Comment by adwbkk** [comment]
Deleting shipmonitor.json did the trick.
All good now
Thanks
