### ISSUE TITLE
TTS volume slider broken (for most voices?), either no or full volume

### ISSUE THREAD

**Issue by alterNERDtive** [EDCD/EDDI#2234]
### Expected
The TTS volume slider has a smooth curve from 0 to 100% volume.

### Observed
(With most voices?) 0-49% corresponds to no voice, 50-100% to full blast.

### Steps to reproduce
1. Update to latest beta
2. Set volume to <50%, hit the test button.
3. Set volume to >50%, hit the test button.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1-b2
* Localization [if applicable]
  * EDDI's language: English
  * Voice: see below

### Investigation Notes
For the default Windows TTS voices, the bugged behaviour applies.

For the Cortana voices (Eva, Mark, Sarah), it works correctly.

For “Windows TTS default” it’s bugged for me, even though that default voice is “Microsoft Eva Mobile” (= a Cortana voice).

![image](https://user-images.githubusercontent.com/53827887/128761082-f752a7a3-f7f9-4b8a-8683-7fd135075e13.png)

**Comment by Tkael** [comment]
~~Would you please attach your eddi.log from your last run? I'd like to review for any logged exceptions.~~
EDIT: Nevermind, I think I've identified the issue.
