### ISSUE TITLE
VA variables for 'horizons' and 'odyssey' both show TRUE in Odyssey

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2237]
### Expected
The Voice Attack variables {BOOL:horizons} and {BOOL:odyssey} to return true or false depending which version of the game is running.

### Observed
Running Odyssey, both are returning as TRUE.
Running in Horizons, 'horizons' is TRUE and 'odyssey' is FALSE (as expected).

### Steps to reproduce
1. Load game into either Horizons or Odyssey
2. Test the Boolean values of 'horizons' and 'odyssey' in Voice Attack.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1-b3
  * VoiceAttack Version: v1.8.9
* Localization [if applicable]
  * EDDI's language:English
  * Voice: Ivona Amy British English

### Investigation Notes
I wanted to test these out as they were both returning False in previous versions of EDDI, and I want to use these in my VA profile.  Now they seem to both return True when Odyssey is running.  Shouldn't 'horizons' be False when Odyssey is running?  I also wonder if this is intended behaviour, as technically Horizons is part of Odyssey?

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
This is intended. Both modules are technically DLC. If both modules are active then they will both return true.
