### ISSUE TITLE
Loss of volume control

### ISSUE THREAD

**Issue by Nomad2172** [EDCD/EDDI#2238]
Just upgraded to version 4.0.1-b2 on August 8, 2021 and have lost the ability to control volume. Volume of voice will only work between volume 51 - 100. Once you drop to 50 or below you get no voice response.

**Comment by Tkael** [comment]
Thanks. Version 4.0.1-b3 has been released which should correct this issue.

**Comment by Nomad2172** [comment]
Confirming that Version 4.0.1-b3 DID correct the issue. Thanks for an incredible fast response and resolution!!!!!!!!
