### ISSUE TITLE
System name mispronunciation for last two betas

### ISSUE THREAD

**Issue by Taomyn** [EDCD/EDDI#2239]
## What's Wrong (please be as specific as possible)

Not sure what got changed but the last two betas, 4.0.1-b2 and b3, the pronunciations of systems with words + characters/numbers has gone very weird.

### Expected
Say "Vesper-M4" says "Vesper" "M4"

### Observed
Say "Vesper-M4" says "V" "E" "S" "P" "E" "R" "dash" "M4"

### Steps to reproduce
Within any script, enter:

```
{P("vesper-m4")} - wrong
{P("vesper m4")} - right
{P("vesper")} - right

```
### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1-b3
  * VoiceAttack Version: n/a 
* Localization [if applicable]
  * EDDI's language: Auto, English-UK
  * Voice: Ivona 2 Emma

## My Investigation
Same strings entered into my custom lexicon for the Ivona voice (not the new feature for this release of EDDI), pronounces all the examples above correctly.

### Investigation Notes
Was fine with v4.0.1-b1

**Comment by Tkael** [comment]
Thanks, I'll make some tweaks to accommodate this name pattern.

**Comment by Tkael** [comment]
Hmm... it looks like we already have some code intended to handle this but the match is case sensitive. 

{P("vesper-m4")} - wrong
{P("VESPER-M4")} - right

All uppercase characters is the expected casing from the player journal
- https://www.edsm.net/api-v1/system?systemName=VESPER-M4&showInformation=1
- https://www.spansh.co.uk/system/1625385077107
```json
{ "timestamp":"2021-08-12T02:46:10Z", "event":"FSDTarget", "Name":"VESPER-M4", "SystemAddress":1625385077107, "StarClass":"G" }
```

**Comment by Taomyn** [comment]
Interesting, I was briefly able to check my last journal file before I left for work and did not find any non-UPPERCASE mentions, so perhaps something else within EDDI has given it in a different format. I will enable the debug logging in EDDI when I play later tonight and see what it shows when I hear it again.

**Comment by Taomyn** [comment]
Found it but I think I heard it do similar somewhere else I just couldn't get it to trigger:

`2021-08-12T17:43:35 [Debug] ScriptResolver:createVariables State is {"eddi_context_lastdocked":"Rothfuss Holdings","eddi_context_fuel_remaining":8.0,"eddi_context_system_system":"VESPER-M4","eddi_context_fuel_used":0.500055,"eddi_context_last_subject":"mission","eddi_context_fsd_target":"Hyperspace","eddi_context_landing_pad_station_model":"Outpost","eddi_context_body_type":"Station","eddi_context_station_name":"Rothfuss Holdings","eddi_context_redirected_to":"VESPER-M4_Rothfuss Holdings","eddi_context_wanted_list":"","eddi_context_system_name":"VESPER-M4","eddi_context_bounty_amount":120120.0,"eddi_context_approach_time":1628787689.0,"speechresponder_quiet":false,"eddi_context_srv_deployed_id":"","eddi_context_remaining_jumps":0.0,"eddi_context_criminal_record_change":true,"eddi_context_last_action":"complete","eddi_context_last_settlement":"Toro Chemical Silo","eddi_context_body_system":"VESPER-M4","eddi_context_last_speech":"On Foot mission completed. You have received 10,000 credits from Nationals of <say-as interpret-as=\"characters\">V</say-as> <say-as interpret-as=\"characters\">E</say-as> <say-as interpret-as=\"characters\">S</say-as> <say-as interpret-as=\"characters\">P</say-as> <say-as interpret-as=\"characters\">E</say-as> <say-as interpret-as=\"characters\">R</say-as> dash <say-as interpret-as=\"characters\">M</say-as> 4. <break time=\"1000ms\" />","eddi_context_search_count":0.0,"eddi_context_landing_pad_station":"Rothfuss Holdings","eddi_context_landing_pad_pad":2.0,"eddi_context_bounty_name":"Commando","eddi_context_body_name":"Rothfuss Holdings","eddi_context_redirected_from":"LP 869-42_Toro Chemical Silo","eddi_context_message_name":"Rothfuss Holdings","eddi_context_message_content":"Docking request granted.","eddi_context_landing_pad_system":"VESPER-M4","eddi_context_search_distance":0.0,"eddi_context_bounty_faction":"Pirate","eddi_context_system_lastvisit":1628710302.0}
`

**Comment by Tkael** [comment]
Noted. I think I'm going to close this issue as resolved but if you see this behavior (spelling out words that should be whole) then please let me know. o7

**Comment by Taomyn** [comment]
> Noted. I think I'm going to close this issue as resolved but if you see this behavior (spelling out words that should be whole) then please let me know. o7

Resolved, did you fix it then?

**Comment by Taomyn** [comment]
> Noted. I think I'm going to close this issue as resolved but if you see this behavior (spelling out words that should be whole) then please let me know. o7

My home system of Llyr, spelt when put through P():

```
{P(homesystem.name, 'starsystem')} .
{P('LLYR', 'starsystem')} .
LLYR
```

**Comment by Tkael** [comment]
Noted and fixed for the next release.
{P("Nationals of VESPER-M4", "faction")} - not spelled out, pronounced like 'Nationals of Vesper M 4'
{P('Llyr', 'starsystem')} - not spelled out, pronounced more or less like 'Liar'

**Comment by Taomyn** [comment]
Thanks @Tkael I will try it out once released and let you know how it goes.
