### ISSUE TITLE
No voices after 4.0.1-b2

### ISSUE THREAD

**Issue by saucyknave** [EDCD/EDDI#2240]
I installed the update 4.0.1-b2 and suddenly had no voices audible via EDDI.  None of the voices available are audible.  I'm using Windows 10 64bit, 20h2, no spacial audio effects.  Voices were perfectly audible on 4.0.1-b1, so I completely uninstalled EDDI and reinstalled 4.01-b1.  Just today (8/11/2021, around 10:20pm CST), I installed the 4.01-b3 release, and same problem - no voices audible at all.  In both cases, I'm using a custom profile, which has only silenced a couple of items, like Ship Refueled.

I can uninstall and go back to 4.0.1-b1, but I'd like to know WHY I'm not getting any audio and what suggestions there are for getting them back.  Thank you for an awesome program!!!

**Comment by Tkael** [comment]
4.0.1-b3 should have resolved most (if not all) issues with speech volume.
Please zip up your `.log` files (at %appdata%/EDDI) and attach them here for review?

**Comment by Tkael** [comment]
Please also include `speech.json` from the same location.

**Comment by Madproforg** [comment]
I've got the same problem, no voices.
Error line from the log file
2021-08-12T07:26:49 [Warning] SpeechService:getSpeechStream Speech failed (Western European (Windows)): {"ClassName":"System.InvalidOperationException","Message":"Sequence contains more than one matching element","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at EddiSpeechService.SpeechService.speak(String voice, String speech)\r\n   at EddiSpeechService.SpeechService.getSpeechStream(String voice, String speech)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nSingleOrDefault\nSystem.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Linq.Enumerable\nTSource SingleOrDefault[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])","HResult":-2146233079,"Source":"System.Core","WatsonBuckets":null}

**Comment by Madproforg** [comment]
I've got the same issue.
On the Speech Responder tab every voice is listed twice, which possibly is also the cause of the error in the log (attached)
[eddi1.zip](https://github.com/EDCD/EDDI/files/6973575/eddi1.zip)

Installing 4.0.1-b1 over the top, speech started fine

**Comment by Madproforg** [comment]
Forget to mention. I had previously ran a powershell script which enabled the other voices for use in EDDI and other TTS apps as well

**Comment by Tkael** [comment]
I wonder if that's true for everyone with this issue?

**Comment by Tkael** [comment]
Do you still have a copy of the PowerShell script?

**Comment by saucyknave** [comment]
[eddi.zip](https://github.com/EDCD/EDDI/files/6976185/eddi.zip)
Attached log files.  I never ran any ps script to enable voices, but in EDDI I do see duplicate voices listed on the "Text-To-Speech" tab under "Voice".

**Comment by saucyknave** [comment]
I went ahead and installed an additional voice package in Windows Speech settings, specifically English (United Kingdom).  After that, EDDI will be audible with any of the UK voices, but still none of the US voices.  Furthermore, when selecting a voice in EDDI, I can test it on a UK voice but not a US voice.  What's more, if I select a UK voice and test it, then switch the voice to "Windows TTS default", it just plays in whatever UK voice I just had it set to.

**Comment by Darkcyde13** [comment]
As it's not been confirmed yet, @saucyknave & @Madproforg have you upgraded to beta 3, or are you still running beta 2?

**Comment by Madproforg** [comment]
beta 3 in my case (madproforg)

**Comment by saucyknave** [comment]
I upgraded to beta 3 to test some of the other comments, so that's where
I'm at now.

**Comment by Tkael** [comment]
Please re-test with [version 4.0.1-b4](https://github.com/EDCD/EDDI/releases/download/Release%2F4.0.1-b4/EDDI-4.0.1-b4.exe)?

**Comment by Madproforg** [comment]
That worked for me.

**Comment by Tkael** [comment]
Thanks @Madproforg. Can you also confirm, @saucyknave?

**Comment by saucyknave** [comment]
Sorry for the delay.  I saw your comment but work demanded my attention.  I just upgraded and it works now.  Freaked out a bit because the last voice I picked was Zira at about 2x the speed.  But yes, the voices are audible and each voice is not duplicated in the list any longer.  Back to normal.  Well done.
