### ISSUE TITLE
German microsoft voices do not work with the voice() command and ...

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#2244]
... Microsoft Zira also !

For example, if I set Hedda as the second voice using the voice() command ( {voice("I'm the second voice", "Microsoft Hedda")} ), the set voice still speaks under the "Text-to-speech" tab (for me Petra Harpo).

I expect the text "I'm the second voice" to be spoken by the German Microsoft voice "Hedda".

If I use as second voice e.g. "IVONA 2 Hans OEM" it works fine. 

If I set Microsoft Zira ( {Voice("I'm the second voice", "Microsoft Zira")} ), then Microsoft Mark speaks.

My test commands:
{SetState("stimme2", "IVONA 2 Hans OEM")}
{set text to: Ich bin die zweite Stimme}
{Voice(text, state.stimme2)}

### Configuration
  * EDDI Version:  v.4.0.1
  * VoiceAttack Version: 1.8.9 64 bit
* Localization: German
  * EDDI's language: German
  * Voice: "Text-to-speech": Petra Harpo 22kHz

**Comment by Darkcyde13** [comment]
Hmm, this is weird.  If I use Microsoft Zira Desktop as the main voice, then Ivona Amy works as the second voice.  But if I use Microsoft David, the Ivona Amy doesn't work.

So I've gone through the voices I have installed, and come up with this table:
|Voice|Amy|George|Hazel|Susan|Zira|
|---|---|---|---|---|---|
|IVONA 2 Amy|-|x|x|x|+|
|Microsoft George|x|-|+|+|o|
|Microsoft Hazel|x|+|-|+|o|
|Microsoft Susan|x|+|+|-|o|
|Microsoft Zira Desktop|+|i|i|i|-|

The main voice is down the left, and the temporary second voice is along the top.
The dash - is where both voices would be the same, so I didn't try those.
The x is where the second voice failed and used the same first voice.
The + is where both voices worked as expected.
The o is where the second voice didn't vocalise at all.
The i is where my PC's main voice (currently Ivona Amy) spoke instead.

So, Zira and Amy seem to work OK together, and the normal Microsoft (non-Desktop) work OK together, but these two groups do not work with each other.

Hopefully this can be of some help to the team in figuring out what is going on, and why some work and others don't. 

EDIT: For context, these are all British English voices (although Zira is American English).  My test code is this, swapping out the voices as needed:
```
First voice.
{Voice("Second voice", "IVONA 2 Amy")}
```

**Comment by Tkael** [comment]
Hmm. This sounds like a problem when jumping from a voice using one speech synthesizer to a second choice using a different speech synthesizer (since we unlocked voices by adding support for a 2nd Windows speech synthesizer). Tricky. 🤔

**Comment by nepomuk16321** [comment]
For me, it's not a big problem now. It just came up during the discussion in the German forum and we couldn't explain it.

**Comment by Tkael** [comment]
Resolved by https://github.com/EDCD/EDDI/commit/2fa4fb2a8329319a611963e9bd63e0eff6841d08 for the next update.
