### ISSUE TITLE
Criminal record not storing shipID

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2246]
### Expected
The criminalrecord object to populate the shipID variable within the finseIncurred and bountiesIncurred sections.

### Observed
The shipID variable is not populated.

### Steps to reproduce
1. Commit a crime and get a fine or bounty.
2. Visit a station to pay off the fine/bounty.
3. The Crime check station script should report you can pay there.
4. Observe that it does not inform you at all.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1
  * VoiceAttack Version: N/A
* Localization N/A
  * EDDI's language: British English
  * Voice: Ivona 2 Amy Britsh English

### Investigation Notes
In my personality, I have the Ship swapped event script tell me if I have any outstanding fines or bounties on the ship I am swapping to.  I don't normally gain a criminal record, and when I do, I rarely go back.  Anyway, I had managed to get a couple of fines on my exploration ship a while ago, and when I swapped to it recently I realised that my script was telling me the ship was clean, when it wasn't.

So, to check this out, I went back to the EDDI default personality, launched in a clean ship, fired my lasers within the station no fire zone, and got myself some fines.

I redocked, and ran the Crime check system script, which correctly reported my fines.  I then ran the Crime check station script, and nothing was spoken.  I went back to my personality, and checked my Crime Check Ship script.  This uses a large portion of the Crime check station script, and is designed to inform of crimes associated with the ship I'm swapping to.

I added some test code lines to see if I could figure out what was happening to prevent it working as intended.  My script now looks like this:
```
{_ Crime Check Ship _}
{_ Reports crimes associated only with your current ship _}


{set ship_factions to []}
{set ship_systems to []}
{set bounties_count to 0}
{set fines_count to 0}
{set ship_bounties to 0}
{set ship_fines to 0}

{for record in criminalrecord:
Faction: {record.faction}.
    {set reports to record.finesIncurred} Fines:
    {if len(reports) > 0:
        {for report in reports:
        {report.shipId}, {ship.LocalId}.
            {if report.shipId = ship.LocalId:
                {set ship_fines to ship_fines + report.amount}
                {set fines_count to fines_count + 1}

                {if find(ship_factions, record.faction) = -1:
                    {set ship_factions to cat(ship_factions, [P(record.faction, "faction")])}
                }
                {if find(ship_systems, record.system) = -1:
                    {set ship_systems to cat(ship_systems, [P(record.system, "starsystem")])}
                }
            }
        }
    }

    {set reports to record.bountiesIncurred} Bounties:
    {if len(reports) > 0:
        {for report in reports:
            {if report.shipId = ship.LocalId:
                {set ship_bounties to ship_bounties + report.amount}
                {set bounty_count to bounty_count + 1}

                {if find(ship_factions, record.faction) = -1:
                    {set ship_factions to cat(ship_factions, [P(record.faction, "faction")])}
                }
                {if find(ship_systems, record.system) = -1:
                    {set ship_systems to cat(ship_systems, [P(record.system, "starsystem")])}
                }
            }
        }
    }
}

{if bounties_count > 0 || fines_count > 0:
    {if bounties_count > 0: Warning:
    |elif fines_count > 0: Caution:
    }
    This ship is wanted

    {if len(ship_factions) = 1: by {ship_factions[0]}
    |elif len(ship_factions) > 1: by {List(ship_factions)}
    }

    {if len(ship_systems) = 1: in the {ship_systems[0]} system
    |elif ship_systems > 1: in the {List(ship_systems)} systems
    }

    {if ship_bounties > 0 || ship_fines > 0:
        for a total of {ship_bounties + ship_fines} credits
    }
|else:
    This ship is clean
}.

```
I've added lines to tell me the faction, and then the record.shipID and ship.LocalID for each individual fine or bounty.  Line 17 is {report.shipId}, {ship.LocalId}.  This is the output I'm getting:

> Faction: Workers of Iah Bulu Future. Fines:, 22., 22., 22. Bounties: Faction: Kokobii Empire League. Fines:, 22., 22., 22., 22., 22., 22., 22., 22., 22. Bounties: This ship is clean.

The ship I am currently in has the ID of 22.  The above should show "22, 22." for all entries under the 'Kokobii Empire League', but the {record.shipID} variable is empty.  The 'Iah Bulu Future' entries are for ship ID 29.
My Crime Monitor looks like this:
![image](https://user-images.githubusercontent.com/24360725/131262838-b25d44a1-3f4e-44c0-9479-642e2be9dd27.png)
I notice that the Station is listed as a 3-3 code, not a station name.  Is that correct, or another bug?

The Journal entries are like this:

> { "timestamp":"2021-08-29T19:02:52Z", "event":"CommitCrime", "CrimeType":"fireInNoFireZone", "Faction":"Kokobii Empire League", "Fine":100 }

Here, I notice there is no entry for the ship ID.  I assume EDDI should automatically assign the current ship ID to the crime entry when it is received.

If you need any further info, I'll be happy to help out if possible.

### EDDI Logs
N/A

### Player journals
As above.

**Comment by Tkael** [comment]
It's true that the criminal record no longer includes a ship ID parameter. That is because Odyssey no longer stores crimes per ship and instead stores them per commander (https://forums.frontier.co.uk/threads/elite-dangerous-odyssey-bgs-and-crime-details.575842/). 

When I overhauled the Crime Monitor, I had to choose whether to spend development time on the soon-to-be-obsolete Horizons criminal system or to instead focus solely on the Odyssey criminal system. I chose to focus my attention solely on Odyssey. While I understand that this is an imperfect solution for commanders on Horizons, I hope you can see and understand my reasoning.

**Comment by Darkcyde13** [comment]
Ahh, I see.  Thank you for pointing that out, I had forgotten that part.  Looking over the variables again, I now see that there is a 'hot' variable for ships, so I can make use of that instead.

That being said, the 'Crime check station' script still uses the shipID under the criminal record, on lines 63 and 75.  Should this not be removed and updated now?  If I'm reading the code right, this script will never work for crimes now, as record.shipID will never equal ship.LocalID?

Also, that 3-3 code for the station in the Crime Monitor, where does that come from and what does it represent?  I clicked Update and the code changed to something different.  There's no link to a Crime Monitor section in the Wiki, so where can I find details on this please?

**Comment by Tkael** [comment]
Good point. I'll give `Crime check station` some more thought.

What do you mean by "that 3-3 code for the station in the Crime Monitor"?

The `System` and `Station` columns record our best guess for the home system and station for the faction. The 'Update' button triggers a search to match manually added faction names and fill faction system and station details.

**Comment by Darkcyde13** [comment]
> What do you mean by "that 3-3 code for the station in the Crime Monitor"?

If you look at the image I posted in the initial report above, you can see that under the 'Station' column, there are 3-3 codes (sorry, I should have been more specific and said ' 3 alphanumeric - 3 alphanumeric' codes).  In the image they are "JZL-3KW" and "QNQ-63X".  I thought these should be station names.

Hmm, thinking about it now, I've realised they are ship codes for fleet carriers.  This would also explain why the code changed when I clicked the update button for the 'Iah Bulu' entry I have.  I can understand using fleet carriers to pay off crimes, but as they can move about, I would have thought that only stations would be the preferred choice to use in that column.  Is the inclusion of fleet carriers intentional, or is it a bug?

**Comment by Darkcyde13** [comment]
I've had a quick think about the Crime check station script, and I think all you need to do is remove the lines that check the IDs (and corresponding closing brackets).

I just made a quick copy of the default script, removed those lines, committed a 'fire in no fire zone' crime, and ran the script.  It seems to work as expected now, but obviously I've not done a comprehensive test on it yet.

I assume that the IDs are still present in Horizons?  If so, I think the problem will be between Horizons and Odyssey users.  You could make it so it works in both, by just adding a check for Odyssey to the ID check lines, like this `{if (report.shipId = ship.LocalId) || odyssey:`, but then that would stop working when FDev merge Odyssey crime into Horizons.  On the other hand, leaving it makes it work in Horizons, but not Odyssey; and removing it makes it work in Odyssey but not Horizons.  It seems like  a Catch 22 situation to me. :/

Of course, if the IDs are no longer stored in EDDI's crime monitor at all, then simply removing those lines should fix things, as the   script will no longer work for Horizons players anyway.

EDIT:  I've run a more thorough check now, and removing those lines does seem to make the script work as expected again, with local & interstellar fines & bounties being reported correctly... while in Odyssey of course.

**Comment by Tkael** [comment]
> > What do you mean by "that 3-3 code for the station in the Crime Monitor"?
> 
> If you look at the image I posted in the initial report above, you can see that under the 'Station' column, there are 3-3 codes (sorry, I should have been more specific and said ' 3 alphanumeric - 3 alphanumeric' codes). In the image they are "JZL-3KW" and "QNQ-63X". I thought these should be station names.
> 
> Hmm, thinking about it now, I've realised they are ship codes for fleet carriers. This would also explain why the code changed when I clicked the update button for the 'Iah Bulu' entry I have. I can understand using fleet carriers to pay off crimes, but as they can move about, I would have thought that only stations would be the preferred choice to use in that column. Is the inclusion of fleet carriers intentional, or is it a bug?

Ahh, I see. Yes, those look like fleet carriers to me too. I believe that the crime monitor code in question pre-dates fleet carriers and that we simply didn't identify a need to exempt fleet carriers from the algorithm after they were introduced. So... working as originally intended but no longer quite fit for purpose. ;-) I think I'll add an exemption for fleet carriers.

**Comment by Tkael** [comment]
> 
> 
> I've had a quick think about the Crime check station script, and I think all you need to do is remove the lines that check the IDs (and corresponding closing brackets).
> 
> I just made a quick copy of the default script, removed those lines, committed a 'fire in no fire zone' crime, and ran the script. It seems to work as expected now, but obviously I've not done a comprehensive test on it yet.
> 
> I assume that the IDs are still present in Horizons? If so, I think the problem will be between Horizons and Odyssey users. You could make it so it works in both, by just adding a check for Odyssey to the ID check lines, like this `{if (report.shipId = ship.LocalId) || odyssey:`, but then that would stop working when FDev merge Odyssey crime into Horizons. On the other hand, leaving it makes it work in Horizons, but not Odyssey; and removing it makes it work in Odyssey but not Horizons. It seems like a Catch 22 situation to me. :/
> 
> Of course, if the IDs are no longer stored in EDDI's crime monitor at all, then simply removing those lines should fix things, as the script will no longer work for Horizons players anyway.
> 
> EDIT: I've run a more thorough check now, and removing those lines does seem to make the script work as expected again, with local & interstellar fines & bounties being reported correctly... while in Odyssey of course.

I think the change in the long run is beneficial for the crime monitor. After all, the Crime Monitor UI has never been great for distinguishing crimes by ship ID. 

Sounds like your tests line up with my thinking about how we ought to tweak the script for Odyssey and beyond.
