### ISSUE TITLE
Distance from Home variable does not set in Voice Attack

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#2248]
## What's Wrong (please be as specific as possible)
'{DEC:System distance from home}: the number of lights years between this system and the your home system, to two decimal places' always returns 'not set' in VA

_System Variables
{DEC:System distance from home}: the number of lights years between this system and the your home system, to two decimal places_

### Expected
Variable to be set to distance from home system

### Observed
Variable always returns 'not set'

### Steps to reproduce
1. Visit system distant from home system
2. Examine {DEC:System distance from home} in Voice Attack

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  4.0.1
  * VoiceAttack Version: 1.8.9
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

## My Investigation
EDDI variable; {system.distancefromhome} is set correctly 
### EDDI Logs
No log entries for this problem

**Comment by Darkcyde13** [comment]
I've just tried this in a VA command, writing it to the log: `{DEC:System distance from home}` and it's working for me.  I copied the line directly from your post above, and pasted into the command.

![image](https://user-images.githubusercontent.com/24360725/131546302-5d3333a5-3086-442c-aaa0-51500180ad8b.png)
![image](https://user-images.githubusercontent.com/24360725/131546513-853f5d5c-b701-4ab9-821d-25e1ff2c73e9.png)

Double check that it's spelled correctly in your command.  I can't see why it would work in EDDI, but not in VA unless there is a typo somewhere.

Could you post a screenshot of your command to look at?

**Comment by rodan123** [comment]
I don't know then, are you using the latest EDDI version? I believe it was working for me until version 4.

This doesn't work for me in VA (always get first option);
```
Begin Decimal Compare : [System distance from home] Equals 0  
Say 'You are in your home system {TXT:Home system name}'  
Else  
Say, 'It is {DEC:System distance from home} light years to {TXT:Home system name}'  
End Condition
```

 But this does work in Cottle:
```
{if system.distancefromhome = 0: 
	You are in your home system, {P(homesystem.systemname)}
|else: 
	It is {system.distancefromhome} light years to {P(homesystem.systemname)}
}
```

**Comment by Darkcyde13** [comment]
Hmm, strange.  I copied your command exactly, and it worked fine for me.  I'm using VA v1.8.9 and EDDI v4.0.1.

However, I accidentally closed VA, and when I opened it again, the command stopped working.  Well, I keep getting the second option, not the first like you, and it tells me "It is Not set light years to Kokobii", whereas before it said "It is 189.22 light years to Kokobii".

I tried jumping to another system, and then exiting ED to the main menu, but it still wouldn't work.  Weirdly, EDDI stopped responding too, even though I could test-run scripts and they worked.  Most odd.

I quit Elite and VA, then loaded VA back up, and then Elite.  Still not working.  I've tried jumping to another system, and running the variable in Cottle to make sure it's set there, but it will not work in VA at all anymore.

There must be something particular that needs to happen to set it, but I have no idea what that could be.  When I had it working, all I had done was load into game while docked, so nothing special.  This is a bit of a puzzle....

**Comment by rodan123** [comment]
Yes, you'll always get the second option in VA if you don't tick the "Evaluate 'Not Set' as zero" checkbox when setting the conditional decimal compare block in VA. 
So, you are now essentially seeing the same result as me; 'System distance from home' evaluating as "Not Set" in VA.

But, I think you are on to something regarding the loading of the game. I always load VA before the game because I play in VR. 
If I load VA after the game is loaded, the variable 'System distance from home' is set correctly, **until the first jump**. Then it goes into the same 'Not Set' condition as detailed above.

**Comment by Tkael** [comment]
Hi @rodan123, have you noticed any problems with other system variables not being updated in VA or is this the only one?

The behavior that you're describing does seem odd. Distance should be recalculated every time that we set or change our current star system (from `Location`, `Carrier jump engaged`, `Carrier jump`, `Docked`, `FSD engaged`, `Jumped`, etc.).

**Comment by rodan123** [comment]
> Hi @rodan123, have you noticed any problems with other system variables not being updated in VA or is this the only one?

Hi @Tkael 

As luck would have it, I have a VA command that tests most system variables. They seem to be updating fine other than `System distance from home` , DIST HOME below;

```
7:46:58.505 DIST HOME: Not set
7:46:58.503 STNS: 2
7:46:58.501 COMT: Not set
7:46:58.499 MV: 10041
7:46:58.497 PV: August 25, 2021
7:46:58.495 VSTMINS: 10041
7:46:58.493 VSTS: 48
7:46:58.491 Z: -16.84375
7:46:58.489 Y: -28.375
7:46:58.487 X: 8.1875
7:46:58.485 PERNAM: Not set
7:46:58.483 PERMIT: False
7:46:58.481 POWST: Contested
7:46:58.476 POWS: None
7:46:58.474 POW: None
7:46:58.472 STE: Boom
7:46:58.470 ECON: Colony
7:46:58.468 FAC: Earth Defense Fleet
7:46:58.466 GOV: Corporate
7:46:58.464 ALG: Federation
7:46:58.462 POPS: 43,000
7:46:58.460 POP: 43008
7:46:58.458 NAMS: Aspelenie
7:46:58.456 SYS: Aspelenie

7:50:33.617 DIST HOME: Not set
7:50:33.615 STNS: 19
7:50:33.613 COMT: Not set
7:50:33.610 MV: 309
7:50:33.609 PV: August 31, 2021
7:50:33.606 VSTMINS: 309
7:50:33.604 VSTS: 690
7:50:33.602 Z: -10.65625
7:50:33.601 Y: -24.46875
7:50:33.599 X: 9.8125
7:50:33.593 PERNAM: Not set
7:50:33.591 PERMIT: False
7:50:33.589 POWST: Contested
7:50:33.587 POWS: None
7:50:33.586 POW: None
7:50:33.584 STE: Boom
7:50:33.582 ECON: None
7:50:33.579 FAC: CPD-28 332 Organisation
7:50:33.577 GOV: Corporate
7:50:33.576 ALG: Federation
7:50:33.573 POPS: over 36 and a half million
7:50:33.571 POP: 36615131
7:50:33.569 NAMS: <say-as interpret-as="characters">C</say-as> <say-as interpret-as="characters">P</say-as> <say-as interpret-as="characters">D</say-as> dash 28 3 3 2
7:50:33.567 SYS: CPD-28 332
```

**Comment by Tkael** [comment]
I think I have a solution for the next release. o7
