### ISSUE TITLE
EDDI state context last speech landing pad gives no audible response

### ISSUE THREAD

**Issue by CMDR-Frici** [EDCD/EDDI#225]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1462836/eddi_issue.zip)
## Steps to reproduce

1. `Request docking permission`
1.1 `script fires ... blablabla your pad is NUMBER blabla`
2. `what was my landing pad?`
2.1 verified to be the default script by T'Kael

## Expected
 `script fires ... blablabla your pad is NUMBER blabla`
## Observed
Nothing, the command is executed and recognized in VA but no audible response is heard.. unlike say... repeat the last thing.
IF i say say that again it works but the other one doesn't 

## Investigation
https://cdn.discordapp.com/attachments/353595704658231299/378661634606104591/unknown.png
https://cdn.discordapp.com/attachments/353595704658231299/378661761475280896/unknown.png
https://cdn.discordapp.com/attachments/353595704658231299/378662392210391040/unknown.png

**Comment by Tkael** [comment]
Does your 'Docking granted' look like this? Note the line `{SetState('eddi_context_last_subject', 'landing pad')}`. From your log, it looks like this variable may not be getting set?
![untitled](https://user-images.githubusercontent.com/4382539/32682394-48233586-c629-11e7-8746-969dd41e891d.png)

**Comment by CMDR-Frici** [comment]
Yes my script was not looking like that.
Will check all of them, you can attribute this one to PEBKAC I guess.
