### ISSUE TITLE
Audio in Voice Attack and Elite Dangerous

### ISSUE THREAD

**Issue by DHC1985** [EDCD/EDDI#2255]
Hello,

Recently my audio for EDDI has lost audio output for both Horizons and Odyssey.  I've checked VA's audio settings.  VoiceAttack works properly... but my game isn't the same without EDDI being present.

Other than what I have listed I don't know specifically what to point to to help with this.

Thank you

**Comment by Tkael** [comment]
Check EDDI's volume?
Check the volumes for each app in Windows?
If you use a surround sound system, check your audio channels. EDDI typically plays through the central speaker channel.

**Comment by DHC1985** [comment]
Thank you for the quick response.

I checked all volume levels... EDDI didn't show up in the Sound Mixer.  I
assume it's running through VoiceAttack and using that apps channel?  When
I start VoiceAttack I wait to see the EDDI plugin is enabled, then I start
Elite Dangerous.  Usually I hear EDDI on the initial start into ED.

I went into EDDI stand-alone and tried to hear Commander Name with the
'Hear It' button... nothing.  Don't know if this helps.

Respectfully,

Mike Kanir

**Comment by Tkael** [comment]
Did you check EDDI's volume level in the `Text to Speech` tab?
Approximately when did this change occur? Had you made any recent changes to your configuration?
Have you checked EDDI's log files at `%appdata%/EDDI/eddi.log` for exceptions?

**Comment by DHC1985** [comment]
No, I just did... and thank you... voice wasn't chosen and that seems to
have cleared up the problem.

My GPU died about 2 weeks ago and the audio drivers were related to the
card, nVidia sound drivers.  Thanks for the help, such a big relief.

Regards,

Mike Kanir

**Comment by Tkael** [comment]
Glad you were able to sort it out. o7 cmdr

**Comment by DHC1985** [comment]
Thanks!

Do you have any idea what an 'exploration code' is?  Exploration code
green or gold?

Thanks

**Comment by Darkcyde13** [comment]
> Thanks! Do you have any idea what an 'exploration code' is? Exploration code green or gold? Thanks

Those are the two categories for a system when you've finished scanning.  Gold means that every element you can get in the game, is available in that system.  Green means that the system has all the elements needed to synthesise an FSD jump boost.

**Comment by DHC1985** [comment]
Thanks a ton. Very much appreciated
