### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by Jessebob42** [EDCD/EDDI#2256]
I'm getting no audio from EDDI.  It's not showing up in my (windows10) Mixer window.  I've checked to make sure it wasn't getting assigned to an alternate Audio Device and it's not.  There's just no Audio channel.  

Version: 4.0.1

I've connected up my Bluetooth heatset and I have the same issues (no audio, no EDDI device in Audio Mixer).  All other programs with audio work fine. 

Maybe an Uninstall/Install will fix it?

**Comment by Darkcyde13** [comment]
Have a quick look at these two issue numbers, as they've had similar problems (no audio), and each one had a different fix.  See if either of these helps first. :-)
https://github.com/EDCD/EDDI/issues/2251
https://github.com/EDCD/EDDI/issues/2255

**Comment by Jessebob42** [comment]
I had to uninstall EDDI, then go into my profile's C:\Users\...\Appdata\Roaming\EDDI to manually delete any/all config data (I should prob have tried that first🤔).   Then reinstall EDDI and there's now a EDDI volume icon in my Win10 Mixer window.  

It's working perfectly now. Setting up back EDDI is a piece of cake, so no worries. 👍🍻

My issue is closed.

**Comment by Jessebob42** [comment]
Doh!  CLicked the wrong button.... 😐🍻
