### ISSUE TITLE
Maximum "Pattern Alpha/Beta Obelisk Data" Values Incorrect

### ISSUE THREAD

**Issue by aldeaman** [EDCD/EDDI#2259]
## What's Wrong (please be as specific as possible)
The maximum "Pattern Alpha/Beta Obelisk Data" values are 200 and 250, respectively, in v4.0.1 but the game indicates maximum values of 150.

### Expected
Expected values to match game values @ 150.  Delta, Epsilon and Gamma values are the same between EDDI 4.0.1 and the game.

### Observed
Two screenshots provided.

![EDDI 4 0 1 Screenshot](https://user-images.githubusercontent.com/68206334/133870641-2ddf46d4-2946-44b2-9d98-a251e163575f.jpg)

![Screenshot_0001](https://user-images.githubusercontent.com/68206334/133870654-614e461d-89d4-48e7-ae19-2b2912e50cf5.jpeg)

### Steps to reproduce
N/A

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: N/A
  * Localization U.S. English
  * EDDI's language: English
  * Voice: Microsoft David

**Comment by Tkael** [comment]
Thanks for the report.
