### ISSUE TITLE
Wrong system names spelling in Spanish

### ISSUE THREAD

**Issue by Transcan** [EDCD/EDDI#2263]
## What's Wrong (please be as specific as possible)
System names with a - (dash) in its name are incorrectly spelled in spanish

### Expected
It should say "guión" ("dash" in Spanish)

### Observed
But it says "guion" (notice the "ó")

### Steps to reproduce
Any system with a "-" in the name ussing the P( ) function will be spelled incorrectly

### Configuration
  * EDDI Version: 4.0.1
  * EDDI's language: Spanish
  * Voice: Any spanish voice

## My Investigation
I guess the problem comes from file EDDI/SpeechService/Properties/Phrases.es.resx it has this code inside:
```
  <data name="dash" xml:space="preserve">
    <value>guion</value>
    <comment/>
  </data>
```
which is wrong... It should be:
```
  <data name="dash" xml:space="preserve">
    <value>guión</value>
    <comment/>
  </data>
```

### Investigation Notes
I couldn't test it because I don't know how to compile the program. But I made some cottle script tests, forcing the spelling of an invented system name with the wrong "guion" in it, and it sounds exactly as a real system name through the P( ) function.
So my guess is that simple ó missing in the Phrases.es.resx that changes the spelling.

**Comment by Tkael** [comment]
Thanks for the feedback. If you'd like to assist with the translation then please read https://github.com/EDCD/EDDI/blob/develop/docs/Localization_for_translators.md.

You can PM either `VerticalBlank` or `Tkael` once you have an account and we'll add you to the project.

**Comment by hoksilato2** [comment]
The error has been fixed on crowdin translation. Thanks to all!

@Transcan you can go to Spanish forum. I'm sure we need your help :)
https://forums.frontier.co.uk/threads/eddi-en-espanol-released.428059/

**Comment by Tkael** [comment]
Perfect! The correction should be available after EDDI's next release.

**Comment by Transcan** [comment]
> The error has been fixed on crowdin translation. Thanks to all!
> 
> @Transcan you can go to Spanish forum. I'm sure we need your help :) https://forums.frontier.co.uk/threads/eddi-en-espanol-released.428059/

Sure! I made some modifications in Shirka that I would love to share.
