### ISSUE TITLE
Use ShipDetails() compatible ship models

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2268]
## What happens now
In the Bounty awarded, Ship purchased, and Ship sold events, (and maybe the Ship interdicted event too?) the variables for some of the ship models appear to have already been modified so they are spoken correctly.  So for example,  "viper Mark 3" is used so that it is spoken correctly.  However, the P() function is now capable of making this modification, so the pre-modded version is not really necessary anymore.  This applies to all ships with Roman numerals in the name.

The main problem with this pre-modded approach, is that the ShipDetails() function will not work on these variables.  In the above example, 'viper Mark 3' is not recognised by ShipDetails(), instead it requires the ship to be called "Viper Mk III".

## What I'd like to happen 
I'd like the ship model event variables to be the ShipDetails() compatible versions, and then use the P() function to correctly pronounce them.  This way, for those of us who would like to, we can then use the ShipDetails() to provide other ship data, like the manufacturer.

## How it can happen
Make sure the event variables for Bounty awarded (event.target), Ship purchased/Ship sold (event.ship) are in a format that ShipDetails() can use.  Then update those scripts to use P().

I'm not sure about the Ship interdicted event (event.interdictor).  I've not been able to get interdicted by a ship that may cause a problem, to be able to check how they are used.

## EDDI Version
EDDI v4.0.1

**Comment by Tkael** [comment]
- `Bounty awarded` - agreed, the current output is phonetic and cannot be fed back into ShipDetails() as is.
- `Ship purchased` - this should not present any problems for ShipDetails(), the provided string should already be compatible / phonetics are not automatically applied.
- `Ship sold` - this should not present any problems for ShipDetails(), the provided string should already be compatible / phonetics are not automatically applied.
- `Ship interdicted` - not applicable, the `interdictor` property gives the name of a pc or the faction of an npc rather than a ship model.

**Comment by Darkcyde13** [comment]
Ah, of course, Ship purchased is already using P() and Ship sold is using ShipName().

Yes, I got interdicted a short while ago and realised that it wouldn't apply to that event.

**Comment by Darkcyde13** [comment]
As an additional note to this, I've just been interdicted by a "Military System Defence Force" vessel, and I'm getting the bare base variable of "$ShipName_Military_Independent;" being spoken when I submitted to the interdiction.  This is using the {event.interdictor} variable in the Ship interdicted event script.  I note there is no default script for this event.

Granted I did have it as {P(event.interdictor, "shipmodel")}, but would that cause it to use the variable like that?

I have a script I call ShipType that I had been using for Ship interdicted and for Bounty awarded, where it takes the relevant ship variable, and checks it for proper English.  In it I have the following:

```
|elif shiptype = "$ShipName_Military_Alliance;":
   {set ship to "the Alliance Defence Force"}

|elif shiptype = "$ShipName_Military_Empire;":
   {set ship to "the Imperial Navy"}

|elif shiptype = "$ShipName_Military_Federation;":
   {set ship to "the Federal Navy"}

|elif shiptype = "$ShipName_Military_Independent;":
   {set ship to "the System Defence Force"}
```

After the above discussion, I had removed the calls to ShipType, but it seems that at least the '_Military_Independant' is still needed.

This was only in Ship interdicted.  The proper English version was used in NPC interdiction commenced (event.by).  So could I ask that the above four types are also checked in the Ship interdicted (event.interdictor) event please?

(Edited to clarify I meant 'event' at the end there)

**Comment by Tkael** [comment]
Noted, I thought we had handled those but it must have been something in another event. Let me see if I can find some examples of raw journal events with these values that we can reference.

```json
{ "timestamp":"2021-08-05T06:15:14Z", "event":"ReceiveText", "From":"$ShipName_Military_Independent;", "From_Localised":"System Defence Force", "Message":"$Military_StartInterdiction09;", "Message_Localised":"Naval scan in progress.", "Channel":"npc" }
{ "timestamp":"2021-08-05T06:15:19Z", "event":"Interdicted", "Submitted":true, "Interdictor":"$ShipName_Military_Independent;", "Interdictor_Localised":"System Defence Force", "IsPlayer":false, "Faction":"New Kuwembaa Labour" }
{ "timestamp":"2021-08-05T06:16:45Z", "event":"EscapeInterdiction", "Interdictor":"$ShipName_Military_Independent;", "Interdictor_Localised":"System Defence Force", "IsPlayer":false }
```

```json
{ "timestamp":"2021-08-17T07:27:46Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"eagle", "ScanStage":3, "PilotName":"$ShipName_Military_Independent;", "PilotName_Localised":"System Defence Force", "PilotRank":"Expert", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Exiled Marlinist Assembly of Baltah'Sine", "LegalStatus":"Clean" }
```
