### ISSUE TITLE
Fuel Check incorrect report after boarding ship

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2270]
### Expected
When boarding your ship after being on foot, the Fuel Check script to correctly report the amount of fuel you have.

### Observed
The Fuel Check script says you have less than 25% fuel remaining, even if you have a full tank.

### Steps to reproduce
1. Leave your ship to wander around a station.
2. Board your ship.
3. Take off (or just run the Fuel check script manually)
4. Observe the fuel level is reported as less that 25%, sometimes even as 0%.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  v4.0.1
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: British English
  * Voice: Ivona Amy

### Investigation Notes
I noticed this a while ago, but keep forgetting to report it, mainly because I've been in the middle of something when I hear it.

The Status.json file seems to have the correct data for the ships fuel after boarding, but I'm guessing that EDDI doesn't recalculate the fuel % between boarding and take off, and is still using on-foot values.

Status.json on foot:
`{ "timestamp":"2021-10-09T13:30:49Z", "event":"Status", "Flags":0, "Flags2":90121, "Oxygen":1.000000, "Health":1.000000, "Temperature":293.000000, "SelectedWeapon":"", "LegalState":"Clean", "BodyName":"Lebedev Hub", "Balance":2470068105 }`

Status.json immediately after boarding:
`{ "timestamp":"2021-10-09T13:32:48Z", "event":"Status", "Flags":16842765, "Flags2":0, "Pips":[5,2,5], "FireGroup":0, "GuiFocus":0, "Fuel":{ "FuelMain":32.000000, "FuelReservoir":0.039038 }, "Cargo":0.000000, "LegalState":"Clean", "Balance":2470068105, "Destination":{ "System":16063580284305, "Body":27, "Name":"Lebedev Hub" } }`

Examples of Fuel check script output after boarding:
```
Warning: Fuel reserves now at 0 percent capacity, commander.
Warning: Fuel levels now at 0 percent capacity.
Caution: Fuel reserves are now below 25%.
```

The variable status.fuel is correct (in this case, it's set to 32.039038), it's just the calculated % (status.fuel_percent) that is set as 'void'.

### EDDI Logs
None

### Player journals
None

**Comment by Tkael** [comment]
Bug found and squashed for the next release. o7
