### ISSUE TITLE
Body atmosphere report - Class 1 Gas Giant

### ISSUE THREAD

**Issue by CMDR-Evolution** [EDCD/EDDI#2272]
The Class I Gas Giant section of the script has two issues:
The tempmax and tempmin values are the wrong way around. They currently show:
                {set tempmin to: {TempCalc(153)}}
                {set tempmax to: {TempCalc(83)}}
but should be:
                {set tempmin to: {TempCalc(83)}}
                {set tempmax to: {TempCalc(153)}}

The line below that reads:
surface temperatures of {Humanise(tempmax)} {tempscale} {Occasionally(2, OneOf(", or less,", ", at most,"))} {OneOf("and", "with", "forming")}
but it looks like it should be:
surface temperatures {OneOf("of", "ranging")} between {Humanise(tempmin)} and {Humanise(tempmax)} {tempscale}, {OneOf("and", "with", "forming")}

An extra thought to mention - the original two Occasional outputs are saying opposite things.

### Expected
tempmin to be minimum, 
tempmax to be maximum,
Temperature range to be output.

### Steps to reproduce
1. Get in an exploration ship
2. Map a Class 1 Gas Giant (they're very common)
3. This will trigger the Body Mapped script, then Body report, then the necessary Body atmosphere report.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: N/A

### Investigation Notes
The details above are for the default personality as mine has other adjustments.

This was found when overhauling the scripts I've mentioned and in addition to those are many other adjustments to my EDDI personality, I'll be updating my post in the Github personality section, hopefully in the next week or so.

**Comment by Darkcyde13** [comment]
Good spot, I hadn't noticed it even after all the times I've gone over that script. ;)

That being said, when the two tempcalc lines are corrected, then the following line you mention does become correct too.  I can see why it was probably originally done that way, with it only being for tempmax, as the first part of that IF block, the gas giant Class V section, only uses 'tempmin'.  So it goes from Class V tempmin only, Class VI to II min & max, Class I tempmax only even though both are supplied.  I do agree that it would make sense to use both for Class I as well, as both are set up. :)

**Comment by CMDR-Evolution** [comment]
Thank you! I'm a QA Engineer for a living and try my best to cover all angles. I have to say, the work your team has done is truly astounding. You add so much to Elite and for many years, I've strongly felt Elite really wouldn't seem as fascinating without your great work. Without EDDI last year, I would've missed out on so much exploration money. I really think Frontier should have this on the launcher (and some other great tools too). Thanks for your feedback Darkcyde13.

**Comment by Darkcyde13** [comment]
You're welcome, although I'm not actually an official team member. :)  I'm more of an 'enthusiastic user' who has made more than a few contributions to the scripting over the years, along with ideas for the program, and reporting of bugs. ;)

The praise for the software must lay firmly with T'kael and Verticalblank (and the dearly departed Hoodathunk), without which EDDI just wouldn't exist after the original author (jgm) stopped developing it after not playing Elite anymore.

I do have to agree though, that Elite wouldn't be half as enjoyable without EDDI. :)
