### ISSUE TITLE
Grammar issue in system report (faction conflict state)

### ISSUE THREAD

**Issue by arancaytar** [EDCD/EDDI#2273]
## What's Wrong (please be as specific as possible)

When reading out the system state report in a system at war, there is sometimes a minor grammar issue.

### Expected

The sentences "{faction} are recovering after {being ahead in|being tied in} {a conflict} with {faction} for control of {station}" are grammatically correct.

### Observed

The sentences are instead "{faction} are recovering after {ahead in|tied in} {a conflict} with {faction} for control of {station}".

### Steps to reproduce
1. Go to a system with the above conflict conditions.
2. Listen to the system state report.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
* Localization [if applicable]
  * EDDI's language: English

### Investigation Notes

This is a consequence of using "are" / "will soon be" / "are recovering after" as interchangeable fragments. Only the first two work with both present tense (winning/losing/etc) and adjectives (ahead/tied). The latter takes an additional "being" to work.

We could use additional logic to insert "being" when needed, but it would likely be simpler to just say "were recently" instead of "are recovering after".

**Comment by Tkael** [comment]
`{ahead in|tied in}` simply doesn't belong when describing a past conflict. We should only apply that logic to current conflicts.
