### ISSUE TITLE
Module transfer - expected arrival 'days'

### ISSUE THREAD

**Issue by CMDR-Evolution** [EDCD/EDDI#2274]
A very small thing to mention here. In the 'Module transfer' script, it will only show days, hours and minutes but not a singular day, hour or minute (unlike the 'Ship transfer initiated' script which covers those).

### Expected - as shown in the 'Ship transfer initiated' script
```
    {if t_remaining > (60*60*24):
        {set t_days to floor(t_remaining/(60*60*24))}
        {if t_days > 1:
            {t_days} days,
        |else:
            1 day,
        }
        {set t_remaining to t_remaining-(t_days*(60*60*24))}
    }

    {if t_remaining > 3600:
        {set t_hours to floor(t_remaining/3600)}
        {if t_hours > 1:
            {t_hours} hours,
        |else:
            1 hour,
        }
        {set t_remaining to t_remaining-(t_hours*(60*60))}
    }

    {if t_remaining > 60:
        {if t_days || t_hours: and}
        {set t_minutes to round(t_remaining/(60),0)}
        {if t_minutes > 1:
            {t_minutes} minutes.
        |else:
            1 minute,
        }
    }
```

### Observed - as shown in the 'Module transfer' script
```
   {if t_remaining > (60*60*24):
      {set t_days to floor(t_remaining/(60*60*24))}
      {t_days} days,
      {set t_remaining to t_remaining-(t_days*(60*60*24))}
   }

   {if t_remaining > 3600:
      {set t_hours to floor(t_remaining/3600)}
      {t_hours} hours,
      {set t_remaining to t_remaining-(t_hours*(60*60))}
   }

   {if t_remaining > 60:
      {if t_days || t_hours: and}
      {set t_minutes to round(t_remaining/(60),0)}
      {t_minutes} minutes.
   }
```

### Steps to reproduce
1. Transfer a module which will take an amount of time containing a day / hour or minute within the total.
2. Replace the code segment for 'Module transfer' with the 'Ship transfer initiated' equivalent, as shown above then try again. 

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: [if applicable] 

### Investigation Notes
I found this while editing the script for my EDDI personality, then found a fix in the other script.

**Comment by Darkcyde13** [comment]
I've had a look over this and found my version of 'Ship transfer initiated' was old, before the update that adds the IF/ELSE parts for days, hours, minutes.

Checking it a bit further, I've realised the default still doesn't work properly.  I know this will be rare, but given times that are exact to the day/hour/minute (so 86400, 3600, and 60), results in 'odd' behaviour.  It says:

> Expected arrival in: 24 hours
> Expected arrival in: 60 minutes
> Expected arrival in:

OK, the 24 hours and 60 minutes are not strictly wrong, but any time less than 61 will result in that last line being spoken with no time.

I've gone over it, and I think I've come up with the correct code to make any situation be correct.  I've tested it quite a bit with various times, and all seem to result in the correct speech.  This is what I now have in my version of the script:

```
{if t_remaining:

    Expected arrival in:

    {if t_remaining >= (60 * 60 * 24):
        {set t_days to floor(t_remaining / (60 * 60 * 24))}
        {if t_days > 1: {t_days} days |else: 1 day }
        {set t_remaining to t_remaining - (t_days * (60 * 60 * 24))}
    }

    {if t_remaining >= 3600:
        {set t_hours to floor(t_remaining / 3600)}
        {if t_days:, }
        {if t_hours > 1: {t_hours} hours |else: 1 hour }
        {set t_remaining to t_remaining - (t_hours * (60 * 60))}
    }

    {if t_remaining >= 60:
        {if t_days || t_hours:, }
        {if t_remaining - (t_minutes * 60) = 0: and}
        {set t_minutes to floor(t_remaining / 60)}
        {if t_minutes > 1: {t_minutes} minutes |else: 1 minute }
        {set t_remaining to t_remaining - (t_minutes * 60))}
    }

    {if t_remaining > 0:
        {if t_days || t_hours || t_minutes:, and}
        {t_remaining} {if t_remaining = 1: second |else: seconds}
    }.
}
```
This now results in these:

> your Krait Mark 2 being transferred from Balante. Expected arrival in: 1 day, 1 minute, and 10 seconds.
> your Krait Mark 2 on its way from Balante. Expected arrival in: 1 day, 25 minutes, and 10 seconds.
> your Krait Mark 2 being transferred from Balante. Expected arrival in: 1 day, 1 hour, 1 minute, and 10 seconds.
> your Krait Mark 2 being transferred from Balante. Expected arrival in: 1 minute.
> your Krait Mark 2 being transferred from Balante. Expected arrival in: 55 seconds.
> 

I believe this can be used in the Module transfer script too.

EDIT: Updated the minutes and seconds code.  Now handles a single second.

**Comment by CMDR-Evolution** [comment]
Great work again Darkcyde13! I'll add your suggestions to my personality for sure. I barely need to make any module transfers but I may have a couple of modules I could transfer and test it with too. Certainly by the looks of it though, you've definitely made it better! o7

**Comment by Darkcyde13** [comment]
Hmm, I think I'm going to cut this code out of both scripts, and make it a separate script of it's own.  That way, any script that needs a report of 'time remaining' can access it, and it would be a central place to make any changes to if needed (instead of making the same change in multiple scripts). ;)

**Comment by Tkael** [comment]
Rather than always reporting seconds (which is more precision than I believe we need here), I think I'll use
```
    {if t_remaining >= 0:
        {if t_days || t_hours: and}
        {set t_minutes to round(t_remaining/(60),0)}
        {if t_minutes > 1:
            {t_minutes} minutes.
        |else:
            {if t_remaining < 60: less than} 1 minute.
        }
    }
```
