### ISSUE TITLE
Body report - Rotational period 'days'

### ISSUE THREAD

**Issue by CMDR-Evolution** [EDCD/EDDI#2275]
A very, very tiny last thing to mention here. In the 'Body report' script, it will only show days which applies for everything except one day. 

### Expected:
A day could be mentioned if one day applies.

### Observed :
All outputs will state 'days'

### Steps to reproduce
1. In the 'Body Report' script, have {set reportRotation to 1} chosen at the top of the script. 
2. Map a planet with a rotational period of one day.
3. A solution for this is to use something like this:
```
    		{if reportbody.rotationalperiod = 1:
    			{Humanise(round(reportbody.rotationalperiod, 1))} day
    		|else:
    			{Humanise(round(reportbody.rotationalperiod, 1))} days
    		}
```

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: [if applicable] 

### Investigation Notes
I found this while editing the script for my EDDI personality, then added the fix, tested it and it's working as expected.

**Comment by Darkcyde13** [comment]
How about this? The calculation only needs to be done once with this:
```
        {set days to Humanise(round(reportBody.rotationalperiod, 1))}
        rotational period of {days} {if days = 1: day |else: days}
```

It's also a bit shorter, and I do like my code to be compact where possible. ;)

**Comment by Darkcyde13** [comment]
'Body report summary' has the same problem. It could be fixed in a similar way, by setting a variable up to be 'day' or 'days' then adding that to the cat() for each part of the rotational period section. So something like this:
```
    {if reportbody.rotationalperiod < 0: {set retrograde to cat(" ", "retrograde", " ")} }
    {if reportRapidRotation && reportbody.rotationalperiodprobability:
        {set days to Humanise(reportBody.rotationalperiod)}
        {if cast(days, "n") = 1: {set days to cat(days, " day")} |else: {set days to cat(days, " days")} }
        {if !retrograde && reportbody.rotationalperiodprobability < 0.1:
            {set notables to cat(notables, [cat("an incredibly short rotational period of ", days)])}
        |elif !retrograde && reportbody.rotationalperiodprobability < 1:
            {set notables to cat(notables, [cat("an extremely short rotational period of ", days)])}
        |elif !retrograde && reportbody.rotationalperiodprobability < 3:
            {set notables to cat(notables, [cat("an unusually short rotational period of ", days)])}
        }
    }
```

**Comment by CMDR-Evolution** [comment]
> How about this? The calculation only needs to be done once with this:
> 
> ```
>         {set days to Humanise(round(reportBody.rotationalperiod, 1))}
>         rotational period of {days} {if days = 1: day |else: days}
> ```
> 
> It's also a bit shorter, and I do like my code to be compact where possible. ;)

Thank you @Darkcyde13 o7. 

> 'Body report summary' has the same problem. It could be fixed in a similar way, by setting a variable up to be 'day' or 'days' then adding that to the cat() for each part of the rotational period section. So something like this:
> 
> ```
>     {if reportbody.rotationalperiod < 0: {set retrograde to cat(" ", "retrograde", " ")} }
>     {if reportRapidRotation && reportbody.rotationalperiodprobability:
>         {set days to Humanise(reportBody.rotationalperiod)}
>         {if cast(days, "n") = 1: {set days to cat(days, " day")} |else: {set days to cat(days, " days")} }
>         {if !retrograde && reportbody.rotationalperiodprobability < 0.1:
>             {set notables to cat(notables, [cat("an incredibly short rotational period of ", days)])}
>         |elif !retrograde && reportbody.rotationalperiodprobability < 1:
>             {set notables to cat(notables, [cat("an extremely short rotational period of ", days)])}
>         |elif !retrograde && reportbody.rotationalperiodprobability < 3:
>             {set notables to cat(notables, [cat("an unusually short rotational period of ", days)])}
>         }
>     }
> ```

Wow, thanks a lot. Over the last few months I've added many variables in many of my scripts. The bond & bounty awarded scripts are almost made entirely from variables now. Funny you should mention that, today I'll be taking a look at this script too. I saw another bug / suggestion about temperatures and have actually already covered that in my body atmosphere report, but not yet applied it to body report summary. I won't waffle on about it here but will share my suggestion on that thread later. 

In the meantime, thanks again. Last thing is, although I've been getting better and better at EDDI coding recently, there's still a lot of advanced things I haven't learned yet. E.G. ` {if cast(days, "n") = 1: {set days to cat(days, " day")} |else: {set days to cat(days, " days")} }` ....
I would never of been able to think of that and can only hazard a guess at what it's doing lol. My solution would've been a lot more simple (due to my limited knowledge) with something like: 
```
{if reportBody.rotationalperiod != "", {set days to reportBody.rotationalperiod}
{if days = 1: {set days2 to "day"} |else: {set days2 to "days"}}
```
then
```
{if !retrograde && reportbody.rotationalperiodprobability < 0.1:
{set notables to cat(notables, [cat("an incredibly short rotational period of ", {days} {days2} )])}
```
P.S I used a similar approach to that in my body report summary script too - converting thousands of kilograms to tonnes and thousands of kilometers to megameters as I couldn't see how to set a variable to an integer and string.

I'll definitely use both of your great suggestions and hopefully they'll be implemented in the main build soon too. Cheers mate and fly safe o7

**Comment by Darkcyde13** [comment]
> In the meantime, thanks again. Last thing is, although I've been getting better and better at EDDI coding recently, there's still a lot of advanced things I haven't learned yet. E.G. {if cast(days, "n") = 1: {set days to cat(days, " day")} |else: {set days to cat(days, " days")} } ....
> I would never of been able to think of that and can only hazard a guess at what it's doing lol.

The reason I used cast() is because the preceding Humanise() converts the output to a string, instead of a number.  Cast() returns a variable as any given type where possible, and in this case 'n' converts it to a number so that it will then work in the check for =1.  I did consider other options, because _technically_ Humanise() could result in something like "just over 1" which I don't think would convert to a number.  However, Humanise() generally doesn't do anything with such small numbers that would impact this instance of it's use. :)

**Comment by CMDR-Evolution** [comment]
> > In the meantime, thanks again. Last thing is, although I've been getting better and better at EDDI coding recently, there's still a lot of advanced things I haven't learned yet. E.G. {if cast(days, "n") = 1: {set days to cat(days, " day")} |else: {set days to cat(days, " days")} } ....
> > I would never of been able to think of that and can only hazard a guess at what it's doing lol.
> 
> The reason I used cast() is because the preceding Humanise() converts the output to a string, instead of a number. Cast() returns a variable as any given type where possible, and in this case 'n' converts it to a number so that it will then work in the check for =1. I did consider other options, because _technically_ Humanise() could result in something like "just over 1" which I don't think would convert to a number. However, Humanise() generally doesn't do anything with such small numbers that would impact this instance of it's use. :)

Ah, thank you. I could almost certainly use that in other places too o7. 

> How about this? The calculation only needs to be done once with this:
> 
> ```
>         {set days to Humanise(round(reportBody.rotationalperiod, 1))}
>         rotational period of {days} {if days = 1: day |else: days}
> ```
> 
> It's also a bit shorter, and I do like my code to be compact where possible. ;)

I was just going to say this about your help from last night when I saw your comment just appear :), I couldn't get it working and was struggling to find the reason. It turned out reportBody should be lowercase so it's like:
`{Humanise(round(reportbody.rotationalperiod, 1))}`

I can confirm it's working now. Thanks again

**Comment by Darkcyde13** [comment]
> I was just going to say this about your help from last night when I saw your comment just appear :), I couldn't get it working and was struggling to find the reason. It turned out reportBody should be lowercase so it's like:
> {Humanise(round(reportbody.rotationalperiod, 1))}
> 
> I can confirm it's working now. Thanks again

Ah, yes, sorry, my bad. :)  In my personality, I've gone through it all and standardised variables and naming conventions as best I can.  In this case, I've changed the 'reportbody' to 'reportBody' as this is how many variables are used in other default scripts (or were when I last looked over everything to see what was best to use ;) ).

I try to put things back to 'default' when making bug reports and other suggestions, but this one slipped though the net. :)
