### ISSUE TITLE
Allow SetState() to set void variables

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2279]
## What happens now
Currently, SetState() will not set, or change, any variable if you attempt to set it to be 'void'.  The 'set' command does allow this for variables within the instance of the script execution.

So {set temp to void} works, but {SetState('temp', void)} does not.  If state.temp has previously been set, it will retain it's original value, and SetState('temp', void) will have no effect on it.

## What I'd like to happen 
Allow SetState() to be able to set a state variable to be 'void', effectively erasing the variable.  This is preferable to something like setting it to "" (an empty string) because that is still considered as being 'set', as a string, rather than non-existent as 'void' would be.  'void' allows a variable to be unset/undefined.

## How it can happen
Unfortunately, I don't know any C#, so I am unable to comment on how to achieve this.  My guess is that the SetState() function has checks to see if the value that it is trying to be set to, is "not void".  I've tried setting a local variable to void in a script, then setting a state variable to that, but that also doesn't work.

## EDDI Version
EDDI v4.0.1

**Comment by Tkael** [comment]
This may be possible. We need to make sure that we can make it work well with VoiceAttack.

**Comment by Darkcyde13** [comment]
Just an additional thought after a related discussion on the forums.  Attempting to set a state variable to `null` also has no effect, just like trying to set it to `void`.
