### ISSUE TITLE
Weapon mount code in module scripts no longer functions

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2281]
### Expected
The code to report weapon mounting type to work correctly.

### Observed
The code no longer functions.

### Steps to reproduce
1. Store a fixed/gimballed/turreted weapon.
2. Observe the script no longer says what the mounting is.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: V4.0.1
  * VoiceAttack Version: N/A 
* Localization [if applicable]
  * EDDI's language: British English
  * Voice: Ivona 2 Amy

### Investigation Notes
I had a copy of this particular code in another script, and realised it was no longer working as intended.  I don't need it anymore anyway, so I've deleted it, but I found the scripts where I copied it from, and discovered that it doesn't work in them either.

The code is this (taken from 'Module stored'):
```
{if type(event.module.mount) != "void":
    {for index, value in event.module.mount: {set mount to value}}
    {if mount = 0:
        fixed
    |elif mount = 1:
        giimballed
    |elif mount = 2:
        turreted
    }
}
```
I guess something changed at some point in the past that has rendered this code obsolete now, as `event.module.mount` actually contains the mount name.  This can be replaced simply to: `{event.module.mount}`

As 'gimballed' in English sound like 'jimballed', you could amend it to:
```
{if event.module.mount = "gimballed":
    giimballed
|else:
    {event.module.mount}
}
```
I've tested both these out in the Module stored script, and it now works as it used to, so I'm preferring the latter solution for the pronunciation.  Well, for English anyway, I guess just the bare variable would be ok for other languages.  Although... are there 'invariant' versions that could be used instead?

This applies to all the 'Module...' event scripts:

> Module purchased
> Module retrieved
> Module sold
> Module sold from storage
> Module stored
> Module swapped
> Module transfer
> Modules stored

I've tested my preferred solution in all the above, making variable name changes where necessary, and all work perfectly, correctly saying the mount type.  As 'mount' only applies to weapons, any other module type is blank (empty string).

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Darkcyde13** [comment]
I've also realised that in many of those Module scripts, you can update the checks for 'void' items.  So this code (example taken from Module stored): `{if type(event.cost) != "void":`  can be shortened to just `{if event.cost:`.  There a few examples of this in those scripts.  May as well update them at the same time. :)

**Comment by Tkael** [comment]
Thanks for this, looks like we inadvertently made a change which invalidated some code in the default scripts.

`giimballed` works for Ivona Amy but may not work equally well for other voices. 
Using https://github.com/EDCD/EDDI/wiki/Lexicons is an alternate solution.

**Comment by Darkcyde13** [comment]
> Thanks for this, looks like we inadvertently made a change which invalidated some code in the default scripts.
> 
> `giimballed` works for Ivona Amy but may not work equally well for other voices. Using https://github.com/EDCD/EDDI/wiki/Lexicons is an alternate solution.

Yes, 'giimballed' does work for Ivona Amy, however, I mentioned it because that's how it is spelled in all the default scripts:
```
{if type(event.module.mount) != "void":
    {for index, value in event.module.mount: {set mount to value}}
    {if mount = 0:
        fixed
    |elif mount = 1:
        giimballed
    |elif mount = 2:
        turreted
    }
}
```
Running a few tests with all the voices I have installed (Ivona Amy, MS George, MS Hazel, MS Susan, and MS Desktop Zira), they all say 'jimballed' for 'gimballed', except Zira, which does sound correct.  Using 'giimballed' works for Amy, but not the others.  However, I found that using 'ghimballed' instead, makes it sound correct in all the voices, although Zira does put a slight inflection on the 'all' part.  I'm guessing this is why the defaults used the double 'i' spelling in the first place, because the Windows default voices don't pronounce it properly.  Using 'h' is the best fit, as it works better than 'i' or the plain 'gimballed', in all the Windows default voices.

**Comment by Darkcyde13** [comment]
Hmm, I can't seem to get the Ivona lexicon working.  I've followed the instructions on the link you gave, but I'm still getting 'jimballed'.  I have this in the Ivona Lexicon:
![image](https://user-images.githubusercontent.com/24360725/140148758-b870b451-1b99-4833-9961-4b25581a0b6b.png)
I thought I'd followed the instructions properly, but is there anything else I need to do?

**Comment by Tkael** [comment]
I'm not sure why the lexicon editor isn't working. You seem to be using a different version of the lexicon editor than I am so I cannot replicate your conditions exactly.
You might try removing the \<speak\> tags?
In your editor, is the input case sensitive (i.e. is "Gimballed" distinct from "gimballed")?

**Comment by Tkael** [comment]
For reference, here are some screenshots showing my access route and my Ivona lexicon editor:
https://github.com/EDCD/EDDI/blob/develop/images/lexicons-Ivona1.png
https://github.com/EDCD/EDDI/blob/develop/images/lexicons-Ivona2.png
https://github.com/EDCD/EDDI/blob/develop/images/lexicons-Ivona3.png

**Comment by Darkcyde13** [comment]
My version of Ivona is (as far as I was aware) the last commercially available version from Ivona (the company).  By that I mean the last version you had to download an installer of about 270Mb.  After my version, I believe Ivona changed their distribution model and website (and distributor I think as it's now Harpo software).  This was back in about 2015, so my version is quite old now, and there are no updates for it, even though Ivona continues to be updated for the versions that came after it.  My version is '1.6.70 Aug 25 2014', and this can't be updated with the versions from Harpo software.  Under 'Voice selection' it's listed as "IVONA-2 Amy - British English female voice [22kHz]", whereas I see yours is just "IVONA 2 Amy OEM".

Anyway, I've given it another go, and to my surprise, 'gimballed' is now working in the Lexicon, although I don't know how.  I made a change to the lexicon command, to see if it would change in EDDI, but it doesn't.  Even after a reboot, Ivona still seems to be using `<speak><phoneme alphabet="ipa" ph="ɡɪmbəlɗ">gimballed</phoneme></speak>` even though I changed the word to 'gimbaed' in the command.  EDDI is still saying 'gimballed' correctly.  I am mystified as to how it is still 'working' when it technically shouldn't.  I've even tried just adding 'ghimballed' (and 'ghimbal') rebooting to restart the speech engine, and they don't work.  I've also tried with different case too, but still nothing.  It's like the lexicon is having no effect, and somewhere between my posts above, and today, it started using the lexicon command. but still refuses to acknowledge any amendment to the lexicon commands.

As for your screenshots, yes that's exactly how I get to my version too.

**Comment by Darkcyde13** [comment]
I've downloaded the latest version of Ivona from Harpo software to try out.  It's only a 30 day trial though, but it does say "IVONA 2 Amy OEM" like yours.  I've added the lines to the lexicon, and they work perfectly fine first time.  So it seems that it's something to do with the older version I have.  I may have to invest in the new version, but I don't like the idea of having to buy the same thing again when the one I have works fine, albeit with an annoying quirk with the lexicon. 😒

**Comment by Tkael** [comment]
A version number for my copy is a little difficult to find, but as you can see / guess my version came from Harpo.

The minimal change required to correct this is to change `.mount` to `.Mount` in the scripts so that the enum resolves properly. That said, I think I'm going to take the opportunity to rework this into a proper localizable variable rather than an enum.
