### ISSUE TITLE
cat() function trims spaces and doesn't evaluates internal functions

### ISSUE THREAD

**Issue by Transcan** [EDCD/EDDI#2287]
## What's Wrong
Cottle function cat() trims spaces of string inputs, it removes whitespace from both sides of the input strings.
It also doesn't evaluate functions inside string inputs

### Expected
It should not trim the inputs, and it should evaluate the functions inside the strings.

### Observed and Steps to reproduce
This example code from my Bond Awarded script:

```
{set recompensa to cat(
   "{Humanise(event.reward)} créditos",
   OneOf(" ganados", " otorgados", " recibidos"),
   Occasionally(1, " en bonos de combate"),
   Occasionally(1, " de {Occasionally(1, 'la facción')} {P(event.victimfaction, 'faction')}")
)}

{recompensa}.
```
(Occasionally is set to 1 for the purpose of the test)

The expected output should be something like this:
`500 créditos otorgados en bonos de combate de la facción Lencali Freedom Party.`

But the output you get is this:
`{Humanise(event.reward)} créditosotorgadosen bonos de combatede la facción Lencali Freedom Party.`

Note that the Humanise() function is not evaluated, and there are no spaces between each inputs strings even though they are specified in the code.

I don't know if is a Cottle problem or if its the implementation of that function in EDDI that is not working properly...

### Configuration
* EDDI Version: v4.0.1
* Localization (I guess is language invariant, but just in case)
  * EDDI's language: spanish
  * Voice: Microsoft Ana (Spanish)

**Comment by Darkcyde13** [comment]
To put something like that together, I think you need to implement the commands slightly differently.  You shouldn't need to put `Humanise()` inside quotes like that, and you do need to add spaces between the elements.  Use this, it works just as you intend. :)

```
{set recompensa to cat(
   Humanise(event.reward), " ", "créditos", " ",
   OneOf("ganados", "otorgados", "recibidos"), " ",
   Occasionally(1, "en bonos de combate"), " ",
   Occasionally(1, "de {Occasionally(1, 'la facción')} {P(event.victimfaction, 'faction')}")
)}

{recompensa}.
```

> zero créditos ganados en bonos de combate de la facción.

`cat()` is a native Cottle command, and it trims whitespace automatically.  I don't know if this is something that EDDI can 'fix' or not.

**Comment by Tkael** [comment]
Indeed, `cat()` is a native Cottle command. I'm not sure that we have a way to force it resolve custom functions like `Humanise()`. As far as trimming whitespaces is concerned, there is one configuration setting that I might be able to play with but I'm not sure that it would resolve the trimming within `cat()` or that there wouldn't be other impacts from changing the setting. We'll probably need to run some experiments.

**Comment by Darkcyde13** [comment]
I've had a quick look into this, as I was sure I was able to use whitespace in some of my code somewhere.  Indeed, I do use `cat()` with whitespace in some places, so I was curious to see what conditions it does and does not work in.  As far as I can tell at the moment, whitespace will work, but not when used in another command.

So, these work (just as an example):
```
{set recompensa to cat(
   Humanise(event.reward), " créditos ",
   "ganados ", "otorgados", " recibidos"
)}
{recompensa}.
```
> zero créditos ganados otorgados recibidos.

But these don't (whitespace is removed):
```
#{OneOf(" ganados ", " otorgados ", " recibidos ")}#
#{Occasionally(1, " en bonos de combate ")}#
```
> #ganados# #en bonos de combate#

So, by these results, it's not `cat()` that is removing the whitespace, it's the other commands.  Either `OneOf()` & `Occassionally()` need to be updated to keep whitespace, or you will need to add extra whitespace as in my previous example.

Although, with this information, you can slightly alter the first line to be: `Humanise(event.reward), " créditos ",` instead.


EDIT:  It seems that Cottle will trim down extra whitespace automatically to only one space, like this:
```
{set test to "      ganados        "}
#{test}#
```

> `# ganados #`

(I had to make this look like code as Github uses "hash space" to increase font size)

So, as `OneOf()` and `Occassionally()` are EDDI commands (not Cottle) maybe changing these will be much easier.  It would be nice if they could also collapse extra whitespace to only one as well, like Cottle can. :)

**Comment by Transcan** [comment]
> So, by these results, it's not `cat()` that is removing the whitespace, it's the other commands. Either `OneOf()` & `Occassionally()` need to be updated to keep whitespace, or you will need to add extra whitespace as in my previous example.
>
> So, as `OneOf()` and `Occassionally()` are EDDI commands (not Cottle) maybe changing these will be much easier. It would be nice if they could also collapse extra whitespace to only one as well, like Cottle can. :)

Yes, I made some experiments too, and found out the same: Is not cat() the one that trims white spaces, but the other, EDDI custom, functions.

It would be great if the custom functions behave the same as the rest of cottle functions. As we know now:
Trimming extra white spaces to leave only one.

The other 'problem' with not evaluating functions inside strings can be solved as you said in the first comment. Thanks for the tip.
Knowing that its how it works, I can code in other ways. There is no need to bother trying to make it work.

**Comment by Tkael** [comment]
It's not exactly Cottle - collapsing blank characters is actually happening in EDDI after the script passes through Cottle's rendering engine. That said, there may be an extra trim on custom functions that doesn't need to be there. Looking.

**Comment by Tkael** [comment]
Aha! That same collapse and trim function was being applied to each custom function as well as to the script as a whole. I'll patch it so that the function is only applied at the top level final render.

**Comment by Darkcyde13** [comment]
Hmm, so would I be correct in thinking that this could actually speed up scripts a little bit?  I mean, if that trim function only needs to be done once on the whole script, rather than on every function, then that should be a whole lot of 'trims' that don't get processed anymore (depending on how many functions are used in a script, of course).

So, tidying up the output, and making it more efficient.  Sounds like a win-win to me! 😀 👍

**Comment by Tkael** [comment]
Very slightly but yes. :-)
