### ISSUE TITLE
Variable {TXT:Ship fuel tank drive grade} not functioning

### ISSUE THREAD

**Issue by ArNeo-VR** [EDCD/EDDI#2288]
## What's Wrong (please be as specific as possible)
Output is 'Not set' and stays 'Not set'

### Expected
Depending on the ships fuel tank grade: C [A..F]

### Observed
Either only the main tank or an optional module: tank bought. Output is 'Not Set' 
Variable {INT:Ship fuel tank class} does give a result 5

### Steps to reproduce
1. Start Elite Dangerous go into ship.  
2. Check the variable.

### Configuration
* Version
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.8.9
* Localization en-us
  * EDDI's language: English
  * Voice: Ivona 2 Kendra [English]

### Investigation Notes
Equiping an additional Fuel tank.
Checked the other type variable INT / SMALL / DEC / BOOL all are 'Not set'
Changing the fuel-tank module and back, output stays 'Not set'

### EDDI Logs
No info found regarding this issue.

### Player journals
{ "timestamp":"2021-11-20T12:28:18Z", "event":"Loadout", ... ... , { "Slot":"FuelTank", "Item":"int_fueltank_size5_class3", "On":true, "Priority":1, "Health":1.000000, "Value":81013 }, ...

edit: added changing module.

**Comment by Tkael** [comment]
Hmm. That module name looks like it might be off in the docs. Have you tried `{TXT:Ship fuel tank grade}`?
