### ISSUE TITLE
Limpet check script doesn't recognize multi limpet controllers

### ISSUE THREAD

**Issue by Vip3rak** [EDCD/EDDI#2298]
### Steps to reproduce
1.  Install multi limpet controller on ship
2. Click "test" on limpet check script.

### Expected
EDDI to remind me to buy limpets.

### Observed
Script either doesn't remind about having no limpets on board or reports having limpets but no controller.

### Configuration
  * EDDI Version:  4.0.1
  * EDDI's language: English

## My Investigation
Tried Mining, Rescue and Operations Multi Limpet Controllers. Script didn't recognize any of them.
Standard Collector Limpet Controllers are recognized properly.

**Comment by Tkael** [comment]
Already implemented for the next release. o7 cmdr
