### ISSUE TITLE
Frontier API authentication is spawning a second instance of EDDI

### ISSUE THREAD

**Issue by ghost** [EDCD/EDDI#2300]
## What's Wrong (please be as specific as possible)
When trying to connect EDDI to Frontier, EDDI launches a browser instance, that directs to the Frontier Auth. service page. After login, a new instance of EDDI is launched. This causes an error stating that "Only one instance of EDDI can run at a time. Please close other instance and try again." 
Thus, the connection to the API cannot be properly established.

### Expected
Tthe connection to the API properly established.

### Observed
See under "What's wrong" above.

### Steps to reproduce
See under "What's wrong" above.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.8.9 (though VA is closed during this action).
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
This has been tested with Chrome, FireFox and Edge. Testing has been done with EDDI and browser session started both normally and run by Administrator.

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
This is typically caused by a registry issue. Have you tried reinstalling EDDI?

**Comment by ghost** [comment]
Hi TKael - and thank you for replying.

Yes, I've tried to reinstall on top of the original installation. When that didn't solve the issue I uninstalled EDDI and reinstalled it. Issue still occurs.
Should I cleanup the Registry after uninstall? If so, can you list the REgistry key that needs to be removed, or should I simply "search and destroy" for anything EDDI?

**Comment by ghost** [comment]
Ok, problem solved.

First, I uninstalled v.4.0.1, and then installed v.3.5.2 (it was the latest previous version I had available at hand). 

At statup EDDI informs that a mandatory update is available, but I could still access the Frontier API configuration tab. However, I was warned that EDDI ran in Administrator mode, and that it could affect the communication between the browser and EDDI. I tried anyway and got the issue of the browser wanting to spawn another EDDI instance.

I they examined the properties for EDDI (through the Desktop shortcut), and the "Run this program as an administrator" option  was ticked (I had not done this manually, but I started the installation package as administrator, which might have provoked this?). I unticked the "Run this program as an administrator" option, launch EDDI and then were able to successfully connect to Frontier API.

Final step was to install EDDI v.4.0.1 as a normal user (which I'm quite sure I also did in the first initial installation of v.4.0.1). Now, when starting EDDI, the Frontier API is still connected.

**Comment by Tkael** [comment]
Yes, I'm remembering now that administrator mode can make a difference (EDDI and the browser need to be running in the same mode). Nice sleuthing.  o7
