### ISSUE TITLE
Incurred bounty not reset after paying at interstellar factor

### ISSUE THREAD

**Issue by Perlig** [EDCD/EDDI#2308]
How to repeat:
- incur a bounty for shooting at a clean ship
- jump to another system with an interstellar factor and pay bounty there
- return to original system or another system with the same controlling faction
- "Crime check system" script warns "You are wanted in this system"
- Crime monitor still lists the bounty although paid

Workaround:
- Manual deletion

```
{ "timestamp":"2022-01-15T18:37:38Z", "event":"CommitCrime", "CrimeType":"assault", "Faction":"Radio Sidewinder Crew", "Victim":"Jim Grady", "Bounty":100 }
{ "timestamp":"2022-01-15T18:37:38Z", "event":"CrimeVictim", "Offender":"waylongway", "CrimeType":"assault", "Bounty":100 }
{ "timestamp":"2022-01-15T18:37:40Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"ferdelance", "Ship_Localised":"Fer-de-Lance", "ScanStage":3, "PilotName":"$npc_name_decorate:#name=Jim Grady;", "PilotName_Localised":"Jim Grady", "PilotRank":"Deadly", "ShieldHealth":91.894226, "HullHealth":100.000000, "Faction":"Values Party of Na Chem", "LegalStatus":"Clean" }
...
{ "timestamp":"2022-01-15T18:39:10Z", "event":"FSDJump", "StarSystem":"Anindari", "SystemAddress":5069269575105, "StarPos":[18.09375,42.53125,72.00000], "SystemAllegiance":"Independent", "SystemEconomy":"$economy_Terraforming;", "SystemEconomy_Localised":"Terraforming", "SystemSecondEconomy":"$economy_Refinery;", "SystemSecondEconomy_Localised":"Refinery", "SystemGovernment":"$government_Corporate;", "SystemGovernment_Localised":"Corporate", "SystemSecurity":"$SYSTEM_SECURITY_low;", "SystemSecurity_Localised":"Low Security", "Population":242357, "Body":"Anindari A", "BodyID":3, "BodyType":"Star", "JumpDist":26.412, "FuelUsed":6.214149, "FuelLevel":23.525852, "Factions":[ { "Name":"LHS 53 Exchange", "FactionState":"None", "Government":"Corporate", "Influence":0.144444, "Allegiance":"Federation", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Blue Central Group", "FactionState":"None", "Government":"Corporate", "Influence":0.501010, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":30.000000 }, { "Name":"Anindari Mob", "FactionState":"CivilUnrest", "Government":"Anarchy", "Influence":0.011111, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000, "ActiveStates":[ { "State":"CivilUnrest" } ] }, { "Name":"League of Tukur", "FactionState":"Retreat", "Government":"Confederacy", "Influence":0.022222, "Allegiance":"Federation", "Happiness":"$Faction_HappinessBand3;", "Happiness_Localised":"Discontented", "MyReputation":0.000000, "RecoveringStates":[ { "State":"Blight", "Trend":0 } ], "ActiveStates":[ { "State":"Famine" }, { "State":"CivilUnrest" }, { "State":"Retreat" } ] }, { "Name":"Progressive Party of Anindari", "FactionState":"None", "Government":"Democracy", "Influence":0.097980, "Allegiance":"Federation", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Anindari League", "FactionState":"None", "Government":"Dictatorship", "Influence":0.129293, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Anindari Network", "FactionState":"None", "Government":"Corporate", "Influence":0.093939, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000, "RecoveringStates":[ { "State":"PublicHoliday", "Trend":0 } ] } ], "SystemFaction":{ "Name":"Blue Central Group" } }
...
{ "timestamp":"2022-01-15T18:41:31Z", "event":"PayBounties", "Amount":100, "Faction":"$faction_Independent;", "Faction_Localised":"Independent", "ShipID":38, "BrokerPercentage":25.000000 }
```

**Comment by Darkcyde13** [comment]
I believe this is a known 'problem', and it's not EDDI's fault.  For EDDI to clear any paid fines or bounties, it has to match the payment to the record in the monitor.  To do this, it needs to know the amount and the faction(s) involved, so that it can delete the correct entry.

As you can see in your Journal logs, when paying the fine, there is no faction listed (it just says 'Independent').  This means EDDI is unable to make a match to the entry in the monitor (for 'Values Party of Na Chem'), and so can't delete it.  Manual deletion is the only way this can be resolved.

Most of the time, there are factions listed in the Journal entries, but sometimes they are not.  FDev needs to make sure there is a list of factions paid off in the Journal entry, before EDDI can automatically remove it.

**Comment by Perlig** [comment]
I'm aware of the data deficiency in the PayBounties event. Let's not view it as a bug report, but a feature request.

There is some data included, specifically the amount of the bounty. In many/some cases it can be deduced which bounty has been paid. Simply going through the list of incurred bounties, find a matching entry with this value, and if it's the only one with this value, delete it. Otherwise, ignore the event or better yet, give a warning/notification.

**Comment by Tkael** [comment]
The trouble is that there is often no single entry that matches the value paid so no easy identification can be made (you might have other 100 cr bounties recorded, with only that single data point we may not be able to match the payment to the record).

**Comment by Tkael** [comment]
Essentially, I think that what is occurring is that some crimes are being converted to superpower bounties but no journal event records that transaction / conversion.

**Comment by Tkael** [comment]
The circumstances that trigger that conversion are unclear, but certainly seem to be more common in Odyssey than in Horizons.

**Comment by Perlig** [comment]
It will certainly not be possible to cover all cases. But at least for my playstyle, where I have usually only one bounty when I pay it at an interstellar factor, it would solve the problem to 100%. And the proposed solution is pretty simple.
