### ISSUE TITLE
Installed tts voice from Cereproc and volume goes loud randomly

### ISSUE THREAD

**Issue by Ageingjedi** [EDCD/EDDI#2309]
## What's Wrong (please be as specific as possible)
Installed Caitlin tts voice from Cereproc and volume goes loud randomly when using EDDI
### Expected
[Describe what you expected to happen]
Volume for installed tts voice to remain level
### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]Caitlin English Irish accent

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
I'm not sure how to replicate this? Is Caitlin always loud in EDDI or only sometimes?

**Comment by Tkael** [comment]
If you switch to different speakers, does this still occur?

**Comment by Ageingjedi** [comment]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/7876763/eddi_issue.zip)
Hi. Thanks for the reply. Have seen I can attach an output from EDDI for you. Issue occurs when on headset or on but in speaker.

It is the volume level not being constant when EDDI talks during a game of ED. If I'm scanning planets, I get a lot of speech from EDDI about planets, and intermittently, the volume can go up a notch then back down. Is that just a feature of the EDDI app? Have attached screenshot of my setting for text to speech. Am running windows 10. Thank you.
![Screenshot 2022-01-16 104653](https://user-images.githubusercontent.com/97809371/149656835-ea011f82-5299-49c3-b9c6-f0b642cb9356.png)

**Comment by Tkael** [comment]
Thank you for the logs and screenshot. Unfortunately, I'm not able to find anything amiss in either. 🤔 

While it is possible to affect speech volume with commands in the Speech Responder, I expect that you're probably using the default scripts. If you are using your own personality... 
- Are there specific scripts that are always loud? 
- Does the problem persist if you switch to the default personality?

**Comment by Ageingjedi** [comment]
Thanks for checking this out. Am not knowledgeable enough to use anything but the defaults. Suspect it may be a quirk of the tts voice I purchased from Cereproc and is not terrible, just a bit annoying that the volume doesn’t stay at the same level. EDDI works well otherwise and is a good app to have when doing long expeditions in ED. Just needed to change from the default windows tts voices. Please feel free to close this now.
