### ISSUE TITLE
Add option to start minimized?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#231]
EDDI would need to go the system tray.

**Comment by richardbuckle** [comment]
I tried to find UI guidance on whether to use the system tray. MS seem to be encouraging apps that have a desktop presence to minimise to the taskbar instead and maybe use a Jump List or thumbnail toolbar: [MSDN article](https://msdn.microsoft.com/en-us/library/dn742495.aspx?f=255&MSPPError=-2147217396).

Thoughts welcomed.

**Comment by Tkael** [comment]
Alright. After reviewing, I'm on board with starting minimized to the taskbar. Perhaps jump lists could eventually be used to switch personalities. 🙂

**Comment by richardbuckle** [comment]
This is probably one of those areas where decisions either way will be criticised and we will just have to be prepared for that.

**Comment by Tkael** [comment]
Closed pending approval of #299. PR #299 does not add a checkbox to the UI for starting minimized, but it does remember whether EDDI was minimized when closed and restores that condition.
