### ISSUE TITLE
Event responder or internal webpage server that provides a ship "dashboard"

### ISSUE THREAD

**Issue by Deadweasel** [EDCD/EDDI#2310]
## What happens now
EDDI talks and handles data movement between journals and status files and external concerns such as EDDB and Inara as usual

## What I'd like to happen 
I already use EDDI with every E:D session, and I've been also attempting to create a touchscreen dashboard for additional info that isn't so quick or easy to review in-game, but EDDI is already reading these elements; I just need a non-redundant method of getting that info out to a visual medium, not just vocal read-offs of potentially long lists of items.  An additional "responder" that serves up a customizable webpage, with elements that update themselves as journal and status file contents change would be perfect.

## How it can happen
Implemented as another independent responder, accessed from another device on the local network via web browser, and utilizing javascript or even Node.JS to allow for individual element updates, rather than whole-page refresh.  

## EDDI Version
4.0.1

Dashboard concept
![Screenshot 2022-01-18 090029](https://user-images.githubusercontent.com/1332439/150001589-feb50797-8a09-4eb3-bfcd-62972927feac.png)

**Comment by Tkael** [comment]
EDDI focusses on providing feedback primarily via audio rather than via panels. I don't think this suggestion is something that is within the scope we're maintaining for this project. If you're looking for a plugin interface for your dashboard then EDDiscovery or EDMC might be better options?

What problem is the dashboard attempting to solve exactly?

**Comment by richardbuckle** [comment]
I agree that it's out of scope for EDDI. It is a great idea but I think EDMC or EDDiscovery would be a better platform.

**Comment by richardbuckle** [comment]
There is also the GameGlass stuff if you want to save the time.

**Comment by Deadweasel** [comment]
Ah, I understand, but thanks for at least considering it! ;)

Currently the dashboard is just an interactive touchscreen that's trying to provide more at-a-glance info than some of the other projects out there.  Eventually I'd like to have it providing a comprehensive ship status overview that makes it quick and easy to see the detailed status of modules and functions.
In combat, I might be able to see more quickly that a given module is being targeted based on how quickly its integrity is going down.  Or in exploration, I can look over and quickly check to see if I need to make a repair pitstop before I get stranded somewhere in the black. Basically providing more info from the cockpit side panels on a separate screen without forcing me to navigate to those panels in-game.

By and large, it's really just a hobby project to improve that immersion factor, but I'm reluctant to create/install another service to read the journal and status files.  I had hoped maybe EDDI already had some sort of mechanism to emit flags or objects that an external service or client could read instead, but I understand that's a gateway to feature creep in EDDI's case, too! :)

Thanks again!

**Comment by Tkael** [comment]
It is probably worth noting that EDDI does not have real-time information on module integrity values. FDev have asked us to use the Frontier API endpoint (which is the sole source of that information) sparingly so we typically update information from the Frontier API when you dock.
