### ISSUE TITLE
Speech Responder Currently Active

### ISSUE THREAD

**Issue by dukenewcombe** [EDCD/EDDI#2311]
## What happens now
Within voice attach you can "wait until the command is finished"; however when I use the external plugin, using the say context only takes a (arbitrary) second. Say I want to get two reports, but the second should be 15 secs after the first one, I don't see a way to achieve this... currently if I place a pause in VA it will be 15 secs from what is essentially the start of the first message and not the end.

## What I'd like to happen 
I'd like to be able to use the end of the message as a starting point for the subsequent actions.

## How it can happen
A simple boolean with is the TTS actively saying something.

## EDDI Version
4.0.1

**Comment by Tkael** [comment]
Check this out?
{BOOL:EDDI speaking}: true if EDDI is currently speaking

**Comment by dukenewcombe** [comment]
I hadn't seen that one in the wiki, but definitely what I need. Brilliant!

Love your work mate!
