### ISSUE TITLE
Engineer Contributed missing variables

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2313]
### Expected
Engineer Contributed to correctly report the materials used to unlock an engineer.  Specifically the Sensor fragments for Chloe Sedesi.
Expected "Chloe Sedesi thanks you for contributing 25 units of Sensor Fragments"

### Observed
The script resulted in "Chloe Sedesi thanks you for contributing of.", missing the amount, units, and the item contributed.

### Steps to reproduce
1. Hand in 25 Sensor Fragments to Chloe Sedesi.
2. Listen to the result of the Engineer contributed event script.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: UK English
  * Voice: Ivona Amy

### Investigation Notes
I have the speechresponder.out file open in Notepad++ so I can see what's being spoken as well as hear it.  I've finally got around to opening up Chloe Sedesi, and when I handed in my contribution to Chloe, I got "Chloe Sedesi thanks you for contributing of."  It is missing most of the data.

Unfortunately, she was the last (main) engineer I had left to open, and I find the on-foot ones too much trouble to try, so I'm not able to try it again with another engineer.

### EDDI Logs
The log has no entries for this.

### Player journals
Relevant section from the Journal 
```
{ "timestamp":"2022-02-02T23:13:17Z", "event":"EngineerContribution", "Engineer":"Chloe Sedesi", "EngineerID":300300, "Type":"Materials", "Material":"unknownenergysource", "Material_Localised":"Sensor Fragment", "Quantity":25, "TotalQuantity":25 }
{ "timestamp":"2022-02-02T23:13:18Z", "event":"EngineerProgress", "Engineer":"Chloe Sedesi", "EngineerID":300300, "Progress":"Unlocked", "Rank":1 }
```

**Comment by Tkael** [comment]
Thanks for reporting. This will be fixed in the next update. o7
