### ISSUE TITLE
EDDI crashing VA

### ISSUE THREAD

**Issue by conorb69** [EDCD/EDDI#2314]
## What's Wrong (please be as specific as possible)
Voice attack randomly crashing with no notification. Only happens when I have EDDI plugin running and when I jump. I'm running version 4.01 of EDDI and have tried bothe stable and beta release of VA. Have uninstalled and reinstalled EDDI, HCS Voice pack and VA but the issue persists. I'm running Horizons (No Oddysey).

### Expected
EDDI to remain stable when jumping

### Observed
Error logs from EDDI and VA attached
[eddi.log](https://github.com/EDCD/EDDI/files/8003474/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/8003475/eddi1.log)
[VoiceAttackFault.txt](https://github.com/EDCD/EDDI/files/8003476/VoiceAttackFault.txt)

### Steps to reproduce
Appears to be random but invariably the crash occurs when jumping.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.01
  * VoiceAttack Version: 1.9.9.88
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Ivona Amy

### Investigation Notes
I have run VA without the EDDI plugin and have experienced no crash.

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]
[eddi1.log](https://github.com/EDCD/EDDI/files/8003490/eddi1.log)

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at

 [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
The timestamps for the VoiceAttack and EDDI logs don't sync up. When did the crash actually occur?

EDDI is typically quite good about logging exceptions that lead to a crash. There is nothing in the EDDI logs that would indicate a fault in EDDI precipitated a crash.

The VoiceAttack logs point to an exception that occurred during an invokation and speech recognition.

If you disable the VoiceAttack commands that you have running during a jump or use a different VoiceAttack profile, does the crash still occur?

**Comment by conorb69** [comment]
Thanks Brian - I'll try with a different profile and let you know.

**Comment by Tkael** [comment]
Hi @conorb69, any updates?

**Comment by conorb69** [comment]
I've tried using my own VA profile and with the EDDI plugin enabled and it seems to work fine now. Done about 40 jumps with no issues. It seems it may be an HCS issue rather than EDDI. Would be grateful if you could please close this issue. Thanks.

**Comment by Tkael** [comment]
Done. o7
