### ISSUE TITLE
EDSM error received: Commander name/API Key not found

### ISSUE THREAD

**Issue by barateza** [EDCD/EDDI#2323]
I see this error comes from time to time but I'd like to report anyway to understand whether this is an error on EDSM side or EDDI.

Verbose log is attached.

[eddi_issue.zip](https://github.com/EDCD/EDDI/files/8102711/eddi_issue.zip)

**Comment by Tkael** [comment]
Here's what I'm finding in the log:
`2022-02-19T17:54:34 [Warning] StarMapService:SetEdsmCredentials EDSM Responder not configured: API key not set.`

It looks like you have not fully configured the EDSM responder. This means that we cannot synchronize your flight log from your EDSM account. If you do not have an EDSM account or do not wish to synchronize flight logs then you can safely disregard this.

o7
