### ISSUE TITLE
DiamondbackX showing up as AspX on ship list

### ISSUE THREAD

**Issue by Thedoczek** [EDCD/EDDI#2325]
### Expected
Is should appear as Diamondback Explorer

### Observed
It appears as Asp Explorer
![image](https://user-images.githubusercontent.com/69758777/154838581-42a1a7c2-8392-4872-87a0-bcb9c0bdcd4f.png)
On this image, Gozov Ratter is my exploring ship, and is a Diamonback Explorer. Yastarn Miner is my mining ship and is normal AspX. Both ships show up as Asp.

### Steps to reproduce
1. Buy DX
2. Buy AspX
3. Park them somewhere
4. Open ship list
5. done

### Configuration
* Version
  * EDDI Version: 4.0.1
* Localization
  * EDDI's language: English

**Comment by Tkael** [comment]
I don't suppose you might have two separate accounts for Elite Dangerous? Your shipyard data could become corrupted if you switch Frontier API accounts or sign in using an account which doesn't match your active commander.

Best fix if this has occurred is to navigate to `%AppData%/EDDI` and delete `shipmonitor.json` while EDDI is not running. The file will be rebuilt the next time you run EDDI.
