### ISSUE TITLE
JournalMonitor:ParseJournalEntry Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by barateza** [EDCD/EDDI#2326]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/8121268/eddi_issue.zip)

I am receiving the errors below on the verbose log:

`JournalMonitor:ParseJournalEntry Object reference not set to an instance of an object.`
`ScriptResolver:resolveFromValue Exception has been thrown by the target of an invocation.`

I noticed it via the text-to-speech feature, the AI started talking about errors and exceptions. I can notice the error:

- Before FSD countdown
- When entering an station
- When accessing the market.

Any attention is appreciated.

**Comment by Tkael** [comment]
```
JournalMonitor:ParseJournalEntry Object reference not set to an instance of an object.
```
This is an exception that is thrown for commanders running Horizons. A fix has already been implemented and is pending release.

```
 ScriptResolver:resolveFromValue Exception has been thrown by the target of an invocation.
```
A Windows system exception appears to have occurred. You might want to revalidate your windows installation files to verify that Windows files have not become corrupted. See <https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e>
