### ISSUE TITLE
Error with FSD engaged 

### ISSUE THREAD

**Issue by M4DMAXX** [EDCD/EDDI#2330]
I got this Error:

Error with FSD engaged script: Exception has been thrown by the target of an invocation.

I read in an older forum post that not setting a Homesystem can cause this but it dont help me.

I used EDDI and a German Profile since 2 years. But now i wanted to change to english. 

I use the Zira Voice and the default EDDI Profile.

**Comment by M4DMAXX** [comment]
https://pastebin.com/JjpgHBk3 Here the log file

**Comment by M4DMAXX** [comment]
https://controlc.com/15fa3c96 Log file

**Comment by Tkael** [comment]
I don't think it has anything to do with setting your home system. The materials data associated with the star system appears to have been in an invalid state but the cause of the invalid state is unclear. I'll have to think about potential causes.

**Comment by Tkael** [comment]
I believe this is a known issue which has already been resolved for the next release by www.github.com/EDCD/EDDI/commit/34234d9a875b704fd21bfb7b8c3aa362b25a5f91. o7 commander

**Comment by M4DMAXX** [comment]
Thx
