### ISSUE TITLE
EDDI 4.0.1 crashing VoiceAttach when running as a plugin

### ISSUE THREAD

**Issue by Wolfang42** [EDCD/EDDI#2331]
EDDI 4.0.1 runs just fine in standalone mode.  It is installed in the APPS folder of VoiceAttack. However, when loading VoiceAttack, it crashes to desktop after trying to load in the EDDI plugin.  This happens in the current release version of VA v1.8.9 64-bit as well as the current beta version v1.9.9.95 64-bit.  Logs attached
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/8226387/eddi_issue.zip)
.

**Comment by alterNERDtive** [comment]
As investigated on EDCD Discord, it’s an issue with Amazon Polly voices. Those are 64bit only, so it doesn’t happen when run standalone.

Relevant log files: https://discordapp.com/channels/164411426939600896/353595704658231299/951593057680252999
