### ISSUE TITLE
Can't open companion app

### ISSUE THREAD

**Issue by TheProphet-S** [EDCD/EDDI#2337]
### Expected
Open EDDI settings
### Observed
I see EDDI's icon on the traybar, but the window does not show.
![screen](https://user-images.githubusercontent.com/61625500/161150520-7b443257-1fa1-42d2-a5a5-b20fb7f00d68.png)

### Steps to reproduce
uninstalled and reinstalled EDDI

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: [if applicable] 1.8.9 Steam
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] US
  * Voice: [Name and language]

### Investigation Notes
I tried uninstalling and reinstalling, removing folder in appdata/roaming

### EDDI Logs

[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]
[eddi.log](https://github.com/EDCD/EDDI/files/8393121/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/8393122/eddi1.log)
[eddi2.log](https://github.com/EDCD/EDDI/files/8393123/eddi2.log)

**Comment by Tkael** [comment]
Hmm... no errors recorded in the log when running in standalone mode (the mode you appear to have been using when you took the screenshot).

Perhaps the window is minimized or off screen?

Please hold down the LEFT SHIFT button and then right click on the tray icon. You should see a menu come up with options like `Restore`, `Move`, `Size`, `Minimize`, `Maximize`, and `Close`.
![context_menu](https://user-images.githubusercontent.com/4382539/161178209-64f5fad4-bdf3-4091-916c-672e9d5df907.png)

1) If the option is not grayed out, start by selecting `Restore`.
2) Next, try selecting `Move` and then selecting the portion of the screen where you'd like the window to appear.

**Comment by Tkael** [comment]
@TheProphet-S Any updates on this?

**Comment by TheProphet-S** [comment]
Hi, I managed to open the window with "Maximize", move didn't work. Thanks for the tip :-)
