### ISSUE TITLE
Reported Star Age in "Thousands" instead of "Millions"

### ISSUE THREAD

**Issue by soifua** [EDCD/EDDI#234]
## Steps to reproduce

1. Have EDDI open when you scan a star
2. listen to the reported age of the star

## Expected
EDDI should report the actual age in the star in millions of years. 

## Observed
I just scanned star named Zunuae PG-Y d74565 A. In System Map, it's age is reported as 2,786 MILLION YEARS. But after scanning, EDDI says something like 2,786 years, making it one of the youngest stars in the galaxy. Obviously, this is incorrect.

## Investigation
n/a

**Comment by Tkael** [comment]
We had to make a change to the default script in the last update. Please check your 'Star report' script against the default. If it does not match, please reset your script to the default.

**Comment by soifua** [comment]
star report script? where might I find this?

**Comment by Tkael** [comment]
1. Open EDDI and go to the 'Speech responder' tab. 
2. Once there, find 'Star report' in the list and click the 'Edit' button for that row.
3. Click the 'Reset to Default' button.
4. Click the 'Ok' button to save the change.
You're done!

**Comment by soifua** [comment]
I tried it and it actually didn't fix the problem. It turns out the issue was with the "Star scanned" script, not the "Star report" script. But there's no way I would have even tried that unless you pointed me in right direction, so much thanks.

**Comment by Tkael** [comment]
Ok, so are you good then? I'm not sure?

**Comment by Tkael** [comment]
Closing as fixed. Let us know if otherwise!
Thanks for reporting.
