### ISSUE TITLE
Salvation's 'Secret' CG stuck in mission monitor

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2340]
### Expected
Missions and Community Goals to be removed from the Mission Monitor if none exist when loading your game.

### Observed
The recent 'secret' CG for Salvation remains in the Mission Monitor even after completion, and there is no way to remove it in the EDDI interface.

### Steps to reproduce
Not really reproduceable now, as the CG is over.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1
  * VoiceAttack Version:  N/A
* Localization [if applicable]
  * EDDI's language: English GB
  * Voice: Ivona Amy

### Investigation Notes
I took part in the 'secret' Salvation CG last week, which auto completed when it expired.  When I next logged on, I received an in-game message to thank me for participating, at which point I was awarded the CG rewards.  There was no mission to claim or hand in, and EDDI thinks it's still in my missions to claim, but it's not.

Subsequent relogs in game and restarts of EDDI have not cleared it either.  It's just stuck in my mission monitor forever now.  I was under the impression that EDDI should refresh the mission monitor when you load your game, but this is not happening with this one, possibly due to the unique nature of the way the mission was 'given' and 'completed'.

I have been able to remove it by deleting the mission data out of the missionmonitor.json file, but this shouldn't be necessary for a user to do.

Could there be some way to remove stale missions from the monitor added to the EDDI interface?  Maybe a right-click menu to remove individual missions?  Or maybe a button to remove the highlighted mission, with a pop-up confirmation?

I have kept a copy of my missionmonitor.json file if you need to look at it, or use it for testing:
[missionmonitor.zip](https://github.com/EDCD/EDDI/files/8457951/missionmonitor.zip)

I notice that in the monitor file, the statusEDName says 'Claim', but there is nothing in my in-game transactions tab at all.

### EDDI Logs
None

### Player journals
None.

**Comment by Tkael** [comment]
Normal missions are removed when you next log in and a new 'Missions' journal entry is written. That entry omits community goal events so at the time being community goal events are removed either 
- When we receive an event indicating that you've claimed the reward or
- When we see a `CommunityGoal` event summarizing the currently active community goals and it does not include a community goal we think is active.

If neither of those occurs then we can end up in a situation where the community goal is not automatically removed. 

Other than adding a `Remove` button (which is a possibility I've considered), another possible solution might be to temporarily remove community goal events when you load into the game and then to restore them again if confirmed active (via a `CommunityGoal` event).

**Comment by Darkcyde13** [comment]
Hmm, tough choice.

On the one hand, I'd say go for the 'automatic' method of temporarily removing them at start of game as this requires no user input, but the downside to that is for those of us who have mission/CG reports on game start.

On the other hand, having a button to remove old missions isn't a bad idea.  While it does require user input, so does removing old crime entries from the crime monitor, so there is already a precedent for this kind of situation.  At least with missions/CGs it's much less likely to happen.

After thinking about it, personally, I think I'd prefer the second option.

**Comment by Tkael** [comment]
A CG report at game start won't provide up-to-date data until a fresh event is written anyways, so I'm going to try the automatic option (which will handle removing "stuck" goals).

**Comment by Darkcyde13** [comment]
The only thing my CG report does on game start is to simply say that I have one, it doesn't give any other data.  Well, thanks for adding this auto removal, it will be helpful. :)
