### ISSUE TITLE
ShipName() is localized even if it shouldn't be

### ISSUE THREAD

**Issue by Klajan** [EDCD/EDDI#2346]
## What's Wrong
_"your ship" (EN)_ is localized to _"deine ship" (DE)_ even though EDDI language is set to English.
This only happens if launched through VoiceAttack beta.

### Expected
"your ship" should adhere to the language set in EDDI

### Observed
"your ship" is localized to German even though EDDI is set to English

### Steps to reproduce
1. launch EDDI as VoiceAttack Plugin.
2. speak ship name without any name set

### Configuration
* Version
  * EDDI Version: 4.0.1
  * VoiceAttack Version: v1.9.9.108
* Localization
  * EDDI's language: EN
  * Windows language: DE
  * Voice: Microsoft Mark

### Investigation Notes
This behavior only happens with the beta versions of VoiceAttack.

**Comment by Tkael** [comment]
This should be fixed for the next release. o7
