### ISSUE TITLE
New 'Unclassified Relic' not recognised

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2378]
As per title, the new 'Unclassified Relic' commodity is not recognised.

Journal entry when collecting them from the Thargoid Machine:
> { "timestamp":"2022-08-13T23:10:42Z", "event":"CollectCargo", "Type":"AncientRelicTG", "Type_Localised":"Unclassified Relic", "Stolen":false }

EDDI output:
> ancientrelictg now on board.

I was wondering, shouldn't this default to the localised version (which would be correct)?

**Comment by Tkael** [comment]
Thanks. I was already aware of the definition update.

Ideally, this would default to the localized name but in this case the event pre-dates localized names being written to the journal so we don't currently handle the localized name. We will certainly be able to implement a fix for that though. :-)

**Comment by Tkael** [comment]
Resolved by b4a8c5e2016c4f3844010835b4a0da708208c631.
