### ISSUE TITLE
Galnet unable to retrieve marked read items

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#238]
See my fork for potential fix. https://github.com/rodan123/EDDI
[Galnet list news headlines.txt](https://github.com/EDCD/EDDI/files/1479564/Galnet.list.news.headlines.txt)

Speech responder did not retrieve articles once they had been marked read. Marked-read retrieval was hard coded to **false** in _ScriptResolver.cs_.
_GalnetSqLiteRepository.cs_ had no SELECT statement that would retrieve previously marked read articles. The default EDDI personality marks items read automatically after playing once.
Modified code  to respect second argument as boolean, allowing retrieval of all items READ and UNREAD in a category. Added "All" category to retrieve all DB categories. **GalnetNewsArticles()** is the same as **GalnetNewsArticles("All",false)** and will retrieve all UNREAD articles in any category, while **GalnetNewsArticles("All",true)** will retrieve all articles READ and UNREAD. _Galnet list news headlines.txt_ is a sample cottle script to list Galnet headlines utilizing the above changes.

**Comment by richardbuckle** [comment]
Fixed Markdown in for the fork URL.

Many thanks for this! Looks good at first sight. Please generate a pull request so that the team can collaborative to review it in detail.

**Comment by Tkael** [comment]
Indeed. A pull request will be the best way to compare the current version and proposed revisions. 
Sound like this might be a great complement to my current pull request, which tests for recent journal entries before retrieving new articles.

**Comment by Tkael** [comment]
Closed as complete, pending approval on pull request #238.
