### ISSUE TITLE
EDDI Ship Monitor export not working

### ISSUE THREAD

**Issue by DarrenMKL** [EDCD/EDDI#2380]
It's no longer exporting my ship stats to Corolis or EDSY. Have only noticed it on the current version 4.0.1, was working previously.

**Comment by Tkael** [comment]
Please elaborate. What happens when you press the "Export it" button? Or is the button greyed out?

**Comment by Tkael** [comment]
For reference, I'm not having any issues at present with exporting ships.

**Comment by DarrenMKL** [comment]
Hi.

Nothing happens, no new browser tab or browser window. I have tried with
chrome open and closed.

**Comment by DarrenMKL** [comment]
Just to add too, it's not greyed out.

**Comment by Tkael** [comment]
Is anything recorded in your log when you try to export your ship?
Your logs are located at %appdata%/EDDI and end with the .log extension.
Logs are numbered from most recent to least recent.

**Comment by Tkael** [comment]
Hi @DarrenMKL , please take a look at your logs when you have a moment and let me know. o7

**Comment by DarrenMKL** [comment]
Odd, I replied to the email requesting the log on Saturday same way I replied to the email messages previously (and they show up on here and this is the first reply I have typed on here) but the log one doesn't. Anyway, here it is, just ran it right now again.
[eddi.log](https://github.com/EDCD/EDDI/files/9488855/eddi.log)

**Comment by Tkael** [comment]
I think Github has issues with email responses which have attachments. Better to click through to Github to respond.

In any case, here's the exception:
```
2022-09-05T10:03:51 [Error] ConfigurationWindow.xaml:exportShip Failed: : {"NativeErrorCode":740,"ClassName":"System.ComponentModel.Win32Exception","Message":"The requested operation requires elevation","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)\r\n   at System.Diagnostics.Process.Start()\r\n   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)\r\n   at EddiShipMonitor.ConfigurationWindow.exportShip(Object sender, RoutedEventArgs e)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nStartWithCreateProcess\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Diagnostics.Process\nBoolean StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)","HResult":-2147467259,"Source":"System","WatsonBuckets":null}
```

It looks like EDDI does not have sufficient permission to send the data to your browser. Are you running your browser in administrator mode?

**Comment by DarrenMKL** [comment]
I was, turning it off has fixed it. Clearly between last using EDDI (I'm back on ED after a break) and now I've had to do something else to fix something that needed admin privileges and I left it on and this is the first (and only) thing that has been effected.

Thank you.

**Comment by DarrenMKL** [comment]
Hi Brian. Just run it again right now (fresh Windows boot etc.) Log attached ThanksDarren Sent from Mail for Windows From: Brian WilsonSent: 03 September 2022 02:40To: EDCD/EDDICc: DarrenMKL; AuthorSubject: Re: [EDCD/EDDI] EDDI Ship Monitor export not working (Issue #2380) Is anything recorded in your log when you try to export your ship?Your logs are located at %appdata%/EDDI and end with the .log extension.Logs are numbered from most recent to least recent.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Tkael** [comment]
Hi Darren, email attachments don't work with Github so I did not receive your log.

**Comment by Tkael** [comment]
Is it the same situation we already discussed above (with your browser in administrator mode)?

**Comment by DarrenMKL** [comment]
Not sure what’s happened there, I didn’t post anything since we fixed it. So, not me 😊maybe lag with the old attachment? Sent from Mail for Windows From: Brian WilsonSent: 11 October 2022 13:52To: EDCD/EDDICc: DarrenMKL; MentionSubject: Re: [EDCD/EDDI] EDDI Ship Monitor export not working (Issue #2380) Is it the same situation we already discussed above (with your browser in administrator mode)?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
