### ISSUE TITLE
Total Assets is not being reported correctly - Fleet Carrier not being included?

### ISSUE THREAD

**Issue by SmartShots** [EDCD/EDDI#2387]
When Inara is updated by EDDI the total assets are being reported incorrectly. I have 15 Billion+ in total assets in game. When Inara picks up the data from Frontier it also shows 15 Billion+ total assets. When Inara gets data from EDDI the total assets shows as 3 Billion+.

I would expect EDDI to pick up the correct data and send that to Inara.

I suspect that it is because most of my assets are what's on my fleet carrier (services, etc.) and they are not being included in the total that EDDI is reporting.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.10.3.7

**Comment by Tkael** [comment]
Hmm.... have you looked at the breakdown of your assets at https://inara.cz/elite/cmdr-credits-assets/ to identify the missing data?

When I access my Inara profile (which I update via EDDI), I see my fleet carrier assets recorded correctly.
![image](https://user-images.githubusercontent.com/4382539/190826021-07c5b61c-22b4-48f3-a0f1-28a0601f8063.png)

When I look at https://inara.cz/elite/cmdr-credits-assets/ my fleet carrier and miscellaneous services appear to be included within the total.
![image](https://user-images.githubusercontent.com/4382539/190826251-105b4cd0-89b2-43fa-bb2c-30637c0005c9.png)

Assets data is all derived directly from the raw journal "Statistics" event, as described [here](https://inara.cz/elite/inara-api-docs/#event-43). We take the "Statistics" journal event, remove the timestamp and event name, and then pass everything else including all of the available asset data to Inara. 

https://github.com/EDCD/EDDI/blob/ac863458a504d281ed4997a0b308156f8b6cac93/InaraResponder/InaraResponder.cs#L1416-L1444
Partial asset data being reported to Inara is extremely unlikely and we probably need a different explanation. 

Is the data similar to what you would have expected to see at the start of your last play session?
Is the data simply frozen / never updating between play sessions?
Is it possible that you have some other application sending updates to Inara? 
If you have multiple Elite accounts then could data have come from a second account?
Are there any exceptions recorded in your .log files (found in %appdata%, in the EDDI folder) which might be relevant to this issue?

**Comment by SmartShots** [comment]
Hmmm, not sure where it's going wrong but...

This is the credits page, clearly showing the correct 'official' updates from Frontier and the last 2 updates that came from EDDI.

![image](https://user-images.githubusercontent.com/74139324/190849296-6d162622-fdb0-4723-91bc-6c98bfd91a3b.png)

This the credits assets page:

![image](https://user-images.githubusercontent.com/74139324/190849225-f0f20cca-cc94-4890-b0de-95e094019bac.png)

Which is an entirely different amount again. The Miscellaneous services are not listed though. I am going to guess that it's something to do with data not being imported for my Fleet Carrier as when I go into my hangar on Inara and look at the fleet carrier there is literally no information displayed, in any of the sections:

![image](https://user-images.githubusercontent.com/74139324/190849730-b92978dd-bcfa-47fa-8acd-163785416dc0.png)

> Is the data similar to what you would have expected to see at the start of your last play session?
No, it's been a while since I had 3 Billion total assets.

> Is the data simply frozen / never updating between play sessions?
No, the data does change as you can see in the last two entries in my credits above.

> Is it possible that you have some other application sending updates to Inara?
No, only the official updates from Frontier direct to Inara.

> If you have multiple Elite accounts then could data have come from a second account?
No, I don't think so. I do have another account but it's never used now. It was only used for the private group name when I used to run my own player group, but it hasn't been signed into for over a year now and never on this PC.

> Are there any exceptions recorded in your .log files (found in %appdata%, in the EDDI folder) which might be relevant to this issue?

My EDDI Log from yesterday:
[eddi1.log](https://github.com/EDCD/EDDI/files/9591363/eddi1.log)

My EDDI log from today:
[eddi.log](https://github.com/EDCD/EDDI/files/9591351/eddi.log)

**Comment by Darkcyde13** [comment]
I have been having the same problem, but I must admit, I never considered it could have been EDDI's fault.  I've found that INARA has said there were errors in receiving data, but it didn't specify where from.  I just took it to mean from the game files (as I've had trouble with INARA obtaining data from a manual scan of the Journal sometimes), but thinking about it, it is probably from EDDI as I use that solely for sending all my data to those websites EDDI can send data to.

As you can see from the below, I should have total assets of around 13.5 billion.  I made enough money on that Tritium CG to buy a FC (hence the spike in assets and immediate drop in credits), but you can see some dips in total assets back to my pre FC level.  These have been when INARA said there were errors in receiving data, and by getting INARA to re-aquire my latest data from the game files, the amount goes back up to the correct level.

![image](https://user-images.githubusercontent.com/24360725/190851906-c3d521b7-9104-4140-9aac-c540dffc26fa.png)

To get this image, I got INARA to manually update again, which in hindsight was a bad thing to do before checking everything over first.  Consequently, I can't see what INARA thought I was 'missing' in my 'Assets Value' page to make that deficit, but it's does seem to be around the same value in the 'Misc' entry on the 'Assets Value' page, around 5.5 billion Cr.

I'll see if I can keep an eye on this as I play over the next few days, and see what I can find out.

EDIT:  I've just realised, looking at the above image, the entries that are wrong (only 8 billion total assets) are the ones that don't have a tick on the very left side, and also have an 'Edit' option on the right.  Any idea what these represent, as I've not really looked at them before?  Could these help in determining what's going on?  I see the exact same in @SmartShots info too.

**Comment by SmartShots** [comment]
> EDIT: I've just realised, looking at the above image, the entries that are wrong (only 8 billion total assets) are the ones that don't have a tick on the very left side, and also have an 'Edit' option on the right. Any idea what these represent, as I've not really looked at them before? Could these help in determining what's going on? I see the exact same in @SmartShots info too.

The entries with the check marks are the official updates from Frontier.

**Comment by Darkcyde13** [comment]
Quick update after today's play session.  Something odd is happening...

![image](https://user-images.githubusercontent.com/24360725/190880649-d913a01b-611b-46e6-a9b0-c9e0bec6f138.png)

The last entry dated the 14th Sept, has changed.  In my first post above, it was an official update from Frontier (thanks @SmartShots).  However, after playing today, it's no longer an official update and is missing my full asset value again.

A quick look at the asset value page, show the Misc category is not what it was earlier today...

![image](https://user-images.githubusercontent.com/24360725/190880745-24379036-a1df-4bc0-b52d-55ea4a169069.png)

Now it's only 710 million.  When I made my post above it was over 5 billion, which it should be.

I have copies of my EDDI log and Journal, if they would be helpful at all?
[Journal.2022-09-17T202707.01.log](https://github.com/EDCD/EDDI/files/9592830/Journal.2022-09-17T202707.01.log)
[eddi.log](https://github.com/EDCD/EDDI/files/9592831/eddi.log)

**Comment by SmartShots** [comment]
Just adding to my notes:

Looking at when my credit assets are correct (updated from Frontier):
![image](https://user-images.githubusercontent.com/74139324/190894033-708adf55-ce2e-4d2f-be70-b38f6cb020fa.png)
NOTE: I manually deleted the previous incorrect EDDI updates and haven't been in game yet today.

My credit assets page is now also correct:
![image](https://user-images.githubusercontent.com/74139324/190894015-ae3a4d59-4b30-4c50-b128-7baae0a75afb.png)
NOTE: It is now showing the correct Misc services, however, my Fleet carrier pages are still blank.

**Comment by SmartShots** [comment]
Also - I just went in game and got EDDI to update again and the incorrect credits and missing Misc services are back:
![image](https://user-images.githubusercontent.com/74139324/190894750-f05a40dd-ab8d-4f23-9d18-357ef6db4a0d.png)

![image](https://user-images.githubusercontent.com/74139324/190894769-bb8309fd-2312-41f4-942c-14e1e6b31d4e.png)

Todays EDDI Log:
[eddi.log](https://github.com/EDCD/EDDI/files/9593497/eddi.log)

My Journal from this morning:
[Journal.2022-09-18T094448.01.log](https://github.com/EDCD/EDDI/files/9593499/Journal.2022-09-18T094448.01.log)

My Journal from yesterday:
[Journal.2022-09-17T175923.01.log](https://github.com/EDCD/EDDI/files/9593500/Journal.2022-09-17T175923.01.log)

**Comment by SmartShots** [comment]
I have spoken to Artie (Inara creator) and pointed this issue out to him, in case any part of it was down to Inara, this is what he had to say:

> Hello, thanks for bringing this to my attention. It's definitely EDDI's flaw, because it sets only credits (but not assets) over API, so Inara calculates the assets from ships, but in a case the player has engineered personal equipment, etc. the value is off as seen. What EDDI must do is to set credits and assets from the journal's statistics event at once, which is currently not doing.

**Comment by Tkael** [comment]
Artie and I have identified the issue. It's some code that has been updated in my development build but which hasn't yet made it's way into release. It will be resolved with the next release. o7

**Comment by Tkael** [comment]
Resolved by a22e1b469b0cf1633f61779f186ce8c009b7be10.
