### ISSUE TITLE
Some events are not being returned to Voice Attack

### ISSUE THREAD

**Issue by dupsatou** [EDCD/EDDI#2388]
## What's Wrong (please be as specific as possible)

It seems that whether or not EDDI returns an event to voice attack can be hit or miss.  I have also seen events queue up and suddenly come in hours later while playing ED rather than when I actually needed them.  Everything basically discussed in issue #1215 is true for me here - even in the comments of high CPU usage.

### Expected
Events are returned to VoiceAttack promptly so profiles can respond and take action immediately.

### Observed
Doing something in the game that should send an event is delayed or never comes.  Exact example and steps to reproduce are in #1215 as well.  Also noticed high CPU utilization (maxing out) while EDDI plugin is enabled.

### Steps to reproduce

See #1215 

### Configuration
* Version
  * EDDI Version: 4.0.1
  * VoiceAttack Version: 1.10.3 64-Bit
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Default - English

**Comment by Tkael** [comment]
Does this occur using the default EDDI.vap profile?
If not then there may be a loop in your VoiceAttack profile that is consuming your CPU's resources.

**Comment by Tkael** [comment]
If it does continue to occur when using EDDI.vap then please submit a DEBUG eddi.log file so that we can examine the timing as events are being processed by EDDI. Please don't forget to disable DEBUG logging after collecting the data.

**Comment by Tkael** [comment]
Closing due to lack of further feedback.
