### ISSUE TITLE
Support for Windows 11 Natural Voices?

### ISSUE THREAD

**Issue by lenninscjay** [EDCD/EDDI#2396]
With the addition of Windows 11 three new natural sounding TTS voices were added. Aria, Guy, and Jenny. They're installable through the Accessibility<Narrator window. I suspect that Windows 11 actually installs these through the Microsoft Store App which might explain why they don't show up in the normal TTS install directory.

**Comment by lenninscjay** [comment]
The updated windows 11 Voices are located in the below directories:

C:\Program Files\WindowsApps\...

...MicrosoftWindows.Voice.en-US.Aria.1_1.0.6.0_x64__cw5n1h2txyewy
...MicrosoftWindows.Voice.en-US.Guy.1_1.0.3.0_x64__cw5n1h2txyewy
...MicrosoftWindows.Voice.en-US.Jenny.1_1.0.6.0_x64__cw5n1h2txyewy

The original windows TTS is located in C:\Windows\Speech_OneCore\Engines\TTS\en-US

I tried a brute force copy and paste for the files in the aria directory into the TTS/en-US directory and thought I got it working, with EEDI configured to "Windows Default TTS" but when I when I tried to reproduce it I couldn't.

**Comment by Tkael** [comment]
I've looked for information on these but have come up empty as far as finding 3rd party developers that have been able to access and implement these in a desktop-only context (i.e. without accessing a rate limited or paid Azure server account). I'm also still on Windows 10 so unable to test the new voices locally.

If you have any information that might be relevant for supporting these voices in EDDI then please do not hesitate to share!

**Comment by Tkael** [comment]
To support the OneCore voices we needed to add a second Speech Synthesizer library to EDDI. I'd expect that the new Natural Voices would require something similar but I've been unable to find any documentation that doesn't point developers back to server-processed voices with Azure.

Also please note: They may be registry hacks to get this working but we do not want to support or encourage registry hacks.

**Comment by lenninscjay** [comment]
Tkael, wow, quick response man. Yes, regarding the registry hacks I was just looking through SystemSpeechSynthesizer.cs and saw a couple of comments in there that made me consider digging through registry which I might do myself but wouldn't recommend user wide.

I can't really recommend windows 11 either, but here I am haha. For what it's worth, the new Windows 11 voices are free and sound on par with amazon polly as far as I can tell. So that's promising.

Because it sounds so much like the polly cloud speech, I do think you're on the right track with Azure so it may not be feasible, but I'll keep digging.

**Comment by Tkael** [comment]
Closing as I don't think it's possible to access these voices without registry hacks at this time (and we can't really support any issues you might encounter if you unlock voices with registry hacks).

**Comment by gexgd0419** [comment]
Microsoft hasn't allowed third-party apps to use those natural voices yet.

The Narrator natural voices are offline ([embedded](https://learn.microsoft.com/azure/ai-services/speech-service/embedded-speech)) versions of [Azure AI Speech](https://learn.microsoft.com/azure/ai-services/speech-service/) voices. Microsoft limits third-party access to embedded speech models, and requires [submitting an application form](https://aka.ms/csgate-embedded-speech) if you want to use them. Obviously, Microsoft wants most users to use the online version, which costs money.

However, @lenninscjay  if you want to have a try, here's my program called [NaturalVoiceSAPIAdapter](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter). After installation, it can make Narrator natural voices accessible to all SAPI 5 compatible programs. EDDI should be one of them.

Also, the minimum system version requirement for the Narrator natural voice packs is Windows 10 17763, so you can even install those voices on Windows 10, as long as you have the [Microsoft store links](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/wiki/Narrator-natural-voice-download-links).

**Comment by Tkael** [comment]
Deleted a necro comment from the dev of a repo that I do not know or think I can endorse, pointing to an application released just a few days old which has no direct bearing on EDDI and which might or might not be trustworthy.
