### ISSUE TITLE
Errors with some scripts: 'Exception has been thrown by the target of an invocation.'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2397]
### Expected
All scripts to operate normally.

### Observed
For some reason, I'm now getting an error when certain scripts try to run:
Error with <script name> script: Exception has been thrown by the target of an invocation.

### Steps to reproduce
I don't think you'll be able to reproduce it, as I'm sure it will be a problem my end, but see investigation below to see what I did.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.1
  * VoiceAttack Version: v1.10.3
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: Ivona Amy

### Investigation Notes
This is the order of events leading to this problem...

1. Loaded into game.
2. Loaded VA as I had not started it quick enough to load before getting into game.
3. Jumped to a few systems on my way back to one of the Stargoids.
4. Noticed that one of my VA commands was giving an error because I had started VA after Elite.
5. Quit Elite to main menu, and reloaded.
6. Jumped to my next system.
7. My custom FSD engaged script gave the above error.  I think, because it tried to report on the exploration status of the new system.
8. Did the honk, and got the same error from the Discover scan script.

So, after this, I tried reloading both VA and Elite from scratch.  Still errored.  Tried a reboot, and reloaded using the EDDI default personality.  Tried the Bodies mapped script without jumping anywhere, but it still errors.

I noticed I'd been disconnected from the Frontier API, so I reconnected that, and tested the Bodies mapped script again, without VA, and using the default EDDI personality, but still get the error.  Just in case, I re-obtained my EDSM logs, but it still errors.

So, I'm at a loss as to why it started, or why it's still happening.  The scripts look fine to me when viewed, so it doesn't look like the personalities have been corrupted, at least not from what I can see.

Attached is my EDDI log from my last attempts, where you can see the exception errors (looks like a 'divide by zero'?).  This was with VA, and the EDDI default personality.  So far, I've tried some of the Body/Bodies scripts, and get the error on some, but not all, of those I tried.
 
### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/9687432/eddi.log)

### Player journals
I doubt this will help, but this is the Journal from my last session.
[Journal.2022-09-30T210446.01.log](https://github.com/EDCD/EDDI/files/9687444/Journal.2022-09-30T210446.01.log)

**Comment by Darkcyde13** [comment]
I just tried renaming the EDDI.sqlite and re-obtained my EDSM logs again to recreate the database.  Loaded VA , and back into the game, but still getting the error. :(

**Comment by Darkcyde13** [comment]
Also just tried removing the EDDI directory from AppData\Roaming (made a backup first), and reinstalling EDDI, but still get the error.

**Comment by Darkcyde13** [comment]
....and now, it all seems to be working again, without me doing anything.  I was playing, making sure EDDI was still reporting to EDSM, and just in the middle of playing, it stopped erroring.  Weird.

I'll close this for now, but if it happens again, I'll reopen it.  So confused by it now....

**Comment by Tkael** [comment]
One of the new body properties that we added in version 4.0.1 was a `solarday` property.
This property calculates the solar day from the orbital and rotational periods. An exception can occur when the orbital and rotational periods are exactly equal (which would represent an infinite solar day and can occur with tidally locked bodies). 
The next release will include a fix for this by making the `solarday` value null when this would occur.

EDDI may have corrected itself by obtaining journal data rather than EDSM data (number precision may be a little different between the two) or as soon as you left the system / stopped trying to access information about the specific body that triggered the error.

o7
