### ISSUE TITLE
Galnet: Unable to mark item UNREAD

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#241]
Unable to mark news items UNREAD.
Found another error in GalnetMonitor/GalnetSqLiteRepository.cs 
MarkUnread(News news);  set the @read value to "1" , should set to "0" to mark item as unread.

I have fixed this in my fork. 

Also, I have rewritten most of the Galnet cottle scripts so they work properly, if you're interested.
Have not uploaded them.

Thanks.

**Comment by Tkael** [comment]
Closed as complete, pending approval on pull request #238.
