### ISSUE TITLE
Ship interdicted script

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2421]
## What's Wrong (please be as specific as possible)

This is a simple one.  The change log says "Ship interdicted updated to add a default script.", but in the default personality, it's blank. Nothing there.

Edit: Sorry, I forgot to include the EDDI version. It's v4.0.2-b1.

**Comment by Tkael** [comment]
Yep, looks like I missed adding this. It would have been a simple script in any case and I should have no trouble adding it once I'm back at my home PC again. Thanks for raising the issue and letting me know so that I can correct it.
