### ISSUE TITLE
status.destinationName is always 'void'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2422]
### Expected
status.destinationName, and status.destinationLocalizedName to be populated with the currently selected destination as per the Status.json file.

### Observed
These variables are always set to 'void'.

### Steps to reproduce
1. Select a destination, either by the left nav panel or from any map.
2. Observe these status variables are always 'void', even though the Status.json file has been updated.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.2-b1
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I wanted to try out ideas for arriving at a carrier, but nothing worked.  I discovered that these variables are always void, so my ideas cannot work.

status.destinationName should be populated from the below Status.json, but it is not:

`{ "timestamp":"2022-11-27T16:53:04Z", "event":"Status", "Flags":16777224, "Flags2":0, "Pips":[2,8,2], "FireGroup":0, "GuiFocus":7, "Fuel":{ "FuelMain":30.740002, "FuelReservoir":0.293919 }, "Cargo":0.000000, "LegalState":"Clean", "Balance":5877580116, "Destination":{ "System":241828889788, "Body":0, "Name":"MCRN SUSTENTUS FEREBAT XZX-84Z" } }`

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
Ah, looks like I made a change to the variable name to be more consistent with other `status` variables but didn't update the documentation to match. Please try using `destination_name` and `destination_localized_name`. I'll update the documentation for the next release.
