### ISSUE TITLE
Next destination event not triggering

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2423]
### Expected
The 'Next destination' event to trigger when I select an in-system destination

### Observed
This event does not trigger, no matter what in-system object I select as a destination.

### Steps to reproduce
1. Select an in-system destination from the left nav panel or system map.
2. Observe that the event does not trigger and nothing is spoken.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.2-b1
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I've tried selecting various different objects as destinations, but the event never triggers.

### EDDI Logs
No entries in the log when I select a destination.

### Player journals
There is no event in the Journal for selecting a destination, so this could also be related to the other issue I opened regarding the status.destinationName not being populated #2422

**Comment by Tkael** [comment]
The script is disabled by default. Did you enable it?

**Comment by Darkcyde13** [comment]
Gah! I didn't notice that. Sorry.  That would be my visual disability at work again! Lol!

Although, why have it disabled by default?  Every other script is enabled by default (as far as I can tell).  I thought they should all be enabled and let the user decide to turn them off?

**Comment by Tkael** [comment]
We have occasionally defaulted scripts to disabled in the past but it is uncommon (sorry if I should have documented this differently). In this case, I felt like the default script I was using was a little more verbose than I or most would like (and in some cases did not yield proper grammar describing the destination) so I switched it off by default. 

I'll close this issue for now, but please feel free to let me know if you have any suggestions for refining this script. o7
