### ISSUE TITLE
EDDI crashing when creating a new script

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2429]
## What's Wrong (please be as specific as possible)

As mentioned on the forums, I'm having a problem creating new scripts.  I can open a new script, add any info, make a script, all fine. 
 When the OK button is clicked, EDDI freezes for a couple of seconds then crashes to desktop.  This happens with EDDI standalone and as a VA plugin.  It seems to be something up with my installation as others have reported it works OK for them.

T'kael requested I make this issue and I'm attaching a verbose log.  Any help would be greatly appreciated.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.2-b1
  * VoiceAttack Version: v1.10.3
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### EDDI Logs

[eddi.log](https://github.com/EDCD/EDDI/files/10135577/eddi.log)

**Comment by Tkael** [comment]
Replicated. This will be fixed for the next release (soon!).
