### ISSUE TITLE
frontier api problem

### ISSUE THREAD

**Issue by optimisticcynic** [EDCD/EDDI#2434]
I am running into an issue connecting to the frontier api.  it is getting stuck at the connecting step and never moves past it.

**Comment by Tkael** [comment]
> I am running into an issue connecting to the frontier api.  it is getting stuck at the connecting step and never moves past it.

I need more specifics. Please create a new ticket using the issue template and please include a copy of your eddi.log files from `%appdata%/EDDI`.
