### ISSUE TITLE
{destinationdistance} set to wrong value

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2438]
### Expected
The variable `{destinationdistance}` to be populated with the correct value.

### Observed
The variable is populated with what would have been the previous value.

### Steps to reproduce
1. Select a route on the Galaxy Map.
2. Check the value of `{destinationdistance}`.
3. Observe it has the value of the previous destination.
4. Repeat from point 1.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.2-b2.
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I was looking at changing part of my Jumped script that was no longer working, and while testing the `{destination.name}` and `{destinationdistance}` variables, I found the distance was always being set to the previous destinations distance, not the current one.

For example, the distance between Ascella and Shokuth is 183.29LY (in game).  While I am in Ascella, and I selected Shokuth to begin with, `{destinationdistance}` reported zero.  I then selected Lowat Yuan (5.14LY in game) and `{destinationdistance}` reported as 187.69LY.  Not quite the same as the in game distance to Shokuth, but close enough.  I then selected Shokuth again, and `{destinationdistance}` said 5.14LY, the distance to Lowat Yuan.  I reselect Lowat Yuan, and again the variable was set to 187.69LY.  I next selected the Taurinmuth system (6.38LY in game) and the variable was again set at 5.14LY.

It's almost as if the `{destinationdistance}` variable is being set just before the new system is selected, and thus stores the previous system's distance.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
Thanks for the report. Should be fixed in the next release.
