### ISSUE TITLE
Suggested improvement to pronunciation for `Cobalt` (with Microsoft TTS male en-AU voice, James)

### ISSUE THREAD

**Issue by slippycheeze** [EDCD/EDDI#2442]
## What happens now
Microsoft TTS male en-AU voice, James, pronounces "cobalt" very, very poorly.  Unrecognisably poorly.

## What I'd like to happen 
A custom lexicon entry with the correct pronunciation should resolve this; given it isn't likely a conflict, I'd suggest it for everyone™, but YMMV.

## How it can happen
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lexicon version="1.0" 
      xmlns="http://www.w3.org/2005/01/pronunciation-lexicon"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:schemaLocation="http://www.w3.org/2005/01/pronunciation-lexicon 
        http://www.w3.org/TR/2007/CR-pronunciation-lexicon-20071212/pls.xsd"

      alphabet="ipa"
      xml:lang="en-au">
  <lexeme>
    <!-- didn't automatically get cobalt, the element, correct. -->
    <grapheme>cobalt</grapheme>
    <phoneme>ˈkoʊbɒlt</phoneme>
  </lexeme>
</lexicon>
```

## EDDI Version
v.4.0.1

**Comment by richardbuckle** [comment]
Given that "cobalt" is a common real-world word, seems like a problem with the voice rather than EDDI. The lexicon is more intended for fixing terms that are specific to astronomy and/or the fictional setting.
