### ISSUE TITLE
Xeno Drone Multi-Controller is not present in ship module list, but is in `ModulesInfo.json`

### ISSUE THREAD

**Issue by slippycheeze** [EDCD/EDDI#2444]
## What's Wrong (please be as specific as possible)

The "Limpet Check" script kept telling me I had limpets, but no controller; I have the "Xeno Drone Multi-Controller" installed, so that isn't correct.  Some debugging later and I figured out it can't actually see it: it isn't present in `ship.compartments` when the voice responder runs.

### Expected
EDDI could see the drone controller, and treated it as the appropriate type.  (which, in the default script, is "you have any controller", quite correctly, so it should go down the "have controller, need limpets?" path.)

### Observed
speechresponder.out: `Full control re-established.  You are carrying limpets but no limpet controller.`

### Steps to reproduce
I presume that using the attached `ModulesInfo.json` in a test should be sufficient.  
If not I'll supply whatever additional data is required.

Potentially helpfully, here is [I'm gonna go POKE it!](https://coriolis.io/import?data=H4sIAKOtoWMC_7WW32_TMBDH_5WRF16K1KQdoL5N-6ENBkx04gGEoqt9bcwcn3V2ygra_47jljVN26WT4KVNU38_d_767pLfyQeSlUaXjL79Tk7Kkq7MqVY2GaW91c9LshY5GWW95MpjmYySwvq8QPBOmTsNlREFcu4rZvS5V2aR9JJPJhl5rrCX3LAiVn4RiWNNPgBuw6JLYGlJGZ8mD73_HTrbHTrrDp32N2KLAqbTdeBnb3YQIzaArlCo5YTI-QB06hf2c6HBuePngYdNsFRQkpETEHf3Ohck7qzynbxxoezpam0DVtYFAiyAZzSBhSTiPajhI-q0XnwJXhT70wIuqeJ8xiAx7UzuJK5u0sKmc0s_ka2GcFlbNzjUuptad1Pr2kQ0M2Uw0oZLWraH1n-kfQBlzqPOtXHFIlSRZDVfIo-fTnCNvGAoMRzI1J_V4jZWqym6ylrijY3vS3XwyL0OwvFSuNNLqZxnNak88SEetBw9W6vbdIfGEbtDsl0362eQsEWaVqg9mLumoYPO_C6C6jaodtGcILLN7Q47M6u_-mk-rjVbW40tPUODDM_2MYKz3eDYghy6p-liehhyEJGDNrKstFeSyaAg45l0fo-Gmvy_1k5Buz3FGgMMdweYVLPZIoyNiMyedmG4STyOxKxNZLSgeDUss82G6kry9W6kRA9Ko3QVT0GgE2DM0-O9xX0TuekWN0xTZWaCSlvV4x3kHIxA2dmmEfp2GypRgM7x3mqKDlQ8x8XeebwugbNat5NEE0W5DH4Kr8iEFwF3GCz7l7CNqgmna_wPmuSbjwvNlnL4VTF2z6Ka8I4mWxMuDPxw0tYygShcpTx2HUkDuhTz4mSlH9f6Zog5KRFqM7TnXAl_wKl8CQah_lLLkofvvfgAbj8mk-Xtq7Pl9KkvJZpYI9e2P1z9_TE8LcKtq5fl0YyMgfB5dPPp_fmR8i_CEpwvJdcEkqr6TcCrEp2Hso6X9bPsVZq9yvq3aTYaZqM0_Zo8_AGREb8dGgoAAA%3D%3D) on coriolis, which I think should give you the right JSON as well.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.4.0.2-b3
  * VoiceAttack Version: none
* Localization [if applicable]
  * EDDI's language: english (en-au, I believe)
  * Voice: Microsoft Susan, en-GB, Female

### Investigation Notes
I modified the "Limpet Check" script to add the name of each module it looked at:
```
Fuel Scoop.
Shield Generator.
Cargo Rack..
Planetary Vehicle Hangar.
AFM Unit. 
Detailed Surface Scanner. 
Advanced Docking Computer. 
You are carrying limpets but no limpet controller.
```

I further used the Cottle `{dump ship.compartments}` tool, and checked, and the xeno module – as far as I can tell – is not present, but without a localized name, it is entirely absent.  Everything else is present.

Note: the double-full-stop after Cargo Rack suggests to me that, perhaps, there in an empty module definition there.  My guess is that the module fails to load for some reason.

### Player journals
See the attached file: [ModulesInfo.json.txt](https://github.com/EDCD/EDDI/files/10268466/ModulesInfo.json.txt)

**Comment by slippycheeze** [comment]
I can no longer reproduce this.  After a restart, EDDI is correctly seeing the module, and is happy that a limpet controller is present.

I have no explanation, just confusion.

**Comment by Tkael** [comment]
The symbolic name (as found in the journal) is `int_multidronecontrol_xeno_size3_class3`. I've confirmed that EDDI recent versions do contain a definition for this module.

I'm not sure EDDI failed to recognize this issue the first time around. Could you possibly have another (older) version of EDDI installed on your system that you might have run inadvertently?
