### ISSUE TITLE
"Bodies to map" script reset

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2448]
## What's Wrong (please be as specific as possible)
4.0.2-b3 keeps resetting my "Bodies to scan" script to the default script on startup.

### Expected
Expect edited script to remain edited

### Observed
I can edit the script, but if I exit EDDI and restart it (Standalone or VA plugin) then the edited text has been reset to the default script.
### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.2-b3
  * VoiceAttack Version: latest

**Comment by Darkcyde13** [comment]
It's not just that script, it's quite a few others too.  I've checked over some of my other scripts, and they too have been reset to default, across all the personality versions I have.  I've lost months of work on many of them.

I went back to b2, reloaded my last release version, and all my edited scripts were fine.  I reinstalled b3 and my edited scripts were reset back to default again.

I've gone back to b2, and I'm going to have to go through all my scripts to see what is gone and what is still there.  Thankfully, I keep a change log, so I can at least work out what I need to do again. but it will take a long time.

Edit: Maybe EDDI should have an option on the first loading of a new version, one that asks if it should update any/all scripts?  Something like that could have saved me from losing months of work. :(

**Comment by Tkael** [comment]
I think I've found the issue. It affects all non-event scripts with default values. I'm very sorry and will release an updated version ASAP!

**Comment by Tkael** [comment]
Version 4.0.2-b4 released. This corrects the immediate issue with customized scripts reverting to default values and further implements a system of rolling backups when we upgrade personality scripts (similar to how EDDI keeps recent logs on a rolling basis).

**Comment by Tkael** [comment]
Now I can :zzz:.

**Comment by Darkcyde13** [comment]
> Now I can 💤.

Thank you for the quick response, fix, and enhancement.  Your work is very appreciated, and you've truly earned that sleep! :)

**Comment by Darkcyde13** [comment]
Just an additional thought...

I've just installed b4, and seen the backups get created.  Would it be possible to make those backups in a separate folder, maybe appended with the date of the backup?  It would keep the personalities folder cleaner, be more organised, and make finding files a bit easier, rather than having 10 copies (as they would eventually become) all listed in the one folder?

Maybe something like this?

![image](https://user-images.githubusercontent.com/24360725/208959831-fd12878f-d5d7-484a-a745-db49434562f1.png)
