### ISSUE TITLE
Galnet: DeleteNews not exposed 

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#245]
Function to delete Galnet articles was not exposed, preventing deletion of articles from database.
There is no cleanup in the Galnet monitor, so database would grow as new articles are added and none ever deleted.
Exposed as _GalnetNewsDelete_ in ScriptResolver.cs to allow user to manage database and delete old articles as desired.

**Comment by Tkael** [comment]
Incorporated into pull request #239
