### ISSUE TITLE
Unknown ED name `Wreckage_AncientProbe_Skimmers` in resource `EddiDataDefinitions.Properties.SignalSource`

### ISSUE THREAD

**Issue by slippycheeze** [EDCD/EDDI#2457]
## What's Wrong (please be as specific as possible)

Missing translation, I suppose?  From `eddi.log`:
```2022-12-28T11:39:18 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Wreckage_AncientProbe_Skimmers in resource EddiDataDefinitions.Properties.SignalSource```

### Steps to reproduce
Found on scan of planet [Synuefe HM-L C24-10 A 4](https://www.edsm.net/en/system/bodies/id/25906590/name/Synuefe+HM-L+c24-10/details/idB/41379448/nameB/Synuefe+HM-L+c24-10+A+4) when selecting a "Minor Wreckage" object.  

Has also happened once before, but I dismissed it as a likely aberration at the time, and didn't capture details.  I can't confirm this is a long-term persistent object.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.4.0.2-b4
  * VoiceAttack Version: not used
* Localization
  * EDDI's language: Automatic / en-GB (LCID 2057)
  * Voice: Microsoft Zira / en

### EDDI Logs
I checked the logs; there is no indication that anything other than the "can't translate" message was present.  I've captured the log, just in case, but for now am not upload.  Ditto the journals, 

### `status.json`
```json
{ 
    "timestamp":"2022-12-28T12:34:30Z", 
    "event":"Status", 
    "Flags":150995032, 
    "Flags2":0, 
    "Pips":[4,8,0], 
    "FireGroup":0, 
    "GuiFocus":0, 
    "Fuel":{ 
        "FuelMain":30.439999, 
        "FuelReservoir":0.394838 
    }, 
    "Cargo":3.000000, 
    "LegalState":"Clean", 
    "Balance":126858837, 
    "Destination": { 
        "System":2833302557394, 
        "Body":8, 
        "Name":"$POIScene_Wreckage_Cargo_03_Skimmers;", 
        "Name_Localised":"$POISCENARIO_WATSON_WRECKAGE_BUGGY_01_EASY;  " 
    } 
}
```

**Comment by Darkcyde13** [comment]
I can confirm this.  I visited the same body, and when selecting the Minor Wreckage POI, the 'Next destination' event script reported: `En route to the $POISCENARIO_WATSON_WRECKAGE_BUGGY_01_EASY;.`

**Comment by Tkael** [comment]
Thanks. FDev unfortunately left us with another cryptic symbolic output in the "Name_Localised" field but I'll update our signal definitions to translate this into a friendlier signal name.
