### ISSUE TITLE
Possible bug with  {TXT:Last station name} in EDDI/VA

### ISSUE THREAD

**Issue by Malandark** [EDCD/EDDI#2464]
### Expected
[I expected this to give the name of the LAST Station name I visited]

### Observed
[I am currently in the star system BD+15 2847

When I used {TXT:Last station name] in Voice Attack I get the name of the station I am parked outside of that I have not yet docked with

Write [Blue] 'Last station name is {TXT:Last station name}'   to log

Will give the Station name that I am parked outside of. ]

### Steps to reproduce
Here is what I did:-
I am currently in the star system BD+15 2847

I just left the Reynolds Terminal and supercrusied to the  Kaleri Gateway station, which is also in the same system.

Before docking at this station if I press Left Ctrl + Left Alt + Left Shift + 7 in Voice Attack to get the last station details then this line:-

Write [Blue] 'Last station name is {TXT:Last station name}'   to log

Will give the Station name that I am parked outside of. 

So using {TXT:Last station name} in VA will give the name of the Station current station and not my last visited one.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  EDDI 4.0.2-b4
  * VoiceAttack Version: [v.10.3 64-bit] 
* Localization [if applicable]
  * EDDI's language: [English]
  * Voice: [EDDI Default though I also use IVONA Amy at times]

## My Investigation
Tried at different ED Stations, same results

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by nepomuk16321** [comment]
The name "Last station" is somewhat misleading. I have just tested it. If you jump to another system after leaving the station and query the "last station" in VA, VA will output a "Not set".
"Last station" means the last station you were in, but not consecutive. It is actually always called the station you are near. I don't know the exact delimitation to the change. A border is the jump into another system. A second border will be the leaving of the SC, if you fly to another station, then also the name of the new station is taken over.
You can test it yourself. With notepad++ you can look at the current journal.log. You will find the event "Docked" and right behind it "StationName". (Sorry for my English, DeepL helps me)
@T'Kael and @Darkcyde - please correct if this is not correct.

**Comment by Tkael** [comment]
Indeed. This may actually be better described as the current station then the last station (it's an old legacy name, likely named to match the Frontier API output which defines the "last station" as the last station you've visited even if you are still docked at that station.

**Comment by Tkael** [comment]
It is probably undesirable to have the current station set prior to docking. Considering whether to change this or whether this might be a breaking change for some scripts.
