### ISSUE TITLE
Rotational correction not a status variable?

### ISSUE THREAD

**Issue by MalicT** [EDCD/EDDI#2465]
## What's Wrong (please be as specific as possible)
Trying to get EDDI to determine if rotational correction is on or off, much like flight assist, lights, gear, cargo scoop, hardpoints, etc

### Expected
Using EDDI to get rotational correction true/false

### Observed
does not exist in documentation or different wordings I attempted

**Comment by Tkael** [comment]
That value is not currently accessible via the current journal output, including from status.json (https://elite-journal.readthedocs.io/en/latest/Status%20File/). If you use VoiceAttack then you may be able to react to key presses to track the variable but unfortunately I don't think that I can offer a better solution at present. o7
