### ISSUE TITLE
On Foot Missions destination station/settlement

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2471]
## What happens now
When an on foot mission is taken and added to the mission monitor, if the target system is known, it is added correctly.  However, the target station/settlement is not.

## What I'd like to happen 
The target station/settlement to be added and available to scripts.

## How it can happen
I'm taking some on foot missions for materials, and thought I revisit this, as I know in the past the target station/settlement was not available.  Looking at the Journal now, it seems this information is available.  Would it be possible to have this information added please?

Journal entry with `DestinationSettlement`:
```
{ "timestamp":"2023-01-03T22:14:24Z", "event":"MissionAccepted", "Faction":"Gabjaujavas Dominion", "Name":"Mission_OnFoot_Collect_Contact_MB", "LocalisedName":"Secure a package from Nariah Nieves", "Commodity":"$PersonalDocuments_Name;", "Commodity_Localised":"Personal Documents", "Count":1, "DestinationSystem":"Iah Bulu", "DestinationSettlement":"Clothier's Respite", "Target":"Nariah Nieves", "Expiry":"2023-01-04T04:17:30Z", "Wing":false, "Influence":"+", "Reputation":"+", "Reward":54212, "MissionID":909166596 }
```

## EDDI Version
V4.0.2-rc1

**Comment by Darkcyde13** [comment]
Sorry, I forgot to add the other entries for this mission.

Redirected:
```
{ "timestamp":"2023-01-03T22:42:49Z", "event":"MissionRedirected", "MissionID":909166596, "Name":"Mission_OnFoot_Collect_Contact_MB", "NewDestinationStation":"Vetulani Installation", "NewDestinationSystem":"Gabjaujavas", "OldDestinationStation":"Clothier's Respite", "OldDestinationSystem":"Iah Bulu" }
```
I also noted that the `Mission redirected` script didn't seem to trigger when this happened.  Nothing was spoken for it, and my version of the script should always say something.

Completed:
```
{ "timestamp":"2023-01-03T22:55:57Z", "event":"MissionCompleted", "Faction":"Gabjaujavas Dominion", "Name":"Mission_OnFoot_Collect_Contact_MB_name", "MissionID":909166596, "Commodity":"$PersonalDocuments_Name;", "Commodity_Localised":"Personal Documents", "Count":1, "DestinationSystem":"Iah Bulu", "DestinationSettlement":"Clothier's Respite", "Target":"Nariah Nieves", "Reward":34212, "MaterialsReward":[ { "Name":"MiningAnalytics", "Name_Localised":"Mining Analytics", "Category":"$MICRORESOURCE_CATEGORY_Data;", "Category_Localised":"Data", "Count":2 } ], "FactionEffects":[ { "Faction":"Gabjaujavas Dominion", "Effects":[  ], "Influence":[ { "SystemAddress":9465705473465, "Trend":"UpGood", "Influence":"+" } ], "ReputationTrend":"UpGood", "Reputation":"+" } ] }
```

Edit:  After doing a couple more missions, I can confirm that the `Mission redirected` event is not triggering when the mission criteria is complete (collected an item).  The Journal event says `MissionRedirected` so shouldn't this have triggered the event script?

**Comment by Tkael** [comment]
Thanks. It looks like I implemented this partially but never finished hooking it up completely. Should be easy to finish.
