### ISSUE TITLE
Cottle `Log` function has unintuitive failure mode with multiple arguments

### ISSUE THREAD

**Issue by slippycheeze** [EDCD/EDDI#2475]
## What's Wrong (please be as specific as possible)

I made a (bad) assumption, and invoked in Cottle: `{Log("RouteDetails('set', '", target, "')")}` to write three things to the log as a single string.

### Expected
`Log` accepts any number of arguments, stringifies them, then concatenates them without any interpose character, and emits a single log message.

eg: `Log("one", "two")` → `onetwo`

### Observed
Nothing happened.  Literally, no log message or speech was generated, as if the `Log` call was not even there.

### Steps to reproduce
1. In Cottle, `{Log("one", "two")}`
2. Check the logs...

### Configuration
* Version
  * EDDI Version: v.4.0.2-b5
  * VoiceAttack Version: N/A

**Comment by Tkael** [comment]
https://github.com/EDCD/EDDI/wiki/Help#log

Log is intended to write messages that are already a single string.

**Comment by Tkael** [comment]
Thanks for the feedback but I'm going to close this one. I don't think that this function should be required to interpret anything more complex than a simple string. And concatenating strings is already easily done with the tools available.
