### ISSUE TITLE
Translation error in Engineer.majorspecialties

### ISSUE THREAD

**Issue by Transcan** [EDCD/EDDI#2476]
I'm building up my new ship, and when I went to Selene Jean I noticed that the message triggered by Engineer report script is given a wrong translation for "HullReinforcement".

### Expected
_En este sistema está la base de Selene Jean especializado en modificar Blindaje y **Refuerzos de casco**._

### Observed
_En este sistema está la base de Selene Jean especializado en modificar Blindaje y **HullReinforcement**._

### Steps to reproduce
Set Spanish as game and EDDI language. Go to Kuk system (Selene's home system).

### Configuration
EDDI versión 4.0.2-rc1

## My Investigation
Using speechresponder.out I see the Engineer.majorspecialties list is not totally localized:
Armour is localized as Blindaje, but HullReinforcement isn't.
So I checked if that property is translated in EngineerSpecialty.es.resx and it is already localized.
But the speciality in that file is HullReinforcement**s** (notice the "s"):
```
  <data name="HullReinforcements" xml:space="preserve">
    <value>Refuerzos de casco</value>
  </data>
```
Maybe the error comes from that missing "s"?

**Comment by Tkael** [comment]
Yes, that appears to be the correct conclusion. Thank you. I'll fix this for the next release. o7
