### ISSUE TITLE
EDDI Plugin 4.0.2 Update affects Voiceattack shutdown

### ISSUE THREAD

**Issue by Maskzone** [EDCD/EDDI#2484]
I have rolled back EDDI 4.0.2 to EDDI 4.0.1 as when the latest version of EDDI is installed and plugin support enabled in Voiceattack, it prevents the complete shutdown of Voiceattack: this then prevents you restarting Voiceattack again. To restart Voiceattack you have to go to task manager and end the Voiceattack exe task in order to restart the app.
 
### Expected
Voiceattack shuts down and then if required can be restarted without having to go to the Task Manager and killing the Voiceattack task.

### Observed
Unable to restart Voiceattack after closing app with EDDI plugin 4.0.2 installed and enabled.

### Configuration
* Version
  * EDDI Version: 4.0.2
  * VoiceAttack Version: 1.10.3 - Steam 64bit
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: Amy
 
## My Investigation
###To restart Voiceattack you have to go to task manager and end the Voiceattack exe task in order to restart the app.

**Comment by Darkcyde13** [comment]
This sounds very similar to what I have been experiencing with the betas ([here](https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-10055291)), although I've not had it (yet) with the release version.

See if it still happens after disconnecting the Frontier API, because that seems to be what causes my problems.  It's just that, for me, it's intermittent, but when it starts, then it happens much more frequently.

**Comment by Tkael** [comment]
It does indeed sound similar. Some process not getting the request from VoiceAttack to close perhaps.

**Comment by nepomuk16321** [comment]
I visited some systems tonight and scanned many objects (about 17:30 - 22:30). VA and EDDI (v.4.0.2 - but NOT with the original character) were in operation. EDDI as a plugin from VA (v1.10.3 - 64-bit). API is connected. Not a single crash so far.
Can I help with any log, maybe as comparison ?
Greetings from nepomuk

**Comment by daBernd** [comment]
Same issue here,
I provide a EDDI logfile when VA/EDDI it is starting "the right way". That means the green message from EDDI " EDDI is fully operational" appears.
Often EDDI does not bring this message. And so the whole events are not running.
The only way to bring EDDI back to life then, is to delete the EDDI.sqllite file under Appdata\ Roaming\EDDI.
[eddi.log](https://github.com/EDCD/EDDI/files/10410611/eddi.log)

This second log is when there is no sucess message from EDDI
[eddi.log](https://github.com/EDCD/EDDI/files/10410628/eddi.log)

**Comment by Tkael** [comment]
I believe this is resolved for the next release.
