### ISSUE TITLE
Ship Module and Ship Hard Point Arrays  

### ISSUE THREAD

**Issue by Glock-N-Load** [EDCD/EDDI#2486]
The Ship Module and Ship Hard Point Arrays are empty (other arrays could be affected)

I scan these arrays to find if a module/utility module is on my ship. After going from EDDI v4.01 to v4.0.2 these arrays are returning empty.
{INT:Ship compartments} This value is blank
{TXT:Ship compartment -index- module}: the name of the module in this slot. All are empty
{TXT:Ship tiny/small/medium/large/huge hardpoint -index- module} All are empty

**Comment by Darkcyde13** [comment]
This could also be related to #2482.  If so, it sounds like some VA variables are not being correctly populated.

**Comment by Tkael** [comment]
Thanks for the report. Closing as a duplicate of #2482.
