### ISSUE TITLE
Ship cargo capacity: {INT:Ship cargo capacity} tons

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2489]
### Expected
Result is zero

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  latest EDDI

**Comment by FireSammy** [comment]
Used to work just fine

**Comment by Darkcyde13** [comment]
Sounds like the same thing as reported in #2482.

**Comment by Tkael** [comment]
Thanks for the report. Closing as a duplicate of #2482.
