### ISSUE TITLE
"Flight assist" script incorrectly handles some UI interactions while in supercruise

### ISSUE THREAD

**Issue by slippycheeze** [EDCD/EDDI#2496]
### Expected
EDDI runs the script when I manually change flight assist; it stays silent when it automatically enables (eg: entering supercruise kinda turns it on, but only because it is in state 3 of the boolean, "in supercruise").

### Observed (and steps to reproduce)
1. GOOD: EDDI announces "flight assist disabled" when I manually turn it off, as it should.
2. BAD: EDDI announces "flight assist enabled" when I enter supercruise, even though (a) it will be off when I return to normal space, and (b) I didn't change the state.
3. BAD: EDDI announces "flight assist disabled" when I open various UI controls:
   - the system map
   - the galaxy map
   - the main menu
4. BAD: EDDI announces "flight assist disabled" when I return to normal space (exit supercruise), even though it was off before I started supercruise.

### Configuration
* Version 
  * EDDI Version: v.4.0.2
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: en-GB
  * Voice: Microsoft Zira / English

### EDDI Logs
I enabled "verbose" logging, because I'm pretty sure you want all those debug details to figure this one out.   Hope that isn't an inconvenience.  I did trim the log to exclusively the section where my "test it behaves the way I think" sequence from "observed" happened, so you should only have those events.

Pretty sure it includes the journal content, too, so I figure you don't need a second copy.

[eddi-flight-assist-bug.zip](https://github.com/EDCD/EDDI/files/10428762/eddi-flight-assist-bug.zip)

**Comment by Tkael** [comment]
I respectfully disagree. It's technically correct to say that flight assist is enabled during supercruise and disabled again when you re-enter normal space and I don't think it really makes sense to change this behavior when you should already be able to modify your script (by checking the values of other status properties like `status.fsd_status`) to filter out speech in particular cases like these where you'd prefer not to hear speech.
