### ISSUE TITLE
After Ship Swap ((EDDI events)) completely stop working

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2509]
## What's Wrong (please be as specific as possible)
After Ship Swap ((EDDI events)) completely stop working, meaning I have to completely restart the game and VA. This might be a VA problem with the plugin, but not sure. It seems to be the problem with EDDI

### Expected
[Describe what you expected to happen]
Expect to see and work with normal ((EDDI events)) as usual, just to name a few, -Undocked, fsd variables, jumped, etc...

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
Every time I log in and swap ship and try to launch from the station and jump

If this is a duplicate, I'm sorry. I couldn't find this from any of your issues list nor closed issues list

**Comment by nepomuk16321** [comment]
Hello FireSammy, I have tested the ship change. VA_Version 1.10.3 64bit and EDDI v.4.0.2 . Well what can I say, everything worked for me. I have changed the ship several times, jumped and back again, no problems. Probably it is helpful for T'Kael if you upload the eddi.log with the crash here.

**Comment by FireSammy** [comment]
Ok i will test it right now. I have the same VA and EDDI versions as you have. Plugin support has been initialized as fully operational and EDDI API connect is on

**Comment by FireSammy** [comment]
First ship swap from Anaconda to Diamondback Explorer was successful, and everything works ok. Second Swap from Diamondback Explorer to Imperial Cutter worked ok too. I don't get this. It seems that I cannot reproduce this problem the same way it happened last time. The problem occurred two times before I posted it as an issue here. I would hope to keep this open if this problem rises again

**Comment by nepomuk16321** [comment]
EDDI writes a new log file at every start in the directory where the directory "personality" is located. That are together 10 log files. Maybe you still have the log with the error. Have a look. If yes, then post the log here. Maybe T'Kael can read something from it.

**Comment by Tkael** [comment]
Some users have reported a locking condition that can prevent a clean exit from VA when the Frontier API is active (I think that should be just about solved for the next release). This could perhaps be related.

**Comment by FireSammy** [comment]
Just a minute ago this happened again after swapping from Diamondback Explorer to Imperial Cutter, attachment EDDI log file. I had to restart the game and VA. After logging back in and not swapping ship, many errors that I have reported previously about ((EDDI events)) and many other variables seem to work just fine, so these problems are -must be related to ship swapping... I suggest you take a look at this please, thank you

[eddi.log](https://github.com/EDCD/EDDI/files/10767417/eddi.log)

**Comment by FireSammy** [comment]
After two hours of mining, swapping from Imperial Clipper back to Diamondback Explorer, no issues. I dont understand??
After this, i did some passenger missions and swapped ships 2 times, without any problems. I repeat, i dont understand this bug...

**Comment by FireSammy** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/10804828/eddi.log)

**Comment by FireSammy** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/10804981/eddi.log)

**Comment by Tkael** [comment]
Please re-test with recently released version 4.0.3-b1?
