### ISSUE TITLE
Exclude non-english voices from random voice select when reading english event text

### ISSUE THREAD

**Issue by ccstorm-nl** [EDCD/EDDI#2512]
Probably hosted in EddiSpeechResponder.CustomFunctions.

It is a reeeeeeel pain to the ears when you hear a dutch voice trying to read english text....

**Comment by Tkael** [comment]
Please add the voice name you wish to exclude to this section of the script:
![image](https://user-images.githubusercontent.com/4382539/221426319-a228b576-f59d-46ce-9f69-b6815151984f.png)
