### ISSUE TITLE
Found Potential Bug? 

### ISSUE THREAD

**Issue by MacMonkey93** [EDCD/EDDI#2514]
EDDI does not display any icon in sound setting nor sound mixer and does not play sound at all. 

### Expected
I expected for the app to play sound when used. 

### Observed
When i pressed the  Test voice button under the "Text-to-Speech" Tab so see if I could hear it respond to me nothing plays.

### Steps to reproduce
1. Open app, Go to "Text-to-Speech" tab click on Test voice and hear if it responds. Look in sound mixer and sound setting for the EDDI App
![Thing no workie](https://user-images.githubusercontent.com/50534477/221424202-876eec33-64cb-471a-a436-57282fab81d4.PNG)
2. Test to see if EDDI appears in the sound settings and test if it responds. 

### Configuration
* Version 
  * EDDI Version: v.4.0.2
  * VoiceAttack Version: Voice Attack not used 
* Localization 
  * EDDI's language: English
  * Voice:  Microsoft George in English.

## My Investigation:
I have uninstalled EDDI twice, Had removed voice attack to eliminate that causing issues. Made sure every check mark was set for the app to work correctly,  
### Investigation Notes:
I was running the old version v.4.0.1 and the same issues applied as v.4.0.2. 

### EDDI Logs
No log file found.

**Comment by Tkael** [comment]
Did you look for log files? They'd be at `%APPDATA%/EDDI` on your computer and suffixed with a `.log` extension.
![image](https://user-images.githubusercontent.com/4382539/221426513-5b16e586-4b6e-4341-b1f5-f0cb72e91e53.png)

![image](https://user-images.githubusercontent.com/4382539/221426537-1afbfef5-da07-4608-9c32-5227a2a5d9af.png)

If EDDI doesn't generate any .log files then it is either failing very quickly after it starts (in which case the UI probably wouldn't appear at all) or there may be a file permission issue preventing it from writing to the folder location discussed above.

**Comment by MacMonkey93** [comment]
Do you want all of the log files?

**Comment by Tkael** [comment]
You are free to provide just what you think might be useful. I probably won't need more than the most recent couple but it won't be a problem if you wish to send more.

Please attach them to this ticket in a `.zip` folder.

**Comment by MacMonkey93** [comment]
I will just send all the log files as im not exactly sure which ones to send. 
[EDDI Logs.zip](https://github.com/EDCD/EDDI/files/10834335/EDDI.Logs.zip)

**Comment by Tkael** [comment]
This appears to be the primary problem:
```
2023-02-26T16:30:34 [Warning] SpeechService:play Failed to speak; CSCore not registered. Installation may be corrupt or Windows version may be incompatible.: {"ClassName":"CSCore.CoreAudioAPI.CoreAudioAPIException","Message":"IAudioClient::IsFormatSupported caused an error: 0x80070057, \"The parameter is incorrect.\".","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at CSCore.CoreAudioAPI.AudioClient.IsFormatSupported(AudioClientShareMode shareMode, WaveFormat waveFormat, WaveFormat& closestMatch)\r\n   at CSCore.SoundOut.WasapiOut.SetupWaveFormat(IWaveSource source, AudioClient audioClient)\r\n   at CSCore.SoundOut.WasapiOut.InitializeInternal()\r\n   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)\r\n   at EddiSpeechService.SpeechService.play(IWaveSource source, Int32 priority) in EddiSpeechService\\SpeechService.cs:line 305","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nIsFormatSupported\nCSCore, Version=1.2.1.2, Culture=neutral, PublicKeyToken=5a08f2b6f4415dea\nCSCore.CoreAudioAPI.AudioClient\nBoolean IsFormatSupported(CSCore.CoreAudioAPI.AudioClientShareMode, CSCore.WaveFormat, CSCore.WaveFormat ByRef)","HResult":-2147024809,"Source":"CSCore","WatsonBuckets":null,"Interface":"IAudioClient","Member":"IsFormatSupported"}
```

As you appear to be using Windows 10 (same as I am), I would suggest the following:
1) Check for windows installation / corruption issues as described [here](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e).
2) Reinstall EDDI.
3) Report back to let me know if the issue is still present?

Additionally: You seem to be using the `Name (spoken)` field in the `Commander Details` tab improperly as `MacMonkey93` is not a valid IPA code that can be converted into a phonetic pronunciation of your commander name. Try using this instead: `mækˈmʌŋkiˈnaɪntiˈθɹi`.

**Comment by MacMonkey93** [comment]
![Capture](https://user-images.githubusercontent.com/50534477/221431105-9846eff7-9903-4249-856d-3079181cacdf.PNG)
This is from the windows ten fix and nothing is wrong with that so i guess il try another reinstall.

**Comment by Tkael** [comment]
Are you perhaps using audio drivers which differ from the Windows default?

**Comment by MacMonkey93** [comment]
Yeah im using Realtek audio drivers

**Comment by Tkael** [comment]
In that case you might try reinstalling / updating your audio drivers.

**Comment by MacMonkey93** [comment]
Alright il try reinstalling my audio drivers

**Comment by MacMonkey93** [comment]
my audio drivers are upto date and theres nothing wrong with them sooo what now?

**Comment by Tkael** [comment]
I'll try adding a fallback in the next release but this seems like it may be more of a Windows (and perhaps registry) issue than an EDDI issue. I'm not sure there's very much else that I can do.
