### ISSUE TITLE
{DEC:Credits} not working at the moment

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2515]
As the header says {DEC:Credits} is not working at the moment. EDDI is operational, connected.
Other credit values are working such as {DEC:EDDI commander continued credits}

**Comment by FireSammy** [comment]
Weird, as {DEC:Credits} worked when logging out programmed with ((EDDI shutdown)), It was the correct credit value. Weird...

**Comment by Tkael** [comment]
By "not working", I assume that you mean that it is returning a value of zero credits (or perhaps failing to update correctly after a transaction)? 
Could be related to some recent hiccups with accessing the Frontier API. 
I'll add a little bit of code to try to guard against a null result from the Frontier API.

**Comment by Tkael** [comment]
Again, please be as descriptive as possible in your bug reports. The more specific you are, the more likely that I'll be able to provide an effective fix.
