### ISSUE TITLE
{DEC:EDDI ship transfer initiated distance} Does not seem to be working now

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2516]
## What's Wrong (please be as specific as possible)
As the header says {DEC:EDDI ship transfer initiated distance} is not working at the moment. All other variables in the 
((EDDI ship transfer initiated)) available are working

**Comment by Tkael** [comment]
Please use the template when submitting bug reports. In this case, it would be helpful to know (for instance) which version of EDDI you are using currently and to have a copy of the player journal data associated with this issue.
