### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by EdgarsRD** [EDCD/EDDI#2518]
Installed EDDI, after that I tried to connect to frontier API and got the following error.

"The exception unknown software exception (0xe0434352) occured in the application at location 0x000000007633B922"

No idea what that means.

**Comment by Tkael** [comment]
This seems like it could be a glitch in your .net framework installation. [Here](https://thegeekpage.com/how-to-solve-unknown-software-exception-0xe0434352/) are a few options to assist with troubleshooting.
