### ISSUE TITLE
Body Scan reads only gravity and body type, regardless of other planetary information.

### ISSUE THREAD

**Issue by StepnSteph** [EDCD/EDDI#252]
## Steps to reproduce

1.

Body Scan reports _ONLY_ "This planet is a (gravity rating) (body type)", where gravity and body types are relevant to the scan. It ignores all other information about the planet such as, for example, whether it is ringed, or suitable for landing, or what materials it contains, volcanism or so on.

2. 

It happens all the time on all planets, regardless.

## Expected

That the other information is vocalized.

## Observed

See #1 above.

## Investigation

Since this happens by default I've created a new personality and attempted to modify the script, in large part just moving bits around or removing certain lines, to see what happens. It has no effect.

**Comment by Tkael** [comment]
Please confirm whether you are using the default versions of the `Body report` and `Body scanned` scripts in EDDI?
1. Navigate to the Speech responder tab
2. Find those two scripts
3. For each script:
  a. Click the `edit` button
  b. Click `Reset to default`
4. After resetting both scripts, does the issue repeat? 

Please also specify the version of EDDI that you are currently using?

**Comment by StepnSteph** [comment]
I can do this, but it does this by default straight out of installation. I only made the second personality and tinkered with it in an attempt to manipulate the behavior.

I did install over an old version of EDDI. Actually come to think of it I'm going to completely delete the EDDI folder and re-install it. Be back with the results of that.

**Comment by Tkael** [comment]
Reinstallation does not overwrite/change your customized personalities.

**Comment by StepnSteph** [comment]
Back. It's behaving the same.

I uninstalled via the Apps & Features menu and then went into the AppData\Roaming and deleted the EDDI folder there. I then re-installed, entered my login details for the Frontier API, and left everything else at default.

For whatever reason, EDDI seems to skip everything except for gravity and {reportbody.planettype} .

**Comment by Tkael** [comment]
Does this occur when you hit the 'test' button, when you scan a body in-game, or both?

**Comment by StepnSteph** [comment]
Both.

**Comment by Tkael** [comment]
Then you're reset everything that I can think of. In anyone else wants to weigh in, I'm at a bit of a loss. Have you tried testing each of the variables individually to see if they are set?

**Comment by Darkcyde13** [comment]
I've tested the default script out and I have to agree, some of the report is not being spoken, although I'm not sure why.  My guess is that reportbody isn't being fully populated.

Using the default script, I've scanned a landable planet, and this is the result:-

>  Scan complete. Crucis Sector charlie victor dash papa alpha fife dash fawer tree is a low-gravity Icy body that is suitable for landing. It has a fast rotational period of 0.44 days. Estimated scan value: 996 credits

It should have reported the radius, mass and the materials, but it doesn't.

However, using my own script, and scanning another landable planet in the same system, I get this:-

> Planet 1 is a low-gravity Icy body that is suitable for landing. It has a radius of 4785 kilometers, less than eighty percent of the radius of Earth, and less than one third of Earth's mass. It has a rotational period of 2 days. This body is made up from: Sulphur, Carbon, Iron, Phosphorus, Nickel, Chromium, Zinc, Vanadium, Niobium, Molybdenum and Polonium,.

The only major difference between the default script and my own is that I have added triple redundancy fall backs for 'reportbody' (may be overkill, but it works).  I have this near the top of my script:-
```
{_ Set reportbody to event data _}
{set reportbody to event}
{set eventdata to true}

{_ Fallback to BodyDetails if no event data _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
    {set eventdata to false}
}

{_ Second fallback if BodyDetails fails with system argument above _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name)}
    {set eventdata to false}
}
```
@StepnSteph try adding this to the top of your script, just below where the state variables are set.  See how that works for you.

As a side note, the reason I set 'eventdata' is for the following section I have in my version of the script:-
```
    {_ Radius}
    {if reportbody.radius:
        {if eventdata:
            {_ Convert radius if data is from event as this is in meters _}
            {set radius to round(reportbody.radius/1000, 1)}
        |else:
            {set radius to round(reportbody.radius, 1)}
        }

        It has a radius of {radius} kilometers,

        {set compare_radius to radius / 6371}
        {compare(compare_radius)}
        the {OneOf("size","radius")} of Earth,
    }
```
The radius from the event is in meters, while the radius from BodyDetails() is in kilometres.

If you like, I can post my complete script.

**Comment by Tkael** [comment]
That discrepancy between the event and BodyDetails() function is something that we're going to deal with in an upcoming update. As is the unreliable data we sometimes get from the server.

**Comment by Tkael** [comment]
If it is an issue with bad server data, it shouldn't be happening "... all the time on all planets...". @StepnSteph, can you confirm whether the issue that Darkcyde described fits with your observations?

**Comment by StivlWrith** [comment]
for the problem of "Body report" script, I use this at the start of the script:

```
{set Bodies to []}
 {for Bodies in system.bodies:
  {if Bodies.name = state.eddi_context_body_name: {set reportbody to Bodies} }
 }
```

since, I have no more problems

**Comment by StepnSteph** [comment]
Hey folks,

I've just tried both StivlWrith's and DarkCyde13's fixes (each individually and together because why not) and my situation is the same as before.

Literally every planet only reports (planet name) is a (gravity type) (body type). That's all that's ever returned.

For example, I just scanned a landable planet (and I do have Horizons, of course) and EDDI says: "PlanetName is a low gravity icey body".

Note that gas giants report according to their type. I can't spell the stuff but, for example, if I scan a gas giant it will say "PlanetName is a sardoski class I gas giant with ammonia based life" etc etc. That's from off the type of my head, but I'm sure that you're familiar with what I'm talking about.

Anyroad, nothing is ever mentioned about being landable, or about rings, or about volcanism (if present), and so forth.

Here it is with both of their additions added to the other. I've replaced the PlanetName with "This is a" because let's face it, these planet names are crazy. The rest is copy / paste from EDDI's default.

------------

{_ Fetch from context }
{set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
{if !reportbody.name || reportbody.name = "": {set reportbody to BodyDetails(state.eddi_context_body_name)} }

{set Bodies to []}
 {for Bodies in system.bodies:
  {if Bodies.name = state.eddi_context_body_name: {set reportbody to Bodies} }
 }

{_ Set reportbody to event data _}
{set reportbody to event}
{set eventdata to true}

{_ Fallback to BodyDetails if no event data _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
    {set eventdata to false}
}

{_ Second fallback if BodyDetails fails with system argument above _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name)}
    {set eventdata to false}
}

{if !reportbody.name || reportbody.name = "":
    I'm not sure which body you are asking about.
|else:
    This is a
    {if reportbody.gravity < 0.5:
        low-gravity
    |elif reportbody.gravity <2:
        medium-gravity
    |elif reportbody.gravity <4:
        high-gravity
    |else:
        extremely high-gravity
    }

    {if reportbody.tidallylocked:
        tidally-locked
    }

    {if reportbody.terraformstate = "Terraformable":
        terraformable
    |elif reportbody.terraformstate = "Terraformed":
        terraformed
    }

    {if len(reportbody.rings) > 0:
        ringed
    }

    {reportbody.planettype}

    {if reportbody.terraformstate = "Terraforming":
      in the process of being terraformed
    }

    {if type(reportbody.landable) != "void": 
        that is
        {if reportbody.landable:
            suitable
        |else:
            unsuitable
        }
        for landing
    }
    . {_ note the full stop}

    {_ Atmosphere? }

    {if reportbody.volcanism:
        This planet shows signs of volcanism, with
        {if reportbody.volcanism.type = 'Geysers':
            {if reportbody.volcanism.amount = 'Major':
                high numbers of
            |elif reportbody.volcanism.amount = 'Minor':
                low numbers of
            }
            active {reportbody.volcanism.composition} geysers
        |else:
            {if reportbody.volcanism.amount = 'Major':
                high levels of
            |elif reportbody.volcanism.amount = 'Minor':
                low levels  of
            }
            active {reportbody.volcanism.composition} magma flows
        }.
    }

    {if reportbody.landable :
        It has a
        {if reportbody.rotationalperiod < -20.0:
            slow retrograde
        |elif reportbody.rotationalperiod < -0.5:
            retrograde
        |elif reportbody.rotationalperiod < 0:
            fast retrograde
        |elif reportbody.rotationalperiod <= 0.5:
            fast
        |elif reportbody.rotationalperiod > 20.0:
            slow
        }
        rotational period of {Humanise(reportbody.rotationalperiod)}
        day{if Humanise(reportbody.rotationalperiod) != "1":s}.

        {set goodmaterials to []}
        {set greatmaterials to []}
        {for material in reportbody.materials:
            {if material.percentage >= MaterialDetails(material.material).greatpctbody:
                {set greatmaterials to cat(greatmaterials, [material])}
            |elif material.percentage >= MaterialDetails(material.material).goodpctbody:
                {set goodmaterials to cat(goodmaterials, [material])}
            }
        }

        {if len(greatmaterials) > 0:
            This body contains very high levels of
            {if len(greatmaterials) = 1:
                {greatmaterials[0].material}
            |elif len(greatmaterials) = 2:
                {greatmaterials[0].material} and {greatmaterials[1].material}
            |else:
                {set cur to 0}
                {while cur < len(greatmaterials):
                    {if cur = 0:
                        {greatmaterials[cur].material}
                    |elif cur < len(greatmaterials) - 1:
                        , {greatmaterials[cur].material}
                    |else:
                        , and {greatmaterials[cur].material}
                    }
                    {set cur to cur + 1}
                }
            }
        }
        {if len(goodmaterials) > 0:
            {if len(greatmaterials) > 0:
                and high levels of
            |else:
                This body contains high levels of
            }
            {if len(goodmaterials) = 1:
                {goodmaterials[0].material}
            |elif len(goodmaterials) = 2:
                {goodmaterials[0].material} and {goodmaterials[1].material}
            |else:
                {set cur to 0}
                {while cur < len(goodmaterials):
                    {if cur = 0:
                        {goodmaterials[cur].material}
                    |elif cur < len(goodmaterials) - 1:
                        , {goodmaterials[cur].material}
                    |else:
                        , and {goodmaterials[cur].material}
                    }
                    {set cur to cur + 1}
                }
            }
        }
        {if len(greatmaterials) > 0 || len(goodmaterials) > 0:
            .
        }
    }
}

**Comment by Tkael** [comment]
I need to know which body / system you are scanning so that I can review the server data for that location.

**Comment by StivlWrith** [comment]
I just think about something. One time I had something like that, and after some days (or weeks), i realised that i forget to put the advanced surface scanner in my ship (don't remember if i had none or just basic surface scaner). In the result of scan, there was lot of differences. 
If not that, what you can do is to take a look in the game log if your scan log have all the needed informations like
`{ "timestamp":"2017-11-27T13:01:31Z", "event":"Scan", "BodyName":"NGC 4463 Sector PI-P b36-5 B 4", "DistanceFromArrivalLS":45999.742188, "TidalLock":false, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.021067, "Radius":2293842.500000, "SurfaceGravity":1.595805, "SurfaceTemperature":37.459572, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":22.409916 }, { "Name":"carbon", "Percent":18.844418 }, { "Name":"iron", "Percent":15.498662 }, { "Name":"phosphorus", "Percent":12.064520 }, { "Name":"nickel", "Percent":11.722539 }, { "Name":"chromium", "Percent":6.970263 }, { "Name":"manganese", "Percent":6.400789 }, { "Name":"germanium", "Percent":3.273058 }, { "Name":"tin", "Percent":1.007667 }, { "Name":"ruthenium", "Percent":0.957141 }, { "Name":"tungsten", "Percent":0.851032 } ], "SemiMajorAxis":315986444288.000000, "Eccentricity":0.000067, "OrbitalInclination":0.051758, "Periapsis":279.576050, "OrbitalPeriod":231043632.000000, "RotationPeriod":146188.468750, "AxialTilt":0.500253 }
`

You can find (it's like that for me) in 

> C:\Users\YourAccount\Saved Games\Frontier Developments\Elite Dangerous

**Comment by Darkcyde13** [comment]
@StepnSteph I'm not sure how Stivlwriths code can break the script.  It simply scans through the system bodies and sets up 'reportbody' if one of them matches the current body.  It shouldn't matter where that snippet of code is.

However, because you have put it after my code, it totally voids what mine does.  Like wise, putting mine after his will void what his does, as they will both overwrite what the previous one has set up.

Use one OR the other, but not both at the same time.

That being said, Stivlwriths code will suffer the same problems the default script has, because it gets the data from BodyDetails(), just as the default does.  The advantage of using my code is that it tries to get the data from the scan event itself first, which seems to be a bit more reliable than trying to get the data from the EDDN(?) server, as this (on occasion) is less than 100% reliable.

If you are calling the Body Report script by itself, and not from the Body Scanned event, then all three versions (default, mine, and Stivlwriths) will always get the data from the EDDN server, as that is the only source for the data.

Just to be sure, try replacing the whole Body Report script with my version.  So, open the Body Report script, delete everything, and paste in the following:-

```
{_ Tries to use event data first, with fallbacks to BodyDetails() _}
{_ Some variables are different between these two, so script now works with both _}
{_ Set each section to only speak if that data is available. Basic/Advanced Scanner fix _}


{set compare(stat) to:

    {if stat > 0.95 && stat < 1.05:
        {OneOf("approximately","roughly","nearly")} equal to 
    |elif stat > 1:
        {Humanise(stat)} times
    |elif stat < 1:
        {if stat > 0.89: {OneOf("fractionally","just")}}
        less than
    }

    {if stat < 0.01:
        one percent of
    |elif stat < 0.1:
        ten percent of
    |elif stat < 0.2:
        one fifth of
    |elif stat < 0.3:
        one third of
    |elif stat < 0.4:
        forty percent of
    |elif stat < 0.5:
        half of
    |elif stat < 0.6:
        two thirds of
    |elif stat < 0.7:
        seventy percent of
    |elif stat < 0.8:
        eighty percent of
    |elif stat < 0.9:
        ninety percent of
    }
}

{_ Set reportbody to event data _}
{set reportbody to event}
{set eventdata to true}

{_ Fallback to BodyDetails if no event data _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name, state.eddi_context_body_system)}
    {set eventdata to false}
}

{_ Second fallback if BodyDetails fails with system argument above _}
{if !reportbody.name || reportbody.name = "":
    {set reportbody to BodyDetails(state.eddi_context_body_name)}
    {set eventdata to false}
}

{if !reportbody.name || reportbody.name = "":
    {_ If it's still not possible to get the body name...  _}
    I'm
    {OneOf("not sure","unsure")}
    {Occasionally(2,"of")}
    which body
    {OneOf("you are","you're")}
    {OneOf("asking about","referring to")}.
|else:
    {reportbody.name} is a

    {if reportbody.gravity:
        {if reportbody.gravity < 0.5:
            low-gravity
        |elif reportbody.gravity <2:
            medium-gravity
        |elif reportbody.gravity <4:
            high-gravity
        |else:
            extremely high-gravity
        }
    }

    {if reportbody.tidallylocked:
        tidally-locked
    }

    {if reportbody.terraformstate = "Terraformable":
        terraformable
    |elif reportbody.terraformstate = "Terraformed":
        terraformed
    }

    {if len(reportbody.rings) > 0:
        ringed
    }

    {if reportbody.bodyclass:
        {reportbody.bodyclass}
    |elif reportbody.planettype:
        {reportbody.planettype}
    |else:
        body
    }

    {if reportbody.terraformstate = "Terraforming":
      in the process of being terraformed
    }

    {if type(reportbody.landable) != "void": 
        that is
        {if reportbody.landable:
            suitable
        |else:
            unsuitable
        }
        for landing
    }
    . {_ note the full stop}

    {_ Radius}
    {if reportbody.radius:
        {if eventdata:
            {_ Convert radius if data is from event as this is in meters1_}
            {set radius to round(reportbody.radius/1000, 1)}
        |else:
            {set radius to round(reportbody.radius, 1)}
        }

        It has a radius of {radius} kilometers,

        {set compare_radius to radius / 6371}
        {compare(compare_radius)}
        the {OneOf("size","radius")} of Earth,
    }

    {_ Earth Mass}
    {if reportbody.earthmass:
        {if reportbody.radius:
            and
        |else:
            It is
        }
        {compare(reportbody.earthmass)}
        Earth's mass.
    }

    {_ Atmosphere? }

    {if reportbody.volcanism:
        This planet shows signs of volcanism, with
        {if reportbody.volcanism.type = 'Geysers':
            {if reportbody.volcanism.amount = 'Major':
                high numbers of
            |elif reportbody.volcanism.amount = 'Minor':
                low numbers of
            }
            active {reportbody.volcanism.composition} geysers
        |else:
            {if reportbody.volcanism.amount = 'Major':
                high levels of
            |elif reportbody.volcanism.amount = 'Minor':
                low levels  of
            }
            active {reportbody.volcanism.composition} magma flows
        }.
    }

    {if reportbody.landable:
        {if reportbody.rotationalperiod && !reportbody.tidallylocked:
            It has a
            {if reportbody.rotationalperiod < -20.0:
                slow retrograde
            |elif reportbody.rotationalperiod < -0.5:
                retrograde
            |elif reportbody.rotationalperiod < 0:
                fast retrograde
            |elif reportbody.rotationalperiod <= 0.5:
                fast
            |elif reportbody.rotationalperiod > 20.0:
                slow
            }
            rotational period of {Humanise(reportbody.rotationalperiod)}
            day{if Humanise(reportbody.rotationalperiod) != "1":s}.
        }

        {set goodmaterials to []}
        {set greatmaterials to []}
        {set allmaterials to []}
        {for material in reportbody.materials:
            {if material.percentage >= MaterialDetails(material.material).greatpctbody:
                {set greatmaterials to cat(greatmaterials, [material])}
            |elif material.percentage >= MaterialDetails(material.material).goodpctbody:
                {set goodmaterials to cat(goodmaterials, [material])}
            |else
                {set allmaterials to cat(allmaterials, [material])}
            }
        }

        {if len(greatmaterials) > 0:
            This body contains very high levels of
            {set cur to 0}
            {while cur < len(greatmaterials):
               {P(greatmaterials[cur].material)} at {round(greatmaterials[cur].percentage, 1)}%
               {set cur to cur + 1}
               {if cur = len(greatmaterials) - 1:
                   and
               |elif cur < len(greatmaterials) - 1:
                   ,
               }
            }
        }
        {if len(goodmaterials) > 0:
            {if len(greatmaterials) > 0:
                and
            |else:
                This body contains
            }
            high levels of
            {set cur to 0}
            {while cur < len(goodmaterials):
               {P(goodmaterials[cur].material)} at {round(goodmaterials[cur].percentage, 1)}%
               {set cur to cur + 1}
               {if cur = len(goodmaterials) - 1:
                   and
               |elif cur < len(goodmaterials) - 1:
                   ,
               }
            }
        }
        {if len(allmaterials) > 0:
            {if len(greatmaterials) > 0 || len(goodmaterials) > 0:
                It is also
            |else:
                This body is
            }
            {OneOf("comprised of","made up from")}:
            {set cur to 0}
            {while cur < len(allmaterials):
               {P(allmaterials[cur].material)}
               {set cur to cur +1}
               {if cur = len(allmaterials) - 1:
                   and
               |elif cur < len(allmaterials) - 1:
                   ,
               }
            }.
        }
    }
}
```

Then scan a planet/moon and see what you get as the result.  Of course, make sure you are using a Detailed Surface Scanner (DSS) on your ship, or you will only get very basic information.

**Comment by StepnSteph** [comment]
If I don't have a detailed surface scanner on my ship I swear to god I'm going to face palm with the bottoms of both of my bare feet. Every one of my ships have one and I've always bought them for each of my ships for... ever now.

I don't have access to any kind of port for awhile (out in the voice between Colonia and the Bubble)

Is there a way that I can check while out in space?

**Comment by Tkael** [comment]
Create a new script and paste this in, then hit the test button:
```
{for compartment in ship.compartments:
    {if compartment.module.name = "Advanced Discovery Scanner":
        {compartment.module.name} equipped.
    |elif compartment.module.name = "Basic Discovery Scanner":
        {compartment.module.name} equipped.
    |elif compartment.module.name = "Detailed Surface Scanner":
        {compartment.module.name} equipped.
    |elif compartment.module.name = "Intermediate Discovery Scanner":
        {compartment.module.name} equipped.
    }
}
```
For reference, FDev's Journal Manual has this to say about parameters available with different scanner configurations:
```
Note that a basic scan (ie without having a Detailed Surface Scanner installed) will now save a reduced amount of information.

A basic scan on a planet will include body name, planet class, orbital data, rotation period, mass, radius, surface gravity; but will exclude tidal lock, terraform state, atmosphere, volcanism, surface pressure and temperature, available materials, and details of rings. The info for a star will be largely the same whether a basic scanner or detailed scanner is used.
```

**Comment by StepnSteph** [comment]
Thank you sir.

It says that an Advanced Discovery Scanner is equipped.

**Comment by Tkael** [comment]
No detailed discovery scanner? It sounds like that's the problem then.

**Comment by StepnSteph** [comment]
Yep, that's all the script says.

I'm a creature of habit and drooling idget, apparently.

Well I'm off to bed.

**Comment by Tkael** [comment]
In any case, I'm glad we got it resolved. Sorry I had you looking at so many other things without doing this simple check first.
