### ISSUE TITLE
Text-to-Speak Changes between installed languages by itself while still reading english text

### ISSUE THREAD

**Issue by Nygosaki** [EDCD/EDDI#2520]
## What's Wrong (please be as specific as possible)
I have 2 language packs installed. English and Czech. I have my entire OS, and all applications set to use English. Sometimes, the TTS changes voices. First is the voice that I set myself. After that, the TTS continues changing voices until it reaches Microsoft Jakub (the Czech male TTS). After reaching Microsoft Jakub, it stays at that voice until I restart the program. I would like to note that Microsoft Jakub still tries to read English text, which results in a incoherent mess of sounds. 
### Expected
I would expect the voice to not change.

### Observed
N/A

### Steps to reproduce
1. Install the Czech Language pack
2. Unknown

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.2
  * VoiceAttack Version: N/A
* Localization [if applicable]
  * EDDI's language: English
  * Voice: Microsoft David - English

## My Investigation
N/A
### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
Nothing in logs that could point to the issues.

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
EDDI may prune it's list of available voices in response to an exception (and if this occurs then the the exception should be recorded in EDDI's .log files at `%appdata%/EDDI`). Could you please provide the .log file from a session where this occurred?

I would also suggest that you run a scan of your Windows installation in case some file corruption has affected the speech synthesizers. https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

**Comment by Tkael** [comment]
I was able to debug a somewhat similar issue from another user. 
I understand from your initial report that you are not using VoiceAttack. Please let me know if you are.
Are you using a customized EDDI personality to switch between voices? If you are, please share information about the scripts you are using for this purpose?

**Comment by Nygosaki** [comment]
> EDDI may prune it's list of available voices in response to an exception (and if this occurs then the the exception should be recorded in EDDI's .log files at `%appdata%/EDDI`). Could you please provide the .log file from a session where this occurred?

I am sadly unable to find the relevant play session's log file.
> I was able to debug a somewhat similar issue from another user. I understand from your initial report that you are not using VoiceAttack. Please let me know if you are. Are you using a customized EDDI personality to switch between voices? If you are, please share information about the scripts you are using for this purpose?

I am not using VoiceAttack, nor am I using any scripts.
I am using the app by itself without any changes/addons.
> I would also suggest that you run a scan of your Windows installation in case some file corruption has affected the speech synthesizers. https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

Wierdly enough, after following the article, the issue has not showed up again yet.

**Comment by Tkael** [comment]
Thanks for the update. o7

**Comment by Tkael** [comment]
Closing as presumably resolved.
