### ISSUE TITLE
Excluding a voice from message narration

### ISSUE THREAD

**Issue by Nygosaki** [EDCD/EDDI#2526]
## What happens now
When EDDI narrates messages sent in the chat, it uses a different voice for every message. If you have a Microsoft voice package for another language, it uses that too. This results in the voice saying nonsense as it tries to pronounce English words in it's on language.

## What I'd like to happen 
For the chat narration to not use voices that are in another language. 

## How it can happen
add a "exclude voice from usage" area, where you can click specific voices to prevent them from ever appearing.

## EDDI Version
4.0.2

**Comment by Tkael** [comment]
Hi there! If you examine the `Message received` script you'll find that there's a section already present in the script to exclude voices by name. Please feel free to revise the script and add any voice names you wish to exclude.

**Comment by Tkael** [comment]
![image](https://user-images.githubusercontent.com/4382539/229381255-2f60dc5c-b075-465c-94d3-a25e760c433a.png)
