### ISSUE TITLE
The announcement of the "launchbays" is not correct.

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#2530]
## What's Wrong (please be as specific as possible)
Smaller problem: The announcement of the "launchbays" is not correct.
No changes of the "launchbays" are recognized. The hangars are detected correctly. If the number of vehicles is queried via the script "Launchbay report", only one SRV is announced although I have installed two hangars (size 4 and size 2) with a total of 3 SRVs. I think the query via the API is not correct or does not work at all. But the connection to the API exists.

### Expected
Correct announcement of the number of e.g. SRVs.

### Observed
speechresponder.out: You have a size 2 sierra romeo victor hangar, holding 1 Scarab, with.
I have installed two hangars (size 4 and size 2) with a total of 3 SRVs.

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.4.0.2
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

## My Investigation
I changed the number and types of hangars. No change in the announcement.

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
 [These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games 
 folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue 
 occurred.]
[Journal.2023-04-10T235230.01.zip](https://github.com/EDCD/EDDI/files/11194290/Journal.2023-04-10T235230.01.zip)

**Comment by Tkael** [comment]
FDev changed the requirements for accessing the Frontier API a couple of weeks ago. As launchbay data is exclusively provided from the Frontier API, what you are observing is almost certainly one of the unfortunate effects of that change.

The change is a frustrating one (for two reasons):
1) It broke our released code.
2) It requires us to request access to more data than we need (including personal identifiable information (PII) about commanders). That data has always been included even when we hadn't specifically asked for it, and even though we don't parse that data, access to the Frontier API endpoints we use is apparently now conditional on us requesting it anyways. 

I've held off on patching this hoping that FDev would provide a better solution but so far all we've had is radio silence and I think I've waited just about as long as I can.
