### ISSUE TITLE
EDDI 4.0.2 does not listen "Configure EDDI" without function

### ISSUE THREAD

**Issue by Stephan-1967** [EDCD/EDDI#2538]
## What's Wrong
EDDI does not respond to his voice command

### Expected
I expected the configuration interface of EDDI to start after starting VoiceAttack with the command "Configure EDDI".

### Observed
Exactly nothing happens when you issue the "Configure EDDI" command. It looks like VoicAttack does not know the command at all. I managed to get VoiceAttack to recognize this command exactly once and respond with the message "Unrecognized: Configure EDDIE"  >> see also: Figure VoiceAttack_Start below.

### Steps to reproduce
1. Installing VoiceAttack from Stream to default Pass: C:\Program Files (x86)\Steam\steamapps\common\VoiceAttack
2. Installing EDDI to default Pass: C:\Program Files (x86)\Steam\steamapps\common\VoiceAttack\Apps\EDDI
3. Start VoiceAttack
4. Activate "Enable Plugin Support" into VoiceAttack
![General_Tab](https://github.com/EDCD/EDDI/assets/133263979/709cccfb-2feb-43b0-87e5-ea142c5f2525)
5. Make sure EDDI plugin is enabled:
![PluginManager](https://github.com/EDCD/EDDI/assets/133263979/5e239c97-1eb5-43c7-8bf2-e2e2c43a376d)
6. Make sure VoicAttack is listening
7. Say "Configure EDDI" sometimes: Nothing Happens or result is: "Unrecognized: xxxxxxx"
8. Say "Test" sometimes: it Works (Hint: This command is part of the used Profil)
![VoiceAttack_Start](https://github.com/EDCD/EDDI/assets/133263979/fe7fd87c-4fd2-4415-80af-a7b25c83dc15)

### Configuration
* Version
  * EDDI Version: 4.0.2
  * VoiceAttack Version: VoiceAttack 64-bit Version: v1.10.3 - Steam
* Localization N/A
  * EDDI's language: "Automatic"
  * Operation System language (English - US)
  * Voice: Microsoft Speech Recognizer 8.0 for Windows (Englisch - US)

## My Investigation
Try to run a HCS Plugin, result it works.
Try to run a HCS profile, result it works.
Try to use own profil, result it works (See File "VoiceAttack_Start: Command "Test".

### Investigation Notes
N/A

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/11455958/eddi.log)

### Player journals
N/A

**Comment by Tkael** [comment]
Please confirm that you have imported the basic EDDI.vap VoiceAttack profile from your installation folder and that it is either selected or linked to your primary profile? You can read more about EDDI.vap [here](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#eddis-voiceattack-profile).

**Comment by Stephan-1967** [comment]
Hello TKael,

thank you for the answer. Indeed, this solves my problem. :-)

I am unfortunately a complete newbie to VoicAttack, so I just followed the instructions, in the mistaken belief that it was a step by step guide. Since I have no idea, I assumed that the installer EDDI-4.0.2.exe implements all the necessary data. And yes I overlooked the simple fact that VoiceAttack does not show a profile for EDDI.

Maybe it would be useful to note in the section "Using EDDI with VoiceAttack" that you have to import the profile EDDI.VAP and that this file can be found in 
C:\Program Files (x86)\Steam\steamapps\common\VoiceAttack\Apps\EDDI or 
C:\Program Files (x86)\VoiceAttack\Apps\EDDI 
depending on your installation.

In the instructions it is also explained how VoiceAttack must be configured to use plugins, both information are on the same level of knowledge of the user.

Maybe this will help other "newbies" in the future.
