### ISSUE TITLE
EDDI No Pad Location statement

### ISSUE THREAD

**Issue by dalvon** [EDCD/EDDI#254]
EDDI no longer reports the location of the Pad upon approach. 
Reinstalled. Updated. 
Ensured all triggers are active. 
Ensured all plug-ins checked. 
Running VA in conjunction, no issues prior to last update.

**Comment by Tkael** [comment]
Which station and system? If the server doesn't include the particular station that you docked at, that may have had an effect.

**Comment by Tkael** [comment]
Closed as a suspected duplicate of #97. Please let us know if you have any more information about where this was observed.
