### ISSUE TITLE
Tarach Spice

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#255]
While fooling with inventory scripts and running the last CG, I found a typo in _DataDefinitions/CommodityDefinitions.cs_
 **Tarach Spice**; the EDName is written as **TarachSpice**  should be, **tarachtorspice**
Not worth opening a pull request. Might want to edit if you get a chance.

**Comment by Tkael** [comment]
Thanks for the report. Do you have a copy of the journal entry?

**Comment by rodan123** [comment]
Here is an entry from the **journal**;
_{ "timestamp":"2017-11-24T16:16:43Z", "event":"Cargo", "Inventory":[ { "Name":"tarachtorspice", "Count":8 }, { "Name":"drones", "Count":4 } ] }_

Looking through the **EDDI log** I found a more mismatches just from the last CG;
_2017-11-23T06:25:29 CompanionAppService:CommoditiesFromProfile [W] Commodity definition errors: [{"name":"Aepyornis Egg","category":"Foods","avgprice":9769,"rare":null,"buyprice":2262,"stock":0,"stockbracket":0,"sellprice":3065,"demand":0,"demandbracket":0,"StatusFlags":[],"EDDBID":0,"EDName":"CetiAepyornisEgg"},{"name":"Utgaroar Millennial Eggs","category":"Foods","avgprice":9163,"rare":null,"buyprice":1592,"stock":0,"stockbracket":0,"sellprice":2150,"demand":0,"demandbracket":0,"StatusFlags":[],"EDDBID":0,"EDName":"UtgaroarMillenialEggs"},{"name":"Tarach Spice","category":"Narcotics","avgprice":8642,"rare":null,"buyprice":987,"stock":0,"stockbracket":0,"sellprice":1289,"demand":0,"demandbracket":0,"StatusFlags":[],"EDDBID":0,"EDName":"TarachTorSpice"}]_ 

Looked at the code, don't see where the EDName is coming from. EDDB does not list that in the commodities.json where the rest of the info seems to have come from.

**Comment by rodan123** [comment]
Since there was more than one change, I created a pull request (#256) to make the changes.
I updated my local copy of EDDI, travelled to several of the systems, and verified I no longer get _Commodity definition errors_ and the script I wrote uses Commodity.name from the Commodity Template to list the cargo.

**Comment by Tkael** [comment]
Thanks. I'll be happy to look it over as soon as I get back in front of my coding pc.

**Comment by Tkael** [comment]
I've reviewed and approved the changes for incorporation. Closing this issue pending approval of the PR. Thanks for your contribution. :-)
