### ISSUE TITLE
Bookmark Navigation and Multi-Select Navigation

### ISSUE THREAD

**Issue by TROG111** [EDCD/EDDI#2550]
## What happens now
You can create bookmarks in the Navigation Monitor
You can select route plotting for all missions

## What I'd like to happen 
I would like to be able to use the bookmarks I have created as destinations and waypoint in the ship and fleet carrier route plotting panel.

I would also like to be able to select/deselect missions that should be included in the  mission route to be plotted.

## How it can happen
Have a button on the bookmark panel for each bookmark that will select that bookmark (or multiselect) and can be used in the route plotting panel

Have a button on the mission monitor panel for each mission that allow you to select/deselect/multiselect missions to be included/excluded from the mission route plotter.

## EDDI Version
4.0.3-b3

**Comment by Tkael** [comment]
For the sake of having a consistent and clear UI, I'd rather keep the ship and carrier plotting consolidated to the current tabs as much as possible. Selecting bookmarks or missions on one tab and then plotting relative to those selections on another tab is possible but perhaps not great.

What are the underlying problems that you're hoping to solve via these suggestions?

**Comment by Tkael** [comment]
It is already pretty easy to just copy a bookmarked name to the clipboard and then paste into the other tab.

**Comment by Tkael** [comment]
Closing and consolidating with #2555.
