### ISSUE TITLE
"Ship loadout" - error message in eddi.log, no voice output

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#2552]
## What's Wrong (please be as specific as possible)
I have discovered a problem with the "Ship loadout" script. If you buy a garage and then a buggy and switch to the station menu, the script "Ship loadout" (depending on the setup) should announce the equipment. The script "Ship loadout" also starts but nothing is announced acoustically. In the eddi.log you will find a warning and an error (... must not be zero). @T'Kael can you have a look at this ?

Translated with www.DeepL.com/Translator (free version)

### Expected
Announcement of the equipment of the ship (depending on the content of the script)

### Observed
The script is called but without announcements. An error is found in the eddi.log.

### Steps to reproduce
Buy hangar >> buy buggy >> back to station menu (now the script "Ship loadout" is called) >> no announcement, error message in eddi.log

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  EDDI v.4.0.3-b3
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable] German
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
If you start the script via the test button (i.e. after you have switched to the station menu), the text from the script is announced. 

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/11771789/eddi.log)

### Player journals
[Journal.2023-06-16T133516.01.log](https://github.com/EDCD/EDDI/files/11771884/Journal.2023-06-16T133516.01.log)

**Comment by Tkael** [comment]
`HullHealth` should always be present in the `Loadout` event but you seem to have found a circumstance where it is not. I'll work around it by assuming full health in this circumstance, but if a problem develops then we can report it to FDev bug tracker.
