### ISSUE TITLE
EDDI wipes main star data on jumping to a system

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2557]
### Expected
System data to remain intact at all times.

### Observed
Main star data is wiped (set to null) in the database when you jump to a system.

### Steps to reproduce
1. Check the JSON in the EDDI database for any system you have previously visited in the past.
2. Make sure it has correct data for the main star.
3. Jump to that system.  Do not close EDDI.
4. Recheck the JSON in the database.
5. Observe that the main star data is now all set to null.
6. Test EDDI for the system data.
7. Observe that EDDI has complete data for the main star.
8. Close and reopen EDDI.
9. Test for the system data again.
10. Observe that the main star data is now missing.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.3-b3
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I realised that one of my scripts was telling me I hadn't scanned the main star in systems I know that I have fully scanned.  So I checked the database and found the data for the main star was set to null.

I checked the database for another system I know I've fully scanned, and made sure the main star data was all there.  I then jumped to that system, and rechecked the database.  I found the database entry for that main star was now all set to null.

Reported on the forums, and confirmed in this post [here](https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-10173965).

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Darkcyde13** [comment]
I don't know if this is related at all, but I've also noticed that the 'shortname' for stars no longer removes the system name.  So, for example, the short name for "Wardal A" is literally that, instead of just "A".  If this is a separate issue, then I can open a new ticket for it.

**Comment by Tkael** [comment]
Ok. I think I've found the code segment that is causing the problem. It doesn't set a `systemname` property (which is needed for the `shortname` to work) so this observation is confirmatory evidence that I'm in the right place. :-)
