### ISSUE TITLE
{TXT:Last station name} results Not set, new working variable is {TXT:Current station name}

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2561]
## What's Wrong (please be as specific as possible)
{TXT:Last station name} resulting Not set

### Expected
Should give exact Station name last docked

### Observed
I have an automatic station check Voiceattack command that used to work every time very accurately. Now it doesnt

### Steps to reproduce
Every time I go to station the {TXT:Last station name} resulting Not set

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.3-b4
  * VoiceAttack Version: v1.10.6 64-bit

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]
[eddi.log](https://github.com/EDCD/EDDI/files/11957957/eddi.log)

**Comment by Tkael** [comment]
"Last station" was considered to be confusing and was changed in 4.0.3-b1 to "Current station" instead. Ref. https://github.com/EDCD/EDDI/releases/tag/Release%2F4.0.3-b1

**Comment by FireSammy** [comment]
Oh ok, need to update my commands then

**Comment by Tkael** [comment]
Additional context: https://github.com/EDCD/EDDI/issues/2464
