### ISSUE TITLE
Edit & Delete buttons greyed out on new scripts

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2562]
### Expected
The Edit and Delete buttons to be useable after creating a new script.

### Observed
The Edit and Delete buttons are greyed out and not clickable.

### Steps to reproduce
1. Create a new script, and click OK to save it.
2. Observe the Edit and Delete buttons are greyed out and not clickable.
3. Close and reopen EDDI.
4. Observe the buttons are now active and clickable.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.3-b4
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I noticed this a while ago, but I thought it was supposed to have been fixed.  However, I can't seem to find any issue raised for it, maybe I'm imagining it was fixed?

I've tried both in EDDI standalone and under VA, both have the same problem as described above.  To enable the buttons, you have to close EDDI or VA down totally, and re-open them.

### EDDI Logs
N/A
### Player journals
N/A

**Comment by Tkael** [comment]
This hasn't been on my radar but I'll certainly check it out.
