### ISSUE TITLE
VA {BOOL:EDDI speaking} always True

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2563]
### Expected
VA variable `EDDI speaking` to be True when EDDI is speaking, and False when EDDI is not speaking.

### Observed
The variable is initially 'Not set', then becomes True when EDDI speaks, but does not become False when EDDI finishes speaking.  It remains as True until VA is closed.

### Steps to reproduce
1. Load VA with EDDI as a plugin.
2. Test the variable `{BOOL:EDDI speaking}'
3. Observe is it 'Not set'
4. Run any EDDI script that produces speech.
5. Test the variable again.
6. Observe that it remains as True even when EDDI is no longer speaking.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.3-b4
  * VoiceAttack Version: v1.10.6
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I was updating some VA commands that use a loop to check if EDDI is speaking or not, and they were not progressing past the first loop that checked if EDDI was still speaking.  So I tested the `EDDI speaking` boolean in a separate new command, and even though EDDI had stopped speaking long ago, it remained set as True.  It seems only closing VA would reset it to `Not set`.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
Ah. I think I know what's going on there. o7
