### ISSUE TITLE
Refined commodities total: {DEC:Refined commodities} tons does not refresh to zero when swapping ship

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2566]
## What's Wrong (please be as specific as possible)
Refined commodities total: {DEC:Refined commodities} tons does not refresh to zero when swapping ship, and/or reset after selling cargo. Should be zero after selling

### Expected
{DEC:Refined commodities} should result zero

### Steps to reproduce
After swapping ship after selling the commodities from my cargo hold. Also when applying check cargo command, result is the same. It does not refresh to zero

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.3_b4
  * VoiceAttack Version: [if applicable] v1.10.6 64bit
  
[eddi.log](https://github.com/EDCD/EDDI/files/12070510/eddi.log)

![Screenshot 2023-07-17 173723](https://github.com/EDCD/EDDI/assets/21980416/d083596e-0ac8-4d35-b38e-041f7109afc9)

**Comment by Tkael** [comment]
I could be wrong but I don't think that EDDI has a `{DEC:Refined commodities}` variable?

A verbose log capturing a change in your refined commodities should show us for sure if EDDI is setting this value.

**Comment by Tkael** [comment]
What are the contents of your `Check cargo hold` command?

**Comment by FireSammy** [comment]
![Screenshot 2023-07-19 153214](https://github.com/EDCD/EDDI/assets/21980416/d5a1950b-376d-4af1-a69c-83fca389b751)

Variable has worked perfectly util now using ((EDDI: cargo)) and Check Cargo Hold command

The variable will reset when closing the game

**Comment by Tkael** [comment]
As near as I'm aware, EDDI does not currently and has not previously set a `Refined commodities` variable that resets when closing the game.
If you roll back EDDI to a prior revision then does that correct the issue? If so then at which version of EDDI? 
Have you made any changes to your VoiceAttack profile other than installing the latest EDDI beta?

**Comment by FireSammy** [comment]
Id rather not roll back EDDI, i have not done any changes to my voiceattack nor any commands, except installed the new versions to both voiceattack and EDDI. Im hundred % sure it worked great before and I use this quite often as I like to do mining 

And yes I just checked the Cargo Event and no variables listed, maybe you should update it ?? :)

Refined commodities variable is very useful to me, so I would recommend it to all miners

**Comment by Tkael** [comment]
You're sure that `Refined commodities` wasn't a variable that was or is being set somewhere inside your own profile?

You can make a backup of your settings at `%appdata%/EDDI` before rolling back to a prior version. If this is an EDDI issue then I need to know which build had the feature so that I can figure out what happened to it.

**Comment by FireSammy** [comment]
im sure it was not something that came out of somewhere else than the list of variables from EDDI integration list. I don't remember when I made this command list to Cargo event but I know its been there for quite some time. Again I don't want to roll back EDDI. Im absolutely sure it worked perfectly at least two steps back EDDI versions

**Comment by Tkael** [comment]
Here's the revision history for the VoiceAttack Integration page: https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration/_history
I've searched back as far as Dec. 18 2020 without finding any variable matching the description.

**Comment by FireSammy** [comment]
Im pretty sure its older than that. And yes it works perfectly after login into the game, I'm mining now as we speak and it gives correct numbers. It just doesn't reset after visiting the commodity shop emptying the material (selling) and or swapping ship. ITs as old as the command ((EDDI Cargo)) (I think) which is one of the youngest EDDI commands.

I have a faint recall this command had variables in it then, from which I got this variable. I have not invented it by my self

**Comment by Tkael** [comment]
> Im pretty sure its older than that. And yes it works perfectly after login into the game, I'm mining now as we speak and it gives correct numbers. It just doesn't reset after visiting the commodity shop emptying the material (selling) and or swapping ship. ITs as old as the command ((EDDI Cargo)) (I think) which is one of the youngest EDDI commands.
> 
> I have a faint recall this command had variables in it then, from which I got this variable. I have not invented it by my self

I've searched the current source code and the variable doesn't exist in the current source code. Something in your profile is apparently updating the variable but I am confident it is not EDDI.

**Comment by FireSammy** [comment]
LOL this is really weird. Im absolutely sure I got it from EDDI variables lists. I repeat I have not invented it by my self. Adding to that I really recommend you guys revisit this variable as it is partially working very well and its useful when used with cargo commands.

**Comment by Tkael** [comment]
If we were to add this variable it would be overwriting (and being overwritten by) whatever is writing this variable currently.

Perhaps this variable is being generated by HCS or another of the plugins in your setup?

You can try disabling plugins to see which stops that variable from updating.

**Comment by FireSammy** [comment]
I have no other plugins. Only use EDDI and all my variables have been manually done/added into the commands I have. I have never used HCS- No correction I had HCS some time the early days, but its really long time a go. It was quite basic and had problems, then but of course there I got I deas for my commands, but its about 10 years ago. I started to use EDDI as soon as I found about it. I cant tell how long I've used EDDI but feels like forever

**Comment by Tkael** [comment]
![image](https://github.com/EDCD/EDDI/assets/4382539/434c467b-a6ee-410d-bf36-1926818ccd25)
I still maintain that this variable is not tracked or controlled by EDDI.
There is no action that I can take to correct the OP's issue with this variable.
