### ISSUE TITLE
{DEC:EDDI ship transfer initiated distance} results Not set

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2567]
## What's Wrong (please be as specific as possible)
{DEC:EDDI ship transfer initiated distance} results Not set. Should give distance

### Expected
Should give correct distance

### Steps to reproduce
Every time transfer ship

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
EDDI Version: 4.0.3_b4
VoiceAttack Version: [if applicable] v1.10.6 64bit

Not important, very very small annoyance. Just thought someone would want to know

**Comment by Tkael** [comment]
It's just that one variable that is not set? 
Could you share a copy of a player journal from a play session from when this occurred?

**Comment by Tkael** [comment]
It might also be useful to know whether you were transferring ships between two stations, from a station to a carrier, from a carrier to a station, or between two carriers?

**Comment by Tkael** [comment]
Closing for lack of response and failure to replicate when transferring from a fleet carrier to a station in a neighboring system.
![image](https://github.com/EDCD/EDDI/assets/4382539/c4f9b721-1db8-4fa1-a850-ad66ca4d7884)

**Comment by FireSammy** [comment]
![Screenshot 2023-07-31 184853](https://github.com/EDCD/EDDI/assets/21980416/fa9d7bf1-db35-480a-9a0b-20fc27a028c9)

**Comment by Tkael** [comment]
I wasn't able to replicate this in my testing last week.

First, please provide a screenshot of your VoiceAttack command to make sure that you're invoking the variable correctly.

Second, please submit the player journal where this occurred so that I can feed the same data through EDDI and identify any issue?

o7

**Comment by FireSammy** [comment]
OMG i check'd my code and there was a one-letter typo... This means it has never worked, but I just haven't noticed this before the last update... Im terribly sorry for you guys to waste time testing this. MY bad... Once again I beg your forgiveness

The variable works correctly

![Screenshot 2023-08-07 182438](https://github.com/EDCD/EDDI/assets/21980416/65671435-12d2-49e7-96b5-145e21b98d64)

**Comment by Tkael** [comment]
I thought that might be the case. 😂 Glad it's figured out though.
