### ISSUE TITLE
Is Empire rank missing from the list {TXT:EDDI commander ratings empire rank}?? I think it is

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2572]
Is Empire rank missing from the list {TXT:EDDI commander ratings empire rank}?? I think it is from Commander ratings event. Could this be added??

**Comment by Tkael** [comment]
Empire ranks are differentiated with masculine and feminine rank names as described in https://github.com/EDCD/EDDI/wiki/Commander-ratings-event.
