### ISSUE TITLE
Eddie Crash when trying to connect to Frontier Api

### ISSUE THREAD

**Issue by emyrsmorgan** [EDCD/EDDI#2575]
## What's Wrong (please be as specific as possible)
Eddie pauses then crashed when i try to link to Frontier API
### Expected
[Describe what you expected to happen]
log into frontier api through frontier site
### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
I got into the Frontier APi settling and click the Log in Button, Eddie Pauses for a few secs then crashes 
### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]
I got into the Frontier APi settling and click the Log in Button, Eddie Pauses for a few secs then crashes 
### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.3
  * VoiceAttack Version: [if applicable] 
* Localization [if applicable] Win10 English
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]
[eddi.zip](https://github.com/EDCD/EDDI/files/12354300/eddi.zip)

**Comment by Tkael** [comment]
Well, there's an issue with your fleet carrier (I didn't think the available balance on your carrier could be negative but it's at -148848008). That's easy enough to fix but that didn't cause the crash.

According to the log, the crash actually is stemming from the Speech Service (triggered by the normal speech arising from the Frontier API connection process) and seems to occur when your system is trying to access the Windows Speech Synthesizer.

Please follow the following instructions [here](https://support.microsoft.com/en-au/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e) to check and repair any file system corruption on your PC. After repairing any corrupt files and restarting your PC, does the issue still occur? 

Do you have any issues with speech in EDDI when you are not connecting to the Frontier API?

**Comment by emyrsmorgan** [comment]
Wierd since my fleet carrior  balance definatly.not negative. I did find
one thing interesting eddie  voice works fine lf i run it though voice
attack but crashes if i try to run it
directly such as pressing test voice under text to speech. i also see that
the voice drop down has nothing listed dism and sfc found no errors.
perhaps some config file is corrupted for eddie? though  can  not find what
looks like one i

**Comment by emyrsmorgan** [comment]
btw if i start the configure eddi through voice attack that drop down
shows the correct voice and test voice works. though unfortuatke connect to
frontier is greyed out when run through voice attack

**Comment by Tkael** [comment]
The available balance is what's negative (rather than the total balance). I think this value is affected by the active buy orders on your carrier and similar.

From the log it doesn't look like a corrupted config file. It's like EDDI simply can't find / can't initialize the system speech synthesizer.

A few questions:
- According to your initial report you are running Windows 10. Which edition / version of Windows 10?
- When run through VoiceAttack, which voices are available? 
- Are you running either EDDI or VoiceAttack as an administrator?
- Are there any other applications running while EDDI is running that may be competing with EDDI for Speech Synthesizer resources, including VoiceAttack? (this is normally not a problem but I want to try to eliminate as many variables as I can)
- Does the crash occur 100% when triggering any speech through the `Text-To-Speech` tab or `Speech Responder` tab? Or is it only the Frontier API tab that triggers the crash?

**Comment by emyrsmorgan** [comment]
According to your initial report you are running Windows 10. Which edition
/ version of Windows 10?
Windows 10 Pro Version 21h2
  When run through VoiceAttack, which voices are available?
Windows tts default
microsoft Catherine
microsoft David
microsoft James
microsoft mark
microsoft zira

Are you running either EDDI or VoiceAttack as an administrator?
Voice attack and eddie are  runing as an Asministrator, i tried eddi as non
administrator and no change

re there any other applications running while EDDI is running that may be
competing with EDDI for Speech Synthesizer resources? (this is normally not
a problem but I want to try to eliminate as many variables as I can)
No

Does the crash occur 100% when triggering any speech through the
Text-To-Speech tab or Speech Responder tab? Or is it only the Frontier API
tab that triggers the crash?
100 percent though text to speech or Spech responder tab

Also i have both us  English (United states) and English (Austrailin)
Language packs installed on WIn 10 but am currentky using normal American
English   display pack Switching tro Austrailion does not solve the problem
though
wierf that eddie can not find the speech engine only when lauched stand
alone
tried uninstaling and Reinstaling eddie As admin no luck
Btw if i install Eddie Version 4.02 it works again in stand alone and
detects the voice engine and wil authenticate the api

**Comment by emyrsmorgan** [comment]
i Further narrowed it down up to  Eddie Version 4.03-B4 it works fine it is
only the release version that has this problem

**Comment by emyrsmorgan** [comment]
er Eddie Version 4.03-B3 i ment b4 does not even load stand alone

**Comment by emyrsmorgan** [comment]
also changing my Weekly upkeep allocation from 100 to 99 them back to 100
in elite fixed it reporting a negative available balance

**Comment by Tkael** [comment]
Ok, I'm a little confused... Does version 4.0.3-b4 "work fine" or does it "not even load stand alone"?

I'd suggest that you should run neither EDDI nor VoiceAttack as an administrator. There are only a few edge cases where VoiceAttack running as an administrator is required and most people don't run into those edge cases.

EDDI uses two speech synthesizers... the System Speech Synthesizer and the Windows Media Speech Synthesizer. Different voices are associated with each synthesizer. EDDI hides some System Speech voices when there is a (newer) Media Speech equivalent. Do you have any voices installed on your system which do not appear in EDDI's list? 

From the log you sent, EDDI is actually hitting the issue with accessing the System Speech Synthesizer more than once. In one instance, the exception is caught before the entire application fails and in the other it is not. I can reinforce EDDI to guard against failures but your System Speech Synthesizer might still have an unresolved issue.

**Comment by emyrsmorgan** [comment]
B4 does not work b3 Does work
Running them in normal mode has no different effect

**Comment by Tkael** [comment]
Ok, I'm adding some additional protection in case EDDI fails to initialize the System Speech Synthesizer (I don't see any way to prevent the System Speech Synthesizer from failing on your system yet... it seems to fail as soon as EDDI touches it and before we've done anything to configure it).

Please open Powershell, then paste in and run the following to see if other applications on your system are having trouble with the same synthesizer?

```ps
Add-Type -AssemblyName System.speech
$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
$speak.Speak("test");
```
Do you hear "test"?
Does Powershell show an error? If yes, please share the results in a screenshot.

**Comment by emyrsmorgan** [comment]
test worked
Text to speech works with all other applications i have tried it only does
not work with Release.  btw Beta 4 finally loaded from Voice attack  worked
but it took like 3-4  minutes to actualy load . Sending you both logs stand
alone and started with Voice attack . Also when  loaded from voice attack
Beta 4 was working in text to spech tab  Until i tried to connect to
frontier(did not open the web site) then i saw the error in the logs.
Sending you both   log files

**Comment by Tkael** [comment]
Unfortunately, I don't receive attachments when you respond by email so I did not receive the new .log files.

**Comment by emyrsmorgan** [comment]
[ed.zip](https://github.com/EDCD/EDDI/files/12389079/ed.zip)

**Comment by Tkael** [comment]
Thanks. Version 4.0.3-b4 in standalone (eddiStand.log) seems to have the same problem as 4.0.3 (it can't access information connected to the System Speech Synthesizer while trying to inform you about an upgrade being available and fails). Have you perhaps at some point modified your registry to unlock additional voices?

In version 4.0.3-b4 in VoiceAttack (eddi.log) you seem to be running into a different issue (probably because it's not trying to speak during the upgrade process). The other speech synthesizer (the Windows Media synthesizer) is failing because Microsoft Catherine is being passed invalid IPA (specifically, "Thandco" is invalid). I'm not sure what "Thandco" is?

Have you tried swapping to a different voice to see if there's an issue with the current selected voice?

**Comment by Tkael** [comment]
Which voice is your currently selected voice?

**Comment by emyrsmorgan** [comment]
Cathrine is my current voice is is from the astralian englih back. Btw
Thandco is my Commanders name

**Comment by Tkael** [comment]
If the `Name (spoken)` field in the `Commander Details` tab contains `Thandco`, please remove that text as it is invalid IPA.
Please try removing and re-adding the Australian voice pack with Microsoft Catherine (reinstalling the voice pack) then re-testing?
Please try using another voice (like Microsoft David or Microsoft James). Do these fail in the same way?
