### ISSUE TITLE
Request navigation via "Road To Riches" route and other options

### ISSUE THREAD

**Issue by Ricochetv1** [EDCD/EDDI#2577]
## What happens now
The current navigation finder only uses the basic pulsar route plotter with no options.

## What I'd like to happen 
Offer options like Spansh does, with a deviation percentage to find better routes, or worse, if you like. Also, to offer a Road To Riches kind of route that will route you through systems with high value planets.

## How it can happen
If you aren't interfaced with the Spansh API, consider it. Or, run your own algorithm, if you like. I don't know what you're currently using to plot routes. Another option would be to make it so the csv export from Spansh can be imported and used. In fact, what would be REALLY helpful is if it could use a csv route export from Spansh's Road To Riches plotter, and plot the pulsar routes point-to-point.

## EDDI Version
4.0.3

**Comment by Tkael** [comment]
Closing and adding the suggestion to #2555, which overlaps with this request.
