### ISSUE TITLE
Customising the Message Received script wiki is inaccurate

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#258]
The wiki page 'Customising the Message Received script' is not accurate with the description of the event.channel variable.

Where the wiki says:
> event.channel describes _the recipient_ and is one of:
> wing
> local
> voicechat
> friend
> player
> npc

This is not necessarily the recipient.  The following journal entry is for a message received by me from a police vessel after scanning me:
`{ "timestamp":"2017-11-26T20:05:35Z", "event":"ReceiveText", "From":"$ShipName_Police_Federation;", "From_Localised":"Federal Security Service", "Message":"$Police_ThankYouPassedStopAndSearch03;", "Message_Localised":"All clear. Carry on, pilot.", "Channel":"npc" }`

The channel says 'NPC', so in this case it would seem to describe the message sender, not the recipient.

Maybe the wiki description should just say 
> event.channel describes _the communication channel_ the message was sent over

Or something like that?

**Comment by Tkael** [comment]
Agreed. The channel does not describe the recipient.

**Comment by Tkael** [comment]
Wiki updated. Thanks!
