### ISSUE TITLE
Nav Monitor Ship Route reports the wrong next jump distance

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#2591]
## What's Wrong
When you create a ship route in the Nav monitor, after each jump it wrongly reports the next jump distance as being that for item 1 in the list

### Expected
Please see this route
![image](https://github.com/EDCD/EDDI/assets/227024/ab9224af-7cd6-470d-8f01-9f89b67297c1)
I expected the voice report on each jump to show the next jump distance as per the table.

### Observed
The voice report on each jump always says that the next jump will be 20.4 Ly away, the value from item 1 of the table. Excerpts from speechresponder.out:
```
Pulsar route calculated. Freebie will reach Eol Prou AK-A e137 in 7 jumps. Total route distance is 457.0 lightyears. First destination is Eol Prou P X dash T d 3 dash 1133, 20 lightyears away.  Clipboard set.
Guidance enabled.
Course locked in.
Next system is Eol Prou R S dash T d 3 dash 287, 20.4 lightyears away.  Clipboard set.
Next destination is Eol Prou K R dash W e 1 dash 1060, 20.4 lightyears away.  Clipboard set.
Next waypoint is Eol Prou P H dash V d 2 dash 832, 20.4 lightyears away.  Clipboard set.
```

### Steps to reproduce
1. Plot any pulsar route using the Nav monitor.
2. Fly it and observe the above issue.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.3
  * VoiceAttack Version: none
* Localization en
  * EDDI's language: en
  * Voice: IVONA 2 Amy

**Comment by Darkcyde13** [comment]
My additional comment on [#2586](https://github.com/EDCD/EDDI/issues/2586) mentions this too.  Mine was for missions routes.
