### ISSUE TITLE
unknownmineral / unknownrefinedmineral

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#2594]
## What's Wrong (please be as specific as possible)
Hello everyone,
I often see the following 4 lines in the eddi.log:

2024-02-08T17:29:08 [Info] CommodityDefinition:CommodityDefinitionFromEliteID Unrecognized Commodity Definition EliteID 129022408
2024-02-08T17:29:08 [Info] CommodityDefinition:CommodityDefinitionFromEliteID Unrecognized Commodity Definition EliteID 129022409
2024-02-08T17:29:08 [Info] MarketInfoItem:ToCommodityMarketQuote Commodity definition error: unknownmineral
2024-02-08T17:29:08 [Info] MarketInfoItem:ToCommodityMarketQuote Commodity definition error: unknownrefinedmineral

### Expected
[Describe what you expected to happen]

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.4.0.3
  * VoiceAttack Version: [if applicable]  ---
* Localization [if applicable]
  * EDDI's language [or the operating system language if EDDI's language setting is "Automatic"] : German
  * Voice: [Name and language]

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"] [eddi.log](https://github.com/EDCD/EDDI/files/14212754/eddi.log)

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

[Journal.2024-02-08T170654.01.log](https://github.com/EDCD/EDDI/files/14212756/Journal.2024-02-08T170654.01.log)

**Comment by Darkcyde13** [comment]
This looks to me like there are a couple of commodities in the market of that station that EDDI doesn't recognise.  The error in the EDDI log corresponds with a market update
`{ "timestamp":"2024-02-08T17:29:08Z", "event":"Market", "MarketID":128091896, "StationName":"Putzi OPK's Heaven", "StationType":"Coriolis", "StarSystem":"Bohmshohm" }`

My guess would be one of the Titan samples maybe?  Or possibly one of the new materials from a spire site?  Have you been doing any Thargoid activities, collecting Thargoid items?

**Comment by nepomuk16321** [comment]
Yes, I think you're right. And no, I have nothing to do with the Thargoids.
I just want to point out to T'Kael that there are apparently new goods that are not recognised by EDDI. ;-)

**Comment by Darkcyde13** [comment]
I've quickly hopped over to that station, and tried to see what happens.  I too get the same, so I searched through the EDDI log for a market update, and found these two:
`{"id":129022408,"Name":"$unknownmineral_name;","Name_Localised":"Impure Spire Mineral","Category":"$MARKET_category_salvage;","Category_Localised":"Salvage","MeanPrice":31986,"Consumer":false,"Producer":false,"Rare":false},{"id":129022409,"Name":"$unknownrefinedmineral_name;","Name_Localised":"Semi-Refined Spire Mineral","Category":"$MARKET_category_salvage;","Category_Localised":"Salvage","MeanPrice":158421,"Consumer":false,"Producer":false,"Rare":false};`

So it seems they are materials from the spire sites, and I think that explains why EDDI doesn't know about them.  I think they came out after the last EDDI update.

Still, the above should make it easy for the team to add these in now. :)

**Comment by Tkael** [comment]
Correct, these are newer spire site commodities that were added after EDDI's last release.
Both are already coded and will be supported in the next release. :-) https://github.com/EDCD/EDDI/blob/8641d1049d1f28ad33ccb062fc896592aa736d67/DataDefinitions/CommodityDefinition.cs#L443-L444

**Comment by nepomuk16321** [comment]
Thanks !
