### ISSUE TITLE
The variable "{TXT:Environment}" returns an incorrect value in VoiceAttack.

### ISSUE THREAD

**Issue by ZakolkaTV** [EDCD/EDDI#2597]
## What's Wrong
After the pilot is intercepted by Thargoid in hyperspace (during the jump), the variable "{TXT:Environment}" returns an incorrect value in VoiceAttack.

### Expected
After the pilot is intercepted by Thargoid in hyperspace, the {TXT:Environment} variable should take the value "Normal space".

### Observed
After the pilot is intercepted by Thargoid in hyperspace, the {TXT:Environment} variable takes the value "Supercruise", but should return the value "Normal space". At the same time, I noticed that the variable {BOOL:Status supercruise} takes the correct value - "false".

A screenshot with the values of the variables after the interception:
![Скриншот 13-02-2024 175023](https://github.com/EDCD/EDDI/assets/86809192/2ecc16b0-6902-404e-a2fb-c741e761c10a)

### Steps to reproduce
1. Make a jump into the system under the control of Thargoids;
2. Follow step 1 until an interception occurs;
3. After the interception, check the value of the {TXT:Environment} variable.

### Configuration
* Version
  * EDDI Version: 4.0.3
  * VoiceAttack Version: 1.12

**Comment by Tkael** [comment]
I'm not sure the precise timing is clear in this report. Are we saying that the variable is incorrect after the hyperdiction has begun and prior to it's completion (while you are still in witch space and do not yet have full control of your ship) or that the variable is incorrect after the hyperdiction has been completed, the ship has been returned to normal space, and the commander once again has full control of their ship?

Is the `environment` variable value also incorrect in the Speech Responder at that time?
Would it be possible to provide a copy of your player journal from when this took place? The file will be located at `[your Saved Games folder]/Frontier Developments/Elite Dangerous/` and if you can provide any information about where you were jumping from/to or what you were doing before/after then that would help me locate the correct lines in the journal as well.

**Comment by ZakolkaTV** [comment]
@Tkael 
During a hyperjump, the variable shows the correct value "Witch space", even if the jump is intercepted by the targoid.
But after the interception, when we find ourselves in normal space, the variable "Environment" takes the wrong value - "Supercruise". Unfortunately, I do not know what values this variable takes in the responder's speech, because I do not use it

I made a series of jumps: BD+77 84 - Cephei Sector DQ-Y b1 - HIP 8525 - (interception from a targoid) - Cephei Sector DQ-Y b1
To get away from the targoid, I made a jump: HIP 8525 - BD+77 84

Here is the log of my actions:
[Journal.2024-02-20T140614.01.log](https://github.com/EDCD/EDDI/files/14343600/Journal.2024-02-20T140614.01.log)

**Comment by Tkael** [comment]
Ok. EDDI was configured to always set the environment to "Supercruise" after a jump but hyperdictions are a special case that leaves the commander in  "Normal Space". I will add include handling for hyperdictions in the next release. Thank you for the report. o7
