### ISSUE TITLE
The variable "{TXT:Environment}" returns an incorrect value when starting the game.

### ISSUE THREAD

**Issue by ZakolkaTV** [EDCD/EDDI#2598]
## What's Wrong
The variable "{TXT:Environment}" returns an incorrect value when starting the game.

### Expected
When I start the game, I am at the station, the {TXT:Environment} variable should return the value "Docked".

### Observed
Before exiting the game, I dock to the station, the {TXT:Environment} variable returns the value "Docked" - this is correct. After restarting the game and "VoiceAttack" I am still at the station, but the variable {TXT:Environment} returns the value "Normal space" - this is not correct!

### Steps to reproduce
1. Dock to the station and make sure that the {TXT:Environment} variable = "Docked".
2. Close the game and close the "VoiceAttack".
3. Launch the game and "VoiceAttack".
4. Loading game.
5. Check the value of the {TXT:Environment} variable.

### Configuration
* Version
  * EDDI Version: 4.0.3
  * VoiceAttack Version: 1.12

### EDDI Logs
[Journal.2024-02-28T112553.01.log](https://github.com/EDCD/EDDI/files/14431257/Journal.2024-02-28T112553.01.log)

**Comment by Tkael** [comment]
EDDI  fast forwards through your last play session when it starts so that it can present up-to-date data but if you query EDDI while it's still going through that process then you might see some invalid data.

If you wait a minute then check again then is the variable still the same?

**Comment by ZakolkaTV** [comment]
@Tkael 
First, I run VA+EDDI.
Next, I start the game - {TXT:Environment} = "Docked".
After that, I click "Continue" and on the loading screen - {TXT:Environment} = "Docked".
When the game is fully loaded and I see myself in the ship at the station - {TXT:Environment} = "Normal space".

![image](https://github.com/EDCD/EDDI/assets/86809192/ceedba20-1a8a-4a37-8dad-39724e490147)

**Comment by Tkael** [comment]
Resolved by d3d3d4a906413ce3518400767be5c03ea28c1674.
