### ISSUE TITLE
error on test script "Module transfer" and "Ship transfer initiated"

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#260]
## Steps to reproduce

Every time I click on test button for "Module transfer" or "Ship transfer initiated"

Eddi say the speech and after crash

for Module transfer ==> _You have transferred a 0-E Frame Shift Wake Scanner for a cost of 322 credits.  Expected arrival in: 2 minutes._

for Ship transfer initiated ==> _your Adder being transported from Eranin  Expected arrival in: 2 minutes._

edit: copy of log

> 
> 2017-11-29T06:23:00 SpeechResponder:Reload [D] Reloaded Speech responder 1.0.0 
> 2017-11-29T06:23:03 SpeechResponder:Reload [D] Reloaded Speech responder 1.0.0 
> 2017-11-29T06:23:07 GalnetMonitor:monitor [D] No in-game activity detected, skipping galnet feed update 
> 2017-11-29T06:23:08 SpeechResponder:Reload [D] Reloaded Speech responder 1.0.0 
> 2017-11-29T06:23:26 SpeechResponder:.ctor [I] Initialised Speech responder 1.0.0 
> 2017-11-29T06:23:26 Deserializtion:DeserializeData [D] Deserializing { "timestamp":"2017-09-20T07:05:41Z", "event":"FetchRemoteModule", "StorageSlot":25, "StoredItem":"$hpt_cloudscanner_size0_class1_name;", "StoredItem_Localised":"Wake Scanner", "ServerId":128662525, "TransferCost":322, "TransferTime":120, "Ship":"diamondbackxl", "ShipID":38 } 
> 2017-11-29T06:23:26 SpeechResponder:createVariables [D] State is {} 
> 2017-11-29T06:23:26 ScriptResolver:resolve [D] Resolving script Module transfer 
> 2017-11-29T06:23:26 ScriptResolver:resolve [D] Found script 
> 2017-11-29T06:23:26 ScriptResolver:resolveScript [D] Turned script You have transferred a {event.module.class}-{event.module.grade}
> 
> {if event.module.mount:
>     {for index, value in event.module.mount: {set mount to value}}
>     {if mount = 0:
>         fixed
>     |elif mount = 1:
>         giimballed
>     |elif mount = 2:
>         turreted
>     }
> }
> 
> {event.module.name} 
> 
> {if event.transfercost: for a cost of {event.transfercost} credits.}
> 
> {set t_remaining to event.transfertime}
> 
> {if t_remaining:
> 
>    {Pause(1000)}
>    Expected arrival in:
> 
>    {if t_remaining > (60*60*24):
>       {set t_days to floor(t_remaining/(60*60*24))}
>       {t_days} days,
>       {set t_remaining to t_remaining-(t_days*(60*60*24))}
>    }
> 
>    {if t_remaining > 3600:
>       {set t_hours to floor(t_remaining/3600)}
>       {t_hours} hours,
>       {set t_remaining to t_remaining-(t_hours*(60*60))}
>    }
> 
>    {if t_remaining > 60:
>       {if t_days || t_hours: and}
>       {set t_minutes to round(t_remaining/(60),0)}
>       {t_minutes} minutes.
>    }
> } in to speech You have transferred a 0-E Frame Shift Wake Scanner for a cost of 322 credits. <break time="1000ms" /> Expected arrival in: 2 minutes. 
> 2017-11-29T06:23:26 SpeechService:speak [D] Post-selection 
> 2017-11-29T06:23:26 SpeechService:speak [D] {"standardVoice":null,"volume":100,"effectsLevel":32,"distortOnDamage":true,"rate":2,"disablessml":false,"enableicao":false} 
> 2017-11-29T06:23:26 SpeechService:speak [D] Obtaining best guess culture 
> 2017-11-29T06:23:26 SpeechService:speak [D] Best guess culture is  xml:lang="fr-FR" 
> 2017-11-29T06:23:26 SpeechService:speak [D] Feeding SSML to synthesizer: <?xml version="1.0" encoding="UTF-8"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="fr-FR">You have transferred a 0-E Frame Shift Wake Scanner for a cost of 322 credits. <break time="1000ms" /> Expected arrival in: 2 minutes.</speak> 
> 2017-11-29T06:23:26 SpeechService:Speak [D] Stream length is 388002 
> 2017-11-29T06:23:26 SpeechService:Speak [D] Seeking back to the beginning of the stream 
> 2017-11-29T06:23:26 SpeechService:Speak [D] Adding effects 
> 2017-11-29T06:23:26 SpeechService:addEffectsToSource [D] Effects level is 32, chorus level is 19, reverb level is 25, echo delay is 200 
> 2017-11-29T06:23:26 SpeechService:addEffectsToSource [D] Extending duration by 5000ms 
> 2017-11-29T06:23:26 SpeechService:addEffectsToSource [D] Adding chorus 
> 2017-11-29T06:23:26 SpeechService:addEffectsToSource [D] Adding reverb 
> 2017-11-29T06:23:26 SpeechService:addEffectsToSource [D] Adding echo 
> 2017-11-29T06:23:26 SpeechService:play [D] Starting speech 
> 2017-11-29T06:23:26 SpeechService:StartSpeech [D] Checking to see if we can start speech 
> 2017-11-29T06:23:27 SpeechService:StartSpeech [D] We can - setting active speech 
> 2017-11-29T06:23:27 SpeechService:StartSpeech [D] Playing sound buffer 
> 2017-11-29T06:23:27 SpeechService:play [D] Waiting for speech - 00:00:09.2970000 
> 2017-11-29T06:23:36 SpeechService:play [D] Finished waiting for speech 
> 2017-11-29T06:23:36 SpeechService:StopCurrentSpeech [D] Stopping active speech 
> 2017-11-29T06:23:36 SpeechService:StopCurrentSpeech [D] Disposing of active speech 
> 2017-11-29T06:23:36 SpeechService:StopCurrentSpeech [D] Stopped current speech

**Comment by Tkael** [comment]
If you are getting a crash, please provide a copy of your log for review? 
It should be completing after two minutes by announcing the arrival of your ship or module (and does so successfully on my computer)

**Comment by Tkael** [comment]
I've made some revisions to these events on PR #264. Please test the next version when it is released and let us know if the issue persists.
Which version of EDDI are you using? Are you using one of the official builds or are you using something off of the translation branch?

**Comment by StivlWrith** [comment]
it's on the 2.4.6-b1 on the guenuine version.
I try also to make a built of the 2.4.6-b2 and it is the same

**Comment by Tkael** [comment]
My most recent changes are not yet incorporated into 2.4.6-b2.

**Comment by StivlWrith** [comment]
I just think about something. One time I had something like that, and after some days (or weeks), i realised that i forget to put the advanced surface scanner in my ship (don't remember if i had none or just basic surface scaner). In the result of scan, there was lot of differences. 
If not that, what you can do is to take a look in the game log if your scan log have all the needed informations like
`{ "timestamp":"2017-11-27T13:01:31Z", "event":"Scan", "BodyName":"NGC 4463 Sector PI-P b36-5 B 4", "DistanceFromArrivalLS":45999.742188, "TidalLock":false, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.021067, "Radius":2293842.500000, "SurfaceGravity":1.595805, "SurfaceTemperature":37.459572, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":22.409916 }, { "Name":"carbon", "Percent":18.844418 }, { "Name":"iron", "Percent":15.498662 }, { "Name":"phosphorus", "Percent":12.064520 }, { "Name":"nickel", "Percent":11.722539 }, { "Name":"chromium", "Percent":6.970263 }, { "Name":"manganese", "Percent":6.400789 }, { "Name":"germanium", "Percent":3.273058 }, { "Name":"tin", "Percent":1.007667 }, { "Name":"ruthenium", "Percent":0.957141 }, { "Name":"tungsten", "Percent":0.851032 } ], "SemiMajorAxis":315986444288.000000, "Eccentricity":0.000067, "OrbitalInclination":0.051758, "Periapsis":279.576050, "OrbitalPeriod":231043632.000000, "RotationPeriod":146188.468750, "AxialTilt":0.500253 }
`

You can find (it's like that for me) in 

> C:\Users\YourAccount\Saved Games\Frontier Developments\Elite Dangerous

**Comment by StivlWrith** [comment]
I try the hotfix, saddly the result is the same (in game or out of the game) after click on 'test' button

LOG:
```
2017-11-29T19:40:48 SpeechResponder:.ctor [I] Initialised Speech responder 1.0.0 
2017-11-29T19:40:48 Deserializtion:DeserializeData [D] Deserializing { "timestamp":"2017-09-20T07:05:41Z", "event":"FetchRemoteModule", "StorageSlot":25, "StoredItem":"$hpt_cloudscanner_size0_class1_name;", "StoredItem_Localised":"Wake Scanner", "ServerId":128662525, "TransferCost":322, "TransferTime":120, "Ship":"diamondbackxl", "ShipID":38 } 
2017-11-29T19:40:48 SpeechResponder:createVariables [D] State is {} 
2017-11-29T19:40:48 ScriptResolver:resolve [D] Resolving script Module transfer 
2017-11-29T19:40:48 ScriptResolver:resolve [D] Found script 
2017-11-29T19:40:48 ScriptResolver:resolveScript [D] Turned script You have transferred a {event.module.class}-{event.module.grade}

{if event.module.mount:
    {for index, value in event.module.mount: {set mount to value}}
    {if mount = 0:
        fixed
    |elif mount = 1:
        giimballed
    |elif mount = 2:
        turreted
    }
}

{event.module.name} 

{if event.transfercost: for a cost of {event.transfercost} credits.}

{set t_remaining to event.transfertime}

{if t_remaining:

   {Pause(1000)}
   Expected arrival in:

   {if t_remaining > (60*60*24):
      {set t_days to floor(t_remaining/(60*60*24))}
      {t_days} days,
      {set t_remaining to t_remaining-(t_days*(60*60*24))}
   }

   {if t_remaining > 3600:
      {set t_hours to floor(t_remaining/3600)}
      {t_hours} hours,
      {set t_remaining to t_remaining-(t_hours*(60*60))}
   }

   {if t_remaining > 60:
      {if t_days || t_hours: and}
      {set t_minutes to round(t_remaining/(60),0)}
      {t_minutes} minutes.
   }
} in to speech You have transferred a 0-E Frame Shift Wake Scanner for a cost of 322 credits. <break time="1000ms" /> Expected arrival in: 2 minutes. 
2017-11-29T19:40:48 SpeechService:speak [D] Post-selection 
2017-11-29T19:40:48 SpeechService:speak [D] {"standardVoice":null,"volume":100,"effectsLevel":32,"distortOnDamage":true,"rate":2,"disablessml":false,"enableicao":false} 
2017-11-29T19:40:48 SpeechService:speak [D] Obtaining best guess culture 
2017-11-29T19:40:48 SpeechService:speak [D] Best guess culture is  xml:lang="fr-FR" 
2017-11-29T19:40:48 SpeechService:speak [D] Feeding SSML to synthesizer: <?xml version="1.0" encoding="UTF-8"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="fr-FR">You have transferred a 0-E Frame Shift Wake Scanner for a cost of 322 credits. <break time="1000ms" /> Expected arrival in: 2 minutes.</speak> 
2017-11-29T19:40:48 SpeechService:Speak [D] Stream length is 388002 
2017-11-29T19:40:48 SpeechService:Speak [D] Seeking back to the beginning of the stream 
2017-11-29T19:40:48 SpeechService:Speak [D] Adding effects 
2017-11-29T19:40:48 SpeechService:addEffectsToSource [D] Effects level is 32, chorus level is 19, reverb level is 25, echo delay is 200 
2017-11-29T19:40:48 SpeechService:addEffectsToSource [D] Extending duration by 5000ms 
2017-11-29T19:40:48 SpeechService:addEffectsToSource [D] Adding chorus 
2017-11-29T19:40:48 SpeechService:addEffectsToSource [D] Adding reverb 
2017-11-29T19:40:48 SpeechService:addEffectsToSource [D] Adding echo 
2017-11-29T19:40:48 SpeechService:play [D] Starting speech 
2017-11-29T19:40:48 SpeechService:StartSpeech [D] Checking to see if we can start speech 
2017-11-29T19:40:48 SpeechService:StartSpeech [D] We can - setting active speech 
2017-11-29T19:40:48 SpeechService:StartSpeech [D] Playing sound buffer 
2017-11-29T19:40:48 SpeechService:play [D] Waiting for speech - 00:00:09.2970000 

```

**Comment by Tkael** [comment]
A verbose log might tell us more about exactly what is happening right before the crash.

**Comment by StivlWrith** [comment]
The problem is that it is already the verbose log.

I think that the problem is that when I make the test, I am not in game, or not in a station, just work on script and use test button to listen how is the speech

**Comment by Tkael** [comment]
It should work both in and out of game. But go ahead and test in-game to see if you get the same result.

**Comment by StivlWrith** [comment]
Sorry, i connot try to make a ship transfer actually in game, I'm at less at 40000Ly from any station.

I make one other try, like i have a Home System and Home Station already defined,  I change in JournalMonitor the lines 804 and 805 like this
```
     string arrivalStation = EDDI.Instance.HomeStation.name;
     string arrivalSystem = EDDI.Instance.HomeStarSystem.name;
```

rebuilt and make a test on _Ship transfer initiated_ script, and then, it work fine

The scrict _Module transfer_ that I don't change in JournalMonitor continue to not work.

So I make one other try in JournalMonitor / FetchRemoteModule
```
       Logging.Info("Just before");
       string arrivalSystem = EDDI.Instance.CurrentStarSystem.name;
       string arrivalStation = EDDI.Instance.CurrentStation.name;
       Logging.Info("Just after");
```

I rebuild, remove the verbose Log and test again _Module transfer_ 
I have the "Just before" in the log, and no "Just after", EDDI shut down.

**Comment by Tkael** [comment]
I think I can work with that. Expect an updated PR after I get home from work this evening. 😀

**Comment by Tkael** [comment]
The PR has been updated, please rebuild from the hotfix branch and test?

**Comment by StivlWrith** [comment]
It's work fine now, no more problem about that

**Comment by Tkael** [comment]
Great. Then I'll close this issue pending incorporation of PR #264.
