### ISSUE TITLE
EDDI stops speaking when hit by a Titan pulse

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2603]
### Expected
EDDI to speak as and when an event is triggered, after leaving a Titan instance.

### Observed
EDDI no longer voices triggered events.

### Steps to reproduce
1. Fly into a Titan instance.
2. Do whatever you need to do there.  I've targeted the Titan, repaired my modules, repaired my hull, etc.
3. Leave the instance/cloud by flying out.
4. Note that EDDI stops speaking for normal events like jumping to a new system.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: V4.0.3
  * VoiceAttack Version: v1.12
* Localization [if applicable]
  * EDDI's language: British English
  * Voice: Ivona Amy2

### Investigation Notes
I've been visiting Titan Leigong in order to get the ship kit, paint jobs, and decal, and I've noticed that once I've left the instance, EDDI stops speaking.  I'm pretty sure it was the same for Titan Taranis too, I was just learning how to tackle them then, so wasn't really sure when it was happening.

EDDI still processes the events as normal, because the speech is added to the speechresponder.out file as expected, it's just that EDDI no longer speaks them out loud.  I've tried clicking the test button on several scripts, and they all speak as expected.  So it seems to be only triggered events that are affected.

The EDDI log doesn't show anything out of the ordinary and seems to continue to function as expected.  I've not tried it with verbose logging yet though, so I may give that a go at some point.

To be honest, I'm still new to all this, and tend to get caught up in trying not to die, trying to fire off caustic sinks and the TG pulse neutraliser, and get some hits in on the Titan thermal core.  It's only once I've left the instance, or rather the Titan cloud, that I notice EDDI no longer speaking.

Leigong is being bugged at the moment, with the core stuck out (the hotfix didn't fix it), so I may just see about getting some decent logs to examine while I can't do much else to it.

### EDDI Logs
None yet.

### Player journals
None yet.

**Comment by Darkcyde13** [comment]
OK, so I've run my test using verbose logging.  I'm 95% sure EDDI stops speaking because I got hit with the Titan pulse on my way out of the cloud.  All speech was normal entering the cloud, and while I was in there.  On my way out, I let the pulse hit me to speed up my exit, and besides, you can't see the pulse coming from behind in order to time the pulse neutraliser anyway.

When I got hit with the pulse, I got a message in the speechresponder.out to say I have received:
"Massive Energy Surge Analytics Obtained. You have 6 units in your inventory."

However, this was not spoken aloud, so I'm pretty sure it's something to do with this, as it's the only out-of-the-ordinary thing that happened.  If it's not this, it must be something just before it, but I wouldn't know what.

Here's a verbose log of the entire play session:
[eddi.zip](https://github.com/EDCD/EDDI/files/14594760/eddi.zip)

Edit: ...and I guess it would also be helpful to have included the game Journal at the same time...
[Journal.2024-03-13T225421.01.log](https://github.com/EDCD/EDDI/files/14605094/Journal.2024-03-13T225421.01.log)

**Comment by Darkcyde13** [comment]
I've done a couple more runs on Leigong this morning, and EDDI stopped speaking at the same time for each of them.  So it's definitely something around getting hit with the Titan pulse on my way out.  I've not tried deliberately getting hit with it on my way in though.  If I remember, I'll try it the next time I play.

**Comment by Tkael** [comment]
If speech stops for about 15 seconds then this is the intended behavior when speech is interrupted by by a shutdown pulse. If speech does not resume then that would be a bug.

**Comment by Darkcyde13** [comment]
It does not resume.  I have to close down VA/EDDI.  And with the other problem I have of EDDI not starting up again as a plugin, I then have to reboot one or two times before it will load as a plugin again.

Edit: I can understand why a shutdown pulse would stop the in-game computer (of which EDDI is an extension), but a Titan pulse does not fully shut your ship down, it only pushed you back out of the Titan cloud and intermittently affects the ships systems for a few seconds (fewer than 15).  As such I would not expect EDDI to go silent for as long as 15 seconds.

**Comment by Tkael** [comment]
Fair. I didn't remember the exact behavior from getting hit by a Titan pulse (it's been a little while since I've been that close to a Titan). It sounds like I need to detect this special case for the shutdown event and handle it differently from a conventional shutdown.
