### ISSUE TITLE
Anti Xeno Military pilots in Titan Debris Fields

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2604]
There are new Anti Xeno Military pilots in the Titan debris fields (only Taranis at the moment), and EDDI does not seem to handle them correctly in the 'Ship targeted' event.

The Ship targeted script voices the `$Name_AX_Military;` as part of the name, so I think this just needs to be replaced before EDDI uses it.

Journal entries for Ship targeted:
```
{ "timestamp":"2024-03-31T00:53:55Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":1, "PilotName":"$Name_AX_Military; Gregory", "PilotRank":"Master" }
{ "timestamp":"2024-03-31T00:53:58Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":2, "PilotName":"$Name_AX_Military; Gregory", "PilotRank":"Master", "ShieldHealth":100.000000, "HullHealth":100.000000 }
{ "timestamp":"2024-03-31T00:54:00Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":3, "PilotName":"$Name_AX_Military; Gregory", "PilotRank":"Master", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Earls of Barati", "LegalStatus":"Lawless" }
{ "timestamp":"2024-03-31T00:54:01Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":3, "PilotName":"$Name_AX_Military; Gregory", "PilotRank":"Master", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Earls of Barati", "LegalStatus":"Lawless", "Subsystem":"$modularcargobaydoor_name;", "Subsystem_Localised":"Cargo Hatch", "SubsystemHealth":100.000000 }
```

I'd guess that these are similar to the existing AX Pilots, just with a pilot name appended to the end?

EDIT:  I thought it was happening in the Message received event too, but I had missed the output in speechresponder.out file, so I've removed my references to that.

**Comment by Tkael** [comment]
Normally there's a `PilotName_Localised` field that would contain a friendlier name (and EDDI would prefer that name if it were present). We've seen some cases where Frontier have skipped using this field. This looks like one of those cases. Thanks!

**Comment by Tkael** [comment]
Fixed for the next release. https://github.com/EDCD/EDDI/commit/518190495b6c6c995d66e70efe42a25e68b072ae
