### ISSUE TITLE
New Thargoid item

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2605]
The new Thargoid Titan Drive Component isn't properly recognised by EDDI, it's just spoken as "thargoidtitandrivecomponent" when collecting it, or when EDDI tells you what you can sell at a station.

```
{ "timestamp":"2024-03-31T00:04:01Z", "event":"CollectCargo", "Type":"ThargoidTitanDriveComponent", "Type_Localised":"Titan Drive Component", "Stolen":false }
```

I've also noticed that a Thargoid heart is spoken as "ThargoidHeart" with no space between the words.

Both are listed in the Cargo monitor in the same way.

**Comment by Tkael** [comment]
Thanks. I'd already added `ThargoidTitanDriveComponent` for the next release.
`ThargoidHeart` was already added but missing a localized name. Added for the next release.
