### ISSUE TITLE
No Sound From EDDI, need help.

### ISSUE THREAD

**Issue by Solrackx** [EDCD/EDDI#262]
No Sound From EDDI. 
In the tab text-to-speech I have selected a multitude of voices, none of them work. I have tried the voice test and it does not sound anything. I have reinstalled the application, I have tried the voice attack with EDDi, I have also tried removing the voice attack and it does not sound at all. Even so, the voice attack recognizes the commands, applies them, but no voice answers me. I have looked at the voice settings and I do not see any errors, I do not know what to do anymore.

**Comment by Tkael** [comment]
Are you getting sound from other apps? Are you using the default personality? What is the Volume setting on EDDI's Text-to-Speech tab set to?

**Comment by Solrackx** [comment]
Sinceramente, no sé que he hecho para arreglarlo, pero ya está solucionado. Ha sido después de tocar en toda la configuración de sonido. He activado una casilla llamada "sonido espacial" y después de activarla me ha funcionado, pero dudo que haya sido algo de eso. De todas maneras, he comprobado que al dar instrucciones a través del voice attack, antes de que me funcionara, el sonido de EDDi y el de los altavoces subía, pero no se escuchaba; podría ser alguna desconfiguración de windows.
Gracias por la rápida respuesta de verdad, =).

**Comment by Tkael** [comment]
Closing as resolved. :-)
