### ISSUE TITLE
VA Status fsd hyperdrive charging is 'Not set'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#2627]
### Expected
The VA variable `BOOL:Status fsd hyperdrive charging` to be set to true or false.

### Observed
The variable is always reported as 'Not set'.

### Steps to reproduce
1. Create an event command in VA called `((EDDI ship fsd))`
2. Add a write to log for `{BOOL:Status fsd hyperdrive charging}`
3. In game, initiate a jump to another system.
4. Observe the VA log reports 'Not set'.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.0.4
  * VoiceAttack Version: v1.14
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"]
  * Voice: [Name and language]

### Investigation Notes
I wanted to create a VA command that would stop EDDI talking if it was in the middle of a long speech when initiating a jump to another system.  I made a command that checked if `EDDI speaking` was true, and if `Status fsd hyperdrive charging` was true, but the command never worked.  On testing the values of each variable, I found that the hyperdrive one is always 'Not set'.

### EDDI Logs
N/A

### Player journals
N/A

**Comment by Tkael** [comment]
It's possible for the general `status` variable to have changed again before the VoiceAttack command resolves.
Why not use one of the variables that is tied to that event? <https://github.com/EDCD/EDDI/wiki/Ship-fsd-event>
For example, did you test `{BOOL:EDDI ship fsd hyperdrive charging}`?

**Comment by Darkcyde13** [comment]
Ahh, that hadn't crossed my mind.  I've just given it a go, and it seems to be working OK.  So thank you! 😃
