### ISSUE TITLE
EDDI + Voice Attack crashes by incomming EDDI events

### ISSUE THREAD

**Issue by Melbar-Kaasom** [EDCD/EDDI#2629]
## What's Wrong (please be as specific as possible)
Hello,
I use VA mainly with self-created profiles with events from EDDI.
Operating system Windows 11 64 Bit
Unfortunately, VA regularly crashes completely when different events occur.
Can I find out somewhere what triggers the crash or are there other attempts to fix it?

### Expected
[Describe what you expected to happen] 
touchdown-> just set a boolean to true
disembark /embark-> change to another Profile

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v4.1.0-a2
  * VoiceAttack Version: [if applicable] v1.14
* Localization [if applicable] C:\Program Files (x86)\VoiceAttack\Apps\EDDI\
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] German
  * Voice: [Name and language]  Ivona 2 Marlene OEM (German)

### Investigation Notes
[Any investigation you have done, tests using default scripts and personalities, regression tests against earlier versions, etc]

### EDDI Logs
[Any log files providing additional details about what happened. These are located at %APPDATA%/EDDI and have the extension ".log"]

### Player journals
[These are not required if EDDI Logs are verbose but may be helpful otherwise. They are located at [your Saved Games folder]/Frontier Developments/Elite Dangerous/. Please only provide excerpts or attach files from the play session where the issue occurred.]

**Comment by Tkael** [comment]
I need the .log files from `%APPDATA%/EDDI` to see what may be causing EDDI to crash?

**Comment by Melbar-Kaasom** [comment]
i Think  its not a Problem of EDDI,
by stand alone use there is no crash.
i Postet in VA Discord, and the Guys told me to ask here...
here the logs:
[eddi.log](https://github.com/user-attachments/files/16101556/eddi.log)
[eddi1.log](https://github.com/user-attachments/files/16101557/eddi1.log)

**Comment by Tkael** [comment]
The EDDI logs didn't capture any problem. 
I suggest reviewing the Windows Event Viewer to determine if the operating system recorded the error.
<https://www.softwareverify.com/blog/identifying-crashes-with-the-windows-event-log/>
You'd probably be looking for an "Application Error".

**Comment by Tkael** [comment]
Closing for lack of new information.
