### ISSUE TITLE
Body Vulcanism Report

### ISSUE THREAD

**Issue by johnny2trayz** [EDCD/EDDI#2632]
### Expected
Correct Body Vulcianism Report

### Observed
"There is a problem with the script "Body volcanism report" at line 37. expected expression, found \"

### Steps to reproduce
Scanning high metal content worlds

### Configuration
* Version: 18.07
  * EDDI Version:  4.0.4.
  * VoiceAttack Version: None
* Localization 
  * EDDI's language: English
  * Voice: IVONA 2 Nicole
### Investigation Notes
None

### EDDI Logs
https://pastebin.com/fpseS30V
### Player journals
https://pastebin.com/qzHaJa7S

**Comment by Tkael** [comment]
If the `Body volcanism report` is customized, have you tried comparing the customized script to the default and/or resetting the script back to the default?
![image](https://github.com/user-attachments/assets/6866bbb4-07a3-4971-a54a-b89ace73a471)

**Comment by johnny2trayz** [comment]
I have deleted all my personalities and have it set to default. Compare to default and reset to default are grey.

**Comment by johnny2trayz** [comment]
This issue seems to have resolved.
