### ISSUE TITLE
EDDI closes when using button to copy system name to clipboard in Galactic POI

### ISSUE THREAD

**Issue by Ricochetv1** [EDCD/EDDI#2652]
Whenever I try to use the button to copy the system name to the clipboard in Galactic POI of Navigation Monitor, EDDI closes. The system name does not make it into the clipboard when this happens. This also happens in other tabs in Navigation Monitor. EDDI is able to set the clipboard when using automated navigation guidance, so it is only the copy button that is doing this. If I click on the system name in the table and hit Ctrl-C, the system name does go into the clipboard, so that can be used as a workaround. However, there seems to be something wrong with the code in that Copy button on the right of the window.

**Comment by Tkael** [comment]
Hi there. Thank you for the report. I'm not seeing the same on my build and I haven't had any other reports of a similar issue. Perhaps there's an issue with your local machine that's causing this to fail? It might be a good idea for you to run some system diagnostics in case there's file corruption in your OS which is preventing this code from executing successfully. From a command prompt run `sfc /scannow`. If corruption is found but cannot be automatically repaired then run `dism /online /cleanup-image /scanhealth`.

If those system diagnostics do not resolve the problem then please submit a new ticket and provide the information that is requested by the `Bug report` template including
1) the version of EDDI you are running, 
2) whether you're running EDDI from VoiceAttack or standalone, and 
3) a copy of a .log file where this crash occurred (.log files are found in `%appdata%/EDDI`). 
Note: If the .log file doesn't end in an exception then it's possible that some external event killed EDDI. If so then you may find a log for that event in the Windows Event Viewer.

**Comment by Ricochetv1** [comment]
It's quitting because of an uncaught exception. Whereas the automatic guidance is using function setClipboard, it seems the copy button is not, and the error is not handled. Granted, the setClipboard function is receiving the same error as the Copy button, but it is caught and goes on with life. Also, it is somehow able to set the system name in the clipboard regardless of the error. I don't know why my system is throwing this error, but it seems to be erroneous. Maybe if you just set the copy button to either use the same function that the Guidance function is using, or catch the exception and ignore it, it will resolve the issue altogether.
Log files are attached.
[eddi.log](https://github.com/user-attachments/files/17264127/eddi.log)
[eddi3.log](https://github.com/user-attachments/files/17264128/eddi3.log)

**Comment by Tkael** [comment]
Thanks for the logs. I've added some code to harden the next release so that it will catch similar system exceptions. It might still be a good idea to run diagnostics on your system if you have not already done so.
