### ISSUE TITLE
Would like to know if it would be Possible to bring this tool to Linux!

### ISSUE THREAD

**Issue by tinyplayerss** [EDCD/EDDI#2662]
I Would really appreciate that EDDI Can be available on Linux as a Native flatpak also Elite Dangerous can run Really well on Linux and i just would like this App to become available over on Linux this app helped me Greatly on Windows.

**Comment by Tkael** [comment]
Duplicate of #1976. At this time there are no plans for a Linux version.
If we are able to migrate to a newer version of .NET then this might become more possible after that time.
