### ISSUE TITLE
Elite dangerous update

### ISSUE THREAD

**Issue by studiojurdan** [EDCD/EDDI#2663]
Hi, I stopped to play elite dangerous a wile but now i'm on it again and i can see that when i jump between syst, the update to inara and other (the only reason why I use eddi)  don't work again.
I have tried to reset, update, and all the thing i can, but nothing's works again.
Can you help us?

**Comment by Tkael** [comment]
I'm sorry but I don't have enough information to offer any help... why didn't you fill in the standard template for new issues?

Which version of EDDI are you using? Which version of Elite Dangerous are you using (if it is the Legacy Horizons version then Inara doesn't accept updates from that source)? Have you checked your Inara account and credentials?

Closing. Please generate a new issue using the template. o7

**Comment by studiojurdan** [comment]
hello and sorry,
my eddi is the last 4.04
Elite is odyssey and the last because it is impossible to play ather version (auto update) 
WHAT TEMPLATE ?????????????????
I had clic on  submit problem in the EDDI programm
It is not my fault if this clic don't go to the good place :
My inara key is on, and edsm too

**Comment by Tkael** [comment]
Hi there. First off, I have to apologize - I didn't realize that the "Report an Issue" button didn't direct you to the issue template (ref. https://github.com/EDCD/EDDI/issues/new?template=bug_report.md). That'll be fixed for the next release.

You could select to play the Legacy Horizons version of Elite Dangerous using the launcher but it sounds like you're using Odyssey so the game version is unlikely to be the problem. 

Please turn on verbose debugging, jump at least once, click the "Report an Issue" button again, navigate back to this ticket and share the `eddi_issue.zip` file dropped onto your desktop, and then turn verbose logging back off?

**Comment by studiojurdan** [comment]
Hello, it is working now, i have removed, reinstall, pushed again my inara key and ALSO ADD EDSM key (the only change than before) and it work perfectly. thanks a lot for thi beautyfull soft.

**Comment by studiojurdan** [comment]
Hello, it is working now, i have removed, reinstall, pushed again my inara key and ALSO ADD EDSM key (the only change than before) and it work perfectly. thanks a lot for thi beautyfull soft.
