### ISSUE TITLE
Misreading Star Age

### ISSUE THREAD

**Issue by gregmcdougall** [EDCD/EDDI#267]
## Steps to reproduce

Scan a main star - mis-reading the star age. 11,636 Million years announced as 11 thousand. 636.

**Comment by Tkael** [comment]
This behavior was changed by a recent update to harmonize server and journal sourced data. Please open EDDI, navigate to the 'Speech responder tab, locate the 'Star report' script, click 'Edit', then click 'Reset to default' to acquire the updated script.
