### ISSUE TITLE
Call to Fuel check from Jumped event typo.

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#268]
As mentioned in the Discord channel, the Jumped event has a small typo.  Not sure if this has been fixed yet,

The call to the 'Fuel check' script in the Jumped event still has both words capitalised, so 'Fuel Check', rather than only the first word as the actual script is named to match other script convention.  This means it will not work, and 'Fuel check' will never be called.

**Comment by Tkael** [comment]
Already fixed by https://github.com/EDCD/EDDI/commit/13f5f40d9820b8c8e339803839e717f0f7628869, fix will be present in the next release. All the same, thanks for the follow-through. :-)
