### ISSUE TITLE
script : "Crew member role changed"

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#277]
## Steps to reproduce

1. When I want edit this script it is write in Name: New script, description and script are empty.
 When i write anything  in the script window (like: Test) and click on Test script button or OK, EDDI gone OFF

When i gone on the eddi script and try 'test', there is nothing, and for 'view', the window is empty.
test on the last 2.4.6-b2 develop.

the script is really in eddi.json (line 338 to 346)

**Comment by Tkael** [comment]
Correction submitted, PR #279.
