### ISSUE TITLE
Data voucher redeemed speech incomplete

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#278]
## Steps to reproduce

1. Get some redeemable data vouchers, e.g. by scanning one of the INRA sites.
2. Sell the data. Journal entry follows:

```
{
  "timestamp": "2017-12-03T00:18:43Z",
  "event": "RedeemVoucher",
  "Type": "scannable",
  "Amount": 230903,
  "Faction": ""
}
```

## Expected
EDDI to say a complete sentence, such as:

> Data vouchers for Nearly 231 thousand credits redeemed.

## Observed
EDDI says an incomplete sentence:

> Data vouchers for Nearly 231 thousand credits redeemed by.

## Investigation
This is with EDDI 2.4.6-b1 shipping version.

**Comment by Tkael** [comment]
Complete pending PR approval.
