### ISSUE TITLE
Logging.Report() still sends data to http://api.eddp.co

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#284]
## EDDI version in which issue found
2.4.6-b2

## Steps to reproduce

See applicable code [here](https://github.com/EDCD/EDDI/blob/32e154164932387171a1e16fd4bdb9ebbc34dae3/Utilities/Logging.cs#L120). Messages are sent to http://api.eddp.co via POST.

## Expected
These POST messages should be accessible to EDDI developers so that new modules / commodities / etc. can be added to EDDI data definitions as they are introduced in-game.

## Observed
We do not have access to the location where these messages are currently sent.

## Investigation
Our current EDDP server (hosted by Github) [only allows static content](https://help.github.com/articles/what-is-github-pages/) - receiving POST messages is not supported. We may need to transition to a different server that supports PHP, or find a different way to transmit these messages?

**Comment by Tkael** [comment]
@Hoodathunk I'm interested in your thoughts on this issue?

**Comment by richardbuckle** [comment]
Ping. Thoughts welcomed.

My own take is we are doing just fine with the data we get by virtue of being part of EDCD, and we just delete this function and be rid of any associated compliance worries.

**Comment by Tkael** [comment]
The advantage I see (and the use that seems to be intended) is to alert us when's materials / ships / commodities etc. become available so that we can add them into EDDI's definitions. So to me this falls into the 'nice to have but not 100% necessary' category. If we want to drop it, we should also revise the places where it is currently used.

**Comment by Tkael** [comment]
Reducing reliance on internal definitions could also help mitigate the need for this.
