### ISSUE TITLE
EDDI ship monitor issue. unable to change ship spoken name.

### ISSUE THREAD

**Issue by Bladesmith24** [EDCD/EDDI#293]
## EDDI version in which issue found
[]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
i expecteded to be able to change my ship name in ship monitor.
## Observed
[describe what happened instead]
can not change name. when i click on spoken name it does nothing. i got it to work once back when i first installed EDDI. even then only let me add a spoken name to one ship and then nothing. was not much of an issue but since becoming obssessed with elite dangerous it is now starting to be an issue. please help. 
## Investigation
[any investigation you have done, regression tests against earlier versions, etc]
tried resetting, reobtaining api log, uninstalled and reinstalled. still nothing. please help.

**Comment by Tkael** [comment]
If you set a phonetic / spoken name for your ship, it is not spoken correctly via the 'Hear it' button or scripts like `{ShipName()} stands ready`.

This behavior appears to be voice dependent. With Microsoft Hazel, the name set by Name (spoken) is spoken correctly. With Ivona Amy, the incorrect name is used.

**Comment by rodan123** [comment]
On a related note; It would be helpful if someone provided a link in the documentation to a website that could do the IPA transcription. I had a ship name that I wanted to have sounded out phonetically and tried several IPA transcription websites. I found they all inserted characters that EDDI didn't like. Took much trial and error to find a combination of characters that would work. It would be nice to have a website that would take input and be able to cut and paste the IPA translation directly into EDDI.  If you are already using such a website, please document it.

**Comment by Tkael** [comment]
@rodan123 Please do not sidetrack this issue... I've removed your comment here and opened issue #296 instead.

**Comment by Tkael** [comment]
This issue seems to come down to the `speak version="1.0"` tag in the above SSML. 
Ivona is [compliant to SSML version 1.1](http://developer.ivona.com/en/ttsresources/ssml/ssml.html#), and to default to 1.1 when this attribute is undefined. 

It does not seem to fully support IPA when version 1.0 is specified. With another application that was bundled with my copy of Ivona Amy (MiniSpeech): 
- IPA is parsed correctly when the version is set to "1.1", an empty string, or removed entirely. 
- IPA is not parsed correctly when the version is set to "1.0"

The Microsoft Speech Synthesis engine used by EDDI [supports version 1.0](https://msdn.microsoft.com/en-us/library/jj127861.aspx) and does not support version 1.1. Consequently, EDDI throws exceptions and fails to parse IPA correctly whenever the version is set to "1.1", an empty string, or removed entirely. 

It may not be possible to resolve this incompatibility without abandoning the Microsoft Speech Synthesis engine (and that's not something we can do lightly).

**Comment by Tkael** [comment]
@Bladesmith24 Can you confirm that I'm on the right track? Which voice are you using?

**Comment by Bladesmith24** [comment]
EDDI version 2.4.6-b1

**Comment by Tkael** [comment]
What is the name of the voice that you are using?

**Comment by Bladesmith24** [comment]
microsoft zira

**Comment by Bladesmith24** [comment]
active personality EDDI speech responder
text to speech microsoft Zira

**Comment by Tkael** [comment]
Hmm. Those work for me. Doe the example IPA `praɪdɒvˈakɜːnɑ` work for you?

**Comment by Bladesmith24** [comment]
i have ipa disabled. on EDDI main screen. 
i can not change anything on the ship monitor screen accept for enable plugin and change ship role. that is it

**Comment by Tkael** [comment]
Do you mean that you have Phonetic speech disabled? That would disable support for IPA.
If you navigate to the `Text-to-Speech` tab and uncheck the box `Disable phonetic speech`, does IPA work for you then?

**Comment by Bladesmith24** [comment]
correction can change spoken name on only one ship. but when i click test all i hear is .....stands ready.
no ship name. yet my first ship i changed the name not spoken name and it says the name when i click test.
that is all i can do in ship monitor.   spoken names only say stands ready does not even try to say spoken name just stands ready,

**Comment by Bladesmith24** [comment]
moment

**Comment by Bladesmith24** [comment]
phonetic speech is enabled sorry

**Comment by Tkael** [comment]
have you named the ship in Elite Dangerous, or are you trying to add a spoken name while the name is empty?

**Comment by Bladesmith24** [comment]
while empty did not know you can change name in game.

**Comment by Tkael** [comment]
When in station, you should be able to see an option in the UI called 'Livery'. Inside of the 'Livery' section, you can assign a name for your ship.

**Comment by Bladesmith24** [comment]
moment game partially loaded

**Comment by Bladesmith24** [comment]
think i got it thank you.

**Comment by Tkael** [comment]
Ok. Closing this issue.
