### ISSUE TITLE
Link to compatible IPA translation website

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#296]
From @Rodan123:
`It would be helpful if someone provided a link in the documentation to a website that could do the IPA transcription. I had a ship name that I wanted to have sounded out phonetically and tried several IPA transcription websites. I found they all inserted characters that EDDI didn't like. Took much trial and error to find a combination of characters that would work. It would be nice to have a website that would take input and be able to cut and paste the IPA translation directly into EDDI. If you are already using such a website, please document it.`

**Comment by Tkael** [comment]
@rodan123 I agree that a link would be helpful, but I can't say that I've found a single website that I feel is well suited for this purpose. Suggestions welcome!

**Comment by rodan123** [comment]
Sorry didn't mean to derail issue #293. This is the website I had used; [https://tophonetics.com/]( https://tophonetics.com/) 
Liked it because it has both American and British English dialects and also has audio playback so you can fine tune the transcription. It supports a number of other languages. (tabs on top)

**Comment by Tkael** [comment]
[This](http://www.internationalphoneticalphabet.org/english-to-ipa-translator/) looks promising. Unfortunately, the system is down at the moment.

**Comment by StivlWrith** [comment]
Personnaly i use  [(link for english page)](https://easypronunciation.com/en/english-phonetic-transcription-converter)
There is lots of options.
The only problem is that there is a limit of the number of transcription you can make in a day.

**Comment by Tkael** [comment]
All three of these are valid sources. We should also add a disclaimer noting that if IPA isn't working, the user should try a different voice. Voices are not all equally compliant to the standard ( see #296 ).
