### ISSUE TITLE
No speech after a belt scan

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#301]
Yes, I am one of the crazy who make scan of belts, and there is no speech for that. 
Is it possible to have one?

**Comment by Tkael** [comment]
Here is a scan event from a belt scan: 
```{ "timestamp":"2017-08-28T01:06:03Z", "event":"Scan", "BodyName":"LFT 926 B A Belt Cluster 2", "DistanceFromArrivalLS":352.792969 }```
As you can see, there is very little information available here. What kind of information would you like to hear when a belt scan completes?

**Comment by StivlWrith** [comment]
I think it is just a question of point of view. In mine, I like to have a vocal message to confirm i finish the scan of the belt cluster, and also, i have really no interest in the music event, but i will not remove in case it could have interrest for someone

**Comment by richardbuckle** [comment]
Waste of time IMHO.

**Comment by StivlWrith** [comment]
It is normal for everybody to have his own point of view. The thing I don't understand, is why to add the lines of code in SpeechResponder.cs:
```
           if (theEvent is BeltScannedEvent)
                {
                    // We ignore belt clusters
                    return;
                }
```

It simply block the possibility for those who don't think in the same way to have their speech.
I time of typing text for programming, to not write that and add in eddi.json:

```
    "Belt scanned": {
      "enabled": true,
      "priority": 3,
      "responder": true,
      "script": "{_ Nothing of interrest here}",
      "default": true,
      "name": "Belt scanned",
      "description": "Triggered when you complete a scan of a belt"
    },
```

surely take the same amount of time, and don't block those who have interrest on that.

The _Nothing of interrest here_ is present is other script, so it is what i really don't understand

**Comment by richardbuckle** [comment]
Beginning programmers are good at adding code.
Experienced programmers have learned to get good at reducing the amount of code.
Really experienced programmers have learned when not to write code in the first place.

Closing.
