### ISSUE TITLE
Add support for Elite Galaxy Online?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#302]
Allow users to submit data to Elite Galaxy Online?
For record breaking finds, alert users that their find has broken a record?
[API manual here](http://www.elitegalaxyonline.com/wp-content/uploads/2017/05/Elite-Galaxy-Online-API-Documentation-v2.1.pdf). Section 4 in particular appears to be relevant.

**Comment by Tkael** [comment]
There is potentially a lot of redundancy here with EDSM. Thoughts?

**Comment by StivlWrith** [comment]
It could looks, but E.G.O have lots of search tools that don't exist in EDSM (else if not enough search tools).
Or perhabs i don't know how to use EDSM.
I think they are more complementary than competitors

**Comment by richardbuckle** [comment]
Shouldn't the paradigm be that we submit once to EDDN and other services such as EGO pick it up. I mean, that's what EDDN is *for*.

**Comment by Tkael** [comment]
EDSM also doesn't work that way. Both sites require users to have an account. EDDI uploads applicable events to EDSM, but only if users have enabled the EDSM plugin and entered their EDSM details.

There is some merit to the idea of just using EDDN to track everyone, but accounts also make sense in a lot of ways for these sorts of sites. 
1. They act as a filter, so that only those who wish to be tracked are tracked (opt in, rather than making it impossible to opt out). 
2. They provide some accountability for the information submitted from each user. 
3. They allow users on those sites to interact and add additional detail to their discoveries (like screenshots and descriptions) that is not present in the journal. 
4. Etc.

**Comment by richardbuckle** [comment]
Fair points. I guess it is after all EDDI's _raison d'être_ to distribute data to a variety of responders as the user chooses.

**Comment by Tkael** [comment]
EGO has been down for quite some time. It's possible that it's no longer being maintained. Consequently, I'm closing this issue for the time being.
