### ISSUE TITLE
Auto-generate docs for functions added to Cottle

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#303]
These are added in `EDDI\SpeechResponder\ScriptResolver.cs ScriptResolver.buildStore()`

Use similar tech as with the Events to emit wiki documentation from test fixtures.

Index page already manually created at https://github.com/EDCD/EDDI/wiki/Functions, ready for replacement by an auto-generated page.

**Comment by richardbuckle** [comment]
Also reconsider whether a ton of

```
store["blah"] = new NativeFunction((values) =>
            {...]
```
is the best way to go.

At first sight, this use of anonymous functions, while fashionable, impedes discoverability for maintenance programmers.

**Comment by Tkael** [comment]
Help.md is already an attempt to document many of these functions. We could embed the descriptions as strings located with the ScriptResolver functions, so that auto building those wiki pages could take advantage of the information we already have present there, in much the same way as events are handled currently.

Help.md would then become out of date. We could redirect the button to open appropriate section of the wiki instead.

**Comment by Tkael** [comment]
Is there a better way to store these functions? This is the method described by Cottle's documentation.
See http://r3c.github.io/cottle/#custom_dotnet_methods.

**Comment by richardbuckle** [comment]
Let me reflect on that (pun intended). One approach might be to turn the anonymous NativeFunction objects into class properties. Another might be to keep them as they are but make them stubs that call member functions of the class.

The fact that both @Darkcyde13 and I had somehow forgotten about Help.md is rather telling.

**Comment by richardbuckle** [comment]
It will be useful for #1032 as well, to auto-generate lists of EDDI-specific functions and properties for syntax coloring.

**Comment by Tkael** [comment]
So, I've got a branch that accomplishes this (auto-generating a Functions.md document that we can use on the wiki and which can replace the current Help.md). I'm a little uncertain how we should go about replacing Help.md with an auto-generated document and having that same auto-generated doc available when the `Help` button is clicked. Feedback welcome.
