### ISSUE TITLE
Standalone (and via VA addon) crash every time

### ISSUE THREAD

**Issue by EclipzzeX** [EDCD/EDDI#304]
## EDDI version in which issue found
[v2.4.1 - v2.4.6-b1]

## Steps to reproduce

1. I can install and run v2.4.0.  The moment I upgrade (mandatory v2.4.5) the standalone version crashes.  The windows "EDDI has stopped working" error message.  The same result happens when VA has addon support enabled (VA crashes as well).  VA does work on it's own.  I have downloaded and installed every version from v 2.4.0 up to v 2.4.6-b1, and ONLY v2.4.0 does not crash.  Deleting %APPDATA\EDDI has the same effect on EDDI (crashes)

2.  Recently reformatted my computer and reinstalled all applications.  I am now running Windows 10 1709 (OS Build 16299.64)

## Expected
Expected EDDI Standalone to not crash

## Observed
EDDI Standalone crashes every time.

## Investigation
Tested with every version from v2.4.1 up to, and including v 2.4.6-b1.
![image](https://user-images.githubusercontent.com/22237366/33962476-afa839c6-e01f-11e7-80bc-1e550b14164e.png)

at version 2.4.0 was able to turn on the verbose logging.  Here is the log with the last attempt to fire up a v 2.4.6-b1 stand alone session

[eddi.log](https://github.com/EDCD/EDDI/files/1557085/eddi.log)

**Comment by Tkael** [comment]
If you've just recently re-installed, have you already run Elite Dangerous? We recently found a bug where EDDI would crash if the folder where Elite Dangerous stores your player journals hasn't been generated yet ([your Saved Games folder]\Frontier Developments\Elite Dangerous). The next update will handle this case more gracefully.

**Comment by EclipzzeX** [comment]
This was indeed exactly the issue.  I just fired up E:D, got right in to the game and when I exited out, ran EDDI up, all is good.

Thank you!!!  I never use E:D without EDDI, so that possibility did not occur to me.  AWESOME.
