### ISSUE TITLE
No voice/ sounds even test voice won't work

### ISSUE THREAD

**Issue by Stompmaster** [EDCD/EDDI#314]
![clipboard02](https://user-images.githubusercontent.com/31919747/34296458-af87d8a2-e75e-11e7-948f-ecd99bd5163c.jpg)

## EDDI version in which issue found
[2.4.6-b2]

## Steps to reproduce

1. [Just installed the new version and get no sound/voice]
2. [3 versions i had sound/voice saying systems, damage, market data etc but nothing since. i thought the new version might fix it so i had sound but no luck]

## Expected
[sound/voice. even the test voice doesn't work]

## Observed
[no sound, i have checked and have app installed in voice attack even though i don't use voice attack, i just wanted the sounds/ voice for market data ship status etc.
Investigation
[Checked
![clipboard02](https://user-images.githubusercontent.com/31919747/34296656-3413ecf0-e75f-11e7-8dee-a5d15472a6db.jpg)
 all you trouble shooting and rest from Elite but still no luck.]

**Comment by Tkael** [comment]
System volume is not muted? 
Are you getting sound from other apps?
`Volume of speech` in EDDI's `Text-to-Speech` tab is not zero?
The voice that you've selected works in other applications?

If all of the above is true, try disabling phonetic speech on the `Text-to-Speech` tab. Does that resolve the issue?

**Comment by Stompmaster** [comment]
Hi yes system volume is not muted, sound is coming from other apps,no not set to zero, and yes the voice works in other applications.
i have also tried your suggestion of disabling the phonic speech still no luck.
Thanks for trying but not sure what is going on.

**Comment by Tkael** [comment]
It sounds like you haven't had spoons for a few versions. If you install a prior version, do you get sound back?

**Comment by Tkael** [comment]
Closed due to lack of response, but  I'll re-open if you are still trying to figure this out. Were you able to resolve this issue?
