### ISSUE TITLE
Make sure all pending actions are completed prior to writing to config files

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#316]
Ref. #305 & #311. Ship monitor was getting written before asynchronous actions to add and remove were completed.

**Comment by richardbuckle** [comment]
Is this still valid @Tkael @Hoodathunk? I think we have is sorted now?

**Comment by Tkael** [comment]
I agree that the immediate issue that prompted this appears to be resolved. If we see something that looks like this is the future, we'll generate a new issue at that time... there's no need to keep an issue open.

**Comment by Hoodathunk** [comment]
Agreed.
