### ISSUE TITLE
Imperfect window restore if quit while minimised

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#319]
## EDDI version in which issue found
2.4.6-b2

## Steps to reproduce

1. Launch EDDI
2. Siize the window.
3. Exit and relaunch.
4. Observe window size as set.
5. Minimize EDDI.
6. Exit form the toolbar.
7. Relaunch EDDI.
8. Restore from the toolbar,

## Expected
EDDI restores to dimensions when minimised.

## Observed
EDDI restores to v wide dimensions, as if something got transposed.

**Comment by richardbuckle** [comment]
On hold in case incoming b3 fixes solve it.

**Comment by Tkael** [comment]
Not fixed by #313.

**Comment by Tkael** [comment]
Closed pending approval of #320.
