### ISSUE TITLE
EDDI not reacting  to Planetary Docking Request  Landing Pad Assignments

### ISSUE THREAD

**Issue by jngreene** [EDCD/EDDI#321]
## EDDI version in which issue found
[EDDI 2.4.5 plugin via VA 1.6.9 Steam]

## Steps to reproduce

1. Approach a Planetary  facility
2. Request Dock
3. EDDI no response....

## Expected
Expected TTS response with Landing pad number (and preferrably location, but I understand the planetary facilities provide a difficult means location description)

## Observed
no TTS response whatsoever and 'Repeat Landing pad' responsed with prior orbital facility landing pad number/location

## Investigation
 Systems Miaia, Merope and Kadu Mist tested numerous times

**Comment by Tkael** [comment]
EDDI's default script currently gives the docking pad number only for stations (neither outposts nor any planetary settlements have landing pad numbers described). 

You can modify the default script to read out landing pad locations for all stations by revising the script as follows:
```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{set station to StationDetails(event.station)}
{if station.model = "Coriolis Starport" || station.model = "Orbis Starport" || station.model = "Ocellus Starport" || station.model = "Asteroid Base" || station.model = "Unknown Starport":
    {Pause(8000)}
    {F("Landing pad report")}
|else:
    {Pause(8000)}
    Please make your way to landing pad {event.landingpad}.
}
```
Without having any clear way to describe the location, does reading the landing pad number add sufficient value to justify a change to the default script? I'll test this suggested change and see whether I feel like it's helpful.

**Comment by Tkael** [comment]
Updated script after a bit of use:
```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{set station to StationDetails(event.station)}
{if station.model = "Coriolis Starport" || station.model = "Orbis Starport" || station.model = "Ocellus Starport" || station.model = "Asteroid Base" || station.model = "Unknown Starport":
    {Pause(8000)}
    {F("Landing pad report")}
|else:
    {Pause(8000)}
    Landing pad {event.landingpad}
    {OneOf('ready', 'confirmed')}
    {Occasionally(4, cat(', ', F('Honorific') ))}.
}
```

**Comment by Darkcyde13** [comment]
I have something similar to this ready for my next release...

```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{set station to StationDetails(event.station, system.name)}
{set station_type to token(StationDetails(event.station, system.name).model, " ", 0)}
{set station_model to token(StationDetails(event.station, system.name).model, " ", 1)}

{if station_model = "Starport" || station.model = "Base":
    {Pause(11000)}
    {F("Landing pad report")}
|else:
    {if station_type = "Planetary": {Pause(11000)}
    |else: {Pause(2000)}
    }
    {Occasionally(2,"Landing")} Pad
    {event.landingpad}
    {OneOf("has been made", "is")}
    {OneOf("available", "free")}
    {OneOf("for {OneOf('landing', 'docking')}", "to {OneOf('use', 'dock at')}")}.
}
```
This adds the same long pause for planetary ports as it does for starports due to the longer in-game speech, and a shorter pause for outposts as they have little or no speech.  I use eleven seconds rather than eight, as even this length can sometimes start EDDI speaking over the in-game speech, but not quite as often anymore.
