### ISSUE TITLE
Sales advice given for haulage cargo

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#323]
## EDDI version in which issue found
[2.4.5]

## Steps to reproduce

1. Accept one or more missions to deliver cargo to another station.
2. Dock at a station where the market has demand for the type of cargo you are hauling.

## Expected
Either nothing or a note that I need to complete a mission in this station.

## Observed
If the station has a demand for any of the cargo I am hauling, I get the advice that I can sell my cargo here for a profit of X, which is incorrect because haulage cargo cannot be sold on the commodity market.  It cannot be sold at all while the mission is active; if you abandon the mission, it is considered stolen and can only be sold on the black market.

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Hmm. EDDI shouldn't be doing anything with mission cargo as long as a MissionID is set. 

An example from the journal manual:
```
{ "timestamp":"2016-07-26T11:36:44Z", "event":"MissionAccepted", "Faction":"Tsu Network", "Name":"Mission_Collect", **"MissionID":65343026**, "Commodity":"$Fish_Name;", "Commodity_Localised":"Fish", "Count":2, "Expiry":"2016-07-27T15:56:23Z", "Influence":"Low", "Reputation":"High" }
```

From the default `Commodity sale check` event:
```
        |elif cargo.missionid:
            {_ don't do anything with mission cargo at the moment}
```

I'm guessing you have journal entries you can share from accepting these missions and receiving the associated cargo?

**Comment by Tkael** [comment]
Consolidating to #47.
