### ISSUE TITLE
VoiceAttack: Array / list variables not transferred to VoiceAttack

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#33]
See for example: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/276
Option 1: Convert arrays to a concatenated string and send the string to VoiceAttack
Option 2: Recursively iterate through arrays and set variables according to a clear established pattern

**Comment by Darkcyde13** [comment]
While taking a quick look at this, I came across the following in jgm's original EDDI.  Is this anything that can be used? https://github.com/cmdrmcdonald/EliteDangerousDataProvider/commit/47aae56b8eb3f187140bbbed5156fdc6628a13ed

**Comment by Tkael** [comment]
nice find. :-) I believe that this code is what automatically writes the VoiceAttack variables that we enjoy today.

**Comment by Tkael** [comment]
So, I've studied this and object variables are translated to VoiceAttack. The auto-generated documentation (which is generated using a "test" method), however, is extremely inadequate for describing these variables and needs to be improved.
