### ISSUE TITLE
EDDI's 'Speech Responder' includes events which have no speech

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#332]
## EDDI version in which issue found
[2.4.6-b2]

## Steps to reproduce

Example scripts: 'Cargo inventory', 'Commander progress', 'Commander ratings', 'Docking requested', 'File header', etc.

## Expected
Each UI element should clearly describe its contents

## Observed
This UI element can be confusing / disorienting for new users who expect to see only speech related content in the tab entitles 'Speech responder'.
 
## Proposed Fix
Rename 'Speech responder' to 'Event responder' or 'Script responder'?

**Comment by richardbuckle** [comment]
I would argue that it *is* a spech responder, it's just that some of the scripts are silent by default. Nothing stopping a user from implmenting them though.

**Comment by Tkael** [comment]
I understand. But 'Event responder' may still be a more intuitive name for describing what this responder does and is.

**Comment by Tkael** [comment]
Or maybe even 'Event scripts'?

**Comment by richardbuckle** [comment]
Both are rather generic terms though. I mean technically every responder in EDDI is an event responder.

**Comment by Tkael** [comment]
'Script manager'?

**Comment by richardbuckle** [comment]
Well there is some merit in preserving jgm’s classification of Monitors and Responders as set out in ReadMe.md. “Manager” is another of those empty generic terms that ppl use to make fun of Java devs how are always coming up with stuff like “WombleFactoryManagerInterfaceCreatorMethod”.

Let me reflect on it.

**Comment by Tkael** [comment]
Closing as stale, no action for the time being.
