### ISSUE TITLE
Silent die on startup, Exception in NewtonSoft.Json

### ISSUE THREAD

**Issue by chriszero** [EDCD/EDDI#337]
## EDDI version in which issue found
2.4.6-b2

## Steps to reproduce

1. Goto "Commander Detail"
2. Specify any string with ' " ' [Quotation Mark, {U+0022}]

## Expected
EDDI doesn't crash ;-)

## Observed
Instant crash, unable to start again

## Investigation
Starts again if you remove the quotation mark
C:\Users\user\AppData\Roaming\EDDI\eddi.json

**Comment by chriszero** [comment]
Happens also with a \ [backslash]

**Comment by Tkael** [comment]
Hmm... the backslash is an escape character. Apparently commander detail doesn't like those.

We'll have to see if there's anything we can do to harden that, or at least to prevent crashes that an average user might struggle to recover from.

**Comment by Tkael** [comment]
Hmm... the backslash is an escape character. Apparently commander detail doesn't like those.

We'll have to see if there's anything we can do to harden that, or at least to prevent crashes that an average user might struggle to recover from.

**Comment by chriszero** [comment]
It's apparently a known problem of Newtonsoft.Json.
It cost me nearly an hour to investigate,  not an average user ;-)
Could be solved by using data validation on the wpf input box.

**Comment by Tkael** [comment]
Sorry about that then. I'll definitely be looking into it. 
By the way, why did you stumble across it? Is there a system or station name in-game which uses these characters?

**Comment by chriszero** [comment]
Typing some text with caps lock. Quotation mark is on 2 on the German qwertz layout.

**Comment by Tkael** [comment]
Closed pending approval of #341.

**Comment by richardbuckle** [comment]
Fixed for 3.0b1
