### ISSUE TITLE
Galnet Monitor - Filters?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#338]
## EDDI version in which issue found
[2.4.6-b2]

## Expected
Better control over the articles that are read allowed in the UI (rather than relying on users to understand and customize a complex script)

## Observed
At present, if the Galnet monitor is enabled then EDDI will read all articles except "Weekly Updates"

## Proposal
Update the UI to either filter strings for strings to either include or exclude from being vocalized.
e.g. 'Read all (interesting) articles except articles which include the strings...' or 'Read only (interesting) articles which include the strings...'

(Implementation on hold, Galnet Audio may reduce the need for this)

**Comment by richardbuckle** [comment]
Query whether this is sitll worth working on given Galnet Audio? We can focus our energies elsewhere.

**Comment by Tkael** [comment]
That depends on whether we want to remove the Galnet monitor entirely at this juncture. We should either support it or remove it. We shouldn't leave it in as a vestigial feature if we won't support it.

**Comment by Tkael** [comment]
Likewise for Spanish galnet, btw.

**Comment by Tkael** [comment]
I haven't spent enough time to have developed a strong opinion one way or the other.
Arguments for keeping:
- some users like to receive updates out-in-game
- some users might find the removal of this monitor to be fairly disruptive. 
- advanced users can search the content of the Galnet database for useful information or patterns
- if left in, we can simply have it report the article's title rather than full content (the full content is now accessible via Galnet Audio)
Arguments for removing:
- we have limited dev resources
- a similar feature is now available via the in-game ui
- we have an opportunity to simplify the code base

**Comment by Tkael** [comment]
If left in, we can add a check box for verbosity (unchecked / not verbose by default). That way, EDDI can alert users for new galnet articles without necessarily taking the same niche as galnet audio.

**Comment by richardbuckle** [comment]
Let’s give it a week or two to see how users respond to Galnet Audio, then re-evaluate. 

Personally I’m liking Galnet Audio a lot, especially the in-depth articles that play after the news. And if it can reduce our code burden / problem domain, I’m all the happier.

**Comment by Corysia** [comment]
As a user -- and after my first day in 3.0, I don't want EDDI automatically reading me the news articles.  It would be nice if EDDI would still give a summary.  E.g., "There are 2 new Galnet articles".  New from when?  Probably the last time I logged in, not necessarily which ones I've listened to.  EDDI shouldn't have to to track that, especially if I'm listening to them in Galnet Audio, not EDDI.  But I could also live without that feature.  Truth is, without knowing there are new articles, I'll likely not even look at Galnet Audio.

The old Galnet feature in EDDI was awesome and it filled in a missing piece.  And it raised awareness to the entire in-game news system.  But I'm in agreement that simplifying the code base is a good idea.  And at this point, EDDI is replicating a service now present in the base game, not necessarily value-adding.

**Comment by LesserHellspawn** [comment]
I find the Galnet monitor to be vastly superior to Galnet audio and would be sad to see it go.
Things I like in particular:
- automatically reads Galnet articles as they appear
- reads Galnet articles while I'm not ingame
- does not get interrupted by other ingame voices like Galnet audio does

**Comment by richardbuckle** [comment]
Propose to leave EDDI's Galnet monitor as is, close this ticket and devote our energies elsewhere.

**Comment by Tkael** [comment]
Agreed. I don't see much need for this at the moment.
