### ISSUE TITLE
EDDI crashes as soon as it's opened after updating to 2.4.5

### ISSUE THREAD

**Issue by theFisher86** [EDCD/EDDI#340]
## EDDI version in which issue found
[2.4.5]

## Steps to reproduce

1. Install EDDI version 2.3, upgrade when requested to 2.4.5
2. Watch it crash

## Expected
Work

## Observed
Crashes as soon as launched

## Investigation
I took a look at the Event Viewer logs and found this:
```
Faulting application name: EDDI.exe, version: 1.0.0.0, time stamp: 0x5a135051
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0ad705f0
Faulting process id: 0x290c
Faulting application start time: 0x01d38bf07e3e8415
Faulting application path: D:\Games\SteamLibrary\steamapps\common\VoiceAttack\Apps\EDDI\EDDI.exe
Faulting module path: unknown
Report Id: fe249c30-43bd-4c07-891c-23cccc277906
Faulting package full name: 
Faulting package-relative application ID: 
```

It should also be noted this is a brand new, fresh install of Windows 10.  Are there any dependencies that EDDI requires that I may be missing?  EDDI worked fine before I reinstalled windows but now it doesn't so I'm guessing it's a dependency thing but nothing in the log or installation instructions points to dependencies...

**Comment by theFisher86** [comment]
interestingly enough I just installed the 2.4.6-b version and that works just fine.... weird...

**Comment by Tkael** [comment]
EDDI 2.4.5 is dependent on the existence of the folder where your Elite Dangerous journals are stored. It sounds like perhaps you hadn't yet run Elite Dangerous on this new installation and that folder had not yet been generated.

As you've noticed, the beta version is more tolerant of this scenario.

**Comment by Tkael** [comment]
EDDI 2.4.5 is dependent on the existence of the folder where your Elite Dangerous journals are stored. It sounds like perhaps you hadn't yet run Elite Dangerous on this new installation and that folder had not yet been generated.

As you've noticed, the beta version is more tolerant of this scenario.

**Comment by Tkael** [comment]
EDDI 2.4.5 is dependent on the existence of the folder where your Elite Dangerous journals are stored. It sounds like perhaps you hadn't yet run Elite Dangerous on this new installation and that folder had not yet been generated.

As you've noticed, the beta version is more tolerant of this scenario.

**Comment by theFisher86** [comment]
That was exactly the problem! I hadn't run the game yet
