### ISSUE TITLE
EDSM exception

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#342]
## EDDI version in which issue found
[2.4.6-b2]

## Steps to reproduce

1. EDSM exception thrown occasionally when no response is received from EDSM (response = null).

## Expected
EDDI should handle such errors gracefully

## Observed
EDDI force closes (at least in debug mode)

**Comment by RedBaron1947** [comment]
Having an issue with the bet a version,when starting up I have to 'obtain log' before I can get EDDI to work
