### ISSUE TITLE
Other updates to player journal with Beyond, Chapter 1

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#347]
## This needs more sorting, but... To Do
- [x] Update handling EngineeringCraft event (EngineerApply) is obsolete.
- [x] Add and handle Reputation event
- [x] Add and handle Statistics event
- [x] Handle station type in DockingRequested, DockingGranted, DockingDenied, DockingCancelled, DockingTimeout events
- [x] Add and handle SystemsShutdown event
- [x] Re-evaluate the need for the Frontier API connection. Do we now have everything we need to drop it? (Not at this time. It is currently a unique source for some shipyard and commander data)
- [x] Re-evaluate the need for the Galnet monitor. With Galnet Audio, do we want to drop support for this? We can't sync "listened" items at present. (Per discussion in #338, we shall keep this for the time being)
- [x] Handle new Tech broker weapons and modules
  - Medium Shock Cannon (Fixed, gimbal & turret)
  - Medium Remote Flechette Launcher (Fixed & Turret)
  - Medium Enzyme Missile (Fixed)
  - Size 4 Meta Alloy Hull Reinforcement Package
  - Recon Limpet Controller
- [x] ~~Handle new Synthesis recipes~~
  - ~~for new Technology Broker modules and weapons~~
  - ~~for AX weapons~~
- [x] Add a new "Powerplay" event in the journal to log a player's powerplay allegiance, rank, merits etc

We've got our work cut out for us...

**Comment by Tkael** [comment]
@OtisB (EDMC) 
Current format:
{ "timestamp":"2018-03-02T11:28:44Z", "event":"TechnologyBroker", "MarketID":128151032, "ItemsUnlocked":[ { "Name":"Hpt_PlasmaShockCannon_Fixed_Medium", "Name_Localised":"Shock Cannon" } ], "Ingredients":[ { "Name":"iondistributor", "Name_Localised":"Ion Distributor", "Count":6 }, { "Name":"vanadium", "Count":30 }, { "Name":"tungsten", "Count":30 }, { "Name":"rhenium", "Count":36 }, { "Name":"technetium", "Count":30 } ] }

Coming soon:
{ "timestamp":"2018-03-02T11:28:44Z", "event":"TechnologyBroker", "MarketID":128151032, "ItemsUnlocked":[ { "Name":"Hpt_PlasmaShockCannon_Fixed_Medium", "Name_Localised":"Shock Cannon" } ], "Commodities":[ { "Name":"iondistributor", "Name_Localised":"Ion Distributor", "Count":6 } ], "Materials":[ { "Name":"vanadium", "Count":30, "Category":"Raw" }, { "Name":"tungsten", "Count":30, "Category":"Raw" }, { "Name":"rhenium", "Count":36, "Category":"Raw" }, { "Name":"technetium", "Count":30, "Category":"Raw" } ] }

**Comment by rodan123** [comment]
_Re-evaluate the need for the Galnet monitor. With Galnet Audio, do we want to drop support for this? We can't sync "listened" items at present._

I see this is checked off, don't know what was decided. I would like to see the Galnet code stay. As a VR/VoiceAttack user  I have galnet all set up so I can browse, read, delete, and mark articles all with a  few voice commands. I tried the new FD method and prefer voice over pulling menus and punching buttons.

**Comment by Tkael** [comment]
Discussed in #338. We'll keep it around, at least for the foreseeable future.

**Comment by Tkael** [comment]
Player Journal 3.03 updates

Fixed the TechnologyBroker event mixing up Commodities and Materials

Server synchronised time is now used for Journal timestamps

Fixed the Status.json flag for lights when in the SRV

All economy types are now listed in cases where a station has several

More information is included about Wing Cargo Delivery missions

Fixed the ‘fuel scooping’ flag in status.json

Fixed the ‘low fuel’ flag in status.json when in an SRV
