### ISSUE TITLE
Switching Recording/Playback Default Device - No EDDI audio output.

### ISSUE THREAD

**Issue by Renrek** [EDCD/EDDI#351]
## EDDI version in which issue found
[v.2.4.5]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
Switching playback from desktop speakers/microphone to headset by use of switching windows default.

2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
To hear output of EDDI though headset after switching default device.

## Observed
[describe what happened instead]
All output (Game, Voiceattack,) except EDDI sound output would go through headset and could be heard after switching. EDDI commands would trigger from headset microphone but no audio output. When switching back to desktop speakers EDDI output could be heard.

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
So is EDDI outputting through your speakers or not at all?
How are you switching your audio inputs and outputs? Please be very specific.

**Comment by Renrek** [comment]
EDDI is not outputting sound at all. I switch the defaults through the OS (Windows 10) then restart Teamspeak, Voiceattack, and ED. I have even restarted the whole OS. Everything including my personal Voiceattack TTS commands works, but the TTS commands from EDDI do not, I noticed that they execute through voiceattack but do not output sound at all. EDDI will execute "Configure EDDI" by bringing up the panel but anything that has TTS response does not have sound.

**Comment by Renrek** [comment]
I have got it to work by switching back the configuration I originally had speakers/USB Yeti Microphone. But when I want to use my Logitech Wireless Headset with Mic and I switch both Playback and Recording OS Defaults, EDDI does not follow suit. VoiceAttack works, and everything else, just commands that EDDI call TTS do not.

**Comment by Tkael** [comment]
EDDI simply uses the system default device for sound output. I also use both a headset and speakers and am able to switch back and forth between them quite easily (without needing to restart EDDI). I think this is likely to be a problem with your local pc setup...

Have you tried using VoiceAttack to switch your speakers and microphone yet? I've been pretty happy with that method.

**Comment by Renrek** [comment]
I have tried the VoiceAttack options to switch and ended up with the same result. When I switch, I do not get TTS output from EDDI, TTS output from voiceattack works, game audio, and teamspeak works, EDDI commands activate, such as calling up "configure EDDI" and the panel is displayed, I see the TTS commands execute, but with no audio. From my perception the only thing not working is EDDI TTS audio when I switch to headset, it functions when using speakers and Microphone.

**Comment by Renrek** [comment]
I used voice attack to call up the EDDI configuration panel, then used the "test voice" button on the Text-to-Speech tab, no results. However VoiceAttack will give me TTS audio from the commands that I created.

**Comment by Tkael** [comment]
So EDDI is totally silent? Not just on certain scripts?

Open the system volume mixer while using your headset. Verify that EDDI is not muted?
Check EDDI's TTS 'Volume of Speech' settings.
Try reinstalling EDDI and your audio drivers.

If all of those fail, enable verbose logging in EDDI, switch between speakers and your headset a couple of times and trigger some speech, then click the 'Report an Issue' button in EDDI's UI. A zipped log will appear on your desktop. Disable verbose logging and attach the zipped log to this thread for review.

**Comment by Tkael** [comment]
Hi, what's the status on this issue? Were you able to find a resolution?

**Comment by Renrek** [comment]
I'll make sure to try the suggested steps after work tomorrow.  Thanks for the follow-up.

**Comment by TobiasPottgueter** [comment]
Any news on this issue? A friend of mine has a similar problem.
He had used his USB headset at the time he installed EDDI.
As of now he's using his on-board sound card with his speakers and EDDI won't output any sound unless he switches back to his USB headset.

**Comment by Renrek** [comment]
I guilty of not getting around to trying the suggestions. Single parent/Work full time running an IT Dept. I have the next three days off, I will make an effort to experiment and submit my findings.

**Comment by Tkael** [comment]
In my experience, this has always been a local pc sound configuration issue.

**Comment by Tkael** [comment]
Closing as not an EDDI issue.
