### ISSUE TITLE
global persistent variables in response scripts

### ISSUE THREAD

**Issue by branchgabriel** [EDCD/EDDI#354]
in the scripting language I would like to prevent repeated events using the script

for example I want to set a lastmessage variable 
 then I could check the last message and see if it is the same as the previous then I could prevent the AI double spamming

how do you declare a persistent variable?  would you do it to the Context?

Is there a context variable like eddi_context_my_variable

Can I create one myself somehow?  Then I could always store the last message and script a way around all the repeated chatter.

Thanks

**Comment by Darkcyde13** [comment]
You can create persistent variables using SetState().  These will stay in memory, and be available to all scripts, until you close EDDI.

It looks like you are on the right track with what you are saying about "context".  State variables can be any name you choose, like "this_variable" or "eddi_context_my_variable".

To declare (or set) a State variable, use {SetState('variable_name', variable_to_store)}.  Then to use that variable later, use {state.variable_name}.

As for your question, the last message received over comms (assuming this is what you mean) is already stored by SetState() in the Message Received event.  What you would need to do is add an IF statement at the beginning to check if the next message received is the same as the last one.  Something like this:-


```
{if state.eddi_context_message_content != event.message:

   {_ Context }
   {SetState('eddi_context_last_subject', 'message')}
   {SetState('eddi_context_last_action', 'receive')}
   {SetState('eddi_context_message_name', event.from)}
   {SetState('eddi_context_message_content', event.message)}

   {if event.player = true:
       {if event.message = "o7":
           {event.from} salutes
           {if event.channel = "player":
               you
           }.
       |else:
           Message received from {event.source} {event.from}.  Message reads: {event.message}.
       }
   |elif event.source != "Station":
       Message received from {event.source} {event.from}.  Message reads: {event.message}.
   }
}
```

This will check the last message to see if it matches the new one, if it doesn't (shown by the 'not equal' != ) then it will process the event script as normal.  If it does match, then it will skip the whole thing.

Hope this helps! :)

**Comment by branchgabriel** [comment]
I didn't know you could reference state directly I was looking all over other scripts to see if it was possible but couldn't find an example.  now we have an example which is great

`state.some_variable`

Knowing this now has me begging the next question. 
Other than using 
`{SetState('my_variable_name', 'value')}`
to set a variable.  How do replace the value of an existing variable?  kinda like this 

`state.my_variable = foo`  like in javascript or java

can I just use "set" directly  for example

`set state.my_variable to foo`  

or is this not the correct way to do it?

**Comment by Darkcyde13** [comment]
Unfortunately, no.  The only way to set a global variable, accessible from any script, or for the same script over multiple executions, is via SetState().  SetState's  function is to store data across script executions.

Using {set my_variable to your_variable} will only store that value into that variable in that single instance of that particular script.  When a script ends, all variables declared during it's execution are deleted as they are not persistent.

You cannot reassign a value to a state variable by only using {set x to y}, and the syntax of 'state.my_variable' is only used for accessing the stored value.  You must use SetState() to reassign a new value.

I could be wrong, but I believe that SetState was written by the original EDDI programmer for this specific purpose as it is not a native Cottle function.  Cottle is the scripting language that EDDI uses.

Here's the link to the Cottle reference and help:-
https://r3c.github.io/cottle/#toc-1

You are correct though with the equals sign '=', it is only used to compare values.

Although, I get the feeling I'm not quite grasping what it is that you are asking for?

**Comment by Tkael** [comment]
The SetState function is a special and very useful function created by jgm specifically to persist variables between script instances and to make those same variables available to VoiceAttack (by default they are not persisted). 
The function `{set state.my_variable to "foo"}` is not valid for two reasons: 
1. The `{set [key] to [value]}` function requires the key to be a string - it cannot be an object (accessing the properties of an object uses the period, for example cmdr.name would obtain the name value from the cmdr object). Consequently, the Cottle script engine cannot parse it.
2. As Darkcyde already noted it would apply only to that script instance.

Example usage for replacing persisted variable values:
```
{SetState("my_variable","foo")}
My Variable is {state.my_variable}.

{SetState("my_variable","bar")}
My Variable is {state.my_variable}.
```
You can read more about the function [here](https://github.com/EDCD/EDDI/blob/develop/SpeechResponder/Help.md#setstate) and for use with VoiceAttack [here](https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration).

Closing as this feature already exists in the app.
