### ISSUE TITLE
E:D Beta - Bonds Redeemed - rewards array

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#358]
## EDDI version in which issue found
2.4.6-b2

## Steps to reproduce
Earn some Combat bonds in the Beyond beta, and hand them in.

## Expected
Bond Redeemed event reports redeemed amount and faction redeemed for.

## Observed
Faction and amounts from 'event.rewards' no longer working.

## Investigation
Sorry if you're not looking for Beta problems, but I thought I'd report it just in case.

In the process of updating my Fines and Bounties, I've found that the 'event.rewards' array in the Bond Redeemed event doesn't seem to be populated any more.

In game, you can only redeem one at a time, and not all in one go, so I'm assuming they made a behind the scenes change.

Here's the journal entries:-
```
{ "timestamp":"2018-01-27T21:56:47Z", "event":"NpcCrewPaidWage", "NpcCrewId":209598272, "Amount":20241 }
{ "timestamp":"2018-01-27T21:56:47Z", "event":"RedeemVoucher", "Type":"CombatBond", "Amount":358892, "Faction":"Legacy Corp" }
{ "timestamp":"2018-01-27T22:01:54Z", "event":"NpcCrewPaidWage", "NpcCrewId":209598272, "Amount":7560 }
{ "timestamp":"2018-01-27T22:01:54Z", "event":"RedeemVoucher", "Type":"CombatBond", "Amount":134044, "Faction":"Traditional Wyrd Justice Party" }
```

**Comment by Tkael** [comment]
Closed pending approval of #369.
