### ISSUE TITLE
Update shipmonitor and associated functions

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#361]
- [x] Add Engineering data to 'Loadout' event ("Quality" and "BlueprintID" properties and "Modifiers" array )
- [x] Remove 'Insurance Excess' from 'Commander Details' tab in UI - since the 'Loadout' event will now provide both the ship value and its rebuy cost, this field can be calculated and no longer requires direct user input.
- [x] Send 'Loadout' events, rather than Frontier API raw shipyard data, to Coriolis and EDShipyard (ref. #484)
- [x] Handle 'Loadout' new data
- [x] Handle 'EngineerCraft' new data ("Quality" and "BlueprintID" properties and "Modifiers" array )
- [x] ~~Add and handle Outfitting.json~~
- [x] ~~Add and handle Shipyard.json~~
- [x] Handle ship's HullValue, ModulesValue, and Rebuy price in Loadout event
- [x] Add and handle StoredModules event. 
  - Since this is written whenever stored modules change, could this be used as a new trigger for the `ModuleArrived` event?
- [x] Add and handle StoredShips event
  - Use this to populate the shipyard rather than using Frontier API data?
  - Is this written whenever stored ships change, like StoredModules? If so, could this be used as a new trigger for the `ModuleArrived` event?
  - In list of stored ships, handle 'Hot' ships (flag them in the Ship monitor?)
- [x] Deprecate obsolete event `EngineerApply`
- [x] Add and handle EngineerLegacyConvert event
- [x] Handle EngineerID in EngineerContribution, EngineerCraft, EngineerProgress events
- [x] Review and handle possible modifiable module attributes in journal manual appendix?
- [x] Add and handle ModuleInfo event
- [x] Add bool values for whether certain module types are equipped (DSS, fighter bay, planetary vehicle hangar, weapons with expendable ammo, etc.)
- [x] ModuleStore, ModuleRetrieve, MassModuleStore, StoredModules: add Level and Quality to EngineerModifications; add "Hot" flag; add "BuyPrice" in list of stored items 

- Loadout events now are generated when exiting outfitting. 👍

**Comment by rodan123** [comment]
Just a note to let you know that the Shipmonitor is worse in b3. After buying a new ship it does not show, as in b2. A fix in b2 was to  delete the json and let EDDI rebuild it to include the new ship. This does happen in b3, the json stays empty.
Reverted to b2 and the json rebuilt as expected.

**Comment by Darkcyde13** [comment]
@rodan123 Where did you get a b3 from? My version of 2.4.6-b2 is not saying there is an update available?

**Comment by rodan123** [comment]
@Darkcyde13 Compiled from source. You are correct, there isn't a b3 release, yet. I am just letting the team know there is an issue with the shipmonitor code, so they don't release, even in beta, without looking at it, first.

**Comment by Tkael** [comment]
That's actually the primary reason b3 hasn't been released. Thanks for reporting.
