### ISSUE TITLE
Export to Coriolis; Mathematical issue.

### ISSUE THREAD

**Issue by Mainfrezzer** [EDCD/EDDI#367]
## EDDI version in which issue found
[2.4.6-b2]

## Steps to reproduce

Export any ship with modified hull armor to coriolis

## Expected
the modifications done to the hull armor being applied and calculated as expected. 

## Observed
the modifications undergo a basic flaw. theyre additive. thuse having a modified hull gives out false informations.

for example military composite; with a base resistance of - 40% explosive dmg modified to -28.81% result on export to coriolis to a -80.33% resistance. 

The export forgets to take the "- + - = +" into account. Because the positve value (Thermal resistance, whichs base is 0% gets calculated as expected)

**Comment by Tkael** [comment]
EDDI transmits raw values to Coriolis. Any miscalculation will necessarily be on Coriolis' side. Please report this as a bug to the Coriolis team. https://github.com/EDCD/coriolis
