### ISSUE TITLE
EDDI Core: Shipyard doesn't update correctly

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#37]
https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/222
https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/253

**Comment by Tkael** [comment]
https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/222

**Comment by Tkael** [comment]
EDMC is using the new StationServices in the Docked event to determine when to update the Shipyard. Would it be beneficial to do something similar? https://github.com/Marginal/EDMarketConnector/commit/93adfff746cc650d236903332abacb7dd96be59e

**Comment by Tkael** [comment]
Update: The 2.4 beta version of the Companion API includes info on docked ships. https://miggy.org/games/elite-dangerous/fd-api/docked-2.4beta1-nice.json. :-)

**Comment by Hoodathunk** [comment]
When I start on 2.4 cAPI updates, I will look at 'shipyard updating' first

**Comment by Hoodathunk** [comment]
I will work on this next.

**Comment by Hoodathunk** [comment]
I took a look at the associated Ship Monitor code and saw nothing hinky. Then tried to repeat Darkcyde's bug by re-naming my shipmonitor,json file and re-starting EDDI. My current ship (Corvette) was immediately loaded (via cAPI) into my Shipyard database. Note that the value of the current ship is only updated on cAPI Profile re-refreshes. I then cycled through all my mothballed ships (including a Cutter) and they all populated my Ship Monitor tab (excluding values, of course).

At present, I can't re-create Darkcyde's issue but I've work to do on issue, re-instituting the shipyard 2.4 cAPI profile upload functionality.  Please note that the shipyard data in the Profile is barebones... ship model, value, location, that's about it.

Really all it's good for is a placekeeper in the Ship Monitor until you make a ship current and get a 'Ship loadout' event.

**Comment by Hoodathunk** [comment]
Problem presented itself after adding five ships to the EDDI shipyard. This problem is nuanced in that an API update during an EDDI restart will populate the shipyard but a 'Ship loadout' event will not. Gives me somewhere to focus. May have to add some additional debug logging to drill down.

**Comment by Tkael** [comment]
I still can't connect to the Frontier API. Is this issue resolved now?

**Comment by richardbuckle** [comment]
Tests out OK here.
