### ISSUE TITLE
ShipTargetted Event (for Beyond)

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#377]
When written: when the current player selects a new target 
The amount of data written depends on the extent to which the target ship has been scanned 
Parameters: 
-  TargetLocked: bool (ie false when losing target) 
 
If target locked: 
-  Ship: name 
-  ScanStage: number 
 
If Scan stage >= 1 
-  PilotName: name 
-  PilotRank: rank name 
 
If scan stage >= 2 
-  ShieldHealth 
-  HullHealth 
 
If scan stage >= 3 
-  Faction 
-  LegalStatus 
-  Bounty 
-  SubSystem 
-  SubSystemHealth 
 
Example entries:
```
{ "timestamp":"2018-02-03T22:32:32Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":0 }
{ "timestamp":"2018-02-03T22:32:32Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":1, "PilotName":"$ShipName_Police_Federation;", "PilotName_Localised":"Federal Security Service", "PilotRank":"Dangerous" }
{ "timestamp":"2018-02-03T22:32:46Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":2, "PilotName":"$ShipName_Police_Federation;", "PilotName_Localised":"Federal Security Service", "PilotRank":"Dangerous", "ShieldHealth":100.000000, "HullHealth":100.000000 }
{ "timestamp":"2018-02-03T22:32:48Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"anaconda", "ScanStage":3, "PilotName":"$ShipName_Police_Federation;", "PilotName_Localised":"Federal Security Service", "PilotRank":"Dangerous", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Alliance of BD+47 2112", "LegalStatus":"Clean" }
{ "timestamp":"2018-02-03T22:32:49Z", "event":"ShipTargeted", "TargetLocked":false }
{ "timestamp":"2018-02-07T07:19:51Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"independant_trader", "Ship_Localised":"Keelback", "ScanStage":3, "PilotName":"$npc_name_decorate:#name=Jun-Al'e;", "PilotName_Localised":"Jun-Al'e", "PilotRank":"Competent", "ShieldHealth":100.000000, "HullHealth":100.000000, "Faction":"Traditional Wyrd Justice Party", "LegalStatus":"Clean", "Subsystem":"$int_powerplant_size4_class3_name;", "Subsystem_Localised":"Power Plant", "SubsystemHealth":100.000000 }
```

- [ ] Write `Ship targeted` script announcing when targeted ship shield and health values are detected as passing significant threshholds (50% shields, 25% shields, etc.)
- [ ] If not already in danger (see status object variables, PR #372), script may also announce ships which do not have a clean legal status and announce the available bounty for that target?
- [ ] If not already in danger (see status object variables, PR #372), script could occasionally comment on the targeted ship's combat rank, or on the difference between the pilot's combat rank and that of the targeted ship.

Note that module data is only written when that module is specifically targeted... most of the time it won't be present.

**Comment by HighwaymanEd** [comment]
If EDDI is able to determine the ship type targeted, could we get an action to target a specific module by name?

I realize that some module types will be unknown, but the core modules (thrusters, powerplant, FSD, etc) are all in known positions when cycling the previous sub-target.

For example, on a Python, the Powerplant is the 6th module when cycling previous sub targets (off the top of my head, it might be 7) from a freshly locked ship.

**Comment by Tkael** [comment]
Core modules are always at about the same positions but it's not precise. It does depend on the loadout of the target ship and EDDI won't receive that information from this event.
What EDDI + VoiceAttack will be to do will be to automatically cycle through subsystems until it arrives at the subsystem you wish to target, or auto-target the next subsystem when the current subsystem is reduced to zero health.

**Comment by Tkael** [comment]
Note that it takes about a second before Elite writes each new event, so locating a given subsystem on a target may take a couple of seconds.

**Comment by Hoodathunk** [comment]
Note that the event mechanics do not allow for tracking of shield and hull health to specific thresholds. Events are triggered for changes in targetlock, scanstage, and cycling the subsystem only.

@HighwaymanEd, the 'Ship targeted' event will be coming in the 3.0.1-b4 release and I have some VA commands using the new event which implement subsystem targeting fairly nicely. It's not quite ready for prime time but I would be happy to send you a link to the .vap file for testing purposes.

**Comment by richardbuckle** [comment]
PR merged
