### ISSUE TITLE
Crime and Punishment (for Beyond)

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#378]
- [x] ~~~Add `PayBounties` event~~~ (moved to #788)
- [x] Handle fines in MissionFailed and MissionAbandoned events, where appropriate. 
- [x] Handle Wanted Flag in Docked event
- [x] Interstellar bounties are created when the combined fines and bounties for factions aligned with the same superpower breach a threshold. If we track fines and bounties by faction and allegiance, we can generate events that warn when these thresholds are (or will soon be) reached.
- [x] Handle new crime "reckless weapons discharge"
- [x] Bounties and fines incurred by players are applied to the ship that the crime was committed in and never go dormant. Add Fine and Bounty objects to ship definitions.
- [x] Handle new 'detention centre' government type (for new detention centre spawning areas)
- [ ] Add property in the Journal's "Location" or "FSDJump" event indicating if the player is wanted locally
- [ ] Track the total cost to clear the fines and bounties on a hot ship. 
- Power bounties are issued instead of normal bounties for criminal acts to do with valid Powerplay interactions

**Comment by Tkael** [comment]
[ ] - Track notoriety and apply it as a calculation for player rebuy cost / insurance checks?
```
Notoriety and Murder
• Commanders gain a Notoriety rating, a value between zero and ten.
• Notoriety increases by one whenever a Commander commits a murder crime.
• Notoriety decays one unit every 2 hours of time when you’re logged in the game back down to zero. 
• For each level of notoriety, murder bounty values are increased by a fraction of the perpetrator's rebuy cost - the higher the notoriety, the bigger the fraction.
• If the victim is a Commander (a player rather than an NPC) then you pay 10% percent per point of notoriety of the difference between your base rebuy cost, factoring in engineering, and the victim’s rebuy cost. If your cost is less than your victim’s, this will be zero. This is to de-incentivise destroying smaller ships than your own. This number, as well as others in the Beyond update, will be revisited and tweaked after launch to make sure the game is as balanced and enjoyable as possible.
• In addition, Commanders that are destroyed have their rebuy cost reduced based on the notoriety level of their murderer - the more notorious the assassin, the bigger the discount on rebuy cost for the victim.
• Notoriety is linked directly to the Commander, regardless of which ship they fly in.
• Any Notoriety means the interstellar factors cannot clear your fines or bounties.
```

**Comment by Tkael** [comment]
- [ ] Strip 'wanted' attribute from EDDN messages?

**Comment by Tkael** [comment]
Rules for crime & punishment explained here: https://forums.frontier.co.uk/showthread.php/406433-Massive-flaw-in-the-new-Crime-and-Punishment-Selling-credit-for-real-money?p=6401954&viewfull=1#post6401954

**Comment by Tkael** [comment]
- [ ] Fixed missing "PayBounties" event

**Comment by Tkael** [comment]
- [ ] add ShipID and Faction information in PayFines and PayBounties

**Comment by Tkael** [comment]
- [ ] Localize UI facing strings like "clean" and "wanted"

**Comment by Hoodathunk** [comment]
Ship and module `hot` parameter is sufficient for tracking pending fines and bounties.

**Comment by Hoodathunk** [comment]
Data is available for Cottle scripting (by iterating through the criminal record and filtering the faction reports for a specific ship ID) to determine the amount required to clear a hot ship.

**Comment by richardbuckle** [comment]
The crime monitor now addresses this fully.
