### ISSUE TITLE
Add Hyperdiction event?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#382]
Remember current location and if the one in FSDJump is the same, trigger a Hyperdiction event

**Comment by richardbuckle** [comment]
You also get a SystemsShutdown event with no parameters.

```
{"timestamp":"2018-06-06T21:28:21Z","event":"SystemsShutdown"}
```

**Comment by richardbuckle** [comment]
I'm thinking we should drop this idea. The Thargoid events are different now, for one thing.

**Comment by Tkael** [comment]
Agreed.
