### ISSUE TITLE
No text 2 speech after crash

### ISSUE THREAD

**Issue by Rhenthyl** [EDCD/EDDI#383]
## EDDI version in which issue found
[2.4.6-b2]

## Observed
[Running windows 10, EDDI, Voice Attack, EDDiscovery.

Starting yesteraday for no apparent reason EDDI will randomly crash. Restarting it and it works fine, however the text 2 speech bit no longer works.]

## Investigation
[uninstalled, rebooted and reinstalled, text 2 speech still not working. VA works fine though]

**Comment by Tkael** [comment]
I can't help without more information. Log? Sound settings? Did you check the text to speech volume slider in EDDI?
Closing for the moment for lack of information.
