### ISSUE TITLE
custom pronunciation - "thargoid"

### ISSUE THREAD

**Issue by gregmcdougall** [EDCD/EDDI#386]
Can I specify custom pronunciations? The mispronunciation of thargoid as thar-go-id should be configurable?

**Comment by Corysia** [comment]
I'd like to see a pronunciation table, too.  My own name is said correctly by my chosen TTS, but not by another.  There was an app I had, called ReadPlease that had a simple key/value index where you could put in your own phonetic or SSML.

**Comment by Tkael** [comment]
Duplicate of #140. But definitely something we're looking at. Thanks! 🙂

**Comment by Tkael** [comment]
Do you have an IPA with a more correct pronunciation? We probably won't get to the full lexicon into the next update but we could probably slip in a specific pronunciation for thargoids.

**Comment by richardbuckle** [comment]
Already raised as #140 and #98.
