### ISSUE TITLE
"Nav beacon scan" script producing a "Body scanned" and "Star scanned" event for each body in a given system

### ISSUE THREAD

**Issue by CMDRLupusAlpha** [EDCD/EDDI#387]
## EDDI version in which issue found
[2.4.5]

## Steps to reproduce

1. [Accept a mission requiring you to travel to a nearby system (1 or 2 jumps away). Travel to that system. Locate the Nav Beacon in vicinity of the main star. Drop from supercruise at the Nav Beacon. Perform a normal scan (target and point crosshairs at Nav Beacon). ]

2. [It has happened several times lately in different nearby systems. The same thing happened at "Ross 41" Nav Beacon in the same game session, but the last system was named "Tabit". I believe the bodies in those systems where already known rather than "Undiscovered".]

[Journal.180227123907.01.log](https://github.com/EDCD/EDDI/files/1765013/Journal.180227123907.01.log)
[eddi.log](https://github.com/EDCD/EDDI/files/1765019/eddi.log)

## Expected
[Just the Nav Beacon Scanned script.]

## Observed
[The first script that is read via EDDI is the **Nav Beacon scanned** script (eg. "_This navigation beacon contains information on 31 bodies in this system_")  followed by a **Body scanned** script and **Star scanned** script for every one of those bodies within the system. Tabit has 31 bodies, and I was bombarded with 31 scripts in a row (eg " _Analysis of body complete_ "... " _Analysis of body complete_ " ... " _Analysis of body complete_ " .. etc ).]

## Investigation
[Nil. Although I don't remember this happening with earlier versions of EDDI.

I have however recently changed my TTS from Ivona _Amy_ to Cereproc _Heather_. I have noticed the Cereproc voice doesn't recognize the {Pause()} command, so perhaps it's something to do with how Cereproc TTS works with EDDI's code.]

**Comment by Tkael** [comment]
Relevant timestamp appears to be `2018-02-27T01:57:04Z`.
I see that you are using EDDI with VoiceAttack. 
According to the log, the scan events are being triggered through VoiceAttack (via `((EDDI body scanned))` and `((EDDI star scanned))` but EDDI is not triggering a executing a corresponding '((EDDI nav beacon scan))' command through VoiceAttack. The event is in the journal. 

If the nav beacon scan event is not being detected through the VoiceAttack plugin that might account for the behavior we are seeing. 
If you haven't already done so, please add a command to VoiceAttack called `((EDDI nav beacon scan))` and re-test (see https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#running-commands-on-eddi-events)?

**Comment by richardbuckle** [comment]
Multiple other users reporting this in 3.0b1

**Comment by richardbuckle** [comment]
This [forum post](https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=6445951&viewfull=1#post6445951) may also be relevant.

**Comment by richardbuckle** [comment]
Looks like this is related to #395 then, and fixing #395 should fix this.
For confirmation, running EDDI standalone I scanned some nav beacons in systems in Colonia that I've never been to before, and the bug did not occur.

**Comment by Tkael** [comment]
#395 is unrelated. #395 has to do with the status monitor, which was only introduced in 3.0.0-b1. This error was reported with version 2.4.5.

**Comment by Tkael** [comment]
Incidentally, I tested with in-development version 3.0.0-b2 and the problem did not occur.

**Comment by Tkael** [comment]
@CMDRLupusAlpha Are you still having this problem? Have you tried the suggested fix?

**Comment by CMDRLupusAlpha** [comment]
Not yet unfortunately. Sorry, work and running a household getting in the way. Will update to the supported version and re-test within the next 24hrs if all goes to plan. Thanks for your patience and effort investigating the issue.

**Comment by Tkael** [comment]
Closing due to lack of updates and inability to replicate. Please reply to this issue if you identify additional information - we'll still get the notification. :-)

**Comment by CMDRLupusAlpha** [comment]
Hi guys, after a few months of not being in a position to re-test this issue, I've had a look at my EDDI and VA scripts with a fresh pair of eyes and I now know what causes this issue.

I had a VA command called ((EDDI Star scanned)), which did 2 things... 
1. calls for an EDDI event I wrote primarily to generate random speech options (eg. "."I am compiling the data from the {OneOf('Scan','Analysis','Review','Survey')} of this {reportbody.stellarclass}-class star now")
2. Asks me if I want further information about the star. If I respond with "yes", the EDDI event "Star report" is triggered.

The same goes for my ((EDDI Body scanned)) script in VA. This is because when I'm flying around I might not want a full report generated from scanning every body, especially if it's just another small icy body.

I just changed my EDDI events to generate the random speech (as per above in point 1.) via the "Star scanned" and "Body scanned" events (rather than via the VA script ((EDDI ...))  ) and left the request for further info to still be generated via VA script called ((EDDI Star scanned)).

When I scanned the Nav Data point in game I no longer heard 40x repetitions of both "star scanned" and "body scanned" . But I did still hear "would you like more information about this star/body", repeated over and over again.  So I guess  ((EDDI Star scanned)) and ((EDDI Body scanned)) (both VA commands) haven't reaped the benefits of your implementation of "Nav beacon scan" blocking the repetitions of "Star scanned" and "Body scanned". 

I have no idea of a way to work around this problem at this stage.

Sorry for the confusion, and sorry for taking so long to get back to you. I'm unfortunately unable to play for months at a time due to work, much to my disappointment.

**Comment by Tkael** [comment]
That seems reasonable. We block the speech from the speech responder but the events are still generated.
Thanks for following up with more info about this.
