### ISSUE TITLE
TLS error connecting to update server

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#390]
Github have tightened which TSL protocols they accept and this seems to be stopping EDDI from connecting to our update server.

https://stackoverflow.com/a/29221439
https://githubengineering.com/crypto-removal-notice/

**Comment by Tkael** [comment]
I've been watching this. Looks like the best option may be to update the project properties to build using the latest version of the .net framework?

**Comment by richardbuckle** [comment]
Yes I'm exploring it now. Doesn't help already deployed builds of course.

**Comment by richardbuckle** [comment]
As we suspected:


![tls](https://user-images.githubusercontent.com/227024/36867825-52d37b50-1d8e-11e8-8173-7cb52f18ea08.PNG)

**Comment by Tkael** [comment]
Possible fix submitted on PR #406. If this is acceptable, we'll want to try to transition to this new version ASAP and publicize the change as much as we can (Reddit, Discord, Frontier Forums, etc.). 
I'm afraid we're going to have a lot of users that simply won't realize that the auto-update mechanism was broken in their client.

**Comment by rodan123** [comment]
I compiled 3.0.0-b2 on my machine and was still unable to connect to the EDDP server.
_2018-03-09T01:08:07 EDDI:.ctor [I] EDDI 3.0.0-b2 starting 
Net:GetResponse [W] Failed to obtain response, error code SecureChannelFailure 
2018-03-09T01:08:08 EDDI:CheckUpgrade [W] Failed to access http://edcd.github.io/EDDP/ System.Exception: Failed to contact update server
   at Eddi.EDDI.CheckUpgrade()_

My reason for wanting to connect was not so much for the upgrade notifications, but for the material and blueprint json data. The failure to connect to EDDP has broken all scripts that use that data.
Have you considered moving that data to the local install directory? The data is fairly static, hasn't updated in months, and it would save having to download it upon every launch of EDDI. I have already modified the code read a local copy of the json files. If you are interested in this solution, I can post up a PR.

**Comment by richardbuckle** [comment]
Thanks for the heads up @rodan123 — I’ll look into this before proceeding with 3.0.0-b2.

Please be aware that materials and blueprint data have in fact changed for 3.0 so we need to proceed carefully here. However the upgrade server and the EDDP server are no longer on the same host, which may be the problem here.

**Comment by Tkael** [comment]
Hmm. I'm not seeing the same thing. Looks good on my side.

**Comment by Tkael** [comment]
Update: When doing a debug build, no problems are found.
When run from VoiceAttack, I see the same error as @rodan123.
`2018-03-09T16:36:29 EDDI:CheckUpgrade [W] Failed to access http://edcd.github.io/EDDP/ System.Exception: Failed to contact update server
   at Eddi.EDDI.CheckUpgrade() in [EDDI debug directory]\EDDI.cs:line 240`

**Comment by richardbuckle** [comment]
I wonder if VA is linked to an earlier release of .NET 4 and somehow that is downgrading EDDI?
Not sure how to test that hypothesis.

**Comment by Tkael** [comment]
Hmm. I might have that. The `ProtocolVersion` for the web request via VoiceAttack is `1.1`. I'll run the same code in standalone, I suspect it'll be different.

**Comment by Tkael** [comment]
Per https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility#version-compatibility-for-apps: 
`An app can control the version of the .NET Framework on which it runs, but a component cannot. Components and class libraries are loaded in the context of a particular app, and therefore automatically run on the version of the .NET Framework that the app runs on.`

**Comment by richardbuckle** [comment]
I think you right. BTW, `HttpWebRequest.ProtocolVersion` refers to the HTTP protocol not the TLS protocol. Confusing isn't it?

**Comment by richardbuckle** [comment]
https://stackoverflow.com/questions/26389899/how-do-i-disable-ssl-fallback-and-use-only-tls-for-outbound-connections-in-net/26392698#26392698
has a partial answer, but I want to read it carefully first.

**Comment by richardbuckle** [comment]
PR #411 -- please re-test under VA and let me know how it goes.

**Comment by Tkael** [comment]
No good. I've posted the exception messages to the PR.

**Comment by Tkael** [comment]
Now fixed by PR #411.

**Comment by richardbuckle** [comment]
... and **stay dead!!!!**
