### ISSUE TITLE
Problems with VA lowering landing gear

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#391]
See this [forum post](https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=6461680&viewfull=1#post6461680)

And [this one](https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=6460685&viewfull=1#post6460685).

**Comment by Tkael** [comment]
These seem to be problems that don't directly relate to the new status.json file and landing gear status, but I will test of course.

**Comment by Tkael** [comment]
Just tested both with and without VoiceAttack. The variables are being set as expected in both places.
