### ISSUE TITLE
'SRV under ship' script says the same thing when you drive away from the ship

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#392]
See [this reddit post](https://www.reddit.com/r/EliteDangerous/comments/810jfs/eddi_300b1_released/dv05pm8/).

One thing I just noticed: The 'SRV under ship' script says the same thing when you drive away from the ship; "SRV standing by for recovery", which of course doesn't make sense as you race away.

**Comment by Tkael** [comment]
Possible change: "Stowing turret"?

**Comment by Tkael** [comment]
I have a simple fix ready for this, but it's somewhat dependent on the changes to the status monitor so I'm waiting for those to get approved first.

**Comment by Tkael** [comment]
PR submitted on #410. Closed pending approval.

**Comment by richardbuckle** [comment]
Are we sure we even want to generate the event when the SRV leaves the area under the ship? If we do, then the event needs a broader name.

I'm not sure how useful the event is when leaving, so my approach would be only to generate the event when entering, and dispense with the boolean `entering` property.

Thoughts?

**Comment by Corysia** [comment]
I can see a desire for this.  The event could remind you to dismiss the ship.  It could give a cheeky good-bye message as you pull away "bye-bye boys, have fun storming the castle!"  You could change the voice or Voice Attack Profile.

I think a better question is, is it significantly different from "SRV Launched" to warrant another event type?  I believe so as it offers more granularity to the events occurring in the game.

**Comment by Tkael** [comment]
I'm in favor of giving people lots of hooks that they can interact with.
For example, you could auto-dismiss the ship when the SRV leaves the area under the ship via VoiceAttack.

**Comment by richardbuckle** [comment]
fair enough, but I shall split it int two events "SRV entered recovery zone" and "SRV left recovery zone".

**Comment by richardbuckle** [comment]
Second thoughts, rename the event to "SRV recovery zone transition"

**Comment by richardbuckle** [comment]
Upon testing, it looks to me that this event gives no more info than the existing SRV turret event. In particular, the status doesn't show whether the SRV can board its mother ship, only that it is under a ship and its turret is stowed.

I think we should yank this event.

**Comment by richardbuckle** [comment]
Event removed

**Comment by richardbuckle** [comment]
New branch `feature/SRV-turret-depoyable`. Let's discuss.

Way past my bedtime here :)
