### ISSUE TITLE
Every star is "one of the youngest in the galaxy"

### ISSUE THREAD

**Issue by Djuwanna** [EDCD/EDDI#397]
## EDDI version in which issue found
3.0.0-b1

## Steps to reproduce
Scan a star

## Expected
Age of the star to be more realistic

## Observed
Every star I scan is only a few thousand years old, "making it one of the youngest stars in the galaxy"

## Investigation
Suspect this is due to FDEV changes in the log format

**Comment by Tkael** [comment]
Which version did you upgrade from?  EDDI used to get different numbers for stellar age from the journal vs. the server and used to treat them differently. We corrected that but you may still have an old version of the script.

Try: 
1. opening the Speech responder tab in EDDI
2. locating the Star report script
3. clicking the 'edit' button to open the script
4. clicking the button to restore / revert to the default version of the script.
5. closing and re-testing.

**Comment by Djuwanna** [comment]
It seems a number of these scripts are not defaulted, and I didn't modify them.  I'm going to try editing all of them back to default (so I dont' have to reprogram everything if I delete and reinstall).  I'll let you know what I find.  Thanks for the quick response!!!

**Comment by Tkael** [comment]
Ok. Closing as fixed but I'll continue to monitor this thread in case you run into any additional complications.

**Comment by Djuwanna** [comment]
Ok, I figured out what's going on - I'm not using the default EDDI personality, I copied it and created my own AGES ago.  And the scripts associated with THAT personality are old.  I'm copying the EDDI default to another new personality and editing that.  I bet it will work now!
