### ISSUE TITLE
Ship error

### ISSUE THREAD

**Issue by IanTrev** [EDCD/EDDI#399]
## EDDI version in which issue found
2.4.5

## Steps to reproduce

When using the ship name to indicate where you are going, it is getting the wrong one from the list.

## Expected
It's always used the correct name previously.

## Observed
It used another name from the list of my ships.

## Investigation
Restarted it, but that's all. It happens every time now.

**Comment by Tkael** [comment]
This sounds like a known issue - #305. It's a bug introduced by the timing of different threads trying to write to the shipmonitor. We're already working on a fix in response to # 305 so this appears to be a duplicate and should be closed as such. In the meantime, you'll need to clear your corrupted config file:
1. Close completely out of EDDI and VoiceAttack
2. Navigate to %APPDATA%/EDDI
3. Delete `shipmonitor.json`
4. Restart EDDI and launch Elite Dangerous. The shipyard should automatically repopulate as you switch ships.
