### ISSUE TITLE
'Nav beacon scan' event

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#4]
No filter is present to prevent all scan events from being processed & spoken

@Genar_Hofoen (Captain's Log) recommended an approach (using python code to show how Captain's log handles these):

@VerticalBlank (EDRefCard) CL2's JournalParser is a QtObject, so I emit a Signal() when encountering an event handled by the parser. Here's the bit of code for navbeaconscan...
```
    # navbeaconscanevent = False  # Flag to enable or disable scan event notification for GUI.
    # navbeaconscancount = 0  # No. of navbeacon scan events parsed.
    # numbodies = 0  # No. of navbeacon scan events expected.
    def parse_navbeacon_scan(self, line):
        if 'NumBodies' in line:
            self.numbodies = line['NumBodies']
            self.navbeaconscancount = 0
            if self.numbodies > 0:
                self.navbeaconscanevent = True
                self.navBeaconScanStart.emit(self.numbodies)
```
@VerticalBlank (EDRefCard) Then in my parse_star and parse_planet_scan() functions, I'll look to see if self.navbeaconscan is True, and if so, handle the events differently from a normal, interactive scan event.
@VerticalBlank (EDRefCard) partial bit of code at the end of parse_star_scan() ...

```
        if self.navbeaconscanevent:
            self.navbeaconscancount += 1
            self.navBeaconScanBodiesLeft.emit(self.navbeaconscancount)
            if self.navbeaconscancount == self.numbodies:
                self.navbeaconscanevent = False
                self.numbodies = 0
                self.navBeaconScanEnd.emit()
            else:
                return
        self.starScanCompleted.emit(line['BodyName'])
```

**Comment by Tkael** [comment]
No filter is present to prevent all scan events from being processed & spoken

**Comment by Syrrianyl** [comment]
As I see, i don't have any more log from beacon scan, but what i think to solve this problem, and let the choice to final users to have or not all the scans of a system is to create a new function in 'SrcipResolver', a function named GetState, I put this in line 548, just before SetState.
`
            store["GetState"] = new NativeFunction((values) =>
            {
                string name = values[0].AsString.ToLowerInvariant().Replace(" ", "_");
				dynamic StateValue = EDDI.Instance.State[name];
				return StateValue;
			}, 1);

 `

So, after, in the "_Nav beacon scan_" script i add a `
  {SetState("Number_Give_by_Beacon", event.numbodies)}`

And in "_Body scanned_" and "_Star scanned_" I use the value of Number_Give_by_Beacon

For exemple in the "_Body scanned_" it will be like that

`{_ Context }
{SetState('eddi_context_last_subject', 'body')}
{SetState('eddi_context_last_action', 'scan')}
{SetState('eddi_context_body_system', system.name)}
{SetState('eddi_context_body_name', event.name)}

{Pause(1000)}

Scan de {P(event.name)} terminé.


{
if GetState("Number_Give_by_Beacon")>0:
 {SetState("Number_Give_by_Beacon", GetState("Number_Give_by_Beacon")-1)}
|else:
   {F("Body report")}
}`

**Comment by naperken** [comment]
@Syrrianyl - A 'getstate' function is not required. State variables are treated as an objectwithin the speech responder. Using your example, 'state.Number_Give_by_Beacon'.

Addtionally, counting down within a speech responder script has been tried. One theory is that the Cottle interpreter can not keep up, resulting in an inaccurate count.

**Comment by Syrrianyl** [comment]
I agree that it don't work with 'state.Number_Give_by_Beacon', and i use my try with many beacons, and it work well every time the event appear.

**Comment by Tkael** [comment]
One possibility is that due to the "asynchronous" nature of EDDI, some of the scan events may be completing prior to the completion of the nav beacon scan event?

**Comment by Syrrianyl** [comment]
I make other test and finaly realise that the Nav Beacon count also the clusters, so that why also i have difference on counting object in little system

**Comment by naperken** [comment]
I've been studying the event handler in EDDI. All responders subscribe to EDDI events and the  Journal Monitor adds events to the  EDDI 'events' list. Right now, all journal events are processed by the Speech Responder.

EDDIResponder.cs says each repsonder must have an event handler... of course Speech Responder does.

Again, all journal events are 'ungated' in the Speech Responder event handler.

Seems to me a simple matter of gating the 'Scan' events depending on the nav Beacon body count.

Right now, 'Belt Clusters' are ignored in the Journal Monitor... may have to move that functionality to the Speech Responder event handler.

**Comment by Syrrianyl** [comment]
for the cluster belt, the only data are the name and distance from main star. Composition and mass are in the star log. 
If we open the cluster belt scan event, for the data of the belt, the most easy is to send a message to say that compostion is in star, but, not funny for the game play. Or if th star is not yet scanned, send a massage that it's better to scan the star first. with the data of the star if it is possible to save the cluster data somewhere before to use that when the cluster is scanned, or it is too complicate (I don't realize really that)

**Comment by Hoodathunk** [comment]
After more studying of EDDI debug log and how Journal events are passed to Responders (and what's included), the problem is a bit more convoluted because the event type (name) is not included, so you need to re-deserialize the 'raw' event to retrieve (again) the event type and other necessary values. This code snippet has been added to the Speech responder Event Handler...

`
IDictionary<string, object> data = Deserializtion.DeserializeData(theEvent.raw);
            object val;
            data.TryGetValue("event", out val);
            string edType = (string)val;
            if (edType == "NavBeaconScan")
            {
                data.TryGetValue("NumBodies", out val);
                beaconScanCount = (int)(long)val;
                Logging.Debug("beaconScanCount = " + beaconScanCount.ToString());
            }
            else if (edType == "Scan")
            {
                if (beaconScanCount > 0)
                {
                    beaconScanCount -= 1;
                    Logging.Debug("beaconScanCount = " + beaconScanCount.ToString());
                    return;
                }
                data.TryGetValue("BodyName", out val);
                string name = (string)val;
                if (name.Contains("Belt Cluster"))
                {
                    // We ignore belt clusters
                    return;
                }
            }
`

Unfortunately, I was unable to more extensively test this because the 2.4 Beta is now closed. I have ensured that the code snippet is transparent to 'Live'.

I'm going to commit & push with the understanding that detailed testing is required as soon as 2.4 goes live.

**Comment by Tkael** [comment]
Per Darkcyde's report, this is still bugged in beta 2.4 and reading out scans for each body in the system.

**Comment by Tkael** [comment]
I tried this day. Out of just over 20 bodies in the system, only the star scan was voiced.

**Comment by Hoodathunk** [comment]
Ok, that sounds right. At the time, it wasn't clear whether the star scans were included. This is an easy fix.

**Comment by richardbuckle** [comment]
Fixed for me now.
