### ISSUE TITLE
Downgrading crashes EDDI

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#401]
## EDDI version in which issue found
[3.0.0-b2]

## Steps to reproduce

1. Install EDDI 3.0.0-b1 or 3.0.0-b2
2. Install EDDI 2.4.6-b2
3. Attempt to launch EDDI

## Expected
EDDI starts and is stable

## Observed
EDDI crashes

**Comment by richardbuckle** [comment]
Hmm, the installler is designed to support upgrading but not downgrading. It's a tall order because obviously a 2.4.6 installer cannot know what we have added in 3.0.0. 

Let me reflect on this. I would argue that it is within spec, just confusing.

**Comment by Tkael** [comment]
After further testing this appear to be invalid. I believe the crashing was actually attributable to EDSM being down. Version 2.4.6-b2 would crash if the plugin was active but no response was received from EDSM. We fixed that, but not before 2.4.6-b2.
Closing this issue.
