### ISSUE TITLE
Fuel status too frequently announced.

### ISSUE THREAD

**Issue by Corysia** [EDCD/EDDI#402]
## EDDI version in which issue found
3.0.0-b1

## Steps to reproduce

1. Jump to a star.  You'll likely hear what your fuel reserves are.  
2. Fuel scoop.  You'll hear your ship is fully refueled.  You will sometimes also hear your fuel level again.  Sometimes you'll finish scooping before the system information is finished, reporting a lower fuel level than you actually have, then following up with the new level.

## Expected
Less frequent updates.  Perhaps adding a user-configurable threshold value for when updates should be seldom or more frequent.  For example, maybe at 50% fuel reserve, you're alerted more often.  At 25%, you're warned every time you jump.

**Comment by Tkael** [comment]
We have a couple of options here:
1. Leave the default script as-is (in which case you can still modify your local script to your preferences by adding `Occasionally()` (see the `Help` button in the `Edit Script` window)
2. Revise the default script to use `Occasionally`
3. Revise the default script to not speak at all if fuel is >75%
4. Move the `Fuel check` call from the `Jumped` event script and drop it into the newly created `Low fuel` event script (so it'll only announce fuel level before you scoop if your fuel reserves are at less than 25%) but will still report level after you scoop
Thoughts?

**Comment by CMDRLupusAlpha** [comment]
Tkael, this is exactly what I have done, simply removed the part of the script that reported fuel for anything greater than 50%.
I find it much more user friendly only being reminded of my fuel level when I'm getting low, rather than being told the status after every jump.

**Comment by Corysia** [comment]
My choice would be something similar to 2 and 3.  Greater than 75%, don't speak.  After all, when scooping, we already hear "Your ship is fully refueled."  At 75%, speak occasionally.  At 50%, more frequently.

**Comment by Tkael** [comment]
Dropping a revised version of the script here to use for testing... it will scale back fuel reporting as your fuel level increases. Let me know what you guys think? 
```
{_ Fuel Check _}
{_ Report fuel level _}

{if ship.name = state.eddi_fuelcheck_shipname:
    {if state.eddi_context_fuel_used > state.eddi_fuelcheck_maxfuel:
        {SetState('eddi_fuelcheck_maxfuel', state.eddi_context_fuel_used)}
    }
|else:
    {SetState('eddi_fuelcheck_maxfuel', state.eddi_context_fuel_used)}
    {SetState('eddi_fuelcheck_shipname', ship.name)}
}

{set maxfuel to state.eddi_fuelcheck_maxfuel}
{set fuelremaining to state.eddi_context_fuel_remaining}
{set maxjump to fuelremaining/maxfuel}
{set currentfuel to round(fuelremaining / ship.fueltanktotalcapacity * 100, 1)}
{if find(currentfuel, ".0") > -1:
   {set currentfuel to round(currentfuel, 0)}
}
{set shipsfuel to:
   {Occasionally(2, "{P(ShipName())}'s" )} Fuel
   {OneOf("levels", "tanks", "reserves")} {Occasionally(2, "are")} {Occasionally(2, "now")}
}
{set currentpercent to: 
   at {currentfuel} percent {Occasionally(2, "capacity")}
}
{set title to Occasionally(3,"{F('Honorific')}")}

{if maxjump < 0.5:
   Danger!
   {shipsfuel} depleted!
   {Pause(500)}
   Running on reserves. Shutdown of non-essential systems is advised!
   {Pause(500)}
   Emergency transponder standing by, {title}
|elif maxjump < 1.25:
   {OneOf("Warning:", "Caution:", "Danger:", "Attention:")}
   {shipsfuel} {OneOf("dangerously low", "almost depleted")}.
   {OneOf("Please refuel", "Refueling is strongly recommended")}, {title}
|elif currentfuel < 25:
   {OneOf("Warning:", "Caution:", "Danger:", "Attention:")}
   {shipsfuel} {OneOf("below 25%", "{currentpercent}" )}, {title}
|elif currentfuel < 50:
   {shipsfuel} {OneOf("below 50%", "{currentpercent}" )}, {title}
|elif currentfuel < 75:
   {Occasionally(2, "{shipsfuel} {currentpercent}, {title}")}
|elif currentfuel < 100:
   {Occasionally(3, "{shipsfuel} {currentpercent}, {title}")}
|else:
   {shipsfuel} {OneOf(currentpercent, "at maximum")}, {title}
}
```

**Comment by Corysia** [comment]
I tested this a bit more last night while in a Sidewinder so I'd use up some fuel.  Huge improvement to my ears!

**Comment by richardbuckle** [comment]
For my part I would only add that I have customised my own script to round to the nearest percent. The extra decimal place has no information value and dropping it cuts down the verbosity a lot.

**Comment by richardbuckle** [comment]
As an aside, I often feel that we should be more mindful of cognitive burden when designing our scripts. More info isn't always better.

**Comment by Tkael** [comment]
Agreed. I'd forgotten to incorporate that change into this version. Here's a revision:
```
{_ Fuel Check _}
{_ Report fuel level _}

{if ship.name = state.eddi_fuelcheck_shipname:
    {if state.eddi_context_fuel_used > state.eddi_fuelcheck_maxfuel:
        {SetState('eddi_fuelcheck_maxfuel', state.eddi_context_fuel_used)}
    }
|else:
    {SetState('eddi_fuelcheck_maxfuel', state.eddi_context_fuel_used)}
    {SetState('eddi_fuelcheck_shipname', ship.name)}
}

{set maxfuel to state.eddi_fuelcheck_maxfuel}
{set fuelremaining to state.eddi_context_fuel_remaining}
{set maxjump to fuelremaining/maxfuel}
{set currentfuel to round(fuelremaining / ship.fueltanktotalcapacity * 100, 0)}
{set shipsfuel to:
   {Occasionally(2, "{P(ShipName())}'s" )} Fuel
   {OneOf("levels", "tanks", "reserves")} {Occasionally(2, "are")} {Occasionally(2, "now")}
}
{set currentpercent to: 
   at {currentfuel} percent {Occasionally(2, "capacity")}
}
{set title to Occasionally(3,"{F('Honorific')}")}

{if maxjump < 0.5:
   Danger!
   {shipsfuel} depleted!
   {Pause(500)}
   Running on reserves. Shutdown of non-essential systems is advised!
   {Pause(500)}
   Emergency transponder standing by, {title}
|elif maxjump < 1.25:
   {OneOf("Warning:", "Caution:", "Danger:", "Attention:")}
   {shipsfuel} {OneOf("dangerously low", "almost depleted")}.
   {OneOf("Please refuel", "Refueling is strongly recommended")}, {title}
|elif currentfuel < 25:
   {OneOf("Warning:", "Caution:", "Danger:", "Attention:")}
   {shipsfuel} {OneOf("below 25%", "{currentpercent}" )}, {title}
|elif currentfuel < 50:
   {shipsfuel} {OneOf("below 50%", "{currentpercent}" )}, {title}
|elif currentfuel < 75:
   {Occasionally(2, "{shipsfuel} {currentpercent}, {title}")}
|elif currentfuel < 100:
   {Occasionally(3, "{shipsfuel} {currentpercent}, {title}")}
|else:
   {shipsfuel} {OneOf(currentpercent, "at maximum")}, {title}
}
```

**Comment by richardbuckle** [comment]
Thanks, tryng that out. I personally had set the use of the ship name to 1 in 4, personal preference.

**Comment by Tkael** [comment]
Why name your ship if EDDI never uses it? ;-) If there's a consensus that it's a little too often, I don't have any opposition to reducing it.

**Comment by richardbuckle** [comment]
One time in four != "never" :-p
When buckyballing the repetition can get a bit wearisome.

**Comment by richardbuckle** [comment]
Anyhow, happy to go with the above script as default.

**Comment by richardbuckle** [comment]
Discussions like these make me glad.

I have made the last cited script above the default for 3.0.0-b2.
