### ISSUE TITLE
Status variables Not Set in VoiceAttack

### ISSUE THREAD

**Issue by mark-austen-charterhouse** [EDCD/EDDI#404]
## EDDI version in which issue found
2.4.6-b2

## Steps to reproduce

1. Create a VA script which outputs {TXT:Status gui focus} to the log when F4 is pressed.
2. Start up VA and check that EDDI is initialised.
3. Start up Elite and enter your mode of choice.
4. Open the System Map, Galaxy Map or any other of the panels.
4. Press F4

## Expected
The name of the open panel should be displayed in VA.

## Observed
Not set is displayed.

## Investigation
Tested the output with {TXT:Name} which correctly output the commander name.
No further test done, asked this question in case there is a known issue with the Status variables.

**Comment by Tkael** [comment]
Status variables are not supported in version 2.4.6-b2. They are part of current beta 3.0.0-b1 (and soon to be be released 3.0.0-b2)
