### ISSUE TITLE
Possible issue in 'Commodity sale check'

### ISSUE THREAD

**Issue by rootwalla** [EDCD/EDDI#415]
## EDDI version in which issue found
3.0.0-b1

Haven't tested it, but it might interfere with expected behaviour.
Ln 83 of the script is missing quote marks around offload and dump:
You can {OneOf('offload, dump', 'fence')} your stolen
probably should be:
You can {OneOf('offload', 'dump', 'fence')} your stolen

**Comment by Corysia** [comment]
I've submitted a PR to fix this.

**Comment by Tkael** [comment]
Fixed by PR #416. Thanks Corysia. :-)
