### ISSUE TITLE
Proposal: Make all Voice Attack variables for EDDI contextual

### ISSUE THREAD

**Issue by Corysia** [EDCD/EDDI#438]
To avoid accidentally stepping on anyone else's variables in Voice Attack, I propose changing all variables pushed to VA to contain some sort of context.  For example, if the context is "EDDI_", then variables such as "Title" would become "EDDI_Title".

Also, as this is a x.0 release, this may be the best time to introduce this sort of change.

**Comment by Tkael** [comment]
There is of course already an option to use profile scoped variables in VoiceAttack too.

**Comment by Corysia** [comment]
Yes, I knew this would be a big, breaking change and that is why I thought it should be discussed at the 3.0 release level rather than 3.0.1 or 3.1, etc.  Recent events in the community also brought it to my mind.  

I've reviewed the Voice Attack Help manual and I don't believe Command or Profile scoping in Voice Attack can help in this case.  A VAP writer can protect their own variables from being overwritten by a global.  But there's nothing to protect EDDI's variables from being accidentally overwritten by a 3rd party plugin and vice versa.

This approach is already being done with Events.  For example, the event is ((EDDI docked)), not simply ((docked)).

**Comment by Hoodathunk** [comment]
Would be same amount of work to re-write profiles using profile-scoped variables and would provide significantly more protection

**Comment by Tkael** [comment]
That might be the least disruptive set of variables to disturb, but if we do this I'm leaning more towards a "once and done" approach.

**Comment by Tkael** [comment]
`Profile-scoped variables are private to their respective profiles`
See http://voiceattack.com/SMF/index.php?topic=1852.msg8600#new

**Comment by Corysia** [comment]
> Yeah, level of difficulty = low, amount of time required = high.
I'm still new to the code base, but aren't all the Voice Attack variables confined to VoiceAttackPlugin.cs and start with `vaProxy.Set*` ? In most cases, a prefix is passed in.  `setDictionaryValues()` seems to already do what I'm mentioning with `string varname = "EDDI " + prefix + " " + key;`

There's also the idea of deprecation where new variable names are introduced, but the old ones are kept around for a few releases to allow people time to change.  It'll double the memory usage in VA for EDDI, tho.

**Comment by richardbuckle** [comment]
CAn the work be automated at all? In any case, strongly recommend waiting until I have the localisation stuff squared away as that too will churn the codebase quite a bit (hopefully of this weekend).

**Comment by alterNERDtive** [comment]
> Would be same amount of work to re-write profiles using profile-scoped variables and would provide significantly more protection

Scoping is a solution to an entirely different problem. EDDI’s variables _should_ be global, not restricted to a profile; I’m not even sure you can effectively set scoped variables through a plugin anyway.

The proper solution here would be name spacing; that has to be supported in VoiceAttack though, and until then the best you can do is prefixing your variables.

**Comment by richardbuckle** [comment]
So my takeaway as a non-VA user is that the variables should be:

1. global
1. ideally namespaced
1. since namespaced isn't possible, prefixed

Yet prefixing would break existing user code.

This smells like a `won't fix` to me alas.

**Comment by richardbuckle** [comment]
Closing as `won't fix`.
