### ISSUE TITLE
upgrade 2.3.0 to 2.3.1 or 2.4.02b = download failed

### ISSUE THREAD

**Issue by RoundAbout2Space** [EDCD/EDDI#439]
## EDDI version in which issue found
running 2.3.0

## Steps to reproduce

1. start EDDI
2. click on upgrade button

## Expected
I expected tha the download starts as usual

## Observed
Voice Zira: upgrade failed, try later

## Investigation
nn

Any logs you need?

**Comment by Tkael** [comment]
Please manually download the latest version. The server host messed up our updater for older versions.

**Comment by Tkael** [comment]
https://github.com/EDCD/EDDI/releases

**Comment by RoundAbout2Space** [comment]
Thx for the link. Didnt found it yesterday... ☹

It’s running now on 2.4.5!

Fly safe cmdr

________________________________
