### ISSUE TITLE
'Bond Redeemed' Event: event.rewards empty?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#44]
I've been trying to make a list of the rewards when redeeming a combat bond, but it seems the event.rewards variable is always empty. Using len(event.rewards) results in zero. There doesn't seem to be any way to know what factions the redeemed bonds are for.

Is this a bug? Could this be caused by a change in the Player Journal? Or is it by design?

**Comment by Darkcyde13** [comment]
I reported this in the original EDDI issues, number 235. [https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/235](url)

**Comment by Darkcyde13** [comment]
Was going to say I had reported this, then I realised it IS the report I made! lol :P

**Comment by Tkael** [comment]
Yep. Sorry, I thought I'd attributed the stuff I transferred from the original but I guess I missed the attribution on this one.

**Comment by Tkael** [comment]
Huh. This code retrieves the amounts but there's a space between each of the values in each number (e.g. '1000' -> '1 0 0 0'). That shouldn't be happening.
```
   {set cur to 0}
   {while cur < len(event.rewards):
       {event.rewards[cur].amount}
      {set cur to cur + 1}
   }
```

**Comment by Darkcyde13** [comment]
Using my Bond Redeemed script in the beta version of EDDI, the test string is working perfectly.
`{_ Context }
{SetState('eddi_context_last_subject', 'bond')}
{SetState('eddi_context_last_action', 'redeem')}
{SetState('eddi_context_bond_amount', event.amount)}

{_ Update Fines & Bounties}
{F("FinesBounties_Delete")}

Combat bonds for {Humanise(event.amount)} credits redeemed
{Occasionally(2, "
  {if len(event.rewards) = 1:
    by {P(event.rewards[0].faction)}
  |else:
    by
    {set cur to 0}
    {while cur < len(event.rewards):
        {if cur = 0:
        |elif cur < len(event.rewards) - 1:
            , 
        |else:
            and
        }
        {P(event.rewards[cur].faction)} for
        {event.rewards[cur].amount} credits
        {set cur to cur + 1}
    }
  }
")}.
`
When run with the test string I get this:-
`Combat bonds for 2 thousand credits redeemed by The Pilots Federation for 1000 credits, The Dark Wheel for 500 credits and Los Chupacabras for 500 credits.`
I'm fairly sure I wasn't getting this when I first opened the issue.

**Comment by Tkael** [comment]
Hehe. Then we need to conclude that I over-complicated and bugged the Cottle script. Glad it's working now. Will update the default to showcase these object variables.
