### ISSUE TITLE
Not a full program.V3.0.0.-rc1

### ISSUE THREAD

**Issue by bookmite** [EDCD/EDDI#442]
Version V3.0.0.-rc1

Greetings, unfortunately I am not getting not the full set of options are showing in the UI, see attached photo

updated only today, but noticed it a couple of days ago.

No speech responder means I am not getting any voice responses in Elite. 

I have tried uninstalling, cleaning residual files/ folders and re downloading.

any tips on restoring this great application to its former glory ? 

much appreciate your efforts.
![eddi issue](https://user-images.githubusercontent.com/25581394/37767086-d3349ab2-2dc0-11e8-855a-d77595ec5220.jpg)

**Comment by Tkael** [comment]
It looks like EDDI is failing to load some of its files.
1. Please enable verbose logging, then close and reopen EDDI. 
2. Click the `Report an Issue button. 
3. A zipped copy of your recent log will appear on your desktop. Attach that log to this issue.
4. Disable verbose logging.

**Comment by JCalvertJoshua** [comment]
I had the same problem a couple of years ago with Eddi version 2.0
Here's what I wrote on the frontierforum about it. Maybe it helps.

> "I downloaded and installed Eddi2.0 this afternoon. At first it wouldn't work, most of the tabs were missing. I then checked the files in the Eddi map and noticed Windows had blocked most of them and I had to Unblock them first (some security stuff with Windows 10 when the files are downloaded from the internet, I've seen this before when installing a version of Voice Attack some time ago and IIRC Gary of VA changed the install routine of VA to avoid this).
After I unblocked the files and started Eddi again all the tabs were there so I could continue."
>

**Comment by bookmite** [comment]
Thanks for the advice chaps , I’ll try both options tomorrow and report back

**Comment by bookmite** [comment]
Greetings again, I tried what you suggested Tkael, however I got a message saying that the file failed to create the report, any ideas where I can go from here ? 

Joshua, I’m running W7ultimate x64 , I checked in the firewall and it’s allowed, and I don’t have BitDefender running, any ideas ? ...life is space is getting lonely :-)

**Comment by Tkael** [comment]
Try reinstalling in administrator mode?

**Comment by JCalvertJoshua** [comment]
I'm not sure if it's related to the version of Windows and/or firewall. Only remember I had to do the unblock action described in the link below for all files in the EDDI-folder. Otherwise the tab in Eddi would not appear. So for example if I looked at the properties of EddiSpeechResponder.dll it was blocked and the Speechresponder tab didn't appear. After I unblocked it in properties it appeared. Like I said it could be a whole different problem but it might be worth looking at it. 
Here's the link:
https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/

**Comment by bookmite** [comment]
Thanks for the information Joshua, I looked at the properties of the EDDI exe and it seems normal, nothing showing to unblock .

Tkael 
Again thanks Cmdr , I set the exe to run as Administrator, it still fails to compile the report .

Please let me know when you’re on discord, maybe you can talk me through  few ideas

**Comment by Tkael** [comment]
Did you right click on the dll files after installation to make sure they were unblocked?

**Comment by bookmite** [comment]
No I didn’t sir, I seem to have got it working by going in C/users/ name / app data / roaming and deleted ( moved ) all my customised json files and every other file in roaming and local . This got it working again or more correctly had got it working. I noticed as I logged out of Elite that the desktop icon was missing. I then went to the program directory and sent it to the desktop. It now sits on my desktop as an unrecognised file format icon . I will check every dll file properties tomorrow and report back .

**Comment by Tkael** [comment]
status?

**Comment by bookmite** [comment]
My apologies for not updating sooner.

It appears to be sorted thank you.

It seems it was due to some historic customised json files , I deleted those and it worked fine .

The unknown format icon was corrected within the file properties option
