### ISSUE TITLE
SIMPLE. the sceen is blazing white. AAdd some oconmtrast or it unusable

### ISSUE THREAD

**Issue by philgschmidt** [EDCD/EDDI#448]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
I'm not sure I understand your meaning. EDDI uses a fairly standard color template for Windows forms. 

Are you asking for theming support? Something else?

**Comment by Hoodathunk** [comment]
Recommend closing issue due to low effort and unreadable.
