### ISSUE TITLE
Fighter rebuilt event (for Beyond)

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#455]
- [x] Add and handle FighterRebuilt event
@Hoodathunk has expressed interest in this one.

**Comment by Hoodathunk** [comment]
Coding is done and I've tested in-game, just need to add a speech responder script. I expect to PR this tomorrow.

**Comment by Hoodathunk** [comment]
PR #456 generated

**Comment by Tkael** [comment]
Incorporated.
