### ISSUE TITLE
EDDI Core: Cargo not reported correctly

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#47]
See https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/258 & https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/263

**Comment by Tkael** [comment]
This information is not currently present in Companion API logs from beta testing 2.4.

**Comment by richardbuckle** [comment]
Appears to be working now the cAPI is back in 2,4

**Comment by Tkael** [comment]
cargo flags are working now? I must test this! 😀

**Comment by richardbuckle** [comment]
Haven't tested the flags but the limpets are detected correctly.
What are the steps for testing the flags?

**Comment by Tkael** [comment]
Essentially it would be to load up some illegal and stolen cargo and check the verbose logs to see what's recorded. I'll see if I can find some goods to use for testing.

**Comment by Hoodathunk** [comment]
Additionally, the ship.cargo object is not being properly updated during applicable 'commodity' and 'mission' events. If you look at CargoMonitor.cs, it's basically and empty husk. My guess if that this was a work in progress when jgm retired from EDDI development.

I'll take a look at this after I'm finished with the 2.4 cAPI update.

**Comment by Tkael** [comment]
I'm tempted to just turn it off. I don't think Frontier give us enough info to do cargo properly.

**Comment by Tkael** [comment]
@Hoodathunk This is applicable to the branch you are currently working on. o7

**Comment by Tkael** [comment]
Mission ID is not currently set for mission related cargo. Consequently, the `Commodity sale check` script reports mission cargo as available for sale. Ref. issue #323.

**Comment by richardbuckle** [comment]
Pinging this for a revisit.

**Comment by Tkael** [comment]
Incorporated.
