### ISSUE TITLE
'Location' Event handler using in EDDI.cs using 'body' data instead of 'station'

### ISSUE THREAD

**Issue by Hoodathunk** [EDCD/EDDI#474]
'Location' event handler in EDDI.cs still using event.body to designate docked station.

Previous revision of 'Location' event did not provide 'station' name and 'body' name was used instead to obtain docked station. Newer Journal revisions provide station name and unmodified EDDI.cs code is now (rarely) causing bogus station data to be sent to EDDB.

**Comment by Tkael** [comment]
PR #475 submitted (by @Hoodathunk )

**Comment by Tkael** [comment]
Incorporated at 3.0.0-rc3
