### ISSUE TITLE
EDDI Core: Create a 'Missions responder' and missions object?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#48]
Inspired by Darkcyde's mission scripts

**Comment by Tkael** [comment]
Inspired by Darkcyde's mission scripts

**Comment by Syrrianyl** [comment]
For the MissionAcceptedEvent, EDDI take actualy the comodity with 
`Commodity commodity = CommodityDefinitions.FromName(getString(data, "Commodity"))`
, is it not better to use  the Commodity_Localised with 
`string commodity = getString(data, "Commodity_Localised");`
and now we have also a LocalisedName for the name of the event, so is it better to replace
'string name = getString(data, "Name");'
by
'string name = getString(data, "LocalisedName ");'
or it is better to add a new like this
`string localisedname = getString(data, "LocalisedName");` and rework all the MissionAcceptedEvent by adding a value like:
`MissionAcceptedEvent(timestamp, missionid, name, faction, destinationsystem, destinationstation, commodity, amount, passengertype, passengerswanted, target, targettype, targetfaction, false, expiry, influence, reputation, localisedname) `

**Comment by Tkael** [comment]
@Syrrianyl Translation / localization is a separate issue. I've open https://github.com/Tkael/EliteDangerousDataProvider/issues/50 for your recommendation and removed it from here. This is an idea to create an object (like the 'System' object) containing information about current active missions and that can be queried by the user (maybe using a MissionDetails function?)

**Comment by Syrrianyl** [comment]
One day, if I learn enouth in C#, i will start to work for localisation, and an external json to be able to have EDDI with many language, like I see for EDMarket Connector.
But there is a very long way to go........

**Comment by Tkael** [comment]
Possible enhancement allowed by this: convert mission names to a more human readable format using EDDIDataDefinitions?

**Comment by Syrrianyl** [comment]
With new Mission Responder, you mean a new tab where we can see missions?
Is it for actual mission or with different tabs inside to have Abandonned/fail/success/actual missions? 

And for human readable , I have in my logs 2.4 and i think it is alos in english many XXXX_localised, or localisedname. I think that it is here where we can find that by adding à LocalisedName where we have the possibility.
For exemple in MissionAcceptedEvent.cs i think that withe the
`            VARIABLES.Add("name", "The name of the mission");`
we can add a 
`            VARIABLES.Add("Localisedname", "The localised name of the mission");`

and that can be usefull also for DataDefinition and others

**Comment by Tkael** [comment]
Not something in a new tab necessarily but rather something that could be accessed in Cottle with scripts and that would contain all of the information about your current missions. I was thinking it'd be an object described in Variables.md, like we currently have for the commander, ship, star system, etc.

**Comment by Hoodathunk** [comment]
As a collaborator on Darkcyde's mission scripts, I have a intimate understanding of the mission events, so I'm likely the best candidate to take this on.

I can see this functionality becoming a dedicated 'Monitor' and because there is no 'Mission' journal event at game starup (which would be a great idea, btw, FDEV!), a tab for viewing/manipulating the Mission objects would be mandatory... at the very least a button for 'wiping' it.

**Comment by Hoodathunk** [comment]
Now that the Cargo Monitor is in beta, I will be devoting time to this project.
