### ISSUE TITLE
"near surface" event didn't triger when i join or leave the Orbitalcruise

### ISSUE THREAD

**Issue by DragonSaphir** [EDCD/EDDI#492]
## EDDI version in which issue found
2.4.5

## Steps to reproduce
I have build in Voice Attack a new command namend ((EDDI near surface)) but it does not trigger.

**Comment by DragonSaphir** [comment]
after updating EDDI to version 3.0.0 it works ^^

**Comment by Tkael** [comment]
((EDDI Near surface)) wasn't supported in 2.4.5.
Glad you worked it out. 🙂
