### ISSUE TITLE
Companion API: Rare goods bug which reduces prices to minimum not handled.

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#5]
https://forums.frontier.co.uk/showthread.php?t=175338
https://github.com/Marginal/EDMarketConnector/issues/92
Some other projects have implemented a 'safety check' to prevent this bug. We need to review the EDDI source code to see if it had a similar safety check.
The developers of EDMC and EDDiscovery have worked around this by suspending calls to the Companion API while you are carrying rare goods. EDDI may have to do similarly.

**Comment by Tkael** [comment]
Some other projects have implemented a 'safety check' to prevent this bug. We need to review the EDDI source code to see if it had a similar safety check.

**Comment by Hoodathunk** [comment]
Proposed fix:
1. Add 'EnginnerContribution' event to Journal Monitor'
2. modify Cargo Monitor with a 'prehandle' to update cargo on EngineerContribution event
3. Suspend API profile requests while docked at stations with commodity services & carrying rares

**Comment by richardbuckle** [comment]
On hold because we suspect a fix is coming in the cAPI for 2.4.

**Comment by richardbuckle** [comment]
Frontier say this is fixed in 2.4. Test.

**Comment by richardbuckle** [comment]
Will retest now the cAPI is mostly back up.

**Comment by Tkael** [comment]
I don't think a proper test will be possible until #138 is fixed?

**Comment by richardbuckle** [comment]
Nah, the bug is triggered merely by calling the cAPI with a rare in the cargo hold, and FD have documented it as fixed. Not related to EDDN submissions. Easy to test.

**Comment by Tkael** [comment]
I believe the EDDN submissions are failing due to a change with cAPI, not a change with EDDN. 
i.e. the data isn't being parsed by EDDI correctly in the 1st place. Of course, I'm wrong if the 'Commodity purchased check' and 'Commodity sales check' scripts are triggering correctly. I need to catch some zzzz's so won't be able to test until tomorrow.

**Comment by richardbuckle** [comment]
That's not what this ticket is about ;-)

**Comment by richardbuckle** [comment]
YAY tested and FD fixed it.
