### ISSUE TITLE
Cargo monitor, Ship Monitor and Speech Responders (related and not)

### ISSUE THREAD

**Issue by Rode-Ven** [EDCD/EDDI#502]
## EDDI version in which issue found
3.0.1 b-1

## Observed
I have been using the beta version to play around with the new cargo monitor plugin and have run across several issues, not strictly limited to the cargo monitor, and some of them merely considerations for improvements.
It is perhaps noteworthy that some of the problems are limited to the Type-9 Heavy.
I have mostly switched between Type-9 and Anaconda for the test, and rarely a Viper Mk III.

Cargo monitor:
--------------
- sets cargo amount as price/unit - this seems to be specific to the Type-9 Heavy
- does not account for jettisoned cargo (discarded)
- minor typo: 'Sirius Inustrial Equipment' is missing a 'd'
- does not pool PP cargo, i.e. if I buy 3 lots of 50 Sirius Industrial Equipment, they appear as 3 separate entries, being reported separately
- PP cargo is reported as saleable at stations where it isn't, e.g. Sirius Industrial Equipment can only be unloaded in LYR control systems.  maybe exclude PP cargo from being considered

Ship monitor:
-------------
Export to Coriolis
- exports module mass data incorrectly, i.e showing only the module's default weight (e.g. FSD at 40t, where it should be an engineered 52t)
- Type-9 seems to be missing the lately added additional class 8 slot, therefore all module data is exported to the wrong slot

Speech responder:
-----------------
Commodity sale check
Commodity purchased
Commodity sold
- consider adding Humanise() for total cost, total profit. listening to all that single digits stringed up becomes fatiguing rather quickly, especially when selling many lots of cargo

Commodity sale check
- only ever reports using the 'unknowncommodities' branch
  ('marketcommidities' are matched by EDDBID, maybe that is stored wrong?)
- wrongly reports PP cargo as saleable,  maybe exclude PP cargo from being considered

Fighter rebuilt
- also triggered when a fighter successfully docked after being recalled, which makes 'reconstruction complete' a bit irritating

Fine incurred
- minor typo in description: 'when your' should be 'when you'

Power preparation vote cast
- minor typo in description: 'perparation' should be 'preparation'

Ship refueled
- when refueling by 10% at stations, EDDI reports 'fully refueled', though fuel level is well below 100%.

FSD engaged
- (just curious, as there is a section handling comments: how do you set a comment for a system in E:D?)
- consider writing 'not populated' - 'unpopulated' is pronounced as 'new populated' by MS Anna on my machine
- consider writing 'light-years' - 'lightyears' is proncounced as 'light-i-ears' 
- consider downtuning of F("System report") for systems visited often. when flying fortification missions for LYR I don't need the 120th repetition on Lembava. 
I achieved that by altering the script by the following snippet, but maybe there is a way to track how often a system has been visited during a session - I wouldn't mind being informed once per session
`           {if !system.population:
            {OneOf("This system is not populated","There is no human presence here", "Humans have yet to colonise this system")}.
        |elif system.visits < 5: 
            {F("System report")}
        |elif mod(system.visits,5) = 0:
            {Occasionally(4, 
              "{system.name} is {Pause(500)} {Emphasize("ahem!")} {Pause(700)}
                {OneOf(\"I am not going to repeat all the boring stuff again\", 
                       \"Blablabla... as if you would care what I say\",
                       \"but you know that already, don't you?\")}
                .")}
        }
`

**Comment by Hoodathunk** [comment]
- Setting cargo amount as price/unit is a bug, already squashed. This will be corrected in 3.0.1-b2
- Cargo Monitor should account for ejected cargo, but due to limitations in the Journal event data, some events will be improperly reported. I have some improvments coming in b2.

I wrote a post in the FDEV forum regarding cargo related journal event limitations.
https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=6638933&viewfull=1#post6638933

- If commodities have the same ED name, they should be pooled together, regardless of being PP. I will look into this.

- Sirius Industrial Equipment only sell-able in LYR space and similar PP-related issues would require significant filtering for very specialized items... and that's if super-power data is readily available in StationDetails(). I will think on this one.

**Comment by Tkael** [comment]
The Coriolis bugs you noted will need to be addressed with the Coriolis team... we just send Coriolis the raw data from the Loadout event written to the player journal.

**Comment by Rode-Ven** [comment]
I see. It's a bit difficult to tell by who an observed misbehaviour could be addressed from my side of the console.
I assume the aforementioned Loadout event includes the correct mass data? 
Alternately, where can I find that data  so I could take a look myself?

**Comment by Hoodathunk** [comment]
Mass data is not included in the Journal 'Loadout' event. Recommend looking at the Journal Manual

Latest can be found at https://forums.frontier.co.uk/showthread.php/401661-Journal-Documentation-for-v3-0

If you want to peruse your own 'Loadout' data, copy the 'Loadout' event from your latest Journal file and paste into your JSON Viewer of choice.

My favorite is http://xml-json.kwebpia.net/

**Comment by Hoodathunk** [comment]
Also, I've worked on the Commodity sale check. It's now less annoying about power play and some mission-related commodities.

I will incorporate changes in next beta, along with mentioned typos, and will consider suggestions/requests.

**Comment by Rode-Ven** [comment]
I had a look at the loadout event data in my save game files, and the mass data I observed as not exporting right is indeed included, as it is corrections by engineering that is exhibiting deviations.

I furthermore had a look at Coriolis import, and can confirm that there is a problem with its importing function. It seems data gets assigned to wrong 'slots' (e.g. mass data correction for a shield gen gets assigned to 'optimal mass' instead of 'mass').

I'll report that to Coriolis, as you suggested (unless you already did so).

In the meantime, I have come across another possible bug in EDDIs cargo monitor:
When returning from a sightseeing mission to drop off 2 passengers, EDDI informed me I could drop of my mission related clothing cargo. However, I carried no cargo, only those two passengers.
Would you prefer that I'd open a new issue for this?

**Comment by Tkael** [comment]
Multiple, well focused issues are typically preferred over a single "fix everything" issue. But we appreciate the feedback. ;-)

**Comment by Tkael** [comment]
Perhaps categorize purchased Powerplay cargo as `Haulage`?

**Comment by Tkael** [comment]
@Rode-Ven Going through some of this now. Comments are synced from EDSM. And these can be set from VoiceAttack using the default commands in EDDI.vap.

**Comment by Tkael** [comment]
Closing, I think both @Hoodathunk and I have had time to absorb this feedback. Thanks!
