### ISSUE TITLE
Typo in Crime.cs

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#506]
Found this error in my eddi.log;
`2018-04-29T04:11:14 Logging:Report [W] Unable to report message "Unknown Crime ED name dockingMajorTresspass". Invalid data type System.Collections.Generic.Dictionary``2[System.String,System.Object] `

In DataDefinitions\Crime.cs; `public static readonly Crime TrespassMajor = new Crime("dockingMajorTrespass", "Trespassing");`

The EDname is typo-ed as Tre**ss**pass from fdev, declaration should match? Possibly the same for dockingMinorTrespass.

**Comment by Tkael** [comment]
Thanks. I'm already aware and have a local branch waiting in the wings to correct this. 
I'll submit the PR once we merge localization.
