### ISSUE TITLE
V3.0 with astra voice attack.cannot make EDDI stop talking

### ISSUE THREAD

**Issue by RamonSpiteri** [EDCD/EDDI#507]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Try this: https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#shutup
If that doesn't help, we're going to need more details. 

Closing as resolved (as much as the provided information permits). I'll be notified however if you reply to this issue again. :-)

**Comment by RamonSpiteri** [comment]
It worked. Thank you

**Comment by RamonSpiteri** [comment]
How do I import EDDI.vap into voice attack

**Comment by Tkael** [comment]
A copy of EDDI.vap is included in the installation directory (usually your VoiceAttack/Apps folder). 

For guidance on importing profiles, please see `Importing Profiles and Profile Packages` in VoiceAttack's help documentation.
