### ISSUE TITLE
Name is Spelled Out instead being said

### ISSUE THREAD

**Issue by flamberth** [EDCD/EDDI#508]
## EDDI version in which issue found 3.0.0
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
After scooping EDDI lets me know the ship is refueled.  Before v.3.0.0 EDDI said the name of the ship.  Now the name is spelled out letter by letter.
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
Expected to hear the name of the ship.
## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
We're sorry to hear your having trouble. This is the 1st report we've had with this issue and we need a bit more information before we can really get to the bottom of this. 
- If you switch to the default `EDDI` personality, does the issue persist? 
- What settings are you using on the `Text-to-Speech` tab?
- What's the name of the ship
- Are you using VoiceAttack or are you using EDDI as a stand-alone app?

**Comment by flamberth** [comment]
Thank you for the help.
Text-to-Speech tab:
Voice: Microsoft Zira Desktop
Volume: 72
Speed: 0
Processing: 43
Distort on Damage -checked.
Disable phonetic speech -not checked.
Enable ICAO: -not checked.
Ship's Name: Galactic Explorer II
Using VoiceAttack with EDDI

EDDI did say the ship's name correctly tonight, although I wasn't able to reproduce the same situation where my ship was at 85% fuel capacity or less.  If it happens again I'll pay closer attention to the speech and comment on this thread again.  Thank you.

**Comment by Tkael** [comment]
Thanks. Unfortunately, nothing is popping out as out of place (yet). 
Has this occurred multiple times? Has your ship's name always been Galactic Explorer II? Or was it recently renamed? When the issue occurred, did EDDI try to spell out all of the name, or just a part of it?
I'll close this issue for the time being (on the assumption that it was a onetime event and may have been misheard), but if you comment on this issue again I'll get the ping. o7 cmdr!

**Comment by flamberth** [comment]
Galactic Explorer II has been the ship's name for a while now.  EDDI says the name correctly except when jumping to a new system and then scooping.  EDDI reports on the fuel capacity.  There seem to be several responses.  Some don't mention the name of the ship but a couple of them start with the name and instead of saying the name EDDI spells the name.  The responses I've come across are, "(ship name spelled) is now at maximum fuel capacity" and "(ship name spelled) is at 100% fuel capacity, Commander."  When the name is spelled it is the complete name ending with "eye eye" for the roman numeral II.  Thank you again for trying to figure this out.

**Comment by Tkael** [comment]
Ok. I think I have the solution. In the `Fuel check` script, look for `{P(ShipName())}'s` and replace it with `{ShipName()}'s`. The phonetic pronunciation from P() converts the name from saying "galactic explorer two" to "galactic explorer i i".

**Comment by flamberth** [comment]
It worked.  Thanks!!
