### ISSUE TITLE
Expose FSDJump Faction summary information for BGS players

### ISSUE THREAD

**Issue by wentbackward** [EDCD/EDDI#511]
This is a new feature request. The FSDJump event has been updated to include a faction status summary of the entire system. The current ways to obtain this data are to have something (EDDI/EDMC) update EDDB and look for it on a website or head to a station and get the summary from galnet (usually the top article).

This is very useful data for BGS players. It would be great to expose this to EDDI so we can report on it in various ways. It's the "Factions" dictionary item below. 

I can see from the EDDI code it may be difficult to expose an array or dict to VA, so could not easily figure out how this could be done.

```
{
    "timestamp": "2018-03-23T14:07:44Z",
    "event": "FSDJump",
    "StarSystem": "Ye'kua'gsa",
    "SystemAddress": 20462700602817,
    "StarPos": [36.53125, -23.65625, 58.46875],
    "SystemAllegiance": "Federation",
    "SystemEconomy": "$economy_Colony;",
    "SystemEconomy_Localised": "Colony",
    "SystemSecondEconomy": "$economy_Extraction;",
    "SystemSecondEconomy_Localised": "Extraction",
    "SystemGovernment": "$government_Confederacy;",
    "SystemGovernment_Localised": "Confederacy",
    "SystemSecurity": "$SYSTEM_SECURITY_low;",
    "SystemSecurity_Localised": "Low Security",
    "Population": 2463,
    "JumpDist": 23.649,
    "FuelUsed": 10.131948,
    "FuelLevel": 29.635181,

    // -------------- Factions section
    "Factions": [{
        "Name": "Pilots Federation Local Branch",
        "FactionState": "None",
        "Government": "Democracy",
        "Influence": 0.000000,
        "Allegiance": "PilotsFederation"
    }, {
        "Name": "Social Savii Confederacy",
        "FactionState": "None",
        "Government": "Confederacy",
        "Influence": 0.428147,
        "Allegiance": "Federation",
        "PendingStates": [{
            "State": "Boom",
            "Trend": 1
        }, {
            "State": "Expansion",
            "Trend": 0
        }]
    }, {
        "Name": "Social Mitlhou Wa Labour",
        "FactionState": "Boom",
        "Government": "Democracy",
        "Influence": 0.305253,
        "Allegiance": "Federation"
    }, {
        "Name": "Union of Ye'kua'gsa Confederation",
        "FactionState": "Boom",
        "Government": "Confederacy",
        "Influence": 0.162537,
        "Allegiance": "Federation"
    }, {
        "Name": "Ye'kua'gsa Jet Dragons",
        "FactionState": "None",
        "Government": "Anarchy",
        "Influence": 0.009911,
        "Allegiance": "Independent"
    }, {
        "Name": "Sungai Blue Legal Industry",
        "FactionState": "Boom",
        "Government": "Corporate",
        "Influence": 0.009911,
        "Allegiance": "Federation",
        "PendingStates": [{
            "State": "Retreat",
            "Trend": 0
        }]
    }, {
        "Name": "Luan Yun Di Dominion",
        "FactionState": "Boom",
        "Government": "Dictatorship",
        "Influence": 0.084242,
        "Allegiance": "Empire"
    }],
    "SystemFaction": "Social Savii Confederacy"
}
```

**Comment by Tkael** [comment]
How would you plan to access and process this data? Sending it through EDDN allows the aggregators you mentioned (EDDN, EDDB, EliteBGS) to collect data from multiple sources as they travel through the galaxy and present that data through a UI. What added value do you anticipate from accessing the data you collect directly in EDDI?

**Comment by wentbackward** [comment]
We tend to jump from one system to another after the tick, triggering the update and yes true we then use the other tools. It would be nice to be able to get an immediate, without having to exit ED. I imagine we'd have a filter in the script to only report the factions of interest. This would speed things up for us.

In addition this need is amplified as there is a particular bug in ED (we call it the caching bug) where the faction status is not updated at all but instead ED Client reports the data from the previous day (therefore no or an incorrect update goes to EDDN). So as we're jumping between the interesting systems, we'll know if the problem is occurring.

**Comment by wentbackward** [comment]
Ah, we would also want to log this data, probably as a CSV so we can quickly copy and paste the data to excel for example and not have to hit those other sites. But this is a minor point compared to the above.

**Comment by wentbackward** [comment]
Hey mate, yes indeed it is and we spend a lot of effort opening logs, searching for FSDJump events, copying json and then reformatting it and pasting into s/sheets, discord chats etc. I had started building something on top of EDMC to expose the data on a UI, but most of us are not using that but using EDDI.

The EDDP monitor helps when everything is working after the round trip to EDDN (although one of our guys was having trouble with it - a different problem we need to work through). Mostly it's fine but at times the updates take a while and combined with the caching issue we end up going to the source data.

**Comment by Tkael** [comment]
In most cases the data passes through EDDN almost instantly and is available via ROSS within minutes. And whatever analysis of the data that your player group performs may not be instant either (you'll probably still need to set up something that can digest the data). I'm not sure it's worth the effort when Inara is already able to provide data like https://inara.cz/galaxy-minorfaction/15221/ within what is (to me at least) a reasonable span of time. But I'm not really a BGS guy and I understand that others are more involved in this aspect of the game. I'll think about it.

By the way, if you just want the raw unparsed journal events separated to a file, EDDI's already most of the way to being able to do that. {event.raw} will give you the raw string from the journal so we'd just need to give you a way to write that string to a file of your choice. Something like `{WriteToFile("FsdJumpData", event.raw)}` might be possible (and might be something that other players could find a use for too).
