### ISSUE TITLE
EDDI claims I'm carrying stolen cargo...when my holds are barren.

### ISSUE THREAD

**Issue by darth-crunchus** [EDCD/EDDI#512]
EDDI version: 3.0.1 b1

I'm getting an issue in my Type-9, where I had taken a wing source-the-commodity that required me to source a bunch of cargo through piracy, which I wasn't aware of at the time, until EDDI announced that I could "fence my stolen Emergency Power Cells", after which I promptly abandoned said mission.  Every station I've gone to since then, even after I've completed all the missions I had, every time I dock, EDDI tells me, "Reminder: you are carrying stolen cargo", which I'm actually not carrying.  I've tried everything short of re-installing EDDI, and it has changed nothing.  I don't seem to get this issue on any other ship I have, but then again, the only ship I do trading in is my Type-9.

There are no steps to reproduce this, as this is the first time I'm experiencing such an issue.

**Comment by Tkael** [comment]
Have you tried restarting logging to main menu and logging back in (with EDDI running)? That should generate an event that will clear and refresh your cargo monitor.
There are some deficiencies in the data reported by FDev that we are working around in this area, but @Hoodathunk is working on an update for our next release that should significantly improve tracking in this area.

**Comment by Tkael** [comment]
I'm going to close this issue and direct you to #454 if you need more support on this issue.
