### ISSUE TITLE
How to stop EDDI from reading transmission intercepts and information

### ISSUE THREAD

**Issue by RamonSpiteri** [EDCD/EDDI#528]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Customize the EDDP responder according to your preferences. You can disable the plugin or adjust the settings within the plugin.
