### ISSUE TITLE
event.volcanism.type, amount, composition does not work

### ISSUE THREAD

**Issue by Smior** [EDCD/EDDI#538]
EDDI standalone 3.0.1 b2

## Steps to reproduce

During the body scanned event my output from 
{if event.volcanism:
        You can find {event.volcanism.amount} {event.volcanism.composition} {event.volcanism.type} on the surface.
}
is "You can find on the surface."

I expected "You can find major silicate geysers on the surface." or similar

no further investigations done.

**Comment by Tkael** [comment]
It sounds like you may have scanned a body which has no volcanism. Please identify the system you were in and the body you were scanning (so that we can inspect the source data and replicate this issue).

**Comment by Tkael** [comment]
Your script should check for the presence of volcanism before it speaks.

**Comment by Tkael** [comment]
Confirmed, but only when attempting to access data from the event directly (data using the ReportBody() function was ok). Pull request submitted with a fix. 
Thanks for reporting, commander. :-)

**Comment by richardbuckle** [comment]
PR merged.
