### ISSUE TITLE
3.0.1-b2 takes a long time to start

### ISSUE THREAD

**Issue by DaftMav** [EDCD/EDDI#539]
## EDDI version in which issue found
3.0.1-b2 Standalone

## Observed
After updating from 3.0.1-b1 and starting the program again the process just keeps running in the background and the program/window appears about a minute or two later. Looking at the log it seems to go through a long list of "Reporting unique data" with tons of resources, does a few per second and it seems to go through the list twice before the EDDI window/program finally shows up. This happens on every start.

## Investigation
- Downloaded installer from github manually as well and reinstalled, same result.
- Reinstalled 3.0.1-b1 to check and it starts instantly and works as normal again.
- Looked at the log of 3.0.1-b2 in %APPDATA%/EDDI, some of the lines look like errors/warnings:

```
Logging:Report [I] Reporting unique data, anonymous ID : Unknown name hydrogenfuel in resource EddiDataDefinitions.Properties.CommoditiesSystem.Collections.Generic.Dictionary`2[System.String,System.Object] 
Logging:Report [I] Reporting unique data, anonymous ID : Unknown name hydrogenperoxide in resource EddiDataDefinitions.Properties.CommoditiesSystem.Collections.Generic.Dictionary`2[System.String,System.Object] 
Logging:Report [I] Reporting unique data, anonymous ID : Unknown name liquidoxygen in resource EddiDataDefinitions.Properties.CommoditiesSystem.Collections.Generic.Dictionary`2[System.String,System.Object] 
...etc
```

These appear to go at a few lines per second, but it's a long list and it goes through it twice. I could put the entire log somewhere if needed but I think the list of resources it goes through is probably recognizable enough. From the timestamps it was clear this is the stuff that takes about a minute or two to complete.

**Comment by Tkael** [comment]
Hmm... ere you docked at a station at the time?

**Comment by Tkael** [comment]
A casing issue perhaps?

**Comment by DaftMav** [comment]
Ah... of all the things I hadn't done was boot up Elite. Apparently it needed Elite running to figure things out. I thought these tools only read ED's log files and I always start EDDI and EDDiscovery before I actually boot up the game and never had any issues doing so before.

Logfile is clear too now, only shows one line for tg_shipsystemdata but I see there's a pull request for that one already so... This can be closed, sorry.
