### ISSUE TITLE
Speech Responder - Missing 'reportbody.chromaticity' function for Star Report

### ISSUE THREAD

**Issue by sbrenna** [EDCD/EDDI#549]
## EDDI version in which issue found
3.0.1-b2

## Steps to reproduce

1. Jump to am unknown system and scan the main star

## Expected
As for the code of "Star report":
 `{if mainsequence = 1:`

 `{Occasionally(2,"As you can see, it emits a {reportbody.chromaticity} light.")}`

usually EDDI says: _As you can see, it emits a <type of color> light_

## Observed
EDDI says: "_As you can see, it emits a  light_", without `reportbody.chromaticity` output. 

## Investigation
I can't find `{reportbody.chromaticity}` function in the code of `Star report` script anymore.

**Comment by Tkael** [comment]
`{reportbody.chromaticity}` is reported only some of the time. The default script includes:
```        {Occasionally(2,"As you can see, it emits a {reportbody.chromaticity} light.")}```

**Comment by Tkael** [comment]
Fixed, I think. :-)

**Comment by richardbuckle** [comment]
PR merged
