### ISSUE TITLE
EDDB/Ross warning about ignored properties 

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#550]
## EDDI version in which issue found
3.0.1-b2

## Steps to reproduce

Search ross fro warnings generated by submissions from EDDI, e.g. https://ross.eddb.io/eddn/log/51038157

## Expected
No warnings

## Observed
Warnings are generated for ignored properties `BodyID`, `Parents`, and `ScanType`.

## Investigation
We need to proceed carefully here in case those properties are required by other services.

**Comment by Tkael** [comment]
I don't think that these ignored properties are any way harmful to EDDN?

**Comment by AnthorNet** [comment]
They are part of the message and other listeners are using them.

**Comment by Tkael** [comment]
If other listeners (like EDSM) are using them then I think these need to stay. I'm not sure why Ross flags them with warnings, other than perhaps that Ross hasn't fully implemented them yet.

**Comment by AnthorNet** [comment]
Yes they need to stay, because we use them, and we also have request them to be part of the journal.
May be ROSS will update for them, but I'm not really sure.

**Comment by Tkael** [comment]
@richardbuckle I think we have enough info to warrant closing this as an issue now. Closing.
