### ISSUE TITLE
EDDI Core: Pause() function does not currently work with some 3rd party voices?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#56]

**Comment by Syrrianyl** [comment]
I don't know if it is a bug. On what I look, the Pause(800) function send a _<break time="800ms" />_ a Speech Synthesis Markup Language (SSML) function for the TTS in windows. If the TTS dont include SSML, it will not understand the ask of pause. (find here : [https://msdn.microsoft.com/en-us/library/jj127898.aspx](https://msdn.microsoft.com/en-us/library/jj127898.aspx))
To make Pause avable for all TTS, we must think in a total other way to make...

The **Play** function use the same SSML. DId the one who have proplem with Pause have also with Plays?

**Comment by Tkael** [comment]
Yes, I apparently am having problems with both of these functions (even after selecting a different voice - to make this function not work, it may be enough simply have certain voice(s) installed? (I normally use Ivona Amy, Windows 10 x64)

**Comment by Tkael** [comment]
Ivona Amy claims to support ssml.

**Comment by Syrrianyl** [comment]
When i look on the log [ {Log(Pause(500))} ] the result is <break time = "500ms" />, So I go on Ivona site to try Amy voice online, with a text where I add the log result

```
Hello there, my name is Amy. I am one of the IVONA voices. I will read <break time = "500ms" /> 
anything you want. Enter any text here and click Play.
```

The break time command don't work, but, like it is online, I don't know if the test is relevant.

what you can do is to try the command <break time = "500ms" /> in one other way than EDDI to look if it work with your voice.

**Comment by Tkael** [comment]
Ivona claims to conform: http://developer.ivona.com/en/ttsresources/ssml/ssml.html
As you say though, the online demos don't seem to show it working. 
As I've already said, the other native voices installed on my system do not respect the ssml flag either. 

This has been a complaint from a small number of users for a long time and we may eventually want to look for an alternate implementation, but it is less urgent than other changes that need to be made.

**Comment by Tkael** [comment]
SSML confirmed as working with Ivona Amy is Minispeech.

**Comment by Tkael** [comment]
After additional research and study of the code, it would seem this is linked to the 'Enable phonetic speech' option in EDDI. This function works via SSML tags, which are disabled phonetic speech is disabled.
