### ISSUE TITLE
Window opening very slow/late

### ISSUE THREAD

**Issue by deserteagle** [EDCD/EDDI#560]
## EDDI version in which issue found
3.0.1-b2 (standalone and VA Plugin)

## Steps to reproduce

1. Use Windows 10 with the latest update (hit me hard and unprepared on may 15th 2018)
2. Open EDDI Standalone or via voice attack config command

## Expected
EDDI window opens in reasonable time (realtime)

## Observed
it takes more than one minute until the window pops up, although the process itself stats immediately

## Investigation
worked fine in 3.0.0, eddi.log does not tell me too much, but i suspect tons of lines like

2018-05-15T21:29:16 Logging:Report [W] Unable to report message "Unknown name advancedmedicines in resource EddiDataDefinitions.Properties.Commodities". Invalid data type System.Collections.Generic.Dictionary`2[System.String,System.Object] 

todays log (multiple starts) attached.

[eddi - Copy.log](https://github.com/EDCD/EDDI/files/2006928/eddi.-.Copy.log)

**Comment by Tkael** [comment]
Thanks for reporting. This is a duplicate of the same issue as #539 and we have been investigating.

**Comment by Tkael** [comment]
Ref. #544 and branch https://github.com/EDCD/EDDI/tree/review/539-540-commodity-definition-crash-fix_(unfinished)

**Comment by richardbuckle** [comment]
PR merged
