### ISSUE TITLE
Ship roles get messed up

### ISSUE THREAD

**Issue by deserteagle** [EDCD/EDDI#561]
## EDDI version in which issue found
3.0.1-b2 (standalone and VA Plugin)

## Steps to reproduce

1. Edit ship list and set roles (or upgrade from 3.0.0 with already set rules)
2. close EDDI and start again

## Expected
Ship roles are still as set up

## Observed
all ships have the same role

## Investigation
worked in 3.0.0

**Comment by Tkael** [comment]
I haven't been able to replicate this issue (opening and changing files both in VA and as standalone).
This might be a glitch in your local ship config files?

Please navigate to %APPDATA%/EDDI and delete or rename shipmonitor.json (with both VA and EDDI standalone closed). Once you re-open EDDI, a new shipmonitor.json will be generated. With the new shipmonitor.json, are ship roles still getting messed up?

**Comment by Tkael** [comment]
Closing since I've been unable to replicate this. Please let me know if my earlier recommendation didn't resolve the issue.
