### ISSUE TITLE
Ship Name (Phonetic) Preview does not work

### ISSUE THREAD

**Issue by deserteagle** [EDCD/EDDI#562]
## EDDI version in which issue found
3.0.1-b2 (standalone and VA Plugin)

## Steps to reproduce

1. Set a phonetic name
2. click "Hear it!" button

## Expected
audio output of "{phonetic name} stands ready"

## Observed
sad silence, but works when no phonetics are used

## Investigation
worked in 3.0.0 but i suspect major problems with windows update in combination with TTS (messed up all installed MS-voices) so i will downgrade to 3.0.0 and check again

**Comment by Tkael** [comment]
This feature is rather sensitive to the voice you use (not all voices handle the same IPA equally well). Try this with a variety of voices and report your findings?

**Comment by richardbuckle** [comment]
PR Merged

**Comment by richardbuckle** [comment]
Reopening. It is not falling back to the plain text name if the phonetic name is blank.

**Comment by richardbuckle** [comment]
Fixed as best we can for now.
