### ISSUE TITLE
Ship name readout inconsistent

### ISSUE THREAD

**Issue by Djuwanna** [EDCD/EDDI#579]
## EDDI version in which issue found
EDDI 3.0.1-b3 with VoiceAttack 1.7

## Steps to reproduce

I have a ship named the "USS Katybird".  When I'm jumping to a system, it says the name as "USS Katybird" during the jump, as one would expect.  When it finishes scooping fuel however (for example), it says the name as "USS Kaatabird" (flat "aah" sound instead of hard "ay" in the first syllable, and flat "aah" sound instead of hard "e" sound in the second syllable)

## Expected
Expected consistent name pronunciation, right or wrong.

## Observed
Sometimes it gets it right, sometimes it doesn't.

## Investigation
This is a new ship so I haven't tested with prior versions.

**Comment by Tkael** [comment]
Please review the applicable scripts. Does one use `{ShipName()}` while the other uses `{P(ShipName())}`? If so, which one matches your preferred pronunciation?

**Comment by Djuwanna** [comment]
Yes, the FSD Engaged uses {ShipName()} while the Fuel Check uses {P(ShipName())}.  The preferred pronunciation comes from the former.

...John

________________________________

**Comment by richardbuckle** [comment]
PR merged. Fix will be in 3.0.1-b4. Custom scripts might require adjustment.

**Comment by Djuwanna** [comment]
Aaaand...this morning it's working perfectly.  FML.  Nevermind :-)

**Comment by Djuwanna** [comment]
Ok, same session - same ship, nothing changed.  I'm actually just running back and forth between Muang and Fujin on Fujin Tea runs.  It's happening on-and-off.  I can't find a rhyme or reason.  Sometimes it pronounces correctly on the Fuel Check script, sometimes not.  Very odd.

**Comment by Djuwanna** [comment]
Hey guys!

Ok, with the latest release of EDDI, I noticed that this mispronunciation is still happening...and after some playing around, I've determined that frankly, I don't think it's anything you can do anything about.

Do this:  Run "USS Katybird" through the speech engine - it reads out as "USS KATIEBIRD" (for lack of the correct phonetic translation) - or, in other words, it's pronounced correctly.

Now do this:  Add an "apostrophe s" to the name - "USS Katybird's" - as the fuel readout script does.
Now it's pronounced "USS KATABIRD'S".  Soft "a" sound.

I think it's the speech engine itself and how it decides to pronounce the name with vs. without the 's at the end.  I found that if I respell the name of the ship as "KatIE" instead of "KatY", it pronounces correctly.

I should think a speech engine rewrite is well outside scope ;-)  I just thought you'd like to know anyway.

Thanks for checking into this though!!!

Best,

...DJ

**Comment by richardbuckle** [comment]
Some of the software implementation resides in the OS speech engine but an awful lot of it resides in the selected voice – voices are software as much as they are data. And it has to be said they can vary greatly when given unusual words to pronounce. As you have found, it’s not always possible to get a perfect solution.
