### ISSUE TITLE
New StartWithVowel function for more natural speech

### ISSUE THREAD

**Issue by Syrrianyl** [EDCD/EDDI#58]
In many country, there is difference if words starts with vowel or not, like for in english, with "_Encrypted Correspondence_" we will say "**an** _Encrypted Correspondence_" more than "**a** _Encrypted Correspondence_"
For that i work in a boolean function names StartWithVowel in ScriptResolver.cs like this

```
            store["StartWithVowel"] = new NativeFunction((values) =>
            {
                string Entree = values[0].AsString;
                if (Entree == "")
                { return ""; }
				
				char[] vowels = { 'a', 'à', 'â', 'ä', 'e', 'ê', 'é', 'è', 'ë', 'i', 'î', 'ï', 'o', 'ô', 'ö', 'u', 'ù', 'û', 'ü', 'œ', 'y'};
				char firstCharacter = Entree.ToLower().ToCharArray().ElementAt(0);
				Boolean result = vowels.Contains(firstCharacter);
                
				return result;

            }, 1);
```

The use in EDDI script can be

{if StartWithVowel(Value): an |else: a } {Value}
#

**Comment by Tkael** [comment]
You can pretty easily create a script to do the same thing in Cottle without using a built-in function, but I suppose it would reduce the need to keep repeating similar code in many scripts. Maybe we ought to have a few more of these. :-)

**Comment by Tkael** [comment]
Confirmed this works & added it to development build patch-1. :-)
