### ISSUE TITLE
Eddi 3.0.1 b3 radius and mass value "0"

### ISSUE THREAD

**Issue by hermattila** [EDCD/EDDI#580]
Installed EDDI 3.0.1 b3 for test.In the body report script there are no report coming thru about {reportbody.radius} and {reportbody earthmass}
Used the following code
{If reportbody.radius:
This planet has a radius of {reportbody.radius} kilometers and}
{If reportbody.earthmass:
This planet has a {reportbody.earthmass} of earth mass.}
However both output "0"

**Comment by Tkael** [comment]
Which body were you scanning? Are `event.radius` and `event.earthmass` set?

**Comment by hermattila** [comment]
Yeah.well it is a same script i was using prior the update.im at work ATM so i cant tell you but the script is in the closed issues about rotation period in 3.0.1 b2.
Any planet basiclly.

**Comment by hermattila** [comment]
Yeah and yeah.im running a test right now for some reason it is work in your script but skipping in mine.So means it is working just for some reason not whit mine.pls close the issue and i trying to work out why as it was working prior the update.

**Comment by hermattila** [comment]
Ok so i was wrong.i tested your script b4 started elite and guess what,it
was working till i launched ED and after that i wasnt getting any value at
all for event.radius and event.earthmass.wierd one.Have you tried actually
in live ED as test fine till you launch the game

Brian Wilson <notifications@github.com> ezt írta (időpont: 2018. máj. 23.,
Sze 2:23):
