### ISSUE TITLE
"(Ship name)'s fuel tanks now at 101% capacity"

### ISSUE THREAD

**Issue by Djuwanna** [EDCD/EDDI#581]
## EDDI version in which issue found
EDDI v.3.0.1-b3 with VoiceAttack v1.7

## Steps to reproduce

Top off fuel tanks at station

## Expected
Expected 100% 

## Observed
Incorrect fuel level stated

## Investigation
None performed - just noticed it for the first time.

**Comment by Djuwanna** [comment]
Apparently the Swedish Vikings are hiring sub-par fuel technicians at Baliunas Hub. :-)

**Comment by Tkael** [comment]
It sounds like EDDI may be confused about which ship you are actually in (or may have been - it should self correct when EDDI sees the applicable events). Did you switch ships while EDDI was not running or do anything similar?

Can you run some tests? What are the values that you get for the following variables? What values do you expect?
```
- `ship.manufacturer` the manufacturer of the ship (Lakon, Core Dynamics etc)
- `ship.model` the model of the ship (Cobra Mk III, Fer-de-Lance etc)
- `ship.name` the name of the ship
```

**Comment by richardbuckle** [comment]
I've just had this in my DBX. No ship changes in the session. In my case it said 102%.

**Comment by richardbuckle** [comment]
OK I just refuelled at a station and got "Attention: Little Bird's Fuel levels are now below 25%"

Something is definitely wrong.

**Comment by Tkael** [comment]
@richardbuckle What do you see in ShipMonitor.json? Are values recorded correctly?

**Comment by richardbuckle** [comment]
Yup:
```json
      "fueltankcapacity": 32.0,
      "fueltanktotalcapacity": 32.0,
```

**Comment by Tkael** [comment]
Had this this evening, but it was my own fault for starting EDDI while Elite was already running and then not refreshing the data in my shipyard by swapping ships, making a change in outfitting, or similar.

**Comment by richardbuckle** [comment]
Here's an example: I docked and did refuel all.

Journal:
```
{"timestamp":"2018-06-03T21:10:05Z","event":"RefuelAll","Cost":167,"Amount":3.320129}
```

My customised script:
```
...
{set maxfuel to state.eddi_fuelcheck_maxfuel}
{set fuelremaining to state.eddi_context_fuel_remaining}
{set maxjump to fuelremaining/maxfuel}
{fuelremaining} tons remaining. {ship.fueltanktotalcapacity} tons capacity.
{set currentfuel to round(fuelremaining / ship.fueltanktotalcapacity * 100, 0)}
{set shipsfuel to:
   {Occasionally(2, "{ShipName()}'s" )} Fuel
   {OneOf("levels", "tanks", "reserves")} {Occasionally(2, "are")} {Occasionally(2, "now")}
}
...
```

Output:
```
 3.320129 tons remaining. 32.0 tons capacity. Attention: Usually Harmless's Fuel tanks are below 25%, commander
```

It has taken the 3.3 tons I bought as the total amount.

**Comment by Tkael** [comment]
I think I've got it. `Ship refueled` is setting `eddi_context_fuel_remaining` equal to event.total, but per the `Ship refueled` event description `event.total` is `only available if the source is Scoop`. Consequently, when refueling at a station event.total is null and so is `eddi_context_fuel_remaining`.

**Comment by richardbuckle** [comment]
Good sleuthing. Could you take charge from here on please?

**Comment by richardbuckle** [comment]
Merged
