### ISSUE TITLE
3.0.1 b3 event.radius and event.earthmass messed up

### ISSUE THREAD

**Issue by hermattila** [EDCD/EDDI#588]
So i closed my previous report based on "test" button reported and compared the radius and mass of the planets but once i start elite there are no report for these values either in english or any localized version.

Im using 3.0.1 b3 upgraded from 3.0.1 b2

Personality used for it Astra Ext.

Expected 
It has a radius of "xxxx" km less then "xxx" of earthsize and it has "xxx" mass of earth

Reproduce
Start the game and try scanning any planet whit any personality has compare function.

**Comment by richardbuckle** [comment]
Yes I too verified this last night. Fix will be in 3.0.1-b4 later this evening.

**Comment by hermattila** [comment]
Ok thx.Looking forward to it.

Richard Buckle <notifications@github.com> ezt írta (időpont: 2018. máj.
24., Csü 18:40):
