### ISSUE TITLE
no sound when ttesing or in game

### ISSUE THREAD

**Issue by Stompmaster** [EDCD/EDDI#593]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

ok so I am hopeless at this stuff. I have got new version of eedi do I now need to download a voice attack program and link to eedi?

**Comment by Stompmaster** [comment]
have got new version of eddi but no voice, sound, cant even say ship name in the test it section. do I now need to down load a voice attack program and link to eddi?

**Comment by Tkael** [comment]
VoiceAttack is not required.
Does audio play in other applications? If not, there may be an audio driver issue.
Verify that your system volume is not muted and that the volume setting on the Text-to-Speech tab is not zero.

**Comment by Sekotser** [comment]
similar issue. Running 3.0.1-b3, have tried it with voice attack and as a stand alone, but not getting any voice messages/updates at all, whilst playing ED.  The test voices play ok, and plugins are all checked. EDDI downloaded to apps folder of voice attack.  EDDI recognises all my ships, and will export them to EDShipyard, and also 'material monitor' is working, although I have not checked its accuracy

**Comment by Stompmaster** [comment]
yes audio works in all other applications, Yes i have pluggins enabled, volume set yo 60...then changed to 100 still no sound. i can get exports ok, cargo updated with login everything else ok except no sound.

**Comment by Stompmaster** [comment]
Also seems that ship names spoken don't get saved on restart of the program. i type them in and close and restart but they are gone?

**Comment by Sekotser** [comment]
Yes, I do... I am running 6 HCS voicepacks too, and they work fine.  When I
load up voice attack, I get this message on the voice attack display screen
'23:18:17 - Plugin 'EDDI 3.0.1-b3' initialized.'

**Comment by Tkael** [comment]
Does switching to a different TTS voice make a difference?

**Comment by Stompmaster** [comment]
Tried this as well...still no luck

**Comment by Sekotser** [comment]
A strange thing has just occured.  I loaded EDDI, inorder to change the TTS
voice, and it appeared to be working, as it was telling me that an upgrade
was available, so I installed the upgrade to (b4), started ED, and no
speech thereafter.  I closed everything down and changed TTS voice,
reloaded ED, and still no speech

**Comment by Tkael** [comment]
Hmm. We did just release b4. 
EDDI should be using the same settings for both normal TTS and the upgrade notification.

**Comment by Tkael** [comment]
Try disabling phonetic speech? And sharing copies of your logs (with recent attempts to test voices in EDDI)

**Comment by Stompmaster** [comment]
Ok i have got it working now. i downloaded voicepack called NCH software /verbose.
Then dragged EDDI folder into the verbose folder.
Works like a charm now.
thanks guys...anyone else with problem try what i did.

**Comment by Tkael** [comment]
I'm glad you found a solution. I'm not familiar with that software though.
@Sekotser Any updates? Have you tried disabliing phonetic speech or capturing logs?

**Comment by Diettinger** [comment]
I've found that setting your system sound to 5.1 or 7.1 Surround causes EDDI b4 sound to be muted.  You can see that it is playing the text in the Volume Mixer when testing a response but no sound emits from the speakers.  In Stereo or Quadraphonic settings the text to speech works fine.

**Comment by Sekotser** [comment]
Yes I did as you suggested, and still no good.  Earlier on today, I
uninstalled/reinstalled it, and still the same, I have a second laptop with
ED and VA installed, and have tried downloading EDDI on that machine, still
no luck, although there is something wrong with FD servers as they are not
responding to the Frontier/API request.

**Comment by Tkael** [comment]
Are you saying that you have two separate installations on different pcs with this same issue?
If so, can you tell us more about your setup? This is not a common issue.

**Comment by Stompmaster** [comment]
i have 2 folders , one under elite with voice pack not working and the other under NCH which is working

**Comment by Tkael** [comment]
Neither of these is a normal install location. By any chance, @Sekotser, have you moved your Saved Games folder to a non-standard location? EDDI may behave as you're describing if EDDI is unable to locate you're journal files.

**Comment by Sekotser** [comment]
What is it you are asking about my set up, sorry been out all day,
daughters wedding ....  if it's me you're asking about plugind, yes plugins
are enabled, and I have HCS voicepacks running, and they work well - ignore
me a lot of the time - but works well

**Comment by Tkael** [comment]
@Sekotser Congrats on your daughter's wedding. :-) 
I'm sorry, but I still don't think I've received the information I need to help with your TTS issues in-game. 
Right now, I'm wondering if you've moved your `Saved Games` folder to a non-standard location. Make sure that journal files are being written to `[Your `Saved Games` folder]\Frontier Developments\Elite Dangerous`... this is where EDDI expects to find player journal entries.

**Comment by Sekotser** [comment]
Hiya,
The saved games folder is where it should be and the journal files are in
the correct place.   I deleted everything to do with EDDI, and I have just
uploaded EDDI 3.0.0, and it's working perfectly.  Thanks for all your help
and support.

Roger

**Comment by rafikiblues** [comment]
I do have the same problem.
I use EDDI 3.4 - uninstalled and used different version. Same problem.
Sound works in all other Apps. Using Windows 10. Sound mixer is up in volume. Tried "disable phonetic speech" trick as well, no success.

It seems that maybe Windows 10 TTS in general has problems? I do not know. Anyone any help? EDDI does not talk to me :(

**Comment by Tkael** [comment]
Have you tried using a different voice?
Have you checked the speech volume slider in EDDI's Text-to-Speech window?

**Comment by rafikiblues** [comment]
Tried all 4 optional voices (incl. TTS default). Speech volume in EDDI is on 100.

**Comment by Tkael** [comment]
When the UI is open to the `Speech Responder` tab, please check the following:
1. Make sure that the Speech Responder plugin is enabled.
2. There is a checkbox that reads "Do not speak aloud when text is written to the file above. Is this checked or unchecked?
Page over to the `Text-to-Speech` tab. Try disabling phonetic speech?

**Comment by rafikiblues** [comment]
1. Speech Responder plugin is enabled
2. It is unchecked - tried now checked and unchecked. no effect.
3. Diabling phonetic speech has no effect as well.

Do you know how I can test the general TTS of Windows 10? Maybe it is a Windows issue?!
Thanks so far for your help.

**Comment by Tkael** [comment]
You can preview your Windows TTS voice using the Windows settings page. Here's a basic how-to link to get you to the right location. https://www.isunshare.com/windows-10/change-voice-and-speed-of-text-to-speech-in-windows-10.html

**Comment by rafikiblues** [comment]
Thanks,
when I try to test the Windows Voice I dont hear anything. I set Audio settings on Stereo, I checked Audio Output. Everything ok. Also scaned the system with cmd command: "sfc /scannow".

So it is a Windows issue I cannot solve :(

**Comment by Tkael** [comment]
I hope you can friend that can help you troubleshoot the issue. Good luck!

**Comment by rafikiblues** [comment]
Thanks

**Comment by rafikiblues** [comment]
Found a solution. MAybe someone else is interested, while having the same problem.
I run a Windows 10 "N" Version. This comes withouth Media Player and other Media Apps.
Apperently also withouth TTS support.

After upgrading to normal version (for free on Microsoft Homepage) TTS in Windows and then also in EDDI works!

**Comment by Tkael** [comment]
Thanks for the follow up... I'm glad you were able to get it sorted out!

**Comment by rafikiblues** [comment]
After upgrading to EDDI 3.4.1 - same issue again, no sound :(

**Comment by Tkael** [comment]
This still seems like it is a unique issue for your local pc. I'm not sure how to help.
