### ISSUE TITLE
EDDI - VA not working

### ISSUE THREAD

**Issue by SpaceTerp** [EDCD/EDDI#598]
## EDDI version 3.0.1-b4 (happens with other versions as well)
Having trouble getting EDDI to respond while using VA
Upon booting up VA i get the following *EDDI has not been launched prior to VA

Plugin support enabled.
Unable to full initialize EDDI. Some functions may not work.
Plugin 'EDDI 3.0.1-b4' initialized.

No communication seems to exist. Using 'Configure EDDI' does not work

**Comment by Tkael** [comment]
Did you already have EDDI open as a standalone application before you launched VA? Since VA creates a new instance of the application, you need to close EDDI's standalone app before you can launch a new instance through VA.
