### ISSUE TITLE
EDDI Core: List() function?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#60]
Add a list function to convert information stored in a list variable to natural speech?
Essentially, it would replace this cottle script:
```
    {set cur to 0}
    {while cur < len(systemsrepaired):
        {if cur = 0:
        |elif cur < len(systemsrepaired) - 1:
            , 
        |else:
            and
        }
        {systemsrepaired[cur]}
        {set cur to cur + 1}
    }
```
With this: 
`{List(systemsrepaired)}`
and would provide output like the following (depending on the number of items in the list):
```
{systemsrepaired[1]}
{systemsrepaired[1]} and {systemsrepaired[2]}
{systemsrepaired[1]}, {systemsrepaired[2]}, and {systemsrepaired[3]}
etc.
```

**Comment by Syrrianyl** [comment]
I take a look of that, can be useful (more easy to understand and write scripts for final user) but may be useless each time that we want a list of two values (like materials with percentage of each in body)

**Comment by Tkael** [comment]
I've considered that. it might still be possible with the correct approach. For example, List(material[] at percentage[], 3) may be possible to list as: Carbon at 10%, Selenium at 6%, and Sulfer at 3%. ('[]' would designate Cottle lists in the string, the number '3' would indicate the number of iterations). This would be more complex to code.

**Comment by richardbuckle** [comment]
That function is usually called zip().

**Comment by StivlWrith** [comment]
I have some sort of solution, it is not a pure programmer one, more handyman.

```
// list an existing array
            store["List"] = new NativeFunction((values) =>
            {
                string baseLoop;
                string dataLoop; 

                string createLoop;

                if (values.Count == 1)
                {
                    baseLoop = values[0].AsString;
                    createLoop = "{set cur to 0}{while cur < len(" + baseLoop + "):{if cur = 0:|elif cur < len (" + baseLoop + ") - 1: , |else: and }  {" + baseLoop + "[cur]} {set cur to cur + 1}}";
                }
                else
                {
                    baseLoop = values[0].AsString;
                    dataLoop = values[1].AsString;
                    createLoop = "{set cur to 0}{while cur < len(" + baseLoop + "):{if cur = 0:|elif cur < len (" + baseLoop + ") - 1: , |else: and }  {" + baseLoop + "[cur]." + dataLoop + "} {set cur to cur + 1}}";
                }
                return new ScriptResolver(scripts).resolveScript(createLoop, store, false);
            }, 1, 2);
```

**Comment by Tkael** [comment]
PR #215 submitted to create a simple list function that follows the definition I set out in the OP of this issue.
