### ISSUE TITLE
Ship Cargo Capacity does not include Corrosion Proof Cargo Rack(s)

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#601]
## EDDI version in which issue found
v3.0.1-b4
running under Voice Attack or standalone

## Steps to reproduce

1. Equip ship with any Corrosion Proof Cargo Rack
2. Check _ship.cargocapacity_ variable.

## Expected
ship.cargocapacity = total cargo space
## Observed
ship.cargocapacity = total cargo space less Corrosion Proof Cargo Rack(s) Capacity
## Investigation
Worked correctly prior to localization

**Comment by Hoodathunk** [comment]
Thanks for the report, will get right on it!

**Comment by richardbuckle** [comment]
PR merged.
