### ISSUE TITLE
Missing nouns for Search and Rescue hand-in

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#602]
## EDDI version in which issue found
3.0.1-b4

## Steps to reproduce

1. Hand in SAR items. Journal exceprts:
```
{"timestamp":"2018-05-26T22:04:09Z","event":"SearchAndRescue","MarketID":3228973824,"Name":"usscargoblackbox","Name_Localised":"Black Box","Count":1,"Reward":21184}
{"timestamp":"2018-05-26T22:04:09Z","event":"SearchAndRescue","MarketID":3228973824,"Name":"wreckagecomponents","Name_Localised":"Wreckage Components","Count":3,"Reward":23577}
```

## Expected
Something like 
```
1 Black Box recovered in exchange for [some amount] credits
3 Wreckage Components recovered in exchange for [some amount] credits
```
## Observed
EDDI said:
```
1 recovered in exchange for over 21 thousand credits
3 s recovered in exchange for around 23 and a half thousand credits
```

**Comment by Tkael** [comment]
Also not verbalized:
`{ "timestamp":"2018-05-27T21:02:20Z", "event":"SearchAndRescue", "MarketID":3223343616, "Name":"occupiedcryopod", "Name_Localised":"Occupied Escape Pod", "Count":2, "Reward":62645 }`

**Comment by richardbuckle** [comment]
The Cottle script is expecting `event.commodity` to be a `CommodityDefinition` not a `string`. Testing a fix now.

**Comment by richardbuckle** [comment]
Merged
