### ISSUE TITLE
'Limpet check' script searches for localized name 'Limpet' rather than edname 'Drones'

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#608]
Using a language with a localized name for limpets that does not match 'Limpet'...
1.Dock any staton and buy some limpet and Undock.
2.You have 40t of limpet
3.you have limpet controller on your ship but not carrying any limpet.

https://github.com/EDCD/EDDI/blob/master/SpeechResponder/eddi.json#L801 is where it looks like the limpet check is (for the default English personality).

**Comment by richardbuckle** [comment]
PR merged
