### ISSUE TITLE
Message Received event: variable populated incorrectly?

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#61]
A user has requested as simple bit of help for the Message Received event, see [https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5893478&viewfull=1#post5893478](url)

However, when I tested it getting a 'direct' message from a station, the 'channel' was set as 'NPC' not 'direct', even though it was a direct message and 'NPC' should only be listed as a 'source'.

It seems that 'NPC' was in the wrong variable category,

**Comment by Tkael** [comment]
The channel is taken directly from the journal. In this case, the journal recorded the channel as NPC. Clarified Variables.md for this event to show that 'npc' is a valid output for the channel.
