### ISSUE TITLE
EDDI Core: Replace EDDP monitor?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#62]
The EDDP monitor currently relies on access to jgm's private server. Since jgm has stepped away from this project, it is not known whether the server will continue to be supported into perpetuity. We might consider revising this monitor, and the associated functions to get Body and System details, to utilize the EDSM API.

The data currently being pulled from EDDP for faction states & body details can be redirected to pull from EDSM via the EDSM public API, as described here: https://www.edsm.net/en/api-system-v1
The data currently being pulled from EDDP for system details can be redirected to pull from the EDSM API as described here: https://www.edsm.net/en/api-v1

**Comment by Syrrianyl** [comment]
EDDP is also used in DataDefinitions/BlueprintMaterials.cs with [http://api.eddp.co/_blueprintrequirements](http://api.eddp.co/_blueprintrequirements), in MaterialMonitor/MaterialMonitor.cs with [http://api.eddp.co/_materiallocations](http://api.eddp.co/_materiallocations) and [http://api.eddp.co/_materialuses](http://api.eddp.co/_materialuses).
Perhabs it is possible to put in github site, or use site like INARA. eddp is also use to recive log and errors files of users in [http://api.eddp.co/log](http://api.eddp.co/log) and [http://api.eddp.co/error](http://api.eddp.co/error), and, to be able to help users with big problems, it is some important to have access to these logs and error files

**Comment by Tkael** [comment]
Thanks for this. :-)

**Comment by Tkael** [comment]
Consolidated to https://github.com/EDCD/EDDI/issues/97
