### ISSUE TITLE
After PC wipe EDDI won't install

### ISSUE THREAD

**Issue by Wasp0** [EDCD/EDDI#621]
I wiped and reinstalled fresh copy of Win 10 Pro Ver 1803 as my Whole PC was running slow and effecting Elite dangerous game play.

Now i can't install EDDI, i download the setup.exe file and a small window pops up momentarily, saying 'Verifying the application requirements, this may take a few moments, then after a second or two this dissapears and NOTHING then happens.

Tries running as Administrator, same thing.

Please help

**Comment by richardbuckle** [comment]
Perhaps you need to install .NET 4.7.1 from https://www.microsoft.com/en-us/download/details.aspx?id=56115

**Comment by Wasp0** [comment]
Yep tried that get this message when trying to install .Net 

.NET Framework 4.7.1 or a later update is already installed on this computer.??

**Comment by Wasp0** [comment]
Sust it Guys. Just followed the the instructions already on this subject. Should have read them before posting DOH!!
