### ISSUE TITLE
Landing pad report not firing

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#622]
## EDDI version in which issue found
3.0.1-b4

## Steps to reproduce

1. Obtain docking permission at any of the supported types of port (Coriolis, Orbis, Ocellus, Asteroid Base).

## Expected
The "Landing pad report" script runs and provides directions.

## Observed
Silence

## Investigation
I added the following to the "Docking granted" Cottle script:
```
...
{set station to StationDetails(event.station)}
{if station is null: Station is null. |else: {dump station}}
...
```

and consistently got `[]` for the dump.

**Comment by Tkael** [comment]
I wasn't able to replicate this issue, but I expect that you were in an area with poor data coming from our EDDP server. Fortunately, recent updates to the journal mean that we can be less dependent on EDDP server data for this feature.

**Comment by richardbuckle** [comment]
Oort Orbital and The Oracle in the Pleiades so that’s plausible.
