### ISSUE TITLE
Cargo hold not emptied when destroyed

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#624]
## EDDI version in which issue found
3.0.1-b4
## Steps to reproduce

1. Have mission Cargo in the hold
2. Die and rebuy

## Expected

Cargo hold reports empty

## Observed
Cargo is still reported as carried and is marked as stolen.

## Investigation
Only tested with ship, may also apply to SRV death and cargo that hasn't been offloaded to ship.

**Comment by Hoodathunk** [comment]
Ok, I got this one.

**Comment by richardbuckle** [comment]
Tested.
