### ISSUE TITLE
VoiceAttack status variables not set

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#630]
## EDDI version in which issue found
3.0.1-rc1
## Steps to reproduce
1) Extend landing gear or cargo scoop

## Expected
Related VA status variable to be set to True

## Observed
Status variable remains set to False

## Investigation
Replaced _VoiceAttackPlugin.cs_ with version prior to `Merge branch 'feature/voiceattack-variables' ` Functionality restored.

**Comment by Tkael** [comment]
How quickly are you polling this? It can take a second or so for the status monitor to catch up to reality.

**Comment by rodan123** [comment]
Not very quickly. I am seeing that the variable does not change over minutes.
I really don't think the status variables are being set properly as they showed my landing gear up when I started the game docked in a station.  There is an issue with the new _VoiceAttackVariables.cs_ split from _VoiceAttackPlugin.cs_ . As I noted above, reverting to the single, unmolested _VoiceAttackPlugin.cs_  file and recompiling eliminates the issue.

**Comment by Tkael** [comment]
Ah, I think I spotted a bug... I set up a thread to update this but I never told that thread to start.  Lol. Fixing.

**Comment by Tkael** [comment]
`unmolested`? Noted. ;-)

**Comment by Tkael** [comment]
Fix merged.
