### ISSUE TITLE
Error recovery fails to recover EDDI

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#650]
## EDDI version in which issue found
3.0.1-b4

## Steps to reproduce
Trigger an unhandled exception in EDDI

## Expected
EDDI swallows the exception gracefully and recovers

## Observed
Crash.

## Investigation
This approach looks promising: http://community.bartdesmet.net/blogs/bart/archive/2006/11/11/Windows-Vista-Application-Recovery-with-C_2300_.aspx

**Comment by richardbuckle** [comment]
Sorry, I differ. An unhandled exception should indeed crash. That's how programs bail out rather than doing damage.
