### ISSUE TITLE
Unit test "TestListen" never completes

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#68]
This "test" attempts to connect to eddn-relay.elite-markets.net:9500 and read data, however it never completes.

I'm not sure what this test is supposed to accomplish as there are no assertions, but in any case unit tests should not depend on external servers.

I'm not sure this test is worth keeping. What do team members think?

**Comment by Tkael** [comment]
Honestly, I have almost no knowledge on tests. I'll have to do some more reading to bring myself up to speed... in the mean time, I defer to you and Hoodathunk.
EDDN changed server locations a little while ago, jgm made updates during his 2.3.0 tidy ups to match. does this address match the new address or is it pointing to the old one?

**Comment by Tkael** [comment]
Found the relevant document: https://forums.frontier.co.uk/showthread.php/361819-EDDN-Elite-Dangerous-Data-Network
eddn-relay.elite-markets.net:9500 should now be tcp://eddn.edcd.io:9500. Updated and retested, now passes.
