### ISSUE TITLE
2 failing tests

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#69]
Leaving aside TestListen, which never completes, there are currently 6 failing tests in the branch patch-1 and 4 in master. Some are due to jgm hardcoding paths from his local machine and some are null objects.

In master:

- TestDataProviderBodies
- TestGenerateWikiEvents
- TestGetLogs
- TestProximaCentauriComment

In patch-1, additionally:

- TestJournalDocked1
- TestJournalMessageReceived2

So it looks like maybe we broke those two.

**Comment by Tkael** [comment]
does the test give any information as to why it might have failed?

**Comment by richardbuckle** [comment]
Yes when you run them then the failing assertion is detailed in the lower panel. No point listing them all here. I'll deal with the obvious ones and come back to you if any aren't obvious after that.

**Comment by Tkael** [comment]
Regarding TestJournalMessageReceived2: The new output is expected even though it doesn't match the old hardcoded value. Recommendation: Update the hardcoded test value to "Pirate".

**Comment by richardbuckle** [comment]
All passing now.
