### ISSUE TITLE
Wrong voice used on startup welcome message

### ISSUE THREAD

**Issue by TalShaf** [EDCD/EDDI#710]
## EDDI version in which issue found
[Running version 3/0/1-rc-1, standalone.]

## Steps to reproduce

1. Run EDDI.
2. Run Elite and log in.
3. EDDI plays 'Welcome back, commander' in male voice, contrary to settings.
4. EDDI plays 'You are docked at...' in female voice, as per settings.

## Expected
All messages should play in a female voice.

## Observed
Welcome message plays in male voice.

**Comment by Tkael** [comment]
Does this occur with all of the voices installed on your PC? Or is it one specific voice? Is this a new issue or something that has been ongoing?

Does your Windows system default text to speech use the male voice? If EDDI is unable to render text in the preferred language, it may try to fall back to the system's default voice.

**Comment by Tkael** [comment]
Please specify both your preferred and system default voices so that we try try to replicate this?

**Comment by TalShaf** [comment]
Both are set on Microsoft Hazel. Though the voice list in Windows contains more voices than EDDI displays. Perhaps that is part of the issue?

**Comment by Tkael** [comment]
Hmm. Are you using 64 bit Windows? If so, try this? https://www.jaws-users.com/text/Windows/Basics/Using32BitSAPIVoicesInA64BitSystem.html

**Comment by Tkael** [comment]
Please also update to version rc2. :-)

**Comment by TalShaf** [comment]
That dialog displayed the male voice for some reason. I have switched it to my desired setting. 

This started recently. I'm no longer sure this has anything to do with EDDI, honestly. I will test more later on tonight, and will also try selecting a different voice. 

Thanks!

**Comment by Tkael** [comment]
Ok. So we may have found the issue. Please report back after you test so that we can close this ticket. o7

**Comment by Tkael** [comment]
Closing as (presumably) resolved.
