### ISSUE TITLE
Installer script is packaging debug files not release

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#72]
The installer script Installer.iss is packaging up the debug build products. Should be release.

**Comment by Tkael** [comment]
when I've tried to build releases in Visual Studios, EDDI runs but the interface is missing many tabs. judging from the .iss, jgm may have always built from debug rather than release.

**Comment by Tkael** [comment]
when I've tried to build releases in Visual Studios, EDDI runs but the interface is missing many tabs. judging from the .iss, jgm may have always built from debug rather than release.

**Comment by Tkael** [comment]
from my reading on the subject, it seems release is less forgiving... uninitialized variables for example are automatically initialized in debug but not in release, code is not optimized to the same extent in debug, etc. I'd like to get a true release build worked out.

**Comment by richardbuckle** [comment]
That's… very surprising. I'll look into this some more. Uninitialised vars etc would have shown up in the code analyser output. In the past I've seen things like this happen when I add files but forget to add them to both debug and release targets.

Definitely needs to be sorted out!

**Comment by Hoodathunk** [comment]
I was also under the impression that jgm purposefully used the 'debug' code so that he would get all Log messages when he told a user to send him the 'verbose' log.

**Comment by richardbuckle** [comment]
Wanting more logging is not a sensible reason to ship debug builds, which are massively unoptimised in both speed and space, both very undesirable in a real-time plug-in for a game.

If you want more logging from problem cases, use a proper logging solution with control of the logging level but no overhead for the majority. Or, worst case, give the problem cases a release build with more logging hard-coded. But not a debug build, that's sheer folly.

**Comment by richardbuckle** [comment]
Fixed.
