### ISSUE TITLE
High CPU usage with VoiceAttack plugin running

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#720]
## EDDI version in which issue found
Version 3.0.1-rc3

## Steps to reproduce
Initialize EDDI in VoiceAttack and observe CPU utilization

## Expected
VoiceAttack without EDDI initialized is 0.5 - 3%, depending on whether the mic is picking up noise. 

## Observed
With EDDI initialized, VoiceAttack CPU utilization is 10-13%.

## Investigation
EDDI is continually updating VoiceAttack variable values. Ref. VoiceAttackPlugin.cs lines 89 & 130. 
The SetValues method sets background variables for standard objects in VoiceAttack (commander, ship, system, etc.).
Setting shipyard values (including recursing through all objects associated with the `Ship` definition for each ship in the shipyard) appears to be creating the greatest burden on CPU utilization (per Visual Studios debug mode CPU utilization).
Disabling the code for recursing through shipyard data reduces baseline CPU utilization for VoiceAttack to ~3-7%.

Updating shipyard data  (and other data that need not be continually updated) should be updated by discrete events rather than continuously updating with the same values over and over again.

**Comment by Midanthrope** [comment]
Seeing the same as @Tkael reported with my 8700k at 5Ghz, averaging 12% Cpu usage across all cores.  Issue was first noticed with v 3.0.1 RC2 and has persisted with RC3.

**Comment by richardbuckle** [comment]
@Tkael Do your notes mean that you've identified a viable approach for this? If so, how big a risk would it be testing-wise?

**Comment by Tkael** [comment]
That approach wasn't great. I think I found a better one. PR submitted.

**Comment by Tkael** [comment]
If any of you savvy alpha testers wants to build from the PR branch and test, please do so. 
I myself am about to hop on a plane for a family reunion so my testing opportunities will be limited.
Please provide feedback on this thread or on our Discord server.

**Comment by richardbuckle** [comment]
The PR looks plausible to me, but as I’m not a VA user I can’t test it directly. Going to wait a few hours, and if nobody yells I’ll merge it into rc4.

**Comment by richardbuckle** [comment]
Merged.
