### ISSUE TITLE
EDDN commodity messages from EDDI are missing info

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#722]
## EDDI version in which issue found
3.0.1-rc3

## Steps to reproduce
Fly from one station to another with the EDDN responder enabled.

## Expected
there should always be a sellPrice and a buyPrice if there is a stock(Bracket)

## Observed
EDDI: https://ross.eddb.io/eddn/log/66988712
EDMC: https://ross.eddb.io/eddn/log/66928078

## Investigation
Possible regression issue?

**Comment by richardbuckle** [comment]
Problem traced to using `as int` rather than casting.

```csharp
    quote.sellprice = commodity["sellPrice"] as int? ?? 0; // bad, always gives 0
    quote.sellprice = (int)commodity["sellPrice"]; //good
```

Sheesh. Really unintuitive. Only defence is more test coverage, I'd say.

**Comment by Tkael** [comment]
Agreed. We should have had a test for this already.

**Comment by richardbuckle** [comment]
PR #732

**Comment by richardbuckle** [comment]
PR Merged
