### ISSUE TITLE
Issue with getting Functions to work from VA

### ISSUE THREAD

**Issue by sparioendernerd** [EDCD/EDDI#726]
## EDDI version in which issue found
EDDI version is 3.0.1 -rc3 with VoiceAttack.

## Steps to reproduce

1. I made a command in VA that sets a text variable "Script" to "Hey, {TXT:userName}! {Emphasize("Initializing")}" then passes that variable to EDDI's External Plugin say command.
2. I tested the command.

## Expected
I expected the voice to emphasize the word "Initializing" in the sentence.

## Observed
The voice read out "Hey, Spario! Emphasize Initializing"

## Investigation
I searched for any similar issues.

**Comment by Tkael** [comment]
That's an interesting blend of syntaxes. I'm afraid you've found something that wasn't included in the design. Text from VoiceAttack is not passed through the same resolving engine that EDDI scripts pass through and it doesn't look like it would be easy to send everything through the same pipe. I'd recommend keeping EDDI's syntax to EDDI and VoiceAttack's syntax to VoiceAttack. 

VoiceAttack does support the use of SSML tags (which is the same technique that EDDI uses for `Emphasise` and similar functions, so you can do this with just VoiceAttack if you wish. (https://www.w3.org/TR/speech-synthesis11/#S3.2.2)
If you want the voice processing, however, then I'd suggest that you set state variables in VoiceAttack and use them to pass your variables from VoiceAttack to a ready-made script in EDDI.

**Comment by sparioendernerd** [comment]
Yeah I had a feeling the syntax was different. Luckily I'm happy with using SSML in VA. So I think I'll stick to using EDDI for the responses, and general functionality, then keep all the commands to VoiceAttack's TTS. Unfortunately that means I either have to figure out a way to route the audio through a VST plugin, or deal with no effects. (Which is manageable, the effects are a small piece of the immersion.)
