### ISSUE TITLE
"Yourt Target has an bounty assigned" come on every sub-target switch

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#728]
## EDDI version in which issue found

3.0.1-rc3, standalone

## Steps to reproduce

If I select an target with bounty I hear "Your Target has an bounty assigned", which ist nice. When I switch through the sub-system of the target ship the message ist repeated every time.

## Expected
Get the info only when I switched target not on every sub-target switch.

## Observed

Message is ginnve on every sub-target switch.

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by richardbuckle** [comment]
Thanks for the report: I found the same and we are looking at PR #725 fixed a lot of it. 

I've been doing a lot of combat lately so I realise how important it is to avoid distractions.

**Comment by richardbuckle** [comment]
Fixed for 3.0.1-rc4.
