### ISSUE TITLE
Commodity galactic average prices are hardwired

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#731]
We have hardwired the average prices of commodities in code. 

This is incorrect as they can and do change.

**Comment by Tkael** [comment]
Agreed. The Frontier API provides this data - I don't know why we haven't taken advantage of it.

**Comment by richardbuckle** [comment]
Probably because jgm originally made it readonly in the class schema.

Something to revisit ,but not for this release.

**Comment by richardbuckle** [comment]
OK this is now priority as the community has indicated that it is a required field:

```
"required" : [ "name", "meanPrice", "buyPrice", "stock", "stockBracket", "sellPrice", "demand", "demandBracket" ],
```

Also:
   You know, you can append "/test" to the schema to test your messages and the EDDN response.

**Comment by richardbuckle** [comment]
Escalating to show-stopper as we have learned that it is required field.

**Comment by richardbuckle** [comment]
Searched codebase for my comments re #731.

.\Tests\CommodityTests.cs(98):            // Assert.AreEqual(294, quote.avgprice); // TODO: re-enable when #731 is fixed
.\EDDNResponder\EDDNCommodity.cs(11):        [JsonIgnore] // do not send until #731 is fixed https://github.com/EDCD/EDDI/issues/731

**Comment by richardbuckle** [comment]
Over to you @Tkael
