### ISSUE TITLE
How do I use variables in SpeechResponder

### ISSUE THREAD

**Issue by sparioendernerd** [EDCD/EDDI#733]
## EDDI version in which issue found
I'm using EDDI v3.0.1 -rc3, in the SpeechResponder

## Steps to reproduce

1. I tried to use the cmdr.name variable in a OneOf() function,  however I can't seem to figure out the syntax.

## Expected
I expected the TTS to read my In-Game name.

## Observed
It either read out the c m d r dot name, or gave an error.

## Investigation
I've tried various syntax, cmdr.name, {P(cmdr("name"))} and even {F("cmdr.name")}. I also googled for how to use the variables.

**Comment by Tkael** [comment]
`{OneOf("{cmdr.name}", "another name")}` should work (untested since I'm traveling and away from my pc for the next few days)

**Comment by sparioendernerd** [comment]
Thanks, it worked.
