### ISSUE TITLE
Swapout-check script doesn't work correctly with Guardian FSD Boosters

### ISSUE THREAD

**Issue by DaftMav** [EDCD/EDDI#735]
## EDDI version in which issue found
v3.0.1-rc3

## Steps to reproduce
1. Equip Guardian FSD Booster module
2. Land at Macleod Horizons in HIP 19157  -At least this is where it happened to me but I doubt this station is special so I'm assuming other stations could trigger it too. (I don't land at stations a lot, so I'm not sure how often this happens.)

## Observed
EDDI's "swapout check" script suggests swapping out my 5H Guardian FSD Booster to save nearly 5.5 million credits (that's 100% of what it costs). The station doesn't even offer any Guardian FSD Booster modules.

**Comment by Tkael** [comment]
Version rc3 was released before Elite 3.1. Module definitions have been updated and these updated definitions should resolve this issue in the next release.

**Comment by Hoodathunk** [comment]
The 'Swapout check' script tries to match ship modules with station outfitting using EDDBIDs.

All of the guardian modules have an EDDBID of -1 (I'm guessing Anthor hasn't assigned IDs yet) and the 'Swapout check' script is failing on this.

I will modify the script only check EDDBIDs > 0.

**Comment by Tkael** [comment]
Merged.
