### ISSUE TITLE
EDDI does not start anymore !

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#743]
## EDDI version in which issue found
EDDI-3.0.1-rc3
Windows 10 pro v 1709 (Build 16299.547)
.NET Framework 4.7.1

## Observed
Approx. 10 sec after starting EDDI, EDDI shows an empty window, after another 3 seconds Windows shows an error window "EDDI no longer works".  

## Investigation
Problem exists with single operation and as a plug-in by VA. 
The problem persists even after a complete reinstallation (contents of the installation paths deleted).

The problem started after a Windows update. These are the patches from 17.07.2018 on my PC.
KB4338825 / KB4338832 / KB4056254 / 4287903 / KB4134661 / KB4284819 

Here the EDDI-LOG 
[eddi.log](https://github.com/EDCD/EDDI/files/2206920/eddi.log)

**Comment by Tkael** [comment]
Have you tried reinstalling EDDI after the Windows update?

**Comment by nepomuk16321** [comment]
Okay, I read the troubleshooting (specific Issues) page. But my config files are here,
 c:\Program Files (x86)\VoiceAttack\Apps\EDDI\  (EDDI.exe.config ect.) .
I have performed step 2. After that EDDI does not start at all.
Here are my paths:
c:\Program Files (x86)\VoiceAttack\Apps\EDDI\
c:\Users\UserName\AppData\Roaming\EDDI\
c:\Users\UserName\AppData\Local\Eddi\EDDI.exe_Url_jtjtvmlplfce4fdwas0znyrhcb0gsrdn\1.0.0.0\

I think this is related to the windows update. Nothing has been changed on the pc, only the windows update went through. Everything was running smoothly before the update. :-(

Sorry for "my" bad english, it 's google :-)

Greetings nepomuk

**Comment by nepomuk16321** [comment]
I found pages on the web that indicate problems with the July update of Windows. Is it possible that these problems have to do with my EDDI error? Sorry, pages are in german.
(https://www.borncity.com/blog/2018/07/14/microsoft-und-das-juli-2018-patch-desaster-updates-stoppen/)
(https://www.windows-faq.de/2018/05/15/kb4134660-fuer-windows-10-version-1703-und-kb4134661-fuer-1709-erschienen/)

**Comment by Tkael** [comment]
Do you still see this issue if you run EDDI as an administrator?
Try resetting folder permissions? https://blogs.msdn.microsoft.com/astebner/2005/08/20/how-to-manually-reset-folder-and-file-permissions-in-windows-explorer/

**Comment by richardbuckle** [comment]
Are we good to close this then?

**Comment by nepomuk16321** [comment]
Yes, please close. Problem detected and fixed.

Thank you

**Comment by Tkael** [comment]
Glad you were able to find a solution. :-)
