### ISSUE TITLE
EDDI 3.0.1-rc4 using massive amount of CPU

### ISSUE THREAD

**Issue by amadeus1171** [EDCD/EDDI#747]
## EDDI EDDI 3.0.1-rc4
High CPU usage occurs running through Voice Attack.  Stand alone seems to run fine.

## Steps to reproduce

Open Voice Attack with EDDI 3.0.1-rc4 and watch you system melt down

## Expected
Expected Voice Attack not to eat more CPU than Elite. x.x

## Observed
Very high CPU usage.

## Investigation
Runs fine stand alone.

**Comment by richardbuckle** [comment]
That is strange as we thought that was fixed with #720. @Hoodathunk and @Tkael could you test please?

**Comment by Tkael** [comment]
At rest CPU utilization is low, but when EDDI is processing events it spikes as EDDI attempts to set a very high number of values in VoiceAttack. I'm looking at mitigations.

**Comment by richardbuckle** [comment]
Fixed for 3.0.1-rc5
