### ISSUE TITLE
Speech responder: Generate additional personalities or add customization options to current personality?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#75]
Ideas discussed in Discord chat for an enhanced / chatty personality:
1. Create a '.settings' Cottle function, called from 'Commander started' and 'Commander continued', to record the commander's gender and allegiance.
2. Revise the 'Honorific' function to respond to the commander's gender (and allegiance?)
3. Add flavor text for various events (or differing amounts of information) derived from the ship role assigned in the shipyard & allegiance

**Comment by Darkcyde13** [comment]
I had another idea this morning.  In addition to assigning a personality to a particular ship role, as briefly discussed already, maybe also assign a particular TTS voice as well.

**Comment by Tkael** [comment]
Let's make that a separate issue. Opened as Issue #105
