### ISSUE TITLE
EDDI status label in EDDI tab doesn't update dynamically

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#753]
## EDDI version in which issue found
3.0.1-rc4

## Steps to reproduce

1. Observe the state of the "EDDI Status:" label in the bottom left of the "EDDI" tab.
1. Make a change, such as logging -in or out of the Frontier API.
1. Switch back to the EDDI tab and observe the state of the "EDDI Status:" label.

## Expected
Label should dynamically update to reflect current status.

## Observed
Label is unchanged until you quit and relaunch EDDI.

## Investigation
Given the declining importance of the cAPI it might be time to revisit the purpose of this label from scratch.

**Comment by Tkael** [comment]
The `Frontier API` tab already gives us that info so you could argue that there's limited value in having it on EDDI.cs too. But it would also be easy to add a call to `setStatusInfo` after changes to your Frontier API status.

Note that the MainWindow.xaml.cs method `setStatusInfo` is used for a couple of different things right now...
1. Noting if a new release is available.
2. Noting the status of the Frontier API.
3. Noting if EDDI is in safe mode.

**Comment by richardbuckle** [comment]
Probably tme to rethink this UI element then. It clearly dates from the days when the CAPI was the only source of info.
