### ISSUE TITLE
Use test rather than live EDDN endpoints for non-stable builds

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#757]
Currently we use test EDDN endpoints if the game is in beta OR the build configuration is debug.

1. Centralise this logic.
2. Also use test EDDN endpoints if the build number indicates a non-stable build (beta or release candidate -- that logic should reside in `Utilities.Versioning`).

**Comment by Tkael** [comment]
Option one should work well then.

**Comment by Tkael** [comment]
@richardbuckle Any further thoughts on how we want to do versioning moving forward?

**Comment by richardbuckle** [comment]
Yes I have unpublished code for this which I think you'll like a lot.
