### ISSUE TITLE
Not all ships listed in Ship Monitor

### ISSUE THREAD

**Issue by battlestrike2** [EDCD/EDDI#758]
## EDDI version in which issue found
3.0.0 (and previous), Running with voice attack but even in stand alone not all ships listed.
## Steps to reproduce
I have a number of ships not in the list. My main ship I have tried to change the name to an 'older' ship but to no avail. The 'older ship' does change in the list.
The annoying thing about this is it does not give accurate fuel readings to th e'neglected' ship and every jump I get 'fuel less than 25%' or 'no fuel reserve' etc
I have reinstalled both EDDI and VA. I have deleted some ships to see if the list was too long, Repurchased the ships to see if they will rename but they do not.
When trying to change the name in Elite the ID is correctly spoke but no ship name.

## Expected
I expect to change the name of my ship and for it to be recognized and appear on the ship monitor list (as it is in most cases except for this one).

## Observed
The ship in question is 'Deep Space Two'. It was 'Deep Space Three' but I have tried different names, including existing ones' but it makes no difference. Sell the ship and buy a new similar ship also doesn't make any difference. 
Tried buying another type of ship but again the  name is not spoken.
I have other ships not on the list but they are spoken and recognized when used.
I do have TWO Elite accounts and ships from both accounts are in the list eve though Cmdrs name is different. I have no problems with the others when swapping accounts.

## Investigation
Tried reinstalling, have tried new Beta versions, have deleted plugins and reinstalled. Renamed Deep space 2 to 3 and vice versa. Deep Space 2 will rename to 3 but 3 will not rename to two  (by 'rename' I mean speak or appear on the list)

**Comment by battlestrike2** [comment]
Just noticed that only TWO ships of each type are listed. The ships not listed are where I have MORE THAN two. Is this the issue?

**Comment by Tkael** [comment]
EDDI does not support multiple accounts. Both accounts will try to assign the same local id number to the corresponding ship for the account and your shipyard will become corrupted with info from the other account.

**Comment by Tkael** [comment]
Please navigate to %appdata%/EDDI and delete shipmonitor.json to clear and rebuild your shipyard configuration.

**Comment by Tkael** [comment]
We already have an open issue for supporting multiple accounts, so I'm going to close this. Let us know if you have any concerns. o7 cmdr.
