### ISSUE TITLE
Blackmarket Cargo not properly inventoried

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#759]
Been frequenting black-markets lately selling items I find in Thargoid USSs.
Also noted that the ****illegal/prohibited flag** for cargo does not seems to work** any  longer.
Probably a separate issue, let me know if you want me to open a separate issue #.
Stolen flag works OK. 
 
## EDDI version in which issue found
Eddi 3.0.1-rc3

## Steps to reproduce
1. Scoop black-market illegal/stolen items
2. Verify items are reporting in hold via Cargo Report cottle script
3. Sell Items on the black-market
4. Find that items are not removed from inventory when Cargo report cottle script is run afterward 

## Expected
Items to be removed from inventory after sold

## Observed
Items remain in inventory after sold

## Investigation
Examining code it seems that only the selling of stolen mission cargo is accounted for.

**Comment by Tkael** [comment]
Illegal status isn't given to us via the journal, either when we pick up the cargo or when we land. The only source that I think could provide this info would be the Frontier API.

**Comment by rodan123** [comment]
Yeah, I was wondering if the illegal/prohibited list of cargo was still valid. I don't see _prohibited_ in the cottle station variable listing, but it is used in the cargo report cottle script. But, as far as I can tell station.prohibited is always an empty list. There seems to be code in eddi.cs that tries to pull the illegal/prohibited info from the Frontier API, but I didn't dig very far into it. 

Excerpt from Cargo Report Script: 
_{if status.docked:
            {for prohibited in station.prohibited:
                {if cargo.name = prohibited: {set illegal to true}}
            }_

It'd be nice info to have, but the main issue is with the blackmarket cargo not being removed from the Cargo Report inventory when sold.

**Comment by Tkael** [comment]
Assigning this to @Hoodathunk to take a look.
As long as you've visited the station previously, the prohibited commodities list should be saved to `EDDI.Instance.CurrentStation.prohibited`.
We can investigate setting commodities from this list upon entering normal space or with location events, provided that EDDI.Instance.CurrentStation is set. 
We would then clear prohibited flags from cargo in inventory when we leave the station.

**Comment by Hoodathunk** [comment]
on a ‘MarketSell’ event, the ‘blackmarket’ flag was the tricky one. There’s room for improvement in the logic by checking the station prohibited list to determined whether commodity sold in black market was haulage or owned.

I don’t see any value to hard-coding a ‘prohibited’ flag in the commodity object. The snippet above from ‘Cargo Report’ would accomplish the same result in Cottle with less effort in the codebase.

**Comment by rodan123** [comment]
I agree the station.prohibited list is sufficient.
It isn't listed among the station variables on the cottle variables help screen.
Just stumbled upon it in the cargo report script.
 Pity it's not unavailable until docked in a station.
Would be helpful to have that info when jumping into a system. Been fined heavily more than once, dropping into something, then getting scanned by authorities on the way to a station, and forgetting I was carrying illegal goods.

**Comment by Hoodathunk** [comment]
I will update the Cottle variables list.

**Comment by Tkael** [comment]
We've been looking separately at separating ourselves from that eddp server for a long time... it hasn't been updated for a long time and as you say is sometimes extraordinarily out of date. But improving our data source is a separate issue. 
The Frontier API provides sufficient data for now and when we do switch to a more up to date data source we will be able to magnify the utility of the change we've already proposed.

**Comment by rodan123** [comment]
@Hoodathunk Hi. Just took a look at PR #800.

I see that you've now accounted for cmdr **owned** cargo being sold on the black market.
But isn't it possible that cargo the cmdr has **stolen** might also be sold there? 

Just a thought. Great work on the patch.

**Comment by Hoodathunk** [comment]
The ```if (@event.stolen)``` code covers that.

Just looked at the Journal manual again and the event DOES have a flag for illegal (prohibited) cargo... no need to use possibly unreliable station data.

Current logic:
1. If @event.stolen is true, cargo sold was stolen. Note that @event.blackmarket would also be true.
2. If  @event.black market is true and @event.illegal is false, assume cargo sold was haulage. This will not catch every scenario, but until we get a missionid in the event for sold haulage, there is little more we can do. The request has been made.
3. Everything else (including illegal cargo) is owned.
