### ISSUE TITLE
Localization seems to be the cause of incorrect results in Voice Attack.

### ISSUE THREAD

**Issue by JohnJackDoe** [EDCD/EDDI#760]
## EDDI version in which issue found
3.0.1-rc5

## Steps to reproduce

In Voice Attack:
Write [Blue] '{EXP:50*0.5}' to log

## Expected
25

## Observed
250

## Investigation
Disabling EDDI in the plugin-settings makes Voice Attack to calculate correctly again.

![2018-07-24_22-03-27](https://user-images.githubusercontent.com/18377308/43348848-7de4fc1e-91fc-11e8-9a95-da8df50a5815.gif)

**Comment by Tkael** [comment]
Interesting. We don't even come close to doing something that should affect this. Have you tried this experiment with any other plugins?

**Comment by Tkael** [comment]
From the video, it looks like 250 may be the result of the comma in the second expression in your command? (I'm not at my pc to test at the moment)

**Comment by JohnJackDoe** [comment]
Voice Attack do not work with a comma as decimal separator. That's why the expression error.
The order in the log is opposite to the command window.
I used it to show that is not a locale issue of the OS.

**Comment by JohnJackDoe** [comment]
The error does not occur if the plugin is disabled:

![2018-07-28_12-30-05](https://user-images.githubusercontent.com/18377308/43356897-5581349a-9279-11e8-8d2a-60e1b8956b47.gif)

**Comment by Hoodathunk** [comment]
The VA plugin API just does not work this way. Variables can be set and plugin functions can be called but there is no facility for plugins to hook into VA operations like this.

I’m not disputing this anomaly, but there are no variables being used in your expression that a plugin could impact.

I suggest bringing this to VA’s attention and get their thoughts.

**Comment by JohnJackDoe** [comment]
To ask the VA-Forum was my first idea:
http://voiceattack.com/SMF/index.php?topic=2129.0

**Comment by Tkael** [comment]
What language do you use in EDDI?

**Comment by richardbuckle** [comment]
If you explicltly set a language in EDDI, then that locale will be applied to VA too. This is unsatisfactory but we have not been able to identify a better way. 

1. What is your OS locale?
1. What happens if you set EDDI to English?
1. What happens if you set EDDI to Automatic?

The answers to these questions will help us narrow down how to address this,

**Comment by JohnJackDoe** [comment]
My OS locale is German.
That is interesting: 
It only happens if I explicitly set EDDI to German and not if it is set to English or Automatic.
What I don't understand is how EDDI can influence VA in this way when VA has no localization at all?

But thanks for that hint. This is a workaround I can handle with.

**Comment by Tkael** [comment]
Glad we were able to help. 
This issue could very easily prove to be quite complex to resolve, and if so we may want to leave things be.
I'll run a few tests and see if there's a relatively simple way to resolve this issue.

**Comment by Tkael** [comment]
I reached out to Gary at VoiceAttack about this issue. He was kind enough to investigate and reported back the following:
```
Thank you for all the info (I was able to reproduce the problem with your steps).  The expression parser is using the invariant culture to do its calculations, however, I noticed that there is one line of code that is parsing decimal values in there that was NOT forcing the invariant culture for {EXP}.  I've fixed up that section and tested it out and it seems like it is returning proper values.  I'll have a release out soon (code is guts-out at the moment).

Again, thanks for the heads-up!
```
Looks like this will be fixed in a future release of VoiceAttack. :-)
