### ISSUE TITLE
Faction bond message wrong

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#762]
## EDDI version in which issue found
3.0.1-rc5 standalone

## Steps to reproduce

Kill a Thargoid Scout

## Expected
Getting a message that I received 10k from the Pilot's Federation for killing a Thargoid

## Observed
Getting a message that I received 10k from $faction_PilotsFederation for killing $faction_Thargoid (it does say "dollar faction underscore Pilots Federation"

## Investigation
Journal entry:
{"timestamp":"2018-07-28T07:39:54Z","event":"FactionKillBond","Reward":10000,"AwardingFaction":"$faction_PilotsFederation;","AwardingFaction_Localised":"Pilots Federation","VictimFaction":"$faction_Thargoid;","VictimFaction_Localised":"Thargoids"}

Looks like you are not using the localised name

**Comment by Tkael** [comment]
Interesting. Most of the time localized values are not present. Thargoids are the only edge case I've found in my logs where they are.
```
{ "timestamp":"2018-01-31T07:46:49Z", "event":"FactionKillBond", "Reward":50600, "AwardingFaction":"Traditional Wyrd Justice Party", "VictimFaction":"Legacy Corp" }
```
It would seem that, at least for this event, we need to prefer the localized names whenever they are present.

**Comment by Hoodathunk** [comment]
Was wondering about that, TK... well, that’s easy enough to fix

**Comment by Tkael** [comment]
Alright. It's true that Elite Dangerous only supports a limited language set and preferring the localized name from the journal is only really helpful in the context of those supported languages. For that reason, hard coding an exemption into the code for this case might be the better option.

**Comment by CMDR-Cometborne** [comment]
My suggestion is to only use the localized name if a) it is present and b) the non-localized name starts with $faction_

**Comment by Hoodathunk** [comment]
"hard coding an exemption into the code for this case might be the better option."

Would you please elaborate?

**Comment by Tkael** [comment]
Essentially, we'd need a resx file for faction names. I'm still not super happy with this as a solution, but there doesn't seem to be a lot of great solutions here.

**Comment by Tkael** [comment]
As in, always use English for `Pilot's Federation` because it's that ubiquitous?

**Comment by richardbuckle** [comment]
As I learned as a proof-reader for Sagittarius Eye, it's "Pilots Federation" with no apostrophe. Anyhow, I'm still leery about hard-coding exceptions. It may be worth asking what approach other EDCD devs are taking.

**Comment by Tkael** [comment]
@richardbuckle I think this one's waiting for your input.

**Comment by richardbuckle** [comment]
There is also the case where the player runs the game and EDDI in different languages to consider, for a Portuguese speaker may run EDDI in Portuguese and the game in Spanish. Hmm.

**Comment by Tkael** [comment]
Thargoid's not going to change regardless. But if "Pilots Federation" needs to be translated then it needs a resx. Or a space in an existing regx.
And per [this link](https://community.elitedangerous.com/fr/galnet/uid/579b28f89657ba0d4c598970) (in English [here](https://community.elitedangerous.com/en/galnet/uid/579b28f89657ba0d4c598970)), it appears to be correct to translate `Pilots Federation`.

**Comment by richardbuckle** [comment]
Let's patch the immediate "$faction_" issue for 3.0.2 and worry about the rest later.

**Comment by Hoodathunk** [comment]
I started work on this and put it on hold, pending the discussion. The branch, as it stands, does address the immediate issue. Take a look at it... if you think it's sufficient, I will PR it.

**Comment by Hoodathunk** [comment]
Yes, it does. There is only additional 'localized' faction data when the original faction data contains "$faction_". The fix prioritizes the localized data when it exists.

**Comment by richardbuckle** [comment]
Point taken. I'll merge your branch, although I'll modernise it to use `??` notation.

The economist J.M. Keynes said "in the long term, we are all dead." Likewise we as maintainance devs on an ancillary app with no defined API should, I suppose, be pragmatic about the long term.

**Comment by Tkael** [comment]
Alright, though I suggest that we move the logic to the more generic JournalMonitor.cs method `getFaction()` and apply that method to this event. That will allow us to generalize the logic across all events that use the getFaction method.
