### ISSUE TITLE
[Cosmetic] Description EDDI: station variables incorrect

### ISSUE THREAD

**Issue by arnocs** [EDCD/EDDI#766]
## EDDI version in which issue found
[Priority Low] Comments is incorrect.
VoiceAttack 1.7.2, EDDI 3.0.1

## Steps to reproduce
Goto the command in voiceattack, look at the comment.

## Expected
"Write out station variables to the log"

## Observed
"Write out shipyard variables to the log"

## Investigation
[none]

**Comment by richardbuckle** [comment]
Fixed for 3.0.2-b1.
