### ISSUE TITLE
Command missing ;

### ISSUE THREAD

**Issue by arnocs** [EDCD/EDDI#767]
## EDDI version in which issue found
[Priority high] Affects working
VoiceAttack 1.7.2, EDDI 3.0.1

## Steps to reproduce
Command cannot be executed, because missing a semi-colon in the middle

## Expected
Please repeat that;What was that?;Could you say that again?;Say that again

## Observed
Please repeat that;What was that?Could you say that again?;Say that again

## Investigation
Is in 2.4.5, 3.0.0 and 3.0.1

**Comment by richardbuckle** [comment]
Fixed for 3.0.2-b1.
