### ISSUE TITLE
In Voice Attack, {TXT:Ship compartment n module} is not populated

### ISSUE THREAD

**Issue by Corysia** [EDCD/EDDI#769]
## EDDI version in which issue found
3.0.1 Release

## Steps to reproduce

1. In Voice Attack, create an event handler for ((EDDI ship loadout))
2. For the command, use the following inline C# function:
```C#
public class VAInline
{
    public void main()
    {
        VA.SetBoolean("bDockingComputerPresent", false);
        for (int x = 1; x < 11; x++)
        {
            if (VA.GetBoolean("Ship compartment " + x + " occupied").GetValueOrDefault())
            {
                VA.WriteToLog(VA.GetText("Ship compartment " + x + " module"), "red");
            }
        }
    }
} 
```
3. Log in to Elite:Dangerous, swap a module, change ships, or do some other activity that triggers the ship loadout event.

## Expected
For each populated module, the module name should be printed to the VA console

## Observed
For each populated module, a blank line

## Investigation
Spoke with T'kael on Discord and he thinks he's tracked down the issue.

**Comment by Tkael** [comment]
The issue wasn't what I initially thought. It turns out that module definitions in ship.compartments are not being initialized properly. Consequently, only minimal information is being communicated. Essentially, all that we seem to get is whether the compartment is occupied and the associated edname.

**Comment by Tkael** [comment]
I've traced it back to ShipMonitor.json. When modules are written to ShipMonitor.json, only the edname is serialized. All other properties are not.
