### ISSUE TITLE
Test `TestShipScenario1` writes to permanent storage

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#77]
Unit tests should always mock out network and storage access.
TestShipScenario1 doesn't do this and adds a Sidewinder with no name and an Imperial Courier called "Scunthorpe Bound" to the developer's shipyard. This persists in live.

Amend this test to use a mock object to prevent writing to like storage. This may require introducing some dependency injection.

**Comment by Tkael** [comment]
Fixed, long ago.
