### ISSUE TITLE
Remove "Wanted" field before sending

### ISSUE THREAD

**Issue by bgol** [EDCD/EDDI#770]
https://github.com/EDCD/EDDI/blob/46d7c41841a5701e801a48e083a9270e88091954/EDDNResponder/EDDNResponder.cs#L136
```c#
data.Remove("Wanted");
```
The "Wanted" field can also be removed.

**Comment by bgol** [comment]
The "Wanted" field is commander specific and EDDN messages should be stripped of them.

**Comment by Tkael** [comment]
@bgol is referencing the guidelines for using EDDN published to the github (here)[https://github.com/EDSM-NET/EDDN/wiki#app-developers-data-uploaders].
Agreed, and easily done.

**Comment by richardbuckle** [comment]
Fixed for 3.0.2-b1.
