### ISSUE TITLE
In VA, {BOOL:Status hardpoints deployed} not always correct

### ISSUE THREAD

**Issue by Corysia** [EDCD/EDDI#772]
## EDDI version in which issue found
3.0.1-rc6, 3.0.1 Release

## Steps to reproduce
Inconsistent.  I can detect when it's going to happen, but I can't determine what is flipping the state variable.  Common precursors are:
1. Using the D-Scanner in supercruise
2. Being interdicted and killing the opponent, then resuming supercruise after stowing hardpoints.

## Expected
Nothing out of the ordinary.

## Observed
Immediately after exiting supercruise at about 9km from the station, my hardpoints deploy.

## Investigation
I've set up an event in Voice Attack to handle the ((EDDI station no fire zone entered)) and then test the value of {BOOL:Status hardpoints deployed} to automatically stow hardpoints.
```
Begin Boolean Compare : [Status hardpoints deployed] Equals True
    Press variable key(s) [edDeployHardpointToggle] and hold for 0.2 seconds and release
    Set Text [Script] to '[we have;][entered;crossed over;crossed into;reached] the no fire zone. [retracting;powering down;disarming;stowing;] [weapons;hard points]'
    Execute external plugin, 'EDDI 3.0.1-rc6' and wait for return
End Condition
```
I've also added a test in my 'Disengage' event to write the status of the {BOOL:Status hardpoints deployed} variable to the VA log window.

Sometimes, rarely, but at least once in a two hour play session, {BOOL:Status hardpoints deployed} is set to TRUE at the time of telling VA to 'Disengage'.  This is impossible as the ship is in Supercruise and usually has been for several moments -- however long it takes to fly 900ls, at least.  Upon exiting supercruise, the ((EDDI station no fire zone entered)) event triggers and, following the value of the deployed state, my VA profile attempts to stow the weapons -- which is a toggle, so they actually deploy within the no-fire zone.

*NOTE* I have not checked to see if {BOOL:EDDI station no fire zone entered weaponsdeployed} is properly set.  I will add some logic to report on that.

**Comment by Tkael** [comment]
If you are hitting the no fire zone the moment you exit supercruise and trying to react to that state immediately, that could be creating an issue. `Status` tends to be written just a tiny bit behind the other events, so the status may not have caught up completely at the instant you exit supercruise.

Consider
1. Adding a short delay between exiting supercruise and checking the value of the status variable or
2. Adding a loop that waits until {BOOL:Status supercruise} is false prior to proceeding?

**Comment by Corysia** [comment]
Neither help.  I tried both of those ideas earlier.  Something is flipping the value of {BOOL:Status hardpoints deployed} while {BOOL:Status supercruise} is TRUE.  And it seems to be linked to using the Discovery scanner (fire 2).  The next time this happens, I'll capture a log and see what the events are.  I'll also add more logging to my VAP so that I can try to detect where things go wrong.  It doesn't happen very often, so it's going to be hard to track down.

**Comment by Tkael** [comment]
I've tested your script and confirmed the behavior. 
The status does flip quite quickly to false, but if you are already in the no-fire zone when you exit supercruise the variable may still be set incorrectly when the event triggers.
I've also confirmed that using your discovery scanner does deploy hardpoints while in supercruise.

**Comment by Tkael** [comment]
I've submitted a PR to keep {BOOL:Status hardpoints deployed} false while in supercruise. o7
