### ISSUE TITLE
Scanning ships in supercruise, not being told when data collected

### ISSUE THREAD

**Issue by Taomyn** [EDCD/EDDI#773]
## EDDI version in which issue found
3.0.1, in VA

## Steps to reproduce

1. Scan ship in supercruise
2. Scan returns data for collection i.e. is not full

## Expected
Voice should report data type collected

## Observed
HUD shows data obtained, EDDI remains quiet

## Investigation
Checked script, reverted to default (not that I had changed it, but I am using my own copy of the profile), the test button does nothing.

**Comment by Hoodathunk** [comment]
@Taomyn Please provide the journal entry for the 'MaterialCollected' event notification you did not receive.

**Comment by Tkael** [comment]
You know guys, the default EDDI personality isn't configured to announce every time that a material is collected. If @Taomyn is using the default script, he shouldn't expect to hear anything.

This is the default script (there is no talking in this script):
```
{_ Context }
{SetState('eddi_context_last_subject', 'material')}
{SetState('eddi_context_last_action', 'collect')}
{SetState('eddi_context_material_name', event.name)}
```
This is my version (with talking):
```
{_ Context }
{SetState('eddi_context_last_subject', 'material')}
{SetState('eddi_context_last_action', 'collect')}
{SetState('eddi_context_material_name', event.material)}


{set material to MaterialDetails(event.name)}
{set unit to OneOf("unit", "sample", "example")}
{set our to OneOf("our", "the", "")}

{if material.category = 'Data':
   {set unit to OneOf("unit", "sample", "record")}
   {set collectiondescription to OneOf(
      "acquired", 
      "captured", 
      "collected", 
      "obtained",
      "received",
      "saved", 
      "added to analysis routines:", 
      "queued for analysis:"
   )}
|else:
   {set unit to OneOf("unit", "sample", "fragment")}
   {set collectiondescription to OneOf(
      "acquired", 
      "collected", 
      "obtained",
      "received",
      "added to {our} stores", 
      "added to {our} inventory"
   )}
}

{if event.amount > 0:
   {OneOf(
      "{event.amount} {unit}s of {event.name} {collectiondescription}", 
      "{collectiondescription} {event.amount} {unit}s of {event.name}"
   )}.
   {set this to "these"}
|else:
   {OneOf(
      "{event.amount} {unit} of {event.name} {collectiondescription}", 
      "{collectiondescription} {event.amount} {unit} of {event.name}"
   )}.
   {set this to "this"}
}


{if material.category = 'Element':
    {_ do nothing _}
|elif material.category = 'Data':
    {Pause(500)}
    {Occasionally(7, OneOf(
       "Running compression algorithm.", 
       "Cataloguing.",
       "Data mining.",
       "Integrating into current models.",
       "Identifying anamolies.",
       "Identifying deviations."
       "Identifying deviations from the norm.",
       "Identifying correlations.",
       "Performing frequency analysis.",
       "Performing regression analysis.",
       "Archiving", 
       "Analyzing."
    ))}

|elif matis.category = "Manufactured":
   {if matis.name = "unknownenergysource":
      {_ Unknown Artifact Fragment}
   }

|elif matis.category = "Unknown":
   {set type to slice(matis.name,0,7)}
   {if type = "ancient":
      {_ ancient alien data}
   }

}
```

**Comment by Hoodathunk** [comment]
@Tkael Yup, you are correct, sir. I'm so used to my own modified script running in the wild that I forgot the default is basically empty.

@Taomyn we do not support non-default scripts. I suggest you give @Tkael 's above script a try and see if that suits your needs.

Cheers!

**Comment by Taomyn** [comment]
The only script I use is one where I copy the default one which I redo every time I update to take into effect any changes and make some changes, mainly disabling some I don't want and more recently getting the percentage completion update on dropping off cargo at the depot to also tell me the number of units remaining.

Since I can remember with EDDI + VoiceAttack, whenever I have targeted ships in supercruise and there has been data downloaded, EDDI has told me by voice the data type downloaded. Same as when I was targeting and scanning all the Guardian obelisks and getting their data. It only doesn't announce something when the storage is full, which is fair enough. I have never written any script code to do this.

**Comment by Hoodathunk** [comment]
@Taomyn I have looked at the history of the default script for 'Material collected' and it has not changed since VerticalBlank, T'Kael, and I took over supporting and maintaining EDDI.

The default script that exists now has not changed since the Material Monitor was first created. What you were using was a custom script.. I will not speculate as to how you obtained it.

It is likely that you inadvertently over-wrote it with the default, which has created your current predicament.

If you enjoyed that functionality, your best option is to paste @Tkael 's script above into your custom personality.

Meanwhile, we will evaluate the merits of making @Tkael script (or one similar) as the default in a future release.

o7

**Comment by Taomyn** [comment]
Hi @Hoodathunk thanks for looking into it, honestly I have never added anything of that nature to either a copy of the default script or the default script itself. I have almost weekly backups going back months, and no extra code is in any of my copies, nor in any of the default versions. I'm as stumped as you are where it came from but I definitely remember it happening. Oh well.

I will take a look at @Tkael 's script as it looks interesting, maybe cut it down a bit as I only need a simple prompt that something new or additional was scanned. In VR audio cues become so much more important when you're not always facing directly ahead.

Keep up the great work o7
