### ISSUE TITLE
EDSM doesn't receive events that EDDI doesn't explicitly handle

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#776]
## EDDI version in which issue found
3.0.1

## Investigation
EDDI supports the current EDSM API, but  we don't currently pass events we're not handling and we don't currently handle all events. For instance, we do not currently handle the statistics event and consequently EDSM doesn't receive it.

**Comment by richardbuckle** [comment]
Fixed for 3.0.2-b1
