### ISSUE TITLE
EDDI Core: Update beta game detection method

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#78]
EDDI currently compares production build numbers from the journal against the server to determine whether a given journal file pertains to a beta or production release build of Elite: Dangerous and set the variable "inBeta".

Frontier recently changes the format of the beta journal files to make them distinct from normal journal files (JournalBeta.170903172048.01.log vs. Journal.170906235611.01.log).

Revise EDDI to remove dependency on "productionbuild" sent from the EDDP server and instead recognize beta game journal files directly?

**Comment by richardbuckle** [comment]
moving to post-2.4

**Comment by Tkael** [comment]
Heh. I didn't see this until after it was ready so I went ahead and submitted the pull request. Approve now or later, either way works. ;-)
