### ISSUE TITLE
Home system economy error from EDDP

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#797]
## EDDI version in which issue found
3.0.1 standalone

## Steps to reproduce

1. Set a breakpoint on `EddiDataDefinitions.ResourceBasedLocalizedEDName.FromEDName` at the Logging.Info call around line 97.
2. Change your home system in the Commander Details tab.

## Expected
No error

## Observed
Breakpoint fires because EDDP is supplying the Localised or Invariant Name for the primary economy, rather than the EDName.

**Comment by Tkael** [comment]
Ah, I see. Well that's an easy fix.
