### ISSUE TITLE
Beta 2.4-b1

### ISSUE THREAD

**Issue by klinzmann** [EDCD/EDDI#80]
Version 2.3.1 allows the download and installation of EDDI 2.4-b1 (beta) but restarting EDDI results in showing active version 2.3.1 and EDDI allows download and upgrade to 2.4-b1.

Where does EDDI downloads the installer for the beta?

**Comment by richardbuckle** [comment]
Congrats but you're jumping the gun a bit, you've stumbled across our internal testing. Stay tuned.
