### ISSUE TITLE
Additional fuel tanks not accounted for

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#819]
## EDDI version in which issue found
3.0.2

## Steps to reproduce

1. Equip addional fuel tank(s)

## Expected
`ship.fueltanktotalcapacity` should account for the extra tanks.

## Observed
`ship.fueltanktotalcapacity` stays equal to `ship.fueltankcapacity`.

[Forum report](https://forums.frontier.co.uk/showthread.php/387955-EDDI-2-4-Bring-your-cockpit-to-life?p=6963061&viewfull=1#post6963061)

Code is `ShipMonitor.ParseShipLoadoutEvent()`.

**Comment by Tkael** [comment]
Did you verify that the compartment and module info in your ShipMonitor.json was written correctly?

**Comment by Hoodathunk** [comment]
Problem appears to be another victim of the module 'single instance' error. Added unit testing for ship.fueltanktotalcapacity & ship.fueltankcapacity in feature/module-info. branch with good results.

PR #870 submitted.

**Comment by Tkael** [comment]
PR #870 merged.
