### ISSUE TITLE
EDDI plugin causing Voice Attack crashes

### ISSUE THREAD

**Issue by yucatan** [EDCD/EDDI#821]
## EDDI version in which issue found
3.0.2

## Steps to reproduce
1- Set Voice Attack to use EDDi as a plugin
2- Issue a command to Voice Attack which requires VA to use EDDI as a responder
## Expected
VA should use EDDI's Text-to-Speech synthesizer to say something

## Observed
"Out of the blue" Voice Attack crashes, with no warning, nor presenting any error message.

## Investigation
Voice Attack version is 1.7.2

1- If I use the same commands, but with VA set to use its own TTS features, with EDDI plugin disabled, VA doesn't crash
2- If I leave EDDI running, so it will give me information when I jump to a system, dock to a station, etc, EDDI doesn't crash.

Bellow is what I find in VA log file (VoiceAttackFault.txt) when VA crashes as described:

8/31/2018 11:30:41 AM***************************************************************************************
System.ArgumentException: Cannot set voice. No matching voice is installed or the voice was disabled.
   at System.Speech.Synthesis.SpeechSynthesizer.SelectVoice(String name)
   at EddiSpeechService.SpeechService.<>c__DisplayClass21_1.<speak>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Please notice the very same "voice" the log says can't be found, VA can use it when in "standalone mode" and EDDI can use with no problems.

Also, the crash doesn't happen as soon as I issue the first command and VA should use EDDI to read the response. It may happen on the first command, but it may happen on the 5th or the 14th. It seems somewhat random.

**Comment by Tkael** [comment]
Is there any corresponding information (with the same or nearly the same timestamp) in EDDI.log (at %APPDATA%/Roaming/EDDI)?

**Comment by yucatan** [comment]
Unfortunately no, the very same error

**Comment by Tkael** [comment]
Posted my findings to what I believe to be the relevant thread on the VoiceAttack forums for feedback: https://voiceattack.com/SMF/index.php?topic=2175.msg10146#msg10146

**Comment by Tkael** [comment]
Do you have a key for the non-Steam version of VoiceAttack? From my personal testing, it looks like the non-Steam version may be more stable. More testers could help validate or invalidate that suspicion.

**Comment by yucatan** [comment]
unfortunately, I don't have a non-steam key :(

**Comment by Tkael** [comment]
I've done everything that I can to generate a method that can produce a crash and have reported my findings to Gary at VoiceAttack, but as I describe [here](https://voiceattack.com/SMF/index.php?topic=2175.msg10180#msg10180) the crash **_appears_** to be occurring after control is passed back to VoiceAttack from EDDI.

**Comment by yucatan** [comment]
@Tkael 

I have been reading both threads (the one I created and other created by Pfeil). I see both teams are working hard to solve the problem :D

By the way, I also run VA with "single TTS Instance" and I also have been 'Ivona 2 Amy' as default TTS voice. It's been a long time since I last used one of MS voices, but I can try that.

**Comment by Tkael** [comment]
Can you try with single TTS Instance off? Maybe VA is trying and failing to reaquire the original TTS Instance? I won't be able to test until this evening.

**Comment by yucatan** [comment]
Ouch, my bad. I thought I had "single TTS instance" on, but it was OFF. Then I changed it to ON and after 
some minutes the crash happened again.

(I will report this on my VA thread)

**Comment by Tkael** [comment]
I've added a commit to convert EDDI to use a single speech synthesizer. This **_appears_** to have helped with stability in VA, though of course much more testing is needed.
