### ISSUE TITLE
Can't filter EDDP State notifications

### ISSUE THREAD

**Issue by timdwilliams** [EDCD/EDDI#828]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]
EDDI 3.03
## Steps to reproduce
With VA closed, opened EDDI 3.0.3, chose EDDP tab, in renamed New Watch to civil war, in the State field in drop down chose civil war,the field now has a red boarder and a red exclamation mark before watch name. try adding new watch and "EDDI has Stopped working" If I close without trying to add new watch and reopen it has reset state to anything. I do receive notifications about anything but can not filter. 
1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
to be able to filter state notifications
## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by poisonbl** [comment]
Did some testing when I ran into this too, and I see it back through the 3.0.2 and 3.0.1 releases. EDDI-3.0.0-b1 is the last release that both runs (due to a crash as it tries to announce the mandatory update), and doesn't exhibit this. Not really a narrow margin, but it's hopefully a start.
