### ISSUE TITLE
Mixed Translation

### ISSUE THREAD

**Issue by snv** [EDCD/EDDI#834]
## EDDI version in which issue found
I am running EDDi 3.0.3 in VoiceAttack 1.7.2

## Steps to reproduce

1. I have a German PC
2. I have setup voice recognition in English, because i prefer gaming in English
3. I have set EDDI to English

## Expected
EDDI's audio output should be English

## Observed
Since localization was added i get a mix of English and German. It seems like while the base texts respect my language choice the variables are german. 

For example (from memory, wording might not be accurate): 
- when entering a Federation System i get "Welcome back, Obermaat", 
- or in Outfitting "You just fitted a Strahlenlaser"
- "You just picked up Fehlerhafte Fokuskristalle"

It does use the english pronunciation voice, but combined with the german words (wich makes it extra hard to understand)

## Investigation
I think the last version i had without this was EDDI 3.0.0-b1 (i skipped a few)

**Comment by Tkael** [comment]
What behavior do you see when you run EDDI standalone (without VoiceAttack)?

**Comment by snv** [comment]
Right, that's interesting.

When i run EDDI standalone it stays english, and when i close it and start VoiceAttack it gets mixed up again.

My VoiceAttack is english too, the Speech Engine is "Microsoft Speech Recognizer 8.0 for Windows (English - US)" only my Keyboard is set to German

**Comment by Tkael** [comment]
It seems that we have an issue where different threads are being assigned different cultures. I'll have to think about this one.

Are the German translated variables consistent? Or are they sometimes English and sometimes German?

**Comment by snv** [comment]
It is very consistent:
When i started EDDI with VoiceAttack i always had German variables all the
time.

Am Di., 11. Sep. 2018 um 02:06 Uhr schrieb Brian Wilson <
notifications@github.com>:

**Comment by Tkael** [comment]
And what language do you see in EDDI's UI? English, German, or a mix?

**Comment by snv** [comment]
I usually start the EDDI UI via in standalone mode, there it is all english.
Now i opened the EDDI UI from inside VoiceAttack for the first time and
yes, it is german and the language is set to automatic :-/


Am Di., 11. Sep. 2018 um 14:17 Uhr schrieb Brian Wilson <
notifications@github.com>:

**Comment by snv** [comment]
Alright, i just fired up ED and yes: after setting the language again in
the UI which i startet from VoiceAttack (and restarting VA) i now have
proper english voice messages.

So, apparently there are two language settings on my system, which are
partly separated and partly mixed together?

Am Do., 13. Sep. 2018 um 01:28 Uhr schrieb Sven Nguyen Van <
sven.nv@gmail.com>:

**Comment by Tkael** [comment]
You were using `Automatic` rather than `English`? That could make a difference in this case. EDDI overrides the default when you select a language, but if you leave it on automatic then I believe it'll try to use the default culture from the host process, which is determined by the operating system if you are running standalone and by VoiceAttack if you are running EDDI as a plugin.

**Comment by Tkael** [comment]
Closing as resolved.
