### ISSUE TITLE
Fails to start after app update, ,NET related

### ISSUE THREAD

**Issue by hastar72** [EDCD/EDDI#835]
## EDDI version in which issue found
3.03

## Steps to reproduce

After app update, error message '.NEt version 4.7.1' required.

## Expected
App to load

## Observed
error message '.NET version 4.7.1' required.

## Investigation
lots of 'mucking about' then saw a thread (related to issue 539) complaining about .NET issues, so edited

EDDI.exe.config
<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />

to 4.7.2

now starts correctly.

**Comment by Tkael** [comment]
What OS version are you using please?
All of EDDI's packages are configured for 4.7.1, but Windows 10 should natively support both 4.7.1 and 4.7.2.
