### ISSUE TITLE
Speech Responder Identifies Some Star Types as "Text-to-Speech Class Star" Instead of Saying The Proper Star Class

### ISSUE THREAD

**Issue by c0dejunKie** [EDCD/EDDI#837]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

EDDI v3.0.3 with voice attack v1.7.2

## Steps to reproduce
1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

Scan curtain stars... Sorry I don't know the exact star type...

## Expected
[describe what you expected to happen]

When a star is scanned this is what should happen:

Scan of {event.stellarclass}-class star {OneOf("complete", "completed", "finished")}.

Resulting in EDDI saying out loud:

Scan of O-Class star complete.  (if it was an O Class star)

## Observed
[describe what happened instead]

On certain stars, I not sure of the exact type, I'm trying to find out which exact star it happens on, but what happens is instead of saying:

Scan of F-Class star complete.   (Note, That I am not currently sure which star type this happens on, so I'm just using F-Class as a stand in.)

Instead of saying what I listed above it will sometimes say this:

Scan of Text-To-Speech Class star complete.

I am currently trying to find the exact star class that this happens too.

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

Have been scanning every star that I come across in order to find which star class this happens too, will report back here when I figure it out, because it is possible that it may be happening to more than 1 star type.

I am using my own personality on the speech responder tab, but I created a new personality when EDDI updated last to v3.0.3 and I have not edited a single one.  All I have done with it is just disable a couple of the ones that I don't need while playing, other than that the personality is the same as the default one.  Ex. "Message Sent, Message Received and a couple others have been disabled. 

Here is what my "Star Scanned" script has in it:

{_ Context }
{SetState('eddi_context_last_subject', 'star')}
{SetState('eddi_context_last_action', 'scan')}
{SetState('eddi_context_star_system', system.name)}
{SetState('eddi_context_star_star', event.name)}
{SetState('eddi_context_last_scan_estimated_value', event.estimatedvalue)}

{Pause(1000)}

Scan of {event.stellarclass}-class star {OneOf("complete", "completed", "finished")}.

{F("Star report")}

{F("Report last scan value")}

{if (event.estimatedhabzoneinner && event.estimatedhabzoneouter) && 
 (event.estimatedhabzoneinner > 0 && event.estimatedhabzoneouter> 0):
   Habitable zone
   {Occasionally(2, OneOf("calculated at", "calculated to fall from"))}: 
   {Humanise(event.estimatedhabzoneinner)} 
   to {Humanise(event.estimatedhabzoneouter)} 
   lightseconds.
|elif event.estimatedhabzoneouter && event.estimatedhabzoneouter > 0:
   Habitable zone
   {Occasionally(2, OneOf("calculated at", "calculated to fall from"))}: 
   {Humanise(event.estimatedhabzoneouter)} 
   lightseconds maximum.
}

**Comment by Hoodathunk** [comment]
I'm struggling with parsing the meaning of "not say that the star type is a Text-to-Speech Star".

Please provide a specific example,

**Comment by c0dejunKie** [comment]
Sorry, I know what I first had in the ticket at first was half assed, I'm not sure why I didn't fill it out better, I am sorry for wasting your time, but I have updated the ticket to better explain the issue that I am Having.

**Comment by Tkael** [comment]
1. Which voice are you using? The way that one voice handles this may differ from how other voices handle it.
2. Please provide the specific star class or star classes where you are having this issue?

**Comment by c0dejunKie** [comment]
1. I am using the default Windows voice called "Microsoft Anna - English (United States)".  I am also using the default Windows speech engine called "Microsoft Speech Recognizer 8.0 for Windows (English-US)".

2.  I am currently trying to get it to repeat again so that I can know which star type that it happens on.  It has happened a lot before I created this ticket, so it shouldn't take too long.  I will post back here once I know the exact star type.

**Comment by Tkael** [comment]
Did the last star you scanned have this issue? If so, you may be able to upload your last journal file for us to review (with the latest 'DateModified`). It'll be located in [your Saved Games folder]\Frontier Developments\Elite Dangerous

Unfortunately, I don't have Microsoft Anna available on this PC. My PC natively supports Microsoft Hazel and Microsoft David.

**Comment by c0dejunKie** [comment]
I'm sorry it took me so long to get back to you on this matter but I was a little busy last night and was unable to play elite in order to find out which stars this issue is affecting, but I was able to get on elite today and you will be happy to know that I was finally able to figure out which class of star EDDI is calling a Text-to-Speech class star.  The star class that it is happening to is "T" class and possible "TTS" class.   This is the line in my journal file for when I scanned the star and EDDI called it a Text-to-Speech class star:

{ "timestamp":"2018-09-16T18:01:58Z", "event":"Scan", "ScanType":"Basic", "BodyName":"Puppis Sector QI-T b3-8 A", "BodyID":1, "Parents":[ {"Null":0} ], "DistanceFromArrivalLS":0.000000, "StarType":"TTS", "StellarMass":0.234375, "Radius":299972544.000000, "AbsoluteMagnitude":10.971222, "Age_MY":0, "SurfaceTemperature":2140.000000, "Luminosity":"VI", "SemiMajorAxis":2544296001536.000000, "Eccentricity":0.122960, "OrbitalInclination":-112.806877, "Periapsis":240.179260, "OrbitalPeriod":17372499968.000000, "RotationPeriod":153232.171875, "AxialTilt":0.000000 }

In-game the star is listed as a T Class star, but shows in the journal as a TTS class star, I'm sure you guys know what that is all about.  I'm going to continue to play so I will post back here if I find any other stars that this may be happening with.

Please let me know if there is any more information that I might be able to give to you.

**Comment by c0dejunKie** [comment]
Oh and I guess I should let you know that I did update to the latest beta version that was released today, v3.1.0-b1,  I also updated the personality that I use so that all my scripts are from the latest version of EDDI.

**Comment by Tkael** [comment]
A TTS class star? That could certainly do it. Thanks.

**Comment by c0dejunKie** [comment]
np happy to help.

**Comment by Tkael** [comment]
So after giving this some thought...
- None of my installed voices exhibit this behavior and you are the first to report it. The voice you are using is not (as far as I'm aware) very commonly used.
- If we change the text output, we risk breaking scripts for other commanders. We'd rather not do that.
- We could either 
  - code a phonetic translation for stellar class 'TTS' (via Translations.cs in EddiSpeechService) or
  - revise the default script to convert the string 'TTS' to something that isn't rendered as 'Text to speech' by any voice engine (something like `tee tee ess` or `T Tauri` won't look clean but should get the job done). 

@richardbuckle @Hoodathunk Feedback welcome.

**Comment by c0dejunKie** [comment]
Hmmm, I find it odd that the default voice that comes with windows 7 is not commonly used, you would think that since it's the default voice that it would be one of the ones that is used the most, but that's just my 2 cents.  Could you please recommend some other voices that I could install that don't have this issue with saying TTS?  Thank you very much for the info and for your time..

**Comment by richardbuckle** [comment]
Maybe we could use `T.T.S.` or `Spacialise(“TTS”)`.

**Comment by Tkael** [comment]
Windows 7 is no longer very commonly used I think. And different versions of Windows (e.g. x32 or x64) have at times shipped with different TTS voices. 

I have installed at the moment:
- Ivona Amy
- Cerevoice Heather
- Microsoft Hazel
- Microsoft David
- Microsoft Zira

Something like 
```
{if event.stellarclass = "TTS":
     {Spacialise(“event.stellarclass”)}
|else:
    {event.stellarclass)
}
```
might work.

@c0dejunKie Can you confirm that the voice you are using converts "TTS" to "Text--to-speech" but does not convert "T T S" the same way?

**Comment by c0dejunKie** [comment]
> @c0dejunKie Can you confirm that the voice you are using converts "TTS" to "Text--to-speech" but does not convert "T T S" the same way?

How would I do that?

**Comment by Tkael** [comment]
If you have not already done so, create a custom personality. Then create a new blank script. Paste the following into that empty script and then hit the "Test" button... which of the lines are pronounced as "Text-to-speech" and which are pronounced "TTS"?
```
TTS.
T.T.S.
T T S.
T. T. S.
```

**Comment by c0dejunKie** [comment]
TTS. <---This one said Text-to-Speech
T.T.S. <--- This one said TTS
T T S. <--- This one said TTS
T. T. S. <--- This one said TTS

Looks like it's just TTS that makes it say Text-to-speech and all the others just say the letters TTS.

**Comment by Tkael** [comment]
Looks like changing the script to 
```
{if event.stellarclass = "TTS":
     {Spacialise(“event.stellarclass”)}
|else:
    {event.stellarclass)
}
``` 
should work nicely then.

**Comment by Tkael** [comment]
I'll opt for increased script legibility and code it into {P(event.stellarclass)}.
