### ISSUE TITLE
System visit totals not incrementing

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#840]
## EDDI version in which issue found
EDDI v3.0.3  running under Voice Attack

## Steps to reproduce

1. Jump to a system
2. Examine {INT:System visits}
3. Jump to another system and then return to the original system
4. Examine {INT:System visits}

## Expected
{INT:System visits} increments by 1 

## Observed
{INT:System visits} does not increment

## Investigation

1. Stop EDDI, refresh data from EDSM, and repeat test -- no effect
2. Stop EDDI, delete database, refresh data from EDSM, and repeat test -- no effect.

Examine database; _totalvisits_  for system not incremented.

**Comment by Tkael** [comment]
Hmm... does it increment when you run EDDI standalone?

**Comment by rodan123** [comment]
Negative. Tested using EDDI standalone and cottle `{system.visits}`
Same result. Variable not incremented, database field _totalvisits_ not updated. 
Although the database field _starsystemlastupdated_ appears to have been updated `2018-09-18 05:53:42.5708875Z`, the rest of the fields seem to remain static.

Was working fine in EDDI version 3.0.2

**Comment by sjmagy** [comment]
I've noticed the exact same issue -- every jump to a system is my first visit, even if it's my home base I've flown in & out of every time I play.

From poking around other "old" custom EDDI profiles others have released, it looks like the variable used to be "system.visits" but in the latest it shows as being "reportsystem.visits", so I tried manually changing that variable in the FSD Engaged script (I think that's the one) back to "system.visits" but it didn't make a difference -- the same information was relayed and the visit count never incremented.  (I've since restored it to the default variable name, though obviously it didn't magically make things work.)

FWIW, I couldn't spot in any jump or system-related script where it is even incrementing the visits value, which may explain why it's always my first visit to the system...?

**Comment by rodan123** [comment]
This issue has been open for quite a while --

I did some investigation today; 

I set up some logging entries and in _EDDI\EDDI.cs_  `private bool eventJumped(JumpedEvent theEvent)` and found that _CurrentStarSystem.name_ and _theEvent.system_ match every time I jump into a system.

The event handler code appears to want  _CurrentStarSystem.name_  to be the name of the system that you jumped from, but it is set to the system you jumped to, so we end up in what appears to be a outdated `else if` section of code _// Jumped event following a Jumping event, ..._ I believe it is outdated because the **Jumping event** is depreciated.

Log entries below with notation;

You can see we jump, journal is parsed, event added, and handled in EDDI.cs. 

2018-10-07T19:07:44 [Info] VoiceAttackPlugin:updateValuesOnEvent Executed command ((EDDI fsd engaged)) 
2018-10-07T19:08:03 [Info] JournalMonitor:ParseJournalEntry Jumped to Zhi  **<- FSD Jump**
2018-10-07T19:08:03 [Info] JumpedEvent:.ctor Added jump event for Zhi   **<- Add JumpedEvent**
2018-10-07T19:08:03 [Info] EDDI:eventJumped Enter:Zhi 25 Event name: Zhi  **<- Enter `eventJumped` EDDI.cs**
`"Enter:" + CurrentStarSystem.name + " " + CurrentStarSystem.visits + " Event name: " + theEvent.system`
2018-10-07T19:08:03 [Info] EDDI:eventJumped Update2: Zhi Visits:26 **<- in EDDI.cs eventJumped as below**
 `else if (CurrentStarSystem.name == theEvent.system && Environment == Constants.ENVIRONMENT_WITCH_SPACE)`
2018-10-07T19:08:03 [Info] VoiceAttackPlugin:updateValuesOnEvent Executed command ((EDDI jumped))

I commented out the obsolete _Jumping_ `else if` section to fall through to the final `else` in `private bool eventJumped(JumpedEvent theEvent)` and that does a proper update and allows the system visit count to increment properly.

Hope that helps track this down, if you haven't already,

**Comment by sjmagy** [comment]
@rodan123  I don't seem to have a file named "EDDI.cs" on my system (using EDDI 3.0.3).  Can you provide more specific direction on which file you commented out the else if clause?  (I checked the scripts in EDDI but didn't see anything there close to what you typed above.)  Is it in the Voice Attack profile?

**Comment by rodan123** [comment]
@sjmagy Apologies if I was confusing. EDDI.cs is a file in the source code of the EDDI program. 
You would need to download the source code, edit it, and then recompile the program to make the changes I described. That isn't something one would casually do without some programming experience. Hopefully this issue will get fixed by one of the devs in the next EDDI release.

**Comment by Tkael** [comment]
Thanks for the investigation. I've been a little engrossed in my own branch recently but I'm hoping to turn my attention to this soon. It sounds like it may be a pretty simple fix.

**Comment by Hoodathunk** [comment]
@Tkael , I will take this.

**Comment by Hoodathunk** [comment]
Submitted PR #864

**Comment by Tkael** [comment]
#864 merged.
