### ISSUE TITLE
Estimated scan values much lower

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#845]
## EDDI version in which issue found
EDDI v3.1.0-b1, both stand alone and under VA 1.7.2

## Steps to reproduce
Scan a body while exploring.

## Expected
Estimated scan values to be as they were pre v3.1.0-b1

## Observed
Estimated scan values are about half what they used to be.

## Investigation
I'm on my way back to the bubble from the Gnosis, scanning systems as I go.  I've updated EDDI to v3.1.0-b1 and now the estimated scan values are reduced.  Normally a scan of the main star would give around 3K as an estimated value, but now it's about 1K.

I have my speach logged so I can go back and see what was said.  Here are some example excerpts from that log.
EDDI v3.0.3:-
>  Scan of K-class star complete. Outotz KD-H c24-1 A is a common main sequence star with a luminosity class of 5-A, that has been around for on the way to 10 billion years. As you can see, it emits a yellow-orange light. This is a typical example of this class of star. This data could get you nearly 3 thousand credits. Habitable zone calculated at: 185 to 369 lightseconds.

EDDI v3.1.0-b1:-
>  Scan of M-class star complete. Outotz ZM-M b49-0 A is a very common main sequence star with a luminosity class of 5-A, that has been around for on the way to 12 billion years. This is a typical example of this class of star. This scan can fetch well over 1 thousand credits. Habitable zone : 38 to 76 lightseconds.

I've also noticed that planets and moons are similarly reduced in value.  Gas giants now give only about 900 credits, whereas before, a similar gas giant was giving over 2000 credits.

EDDI v3.0.3:-
>  Scan and analysis complete. Outotz HY-D b40-0 1 is a extremely high-gravity ringed Gas giant with water based life that is unsuitable for landing. It has a radius of 77445.2 kilometers, 12 times the radius of Earth, and 680 times Earth's mass. It has a rotational period of 0.7 days. This might get you well over 2 thousand credits.

EDDI v3.1.0-b1:-

>  Scan and analysis complete. Outotz RP-D c26-2 3 is a extremely high-gravity ringed Gas giant with water based life that is unsuitable for landing. It has a radius of 77484.1 kilometers, 12 times the size of Earth, and 888 times Earth's mass. It has a rotational period of 2 days. This scan should sell for 960 credits.

**Comment by Darkcyde13** [comment]
Hmmm, after playing for some time tonight (maybe an hour or so), the star values have suddenly now returned to 'about 3K'.  Planet values still seem to be low though.

**Comment by Darkcyde13** [comment]
After a comment in the forums, I've run a couple of tests for this issue.

A comment was made regarding restarting Voice Attack and star values being reported normally, so I've scanned a few planets with EDDI as a stand-alone, and then VA on (EDDI as a plug-in), and got some interesting results.

I've just tried this with two practically identical planets. Both Rocky Ice Worlds with Argon-Rich atmospheres, almost the same size and gravity.  With EDDI as a standalone, one was worth over 1000cr. With VA running (EDDI as a plug-in) the second planet was worth only 412cr. Seems there is something up with the plug-in version maybe?

**Comment by Tkael** [comment]
Possibly, though I'm not sure what would be different on the VA side. The formula would have been affected by the earth masses of the bodies and by whether EDDI thinks you have a DSS equipped (In fact, the only way that the formula should yield a value less than 720 credits should by without a DSS equipped). Do you have the journal events available for review and have you notices any issues with missing ship compartments or modules on your ship either in VoiceAttack or EDDI standalone?

For reference, here's where we obtained the formulas for scan values: https://forums.frontier.co.uk/showthread.php/232000-Exploration-value-formulae

**Comment by Hoodathunk** [comment]
If this is due to EDDI not seeing a DSS is equipped, it's likely due to issue #829.

**Comment by Darkcyde13** [comment]
Ahh, ok.  That makes a lot of sense.  I do have a DSS, and an ADS, so I should be getting the report of the full amount, but I'm not.

I'm not quite sure if this is correct or not, but I've just given the below a quick try:-
```
{for compartment in ship.compartments:
    {compartment.module.name}
}
```
However, this gives no results.  I've also run the VA commands to display the ship compartment variables, and this shows everything has a value except for the actual name, this is blank for everything.

It would appear that this is indeed the cause then.  It seems weird that the star values are correct, or are they not affected by the lack of a DSS?  Although, they did get reported as only 1000cr right after the upgrade to EDDI v3.1-b1, and for a few systems, but then suddenly corrected to almost 3000cr after a jump to another system.  This was after restarting the PC a couple of times.

Well, as this does seem to be something to do with #829, you can close this if you want.  Unless there is something you would like me to try out?

**Comment by Hoodathunk** [comment]
Pr #830 merged.
