### ISSUE TITLE
Some Windows 10 TTS Voices are only recognised by EDDI when compiled as x64

### ISSUE THREAD

**Issue by Loophole62ndFF** [EDCD/EDDI#847]
## EDDI version in which issue found
Version 3.1.0-b1 standalone

## Steps to reproduce

1. In Windows 10 Narrator settings, for me, five voices are available (David, Catherine, Zira, Mark and James)
2. In the release EDDI Text-to-Speech tab, only David and Zira (and "default") are available
3. If you recompile EDDI from source, targeted for x64 instead on "any platform", then all five voices become available in EDDI

So far I have not been able to rebuild a complete working EDDI as x64, as some of the plugins seem to fail with SQLLite-related errors.

A simple solution might be to have an optional x64 release download?

**Comment by rodan123** [comment]
I think I can help with that. Sounds like you haven't installed the additional voices for 32 bit.
MagicMau has a good tutorial on installing additional voices for 32 and 64 bit applications 
https://apps.magicmau.nl/EliteG19s/Docs/EliteG19s-Manual.html#user-content-MoreVoices

**Comment by Tkael** [comment]
Supporting separate x32 and x64 executables sounds simple but introduces complications that we'd rather avoid. If you try @rodan123's suggestion, let us know how it goes.

**Comment by Tkael** [comment]
Leave it open for the time being. Thanks,

**Comment by richardbuckle** [comment]
I would very much like to know whether the OP is running standalone or under VoiceAttack.

Right now it is only VoiceAttack that is holding us back from going 64-bit only.

**Comment by Loophole62ndFF** [comment]
Apologies for omitting that detail - I'm running stand-alone; no Voice Attack.

**Comment by richardbuckle** [comment]
InnoSetup is certainly capable of writing to the registry, however I am leery of making such an intrusive machine-wide change without the user’s explicit consent.

**Comment by Loophole62ndFF** [comment]
Perhaps it might be better to just include a copy of the Powershell script that can do the changes, as part of the installation, and instructions to "do at own risk"?

**Comment by richardbuckle** [comment]
Alternatively we could write it up in the wiki.

**Comment by richardbuckle** [comment]
Closing as it appears to be an isolated case of the user not having the 32-bit voices installed.
