### ISSUE TITLE
.NET Framework 4.7.1 required but not installed

### ISSUE THREAD

**Issue by rosscarlson** [EDCD/EDDI#848]
## EDDI version in which issue found
3.1-b1

## Steps to reproduce
Install and launch

## Expected
it should launch

## Observed
It tells me that 4.7.1 is required but I'm running the latest insider build of Windows 10.  When I go to install 4.7.2 (the latest) I can't as I'm running a newer version

## Investigation
Am guessing it may have something to do with the version of Windows - 1809 17754.1

**Comment by Tkael** [comment]
Is anything recorded in EDDI's log for this? Located at %appdata%/EDDI.

**Comment by rosscarlson** [comment]
Nope, in fact the log is blank as I did a full uninstall to try again.  When I launch EDDI I immediately get 

-----
This application requires one of the following versions of the .NET Framework:
.NETFramework,Version=v4.7.1

Do you want to install this .NET Framework version now?
-----

And when I click yes and download 4.7.2 it won't install as I'm running a higher version.  According to this article (and I've confirmed this on my system) I'm running 4.7.2

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

If I dig to the key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full and look at the DWORD value "Release" I have: 461814 which corresponds to 4.7.2

So I'm basically stuck and can't even launch it - and can't see a way to downgrade to version 4.7.1 - I'm guessing whatever check is in the code isn't properly handling versions higher than 4.7.1 - maybe it doesn't think they exist?

Thanks for getting back to me so quickly - I want to make a tutorial on this for my Youtube channel (CMDR Exigeous here BTW)

-Ross

**Comment by Tkael** [comment]
Hmm. There isn't any "check" per se that's coded into the program. We simply build targeting a specific version of the framework. I've verified that all of the modules in EDDI are targeting 4.7.1, and both 4.7.1 and 4.7.2 are supposed to be fully supported by Windows 10. and I'm not sure how to replicate this issue on my machine (short of fast tracking my windows install to the latest insider build, which may or may not replicate the issue and which I'd rather not do on the pc I use for daily use).
@richardbuckle @Hoodathunk Any thoughts on this? Could one of our Nuget packages cause an issue like this?

**Comment by Tkael** [comment]
According to [this website](https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-10) from Microsoft: 
```
The .NET Framework 4.7.2 is included with:
Windows 10 April 2018 Update

The .NET Framework 4.7.2 can be used to run applications built for the .NET Framework 4.0 through 4.7.1.
```
Have you tried reinstalling .Net version 4.7.2?

**Comment by rosscarlson** [comment]
Yeah, Tkael I would assume you'd need to be running/testing on the build of Windows I'm running and can fully appreciate why you wouldn't want to update to a beta/non-release build.  Also believe/understand you're not doing a hard check - and that it's just a bug somewhere in the framework.  Found the same article that says that my version should be supported.

Hoodathunk - I don't see a way to update the package - if I try to install the latest 4.7.2 it just stops and says I have a newer version installed as it's (I'm assuming) part of the OS.  I see no place I can uninstall/etc. - any ideas?  Certainly not critical - I'm just working on a tutorial for VoiceAttack and wanted to include EDDI in it.

An update though: The odd thing is EDDI IS working as a pluing for VA.  I can't launch the interface so I can't configure EDDI (at least not visually) but I'm getting information from it and it's doing TTS from VoiceAttack - so part of it is working.  Ah bleeding edge software....

**Comment by philstach3** [comment]
yep, I'm getting this issue as well. tried uninstalling and going back versions but I still get this problem.

**Comment by richardbuckle** [comment]
Note to fellow devs, if you really need to experiment with different OS or .NET installations, VMWare is your friend. Takes a lot of time and disk space to set up though.

**Comment by Trist0ne** [comment]
Hey, I was having the same issue with the same beta windows and unable to downgrade the .net. Little bit of fiddling led to the surprising fix; go to where you installed EDDI, and there should be a file called EDDI.exe.config . Open that with notepad. A few lines down you'll see <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />. Change that last bit to v4.7.2, and amazingly it fixes the problem. Hope it works for you too!

**Comment by richardbuckle** [comment]
Closing as just an issue for insider builds etc.
