### ISSUE TITLE
Missing EDNames (mission related)

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#849]
3.1-b1

The following EDNames are showing up as missing in my log:

```
Unknown ED name PilotsFederation in resource EddiDataDefinitions.Properties.Superpowers 
Unknown ED name RegainFooting in resource EddiDataDefinitions.Properties.MissionType 
```

Journal data:
```json
{
  "timestamp": "2018-08-28T20:07:55Z",
  "event": "MissionAccepted",
  "Faction": "Gold Major Co",
  "Name": "Chain_RegainFooting",
  "LocalisedName": "Assassinate Pirate Lord: Diziet",
  "TargetType": "$MissionUtil_FactionTag_PirateLord;",
  "TargetType_Localised": "Pirate Lord",
  "TargetFaction": "Raksha Jet Electronics Corp",
  "DestinationSystem": "Raksha",
  "DestinationStation": "Sarafanov City",
  "Target": "Diziet",
  "Expiry": "2018-08-29T20:04:25Z",
  "Wing": false,
  "Influence": "Med",
  "Reputation": "Med",
  "Reward": 1052596,
  "MissionID": 414475462
}
{
  "timestamp": "2018-08-28T21:02:09Z",
  "event": "MissionAccepted",
  "Faction": "Lumba Federal Corp.",
  "Name": "Chain_RegainFooting",
  "LocalisedName": "Assassinate Pirate Lord: Redlad",
  "TargetType": "$MissionUtil_FactionTag_PirateLord;",
  "TargetType_Localised": "Pirate Lord",
  "TargetFaction": "Lumba Labour",
  "DestinationSystem": "Lumba",
  "DestinationStation": "Tombaugh Station",
  "Target": "Redlad",
  "Expiry": "2018-08-29T21:01:08Z",
  "Wing": false,
  "Influence": "Med",
  "Reputation": "Med",
  "Reward": 431072,
  "MissionID": 414490097
}
{
  "timestamp": "2018-09-18T20:05:31Z",
  "event": "MissionAccepted",
  "Faction": "Green Party of LFT 926",
  "Name": "Chain_RegainFooting",
  "LocalisedName": "Assassinate Pirate Lord: Molai",
  "TargetType": "$MissionUtil_FactionTag_PirateLord;",
  "TargetType_Localised": "Pirate Lord",
  "TargetFaction": "V886 Centauri Corporation",
  "DestinationSystem": "V886 Centauri",
  "DestinationStation": "Tanner City",
  "Target": "Molai",
  "Expiry": "2018-09-19T20:05:23Z",
  "Wing": false,
  "Influence": "Med",
  "Reputation": "Med",
  "Reward": 317890,
  "MissionID": 420038123
}
```

**Comment by Tkael** [comment]
I'm already handling `PilotsFederation` in my dev branch.

**Comment by Hoodathunk** [comment]
I've had some opportunity to look at this.

Just another example of FDEV not sticking to convention. These are clearly not 'RegainFooting' missions types, they 'Assassinate' mission types. IMO, the most appropriate name should have been 'Chain_Assassinate', thus stating it's a chained assassination mission.

The actual type can be extracted from the localized name, but coding would be horrendous for non-US localizations. I will need to think on this for a bit.

**Comment by Hoodathunk** [comment]
Courtesy of Anthor, here are the mappings:

'chain_planetaryincursions'				=> Scan
'chain_helpfinishtheorder'					=> Deliver
'chain_regainfooting'						=> Assassinate
'chain_wrongtarget'						=> Assassinate
'chain_helpwithpreventionmeasures'			=> Massacre
'chain_salvagejustice'						=> Assassinate
'chain_seekingasylum'					=> Assassinate
'chain_miningtoorder'					=> Mining
'chain_findthepiratelord'					=> Assassinate
'chain_safetravelling'						=> PassengerVIP
'chain_salvagejustice_personaleffects'		=> Assassinate
'chain_rescuethewares'					=> Salvage
'chain_rescuefromthetwins'				=> Salvage
'chain_rampantleadership'					=> Assassinate
'chain_clearingthepath'					=> Deliver
'chain_securingmyposition'				=> PassengerVIP
'chain_drawthegeneralout'				=> Assassinate

This makes the solution very trivial.

Coding...

**Comment by Hoodathunk** [comment]
PR #852 submitted.

**Comment by richardbuckle** [comment]
Wow. Those mappings are so unintuitive. Jeez.

Thanks for the PR, will review tomorrow.

**Comment by Hoodathunk** [comment]
PR #852 merged.
