### ISSUE TITLE
EDDI Core: Update cmdr.credits via journal events rather than via the Frontier API?

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#85]
Currently, cmdr.credits uses information exclusively from the Frontier API. Information from the Frontier API may lag behind real-time events / will not always be accurate. 

If there is sufficient information from the player journal, cmdr.credits could be revised to be sourced and updated from player journal events rather than from the Frontier API.

**Comment by Hoodathunk** [comment]
I would not replace the API updating cmdr.credits, it's a reliable, accurate source. But, I think it's a great idea to use journal events to keep the number 'closer to reality' between API updates.

**Comment by Tkael** [comment]
How would we know whether the API data was more current than the other sources? I wouldn't want to overwrite an accurate ledger with old information from the API. 

Maybe we could tie a timestamp to cmdr.credits so that we could know if the API data was more recent than the journal data and only use it if it were more recent? Or do you have another approach in mind for how you would integrate the API and journal data?

**Comment by Hoodathunk** [comment]
Admittedly, there are delays with clients pushing account data to the FDEV servers and client API requests are throttled, but it's very reasonable to say that the API data is accurate when you need it to be, which is immediately following a 'dock'... hence the "updating market data" message.

While docked, you update the credit balance via journal events and you ignore any API updates which might be 'laggy'. Following undocking, where significant amounts of time pass, the API will have plenty of time to 'catch up'.

**Comment by Tkael** [comment]
I *think* API refreshes are only called when docking and undocking. Simply flying through space doesn't trigger a profile refresh. And credits are not always accurate when undocked (likely because EDDI is still processing the API data asynchronously)

**Comment by richardbuckle** [comment]
Kill this one as superseded by 3.0 journal?

**Comment by Tkael** [comment]
The information is in the journal, we just need to track transactions from the journal rather than taking this info from the Frontier API.

**Comment by Tkael** [comment]
Killing this one for now - gaps in the journal reporting prevent a fully accurate ledger. For example, insufficient data is provided about transactions during wing mission interactions with the cargo depot.
