### ISSUE TITLE
Mission related exceptions reported from Rollbar

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#853]
## EDDI version in which issue found
3.1-b1

## Steps to reproduce
(Reports from Rollbar)

## Expected
No exceptions

## Observed
@Hoodathunk I'm not sure if you've already addressed these, but Rollbar's seeing null reference exceptions from various mission related actions. Are these already handled?

## Investigation
https://rollbar.com/EDCD/EDDI/items/6931/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6937/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6965/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6976/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6975/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6969/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6967/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6966/?item_page=0&#instances
https://rollbar.com/EDCD/EDDI/items/6958/?item_page=0&#instances
(click into the timestamps to review the complete details)

**Comment by Hoodathunk** [comment]
6931, 6967, 6969, & 6975 are associated with the Cargo Monitor 'Mission abandoned' event handler. 

6958 is associated with the Cargo Monitor 'Cargo depot' event handler, particular to the 'Deliver' update type.

6937, 6965 & 6966 are associated with the Mission Monitor 'Mission accepted' event handler, particular to the 'AltruismCredits' mission type.

6976 is associated with the Mission Monitor 'Mission accepted' event handler, particular to the 'GenericPermit1' mission type. I've corrected the error and added unit testing. I added the fix to PR #852 due also being missions type related.

**Comment by Hoodathunk** [comment]
Fixed Cargo Monitor exceptions associated with 'Cargo depot' and 'Mission abandoned' events. Added unit testing for 'Cargo depot' event.

**Comment by Hoodathunk** [comment]
Submitted PR #854 for Cargo Monitor exceptions.

**Comment by Hoodathunk** [comment]
PR #854 merged.
