### ISSUE TITLE
uses wrong sound channel if headset used in a 5.1 sound setup

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#859]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

v.3.1.0-b1 (standalone), but same if used as VA plugin

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

I'm using an 5.1 surround setting. If I'm using speaker the EDDI sound comes correct throug the center speaker. If I plugin my Headset the sound comes still through the center speaker. All other programms (ED, VA, discord, EDDiscovery, Mozilla) route the sound correct to the headset.

## Expected
[describe what you expected to happen]

EDDI should also use the headset if plugged in.

## Observed
[describe what happened instead]

see above

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
Hmm... we're not doing anything fancy when it comes to playing audio, it should simply be coming though your default audio channels.
After plugging in the headset, what are the audio channels in your settings set to? Is the headset the default?
If you restart EDDI with the headset plugged in, where is the sound routed after that restart?

I don't have 5.1 sound setup, unfortunately, so it's going to be hard far me to replicate and track this issue down. @Hoodathunk @richardbuckle Does either of you have a setup more amenable to replicating this issue?

**Comment by lwt-pressy** [comment]
If I restart with headset pluged in it makes no difference. The default device 'SB X-FI Surround 5.1 Pro' does not change if i plugin a headset in this usb sound card as it is still the same device. As a workaround I currently reenables my onboard sound so I can plugin my headset there. It's not nice and make the fine soundblaster useless for that case, but so it's another device which i can switch.

**Comment by Tkael** [comment]
Do you use any 3rd party software to manage your 5.1 surround setup? Any non-Windows drivers?

**Comment by Tkael** [comment]
What version of Windows are you running? Is it Windows Vista or later?

**Comment by Tkael** [comment]
Please also post a screenshot of your Windows sound configuration (opening the start menu and typing `sound` should get you to the right config window).
Is your headset configured as both your default sound device and your default communication device?
![soundconfig](https://user-images.githubusercontent.com/4382539/47630618-09290900-daff-11e8-915a-2f571d89ce64.png)

**Comment by lwt-pressy** [comment]
I'm using WIndows 10 Pro (64Bit). The interessting thing is that my headphone will not show up as seperate device.
![sound](https://user-images.githubusercontent.com/13365281/47844366-889a2f00-ddc2-11e8-895a-3cbe12daeecc.png)
