### ISSUE TITLE
Add event `Scanned`

### ISSUE THREAD

**Issue by DeltaTimo** [EDCD/EDDI#868]
## EDDI version in which issue found
Voice Attack Version _v1.7.2.21_ with _EDDI 3.1.0-b1_.

## Steps to reproduce
1. Get scanned at a station.

## Expected
Event should be handled.

## Observed
Event is not handled.

## Investigation
Event occurs when being scanned at a station by local security forces.
It did not call ((EDDI unhandled event)) either for me.
The following is an example of the message taken from my _Journal.NNNNNNNNNNNN.NN.log_:
`{ "timestamp":"2018-10-11T16:14:19Z", "event":"Scanned", "ScanType":"Cargo" }`

**Comment by Darkcyde13** [comment]
Isn't that the 'NPC cargo scan commenced' event?  I would have thought that script should have picked that up.  Or is that a different type of scan?

**Comment by DeltaTimo** [comment]
> Isn't that the 'NPC cargo scan commenced' event? I would have thought that script should have picked that up. Or is that a different type of scan?

'NPC cargo scan commenced' doesn't seem to get that. And from a glimpse at the code, it seemed as if 'NPC cargo scan commenced' actually hooked chat messages and looked for the classic "What do you carry I wonder?" messages instead of using the "Scanned" event.

**Comment by Tkael** [comment]
The rational here might have been that `NPC cargo scan commenced ` happens at the start of the scan (where it is arguably more useful) and not after the scan is completed? If so, what's the use case for firing an event after the scan completes?

**Comment by Tkael** [comment]
Unhandled events pass the same name that FDev assigned to the event. In this case, it would call ((EDDI scanned)).

**Comment by DeltaTimo** [comment]
> The rational here might have been that `NPC cargo scan commenced` happens at the start of the scan (where it is arguably more useful) and not after the scan is completed. If so, what's the use case for firing an event after the scan completes? Or the case for improved immersion?

An example could be custom voice feedback replacing the original or adding to the already existing COVAS.

> Unhandled events pass the same name that FDev assigned to the event. In this case, it would call ((EDDI scanned)).

Are attributes in the logs copied to variables in the same way? I.e. "timestamp" to a string variable "timestamp" with `2018-10-11T16:14:19Z` or "ScanType" with `Cargo`?

**Comment by Tkael** [comment]
`An example could be custom voice feedback replacing the original or adding to the already existing COVAS.`
Can you be more specific?
`Are attributes in the logs copied to variables in the same way? I.e. "timestamp" to a string variable "timestamp" with 2018-10-11T16:14:19Z or "ScanType" with Cargo?`
No, only the type and and raw string (e.g. event.raw in EDDI) are set.

**Comment by DeltaTimo** [comment]
Using VoiceAttack one could use Text-to-Speech or a themed voice-pack, like a character from a video game or movie for example Data from Star Trek to report being scanned at a station adding immersion to the universe and/or making the impression of alive crew members in your ship.

Does event.raw work similarly in VoiceAttack?

Should the use case(s) not be sufficient to implement a handler, I'm okay with just parsing the original message string myself, if that's possible in VoiceAttack.

**Comment by Tkael** [comment]
It seems like the event firing when the scan commences should already satisfy your user case?

I haven't tested it, but I believe the raw is made available to VoiceAttack following the same format as any other event variable.
