### ISSUE TITLE
System State always reported as 'None'

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#869]
## EDDI version in which issue found
EDDI v3.1-b1, both with and without VA v1.72

## Steps to reproduce
Use the test script:-
```
{set report system to SystemDetails('Leesti')}}
{reportsystem.state}
```
Or take and complete missions so the 'Mission faction state' is executed.

## Expected
The current state of the system to be reported. i.e. 'Boom', 'Bust' or 'Famine'.

## Observed
The test script always returns 'None' for every system I've tested.
The 'Mission faction state' script is silent.

## Investigation
Originally reported by user Homunk on the Elite forums here:- https://forums.frontier.co.uk/showthread.php/311614-EDDI-Scripts-and-EDDI-enabled-VA-Commands-Thread?p=7064242&viewfull=1#post7064242

T'kael has run the test script and it works for him, but not for Homunk and myself.

When I first tried the new Missions system, I had thought this functionality had just not been added yet, but on closer inspection after Homunk's comment, I found that it was added, but just not working for me.

I've also tried {reportsystem.bodies} and {reportsystem.stations}, but these are blank. {reportsystem.allegiance} does work though.

Let me know if you need any other info, like logs, etc.

**Comment by Darkcyde13** [comment]
I just noticed this:- https://github.com/EDCD/EDDI/commit/2db7e2ac371566e7e6d3ec54a63e556ae28a7bd2

Could this be a fix, already implemented, but just not available yet?

**Comment by Tkael** [comment]
Given that we're getting different results, it's certainly possible. A new beta should be coming out soon...

**Comment by StivlWrith** [comment]
I write here becaus i have same sort of problem
EDDI version in which issue found

EDDI v3.1
Steps to reproduce
Just in a system where state is not none,

make three script for testing and see the problem

first ; **FSD engaged**
```
{_ Context }
{SetState('eddi_context_last_subject', 'fsd')}
{SetState('eddi_context_last_action', 'engage')}
{SetState('eddi_context_system_name', event.system)}
{SetState('eddi_context_system_system', event.system)}
{SetState('eddi_context_fsd_target', event.target)}

{if event.target = 'Hyperspace':
    {_ Rewrite context to represent a jump }
    {SetState('eddi_context_last_subject', 'jump')}
    {SetState('eddi_context_last_action', 'start')}

    {set reportsystem to SystemDetails(event.system)}

    {_ Wait for the FSD countdown and initial jump}
    {Pause(5000)}
 test reportsystem.name {reportsystem.name}...
 tets reportsystem.state {reportsystem.state}...

{set statereport to F("System state report")}
{if statereport:
    Information:  {statereport}
    {Pause(2000)}
}
    
}
```

second : **Jumped** (original version)
```
{_ Context }
{SetState('eddi_context_last_subject', 'jump')}
{SetState('eddi_context_last_action', 'complete')}
{SetState('eddi_context_system_name', system.name)}
{SetState('eddi_context_system_system', system.name)}
{SetState('eddi_context_fuel_remaining', event.fuelremaining)}
{SetState('eddi_context_fuel_used', event.fuelused)}

{F('Fuel check')}

{set statereport to F("System state report")}
{if statereport:
    Information:  {statereport}
    {Pause(2000)}
}

{set system_missions to F("Mission check system")}
{if system_missions:
    {Pause(2000)}
    {system_missions}
}
```

third : **System state report**
```
{_ Fetch from context }
{set reportsystem to SystemDetails(state.eddi_context_system_system)}
On antre dans le script {Emphasize("System state report","strong")}...
 
 nom du système: {reportsystem.name}...
    état du système: {reportsystem.state}...
```

in the _speechresponder.out_ i have

>  test reportsystem.name Naunapitana... tets reportsystem.state Famine... Information: On antre dans le script System state report nom du système: Naunapitana... état du système: Famine... 
> Information: On antre dans le script System state report... nom du système: Naunapitana... état du système: Aucune... 


Investigation:

Perhabs in EDDI.cs, line 1048 (eventJumped) there is many data inside, except the state one.

```
        private bool eventJumped(JumpedEvent theEvent)
        {
            bool passEvent;
            Logging.Debug("Jumped to " + theEvent.system);
            if (CurrentStarSystem == null || CurrentStarSystem.name != theEvent.system)
            {
                // The 'StartJump' event must have been missed
                updateCurrentSystem(theEvent.system);
            }

            passEvent = true;
            CurrentStarSystem.systemAddress = theEvent.systemAddress;
            CurrentStarSystem.x = theEvent.x;
            CurrentStarSystem.y = theEvent.y;
            CurrentStarSystem.z = theEvent.z;

            Faction controllingFaction = new Faction
            {
                name = theEvent.faction,
                Allegiance = theEvent.Allegiance,
                Government = theEvent.Government
            };
            CurrentStarSystem.Faction = controllingFaction;

            CurrentStarSystem.Economies = new List<Economy> { theEvent.Economy, theEvent.Economy2 };
            CurrentStarSystem.securityLevel = theEvent.securityLevel;
            if (theEvent.population != null)
            {
                CurrentStarSystem.population = theEvent.population;
            }
            CurrentStarSystem.visits++;

            // Update to most recent information
            CurrentStarSystem.updatedat = (long)theEvent.timestamp.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
            StarSystemSqLiteRepository.Instance.SaveStarSystem(CurrentStarSystem);

            setSystemDistanceFromHome(CurrentStarSystem);
            setCommanderTitle();

            // After jump has completed we are always in supercruise
            Environment = Constants.ENVIRONMENT_SUPERCRUISE;

            return passEvent;
        }
```
