### ISSUE TITLE
Login triggers the event - Plugin command : '((EDDI cargo updated))' twice in a row

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#873]
## EDDI version in which issue found
EDDI Operational version 3.1.0-b1
VA v1.7.2.24 (prerelease)

## Steps to reproduce
Login/start ED game session -after selecting a play mode
Edit: Complete a cargo mission

1. [give the fullest and most reproducible steps you can]
Happens every time you log into the game and this has been going on for quite some time now. I don't remember exactly when was the first time. Couple weeks ago -or more

## Expected
[describe what you expected to happen]
Login triggers the event - Plugin command : '((EDDI cargo updated))' twice in a row, instead of one.
Edit: Completing a cargo mission can reapeat it 3 times, instead of one.

Just a small inconvenience if/when having a voice comment script for this command

**Comment by Hoodathunk** [comment]
Pr #880 submitted

**Comment by Tkael** [comment]
PR #880 merged.
