### ISSUE TITLE
Mission Warning event reporting wrong expiry

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#875]
## EDDI version in which issue found
EDDI v3.1.0-b2 with and without VA 1.7.2

## Steps to reproduce
Make sure the warning level is set to something over 1440 minutes. This is the minutes in 24 hours.
Accept any mission with a duration of 24 hours (or below the warning level set).

## Expected
The Mission Warning event triggers, and reports the time remaining before expiry.

## Observed
The event triggers every time, warning me that the mission I just picked up will expire, as expected.  However, it only ever reports the number of minutes remaining, and does not report the hours.

I've had it say "in zero minutes", and variations of 59, 58, 55, etc. depending on how long I've been in the mission board before accepting a mission.

## Investigation
I've been taking many missions to test things out, and this was immediately noticeable.  I had accidentally left my warning level set at 8000 minutes after testing the other day, so all missions I had picked up after upgrading EDDI, triggered the Mission Warning event.

Changing the warning level in Mission Monitor tab to less than 1440, and then back to any number higher than this will also trigger the warning event, as expected, so it is easy to test.

So, instead of being told a mission will expire in "23 hours and 37 minutes", I am told it will expire in "37 minutes".  The hours are ignored and not reported.

**Comment by Hoodathunk** [comment]
I did that purposely. My thought was that nobody would want it set greater than 60 min, but you proved me wrong, buddy.

It's an easy change.
