### ISSUE TITLE
Entered Normal Space event incorrectly reporting I'm near my last station

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#876]
## EDDI version in which issue found
EDDI v3.1.0-b2 with and without VA 1.7.2

## Steps to reproduce
Fly to a planetary settlement.
Depart the settlement, and then go fly to another landable body in the same system, one without any ground settlement.

## Expected
As I drop to normal space around an uninhabited body, I get told I have entered normal space near/at the name of the body.

## Observed
I am told that I have entered normal space near the previous settlement on the other body.

## Investigation
I noticed this when I was looking through the change log, and checking out the new changes.  I spotted the logic of the script would produce this situation, so I tested it out to be sure.

In it's current form, the script will always report the last settlement visited, even when you are dropping near a planet that has no settlements on, while you are in the same system as the last settlement you approached.

The settlement variable needs to be cleared after approaching the settlement on the first planet.  Alternatively, create a new variable that gets set and cleared, and use this to check when entering normal space near a settlement (this is similar to how my original script worked).  This way you can keep the last settlement name in it's variable.

The problem will be, when you fly past a planet with a settlement, thus setting the settlement variable, and then landing at an uninhabited planet, as this will also trigger the settlement section.

To solve this in my scripts, I had a timer set in Settlement Approached, and then in Entered Normal Space I check the timer.  If it's over 60 seconds, it's not approaching a settlement after all.

Here's my solution for this.  In Settlement Approached add:-
`{SetState('settlement_approach_time', SecondsSince(0))}`

And in Entered Normal Space, change this:-
```
    {set time to SecondsSince(0) - state.settlement_approach_time}
    {_ If time since last settlement approach is less than 1 minute _}
    {if time < 60:
        {set settlement to state.eddi_context_last_settlement}
        {set station to StationDetails(settlement, event.system)}
        {if station:
            {SetState('eddi_context_body_name', settlement)}
            {OneOf("near", "close to", "in the vicinity of")}
            {station.model}, {P(settlement)}
            {set station_missions to F("Mission check station")}
        }
    |else:
        {OneOf("near", "close to", "in the vicinity of")} planet {P(event.body)}
    }
```
I just tested this and it works fine.

**Comment by Hoodathunk** [comment]
Thanks. I will give some thought to your solution

**Comment by Hoodathunk** [comment]
PR # 881 submitted
