### ISSUE TITLE
EDDI opens multiple log files for a single session

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#879]
## EDDI version in which issue found
3.1-b2 under VA
## Steps to reproduce

1. Launch EDDI
2. Look for log file

## Expected
Logging entries to be contained in eddi.log

## Observed
Log entries contained in several files, eddi.log, eddi1,log, eddi2.log
eddi1.log contained a single line; _2018-10-14T17:22:17 [Info] VoiceAttackPlugin:VA_Init1 Initialising EDDI VoiceAttack plugin_ 

## Investigation
Commenting out `Logging.incrementLogs();` in eddi.cs seems to restore normalcy.

**Comment by Tkael** [comment]
Separating logs from multiple sessions is an intended feature. Creating a log separation when you open EDDI's main window in VoiceAttack is an unintended consequence that we'll have to consider. Thanks.

**Comment by Tkael** [comment]
E.g. `if (!FromVA)  { Logging.Incrementally(); }`. If that disables log incrementing entirely for VA (I can't review the code very effectively from my phone, so I'm not sure), we'll want to add log incrementing to the plugin code.
