### ISSUE TITLE
Material monitor display of ancient data

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#88]
In preparation for 2.4, I also stocked up on the data available at the guardian sites.  In-game, this is displayed as:

![image](https://user-images.githubusercontent.com/25147462/30608756-9dd43a12-9d79-11e7-864b-8d62af73d903.png)

The material monitor shows:

![image](https://user-images.githubusercontent.com/25147462/30608781-b7607a22-9d79-11e7-9dea-fe04d7937c8a.png)

I like the idea of giving the data names such as "historical", but the monitor also needs to display the in-game names to allow the user to make the connection.  So rather than "Ancient historical data: 23", it should show "Ancient historical data (pattern gamma): 23" or "Pattern gamma obelisk data (ancient historical data): 23".  The latter format would have the advantage that the entry would be in the expected place in the sort order.

**Comment by Tkael** [comment]
@richardbuckle I think this is related to https://github.com/EDCD/EDDI/issues/83, which you wanted to look at.

**Comment by richardbuckle** [comment]
This has reverted: my fault.
