### ISSUE TITLE
had a system with famine now any system i enter it as famine even the ones with no one living in the system version using is 3.1.0-b2

### ISSUE THREAD

**Issue by conrad1878** [EDCD/EDDI#883]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Hoodathunk** [comment]
Likely connected to Issue #878. I'm on it.

**Comment by conrad1878** [comment]
thank you for a quick  service brilliant customer service 


-----Original Message-----

**Comment by richardbuckle** [comment]
PR #887 should address this.

**Comment by richardbuckle** [comment]
Yup, fixed by #887
