### ISSUE TITLE
when scanning the Estimated scan value since last docking stops adding planets unless they are big price happened on all versions one using now is version 3.1.0-b2

### ISSUE THREAD

**Issue by conrad1878** [EDCD/EDDI#884]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment]
By default, EDDI doesn't keep a running total of estimated scan values since last docking. Is this something that you are tracking with a script?

**Comment by conrad1878** [comment]
thank you for 5the information at the  moment I am exploring and scanning if it does not do each planet as you say oh well just have to guess what it is excellent customer service   
keep up the work still an excellent tool for Elite com Conrad 1878 -----Original Message-----
