### ISSUE TITLE
Chapter 4: spurious "From NPC" message spoken on start

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#897]
## EDDI version in which issue found
3.0.4 and 3.1-b3

## Steps to reproduce
1. Enable logging to `speechresponder.out`.
2. Launch chapter 1 beta 1 with the default EDDI personality.

## Expected
No spurious messages.

## Observed
EDDI says "From NPC: .".

## Investigation
It seems to be this new journal line:
```
{ "timestamp":"2018-10-30T20:45:07Z", "event":"ReceiveText", "From":"", "Message":"Entered Channel: Shinrarta Dezhra", "Channel":"npc" }
```

**Comment by Tkael** [comment]
I don't see any value in doing more than blocking events which match this pattern. There's no information here that we aren't already gleaning from the journal.
