### ISSUE TITLE
Feature Request : Option to prevent GalNet news from being read automatically

### ISSUE THREAD

**Issue by mwerle** [EDCD/EDDI#905]
## EDDI version in which issue found
3.03

(But also earlier versions)

## Steps to reproduce

1. Start EDDI (either standalone of Voice Attack)

2. If new GalNet articles are available, they will start being read automatically after the summary is said.

3. While playing, if a new GalNet article becomes available, it will be read automatically after it is announced.

## Expected
I'd -prefer- EDDI to alert me to a new GalNet article but NOT read it as soon as it's available. I might be in the middle of a fight or otherwise not able or wanting to listen to it right now.

Make it an option:

- Auto-read articles 
- Notify new articles
- Shut Up!  :)

**Comment by Tkael** [comment]
1. Have you tried disabling or modifying the `Galnet news published` event?
2. Have you reviewed the commands in EDDI.vap for playing back Galnet articles? 
3. Have you reviewed the `shut up` command in EDDI.vap?

**Comment by mwerle** [comment]
1. Yes, that's what I did, but it'd be nice to have it as a "built-in" option.  Perhaps a variable which can be toggled via VA or the GUI and saved?

2. Yes; that's how I'd prefer to read GalNet news. Get a notification when a new articles comes in but then control reading of articles via VA as/when I have time to do so.

3. Yes; but I don't want to have to yell "shut up" every time.

**Comment by Tkael** [comment]
1. Having two different toggles with the same effect is something that we'd like to avoid (from a UI perspective). 
2. You can do that now.
3. Depending on how you modify the `Galnet news published` event, you don't have to.

**Comment by mwerle** [comment]
Ok, sorry, let me backtrack.  Maybe I missed something.  There's already a toggle to enable/disable auto-reading of news articles (WITHOUT manually having to edit the scripts)?

Ie, (2) - "You can do that now" - how?

**Comment by Tkael** [comment]
Disable the `Galnet news published` event in your `Speech Responder` tab. 
![untitled](https://user-images.githubusercontent.com/4382539/47973247-4be76580-e058-11e8-940f-daf7a9839f3e.png)
Then use these commands to control Galnet news reading from VoiceAttack.
![untitled2](https://user-images.githubusercontent.com/4382539/47973293-aed8fc80-e058-11e8-89a2-59f69bee6e2c.png)

**Comment by mwerle** [comment]
"Disable the Galnet news published event in your Speech Responder tab."

But then I would no longer get the "1 new interesting article has been published" notification either, right?  Sorry if I'm being dense here..

**Comment by Tkael** [comment]
You're right, you wouldn't. But you also said that you didn't want to edit scripts and that you didn't want the Galnet Monitor to randomly start speaking in the middle of a fight. Disabling the script and instead asking EDDI via VoiceAttack `Is there any news?` is one way to resolve that concern. 

You can revise the script to choose how much is said by that event, disable it entirely, or even replace the text to speech with a pre-recorded chime if you wish (either in VoiceAttack or via the EDDI {play()} function. But given that most users are not very familiar with the scripting language, it's easier to give users scripts that they can trim down than to expect users to generate scripts they might want on their own. 

The UI is not perfect and there's certainly a learning curve. We've discussed making changes to make the UI more approachable for new users, but creating (for example) `advanced` and `beginner` modes would require some pretty fundamental changes to the way that EDDI operates and we're not ready to make those changes right now - we need to focus on prepping EDDI for chapter 4 instead.

**Comment by richardbuckle** [comment]
Closing as not supported by reports from other users.
