### ISSUE TITLE
EDDI Core: Re-route 'Send EDDI log to developers' button

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#91]
Logs are currently set to be sent to the old server (where we cannot access them). We need to establish a new method for receiving and troubleshooting commander errors from the app.

**Comment by Tkael** [comment]
Perhaps related...
It is possible to initiate & send a github issue programmatically: https://stackoverflow.com/questions/30307781/how-to-automate-add-my-c-sharp-application-issues-to-github-programmatically

**Comment by Tkael** [comment]
I need feedback on how we want to design this moving forward?

**Comment by richardbuckle** [comment]
I'm a bit nervous about putting the log data in a public forum. I'd rather it was restricted to the dev team, but maybe I'm being overly cautious.

**Comment by richardbuckle** [comment]
Just discovered that the button currently deletes the log after sending. I'll disable that for now.
