### ISSUE TITLE
Wrong maximal amounts for material

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#917]
## EDDI version in which issue found
First noticed in 3.0.3, confirmed with 3.1.0-b5

## Steps to reproduce

Collect lots of materials, get surprised by a "material X is above maximum" voice queue, and compare the amount in your inventory with the maximum.

```
Name                            in-game max     EDDI max
(Thargoid) Propulsion Elements  100             200
(Thargoid) Weapon Parts         150             200
Pattern Alpha Obelisk Data      150             200
Pattern Beta Obelisk Data       150             250
Pattern Gamma Obelisk Data      150             300
Polonium                        150             100
Antimony                        150             100
```

## Investigation
As discussed on Discord, I originally had seen more issues, but I still had a tg_<something> listed in the material monitor, so these could have been historical problems.  To verify the current status, I quite EDDI, updated to the latest beta, deleted the materialmonitor.json, restarted EDDI twice to get maximum values in it, and then loaded the game to get the material numbers filled in.

I also took a quick look at the logs, but there is no voice message nor a log message when the amount of material is above the maximum during load.  It seems the voice message is only generated as reaction to a material collected event.

**Comment by Tkael** [comment]
Name | in-game max | EDDI max | In-Game Rarity
------ | --------------- | ------------ | -------
(Thargoid) Propulsion Elements | 100 | 200 | `Rare`
(Thargoid) Weapon Parts | 150 | 200 | `Rare`
Pattern Alpha Obelisk Data | 150 | 200  | `Rare` (per Howard's spreadsheet), even though right panel description claims `Standard`
Pattern Beta Obelisk Data | 150 | 250 | `Rare` (per Howard's spreadsheet), even though right panel description claims `Common`
Pattern Gamma Obelisk Data |150 | 300 | `Rare` (per Howard's spreadsheet), even though right panel description claims `Very common`
Polonium | 150 | 100 | `Rare` (per Howard's spreadsheet and Raw Material Trader), even though right panel description claims `Very rare`
Antimony | 150 | 100 | `Rare` (per Howard's spreadsheet and Raw Material Trader), even though right panel description claims `Very rare`

**Comment by richardbuckle** [comment]
Merged for Chapter4.
