### ISSUE TITLE
Regression: No landing pad info for Orbis station type

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#92]
In 2.4.0-b2, if you request docking at station of type Coriolis, Ocellus, or Asteroid Base, you will get a voice response telling where your pad is.  If you dock at a station of type Orbis, this voice response is missing.

In earlier versions, the voice response was present for Orbis stations as well.

To reproduce, dock at an Ocellus, Coriolis, Asteroid Base, and finally an Orbis.  Voice responses for the first three, no response for the last.

**Comment by Tkael** [comment]
Here's the test script I used to try to replicate this issue:
```
{_ Context }
{SetState('eddi_context_last_subject', 'landing pad')}
{SetState('eddi_context_landing_pad_system', system.name)}
{SetState('eddi_context_landing_pad_station', event.station)}
{SetState('eddi_context_landing_pad_pad', event.landingpad)}

{set station to StationDetails("Mars High", "Sol")}

Acquiring information for {station.name}.

{if station.model = "Coriolis Starport" || station.model = "Orbis Starport" || station.model = "Ocellus Starport" || station.model = "Asteroid Base" || station.model = "Unknown Starport":
    Information acquired.
    {F("Landing pad report")}
}
```
Testing outside of EDDI, this Orbis Station successfully completed the landing pad report. 
In-game, I visited Friend Terminal in the Mitnahas system. The landing pad report functioned there also.

Orbis starports, as a rule, don't appear to have any problems with the landing pad report. There may, however, be another problem at work here (or maybe an issue in EDDN's information for the specific station you visited). Which station were you visiting when this issue presented itself?

**Comment by CMDR-Cometborne** [comment]
Reed's Rest in Merope. I was travelling back and forth between it and Obsidian Orbital for the CG, and I reproducibly got get queue for Obisidian, and not for Reed's Rest.  However, this was not the only station where I noticed this, I will update the bug report when I find further instances.

**Comment by CMDR-Cometborne** [comment]
Oh, and for the records: Problem persists in 2.4.0-b3

**Comment by CMDR-Cometborne** [comment]
The problem just also happened with two stations in Pleiades Sector IR-W d1-55: The Oracle (another Orbis) and Donar's Oak, which is an Ocellus.

Where do you get the data about the station type from? As far as I know, the station type is not in the journal; the only other source I can think of is EDDB, but all three stations are correctly listed there.

I also got a "no population" voice response when jumping into Pleiades Sector IR-W d1-55 and before that HIP 17692, so the problem might be with your data source.

**Comment by Tkael** [comment]
This is part of https://github.com/EDCD/EDDI/issues/97 and is not an issue with EDDI itself but rather with the data source. We'll look into our options for alternate sources.
