### ISSUE TITLE
## EddI v3.03  Unable to upgrade to version 3.1, does not respond to upgrade request

### ISSUE THREAD

**Issue by Sekotser** [EDCD/EDDI#936]
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Sekotser** [comment]
EDDI v30.3, was running as a standalone (although I do also run it with voiceattck)

As soon as I loaded EDDI, it told me that 'v3.01 was available', I pressed the 'upgrade' button and the program froze, task manager said it was not responding

I expected program to upgrade itself

The program just froze and I had to end task via task ,anager

Tried several times to upgrade the program to no avail

**Comment by Tkael** [comment]
Please attach your log file from the attempted upgrade? Logs are located at %appdata%/EDDI.

**Comment by Sekotser** [comment]
Sorry, I deleted the program, and re-installed the updated 3.1.0, so all
good

**Comment by Tkael** [comment]
Ok. I wasn't able to replicate it on my end so I'm going to put it down to some random glitch. Glad you got it working. :-)

**Comment by Sekotser** [comment]
Thanks Bryan
