### ISSUE TITLE
EDDI Core: Auto update the Wiki

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#94]
Currently, the project builds a local copy of the EDDI Wiki when you run tests 'TestGenerateWikiEvents' and 'TestGenerateWikiEventsList'. The local Wiki files then need to be manually added to the repository via git. 

Desired behavior: automatically push the locally generated Wiki files to origin. 

There are likely to be some developer dependencies required for this function (these will need to be documented). For example, install git bash, configure git bash to accept commands from the command prompt, generate and add an ssh key to your git configuration, etc.

**Comment by Tkael** [comment]
Steps to update the wiki currently (with the dependencies noted above already in place):
1. Git command: git clone https://github.com/EDCD/EDDI.git (this pulls the most recent wiki from Github)
1. Git command: cd source/repos
2. Git command: cd EDDI.wiki
3. (Minimize git, then...) Copy and paste the updated wiki files from where they are generated (currently %userprofile%\source\repos\EDDI\Tests\bin\Release\Wiki) into the newly cloned repository (located at %userprofile%\source\repos\EDDI.wiki)
4. (Return to git...) Git Command: git status (checks for differences and displays a list of the updated / changed files)
5. Git Command: git add Events.md (stages the updated wiki index for a commit)
6. Git Command: git add ... (add each of the other changed files to stage them for a commit)
7. Git Command: git commit -m "(Your commit comments here)"
8. Git Command: git push origin master (sends the commit to the origin)

**Comment by richardbuckle** [comment]
Notes:
* the wiki repo to clone is https://github.com/EDCD/EDDI.wiki.git
* be sure to remove the `events` subdir before replacing it with the newly generated copy, so as to clear out any dead wood or renamed files

**Comment by Tkael** [comment]
I think at this juncture this isn't needed. Closing.
