### ISSUE TITLE
Wrong voice response for Unknown Link

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#95]
Versions: 2.4.0-b2 and 2.4.0-b3

When picking up an Unknown Link with an SRV, you get a voice response that you picked up an "Unknown Artefact Three".  The same wrong name is used during the sales check ("You could see your Unknown Artefact Three here").

Related: When I picked up an Unknown Artefact (the original), I got a voice response that I picked up a Thargoid Sensor, so the new name of 2.4.  However, when I pick up Unknown Resin, Unknown Technology Samples, or Unknown Biological Matter, I still get the old names "Unknown X" instead of "Thargoid X".

This probably also applies to the Unknown Probe (unknown_artefact2 in journal terms), but since they do not spawn reliably right now, I could not verify this

**Comment by Tkael** [comment]
All 3 commodities are defined here: https://github.com/EDCD/EDDI/blob/master/DataDefinitions/CommodityDefinitions.cs
It looks like EDDI isn't connecting the dots to the definition included in the file and is instead falling back to the more basic catch-all at the end of the file.
 
Do you have a copy of the journal file from the collectcargo event?

**Comment by CMDR-Cometborne** [comment]
The interesting bit is:

{ "timestamp":"2017-09-23T07:54:02Z", "event":"CollectCargo", "Type":"unknownbiologicalmatter", "Stolen":false }
{ "timestamp":"2017-09-23T07:56:02Z", "event":"CollectCargo", "Type":"UnknownArtifact3", "Stolen":false }
{ "timestamp":"2017-09-23T07:58:15Z", "event":"CollectCargo", "Type":"unknowntechnologysamples", "Stolen":false }

[Journal.170923071536.01.log](https://github.com/EDCD/EDDI/files/1327400/Journal.170923071536.01.log)

You will have to do quite a bit of adding definitions to do because the journal names for a lot of stuff have no obvious connection to the in-game names.  The journal file I attached should have all the thargoid things in either pickup or load events.

One thing while just looking over the code is that you are missing the unknown/thargoid probe, which is your unknown artefact 2.

**Comment by Tkael** [comment]
Ok, I think I'm good. It would have worked as soon as 2.4.0 dropped, but by adding an EDName to the definition it should now be consistent regardless of whether you are running 2.4.0 or an earlier gamer version. Update to be included in the next beta release.
