### ISSUE TITLE
Clean install of 3.1 not working. Installing 3.0.3 and upgrading works.

### ISSUE THREAD

**Issue by DipsoNOR** [EDCD/EDDI#950]
## EDDI version in which issue found
3,1,0

## Steps to reproduce
Install 3.1 on system that has not had Eddi before = Eddi does not start when run. Doesn't even create the config folders.

Install 3.0.3 and upgrade to 3.1 = works fine.

## Expected
Clean install works "out of the box"

## Observed
Unable to run the program from clean 3.1 install.

## Investigation
Installed previous version and updated. Program now starts.

**Comment by Tkael** [comment]
Ah. That's because we were expecting a directory to exist that hadn't been created yet. Sorry about that. In the next release we'll check for that. ;-)

**Comment by richardbuckle** [comment]
I can have the installer create dirs. Just tell me what you need.

**Comment by richardbuckle** [comment]
Yup.
