### ISSUE TITLE
EDDI crashes VoiceAttack

### ISSUE THREAD

**Issue by Roming22** [EDCD/EDDI#957]
## EDDI version in which issue found
3.1.0

## Steps to reproduce
The issue occurs at random moments. Mostly when jumping to a new system, going into supercruise, or changing ship.

## Expected
[describe what you expected to happen]

## Observed
VA crashes, I suspect because EDDI is taking it downp.

## Investigation
I'm not sure where to find the logs for non-steam VA nor EDDI.

**Comment by Tkael** [comment]
You'll find logs at %appdata%/EDDI. Please attach the log from after a crash for review.

**Comment by Tkael** [comment]
If you disable the EDDI plugin, do crashes still occur? Or if you run EDDI as a standalone app? Did you have any custom scripts or VA commands that trigger for the events you mentioned?

**Comment by Tkael** [comment]
Or are you using default scripts only?

**Comment by Roming22** [comment]
I do have a custom profile on top of EDDI. 

Here are some logs that show warnings and errors:

[eddi1.log](https://github.com/EDCD/EDDI/files/2609591/eddi1.log)

[eddi2.log](https://github.com/EDCD/EDDI/files/2609590/eddi2.log)


I'll try disabling the EDDI plugin. I cannot play without VA, as it handles most of my bindings.

**Comment by Tkael** [comment]
Is this a new condition or had it been crashing like this since you installed EDDI?

**Comment by Tkael** [comment]
Have you tried testing any older versions of EDDI to see if they are more stable?

**Comment by Roming22** [comment]
If I remember correctly it always crashed, but the frequency was not as high as of now. I'll try and test with older versions today and see how long it takes before it crashes.

**Comment by Roming22** [comment]
It crashes as well with 2.4.5 (log file contains data for 3.1.0 and 2.4.5)
[eddi.log](https://github.com/EDCD/EDDI/files/2611812/eddi.log)

**Comment by Tkael** [comment]
Do you use custom VA commands? If so, is the default EDDI.vap stable?

**Comment by Roming22** [comment]
Default vap is not stable. Here are some logs.

[eddi1.log](https://github.com/EDCD/EDDI/files/2613206/eddi1.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/2613204/eddi3.log)

**Comment by Tkael** [comment]
It's just old data in the database. Deleting the database and/or re-syncing flight logs from EDSM will help with that.

**Comment by Roming22** [comment]
I tried removing the database, resync with EDSM. It crashed on my first jump.
Would you like me to enable verbose logging?

**Comment by Tkael** [comment]
Yes please. I'm not getting anything useful from standard logs. If you know where your VA crash logs are kept, please provide those too.

**Comment by Roming22** [comment]
Here's the verbose log:
[eddi.log](https://github.com/EDCD/EDDI/files/2622467/eddi.log)

**Comment by Tkael** [comment]
The logs just abruptly end with no indication of a fatal problem. 
Navigate to VoiceAttack's install directory. You'll probably see a file called `VoiceAttackFault.txt`. Attach that here?

**Comment by Roming22** [comment]
I've run a search on my file system and cannot find such a file, even after having VA crash a couple of times.
I've also reconfigured my inputs to be able to use EDDI without VA, and the behavior is the same, EDDI crashes during system jumps.

**Comment by Roming22** [comment]
Closed by mistake

**Comment by Tkael** [comment]
Sorry this is taking a while to figure out. Thank you for being patient.
Do you have any verbose logs from an EDDI standalone crash that we can review?

**Comment by Roming22** [comment]
No problem. If I knew how to setup the dev environment, I could try to debug it, but I've no experience with C# and could not figure it out (and I don't have access to Visual Studio, only VS Code).

The logs from 4 days ago where with the EDDI standalone setup, with verbose on. I believe this is confirmed by the fact that the string `Initialising EDDI VoiceAttack plugin` does not appears in those logs (but it appeared in previous one).

**Comment by Tkael** [comment]
The logs have unfortunately been of no help at all. :-(
There's actually a version of Visual Studios that's free for open source projects and for individuals (we qualify). That's what I use. Link if you want to check it out: https://visualstudio.microsoft.com/downloads/

**Comment by Roming22** [comment]
I'll need you help setting up the dev env.

Here's the procedure I've done:
* Download and install Visual Studio 2017 Community Edition
* Clone the repository in ~/Documents/code/EDDI
* Checkout the `develop` branch
* Open  `EDDI.sln`  in VS2017
* Go to `Tools` - `Nuget Package Manager` - `Package Manager Settings`
* Enable `Allow NuGet to download missing packages`, ` Automatically check for missing packages during build in Visual Studio`, `Allow format selection on first package install`
* Select `PackageReference` as the default package format
* Click `OK`
* `Build` - `Build solution` -> Status bar says `Build succeeded`
* `Debug` - `Start Debugging` -> Error: `A project with an Output Type of Class Library cannot be started directly. In order to debug this project, and an executable project to this solution which references the library project. Set the executable project as the startup project`

**Comment by Roming22** [comment]
As a fallback measure, I ran the EDDI I built, then attached the debugger to the process
This is the error that was raised:
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by Tkael** [comment]
Did you find the `Set as StartUp Project` setting?
![untitled](https://user-images.githubusercontent.com/4382539/49693722-9cf2e980-fb2f-11e8-8671-a3ac51bcd425.png)
Try selecting this prior to building.

As far as the exception is concerned... that looks like it might be EDDI trying to access a system library and either not being able to do so or returning a bad result? 
You've already tried reinstalling EDDI and VoiceAttack. Try following the steps [here](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system), just in case there's a problem with a system file.

**Comment by Roming22** [comment]
Setting `Eddi` as the startup project did the trick.


```
C:\WINDOWS\system32>DISM.exe /Online /Cleanup-image /Restorehealth

Deployment Image Servicing and Management tool
Version: 10.0.17134.1

Image Version: 10.0.17134.407

[==========================100.0%==========================] The restore operation completed successfully.
The operation completed successfully.

C:\WINDOWS\system32>sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.
```

Still crashing. I'm starting to suspec the TTS voice. I'm normally using IVONA Sally, but I'll use the default voice and see if it helps.

**Comment by Roming22** [comment]
OK, the issue is very likely coming from the TTS voice I'm using. I've not experienced a crash since switching to a Microsoft voice.

I'll try reinstalling my voice, but even if it keeps failing, the issue is not on your end.
Thank you very much for the support.

**Comment by Tkael** [comment]
I'm glad you were able to make headway on this. Sorry to hear that Sally is giving you issues (or were you able to fix it by reinstalling the voice?).

**Comment by Roming22** [comment]
Reinstalling the voice seems to have fixed the issue. Thanks again for the support, I'm sorry that long thread was just noise ;)
