### ISSUE TITLE
Habitable Zone values not sane

### ISSUE THREAD

**Issue by Muczachan** [EDCD/EDDI#959]
## EDDI version in which issue found
3.1.0 standalone

## Steps to reproduce

Scan a previously unexplored main sequence star and take care to notice the Habitable Zone ranges.

## Expected
Even for an M-class star, HZ measured in lightseconds. Starting from 0.5 and ranging to 

## Observed
Way to small (0.05 something) values for event.estimatedhabzoneinner noticed. Same for habzoneouter.

## Investigation
Worked in previous version I have used. 3.0.1, or.3 I believe.

**Comment by Muczachan** [comment]
Sure thing.
https://www.edsm.net/en/system/id/30298236/name/Slegi+FI-R+c21-3 HZ was calculated by EDDI to fall from 0.25 to 0.49 lightseconds.

**Comment by Muczachan** [comment]
Also recorded a movie for another star, see for yourself: https://www.youtube.com/watch?v=SAMRSvR4Sv8
(Looks like EDDI is off by 3 orders of magnitude for giving HZ for A-class as 1.2 to 2.4 lightseconds, while it should most probably be 1200 to 2400 lightseconds.)

**Comment by Tkael** [comment]
We used to record stellar radius in meters from the journal and in kilometers from the server. We standardized to kilometers, which appears to have thrown it off by three orders of magnitude. Easy fix. :-)

**Comment by Tkael** [comment]
Fix added to my working branch.
