### ISSUE TITLE
TTS messages can play out of order

### ISSUE THREAD

**Issue by Corysia** [EDCD/EDDI#962]
# TTS messages can play out of order
Release 3.1

##Problem
Currently, events seem to play in a random order when multiple messages are queued, causing a break in immersion due to continuity.
For example, when jumping in to a system and refueling a ship that is starting around 98% full and a good scoop, it's possible to hear the system information about arrival star, hear your ship is fully refueled, and then hear that your ship is at 98% capacity. 

##Suggestion
Queue messages in a FIFO stack rather than what appears to be a randomly ordered list.  

##Improvement
Queue messages in some sort of Tree structure so that newer/updated status messages can replace older/expired messages.   If a key/value pair is made of MessageType:TextOfMessage, it would be possible to replace an older, still-queued message about fuel status with an updated one if the TTS system has not yet popped it off the queue.

**Comment by richardbuckle** [comment]
In my play testing, the next 3.3 release will fix this.
