### ISSUE TITLE
miss ident variable for ship in page EDDI Variables

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#964]
## EDDI version in which issue found
3.1

## Steps to reproduce

Open variables window when we are in "edit script"

## Expected
see what to put to have ship ID

## Observed
finaly find that it is {ship.ident}

**Comment by Tkael** [comment]
Documented on my working branch.

**Comment by StivlWrith** [comment]
Sorry for my lack in english but I don't understand the meaning of what you write with 

> Documented on my working branch.

It is that you have already see the problem and it is write somewhere that you work on it, or is that you saw the message and noted this to do with the work schedule?

**Comment by Tkael** [comment]
It's fixed on the branch I'm working on and will PR soon.
