### ISSUE TITLE
New feature request - play .mp3 and/or run .bat files from Cottle

### ISSUE THREAD

**Issue by r00tbypass** [EDCD/EDDI#965]
This is not an issue per-say how ever a feature implementation.
if its possible for EDDI to play mp3 files or .bat files, or both would appreciate it

**Comment by Darkcyde13** [comment]
Could you give a use case scenario?  How would you find these features useful?  To add these to EDDI would need a good reason.

**Comment by Hoodathunk** [comment]
There is already a Cottle function to play .wav files. I don't think it's too much of a stretch to want .mp3 compatibility. Right now, it's mainly a matter of amount of effort required and priorities.

**Comment by r00tbypass** [comment]
i understand the effort involved and the your priorities, i'm not asking for it right now, maybe in the near future?
the use case is to get a better voiced AI its a preference matter not all of us like listening to the TTS
i know about the wav files but for some reason when i convert mp3 to wav it loses quality.
the mp3 is not as important as the launch a program when you an event is triggered.
i'm using a program called voicemacro (for me its faster than voiceattack with response) and i can make small bat scripts to make the program start a macro, that's why i need to launch a .bat files from EDDI how ever i understand you're mainly busy with the beyond patch that's why i'm not really in a rush but it would be helpful to have these features as i am working on scripting this myself (another program that's like EDDI which responds to journal events) but i can see why adding something that's already there is pointless i would help out and do it myself if i had any C# or cottle experience unfortunately i only know python, but if you're willing to do this in the future and consider it please let me know since i am already working on a different solution, again i understand if those features are not needed

**Comment by Tkael** [comment]
.wav files are supported via ssml but .mp3 files are not. We'd need a different playback mechanism then we currently use.

**Comment by richardbuckle** [comment]
Closing due to lack of support.
