### ISSUE TITLE
((EDDI location)) only triggering at startup

### ISSUE THREAD

**Issue by punkerich** [EDCD/EDDI#966]
## EDDI version in which issue found
3.1.0
## Steps to reproduce

1. start game, open mode, ((EDDI location)) event in VA is fired
2. quit to main menu
3. continue game, solo mode, (EDDI location)) event in VA is not fired, despite appearing in ED journal

## Expected
((EDDI location)) firing in VA on every appearance of the event in ED journal

Been docked at a station at that time.

**Comment by Hoodathunk** [comment]
This is intentional. Waaaay back in jgm's day, mission stackers complained about getting the notification repeatedly while 'mode switching', and jgm added code to ignore subsequent game sessions when docked at the same station.

Still seems reasonable to me.

**Comment by Tkael** [comment]
Mission stacking is not the only reason for switching game modes. It's also a way to refresh the environment you are in (e.g. Guardian ruins or Dav's Hope, for example). That said, switching game modes should go way down with the 3.3 release.
Let's place this on hold until after 3.3 is released and then re-evaluate.

**Comment by Hoodathunk** [comment]
Addressed by PR #1282.
