### ISSUE TITLE
[REQ] Commander name variable

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#967]
¿It's possible on a new EDDI versions have a "Name Commander: " in "Commander Details" section for use it with a VoiceAttack and EDDI variables?

Thank you and sorry if this section it's only for Issues. This 3.1 version is awesome :)

**Comment by Tkael** [comment]
Or are you looking for ipa support to be able to customize the pronunciation of commander names?

**Comment by hoksilato2** [comment]
Sorry my fault. I searched into wiki but i didn't found it. You can close this issue.
