### ISSUE TITLE
Modification crafted, no blueprint name

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#970]
## EDDI version in which issue found
EDDI 3.1.1 standalone on ED3.2 (not the beta)

## Steps to reproduce
Make an ingeneer modification with this little script
```
L'ingénieur est {event.engineer}. la recette est {event.blueprint} de grade {event.level}..
{set NbreMaterial to len(event.materials)} 

On utilise {NbreMaterial} matériaux de construction
```

## Expected
To have an answer like
L'ingénieur est '_engeneer name_'. la recette est '_blueprint name_' de grade _'x_'.
On utilise '_y_' matériaux de construction
## Observed
[describe what happened instead] the answer i have:

> L'ingénieur est _Hera Tani_. la recette est de grade _2_. On utilise _2_ matériaux de construction

## Investigation
I look in the logs, EDDI seem to use old fashion one like 
`{ "timestamp":"2017-08-06T22:38:40Z", "event":"EngineerCraft", "Engineer":"Hera Tani", "Blueprint":"Sensor_Sensor_LightWeight", "Level":2, "Ingredients":[ { "Name":"salvagedalloys", "Count":1 }, { "Name":"manganese", "Count":1 } ] }`

the actual one is like that
`{ "timestamp":"2018-12-01T16:53:06Z", "event":"EngineerCraft", "Slot":"MediumHardpoint3", "Module":"hpt_multicannon_gimbal_medium", "Ingredients":[ { "Name":"conductiveceramics", "Name_Localised":"Conducteurs en céramique", "Count":1 }, { "Name":"protolightalloys", "Name_Localised":"Proto-alliages légers", "Count":1 }, { "Name":"protoradiolicalloys", "Name_Localised":"Proto-alliages radiologiques", "Count":1 } ], "Engineer":"Tod 'The Blaster' McQuinn", "EngineerID":300260, "BlueprintID":128673494, "BlueprintName":"Weapon_LightWeight", "Level":5, "Quality":0.240000, "Modifiers":[ { "Label":"Mass", "Value":0.856000, "OriginalValue":4.000000, "LessIsGood":1 }, { "Label":"Integrity", "Value":20.400000, "OriginalValue":51.000000, "LessIsGood":0 }, { "Label":"PowerDraw", "Value":0.432384, "OriginalValue":0.640000, "LessIsGood":1 }, { "Label":"DistributorDraw", "Value":0.096250, "OriginalValue":0.140000, "LessIsGood":1 } ] }`

More data and nomore "Blueprint", it is now "BlueprintName"

**Comment by Tkael** [comment]
Thanks. It looks like FDev changed this some time ago but didn't update their documentation to note the change.
