### ISSUE TITLE
Translation into German erroneous / VA does not use some variables

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#973]
## EDDI version in which issue found
3.1.1

## Steps to reproduce
... after the update to version 3.1.1

Some variables for VA have no value. {TXT:Ship name} and {TXT:Ship ident} are "not set"
variable {TXT:Ship model} is OK

Example for translation: In the German translation "Schubdüsen" are again "thrusters"

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
With Version 3.1 EDDI works fine. All variables are detected by VA.
The German translation works well.

**Comment by Tkael** [comment]
3.1.1 is a very minor release that touched neither the ship monitor nor VoiceAttack. Most of the changes are just incorporating the latest translations from the community.

You may have a corrupted shipmonitor.json, or EDDI may have had trouble reading from your files? Do you have more than one account with Elite Dangerous?

Go to `%appdata%/EDDI` and delete `shipmonitor.json` while EDDI is not running to reset your ship monitor configuration. EDDI will rebuild your ship monitor after it next starts.

**Comment by Tkael** [comment]
Please let us know if deleting and refreshing your `shipmonitor.json` fixed the issue? Thanks!

**Comment by nepomuk16321** [comment]
Okay, I'll test it tomorrow. I was on a business trip for two days.
Thanks for the tip.
