### ISSUE TITLE
System Visit totals reset

### ISSUE THREAD

**Issue by rodan123** [EDCD/EDDI#979]
## EDDI version in which issue found
3.1.1 running under Voice Attack

## Steps to reproduce

1. Jump back and forth between two systems, noting system visits
2. After a few jumps the visit total resets to 1

## Expected
Visit total increments with each jump into a system 
## Observed
Visit total resets to first visit

## Investigation
Worked fine with EDDI 3.1-b4, hasn't worked properly with any release since.

**Comment by rootwalla** [comment]
I was just going to post about how since 3.0 (or there about) all SystemDetails(event.system).visits is 0 for me in every system I enter.

I've tried re-obtaining the EDSM log and the issue persists.

**Comment by Tkael** [comment]
If you are not running version 3.1.2, please update to version 3.1.2 and re-sync flight logs from EDSM. 
If the issue recurs, please post the applicable log file from `%APPDATA%/EDDI` to this issue for review.

**Comment by rodan123** [comment]
Updated to 3.1.2 and did a resync to EDSM.
Running the current CG. Been to Zlota several times. After leaving, making a rares circuit and returning, EDDI thought that it was my first visit to the system. Loads of errors in the logfile. Seems every system I  docked at threw a _Problem reading data for star system … from database, re-obtaining from source._
Systems that I just passed through didn't throw that error in the log, Don't know if that is relevant,

Log file attached.

[eddi.log](https://github.com/EDCD/EDDI/files/2660368/eddi.log)

**Comment by rootwalla** [comment]
You should also note that the discount report is not working either, it keeps reporting savings on modules that were purchased at 15%.

**Comment by Tkael** [comment]
@rootwalla Please stay on topic... open a new ticket if you'd like us to investigate the discount report. Provide as much detail as you can, including a copy of your shipmonitor.json and notes identifying the specific ship and module that you believe need our attention. 

This ticket needs to stay focused on the original system.visits issue.

**Comment by Tkael** [comment]
I found an issue with the json parsing for EconomyShares upon docking at Zlota for the cg and corrected it in my working branch. This may have been the root cause, since I've been trading out of Zlota all afternoon with no visit count resets.

**Comment by Tkael** [comment]
That was my solution too. Simple fix, hopefully effective.
