### ISSUE TITLE
List of mispronounced names

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#98]
This issue is to record any mispronunciations as I come across them.

* Hyades
* Merope
* Sterope
* Asterope
* Pleione
* Celaeno
* Conn (gets expanded to "Connecticut" LOL)

Star classes

* Supergiant

Commodities 

* Biowaste

Stations

* Jaques (Ivona Amy pronounces like `Dukes` or `Jukes`)

Other

* Thargoid

**Comment by Tkael** [comment]
Eta Draconis

**Comment by Tkael** [comment]
Thargoid

**Comment by clinkingdog** [comment]
Phanes

(I just came across that today.)

**Comment by Eclipse-73** [comment]
I'm getting a mispronunciation of planets with the 2c listing, makes it say "two degrees celsius" at the end. It's possible then that any 'number+c' combo will have this effect.
If it's of any help I noticed this in the Caelottixa system.

**Comment by richardbuckle** [comment]
Thanks. I’ve also noticed “2g” being pronounced as “two grams” and “2h” as “two hours”. We’ll see if we can work around that.

**Comment by Taomyn** [comment]
Any news on a user-configurable table of pronunciations? Always make smile when I return to Vesper-M4 and dock at Sluff Orbital instead of Slough Orbital. Would be nice to correct some other names and places as well.

**Comment by richardbuckle** [comment]
A bit more research is needed. I had initially hoped (#140) to implement this as an industry-standard lexicon file, which should give the best performance and avoid the need to use the `P()` function -- which in itself uses a rather naive implementation that won't scale well. However lexicon support doesn't seem to be 100% across all voices.

**Comment by arancaytar** [comment]
Commodity: Praseodymium

(pray-zhao-dim-ium should be pray-zeo-dim-ium)

**Comment by k5jat** [comment]
Rank: Ensign

**Comment by BarWeinig** [comment]
- Name: "Sagan"
Should probably be pronounced as Carl Sagan's last name...

- NPC message: "unauthorized"
There is a game generated message (around stations) that is read by EDDI, ending in the line: "stop your unauthorized scan". EDDI pronounces it as "stop your unauthoreazed scan".

**Comment by Tkael** [comment]
Remember to state the voice that is mispronouncing the word (to help us replicate what you are observing), as pronunciation is handled by the voice software unless EDDI provides am override pronunciation.

**Comment by BarWeinig** [comment]
Added it to the original message.
Will delete this message if I see Tkeal post again.

**Comment by arancaytar** [comment]
Just noticed that the Windows TTS "Hazel" voice pronounces Galnet like a French loanword with a silent t ("Galnay").

**Comment by richardbuckle** [comment]
> 
> 
> Just noticed that the Windows TTS "Hazel" voice pronounces Galnet like a French loanword with a silent t ("Galnay").

Yes. Capitalising the 'N' ("GalNet") fixes that.

**Comment by arancaytar** [comment]
Thanks!

Back to actual names, "Aachen Town" station in Alioth system is mispronounced "chen town" (/t͡ʃən/) by Hazel.

Not sure what an acceptable pronunciation would be, but assuming it is the same as the German town, it'd be /ˈɑːxən/.

**Comment by arancaytar** [comment]
The minor faction `Minutemen` (https://www.edsm.net/en/faction/id/2035/name/Minutemen) is pronounced as Minnuh-tea-men (by Hazel).

**Comment by Tkael** [comment]
Where appropriate, mispronounced system, station, and faction names have been added to the P() function.
#2222 enables user lexicons which should help with any remaining pronunciation issues.

Since I primarily use Ivona Amy, I've zipped up a copy of my lexicon file from `C:\ProgramData\RS_S2G_VP` (the equivalent location on your PC may vary depending on install settings and the company you purchased from) and posted it here to help other Ivona users get started with their lexicon.

[Amy.zip](https://github.com/EDCD/EDDI/files/6875337/Amy.zip)
