### ISSUE TITLE
orbis and megaship missing

### ISSUE THREAD

**Issue by StivlWrith** [EDCD/EDDI#981]
## EDDI version in which issue found
3.1.2 standalone

## Steps to reproduce

problem in script each time it's about orbis or megaship : no translation, just in english for these two

## Investigation
Missing orbs and megaship in StationModels.de.resx StationModels.es.resx StationModels.it.resx and StationModels.fr.resx in 3.1.2 although they are present in version 3.1.
translation problem for these 2 stations or a small error?

**Comment by Tkael** [comment]
Hi @StivlWrith, it looks like a change to the English names made in version 3.1.1 may have caused CrowdIn to automatically discard the translations.
We've restored the original English names in 3.1.2 and I've submitted a pull request to restore all of the missing translations.

**Comment by Tkael** [comment]
Of course, the translators are also on top of it. :-)
