### ISSUE TITLE
EDDI constantly uploading data

### ISSUE THREAD

**Issue by jimbot70** [EDCD/EDDI#988]
## EDDI version in which issue found
3.1.2 either standalone or through VA

## Steps to reproduce

Launch EDDI, log into Elite and wait a few seconds.

## Expected
EDDI works as normal

## Observed
After logging into Elite EDDI begins uploading to 35.201.81.77.bc.googleusercontent.com or 77.81.201.35.bc.googleusercontent.com and continues to upload until I quit EDDI or Voice Attack. 
I left EDDI running while I went out and when I came back 5 hours later it was still sending the same data.![image](https://user-images.githubusercontent.com/27317086/49748530-8a7dca80-fc6b-11e8-88d6-92f3278b6ec9.png)

Even after quitting Elite entirely it still is sending this data.

## Investigation
I've tried downgrading to 3.1.0(the version I had before upgrading to 3.1.2 and this starting) and 3.1.1, fully reinstalling EDDI and Voice Attack and two different computers.  Looking at wireshark shows the same data being sent on loop every half a second or so.
![image](https://user-images.githubusercontent.com/27317086/49748636-db8dbe80-fc6b-11e8-9fdb-95b480980727.png)

Disabling every plugin also has no effect on this uploading happening or not.

**Comment by Hoodathunk** [comment]
This is expected. We use a trusted error tracking service called Rollbar. It allows us to be proactive in addressing exceptions and such in our codebase.

**Comment by Tkael** [comment]
And we send data to EDDN and EDSM if you have plugins for those services enabled.

**Comment by jimbot70** [comment]
Is there any way to disable this(not the EDDN/EDSM plugins because while they do upload it's not constantly even without the game running)?  Our internet is slow as hell and constantly using 1/3rd of our upload speed while playing Elite slows everything else down.

**Comment by richardbuckle** [comment]
While connections to Rollbar are expected, bandwidth should only be consumed when errors occur. In normal usage there shouldn't be any traffic. We will look into this.

**Comment by Tkael** [comment]
Can you share a copy of your logs? We'd like to see what data EDDI is trying to send.

**Comment by Tkael** [comment]
Logs are located at `%appdata%\EDDI`.

**Comment by jimbot70** [comment]
[eddi.log](https://github.com/EDCD/EDDI/files/2665782/eddi.log)
Latest of my logs.

**Comment by rodan123** [comment]
Ever consider an "opt-out" option for Rollbar?

**Comment by Tkael** [comment]
This probably was improved by the changes we made in 3.3.1. Please let us know if data consumption is still an issue - we'll see your updates and re-open this issue if needed.

**Comment by jimbot70** [comment]
It has been fine since Elite 3.3 was released.
