### ISSUE TITLE
Little problem: ((EDDI: ship compartment variables)) are not right (Type-9)

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#991]
## Steps to reproduce

Comparison with ship equipment in dock
for example
![image](https://user-images.githubusercontent.com/20616775/49770288-13d0e380-fce4-11e8-9868-83d7d1bec4fd.png)
...
the two biggest slots are 8th

a built-in docking computer is not recognized or listed

**Comment by Tkael** [comment]
Verify that the ship name is correct. If not, EDDI may be mixing up data from ships (this can happen if you load EDDI after you are already in game).
Re-logging back into the game from the main menu may correct it.

**Comment by nepomuk16321** [comment]
You're right. After a new start everything was ok again.

Thx nepomuk :-)
